CREATE TABLE MELANBIDE_DOKUSI_RELDOC_EXTNOT 
(
  RELDOC_ID_DOC_EXTERNO NUMBER(19, 0) NOT NULL,
  RELDOC_OID VARCHAR2(100) NOT NULL , 
  CONSTRAINT MELANBIDE_DOKUSI_RELDOC_E_PK PRIMARY KEY (RELDOC_OID)
  ENABLE 
);

