--------------------------------------------------------
--  DDL for Table MELANBIDE67_SUBV_CENTROS
--------------------------------------------------------
  CREATE TABLE "MELANBIDE67_SUBV_CENTROS" 
   (	"ANIO" NUMBER(4,0), 
	"IMP_OFER_CAPTADAS_REG" NUMBER(5,0), 
	"IMP_OFER_GESTIONADAS" NUMBER(5,0), 
	"NUM_CONTRATOS_INCR" NUMBER(8,0), 
	"PORC_INCREMENTO" NUMBER(5,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLBPRU_DBS1" ;
   COMMENT ON COLUMN "MELANBIDE67_SUBV_CENTROS"."ANIO" IS 'Año de la convocatoria';
   COMMENT ON COLUMN "MELANBIDE67_SUBV_CENTROS"."IMP_OFER_CAPTADAS_REG" IS 'Número de ofertas captadas y registradas';
   COMMENT ON COLUMN "MELANBIDE67_SUBV_CENTROS"."IMP_OFER_GESTIONADAS" IS 'Número de ofertas gestionadas';
   COMMENT ON COLUMN "MELANBIDE67_SUBV_CENTROS"."NUM_CONTRATOS_INCR" IS 'Número de contratos a partir de los cuales se incrementa porcentualmente la subvención';
   COMMENT ON COLUMN "MELANBIDE67_SUBV_CENTROS"."PORC_INCREMENTO" IS 'Porcentaje de incremento sobre subvención estándar en función del número de contratos gestionados.';
REM INSERTING into MELANBIDE67_SUBV_CENTROS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index MELANBIDE67_SUBV_CENTROS_PK
--------------------------------------------------------
  CREATE UNIQUE INDEX "MELANBIDE67_SUBV_CENTROS_PK" ON "MELANBIDE67_SUBV_CENTROS" ("ANIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLBPRU_DBS1" ;
--------------------------------------------------------
--  Constraints for Table MELANBIDE67_SUBV_CENTROS
--------------------------------------------------------
  ALTER TABLE "MELANBIDE67_SUBV_CENTROS" MODIFY ("IMP_OFER_GESTIONADAS" NOT NULL ENABLE);
  ALTER TABLE "MELANBIDE67_SUBV_CENTROS" MODIFY ("IMP_OFER_CAPTADAS_REG" NOT NULL ENABLE);
  ALTER TABLE "MELANBIDE67_SUBV_CENTROS" MODIFY ("ANIO" NOT NULL ENABLE);
  ALTER TABLE "MELANBIDE67_SUBV_CENTROS" ADD CONSTRAINT "MELANBIDE67_SUBV_CENTROS_PK" PRIMARY KEY ("ANIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLBPRU_DBS1"  ENABLE;


