--------------------------------------------------------
--  DDL for Table MELANBIDE67_SUBV_EMPRESAS
--------------------------------------------------------
  CREATE TABLE "MELANBIDE67_SUBV_EMPRESAS" 
   (	"ANIO" NUMBER(4,0), 
	"TITULACION" VARCHAR2(2 BYTE), 
	"RETRIBUCION" NUMBER(15,2), 
	"CONTR_PRACT_6_MESES" NUMBER(15,2), 
	"CONTR_PRACT_12_MESES" NUMBER(15,2), 
	"CONTR_INDEF" NUMBER(15,2), 
	"INCR_MUJER_SUBREPRES" NUMBER(5,2), 
	"PORC_PAGO_1" NUMBER(5,2), 
	"PORC_PAGO_2" NUMBER(5,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLBPRU_DBS1" ;
   COMMENT ON COLUMN "MELANBIDE67_SUBV_EMPRESAS"."ANIO" IS 'Año de la convocatoria';
   COMMENT ON COLUMN "MELANBIDE67_SUBV_EMPRESAS"."TITULACION" IS 'Titulación del trabajador';
   COMMENT ON COLUMN "MELANBIDE67_SUBV_EMPRESAS"."RETRIBUCION" IS 'Retribución bruta anual mínima incluidas las pagas extra';
   COMMENT ON COLUMN "MELANBIDE67_SUBV_EMPRESAS"."CONTR_PRACT_6_MESES" IS 'Contrato en prácticas, subvención por 6 meses';
   COMMENT ON COLUMN "MELANBIDE67_SUBV_EMPRESAS"."CONTR_PRACT_12_MESES" IS 'Contrato en prácticas, subvención por 12 meses';
   COMMENT ON COLUMN "MELANBIDE67_SUBV_EMPRESAS"."CONTR_INDEF" IS 'Subvención por contrato indefinido';
   COMMENT ON COLUMN "MELANBIDE67_SUBV_EMPRESAS"."INCR_MUJER_SUBREPRES" IS 'Incremento porcentual sobre los importes cuando el contrato se firme con una mujer con subrepresentación en el puesto de trabajo';
   COMMENT ON COLUMN "MELANBIDE67_SUBV_EMPRESAS"."PORC_PAGO_1" IS 'Porcentaje sobre el importe total para el primer pago';
   COMMENT ON COLUMN "MELANBIDE67_SUBV_EMPRESAS"."PORC_PAGO_2" IS 'Porcentaje sobre el importe total para el segundo pago';
REM INSERTING into MELANBIDE67_SUBV_EMPRESAS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index MELANBIDE67_SUBV_EMPRESAS_PK
--------------------------------------------------------
  CREATE UNIQUE INDEX "MELANBIDE67_SUBV_EMPRESAS_PK" ON "MELANBIDE67_SUBV_EMPRESAS" ("ANIO", "TITULACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLBPRU_DBS1" ;
--------------------------------------------------------
--  Constraints for Table MELANBIDE67_SUBV_EMPRESAS
--------------------------------------------------------
  ALTER TABLE "MELANBIDE67_SUBV_EMPRESAS" ADD CONSTRAINT "MELANBIDE67_SUBV_EMPRESAS_PK" PRIMARY KEY ("ANIO", "TITULACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLBPRU_DBS1"  ENABLE;
  ALTER TABLE "MELANBIDE67_SUBV_EMPRESAS" MODIFY ("INCR_MUJER_SUBREPRES" NOT NULL ENABLE);
  ALTER TABLE "MELANBIDE67_SUBV_EMPRESAS" MODIFY ("CONTR_INDEF" NOT NULL ENABLE);
  ALTER TABLE "MELANBIDE67_SUBV_EMPRESAS" MODIFY ("CONTR_PRACT_12_MESES" NOT NULL ENABLE);
  ALTER TABLE "MELANBIDE67_SUBV_EMPRESAS" MODIFY ("CONTR_PRACT_6_MESES" NOT NULL ENABLE);
  ALTER TABLE "MELANBIDE67_SUBV_EMPRESAS" MODIFY ("RETRIBUCION" NOT NULL ENABLE);
  ALTER TABLE "MELANBIDE67_SUBV_EMPRESAS" MODIFY ("TITULACION" NOT NULL ENABLE);
  ALTER TABLE "MELANBIDE67_SUBV_EMPRESAS" MODIFY ("ANIO" NOT NULL ENABLE);


