DROP TABLE MELANBIDE67_EMPRESAS;
--------------------------------------------------------
--  DDL for Table MELANBIDE67_EMPRESAS
--------------------------------------------------------
  CREATE TABLE "MELANBIDE67_EMPRESAS" 
   (	"ID" NUMBER(8,0), 
	"NUM_EXP" VARCHAR2(20 BYTE), 
	"COD_PUESTO" NUMBER(8,0), 
	"NOMBRE_PUESTO_SOL" VARCHAR2(100 BYTE), 
	"APELLIDO1" VARCHAR2(50 BYTE), 
	"APELLIDO2" VARCHAR2(50 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"IMPORTE_SUBV_SOL" NUMBER(15,2), 
	"IMPORTE_SUBV_EST" NUMBER(15,2), 
	"IMPORTE_SUBV_OFE" NUMBER(15,2), 
	"REINTEGROS" NUMBER(15,2), 
	"IMPORTE_TOTAL" NUMBER(15,2), 
	"SALARIO_SOL" NUMBER(15,2), 
	"SALARIO_OFE" NUMBER(15,2), 
	"SEXO_SOL" VARCHAR2(1 BYTE), 
	"SEXO_OFE" VARCHAR2(1 BYTE), 
	"DPTO_SOL" VARCHAR2(50 BYTE), 
	"DPTO_OFE" VARCHAR2(50 BYTE), 
	"TITULACION_SOL" VARCHAR2(50 BYTE), 
	"TITULACION_OFE" VARCHAR2(50 BYTE), 
	"MODALIDAD_SOL" VARCHAR2(50 BYTE), 
	"MODALIDAD_OFE" VARCHAR2(50 BYTE), 
	"JORNADA_LAB_SOL" NUMBER(5,2), 
	"JORNADA_LAB_OFE" NUMBER(5,2), 
	"CENTRO_TRAB_SOL" VARCHAR2(100 BYTE), 
	"CENTRO_TRAB_OFE" VARCHAR2(100 BYTE), 
	"CTA_COTIZ_SOL" VARCHAR2(20 BYTE), 
	"CTA_COTIZ_OFE" VARCHAR2(20 BYTE), 
	"FEC_INI_CONTR_SOL" DATE, 
	"FEC_INI_CONTR_OFE" DATE, 
	"FEC_FIN_CONTR_SOL" DATE, 
	"FEC_FIN_CONTR_OFE" DATE, 
	"GRUPO_COTIZ_SOL" VARCHAR2(50 BYTE), 
	"GRUPO_COTIZ_OFE" VARCHAR2(50 BYTE), 
	"CONVENIO_COL_SOL" VARCHAR2(100 BYTE), 
	"CONVENIO_COL_OFE" VARCHAR2(100 BYTE), 
	"OBSERVACIONES" VARCHAR2(2500 BYTE), 
	"DNI_TRAB" VARCHAR2(25 BYTE), 
	"FEC_NACIMIENTO" DATE, 
	"NUM_OFERTA" VARCHAR2(25 BYTE), 
	"CENTRO_COL_GESTION" VARCHAR2(25 BYTE), 
	"CENTRO_COL_CAPTACION" VARCHAR2(25 BYTE), 
	"IMP_PAGO_1" NUMBER(15,2), 
	"IMP_PAGO_2" NUMBER(15,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLBPRU_DBS1" ;
   COMMENT ON COLUMN "MELANBIDE67_EMPRESAS"."ID" IS 'Identificador secuencial del registro';
   COMMENT ON COLUMN "MELANBIDE67_EMPRESAS"."NUM_EXP" IS 'Número de expediente';
   COMMENT ON COLUMN "MELANBIDE67_EMPRESAS"."COD_PUESTO" IS 'Código de puesto solicitado';
   COMMENT ON COLUMN "MELANBIDE67_EMPRESAS"."NOMBRE_PUESTO_SOL" IS 'Nombre del puesto';
   COMMENT ON COLUMN "MELANBIDE67_EMPRESAS"."APELLIDO1" IS 'Primer apellido del trabajador';
   COMMENT ON COLUMN "MELANBIDE67_EMPRESAS"."APELLIDO2" IS 'Segundo apellido del trabajador';
   COMMENT ON COLUMN "MELANBIDE67_EMPRESAS"."NOMBRE" IS 'Nombre del trabajador';
   COMMENT ON COLUMN "MELANBIDE67_EMPRESAS"."IMPORTE_SUBV_SOL" IS 'Importe de la subvención solicitado para el puesto (solicitado)';
   COMMENT ON COLUMN "MELANBIDE67_EMPRESAS"."IMPORTE_SUBV_EST" IS 'Importe de la subvención estimado para el puesto (estimado por el sistema)';
   COMMENT ON COLUMN "MELANBIDE67_EMPRESAS"."IMPORTE_SUBV_OFE" IS 'Importe de la subvención real para el puesto (oferta o final calculado por el sistema)';
   COMMENT ON COLUMN "MELANBIDE67_EMPRESAS"."REINTEGROS" IS 'Importe de los reintegros';
   COMMENT ON COLUMN "MELANBIDE67_EMPRESAS"."IMPORTE_TOTAL" IS 'Importe de la subvención por puesto (importe real - reintegros)';
   COMMENT ON COLUMN "MELANBIDE67_EMPRESAS"."SALARIO_SOL" IS 'Salario bruto anual en la solicitud, pagas incluídas y excluídos costes de SS';
   COMMENT ON COLUMN "MELANBIDE67_EMPRESAS"."SALARIO_OFE" IS 'Salario bruto anual en la oferta o contrato, pagas incluídas y excluídos costes de SS';
   COMMENT ON COLUMN "MELANBIDE67_EMPRESAS"."SEXO_SOL" IS 'Sexo del trabajador (solicitado)';
   COMMENT ON COLUMN "MELANBIDE67_EMPRESAS"."SEXO_OFE" IS 'Sexo del trabajador (oferta o contrato)';
   COMMENT ON COLUMN "MELANBIDE67_EMPRESAS"."DPTO_SOL" IS 'Departamento donde se desarrollará el puesto de trabajo (solicitado)';
   COMMENT ON COLUMN "MELANBIDE67_EMPRESAS"."DPTO_OFE" IS 'Departamento donde se desarrollará el puesto de trabajo (oferta o contrato)';
--------------------------------------------------------
--  DDL for Index MELANBIDE67_EMPRESAS_PK
--------------------------------------------------------
  CREATE UNIQUE INDEX "MELANBIDE67_EMPRESAS_PK" ON "MELANBIDE67_EMPRESAS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLBPRU_DBS1" ;
--------------------------------------------------------
--  Constraints for Table MELANBIDE67_EMPRESAS
--------------------------------------------------------
  ALTER TABLE "MELANBIDE67_EMPRESAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MELANBIDE67_EMPRESAS" MODIFY ("NUM_EXP" NOT NULL ENABLE);
  ALTER TABLE "MELANBIDE67_EMPRESAS" MODIFY ("COD_PUESTO" NOT NULL ENABLE);
  ALTER TABLE "MELANBIDE67_EMPRESAS" ADD CONSTRAINT "MELANBIDE67_EMPRESAS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLBPRU_DBS1"  ENABLE;
  ALTER TABLE MELANBIDE67_EMPRESAS ADD COD_TIPO_NIF VARCHAR2(8 BYTE) ;  
