ALTER TABLE CME_PUESTO ADD (
  CME_PTO_GASTOS_SEG NUMBER(10,2),
  CME_PTO_GASTOS_VIS NUMBER(10,2),
  CME_PTO_GASTOS_SOL_SEG NUMBER(10,2),
  CME_PTO_GASTOS_SOL_VIS NUMBER(10,2)
);

ALTER TABLE CME_JUSTIFICACION ADD (
  CME_JUS_GASTOS_SEG NUMBER(10,2),
  CME_JUS_GASTOS_VIS NUMBER(10,2)
);

ALTER TABLE CME_HIST_PUESTO ADD (
  CME_PTO_GASTOS_SEG NUMBER(10,2),
  CME_PTO_GASTOS_VIS NUMBER(10,2)
);

ALTER TABLE CME_HIST_JUSTIFICACION ADD (
  CME_JUS_GASTOS_SEG NUMBER(10,2),
  CME_JUS_GASTOS_VIS NUMBER(10,2)
);

create or replace
PROCEDURE CME_HISTORICO (expediente in varchar2, tramite IN VARCHAR2) IS

  --CODIGO VARCHAR2(100);
 
BEGIN      
  dbms_output.put_line('INICIO FUNCION CME_HISTORICO: '||to_char(SYSDATE,'yyyymmdd hh24:mi:ss')); 
  
  --INSERTAMOS SOLICITUD
insert into CME_HIST_OFERTA (  CME_OFE_ID,CME_OFE_COD_TRAMITE,CME_OFE_ID_OFERTA,CME_OFE_COD_OFERTA,CME_OFE_COD_OFI_GEST,CME_OFE_PREC,CME_OFE_PREC_NOM,CME_OFE_DIFUSION,CME_OFE_FEC_DIFUSION,
CME_OFE_FEC_ENV_CAND,CME_OFE_NUM_TOT_CAND,CME_OFE_DOC_GEST_OFE,CME_OFE_CONTRATACION, CME_OFE_MOT_CONTRATACION,CME_OFE_COD_TIPO_NIF, CME_OFE_NIF,CME_OFE_NOMBRE,
CME_OFE_APE1, CME_OFE_APE2, CME_OFE_EMAIL, CME_OFE_TLF, CME_OFE_FEC_NAC, CME_OFE_SEXO, CME_OFE_COD_TITULACION, CME_OFE_DOC_CONTRATACION, CME_OFE_FEC_INI, 
CME_OFE_FEC_FIN, CME_OFE_COD_GR_COT, CME_OFE_SALARIOB, CME_OFE_DIETAS_CONVENIO, CME_OFE_DIETAS_CONVOC, CME_OFE_FEC_BAJA, CME_OFE_COD_CAUSA_BAJA, 
CME_OFE_OBSERVACIONES, CME_OFE_COD_PUESTO, CME_OFE_NUMEXP, CME_OFE_EXP_EJE, CME_OFE_ANO_TITULACION, CME_OFE_FL_SUSTITUTO, CME_OFE_NOM_DOC_GEST_OFE, 
CME_OFE_NOM_DOC_CONTRATACION, CME_OFE_ID_OFERTA_ORIGEN, CME_OFE_DESC_PUESTO, CME_OFE_PAI_COD_1, CME_OFE_PAI_COD_2, CME_OFE_PAI_COD_3, CME_OFE_COD_TIT_1,
CME_OFE_COD_TIT_2, CME_OFE_COD_TIT_3, CME_OFE_FUNCIONES, CME_OFE_COD_IDIOMA_1, CME_OFE_COD_IDIOMA_2, CME_OFE_COD_IDIOMA_3, CME_OFE_COD_NIV_IDI_1,
CME_OFE_COD_NIV_IDI_2, CME_OFE_COD_NIV_IDI_3, CME_OFE_COD_NIV_FORM, CME_OFE_CIUDAD_DESTINO, CME_OFE_DPTO, CME_OFE_MESES_CONTRATO, CME_OFE_COD_CAUSA_RENUNCIA, 
FECHA_HIST)
select
SEQ_CME_HIST_OFERTA.nextval, tramite, CME_OFE_ID_OFERTA,CME_OFE_COD_OFERTA,CME_OFE_COD_OFI_GEST,CME_OFE_PREC,CME_OFE_PREC_NOM,CME_OFE_DIFUSION,CME_OFE_FEC_DIFUSION,
CME_OFE_FEC_ENV_CAND,CME_OFE_NUM_TOT_CAND,CME_OFE_DOC_GEST_OFE,CME_OFE_CONTRATACION, CME_OFE_MOT_CONTRATACION,CME_OFE_COD_TIPO_NIF, CME_OFE_NIF,CME_OFE_NOMBRE,
CME_OFE_APE1, CME_OFE_APE2, CME_OFE_EMAIL, CME_OFE_TLF, CME_OFE_FEC_NAC, CME_OFE_SEXO, CME_OFE_COD_TITULACION, CME_OFE_DOC_CONTRATACION, CME_OFE_FEC_INI, 
CME_OFE_FEC_FIN, CME_OFE_COD_GR_COT, CME_OFE_SALARIOB, CME_OFE_DIETAS_CONVENIO, CME_OFE_DIETAS_CONVOC, CME_OFE_FEC_BAJA, CME_OFE_COD_CAUSA_BAJA, 
CME_OFE_OBSERVACIONES, CME_OFE_COD_PUESTO, CME_OFE_NUMEXP, CME_OFE_EXP_EJE, CME_OFE_ANO_TITULACION, CME_OFE_FL_SUSTITUTO, CME_OFE_NOM_DOC_GEST_OFE, 
CME_OFE_NOM_DOC_CONTRATACION, CME_OFE_ID_OFERTA_ORIGEN, CME_OFE_DESC_PUESTO, CME_OFE_PAI_COD_1, CME_OFE_PAI_COD_2, CME_OFE_PAI_COD_3, CME_OFE_COD_TIT_1,
CME_OFE_COD_TIT_2, CME_OFE_COD_TIT_3, CME_OFE_FUNCIONES, CME_OFE_COD_IDIOMA_1, CME_OFE_COD_IDIOMA_2, CME_OFE_COD_IDIOMA_3, CME_OFE_COD_NIV_IDI_1,
CME_OFE_COD_NIV_IDI_2, CME_OFE_COD_NIV_IDI_3, CME_OFE_COD_NIV_FORM, CME_OFE_CIUDAD_DESTINO, CME_OFE_DPTO, CME_OFE_MESES_CONTRATO, CME_OFE_COD_CAUSA_RENUNCIA,  
SYSDATE  
from CME_OFERTA
where CME_OFE_NUMEXP=EXPEDIENTE;
commit;

insert into CME_HIST_PUESTO (CME_PTO_ID, CME_PTO_COD_TRAMITE, CME_PTO_COD_PUESTO,CME_PTO_DESC_PUESTO,CME_PTO_PAI_COD_1,CME_PTO_PAI_COD_2,CME_PTO_PAI_COD_3,CME_PTO_COD_TIT_1,CME_PTO_COD_TIT_2,
CME_PTO_COD_TIT_3,CME_PTO_FUNCIONES,CME_PTO_COD_IDIOMA_1,CME_PTO_COD_IDIOMA_2, CME_PTO_COD_NIV_FORM,CME_PTO_COD_GR_COT, CME_PTO_SALARIO_ANEX1,CME_PTO_DIETAS_MANUT,
CME_PTO_MESES_MANUT, CME_PTO_TRAM_SEGUROS, CME_PTO_IMP_MAX_SUBV, CME_PTO_FEC_INI, CME_PTO_FEC_FIN, CME_PTO_CONVENIO_COL, CME_PTO_SAL_BRUTO, CME_PTO_DIETAS_CONV, 
CME_PTO_COSTE_CONT, CME_PTO_OTROS_BENEF, CME_PTO_COD_RESULT, CME_PTO_COD_MOTIVO, CME_PTO_OBSERVACIONES, CME_PTO_COD_NIV_IDI_1, CME_PTO_COD_NIV_IDI_2, 
CME_PTO_NUMEXP, CME_PTO_EXP_EJE, CME_PTO_CIUDAD_DESTINO, CME_PTO_DPTO, CME_PTO_COD_IDIOMA_3, CME_PTO_COD_NIV_IDI_3, CME_PTO_SAL_SOLIC, 
CME_PTO_DIETAS_SOLIC, CME_PTO_TRAM_SOLIC, CME_PTO_IMP_TOT_SOLIC, CME_PTO_SALARIO_ANEX2, CME_PTO_SALARIO_ANEX3, CME_PTO_SALARIO_ANEX_TOT, 
CME_PTO_MESES_CONTRATO, FECHA_HIST, CME_PTO_GASTOS_SEG, CME_PTO_GASTOS_VIS)
select
SEQ_CME_HIST_SOLICITUD.nextval, tramite, CME_PTO_COD_PUESTO,CME_PTO_DESC_PUESTO,CME_PTO_PAI_COD_1,CME_PTO_PAI_COD_2,CME_PTO_PAI_COD_3,CME_PTO_COD_TIT_1,CME_PTO_COD_TIT_2,
CME_PTO_COD_TIT_3,CME_PTO_FUNCIONES,CME_PTO_COD_IDIOMA_1,CME_PTO_COD_IDIOMA_2, CME_PTO_COD_NIV_FORM,CME_PTO_COD_GR_COT, CME_PTO_SALARIO_ANEX1,CME_PTO_DIETAS_MANUT,
CME_PTO_MESES_MANUT, CME_PTO_TRAM_SEGUROS, CME_PTO_IMP_MAX_SUBV, CME_PTO_FEC_INI, CME_PTO_FEC_FIN, CME_PTO_CONVENIO_COL, CME_PTO_SAL_BRUTO, CME_PTO_DIETAS_CONV, 
CME_PTO_COSTE_CONT, CME_PTO_OTROS_BENEF, CME_PTO_COD_RESULT, CME_PTO_COD_MOTIVO, CME_PTO_OBSERVACIONES, CME_PTO_COD_NIV_IDI_1, CME_PTO_COD_NIV_IDI_2, 
CME_PTO_NUMEXP, CME_PTO_EXP_EJE, CME_PTO_CIUDAD_DESTINO, CME_PTO_DPTO, CME_PTO_COD_IDIOMA_3, CME_PTO_COD_NIV_IDI_3, CME_PTO_SAL_SOLIC, 
CME_PTO_DIETAS_SOLIC, CME_PTO_TRAM_SOLIC, CME_PTO_IMP_TOT_SOLIC, CME_PTO_SALARIO_ANEX2, CME_PTO_SALARIO_ANEX3, CME_PTO_SALARIO_ANEX_TOT, 
CME_PTO_MESES_CONTRATO,SYSDATE , CME_PTO_GASTOS_SEG, CME_PTO_GASTOS_VIS 
from CME_PUESTO
where CME_PTO_NUMEXP=EXPEDIENTE;
commit;


insert into CME_HIST_JUSTIFICACION (CME_JUS_ID, CME_JUS_COD_TRAMITE, CME_JUS_ID_JUSTIFICACION,CME_JUS_COD_PUESTO,CME_JUS_NUMEXP,CME_JUS_EXP_EJE,CME_JUS_ID_OFERTA,CME_JUS_COD_ESTADO,
CME_JUS_FL_VARIOS_TRAB,CME_JUS_IMP_JUSTIFICADO,CME_JUS_SALARIOSUB,CME_JUS_DIETAS, CME_JUS_GASTOSGES,CME_JUS_BONIF, FECHA_HIST, CME_JUS_GASTOS_SEG, CME_JUS_GASTOS_VIS)
select
SEQ_CME_HIST_JUSTIF.nextval, tramite, CME_JUS_ID_JUSTIFICACION,CME_JUS_COD_PUESTO,CME_JUS_NUMEXP,CME_JUS_EXP_EJE,CME_JUS_ID_OFERTA,CME_JUS_COD_ESTADO,
CME_JUS_FL_VARIOS_TRAB,CME_JUS_IMP_JUSTIFICADO,CME_JUS_SALARIOSUB,CME_JUS_DIETAS, CME_JUS_GASTOSGES,CME_JUS_BONIF,SYSDATE, CME_JUS_GASTOS_SEG, CME_JUS_GASTOS_VIS
from CME_JUSTIFICACION
where CME_JUS_NUMEXP=EXPEDIENTE;
commit;

dbms_output.put_line('FIN PROCESO CME_HISTORICO: '||to_char(SYSDATE,'yyyymmdd hh24:mi:ss'));   

END CME_HISTORICO;