
  CREATE TABLE ORI14_AMBITOS_HORAS 
   (	ORI_AMB_COD NUMBER(8,0) NOT NULL ENABLE, 
	ORI_AMB_TERHIS NUMBER(2,0), 
	ORI_AMB_AMBITO VARCHAR2(50 BYTE), 
	ORI_AMB_HORASTOT NUMBER(8,0), 
	ORI_AMB_ANOCONV NUMBER(4,0), 
	 CONSTRAINT XPK_ORI14_AMBITOS_HORAS PRIMARY KEY (ORI_AMB_COD)
  
   ) ;
 

   COMMENT ON COLUMN ORI14_AMBITOS_HORAS.ORI_AMB_COD IS 'IDENTIFICADOR DEL CODIGO DEL AMBITO';
 
   COMMENT ON COLUMN ORI14_AMBITOS_HORAS.ORI_AMB_TERHIS IS 'IDENTIFICADOR DEL CODIGO DE TERRITORIO HISOTIRCO: 1 ALAVA, 48 BIZKAYA, 20 GIPUZKOA';
 
   COMMENT ON COLUMN ORI14_AMBITOS_HORAS.ORI_AMB_AMBITO IS 'DESCRIPCION DEL AMBITO';
 
   COMMENT ON COLUMN ORI14_AMBITOS_HORAS.ORI_AMB_HORASTOT IS 'HORAS DE ORIENTACION DEL AMBITO';
 
   COMMENT ON COLUMN ORI14_AMBITOS_HORAS.ORI_AMB_ANOCONV IS 'AÑO DE LA CONVOCATORIA';
 
   COMMENT ON TABLE ORI14_AMBITOS_HORAS  IS 'AMBITOS DEL PROCEDIMIENTO DE ORIENTACION - ORIENTACION';
   ---------------------------------------------------------------------------
     CREATE TABLE ORI14_AUDITORIA 
   (	USU_COD NUMBER(4,0) NOT NULL ENABLE, 
	PROCESO NUMBER(3,0) NOT NULL ENABLE, 
	FEC_EJECUCION TIMESTAMP (0) NOT NULL ENABLE, 
	RESULTADO VARCHAR2(100 BYTE), 
	COD_PROCEDIMIENTO VARCHAR2(5 BYTE)
   )  ;
 

   COMMENT ON COLUMN ORI14_AUDITORIA.USU_COD IS 'ID del usuario que ejecuta el proceso';
 
   COMMENT ON COLUMN ORI14_AUDITORIA.PROCESO IS 'Código de proceso ejecutado';
 
   COMMENT ON COLUMN ORI14_AUDITORIA.FEC_EJECUCION IS 'Fecha y hora de ejecución del proceso';
 
   COMMENT ON COLUMN ORI14_AUDITORIA.RESULTADO IS 'Resultado devuelto por el proceso.';
   -----------------------------------------------------------------
  
    CREATE TABLE ORI14_ENTIDAD 
   (	ORI_ENT_COD NUMBER NOT NULL ENABLE, 
	EXT_MUN NUMBER(3,0), 
	EXT_EJE NUMBER(4,0), 
	EXT_NUM VARCHAR2(30 BYTE), 
	EXT_TER NUMBER(12,0), 
	EXT_NVR NUMBER(3,0), 
	ORI_ENT_NOM VARCHAR2(80 BYTE), 
	/*
	ORI_ENT_ADMLOCAL VARCHAR2(1 BYTE), 
	ORI_ENT_SUPRAMUN VARCHAR2(1 BYTE), 
	ORI_EXP_CENTROFP_PUB NUMBER(1 ), 
	ORI_EXP_CENTROFP_PRIV NUMBER(1 ), 
	*/
	
	ORI_ENT_ADMLOCAL_VAL VARCHAR2(1 BYTE), 
	ORI_ENT_SUPRAMUN_VAL VARCHAR2(1 BYTE), 
	ORI_EXP_CENTROFP_PUB_VAL NUMBER(8,0), 
	ORI_EXP_CENTROFP_PRIV_VAL NUMBER(8,0), 
	
	
	--ORI_ENT_TRAYECTORIA NUMBER(2,0), 
	ORI_ENT_TRAYECTORIA_VAL NUMBER(2,0), 
	
	ORI_ORIENT_VAL_UBIC NUMBER(2,0), 
	ORI_ORIENT_VAL_DESPACHOS NUMBER(2,0), 
	ORI_ORIENT_VAL_AULAS NUMBER(2,0), 
	
	

	ORI_ENT_ACEPTA_MAS NUMBER(1), 
	ORI_ENT_ASOCIACION NUMBER(1), 
	 CONSTRAINT XPKORI14_ENTIDAD_ PRIMARY KEY (ORI_ENT_COD)
  
   ) ;
 

 
-----------------------------------------------------------------------------

  CREATE TABLE ORI14_ESPECIALIDADES 
   (	ORI_ESP_COD NUMBER(8,0) NOT NULL ENABLE, 
	ORI_ESP_DESC VARCHAR2(100 BYTE), 
	 CONSTRAINT XPKORI14_ESPECIALIDADES PRIMARY KEY (ORI_ESP_COD)
  
   )  ;
 ----------------------------------------------------------------------------
 
 
  CREATE TABLE ORI14_ORI_TRAYECTORIA 
   (	ORI_ORITRAY_COD NUMBER(8,0) NOT NULL ENABLE, 
	ORI_ASOC_COD NUMBER 
, ORI_ORITRAY_NUMEXP VARCHAR2(30 BYTE)
,COLEC1_DEC_327_2007 NUMBER(1)
,COLEC1_DEC_327_2008 NUMBER(1)
,COLEC1_DEC_327_2009 NUMBER(1)
,COLEC1_DEC_327_2010 NUMBER(1)

,COLEC1_MIN_94_2007 NUMBER(1)
,COLEC1_MIN_94_2008 NUMBER(1)
,COLEC1_MIN_94_2009 NUMBER(1)
,COLEC1_MIN_94_2010 NUMBER(1)

,COLEC1_MIN_98_2007 NUMBER(1)
,COLEC1_MIN_98_2008 NUMBER(1)
,COLEC1_MIN_98_2009 NUMBER(1)
,COLEC1_MIN_98_2010 NUMBER(1)

,COLEC1_TAS_03_2007 NUMBER(1)
,COLEC1_TAS_03_2008 NUMBER(1)
,COLEC1_TAS_03_2009 NUMBER(1)
,COLEC1_TAS_03_2010 NUMBER(1)

,COLEC1_ACT_56_03 NUMBER

,COLEC2_LAN_2011 NUMBER(1)
,COLEC2_LAN_2013 NUMBER(1)
,COLEC2_LAN_OTROS NUMBER




	 ,CONSTRAINT XPKORI_ORI14_TRAYECTORIA PRIMARY KEY (ORI_ORITRAY_COD)
   ) ;
  --------------------------------------------------------------------------
  
  CREATE TABLE ORI14_ORI_UBIC 
   (	ORI_ORIENT_UBIC_COD NUMBER(8,0) NOT NULL ENABLE, 
	ORI_ORIENT_ANO NUMBER(4,0), 
	ORI_ENT_COD NUMBER(*,0), 
	ORI_ORIENT_NUMEXP VARCHAR2(30 BYTE),
	ORI_AMB_COD NUMBER(8,0), 
	MUN_PAI NUMBER(3,0), 
	MUN_PRV NUMBER(2,0), 
	MUN_COD NUMBER(4,0), 
	PRV_PAI NUMBER(3,0), 
	ORI_ORIENT_DIRECCION VARCHAR2(100 BYTE), 
	ORI_ORIENT_CP VARCHAR2(5 BYTE), 
	ORI_ORIENT_HORASSOLICITADAS NUMBER(8,2), 
	ORI_ORIENT_HORASADJ NUMBER(8,2), 
	
	ORI_ORIENT_DESPACHOS VARCHAR2(1 BYTE), 
	ORI_ORIENT_AULAGRUPAL VARCHAR2(1 BYTE), 
	ORI_ORIENT_DESPACHOS_VALIDADOS VARCHAR2(1 BYTE), 
	ORI_ORIENT_AULAGRUPAL_VALIDADA VARCHAR2(1 BYTE), 
	
	ORI_ORIENT_VAL_TRAY NUMBER(2,0), 
	ORI_ORIENT_VAL_UBIC NUMBER(8,2), 
	ORI_ORIENT_VAL_DESPACHOS NUMBER, 
	ORI_ORIENT_VAL_AULAS NUMBER, 
	
	
	ORI_ORIENT_PUNTUACION NUMBER(8,2), 
	ORI_ORIENT_OBSERVACIONES VARCHAR2(500 BYTE), 
	 CONSTRAINT XPKORI14_ORI_UBIC PRIMARY KEY (ORI_ORIENT_UBIC_COD)
  , 
	 CONSTRAINT ORI14_R_2 FOREIGN KEY (ORI_ENT_COD)
	  REFERENCES ORI14_ENTIDAD (ORI_ENT_COD) ON DELETE SET NULL ENABLE, 
	 CONSTRAINT ORI14_R_3 FOREIGN KEY (ORI_AMB_COD)
	  REFERENCES ORI14_AMBITOS_HORAS (ORI_AMB_COD) ON DELETE SET NULL ENABLE
   );
   
-------------------------------------------------------------------


  CREATE TABLE ORI14_TMP_ADJUDICACION 
   (	ORI_ORIENT_UBIC_COD NUMBER(8,0), 
	VALORACION NUMBER(8,2), 
	HORAS_SOLICITADAS NUMBER(8,2), 
	HORAS_ASIGNADAS_TEMP NUMBER(8,2), 
	PORC_TEMP NUMBER(8,2), 
	PORC_SOLICITADO NUMBER(8,2), 
	PORC_CONSUMIDO NUMBER(8,2), 
	HORAS_ASIGNADAS NUMBER(8,2), 
	IND_FINALIZA NUMBER, 
	FECHA_CREACION DATE, 
	COD_AMBITO NUMBER
   )  ;
 
-----------------------------------------------------


  CREATE TABLE ORI14_UBICACIONES 
   (	ORI_UBI_COD NUMBER NOT NULL ENABLE, 
	ORI_UBIC_ANO NUMBER(4,0), 
	ORI_UBIC_PUNTUACION NUMBER(8,2), 
	ORI_AMB_COD NUMBER(8,0), 
	MUN_PAI NUMBER(3,0), 
	MUN_PRV NUMBER(2,0), 
	MUN_COD NUMBER(4,0), 
	PRV_PAI NUMBER(3,0), 
	 CONSTRAINT XPKORI14_UBICACIONES PRIMARY KEY (ORI_UBI_COD)
  
   ) ;
 
------------------------------------------------------

  CREATE TABLE ORI14_ASOCIACION
   (	ORI_ASOC_COD NUMBER NOT NULL ENABLE, 
	ORI_ENT_COD NUMBER,
	ORI_ASOC_NOMBRE  VARCHAR2 (500),
	ORI_ENT_SUPRAMUN NUMBER(1),
	ORI_ENT_ADMLOCAL NUMBER(1),
	ORI_EXP_CENTROFP NUMBER(1),
	 CONSTRAINT XPKORI14_ASOCIACION PRIMARY KEY (ORI_ASOC_COD)
  
   ) ;




