create or replace PROCEDURE   adjudica_orientacion_2014 (ano in number, mensaje out varchar2, exp_estado_incorrecto out number) iS

HORAS_AMBITO Number(8,2);
HORAS_AMBITO_INI Number(8,2);
ambito Number(8);
UBICACION NUMBER(4);
UBIC_NULL NUMBER(4);
entidad number(4);
HORAS_SOLICITADAS Number(8,2);
HORAS_TOT_SOLICITADAS Number(8,2);
HORAS_X_PUNTO NUMBER (12,9);
VALORACION NUMBER(6,2);
entidad_Ant number(10);
VALORACION_TOT number(12,8);
HORAS_ASIGNADAS number(8,2);
PO_PUNTUACION NUMBER(8,2);
PO_HORAS NUMBER(8,2);

HORAS_CONSUMIDAS NUMBER(8,2);
HORAS_TEMP NUMBER(8,2);
FIN NUMBER;
CAMBIO_AMBITO NUMBER;
loops number;
actualizado number;
ULTIMA NUMBER;
seguir number;
HORAS_SOL_ENTIDAD NUMBER(8,2);
HORAS_SOL NUMBER(8,2);
HORAS_ADJ_ENTIDAD NUMBER(8,2);

PUNT_ENTIDAD NUMBER(8,2);
PORCEN_ENTIDAD NUMBER (12,10);
BLOQUES_ENTIDAD NUMBER(2);
BLOQUES_CONSUMIDO NUMBER(8);
BLOQUES_SOLICITADOS NUMBER(2);
BLOQUES_ASIGNADOS NUMBER(2);
NUM_ACEPTAN_MAS NUMBER;
PROPORCION NUMBER(8,4);


    v_ORI_ENT_COD NUMBER;
    v_ori_amb_cod  NUMBER;
    v_ORI_ENT_SUPRAMUN NUMBER;
    v_ORI_ENT_ADMLOCAL NUMBER;
    v_ORI_EXP_CENTROFP_PRIV_VAL NUMBER;
    v_ORI_EXP_CENTROFP_PUB_VAL NUMBER;
    v_ORI_ENT_TRAYECTORIA_VAL NUMBER;
    v_ORI_ORIENT_VAL_UBIC NUMBER(8,2);
    v_ORI_ORIENT_VAL_DESPACHOS NUMBER;
    v_ORI_ORIENT_VAL_AULAS NUMBER;


lines_out number(8);

-----------------------------------------------------------------------------
--              Declaraci?n de variables y Cursores                        --
-----------------------------------------------------------------------------
    CURSOR EXPEDIENTES(AMB IN NUMBER) IS
        SELECT A.ORI_ENT_COD,ORI_ORIENT_UBIC_COD,ORI_ORIENT_HORASSOLICITADAS,ORI_ORIENT_PUNTUACION  
        FROM ORI14_ORI_UBIC B 
        INNER JOIN ORI14_ENTIDAD A ON A.ORI_ENT_COD=B.ORI_ENT_COD 
        --INNER JOIN E_CRO C ON C.CRO_NUM=A.EXT_NUM
        WHERE 
        --CRO_TRA=3 AND CRO_FEF is null   AND 
        ORI_AMB_COD=AMB AND ORI_ORIENT_ANO=ANO
        and ORI_ORIENT_PUNTUACION<>0
		order by B.ORI_ENT_COD,ORI_ORIENT_PUNTUACION  desc ;
        
    CURSOR EXPEDIENTES2(AMB IN NUMBER) IS
        SELECT b.ORI_ORIENT_UBIC_COD,
CASE WHEN HORAS_ASIGNADAS_TEMP>HORAS_SOLICITADAS THEN HORAS_SOLICITADAS ELSE HORAS_ASIGNADAS_TEMP END HORAS_ASIGNADAS_TEMP
        FROM  ORI14_TMP_ADJUDICACION B 
        inner join  ORI14_ORI_UBIC a on a.ORI_ORIENT_UBIC_COD=b.ORI_ORIENT_UBIC_COD
        inner join ori14_entidad c on c.ORI_ENT_COD=a.ORI_ENT_COD
      WHERE COD_AMBITO=AMB 
      ORDER BY VALORACION DESC, C.ORI_ENT_TRAYECTORIA_VAL, c.ORI_ORIENT_VAL_DESPACHOS,c.ORI_ORIENT_VAL_AULAS,
      c.ORI_ENT_SUPRAMUN_VAL, c.ORI_ENT_ADMLOCAL_VAL,c.ORI_EXP_CENTROFP_PUB_VAL,c.ORI_EXP_CENTROFP_PRIV_VAL ;        
 
    CURSOR AMBITOS IS
        SELECT ORI_AMB_COD,ORI_AMB_HORASTOT  FROM ORI14_AMBITOS_HORAS 
        where ORI_AMB_ANOCONV=ano ;  
        
          CURSOR EXPEDIENTES4(AMB IN NUMBER) IS
        SELECT A.ORI_ENT_COD,d.oRI_ORIENT_UBIC_COD,b.HORAS_SOLICITADAS,b.VALORACION  
       FROM 
      ORI14_TMP_ADJUDICACION b
      INNER JOIN ORI14_ORI_UBIC D ON D.ORI_ORIENT_UBIC_COD=B.ORI_ORIENT_UBIC_COD
      INNER JOIN ORI14_ENTIDAD A ON A.ORI_ENT_COD=D.ORI_ENT_COD 
      --INNER JOIN E_CRO C ON C.CRO_NUM=A.EXT_NUM
      WHERE 
      --CRO_TRA=3 AND CRO_FEF is null   AND 
      B.COD_AMBITO=AMBITO 
      and HORAS_ASIGNADAS<HORAS_SOLICITADAS
       and HORAS_ASIGNADAS<>0;
      
                       
    CURSOR EXPEDIENTES5(AMB IN NUMBER) IS
        SELECT b.ORI_ORIENT_UBIC_COD,
            CASE WHEN HORAS_ASIGNADAS_TEMP>HORAS_SOLICITADAS-HORAS_ASIGNADAS THEN HORAS_SOLICITADAS-HORAS_ASIGNADAS ELSE HORAS_ASIGNADAS_TEMP END HORAS_ASIGNADAS_TEMP
        FROM  ORI14_TMP_ADJUDICACION B
        inner join  ORI14_ORI_UBIC a on a.ORI_ORIENT_UBIC_COD=b.ORI_ORIENT_UBIC_COD
        inner join ori14_entidad c on c.ORI_ENT_COD=a.ORI_ENT_COD
      WHERE COD_AMBITO=AMB 
      and HORAS_ASIGNADAS<HORAS_SOLICITADAS
       and HORAS_ASIGNADAS<>0
ORDER BY VALORACION DESC, C.ORI_ENT_TRAYECTORIA_VAL, c.ORI_ORIENT_VAL_DESPACHOS,c.ORI_ORIENT_VAL_AULAS,
      c.ORI_ENT_SUPRAMUN_VAL, c.ORI_ENT_ADMLOCAL_VAL,c.ORI_EXP_CENTROFP_PUB_VAL,c.ORI_EXP_CENTROFP_PRIV_VAL;  
      
             CURSOR EXPEDIENTES6(AMB IN NUMBER) IS
        SELECT A.ORI_ENT_COD,d.oRI_ORIENT_UBIC_COD,b.HORAS_SOLICITADAS,b.VALORACION  
       FROM 
      ORI14_TMP_ADJUDICACION b
      INNER JOIN ORI14_ORI_UBIC D ON D.ORI_ORIENT_UBIC_COD=B.ORI_ORIENT_UBIC_COD
      INNER JOIN ORI14_ENTIDAD A ON A.ORI_ENT_COD=D.ORI_ENT_COD 
      --INNER JOIN E_CRO C ON C.CRO_NUM=A.EXT_NUM
      WHERE 
      --CRO_TRA=3 AND CRO_FEF is null   AND 
      B.COD_AMBITO=AMBITO 
      and HORAS_ASIGNADAS<HORAS_SOLICITADAS
       and HORAS_ASIGNADAS=0;
      
                       
    CURSOR EXPEDIENTES7(AMB IN NUMBER) IS
        SELECT b.ORI_ORIENT_UBIC_COD,
            CASE WHEN HORAS_ASIGNADAS_TEMP>HORAS_SOLICITADAS-HORAS_ASIGNADAS THEN HORAS_SOLICITADAS-HORAS_ASIGNADAS ELSE HORAS_ASIGNADAS_TEMP END HORAS_ASIGNADAS_TEMP
        FROM  ORI14_TMP_ADJUDICACION B
        inner join  ORI14_ORI_UBIC a on a.ORI_ORIENT_UBIC_COD=b.ORI_ORIENT_UBIC_COD
        inner join ori14_entidad c on c.ORI_ENT_COD=a.ORI_ENT_COD
      WHERE COD_AMBITO=AMB 
      and HORAS_ASIGNADAS<HORAS_SOLICITADAS
       and HORAS_ASIGNADAS=0
       ORDER BY VALORACION DESC, C.ORI_ENT_TRAYECTORIA_VAL, c.ORI_ORIENT_VAL_DESPACHOS,c.ORI_ORIENT_VAL_AULAS,
      c.ORI_ENT_SUPRAMUN_VAL, c.ORI_ENT_ADMLOCAL_VAL,c.ORI_EXP_CENTROFP_PUB_VAL,c.ORI_EXP_CENTROFP_PRIV_VAL;       
      
      
    CURSOR EXPEDIENTES8(AMB IN NUMBER) IS
        SELECT b.ORI_ORIENT_UBIC_COD
        FROM  ORI14_TMP_ADJUDICACION B
        inner join  ORI14_ORI_UBIC a on a.ORI_ORIENT_UBIC_COD=b.ORI_ORIENT_UBIC_COD
        inner join ori14_entidad c on c.ORI_ENT_COD=a.ORI_ENT_COD
      WHERE COD_AMBITO=AMB 
      and (HORAS_ASIGNADAS<HORAS_SOLICITADAS OR C.ORI_ENT_ACEPTA_MAS=1) 
       ;
       
       
    CURSOR entidades_1  IS
    select ORI_ENT_COD, 
    case when ORI_ENT_SUPRAMUN = total then 1 else 0 end ORI_ENT_SUPRAMUN,
    case when ORI_ENT_ADMLOCAL = total then 1 else 0 end ORI_ENT_ADMLOCAL,
    case when ORI_EXP_CENTROFP_PUB_VAL = total then 1 else 0 end ORI_EXP_CENTROFP_PUB_VAL,
    case when ORI_EXP_CENTROFP_PRIV_VAL = total then 1 else 0 end ORI_EXP_CENTROFP_PRIV_VAL
    from (
    select 
    a.ORI_ENT_COD,
sum(nvl(a.ORI_ENT_SUPRAMUN,0)) ORI_ENT_SUPRAMUN,
sum(nvl(a.ORI_ENT_ADMLOCAL,0)) ORI_ENT_ADMLOCAL,
sum(nvl(a.ORI_EXP_CENTROFP_PUB,0)) ORI_EXP_CENTROFP_PUB_VAL,
sum(nvl(a.ORI_EXP_CENTROFP_PRIV,0))ORI_EXP_CENTROFP_PRIV_VAL,
count(*) total
    from ORI14_ASOCIACION a inner join ori14_entidad b on a.ORI_ENT_COD=b.ORI_ENT_COD
    group by a.ORI_ENT_COD);
    
    CURSOR entidades (AMB IN NUMBER) IS
select 
b.ORI_ENT_COD,
a.ori_amb_cod,
max(nvl(a.ORI_ORIENT_VAL_TRAY,0))ORI_ENT_TRAYECTORIA_VAL,
max(nvl(a.ORI_ORIENT_VAL_UBIC,0))ORI_ORIENT_VAL_UBIC,
max(nvl(a.ORI_ORIENT_VAL_DESPACHOS,0))ORI_ORIENT_VAL_DESPACHOS,
max(nvl(a.ORI_ORIENT_VAL_AULAS,0)) ORI_ORIENT_VAL_AULAS
 from ori14_ori_ubic a inner join ori14_entidad b on a.ORI_ENT_COD=b.ORI_ENT_COD
WHERE ORI_AMB_COD=AMB 
 group by b.ORI_ENT_COD,a.ori_amb_cod;
      
Begin

  DBMS_OUTPUT.PUT_LINE('ANO: '||ANO||' ---- INICIO DEL PROCESO: '|| TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS'));
    
  SEGUIR:=0;
  entidad_ant:=99999999;
	
  SELECT 
    COUNT(A.EXT_NUM )
    into seguir
  FROM ORI14_ORI_UBIC B 
  INNER JOIN ORI14_ENTIDAD A ON A.ORI_ENT_COD=B.ORI_ENT_COD 
 -- INNER JOIN E_CRO C ON C.CRO_NUM=A.EXT_NUM
  WHERE  
  --CRO_FEF is null   AND 
  --CRO_TRA NOT IN (3,12,999) and --RESOLUCION PROVISIONAL, RESOLUCION DENEGATORIA, CIERRE EXPEDIENTE.
    ORI_ORIENT_ANO=ANO;
        
    
  IF SEGUIR =0 THEN
    exp_estado_incorrecto:=0;
  ELSE
    MENSAJE := 'EXPEDIENTES EN ESTADOS NO PERMITIDOS';
    exp_estado_incorrecto:=1;
  END IF;
  
  
  DELETE FROM ORI14_TMP_ADJUDICACION;
  
  for reg_entidades_1 in entidades_1 loop
    v_ORI_ENT_SUPRAMUN:=reg_entidades_1.ORI_ENT_SUPRAMUN;
    v_ORI_ENT_ADMLOCAL:=reg_entidades_1.ORI_ENT_ADMLOCAL;
    v_ORI_EXP_CENTROFP_PUB_VAL:=reg_entidades_1.ORI_EXP_CENTROFP_PUB_VAL;
    v_ORI_EXP_CENTROFP_PRIV_VAL:=reg_entidades_1.ORI_EXP_CENTROFP_PRIV_VAL;
    
    update ori14_entidad set
    ORI_ENT_SUPRAMUN_VAL=v_ORI_ENT_SUPRAMUN,
    ORI_ENT_ADMLOCAL_VAL=v_ORI_ENT_ADMLOCAL,
    
    ORI_EXP_CENTROFP_PUB_VAL=v_ORI_EXP_CENTROFP_PUB_VAL,
    ORI_EXP_CENTROFP_PRIV_VAL=v_ORI_EXP_CENTROFP_PRIV_VAL
   where ORI_ENT_COD=v_ORI_ENT_COD;
    
  end loop;

  
  FOR REG_AMBITO IN AMBITOS LOOP
    ambito:=reg_ambito.ORI_AMB_COD;
    HORAS_AMBITO:=reg_ambito.ORI_AMB_HORASTOT;
    
    FOR REG_entidades IN entidades (Ambito) LOOP
    v_ORI_ENT_COD:=REG_entidades.ORI_ENT_COD;
    v_ori_amb_cod:=REG_entidades.ori_amb_cod;
   
    v_ORI_ENT_TRAYECTORIA_VAL:=REG_entidades.ORI_ENT_TRAYECTORIA_VAL;
    v_ORI_ORIENT_VAL_UBIC:=REG_entidades.ORI_ORIENT_VAL_UBIC;
    v_ORI_ORIENT_VAL_DESPACHOS:=REG_entidades.ORI_ORIENT_VAL_DESPACHOS;
    v_ORI_ORIENT_VAL_AULAS:=REG_entidades.ORI_ORIENT_VAL_AULAS;
    

    update ori14_entidad set
    ORI_ENT_TRAYECTORIA_VAL=v_ORI_ENT_TRAYECTORIA_VAL,
    ORI_ORIENT_VAL_UBIC=v_ORI_ORIENT_VAL_UBIC,
    ORI_ORIENT_VAL_DESPACHOS=v_ORI_ORIENT_VAL_DESPACHOS,
    ORI_ORIENT_VAL_AULAS=v_ORI_ORIENT_VAL_AULAS
    where ORI_ENT_COD=v_ORI_ENT_COD;
    end loop;
    
    entidad_ant:=9999999999;
    
    SELECT  
      SUM(PUNT) 
      INTO VALORACION_TOT 
    FROM (
      SELECT MAX(NVL(b.ORI_ORIENT_VAL_TRAY,0))+
      MAX(NVL(b.ORI_ORIENT_VAL_UBIC,0))+
      MAX(NVL(b.ORI_ORIENT_VAL_DESPACHOS,0))+
      MAX(NVL(b.ORI_ORIENT_VAL_AULAS,0))
   
      PUNT, b.ORI_ENT_COD  
      FROM ORI14_ORI_UBIC b
      INNER JOIN ORI14_ENTIDAD A ON A.ORI_ENT_COD=B.ORI_ENT_COD 
      --INNER JOIN E_CRO C ON C.CRO_NUM=A.EXT_NUM
      WHERE 
      --CRO_TRA=3 AND CRO_FEF is null   AND 
      ORI_AMB_COD=AMBITO 
        AND ORI_ORIENT_ANO=ANO
      GROUP BY b.ORI_ENT_COD
      );
  
    BLOQUES_CONSUMIDO:=0;
    DBMS_OUTPUT.PUT_LINE('-------------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('AMBITO: '||ambito || '    BLOQUES: '||HORAS_AMBITO);
        
    FOR REG_EXP IN EXPEDIENTES (AMBITO) LOOP
      entidad:=REG_EXP.ORI_ENT_COD;
      ubicacion:=REG_EXP.ORI_ORIENT_UBIC_COD;
      
       IF (ENTIDAD<>ENTIDAD_ANT) THEN
      
      DBMS_OUTPUT.PUT_LINE('-----------------');
      DBMS_OUTPUT.PUT_LINE('RECORRO CURSOR EXPEDIENTE: entidad: '||entidad|| '                ubicacion'||ubicacion);
      
      SELECT MAX(NVL(b.ORI_ORIENT_VAL_TRAY,0))+
      MAX(NVL(b.ORI_ORIENT_VAL_UBIC,0))+
      MAX(NVL(b.ORI_ORIENT_VAL_DESPACHOS,0))+
      MAX(NVL(b.ORI_ORIENT_VAL_AULAS,0)) into PUNT_ENTIDAD
      FROM ORI14_ORI_UBIC b
      INNER JOIN ORI14_ENTIDAD A ON A.ORI_ENT_COD=B.ORI_ENT_COD 
      --INNER JOIN E_CRO C ON C.CRO_NUM=A.EXT_NUM
      WHERE 
      --CRO_TRA=3 AND CRO_FEF is null   AND 
      ORI_AMB_COD=AMBITO 
        AND ORI_ORIENT_ANO=ANO
      AND  b.ORI_ENT_COD=entidad;
            DBMS_OUTPUT.PUT_LINE('PUNT_ENTIDAD '||PUNT_ENTIDAD );

      SELECT SUM(NVL(ORI_ORIENT_HORASSOLICITADAS,0)) into BLOQUES_SOLICITADOS
      FROM ORI14_ORI_UBIC b
      INNER JOIN ORI14_ENTIDAD A ON A.ORI_ENT_COD=B.ORI_ENT_COD 
      --INNER JOIN E_CRO C ON C.CRO_NUM=A.EXT_NUM
      WHERE 
      --CRO_TRA=3 AND CRO_FEF is null   AND 
      ORI_AMB_COD=AMBITO 
        AND ORI_ORIENT_ANO=ANO
      AND  b.ORI_ENT_COD=entidad;
      
      DBMS_OUTPUT.PUT_LINE('BLOQUES_SOLICITADOS '||BLOQUES_SOLICITADOS );
      
      
      PORCEN_ENTIDAD := PUNT_ENTIDAD/VALORACION_TOT;
      DBMS_OUTPUT.PUT_LINE('BLOQUES_A_ASIGNAR '||PUNT_ENTIDAD*HORAS_AMBITO/VALORACION_TOT );
      
      SELECT ROUND(PUNT_ENTIDAD*HORAS_AMBITO/VALORACION_TOT ,0) INTO BLOQUES_ENTIDAD FROM DUAL;
      DBMS_OUTPUT.PUT_LINE('BLOQUES_A_ASIGNAR_REDONDEADO '||BLOQUES_ENTIDAD );
     

      INSERT INTO ORI14_TMP_ADJUDICACION(
          ORI_ORIENT_UBIC_COD, 
          VALORACION, 
          HORAS_SOLICITADAS, 
          HORAS_ASIGNADAS_TEMP, 
          --PORC_TEMP, 
          --PORC_SOLICITADO, 
          --PORC_CONSUMIDO, 
          --HORAS_ASIGNADAS, 
          --IND_FINALIZA,
          FECHA_CREACION,COD_AMBITO)
        VALUES (ubicacion,PUNT_ENTIDAD,BLOQUES_SOLICITADOS,BLOQUES_ENTIDAD,SYSDATE,AMBITO);
        entidad_ant:=entidad;
      end if;  
      
      DBMS_OUTPUT.PUT_LINE('ubicacion '||ubicacion||' PUNT_ENTIDAD: '||PUNT_ENTIDAD||' BLOQUES_SOLICITADOS: '||BLOQUES_SOLICITADOS||' BLOQUES_ENTIDAD: '||BLOQUES_ENTIDAD);
      
      END LOOP;
      
      
      --fase 2. de lo que le correspondería ir dando hasta llegar al maximo por orden de puntuacion decreciente
        BLOQUES_CONSUMIDO:=0;
    FOR REG_EXP IN EXPEDIENTES2 (AMBITO) LOOP
      ubicacion:=REG_EXP.ORI_ORIENT_UBIC_COD;
      BLOQUES_ENTIDAD:=REG_EXP.HORAS_ASIGNADAS_TEMP;      
      
      
        IF BLOQUES_CONSUMIDO+BLOQUES_ENTIDAD>=HORAS_AMBITO THEN
          BLOQUES_ENTIDAD:=HORAS_AMBITO-BLOQUES_CONSUMIDO;
          BLOQUES_CONSUMIDO:=BLOQUES_CONSUMIDO+BLOQUES_ENTIDAD;
          
        ELSE 
          BLOQUES_CONSUMIDO:=BLOQUES_CONSUMIDO+BLOQUES_ENTIDAD;
                     
        END IF;
     
      UPDATE ORI14_TMP_ADJUDICACION SET HORAS_ASIGNADAS=BLOQUES_ENTIDAD WHERE ORI_ORIENT_UBIC_COD=ubicacion;
      commit;
      END LOOP;
      
      --fase 3. Si aún quedan bloques por entregar.
      
      SELECT SUM(NVL(HORAS_ASIGNADAS,0)) INTO BLOQUES_ASIGNADOS FROM ORI14_TMP_ADJUDICACION
      WHERE COD_AMBITO=AMBITO; 
      
      IF HORAS_AMBITO-BLOQUES_ASIGNADOS > 0 THEN
      --VAMOS A RECORRER LOS EXPEDIENTES E IR DANDO HORAS.
         Dbms_Output.Put_Line('QUEDAN HORAS POR ADJUDICAR');  
      
       entidad_ant:=9999999999;
    
    SELECT  
      nvl(SUM(VALORACION),0) 
      INTO VALORACION_TOT 
    FROM 
      ORI14_TMP_ADJUDICACION b
      INNER JOIN ORI14_ORI_UBIC D ON D.ORI_ORIENT_UBIC_COD=B.ORI_ORIENT_UBIC_COD
      INNER JOIN ORI14_ENTIDAD A ON A.ORI_ENT_COD=D.ORI_ENT_COD 
      --INNER JOIN E_CRO C ON C.CRO_NUM=A.EXT_NUM
      WHERE 
      --CRO_TRA=3 AND CRO_FEF is null   AND 
      B.COD_AMBITO=AMBITO 
      and HORAS_ASIGNADAS<HORAS_SOLICITADAS
      and HORAS_ASIGNADAS<>0
      ;
  
    BLOQUES_CONSUMIDO:=0;
    DBMS_OUTPUT.PUT_LINE('----fase3---------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('AMBITO: '||ambito );
    DBMS_OUTPUT.PUT_LINE('VALORACION_TOT: '||VALORACION_TOT );
    DBMS_OUTPUT.PUT_LINE('HORAS_AMBITO: '||HORAS_AMBITO);
    DBMS_OUTPUT.PUT_LINE('BLOQUES_ASIGNADOS: '||BLOQUES_ASIGNADOS);
        
        
        
        
        
    FOR REG_EXP IN EXPEDIENTES4 (AMBITO) LOOP
      entidad:=REG_EXP.ORI_ENT_COD;
      ubicacion:=REG_EXP.ORI_ORIENT_UBIC_COD;
      BLOQUES_SOLICITADOS:=REG_EXP.HORAS_SOLICITADAS;
      PUNT_ENTIDAD:=REG_EXP.VALORACION;
      
      
      DBMS_OUTPUT.PUT_LINE('RECORRO CURSOR EXPEDIENTE: entidad: '||entidad|| '                ubicacion'||ubicacion);
      PORCEN_ENTIDAD := PUNT_ENTIDAD/VALORACION_TOT;
      DBMS_OUTPUT.PUT_LINE('BLOQUES_A_ASIGNAR '||PUNT_ENTIDAD*(HORAS_AMBITO-BLOQUES_ASIGNADOS)/VALORACION_TOT );
      
      SELECT ROUND(PUNT_ENTIDAD*(HORAS_AMBITO-BLOQUES_ASIGNADOS)/VALORACION_TOT ,0) INTO BLOQUES_ENTIDAD FROM DUAL;
      DBMS_OUTPUT.PUT_LINE('BLOQUES_A_ASIGNAR_REDONDEADO '||BLOQUES_ENTIDAD );
     

      update ORI14_TMP_ADJUDICACION
      set 
      HORAS_ASIGNADAS_TEMP=BLOQUES_ENTIDAD
      where ORI_ORIENT_UBIC_COD=ubicacion;
      commit;
      
      
      
      END LOOP;
      
      
      --fase 4. de lo que le correspondería ir dando hasta llegar al maximo por orden de puntuacion decreciente
        BLOQUES_CONSUMIDO:=0;
    FOR REG_EXP IN EXPEDIENTES5 (AMBITO) LOOP
      ubicacion:=REG_EXP.ORI_ORIENT_UBIC_COD;
      BLOQUES_ENTIDAD:=REG_EXP.HORAS_ASIGNADAS_TEMP;      
      
      
        IF BLOQUES_CONSUMIDO+BLOQUES_ENTIDAD>=HORAS_AMBITO-BLOQUES_ASIGNADOS THEN
          BLOQUES_ENTIDAD:=HORAS_AMBITO-BLOQUES_ASIGNADOS-BLOQUES_CONSUMIDO;
          BLOQUES_CONSUMIDO:=BLOQUES_CONSUMIDO+BLOQUES_ENTIDAD;
          
        ELSE 
          BLOQUES_CONSUMIDO:=BLOQUES_CONSUMIDO+BLOQUES_ENTIDAD;
                     
        END IF;
     
      DBMS_OUTPUT.PUT_LINE('BLOQUES_A_ASIGNAR_REDONDEADO '||BLOQUES_ENTIDAD );
      UPDATE ORI14_TMP_ADJUDICACION SET HORAS_ASIGNADAS=HORAS_ASIGNADAS+BLOQUES_ENTIDAD WHERE ORI_ORIENT_UBIC_COD=ubicacion;
      commit;
      END LOOP;
      
    
      END IF;
      --fase 4, recorriendo expedientes no adjudicados
      SELECT SUM(NVL(HORAS_ASIGNADAS,0)) INTO BLOQUES_ASIGNADOS FROM ORI14_TMP_ADJUDICACION
      WHERE COD_AMBITO=AMBITO; 
      
      IF HORAS_AMBITO-BLOQUES_ASIGNADOS > 0 THEN
      --VAMOS A RECORRER LOS EXPEDIENTES E IR DANDO HORAS.
         Dbms_Output.Put_Line('QUEDAN HORAS POR ADJUDICAR');  
      
       entidad_ant:=9999999999;
    
    SELECT  
      nvl(SUM(VALORACION),0) 
      INTO VALORACION_TOT 
    FROM 
      ORI14_TMP_ADJUDICACION b
      INNER JOIN ORI14_ORI_UBIC D ON D.ORI_ORIENT_UBIC_COD=B.ORI_ORIENT_UBIC_COD
      INNER JOIN ORI14_ENTIDAD A ON A.ORI_ENT_COD=D.ORI_ENT_COD 
      --INNER JOIN E_CRO C ON C.CRO_NUM=A.EXT_NUM
      WHERE 
      --CRO_TRA=3 AND CRO_FEF is null   AND 
      B.COD_AMBITO=AMBITO 
      and HORAS_ASIGNADAS<HORAS_SOLICITADAS
      and HORAS_ASIGNADAS=0
      ;
  
    BLOQUES_CONSUMIDO:=0;
    DBMS_OUTPUT.PUT_LINE('----fase4---------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('AMBITO: '||ambito );
    DBMS_OUTPUT.PUT_LINE('VALORACION_TOT: '||VALORACION_TOT );
    DBMS_OUTPUT.PUT_LINE('HORAS_AMBITO: '||HORAS_AMBITO);
    DBMS_OUTPUT.PUT_LINE('BLOQUES_ASIGNADOS: '||BLOQUES_ASIGNADOS);
        
        
        
        
        
    FOR REG_EXP IN EXPEDIENTES6 (AMBITO) LOOP
      entidad:=REG_EXP.ORI_ENT_COD;
      ubicacion:=REG_EXP.ORI_ORIENT_UBIC_COD;
      BLOQUES_SOLICITADOS:=REG_EXP.HORAS_SOLICITADAS;
      PUNT_ENTIDAD:=REG_EXP.VALORACION;
      
      
      DBMS_OUTPUT.PUT_LINE('RECORRO CURSOR EXPEDIENTE: entidad: '||entidad|| '                ubicacion'||ubicacion);
      PORCEN_ENTIDAD := PUNT_ENTIDAD/VALORACION_TOT;
      DBMS_OUTPUT.PUT_LINE('BLOQUES_A_ASIGNAR '||PUNT_ENTIDAD*(HORAS_AMBITO-BLOQUES_ASIGNADOS)/VALORACION_TOT );
      
      SELECT ROUND(PUNT_ENTIDAD*(HORAS_AMBITO-BLOQUES_ASIGNADOS)/VALORACION_TOT ,0) INTO BLOQUES_ENTIDAD FROM DUAL;
      DBMS_OUTPUT.PUT_LINE('BLOQUES_A_ASIGNAR_REDONDEADO '||BLOQUES_ENTIDAD );
     

      update ORI14_TMP_ADJUDICACION
      set 
      HORAS_ASIGNADAS_TEMP=BLOQUES_ENTIDAD
      where ORI_ORIENT_UBIC_COD=ubicacion;
      commit;
      
      
      
      END LOOP;
      
      
      --fase 4. de lo que le correspondería ir dando hasta llegar al maximo por orden de puntuacion decreciente
        BLOQUES_CONSUMIDO:=0;
    FOR REG_EXP IN EXPEDIENTES7 (AMBITO) LOOP
      ubicacion:=REG_EXP.ORI_ORIENT_UBIC_COD;
      BLOQUES_ENTIDAD:=REG_EXP.HORAS_ASIGNADAS_TEMP;      
      
      
        IF BLOQUES_CONSUMIDO+BLOQUES_ENTIDAD>=HORAS_AMBITO-BLOQUES_ASIGNADOS THEN
          BLOQUES_ENTIDAD:=HORAS_AMBITO-BLOQUES_ASIGNADOS-BLOQUES_CONSUMIDO;
          BLOQUES_CONSUMIDO:=BLOQUES_CONSUMIDO+BLOQUES_ENTIDAD;
          
        ELSE 
          BLOQUES_CONSUMIDO:=BLOQUES_CONSUMIDO+BLOQUES_ENTIDAD;
                     
        END IF;
     
      DBMS_OUTPUT.PUT_LINE('BLOQUES_A_ASIGNAR_REDONDEADO '||BLOQUES_ENTIDAD );
      UPDATE ORI14_TMP_ADJUDICACION SET HORAS_ASIGNADAS=HORAS_ASIGNADAS+BLOQUES_ENTIDAD WHERE ORI_ORIENT_UBIC_COD=ubicacion;
      commit;
      END LOOP;
      
    
      END IF;
      
      SELECT SUM(NVL(HORAS_ASIGNADAS,0)) INTO BLOQUES_ASIGNADOS FROM ORI14_TMP_ADJUDICACION
      WHERE COD_AMBITO=AMBITO; 
      
      IF HORAS_AMBITO-BLOQUES_ASIGNADOS > 0 THEN
      
      
        SELECT COUNT(*) INTO NUM_ACEPTAN_MAS
        FROM  ORI14_TMP_ADJUDICACION B
        inner join  ORI14_ORI_UBIC a on a.ORI_ORIENT_UBIC_COD=b.ORI_ORIENT_UBIC_COD
        inner join ori14_entidad c on c.ORI_ENT_COD=a.ORI_ENT_COD
      WHERE COD_AMBITO=AMBITO 
      and (HORAS_ASIGNADAS<HORAS_SOLICITADAS OR C.ORI_ENT_ACEPTA_MAS=1) ;
      
      if (num_aceptan_mas<>0) then
      
      PROPORCION:= ( HORAS_AMBITO-BLOQUES_ASIGNADOS )/NUM_ACEPTAN_MAS;
      
         
       FOR REG_EXP IN EXPEDIENTES8 (AMBITO) LOOP
        ubicacion:=REG_EXP.ORI_ORIENT_UBIC_COD;
        
      UPDATE ORI14_TMP_ADJUDICACION SET HORAS_ASIGNADAS=HORAS_ASIGNADAS+PROPORCION WHERE ORI_ORIENT_UBIC_COD=ubicacion;
      commit;
       end loop;
       end if;
       end if;
  END LOOP;
      
  
  MENSAJE := 'OK';
  
  
  Dbms_Output.Put_Line('FIN DEL PROCESO' ||TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS'));   

END adjudica_orientacion_2014;