CREATE TABLE "MELANBIDE37_CONT_CLAVES"
  (
    "COD_ORGANIZACION" NUMBER(3,0) NOT NULL ENABLE,
	"TIPO_CONTADOR"    VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "ANO_CONTADOR"     NUMBER(4,0) NOT NULL ENABLE,
    "NUM_CONTADOR"     NUMBER(6,0) NOT NULL ENABLE,
   CONSTRAINT "MELANBIDE37_CONT_CLAVES_PK" PRIMARY KEY ("COD_ORGANIZACION", "TIPO_CONTADOR", "ANO_CONTADOR", "NUM_CONTADOR") 
  );
