Insert into ECA14_DISCAPGRAVEDAD (COD_GRAVEDAD,NOMBRE_C,NOMBRE_E) values (1,'Menor del 33%','Menor del 33%');
Insert into ECA14_DISCAPGRAVEDAD (COD_GRAVEDAD,NOMBRE_C,NOMBRE_E) values (2,'Entre 33 y 65%','Entre 33 y 65%');
Insert into ECA14_DISCAPGRAVEDAD (COD_GRAVEDAD,NOMBRE_C,NOMBRE_E) values (3,'Mayor del 65%','Mayor del 65%');
COMMIT;
----------------------------------------------------------------------------------------------
Insert into ECA14_TIPOCONTRATO (COD_TIPOCONTRATO,NOMBRE_C,NOMBRE_E) values (1,'Indefinido','Indefinido_eus');
Insert into ECA14_TIPOCONTRATO (COD_TIPOCONTRATO,NOMBRE_C,NOMBRE_E) values (2,'Temporal','Temporal_eus');
COMMIT;
----------------------------------------------------------------------------------------------
Insert into ECA14_TIPODISCAPACIDAD (COD_TDISCAPACIDAD,NOMBRE_C,NOMBRE_E) values (1,'Psíquico','Psíquico');
Insert into ECA14_TIPODISCAPACIDAD (COD_TDISCAPACIDAD,NOMBRE_C,NOMBRE_E) values (2,'Físico','Físico');
Insert into ECA14_TIPODISCAPACIDAD (COD_TDISCAPACIDAD,NOMBRE_C,NOMBRE_E) values (3,'Sensorial','Sensorial');
COMMIT;
----------------------------------------------------------------------------------------------
Insert into ECA14_SECTORACT (COD_SECTOR,NOMBRE_C,NOMBRE_E) values (1,'ADMINISTRACION Y OFICINAS','ADMINISTRACION Y OFICINAS');
Insert into ECA14_SECTORACT (COD_SECTOR,NOMBRE_C,NOMBRE_E) values (2,'AGRARIO','AGRARIO');
Insert into ECA14_SECTORACT (COD_SECTOR,NOMBRE_C,NOMBRE_E) values (3,'ARTESANIA','ARTESANIA');
Insert into ECA14_SECTORACT (COD_SECTOR,NOMBRE_C,NOMBRE_E) values (4,'AUTOMOCION','AUTOMOCION');
Insert into ECA14_SECTORACT (COD_SECTOR,NOMBRE_C,NOMBRE_E) values (5,'COMERCIO','COMERCIO');
Insert into ECA14_SECTORACT (COD_SECTOR,NOMBRE_C,NOMBRE_E) values (6,'DOCENCIA E INVESTIGACION','DOCENCIA E INVESTIGACION');
Insert into ECA14_SECTORACT (COD_SECTOR,NOMBRE_C,NOMBRE_E) values (7,'EDIFICACION Y OBRAS PUBLICAS','EDIFICACION Y OBRAS PUBLICAS');
Insert into ECA14_SECTORACT (COD_SECTOR,NOMBRE_C,NOMBRE_E) values (8,'INDUSTRIA PESADA Y CONSTRUCCIONES METALICAS','INDUSTRIA PESADA Y CONSTRUCCIONES METALICAS');
Insert into ECA14_SECTORACT (COD_SECTOR,NOMBRE_C,NOMBRE_E) values (9,'INDUSTRIAS ALIMENTARIAS','INDUSTRIAS ALIMENTARIAS');
Insert into ECA14_SECTORACT (COD_SECTOR,NOMBRE_C,NOMBRE_E) values (10,'INDUSTRIAS DE FABRICACION EQUIPOS ELECTROMECANICOS','INDUSTRIAS DE FABRICACION EQUIPOS ELECTROMECANICOS');
Insert into ECA14_SECTORACT (COD_SECTOR,NOMBRE_C,NOMBRE_E) values (11,'INDUSTRIA DE MADERA Y CORCHO','INDUSTRIA DE MADERA Y CORCHO');
Insert into ECA14_SECTORACT (COD_SECTOR,NOMBRE_C,NOMBRE_E) values (12,'INDUSTRIAS GRAFICAS','INDUSTRIAS GRAFICAS');
Insert into ECA14_SECTORACT (COD_SECTOR,NOMBRE_C,NOMBRE_E) values (13,'INDUSTRIAS MANUFACTURERAS DIVERSAS','INDUSTRIAS MANUFACTURERAS DIVERSAS');
Insert into ECA14_SECTORACT (COD_SECTOR,NOMBRE_C,NOMBRE_E) values (14,'INDUSTRIAS QUIMICAS','INDUSTRIAS QUIMICAS');
Insert into ECA14_SECTORACT (COD_SECTOR,NOMBRE_C,NOMBRE_E) values (15,'INDUSTRIAS TEXTILES','INDUSTRIAS TEXTILES');
Insert into ECA14_SECTORACT (COD_SECTOR,NOMBRE_C,NOMBRE_E) values (16,'INFORMACION Y MANIFESTACIONES ARTISTICAS','INFORMACION Y MANIFESTACIONES ARTISTICAS');
Insert into ECA14_SECTORACT (COD_SECTOR,NOMBRE_C,NOMBRE_E) values (17,'MANTENIMIENTO Y REPARACION','MANTENIMIENTO Y REPARACION');
Insert into ECA14_SECTORACT (COD_SECTOR,NOMBRE_C,NOMBRE_E) values (18,'MINERIA Y PRIMERAS TRASFORMACIONES','MINERIA Y PRIMERAS TRASFORMACIONES');
Insert into ECA14_SECTORACT (COD_SECTOR,NOMBRE_C,NOMBRE_E) values (19,'MONTAJE E INSTALACION','MONTAJE E INSTALACION');
Insert into ECA14_SECTORACT (COD_SECTOR,NOMBRE_C,NOMBRE_E) values (20,'PESCA Y ACUICULTURA','PESCA Y ACUICULTURA');
Insert into ECA14_SECTORACT (COD_SECTOR,NOMBRE_C,NOMBRE_E) values (21,'PIEL Y CUERO','PIEL Y CUERO');
Insert into ECA14_SECTORACT (COD_SECTOR,NOMBRE_C,NOMBRE_E) values (22,'PRODUCCION TRASFORMACION DE ENERGIA Y AGUA','PRODUCCION TRASFORMACION DE ENERGIA Y AGUA');
Insert into ECA14_SECTORACT (COD_SECTOR,NOMBRE_C,NOMBRE_E) values (23,'SANIDAD','SANIDAD');
Insert into ECA14_SECTORACT (COD_SECTOR,NOMBRE_C,NOMBRE_E) values (24,'SEGUROS Y FINANZAS','SEGUROS Y FINANZAS');
Insert into ECA14_SECTORACT (COD_SECTOR,NOMBRE_C,NOMBRE_E) values (25,'SERVICIOS A LA COMUNIDAD Y PERSONALES','SERVICIOS A LA COMUNIDAD Y PERSONALES');
Insert into ECA14_SECTORACT (COD_SECTOR,NOMBRE_C,NOMBRE_E) values (26,'SERVICIOS  A LAS EMPRESAS','SERVICIOS  A LAS EMPRESAS');
Insert into ECA14_SECTORACT (COD_SECTOR,NOMBRE_C,NOMBRE_E) values (27,'TRANSPORTES Y COMUNICACIONES','TRANSPORTES Y COMUNICACIONES');
Insert into ECA14_SECTORACT (COD_SECTOR,NOMBRE_C,NOMBRE_E) values (28,'TURISMO Y HOSTELERIA','TURISMO Y HOSTELERIA');
COMMIT;
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Insert into ECA14_CUMPLELISMI (COD_CUMPLE,NOMBRE_C,NOMBRE_E) values (1,'SI','SI');
Insert into ECA14_CUMPLELISMI (COD_CUMPLE,NOMBRE_C,NOMBRE_E) values (2,'NO','NO');
Insert into ECA14_CUMPLELISMI (COD_CUMPLE,NOMBRE_C,NOMBRE_E) values (3,'CERTIFICADO','CERTIFICADO');
Insert into ECA14_CUMPLELISMI (COD_CUMPLE,NOMBRE_C,NOMBRE_E) values (4,'NO PROCEDE','NO PROCEDE');
COMMIT;
----------------------------------------------------------------------------------------------
Insert into ECA14_RESULTADO (COD_RESULTADO,NOMBRE_C,NOMBRE_E) values (1,'INFORMADA','INFORMADA');
Insert into ECA14_RESULTADO (COD_RESULTADO,NOMBRE_C,NOMBRE_E) values (2,'INTERESADA','INTERESADA');
Insert into ECA14_RESULTADO (COD_RESULTADO,NOMBRE_C,NOMBRE_E) values (3,'VINCULADA','VINCULADA');
COMMIT;
----------------------------------------------------------------------------------------------
