ALTER TABLE ECA14_RES_PREPARADORES ADD (IMPORTE_SEGUIMIENTOS_LIM NUMBER(8,2));
ALTER TABLE ECA14_RES_PROSPECTORES ADD (IMPORTE_VISITAS_CONC NUMBER(8,2));
ALTER TABLE ECA14_VIS_PROSPECTORES MODIFY (ECA_VIS_CIF VARCHAR2(15));