//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.04 at 02:03:36 PM BST 
//


package es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.xml.tratarrespuesta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Respuesta">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="IdTraza" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="IdPeticion" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="FechaRespuesta" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="NumElementos" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="Estado">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Codigo" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="Descripcion" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="TipoCertificado" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="Transmisiones">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Transmision">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="IdTraza" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="IdSolicitud" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="FechaEmisionCertificado" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="Territorio" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="TipoTramite" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="IdExpediente" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="TipoDocumentacion" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="DatoDocumentacion" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="NombreTitular" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="Apellido1Titular" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="Apellido2Titular" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="RazonSocial" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="Resultado" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="Descripcion" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="MotivosNoCumple" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "respuesta"
})
@XmlRootElement(name = "Respuestas")
public class Respuestas {

    @XmlElement(name = "Respuesta", required = true)
    protected Respuestas.Respuesta respuesta;

    /**
     * Gets the value of the respuesta property.
     * 
     * @return
     *     possible String is
     *     {@link Respuestas.Respuesta }
     *     
     */
    public Respuestas.Respuesta getRespuesta() {
        return respuesta;
    }

    /**
     * Sets the value of the respuesta property.
     * 
     * @param value
     *     allowed String is
     *     {@link Respuestas.Respuesta }
     *     
     */
    public void setRespuesta(Respuestas.Respuesta value) {
        this.respuesta = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="IdTraza" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="IdPeticion" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="FechaRespuesta" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="NumElementos" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="Estado">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Codigo" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="Descripcion" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="TipoCertificado" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="Transmisiones">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Transmision">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="IdTraza" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="IdSolicitud" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="FechaEmisionCertificado" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="Territorio" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="TipoTramite" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="IdExpediente" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="TipoDocumentacion" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="DatoDocumentacion" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="NombreTitular" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="Apellido1Titular" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="Apellido2Titular" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="RazonSocial" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="Resultado" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="Descripcion" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="MotivosNoCumple" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "idTraza",
        "idPeticion",
        "fechaRespuesta",
        "numElementos",
        "estado",
        "tipoCertificado",
        "transmisiones"
    })
    public static class Respuesta {

        @XmlElement(name = "IdTraza", required = true)
        protected String idTraza;
        @XmlElement(name = "IdPeticion", required = true)
        protected String idPeticion;
        @XmlElement(name = "FechaRespuesta", required = true)
        protected String fechaRespuesta;
        @XmlElement(name = "NumElementos", required = true)
        protected String numElementos;
        @XmlElement(name = "Estado", required = true)
        protected Respuestas.Respuesta.Estado estado;
        @XmlElement(name = "TipoCertificado", required = true)
        protected String tipoCertificado;
        @XmlElement(name = "Transmisiones", required = true)
        protected Respuestas.Respuesta.Transmisiones transmisiones;

        /**
         * Gets the value of the idTraza property.
         * 
         * @return
         *     possible String is
         *     {@link String }
         *     
         */
        public String getIdTraza() {
            return idTraza;
        }

        /**
         * Sets the value of the idTraza property.
         * 
         * @param value
         *     allowed String is
         *     {@link String }
         *     
         */
        public void setIdTraza(String value) {
            this.idTraza = value;
        }

        /**
         * Gets the value of the idPeticion property.
         * 
         * @return
         *     possible String is
         *     {@link String }
         *     
         */
        public String getIdPeticion() {
            return idPeticion;
        }

        /**
         * Sets the value of the idPeticion property.
         * 
         * @param value
         *     allowed String is
         *     {@link String }
         *     
         */
        public void setIdPeticion(String value) {
            this.idPeticion = value;
        }

        /**
         * Gets the value of the fechaRespuesta property.
         * 
         * @return
         *     possible String is
         *     {@link String }
         *     
         */
        public String getFechaRespuesta() {
            return fechaRespuesta;
        }

        /**
         * Sets the value of the fechaRespuesta property.
         * 
         * @param value
         *     allowed String is
         *     {@link String }
         *     
         */
        public void setFechaRespuesta(String value) {
            this.fechaRespuesta = value;
        }

        /**
         * Gets the value of the numElementos property.
         * 
         * @return
         *     possible String is
         *     {@link String }
         *     
         */
        public String getNumElementos() {
            return numElementos;
        }

        /**
         * Sets the value of the numElementos property.
         * 
         * @param value
         *     allowed String is
         *     {@link String }
         *     
         */
        public void setNumElementos(String value) {
            this.numElementos = value;
        }

        /**
         * Gets the value of the estado property.
         * 
         * @return
         *     possible String is
         *     {@link Respuestas.Respuesta.Estado }
         *     
         */
        public Respuestas.Respuesta.Estado getEstado() {
            return estado;
        }

        /**
         * Sets the value of the estado property.
         * 
         * @param value
         *     allowed String is
         *     {@link Respuestas.Respuesta.Estado }
         *     
         */
        public void setEstado(Respuestas.Respuesta.Estado value) {
            this.estado = value;
        }

        /**
         * Gets the value of the tipoCertificado property.
         * 
         * @return
         *     possible String is
         *     {@link String }
         *     
         */
        public String getTipoCertificado() {
            return tipoCertificado;
        }

        /**
         * Sets the value of the tipoCertificado property.
         * 
         * @param value
         *     allowed String is
         *     {@link String }
         *     
         */
        public void setTipoCertificado(String value) {
            this.tipoCertificado = value;
        }

        /**
         * Gets the value of the transmisiones property.
         * 
         * @return
         *     possible String is
         *     {@link Respuestas.Respuesta.Transmisiones }
         *     
         */
        public Respuestas.Respuesta.Transmisiones getTransmisiones() {
            return transmisiones;
        }

        /**
         * Sets the value of the transmisiones property.
         * 
         * @param value
         *     allowed String is
         *     {@link Respuestas.Respuesta.Transmisiones }
         *     
         */
        public void setTransmisiones(Respuestas.Respuesta.Transmisiones value) {
            this.transmisiones = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Codigo" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="Descripcion" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "codigo",
            "descripcion"
        })
        public static class Estado {

            @XmlElement(name = "Codigo", required = true)
            protected String codigo;
            @XmlElement(name = "Descripcion", required = true)
            protected String descripcion;

            /**
             * Gets the value of the codigo property.
             * 
             * @return
             *     possible String is
             *     {@link String }
             *     
             */
            public String getCodigo() {
                return codigo;
            }

            /**
             * Sets the value of the codigo property.
             * 
             * @param value
             *     allowed String is
             *     {@link String }
             *     
             */
            public void setCodigo(String value) {
                this.codigo = value;
            }

            /**
             * Gets the value of the descripcion property.
             * 
             * @return
             *     possible String is
             *     {@link String }
             *     
             */
            public String getDescripcion() {
                return descripcion;
            }

            /**
             * Sets the value of the descripcion property.
             * 
             * @param value
             *     allowed String is
             *     {@link String }
             *     
             */
            public void setDescripcion(String value) {
                this.descripcion = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Transmision">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="IdTraza" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="IdSolicitud" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="FechaEmisionCertificado" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="Territorio" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="TipoTramite" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="IdExpediente" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="TipoDocumentacion" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="DatoDocumentacion" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="NombreTitular" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="Apellido1Titular" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="Apellido2Titular" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="RazonSocial" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="Resultado" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="Descripcion" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="MotivosNoCumple" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "transmision"
        })
        public static class Transmisiones {

            @XmlElement(name = "Transmision", required = true)
            protected Respuestas.Respuesta.Transmisiones.Transmision transmision;

            /**
             * Gets the value of the transmision property.
             * 
             * @return
             *     possible String is
             *     {@link Respuestas.Respuesta.Transmisiones.Transmision }
             *     
             */
            public Respuestas.Respuesta.Transmisiones.Transmision getTransmision() {
                return transmision;
            }

            /**
             * Sets the value of the transmision property.
             * 
             * @param value
             *     allowed String is
             *     {@link Respuestas.Respuesta.Transmisiones.Transmision }
             *     
             */
            public void setTransmision(Respuestas.Respuesta.Transmisiones.Transmision value) {
                this.transmision = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="IdTraza" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="IdSolicitud" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="FechaEmisionCertificado" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="Territorio" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="TipoTramite" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="IdExpediente" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="TipoDocumentacion" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="DatoDocumentacion" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="NombreTitular" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="Apellido1Titular" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="Apellido2Titular" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="RazonSocial" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="Resultado" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="Descripcion" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="MotivosNoCumple" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "idTraza",
                "idSolicitud",
                "fechaEmisionCertificado",
                "territorio",
                "tipoTramite",
                "idExpediente",
                "tipoDocumentacion",
                "datoDocumentacion",
                "nombreTitular",
                "apellido1Titular",
                "apellido2Titular",
                "razonSocial",
                "resultado",
                "descripcion",
                "motivosNoCumple"
            })
            public static class Transmision {

                @XmlElement(name = "IdTraza", required = true)
                protected String idTraza;
                @XmlElement(name = "IdSolicitud", required = true)
                protected String idSolicitud;
                @XmlElement(name = "FechaEmisionCertificado", required = true)
                protected String fechaEmisionCertificado;
                @XmlElement(name = "Territorio", required = true)
                protected String territorio;
                @XmlElement(name = "TipoTramite", required = true)
                protected String tipoTramite;
                @XmlElement(name = "IdExpediente", required = true)
                protected String idExpediente;
                @XmlElement(name = "TipoDocumentacion", required = true)
                protected String tipoDocumentacion;
                @XmlElement(name = "DatoDocumentacion", required = true)
                protected String datoDocumentacion;
                @XmlElement(name = "NombreTitular", required = true)
                protected String nombreTitular;
                @XmlElement(name = "Apellido1Titular", required = true)
                protected String apellido1Titular;
                @XmlElement(name = "Apellido2Titular", required = true)
                protected String apellido2Titular;
                @XmlElement(name = "RazonSocial", required = true)
                protected String razonSocial;
                @XmlElement(name = "Resultado", required = true)
                protected String resultado;
                @XmlElement(name = "Descripcion", required = true)
                protected String descripcion;
                @XmlElement(name = "MotivosNoCumple", required = true)
                protected String motivosNoCumple;

                /**
                 * Gets the value of the idTraza property.
                 * 
                 * @return
                 *     possible String is
                 *     {@link String }
                 *     
                 */
                public String getIdTraza() {
                    return idTraza;
                }

                /**
                 * Sets the value of the idTraza property.
                 * 
                 * @param value
                 *     allowed String is
                 *     {@link String }
                 *     
                 */
                public void setIdTraza(String value) {
                    this.idTraza = value;
                }

                /**
                 * Gets the value of the idSolicitud property.
                 * 
                 * @return
                 *     possible String is
                 *     {@link String }
                 *     
                 */
                public String getIdSolicitud() {
                    return idSolicitud;
                }

                /**
                 * Sets the value of the idSolicitud property.
                 * 
                 * @param value
                 *     allowed String is
                 *     {@link String }
                 *     
                 */
                public void setIdSolicitud(String value) {
                    this.idSolicitud = value;
                }

                /**
                 * Gets the value of the fechaEmisionCertificado property.
                 * 
                 * @return
                 *     possible String is
                 *     {@link String }
                 *     
                 */
                public String getFechaEmisionCertificado() {
                    return fechaEmisionCertificado;
                }

                /**
                 * Sets the value of the fechaEmisionCertificado property.
                 * 
                 * @param value
                 *     allowed String is
                 *     {@link String }
                 *     
                 */
                public void setFechaEmisionCertificado(String value) {
                    this.fechaEmisionCertificado = value;
                }

                /**
                 * Gets the value of the territorio property.
                 * 
                 * @return
                 *     possible String is
                 *     {@link String }
                 *     
                 */
                public String getTerritorio() {
                    return territorio;
                }

                /**
                 * Sets the value of the territorio property.
                 * 
                 * @param value
                 *     allowed String is
                 *     {@link String }
                 *     
                 */
                public void setTerritorio(String value) {
                    this.territorio = value;
                }

                /**
                 * Gets the value of the tipoTramite property.
                 * 
                 * @return
                 *     possible String is
                 *     {@link String }
                 *     
                 */
                public String getTipoTramite() {
                    return tipoTramite;
                }

                /**
                 * Sets the value of the tipoTramite property.
                 * 
                 * @param value
                 *     allowed String is
                 *     {@link String }
                 *     
                 */
                public void setTipoTramite(String value) {
                    this.tipoTramite = value;
                }

                /**
                 * Gets the value of the idExpediente property.
                 * 
                 * @return
                 *     possible String is
                 *     {@link String }
                 *     
                 */
                public String getIdExpediente() {
                    return idExpediente;
                }

                /**
                 * Sets the value of the idExpediente property.
                 * 
                 * @param value
                 *     allowed String is
                 *     {@link String }
                 *     
                 */
                public void setIdExpediente(String value) {
                    this.idExpediente = value;
                }

                /**
                 * Gets the value of the tipoDocumentacion property.
                 * 
                 * @return
                 *     possible String is
                 *     {@link String }
                 *     
                 */
                public String getTipoDocumentacion() {
                    return tipoDocumentacion;
                }

                /**
                 * Sets the value of the tipoDocumentacion property.
                 * 
                 * @param value
                 *     allowed String is
                 *     {@link String }
                 *     
                 */
                public void setTipoDocumentacion(String value) {
                    this.tipoDocumentacion = value;
                }

                /**
                 * Gets the value of the datoDocumentacion property.
                 * 
                 * @return
                 *     possible String is
                 *     {@link String }
                 *     
                 */
                public String getDatoDocumentacion() {
                    return datoDocumentacion;
                }

                /**
                 * Sets the value of the datoDocumentacion property.
                 * 
                 * @param value
                 *     allowed String is
                 *     {@link String }
                 *     
                 */
                public void setDatoDocumentacion(String value) {
                    this.datoDocumentacion = value;
                }

                /**
                 * Gets the value of the nombreTitular property.
                 * 
                 * @return
                 *     possible String is
                 *     {@link String }
                 *     
                 */
                public String getNombreTitular() {
                    return nombreTitular;
                }

                /**
                 * Sets the value of the nombreTitular property.
                 * 
                 * @param value
                 *     allowed String is
                 *     {@link String }
                 *     
                 */
                public void setNombreTitular(String value) {
                    this.nombreTitular = value;
                }

                /**
                 * Gets the value of the apellido1Titular property.
                 * 
                 * @return
                 *     possible String is
                 *     {@link String }
                 *     
                 */
                public String getApellido1Titular() {
                    return apellido1Titular;
                }

                /**
                 * Sets the value of the apellido1Titular property.
                 * 
                 * @param value
                 *     allowed String is
                 *     {@link String }
                 *     
                 */
                public void setApellido1Titular(String value) {
                    this.apellido1Titular = value;
                }

                /**
                 * Gets the value of the apellido2Titular property.
                 * 
                 * @return
                 *     possible String is
                 *     {@link String }
                 *     
                 */
                public String getApellido2Titular() {
                    return apellido2Titular;
                }

                /**
                 * Sets the value of the apellido2Titular property.
                 * 
                 * @param value
                 *     allowed String is
                 *     {@link String }
                 *     
                 */
                public void setApellido2Titular(String value) {
                    this.apellido2Titular = value;
                }

                /**
                 * Gets the value of the razonSocial property.
                 * 
                 * @return
                 *     possible String is
                 *     {@link String }
                 *     
                 */
                public String getRazonSocial() {
                    return razonSocial;
                }

                /**
                 * Sets the value of the razonSocial property.
                 * 
                 * @param value
                 *     allowed String is
                 *     {@link String }
                 *     
                 */
                public void setRazonSocial(String value) {
                    this.razonSocial = value;
                }

                /**
                 * Gets the value of the resultado property.
                 * 
                 * @return
                 *     possible String is
                 *     {@link String }
                 *     
                 */
                public String getResultado() {
                    return resultado;
                }

                /**
                 * Sets the value of the resultado property.
                 * 
                 * @param value
                 *     allowed String is
                 *     {@link String }
                 *     
                 */
                public void setResultado(String value) {
                    this.resultado = value;
                }

                /**
                 * Gets the value of the descripcion property.
                 * 
                 * @return
                 *     possible String is
                 *     {@link String }
                 *     
                 */
                public String getDescripcion() {
                    return descripcion;
                }

                /**
                 * Sets the value of the descripcion property.
                 * 
                 * @param value
                 *     allowed String is
                 *     {@link String }
                 *     
                 */
                public void setDescripcion(String value) {
                    this.descripcion = value;
                }

                /**
                 * Gets the value of the motivosNoCumple property.
                 * 
                 * @return
                 *     possible String is
                 *     {@link String }
                 *     
                 */
                public String getMotivosNoCumple() {
                    return motivosNoCumple;
                }

                /**
                 * Sets the value of the motivosNoCumple property.
                 * 
                 * @param value
                 *     allowed String is
                 *     {@link String }
                 *     
                 */
                public void setMotivosNoCumple(String value) {
                    this.motivosNoCumple = value;
                }

            }

        }

    }

}
