--SECUENCIA
CREATE SEQUENCE SEQ_MELANBIDE68_TIPDOC_LANBIDE MINVALUE 1000 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1000 NOCACHE ORDER NOCYCLE;

--MODIFICAR TIPDOC_ID A NUMBER 5 Y EN LAS FK
ALTER TABLE MELANBIDE68_TIPDOC_LANBIDE MODIFY TIPDOC_ID NUMBER(5,0);
ALTER TABLE MELANBIDE68_DOKUSI_METADATOS MODIFY TIPDOC_ID NUMBER(5,0);
ALTER TABLE MELANBIDE68_DOKUSI_TIPDOC_LANB MODIFY TIPDOC_ID NUMBER(5,0);
ALTER TABLE R_RED MODIFY RED_TIPODOC_ID NUMBER(5,0);

--AÑADIR CAMPOS
ALTER TABLE MELANBIDE68_TIPDOC_LANBIDE ADD (
    DESCTIPDOC_LANBIDE_ES VARCHAR2(500 BYTE) DEFAULT ' ', 
	DESCTIPDOC_LANBIDE_EU VARCHAR2(500 BYTE) DEFAULT ' ', 
	CODTIPDOC NUMBER(5,0));
    
--COMENTARIOS DE COLUMNA
COMMENT ON COLUMN MELANBIDE68_TIPDOC_LANBIDE.DESCTIPDOC_LANBIDE_ES IS 'Descripción larga castellano';
COMMENT ON COLUMN MELANBIDE68_TIPDOC_LANBIDE.DESCTIPDOC_LANBIDE_EU IS 'Descripción Larga euskera';
COMMENT ON COLUMN MELANBIDE68_TIPDOC_LANBIDE.CODTIPDOC IS 'Código externo del tipo documental, índice único';
    
--CODTIPDOC A TIPDOC_ID
UPDATE MELANBIDE68_TIPDOC_LANBIDE SET CODTIPDOC = TIPDOC_ID;

--CODTIPDOC NOT NULL
ALTER TABLE MELANBIDE68_TIPDOC_LANBIDE MODIFY CODTIPDOC NOT NULL ENABLE;

--CODTIPDOC ÚNICO
ALTER TABLE MELANBIDE68_TIPDOC_LANBIDE ADD CONSTRAINT CODTIPDOC_UN UNIQUE (CODTIPDOC);

--ELIMINAR CAMPOS DE DESCRIPCIONES
ALTER TABLE MELANBIDE68_TIPDOC_PROC DROP (TIPDOC_LANBIDE_ES, TIPDOC_LANBIDE_EU);

--MODIFICAR TIPDOC_ID A NUMBER 5
ALTER TABLE MELANBIDE68_TIPDOC_PROC MODIFY TIPDOC_ID NUMBER(5,0);

--FK A MELANBIDE68_TIPDOC_LANBIDE
ALTER TABLE MELANBIDE68_TIPDOC_PROC ADD CONSTRAINT MELANBIDE68_TIPDOC_PROC_FK1 FOREIGN KEY (TIPDOC_ID) REFERENCES MELANBIDE68_TIPDOC_LANBIDE (TIPDOC_ID) ENABLE;
