DELETE FROM MELANBIDE50_DISPONRECURSOS ;
COMMIT;
alter table MELANBIDE50_DISPONRECURSOS 
  modify DRE_AUL VARCHAR(200);
alter table MELANBIDE50_DISPONRECURSOS 
  modify DRE_TAL VARCHAR(200);
alter table MELANBIDE50_DISPONRECURSOS 
  modify DRE_AUTA VARCHAR(200);
alter table MELANBIDE50_DISPONRECURSOS 
  modify DRE_CAPR VARCHAR(200);