
package es.altia.flexia.integracion.moduloexterno.melanbide54.cliente.altaagencia;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IESISPEPort", targetNamespace = "http://namespace.softwareag.com/entirex/xml/mapping")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IESISPEPort {


    /**
     * 
     * @param areaCOMUNICACION
     * @return
     *     returns es.altia.flexia.integracion.moduloexterno.melanbide54.cliente.altaagencia.IWACALASResponse.AREACOMUNICACION
     */
    @WebMethod(operationName = "IWACALAS", action = "IWACALAS")
    @WebResult(name = "AREA-COMUNICACION", targetNamespace = "")
    @RequestWrapper(localName = "IWACALAS", targetNamespace = "urn:com-softwareag-entirex-rpc:IESISPE", className = "es.altia.flexia.integracion.moduloexterno.melanbide54.cliente.altaagencia.IWACALAS")
    @ResponseWrapper(localName = "IWACALASResponse", targetNamespace = "urn:com-softwareag-entirex-rpc:IESISPE", className = "es.altia.flexia.integracion.moduloexterno.melanbide54.cliente.altaagencia.IWACALASResponse")
    public es.altia.flexia.integracion.moduloexterno.melanbide54.cliente.altaagencia.IWACALASResponse.AREACOMUNICACION iwacalas(
        @WebParam(name = "AREA-COMUNICACION", targetNamespace = "")
        es.altia.flexia.integracion.moduloexterno.melanbide54.cliente.altaagencia.IWACALAS.AREACOMUNICACION areaCOMUNICACION);

}
