CREATE TABLE COLEC_AMBITO 
(
  COLEC_COD_AMBITO NUMBER(5, 0) NOT NULL 
, COLEC_DESC_AMBITO VARCHAR2(20 BYTE) 
--, COLEC_FEC_SYSDATE DATE 
, CONSTRAINT COLEC_AMBITO_PK PRIMARY KEY 
  (
    COLEC_COD_AMBITO 
  )
  ENABLE 
);

CREATE TABLE COLEC_COMARCAS
(
  COLEC_COD_COMARCA NUMBER NOT NULL 
, COLEC_DESC_COMARCA VARCHAR2(50 BYTE) 
, COLEC_COD_AMBITO NUMBER
--, COLEC_FEC_SYSDATE DATE 
, CONSTRAINT COLEC_COD_COMARCA_PK PRIMARY KEY 
  (
    COLEC_COD_COMARCA 
  )
  ENABLE 
);

CREATE TABLE COLEC_MUNICIPIO
(
  COLEC_COD_MUN NUMBER NOT NULL 
, COLEC_DESC_MUN VARCHAR2(50 BYTE) 
, COLEC_COD_COMARCA NUMBER
, COLEC_COD_TTHH NUMBER
--, COLEC_FEC_SYSDATE DATE 
, CONSTRAINT COLEC_COD_MUN_PK PRIMARY KEY 
  (
    COLEC_COD_MUN,COLEC_COD_COMARCA
  )
  ENABLE 
); 


-- DROP TABLE COLEC_ENTIDAD;
CREATE TABLE COLEC_ENTIDAD
(
COLEC_ENT_COD NUMBER NOT NULL 
,COLEC_EXP_EJE NUMBER(4,0) NOT NULL 
,COLEC_NUMEXP VARCHAR2(30 BYTE)  NOT NULL 
,COLEC_ANIO_CONVOCATORIA NUMBER(4,0) NOT NULL 
,COLEC_ENT_ESAGRUPACION		NUMBER(1,0)
,COLEC_ENT_TIPO_CIF VARCHAR2(20 BYTE)
,COLEC_ENT_CIF VARCHAR2(15 BYTE)
,COLEC_ENT_NOMBRE VARCHAR2(500 BYTE)
,COLEC_ENT_CENTESPEMPTH		NUMBER(1,0)
,COLEC_ENT_PARTMAYCEETH      NUMBER(1,0)
,COLEC_ENT_EMPINSERCIONTH    NUMBER(1,0)
,COLEC_ENT_PROMOEMPINSTH     NUMBER(1,0)
,COLEC_ENT_NROTOTINTEG_AGRUP	NUMBER(3,0)
, CONSTRAINT COLEC_ENTIDAD_PK PRIMARY KEY 
  (
    COLEC_ENT_COD 
  )
  ENABLE 
);

CREATE TABLE COLEC_ENTIDAD_AGRUP_LIST
(
COLEC_ENT_COD NUMBER NOT NULL 
,COLEC_ENT_AGRUP_COD NUMBER NOT NULL 
,COLEC_NUMEXP VARCHAR2(30 BYTE)  NOT NULL 
,COLEC_ENT_TIPO_CIF VARCHAR2(20 BYTE)
,COLEC_ENT_CIF VARCHAR2(15 BYTE)
,COLEC_ENT_NOMBRE VARCHAR2(500 BYTE)
,COLEC_ENT_CENTESPEMPTH		NUMBER(1,0)
,COLEC_ENT_PARTMAYCEETH      NUMBER(1,0)
,COLEC_ENT_EMPINSERCIONTH    NUMBER(1,0)
,COLEC_ENT_PROMOEMPINSTH     NUMBER(1,0)
,COLEC_ENT_PORCEN_COMPROM_REALI     NUMBER(5,2)
, CONSTRAINT COLEC_ENTIDAD_AGRUP_LIST_PK PRIMARY KEY 
  (
    COLEC_ENT_COD 
  )
  ENABLE 
);


CREATE TABLE COLEC_SOLICITUD
(
COLEC_COD_SOLICITUD NUMBER NOT NULL 
,COLEC_NUMEXP VARCHAR2(20 BYTE) 
,COLEC_EXP_EJE NUMBER(4,0)
,COLEC_COL1_AR NUMBER(1,0)
,COLEC_COL1_BI NUMBER(1,0)
,COLEC_COL1_GI NUMBER(1,0)
,COLEC_COL2_AR NUMBER(1,0)
,COLEC_COL2_BI NUMBER(1,0)
,COLEC_COL2_GI NUMBER(1,0)
,COLEC_COL3_AR NUMBER(1,0)
,COLEC_COL3_BI NUMBER(1,0)
,COLEC_COL3_GI NUMBER(1,0)
,COLEC_COL4_AR NUMBER(1,0)
,COLEC_COL4_BI NUMBER(1,0)
,COLEC_COL4_GI NUMBER(1,0)
,COLEC1_ULT5_VAL NUMBER
,COLEC2_ULT5_VAL NUMBER
,COLEC_TOT_VAL NUMBER
--,COLEC_FEC_SYSDATE DATE 
, CONSTRAINT COLEC_SOLICITUD_PK PRIMARY KEY 
  (
    COLEC_COD_SOLICITUD 
  )
  ENABLE 
);

/*
CREATE TABLE COLEC_REPRESENTANTES
(
COLEC_COD_REPRESENTANTES NUMBER NOT NULL 
,COLEC_NUMEXP VARCHAR2(20 BYTE) 
,COLEC_EXP_EJE NUMBER(4,0)
,COLEC_TIPO_DOC NUMBER(2,0)
,COLEC_DOCUMENTO VARCHAR2(15 BYTE)
,COLEC_NOMBRE_APE VARCHAR2(300 BYTE)

, COLEC_FEC_SYSDATE DATE 
, CONSTRAINT COLEC_REPRESENTANTES_PK PRIMARY KEY 
  (
    COLEC_COD_REPRESENTANTES 
  )
  ENABLE 
);
*/
/*
CREATE TABLE COLEC_AVISOS
(
 COLEC_COD_AVISOS NUMBER NOT NULL 
,COLEC_NUMEXP VARCHAR2(20 BYTE) 
,COLEC_EXP_EJE NUMBER(4,0)
,COLEC_AVISOS VARCHAR2(300 BYTE)
,COLEC_AMBITO NUMBER(1,0)
,COLEC_COLECTIVO NUMBER(1,0)
,COLEC_FEC_SYSDATE DATE 
, CONSTRAINT COLEC_AVISOS_PK PRIMARY KEY 
  (
    COLEC_COD_AVISOS
  )
  ENABLE 
);

CREATE TABLE COLEC_CENTROS
(
  COLEC_COD_CENTROS NUMBER NOT NULL 
, COLEC_NUMEXP VARCHAR2(20 BYTE) 
,COLEC_EXP_EJE NUMBER(4,0)
,COLEC_AMBITO NUMBER(1,0)
,COLEC_COLECTIVO NUMBER(1,0)
,COLEC_COMARCA NUMBER
,COLEC_MUN NUMBER
,COLEC_DIRECCION VARCHAR2(200 BYTE) 
,COLEC_FEC_SYSDATE DATE 
, CONSTRAINT COLEC_CENTROS_PK PRIMARY KEY 
  (
    COLEC_COD_CENTROS
  )
  ENABLE 
);
*/

CREATE TABLE COLEC_TRAY
(
COLEC_COD_TRAY NUMBER NOT NULL 
,COLEC_COD_ENTIDAD NUMBER
,COLEC_NUMEXP VARCHAR2(20 BYTE) 
,COLEC_EXP_EJE NUMBER(4,0)

,COLEC1_DEC_327_2007 NUMBER(1,0)
,COLEC1_DEC_327_2008 NUMBER(1,0)
,COLEC1_DEC_327_2009 NUMBER(1,0)
,COLEC1_DEC_327_2010 NUMBER(1,0)

,COLEC1_MIN_94_2007 NUMBER(1,0)
,COLEC1_MIN_94_2008 NUMBER(1,0)
,COLEC1_MIN_94_2009 NUMBER(1,0)
,COLEC1_MIN_94_2010 NUMBER(1,0)
,COLEC1_MIN_94_2011 NUMBER(1,0)
,COLEC1_MIN_94_2012 NUMBER(1,0)
,COLEC1_MIN_94_2013 NUMBER(1,0)
,COLEC1_MIN_94_2014 NUMBER(1,0)
,COLEC1_MIN_94_2015 NUMBER(1,0)
,COLEC1_MIN_94_2016 NUMBER(1,0)

,COLEC1_MIN_98_2007 NUMBER(1,0)
,COLEC1_MIN_98_2008 NUMBER(1,0)
,COLEC1_MIN_98_2009 NUMBER(1,0)
,COLEC1_MIN_98_2010 NUMBER(1,0)
,COLEC1_MIN_98_2011 NUMBER(1,0)
,COLEC1_MIN_98_2012 NUMBER(1,0)
,COLEC1_MIN_98_2013 NUMBER(1,0)
,COLEC1_MIN_98_2014 NUMBER(1,0)
,COLEC1_MIN_98_2015 NUMBER(1,0)
,COLEC1_MIN_98_2016 NUMBER(1,0)

,COLEC1_TAS_03_2007 NUMBER(1,0)
,COLEC1_TAS_03_2008 NUMBER(1,0)
,COLEC1_TAS_03_2009 NUMBER(1,0)
,COLEC1_TAS_03_2010 NUMBER(1,0)
,COLEC1_TAS_03_2011 NUMBER(1,0)
,COLEC1_TAS_03_2012 NUMBER(1,0)
,COLEC1_TAS_03_2013 NUMBER(1,0)
,COLEC1_TAS_03_2014 NUMBER(1,0)
,COLEC1_TAS_03_2015 NUMBER(1,0)
,COLEC1_TAS_03_2016 NUMBER(1,0)

,COLEC1_ACT_56_03 NUMBER

,COLEC2_LAN_2011 NUMBER(1,0)
,COLEC2_LAN_2013 NUMBER(1,0)
,COLEC2_LAN_2014 NUMBER(1,0)
,COLEC2_LAN_2015 NUMBER(1,0)

,COLEC2_LAN_OTROS NUMBER
,COLEC1_ULT5_VAL NUMBER
,COLEC2_ULT5_VAL NUMBER
,COLEC_TOT_VAL NUMBER
--, COLEC_FEC_SYSDATE DATE 
, CONSTRAINT COLEC_TRAY_PK PRIMARY KEY 
  (
    COLEC_COD_TRAY
  )
  ENABLE 
);

CREATE TABLE COLEC_TRAY_ESP
(
COLEC_COD_TRAY_ESP NUMBER NOT NULL 
,COLEC_COD_ENTIDAD NUMBER
,COLEC_NOMB_RAZONSOCIAL VARCHAR2 (200 BYTE)
,COLEC_NUMEXP VARCHAR2(20 BYTE) 
,COLEC_EXP_EJE NUMBER(4,0)
,COLEC_COLECTIVO NUMBER(5,0)
,COLEC_NOMBRE_ADM VARCHAR2 (200 BYTE)
,COLEC_DESC_ACTIVIDAD VARCHAR2 (2000 BYTE)
,COLEC_validada NUMBER(1,0)
--, COLEC_FEC_SYSDATE DATE 
, CONSTRAINT COLEC_TRAY_ESP_PK PRIMARY KEY 
  (
    COLEC_COD_TRAY_ESP
  )
  ENABLE 
);

CREATE TABLE COLEC_OTROS_PROGRAMAS
(
COLEC_OTRPRO_COD NUMBER NOT NULL 
,COLEC_OTRPRO_TIPO VARCHAR2 (50 BYTE) --	OTROS_PROG_LANBIDE
,COLEC_OTRPRO_EXP_EJE NUMBER(4,0)
,COLEC_OTRPRO_NUMEXP VARCHAR2(20 BYTE) 
,COLEC_OTRPRO_COD_ENTIDAD NUMBER
,COLEC_OTRPRO_PROGRAMA VARCHAR2 (2500 BYTE)
,COLEC_OTRPRO_PROG_INICIO DATE 
,COLEC_OTRPRO_PROG_FIN DATE 
, CONSTRAINT COLEC_OTROS_PROGRAMAS_PK PRIMARY KEY 
  (
    COLEC_OTRPRO_COD
  )
  ENABLE 
);

CREATE TABLE COLEC_ACTIVIDADES
(
COLEC_ACTIV_COD NUMBER NOT NULL 
,COLEC_ACTIV_TIPO VARCHAR2 (50 BYTE) --	EJE1_DEC3_2015
,COLEC_ACTIV_EXP_EJE NUMBER(4,0)
,COLEC_ACTIV_NUMEXP VARCHAR2(20 BYTE) 
,COLEC_ACTIV_COD_ENTIDAD NUMBER
,COLEC_ACTIV_DESC_SERVPUB VARCHAR2 (2500 BYTE)
,COLEC_ACTIV_INICIO DATE 
,COLEC_ACTIV_FIN DATE 
, CONSTRAINT COLEC_ACTIVIDADES_PK PRIMARY KEY 
  (
    COLEC_ACTIV_COD
  )
  ENABLE 
);


CREATE TABLE COLEC_UBICACIONES_CT
(
COLEC_UBIC_CT_COD NUMBER NOT NULL 
,COLEC_UBIC_CT_NUMEXP VARCHAR2 (30 BYTE)
,COLEC_UBIC_CT_TIPO VARCHAR2 (50 BYTE) --	ANX2_COLE1_ART41A/ANX3_COLE2_ART41B/ANX4_COLE3_ART41C/ANX5_COLE4_ART41D
,COLEC_UBIC_CT_CODENTIDAD NUMBER
,COLEC_UBIC_CT_NOMBREENTIDAD VARCHAR2(200 BYTE)
,COLEC_UBIC_CT_TERRITORIO NUMBER  -- 01,20,48 
,COLEC_UBIC_CT_NROCOMARCA NUMBER
,COLEC_UBIC_CT_MUNICIPIO NUMBER 
,COLEC_UBIC_CT_LOCALIDAD VARCHAR2(200 BYTE) 
,COLEC_UBIC_CT_DIRECCION VARCHAR2(1000 BYTE)
,COLEC_UBIC_CT_PORTAL_DIR VARCHAR2(50 BYTE)
,COLEC_UBIC_CT_PISO_DIR VARCHAR2(50 BYTE)
,COLEC_UBIC_CT_LETRA_DIR VARCHAR2(50 BYTE)
,COLEC_UBIC_CT_CODPOSTAL VARCHAR2(10 BYTE)   
,COLEC_UBIC_CT_TELEFONO VARCHAR2(25 BYTE)   
, CONSTRAINT COLEC_UBICACIONES_CT_PK PRIMARY KEY 
  (
    COLEC_UBIC_CT_COD
  )
  ENABLE 
);

CREATE TABLE COLEC_CENTR_MINIMOS
(
  COLEC_COD_CENTR_MINIMOS NUMBER NOT NULL 
,COLEC_EXP_EJE NUMBER(4,0)
,COLEC_COLECTIVO NUMBER(5,0)
,COLEC_AMBITO NUMBER(5,0)
,COLEC_COMARCAS VARCHAR2 (200)
--, COLEC_FEC_SYSDATE DATE 
, CONSTRAINT COLEC_CENTR_MINIMOS_PK PRIMARY KEY 
  (
    COLEC_COD_CENTR_MINIMOS
  )
  ENABLE 
);
