create or replace PROCEDURE        COLEC_GENERA_AVISOS (EJERCICIO in number, EXPEDIENTE in number, mensaje out varchar2, exp_estado_incorrecto out varchar2) iS

-----------------------------------------------------------------------------
--              Declaraci?n de variables y Cursores                        --
-----------------------------------------------------------------------------
ind_colectivo1 number;
ind_colectivo1_VALIDADO number;
ind_colectivo2 number;
ind_colectivo2_VALIDADO number;
V_COLEC_COL1_AR number(1);
V_COLEC_COL1_BI number(1);
V_COLEC_COL1_GI number(1);
V_COLEC_COL2_AR number(1);
V_COLEC_COL2_BI number(1);
V_COLEC_COL2_GI number(1);
V_COLEC_COL3_AR number(1);
V_COLEC_COL3_BI number(1);
V_COLEC_COL3_GI number(1);
V_COLEC_COL4_AR number(1);
V_COLEC_COL4_BI number(1);
V_COLEC_COL4_GI number(1);
V_COLECTIVO NUMBER (1);
V_AMBITO NUMBER (1);  
V_COMARCA VARCHAR2(200);
NUM_CENTROS NUMBER;
EXP_1 NUMBER;
EXP_2 NUMBER;

  CURSOR COL_AMB IS
        SELECT COLEC_COL1_AR,COLEC_COL1_BI,COLEC_COL1_GI,
        COLEC_COL2_AR,COLEC_COL2_BI,COLEC_COL2_GI,
        COLEC_COL3_AR,COLEC_COL3_BI,COLEC_COL3_GI,
        COLEC_COL4_AR,COLEC_COL4_BI,COLEC_COL4_GI 
        FROM COLEC_SOLICITUD 
        WHERE  COLEC_NUMEXP=EXPEDIENTE AND COLEC_EXP_EJE=EJERCICIO;  
  CURSOR CENTROS (COLEC NUMBER, AMB NUMBER )IS
        SELECT COLEC_COMARCAS FROM COLEC_CENTR_MINIMOS
        WHERE COLEC_EXP_EJE=EJERCICIO AND COLEC_COLECTIVO=COLEC AND COLEC_AMBITO=AMB;
  
Begin
    DBMS_OUTPUT.PUT_LINE('COLEC_GENERA_AVISOS. EXPEDIENTE: '||EXPEDIENTE||' EJERCICIO: '||EJERCICIO||' ---- INICIO DEL PROCESO: '|| TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS'));

  DELETE COLEC_AVISOS WHERE    COLEC_NUMEXP=EXPEDIENTE AND COLEC_EXP_EJE=EJERCICIO;
-- COMPROBAR SI HA SOLICITADO COLECTIVO 1 Y TIENE ESPERIENCIA

  SELECT NVL(COLEC_COL1_AR,0) +NVL(COLEC_COL1_BI,0)+NVL(COLEC_COL1_GI ,0) INTO ind_colectivo1
  FROM COLEC_SOLICITUD WHERE COLEC_NUMEXP=EXPEDIENTE AND COLEC_EXP_EJE=EJERCICIO;

  if ind_colectivo1 <> 0 then 
  
  -- ha solicitado colectivo1 en algun ambito
      --comprobamos si tiene experiencia en dicho ambito
      select COUNT(*) INTO  ind_colectivo1_VALIDADO from colec_tray_esp where COLEC_NUMEXP=EXPEDIENTE AND COLEC_EXP_EJE=EJERCICIO AND COLEC_VALIDADA IS NOT NULL AND COLEC_VALIDADA>0
      AND COLEC_COLECTIVO=1;
      
      if ind_colectivo1_VALIDADO = 0 then 
        -- NO TIENE EXPERIENCIA
        INSERT INTO COLEC_AVISOS (COLEC_COD_AVISOS,COLEC_NUMEXP,COLEC_EXP_EJE,COLEC_AVISOS,COLEC_AMBITO,COLEC_COLECTIVO,COLEC_FEC_SYSDATE)
        SELECT COLEC_AVISOS_SQ.NEXTVAL, EXPEDIENTE, EJERCICIO, 'COLECTIVO 1. NO TIENE EXPERIENCIA ESPECIFICA VALIDADA', NULL, 1,SYSDATE FROM DUAL;
      end if;
      
  end if;

-- COMPROBAR SI HA SOLICITADO COLECTIVO 2 Y TIENE ESPERIENCIA

  SELECT NVL(COLEC_COL2_AR,0) +NVL(COLEC_COL2_BI,0)+NVL(COLEC_COL2_GI ,0) INTO ind_colectivo2
  FROM COLEC_SOLICITUD WHERE COLEC_NUMEXP=EXPEDIENTE AND COLEC_EXP_EJE=EJERCICIO;

  if ind_colectivo2 <> 0 then 
  -- ha solicitado colectivo2 en algun ambito
      --comprobamos si tiene experiencia en dicho ambito
      select COUNT(*) INTO  ind_colectivo2_VALIDADO from colec_tray_esp where COLEC_NUMEXP=EXPEDIENTE AND COLEC_EXP_EJE=EJERCICIO AND COLEC_VALIDADA IS NOT NULL AND COLEC_VALIDADA>0
      AND COLEC_COLECTIVO=2;
      
      if ind_colectivo2_VALIDADO = 0 then 
        -- NO TIENE EXPERIENCIA
        INSERT INTO COLEC_AVISOS (COLEC_COD_AVISOS,COLEC_NUMEXP,COLEC_EXP_EJE,COLEC_AVISOS,COLEC_AMBITO,COLEC_COLECTIVO,COLEC_FEC_SYSDATE)
        SELECT COLEC_AVISOS_SQ.NEXTVAL, EXPEDIENTE, EJERCICIO, 'COLECTIVO 2. NO TIENE EXPERIENCIA ESPECIFICA VALIDADA', NULL, 2,SYSDATE FROM DUAL;
      end if;
      
  end if;
  
  -- COMPROBAR SI TIENE UBICACIONES EN TODO LAS COMARCAS SOLICITADAS.  
  FOR REG_COL_AMB IN COL_AMB LOOP
    V_COLEC_COL1_AR:=REG_COL_AMB.COLEC_COL1_AR;
    V_COLEC_COL1_BI:=REG_COL_AMB.COLEC_COL1_BI;
    V_COLEC_COL1_GI:=REG_COL_AMB.COLEC_COL1_GI;
    V_COLEC_COL2_AR:=REG_COL_AMB.COLEC_COL2_AR ;
    V_COLEC_COL2_BI:=REG_COL_AMB.COLEC_COL2_BI ;
    V_COLEC_COL2_GI:=REG_COL_AMB.COLEC_COL2_GI ;
    V_COLEC_COL3_AR:=REG_COL_AMB.COLEC_COL3_AR ;
    V_COLEC_COL3_BI:=REG_COL_AMB.COLEC_COL3_BI ;
    V_COLEC_COL3_GI:=REG_COL_AMB.COLEC_COL3_GI ;
    V_COLEC_COL4_AR:=REG_COL_AMB.COLEC_COL4_AR ;
    V_COLEC_COL4_BI:=REG_COL_AMB.COLEC_COL4_BI ;
    V_COLEC_COL4_GI:=REG_COL_AMB.COLEC_COL4_GI ;
  
    IF V_COLEC_COL1_AR IS NOT NULL AND V_COLEC_COL1_AR<>0 THEN 
    -- HA MARCADO COLECTIVO 1 - AMBITO ARABA
      FOR REG_CENTROS  IN CENTROS (1,1) LOOP
        V_COMARCA:=REG_CENTROS.COLEC_COMARCAS;
      
        SELECT COUNT (*) 
        INTO NUM_CENTROS 
        FROM COLEC_CENTROS 
        WHERE COLEC_EXP_EJE=EJERCICIO AND COLEC_NUMEXP=EXPEDIENTE
        AND COLEC_AMBITO=1
        AND COLEC_COLECTIVO=1
        AND instr(V_COMARCA,COLEC_COMARCA)<>0;
        
        IF NUM_CENTROS =0 THEN
          INSERT INTO COLEC_AVISOS (COLEC_COD_AVISOS,COLEC_NUMEXP,COLEC_EXP_EJE,COLEC_AVISOS,COLEC_AMBITO,COLEC_COLECTIVO,COLEC_FEC_SYSDATE)
          SELECT COLEC_AVISOS_SQ.NEXTVAL, EXPEDIENTE, EJERCICIO, 'COLECTIVO 1. ARABA. NO TIENE CENTRO/S EN LA COMARCA/S: '||V_COMARCA,  1, 1,SYSDATE FROM DUAL;
        END IF;
      END LOOP;
    END IF;
    
    IF V_COLEC_COL1_BI IS NOT NULL AND V_COLEC_COL1_BI<>0 THEN 
    -- HA MARCADO COLECTIVO 1 - AMBITO BIZKAIA
      FOR REG_CENTROS  IN CENTROS (1,2) LOOP
        V_COMARCA:=REG_CENTROS.COLEC_COMARCAS;
      
        SELECT COUNT (*) 
        INTO NUM_CENTROS 
        FROM COLEC_CENTROS 
        WHERE COLEC_EXP_EJE=EJERCICIO AND COLEC_NUMEXP=EXPEDIENTE
        AND COLEC_AMBITO=2
        AND COLEC_COLECTIVO=1
        AND instr(V_COMARCA,COLEC_COMARCA)<>0;
        
                 
        IF NUM_CENTROS =0 THEN
          INSERT INTO COLEC_AVISOS (COLEC_COD_AVISOS,COLEC_NUMEXP,COLEC_EXP_EJE,COLEC_AVISOS,COLEC_AMBITO,COLEC_COLECTIVO,COLEC_FEC_SYSDATE)
          SELECT COLEC_AVISOS_SQ.NEXTVAL, EXPEDIENTE, EJERCICIO, 'COLECTIVO 1. BIZKAIA. NO TIENE CENTRO/S EN LA COMARCA/S: '||V_COMARCA,  2, 1,SYSDATE FROM DUAL;
        END IF;
      END LOOP;
    END IF;

    IF V_COLEC_COL1_GI IS NOT NULL AND V_COLEC_COL1_GI<>0 THEN 
    -- HA MARCADO COLECTIVO 1 - AMBITO GUI
      FOR REG_CENTROS  IN CENTROS (1,3) LOOP
        V_COMARCA:=REG_CENTROS.COLEC_COMARCAS;
      
        SELECT COUNT (*) 
        INTO NUM_CENTROS 
        FROM COLEC_CENTROS 
        WHERE COLEC_EXP_EJE=EJERCICIO AND COLEC_NUMEXP=EXPEDIENTE
        AND COLEC_AMBITO=3
        AND COLEC_COLECTIVO=1
        AND instr(V_COMARCA,COLEC_COMARCA)<>0;
        
        IF NUM_CENTROS =0 THEN
          INSERT INTO COLEC_AVISOS (COLEC_COD_AVISOS,COLEC_NUMEXP,COLEC_EXP_EJE,COLEC_AVISOS,COLEC_AMBITO,COLEC_COLECTIVO,COLEC_FEC_SYSDATE)
          SELECT COLEC_AVISOS_SQ.NEXTVAL, EXPEDIENTE, EJERCICIO, 'COLECTIVO 1. GIPUZKOA. NO TIENE CENTRO/S EN LA COMARCA/S: '||V_COMARCA,  3, 1,SYSDATE FROM DUAL;
        END IF;
      END LOOP;
    END IF;    
    
    IF V_COLEC_COL2_AR IS NOT NULL AND V_COLEC_COL2_AR<>0 THEN 
    -- HA MARCADO COLECTIVO 2 - AMBITO ARABA
      FOR REG_CENTROS  IN CENTROS (2,1) LOOP
        V_COMARCA:=REG_CENTROS.COLEC_COMARCAS;
      
        SELECT COUNT (*) 
        INTO NUM_CENTROS 
        FROM COLEC_CENTROS 
        WHERE COLEC_EXP_EJE=EJERCICIO AND COLEC_NUMEXP=EXPEDIENTE
        AND COLEC_AMBITO=1
        AND COLEC_COLECTIVO=2
        AND instr(V_COMARCA,COLEC_COMARCA)<>0;
        
        IF NUM_CENTROS =0 THEN
          INSERT INTO COLEC_AVISOS (COLEC_COD_AVISOS,COLEC_NUMEXP,COLEC_EXP_EJE,COLEC_AVISOS,COLEC_AMBITO,COLEC_COLECTIVO,COLEC_FEC_SYSDATE)
          SELECT COLEC_AVISOS_SQ.NEXTVAL, EXPEDIENTE, EJERCICIO, 'COLECTIVO 2. ARABA. NO TIENE CENTRO/S EN LA COMARCA/S: '||V_COMARCA,  1, 2,SYSDATE FROM DUAL;
        END IF;
      END LOOP;
    END IF;
    
    IF V_COLEC_COL2_BI IS NOT NULL AND V_COLEC_COL2_BI<>0 THEN 
    -- HA MARCADO COLECTIVO 2 - AMBITO BIZKAIA
      FOR REG_CENTROS  IN CENTROS (2,2) LOOP
        V_COMARCA:=REG_CENTROS.COLEC_COMARCAS;
      
        SELECT COUNT (*) 
        INTO NUM_CENTROS 
        FROM COLEC_CENTROS 
        WHERE COLEC_EXP_EJE=EJERCICIO AND COLEC_NUMEXP=EXPEDIENTE
        AND COLEC_AMBITO=2
        AND COLEC_COLECTIVO=2
        AND instr(V_COMARCA,COLEC_COMARCA)<>0;
        
        IF NUM_CENTROS =0 THEN
          INSERT INTO COLEC_AVISOS (COLEC_COD_AVISOS,COLEC_NUMEXP,COLEC_EXP_EJE,COLEC_AVISOS,COLEC_AMBITO,COLEC_COLECTIVO,COLEC_FEC_SYSDATE)
          SELECT COLEC_AVISOS_SQ.NEXTVAL, EXPEDIENTE, EJERCICIO, 'COLECTIVO 2. BIZKAIA. NO TIENE CENTRO/S EN LA COMARCA/S: '||V_COMARCA,  2, 2,SYSDATE FROM DUAL;
        END IF;
      END LOOP;
    END IF;

    IF V_COLEC_COL2_GI IS NOT NULL AND V_COLEC_COL2_GI<>0 THEN 
    -- HA MARCADO COLECTIVO 2 - AMBITO GUI
      FOR REG_CENTROS  IN CENTROS (2,3) LOOP
        V_COMARCA:=REG_CENTROS.COLEC_COMARCAS;
      
        SELECT COUNT (*) 
        INTO NUM_CENTROS 
        FROM COLEC_CENTROS 
        WHERE COLEC_EXP_EJE=EJERCICIO AND COLEC_NUMEXP=EXPEDIENTE
        AND COLEC_AMBITO=3
        AND COLEC_COLECTIVO=2
        AND instr(V_COMARCA,COLEC_COMARCA)<>0;
        
        IF NUM_CENTROS =0 THEN
          INSERT INTO COLEC_AVISOS (COLEC_COD_AVISOS,COLEC_NUMEXP,COLEC_EXP_EJE,COLEC_AVISOS,COLEC_AMBITO,COLEC_COLECTIVO,COLEC_FEC_SYSDATE)
          SELECT COLEC_AVISOS_SQ.NEXTVAL, EXPEDIENTE, EJERCICIO, 'COLECTIVO 2. GIPUZKOA. NO TIENE CENTRO/S EN LA COMARCA/S: '||V_COMARCA,  3, 2,SYSDATE FROM DUAL;
        END IF;
      END LOOP;
    END IF;  
    
    IF V_COLEC_COL3_AR IS NOT NULL AND V_COLEC_COL3_AR<>0 THEN 
    -- HA MARCADO COLECTIVO 1 - AMBITO ARABA
      FOR REG_CENTROS  IN CENTROS (3,1) LOOP
        V_COMARCA:=REG_CENTROS.COLEC_COMARCAS;
      
        SELECT COUNT (*) 
        INTO NUM_CENTROS 
        FROM COLEC_CENTROS 
        WHERE COLEC_EXP_EJE=EJERCICIO AND COLEC_NUMEXP=EXPEDIENTE
        AND COLEC_AMBITO=1
        AND COLEC_COLECTIVO=3
        AND instr(V_COMARCA,COLEC_COMARCA)<>0;
        
        IF NUM_CENTROS =0 THEN
          INSERT INTO COLEC_AVISOS (COLEC_COD_AVISOS,COLEC_NUMEXP,COLEC_EXP_EJE,COLEC_AVISOS,COLEC_AMBITO,COLEC_COLECTIVO,COLEC_FEC_SYSDATE)
          SELECT COLEC_AVISOS_SQ.NEXTVAL, EXPEDIENTE, EJERCICIO, 'COLECTIVO 3. ARABA. NO TIENE CENTRO/S EN LA COMARCA/S: '||V_COMARCA,  1, 3,SYSDATE FROM DUAL;
        END IF;
      END LOOP;
    END IF;
    
    IF V_COLEC_COL3_BI IS NOT NULL AND V_COLEC_COL3_BI<>0 THEN 
    -- HA MARCADO COLECTIVO 3 - AMBITO BIZKAIA
      FOR REG_CENTROS  IN CENTROS (3,2) LOOP
        V_COMARCA:=REG_CENTROS.COLEC_COMARCAS;
      
        SELECT COUNT (*) 
        INTO NUM_CENTROS 
        FROM COLEC_CENTROS 
        WHERE COLEC_EXP_EJE=EJERCICIO AND COLEC_NUMEXP=EXPEDIENTE
                AND COLEC_AMBITO=2
        AND COLEC_COLECTIVO=3
        AND instr(V_COMARCA,COLEC_COMARCA)<>0;
        
        IF NUM_CENTROS =0 THEN
          INSERT INTO COLEC_AVISOS (COLEC_COD_AVISOS,COLEC_NUMEXP,COLEC_EXP_EJE,COLEC_AVISOS,COLEC_AMBITO,COLEC_COLECTIVO,COLEC_FEC_SYSDATE)
          SELECT COLEC_AVISOS_SQ.NEXTVAL, EXPEDIENTE, EJERCICIO, 'COLECTIVO 3. BIZKAIA. NO TIENE CENTRO/S EN LA COMARCA/S: '||V_COMARCA,  2, 3,SYSDATE FROM DUAL;
        END IF;
      END LOOP;
    END IF;

    IF V_COLEC_COL3_GI IS NOT NULL AND V_COLEC_COL3_GI<>0 THEN 
    -- HA MARCADO COLECTIVO 1 - AMBITO GUI
      FOR REG_CENTROS  IN CENTROS (3,3) LOOP
        V_COMARCA:=REG_CENTROS.COLEC_COMARCAS;
      
        SELECT COUNT (*) 
        INTO NUM_CENTROS 
        FROM COLEC_CENTROS 
        WHERE COLEC_EXP_EJE=EJERCICIO AND COLEC_NUMEXP=EXPEDIENTE
                AND COLEC_AMBITO=3
        AND COLEC_COLECTIVO=3
        AND instr(V_COMARCA,COLEC_COMARCA)<>0;
        
        IF NUM_CENTROS =0 THEN
          INSERT INTO COLEC_AVISOS (COLEC_COD_AVISOS,COLEC_NUMEXP,COLEC_EXP_EJE,COLEC_AVISOS,COLEC_AMBITO,COLEC_COLECTIVO,COLEC_FEC_SYSDATE)
          SELECT COLEC_AVISOS_SQ.NEXTVAL, EXPEDIENTE, EJERCICIO, 'COLECTIVO 3. GIPUZKOA. NO TIENE CENTRO/S EN LA COMARCA/S: '||V_COMARCA,  3, 3,SYSDATE FROM DUAL;
        END IF;
      END LOOP;
    END IF;      
    END LOOP;
    
  -- COMPROBAR SI TIENE LA EXPERIENCIA NECESARIA
  
  SELECT COLEC1_ULT5_VAL,COLEC2_ULT5_VAL INTO EXP_1, EXP_2
  FROM COLEC_SOLICITUD WHERE COLEC_NUMEXP=EXPEDIENTE AND COLEC_EXP_EJE=EJERCICIO;
  
  IF EXP_1<2 OR EXP_1 IS NULL THEN
    IF EXP_2<1 OR EXP_2 IS NULL  THEN
    -- no se tiene la experiencia minima
       INSERT INTO COLEC_AVISOS (COLEC_COD_AVISOS,COLEC_NUMEXP,COLEC_EXP_EJE,COLEC_AVISOS,COLEC_AMBITO,COLEC_COLECTIVO,COLEC_FEC_SYSDATE)
       SELECT COLEC_AVISOS_SQ.NEXTVAL, EXPEDIENTE, EJERCICIO, 'NO SE DISPONE DE LA EXPERIENCIA GENERAL NECESARIA', NULL,NULL,SYSDATE FROM DUAL;
    end if;
  end if;
    
    
    Dbms_Output.Put_Line('COLEC_GENERA_AVISOS. FIN DEL PROCESO' ||TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS'));   

    
    exception
      when others then
        MENSAJE := 'ERROR';  
END COLEC_GENERA_AVISOS;