ALTER TABLE CPE_JUSTIFICACION ADD (CPE_JUS_BONIF NUMBER(10, 2) );
ALTER TABLE CPE_JUSTIFICACION ADD (CPE_JUS_GASTOSGES NUMBER(10, 2) );
ALTER TABLE CPE_JUSTIFICACION ADD (CPE_JUS_DIETAS NUMBER(10, 2) );
ALTER TABLE CPE_JUSTIFICACION ADD (CPE_JUS_SALARIOSUB NUMBER(10, 2) );
