create or replace
PROCEDURE CPE_HISTORICO (expediente in varchar2, tramite IN VARCHAR2) IS

  --CODIGO VARCHAR2(100);
 
BEGIN      
  dbms_output.put_line('INICIO FUNCION CPE_HISTORICO: '||to_char(SYSDATE,'yyyymmdd hh24:mi:ss')); 
  
  --INSERTAMOS SOLICITUD
insert into CPE_HIST_OFERTA (  CPE_OFE_ID,CPE_OFE_COD_TRAMITE,CPE_OFE_ID_OFERTA,CPE_OFE_COD_OFERTA,CPE_OFE_COD_OFI_GEST,CPE_OFE_PREC,CPE_OFE_PREC_NOM,CPE_OFE_DIFUSION,CPE_OFE_FEC_DIFUSION,
CPE_OFE_FEC_ENV_CAND,CPE_OFE_NUM_TOT_CAND,CPE_OFE_DOC_GEST_OFE,CPE_OFE_CONTRATACION, CPE_OFE_MOT_CONTRATACION,CPE_OFE_COD_TIPO_NIF, CPE_OFE_NIF,CPE_OFE_NOMBRE,
CPE_OFE_APE1, CPE_OFE_APE2, CPE_OFE_EMAIL, CPE_OFE_TLF, CPE_OFE_FEC_NAC, CPE_OFE_SEXO, CPE_OFE_COD_TITULACION, CPE_OFE_DOC_CONTRATACION, CPE_OFE_FEC_INI, 
CPE_OFE_FEC_FIN, CPE_OFE_COD_GR_COT, CPE_OFE_SALARIOB, CPE_OFE_DIETAS_CONVENIO, CPE_OFE_DIETAS_CONVOC, CPE_OFE_FEC_BAJA, CPE_OFE_COD_CAUSA_BAJA, 
CPE_OFE_OBSERVACIONES, CPE_OFE_COD_PUESTO, CPE_OFE_NUMEXP, CPE_OFE_EXP_EJE, CPE_OFE_ANO_TITULACION, CPE_OFE_FL_SUSTITUTO, CPE_OFE_NOM_DOC_GEST_OFE, 
CPE_OFE_NOM_DOC_CONTRATACION, CPE_OFE_ID_OFERTA_ORIGEN, CPE_OFE_DESC_PUESTO, CPE_OFE_PAI_COD_1, CPE_OFE_PAI_COD_2, CPE_OFE_PAI_COD_3, CPE_OFE_COD_TIT_1,
CPE_OFE_COD_TIT_2, CPE_OFE_COD_TIT_3, CPE_OFE_FUNCIONES, CPE_OFE_COD_IDIOMA_1, CPE_OFE_COD_IDIOMA_2, CPE_OFE_COD_IDIOMA_3, CPE_OFE_COD_NIV_IDI_1,
CPE_OFE_COD_NIV_IDI_2, CPE_OFE_COD_NIV_IDI_3, CPE_OFE_COD_NIV_FORM, CPE_OFE_CIUDAD_DESTINO, CPE_OFE_DPTO, CPE_OFE_MESES_CONTRATO, CPE_OFE_COD_CAUSA_RENUNCIA, 
FECHA_HIST)
select
SEQ_CPE_HIST_OFERTA.nextval, tramite, CPE_OFE_ID_OFERTA,CPE_OFE_COD_OFERTA,CPE_OFE_COD_OFI_GEST,CPE_OFE_PREC,CPE_OFE_PREC_NOM,CPE_OFE_DIFUSION,CPE_OFE_FEC_DIFUSION,
CPE_OFE_FEC_ENV_CAND,CPE_OFE_NUM_TOT_CAND,CPE_OFE_DOC_GEST_OFE,CPE_OFE_CONTRATACION, CPE_OFE_MOT_CONTRATACION,CPE_OFE_COD_TIPO_NIF, CPE_OFE_NIF,CPE_OFE_NOMBRE,
CPE_OFE_APE1, CPE_OFE_APE2, CPE_OFE_EMAIL, CPE_OFE_TLF, CPE_OFE_FEC_NAC, CPE_OFE_SEXO, CPE_OFE_COD_TITULACION, CPE_OFE_DOC_CONTRATACION, CPE_OFE_FEC_INI, 
CPE_OFE_FEC_FIN, CPE_OFE_COD_GR_COT, CPE_OFE_SALARIOB, CPE_OFE_DIETAS_CONVENIO, CPE_OFE_DIETAS_CONVOC, CPE_OFE_FEC_BAJA, CPE_OFE_COD_CAUSA_BAJA, 
CPE_OFE_OBSERVACIONES, CPE_OFE_COD_PUESTO, CPE_OFE_NUMEXP, CPE_OFE_EXP_EJE, CPE_OFE_ANO_TITULACION, CPE_OFE_FL_SUSTITUTO, CPE_OFE_NOM_DOC_GEST_OFE, 
CPE_OFE_NOM_DOC_CONTRATACION, CPE_OFE_ID_OFERTA_ORIGEN, CPE_OFE_DESC_PUESTO, CPE_OFE_PAI_COD_1, CPE_OFE_PAI_COD_2, CPE_OFE_PAI_COD_3, CPE_OFE_COD_TIT_1,
CPE_OFE_COD_TIT_2, CPE_OFE_COD_TIT_3, CPE_OFE_FUNCIONES, CPE_OFE_COD_IDIOMA_1, CPE_OFE_COD_IDIOMA_2, CPE_OFE_COD_IDIOMA_3, CPE_OFE_COD_NIV_IDI_1,
CPE_OFE_COD_NIV_IDI_2, CPE_OFE_COD_NIV_IDI_3, CPE_OFE_COD_NIV_FORM, CPE_OFE_CIUDAD_DESTINO, CPE_OFE_DPTO, CPE_OFE_MESES_CONTRATO, CPE_OFE_COD_CAUSA_RENUNCIA,  
SYSDATE  
from CPE_OFERTA
where CPE_OFE_NUMEXP=EXPEDIENTE;
commit;

insert into CPE_HIST_PUESTO (CPE_PTO_ID, CPE_PTO_COD_TRAMITE, CPE_PTO_COD_PUESTO,CPE_PTO_DESC_PUESTO,CPE_PTO_PAI_COD_1,CPE_PTO_PAI_COD_2,CPE_PTO_PAI_COD_3,CPE_PTO_COD_TIT_1,CPE_PTO_COD_TIT_2,
CPE_PTO_COD_TIT_3,CPE_PTO_FUNCIONES,CPE_PTO_COD_IDIOMA_1,CPE_PTO_COD_IDIOMA_2, CPE_PTO_COD_NIV_FORM,CPE_PTO_COD_GR_COT, CPE_PTO_SALARIO_ANEX1,CPE_PTO_DIETAS_MANUT,
CPE_PTO_MESES_MANUT, CPE_PTO_TRAM_SEGUROS, CPE_PTO_IMP_MAX_SUBV, CPE_PTO_FEC_INI, CPE_PTO_FEC_FIN, CPE_PTO_CONVENIO_COL, CPE_PTO_SAL_BRUTO, CPE_PTO_DIETAS_CONV, 
CPE_PTO_COSTE_CONT, CPE_PTO_OTROS_BENEF, CPE_PTO_COD_RESULT, CPE_PTO_COD_MOTIVO, CPE_PTO_OBSERVACIONES, CPE_PTO_COD_NIV_IDI_1, CPE_PTO_COD_NIV_IDI_2, 
CPE_PTO_NUMEXP, CPE_PTO_EXP_EJE, CPE_PTO_CIUDAD_DESTINO, CPE_PTO_DPTO, CPE_PTO_COD_IDIOMA_3, CPE_PTO_COD_NIV_IDI_3, CPE_PTO_SAL_SOLIC, 
CPE_PTO_DIETAS_SOLIC, CPE_PTO_TRAM_SOLIC, CPE_PTO_IMP_TOT_SOLIC, CPE_PTO_SALARIO_ANEX2, CPE_PTO_SALARIO_ANEX3, CPE_PTO_SALARIO_ANEX_TOT, 
CPE_PTO_MESES_CONTRATO, FECHA_HIST)
select
SEQ_CPE_HIST_SOLICITUD.nextval, tramite, CPE_PTO_COD_PUESTO,CPE_PTO_DESC_PUESTO,CPE_PTO_PAI_COD_1,CPE_PTO_PAI_COD_2,CPE_PTO_PAI_COD_3,CPE_PTO_COD_TIT_1,CPE_PTO_COD_TIT_2,
CPE_PTO_COD_TIT_3,CPE_PTO_FUNCIONES,CPE_PTO_COD_IDIOMA_1,CPE_PTO_COD_IDIOMA_2, CPE_PTO_COD_NIV_FORM,CPE_PTO_COD_GR_COT, CPE_PTO_SALARIO_ANEX1,CPE_PTO_DIETAS_MANUT,
CPE_PTO_MESES_MANUT, CPE_PTO_TRAM_SEGUROS, CPE_PTO_IMP_MAX_SUBV, CPE_PTO_FEC_INI, CPE_PTO_FEC_FIN, CPE_PTO_CONVENIO_COL, CPE_PTO_SAL_BRUTO, CPE_PTO_DIETAS_CONV, 
CPE_PTO_COSTE_CONT, CPE_PTO_OTROS_BENEF, CPE_PTO_COD_RESULT, CPE_PTO_COD_MOTIVO, CPE_PTO_OBSERVACIONES, CPE_PTO_COD_NIV_IDI_1, CPE_PTO_COD_NIV_IDI_2, 
CPE_PTO_NUMEXP, CPE_PTO_EXP_EJE, CPE_PTO_CIUDAD_DESTINO, CPE_PTO_DPTO, CPE_PTO_COD_IDIOMA_3, CPE_PTO_COD_NIV_IDI_3, CPE_PTO_SAL_SOLIC, 
CPE_PTO_DIETAS_SOLIC, CPE_PTO_TRAM_SOLIC, CPE_PTO_IMP_TOT_SOLIC, CPE_PTO_SALARIO_ANEX2, CPE_PTO_SALARIO_ANEX3, CPE_PTO_SALARIO_ANEX_TOT, 
CPE_PTO_MESES_CONTRATO,SYSDATE  
from CPE_PUESTO
where CPE_PTO_NUMEXP=EXPEDIENTE;
commit;


insert into CPE_HIST_JUSTIFICACION (CPE_JUS_ID, CPE_JUS_COD_TRAMITE, CPE_JUS_ID_JUSTIFICACION,CPE_JUS_COD_PUESTO,CPE_JUS_NUMEXP,CPE_JUS_EXP_EJE,CPE_JUS_ID_OFERTA,CPE_JUS_COD_ESTADO,
CPE_JUS_FL_VARIOS_TRAB,CPE_JUS_IMP_JUSTIFICADO,CPE_JUS_SALARIOSUB,CPE_JUS_DIETAS, CPE_JUS_GASTOSGES,CPE_JUS_BONIF, FECHA_HIST)
select
SEQ_CPE_HIST_JUSTIF.nextval, tramite, CPE_JUS_ID_JUSTIFICACION,CPE_JUS_COD_PUESTO,CPE_JUS_NUMEXP,CPE_JUS_EXP_EJE,CPE_JUS_ID_OFERTA,CPE_JUS_COD_ESTADO,
CPE_JUS_FL_VARIOS_TRAB,CPE_JUS_IMP_JUSTIFICADO,CPE_JUS_SALARIOSUB,CPE_JUS_DIETAS, CPE_JUS_GASTOSGES,CPE_JUS_BONIF,SYSDATE  
from CPE_JUSTIFICACION
where CPE_JUS_NUMEXP=EXPEDIENTE;
commit;

dbms_output.put_line('FIN PROCESO CPE_HISTORICO: '||to_char(SYSDATE,'yyyymmdd hh24:mi:ss'));   

END CPE_HISTORICO;
/

create or replace
PROCEDURE CPE_BORRADO_HISTORICO (expediente in varchar2, tramite IN VARCHAR2) IS

  --CODIGO VARCHAR2(100);
 
BEGIN      
  dbms_output.put_line('INICIO FUNCION CPE_BORRADO_HISTORICO: '||to_char(SYSDATE,'yyyymmdd hh24:mi:ss')); 
  
  --INSERTAMOS SOLICITUD
DELETE FROM CPE_HIST_OFERTA WHERE CPE_OFE_NUMEXP=EXPEDIENTE AND CPE_OFE_COD_TRAMITE = tramite;
commit;

DELETE FROM CPE_HIST_PUESTO WHERE CPE_PTO_NUMEXP=EXPEDIENTE AND CPE_PTO_COD_TRAMITE = tramite;
commit;

DELETE FROM CPE_HIST_JUSTIFICACION WHERE CPE_JUS_NUMEXP=EXPEDIENTE AND CPE_JUS_COD_TRAMITE = tramite;
commit;

dbms_output.put_line('FIN PROCESO CPE_BORRADO_HISTORICO: '||to_char(SYSDATE,'yyyymmdd hh24:mi:ss'));   

END CPE_BORRADO_HISTORICO;
/