
package es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "LangaiDemanda", targetNamespace = "http://langaiDemanda.services.langaiWS.es/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LangaiDemanda {


    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @param arg7
     * @param arg8
     * @return
     *     returns es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.ServiciosValueObject
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaSimpleServicios", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.ConsultaSimpleServicios")
    @ResponseWrapper(localName = "consultaSimpleServiciosResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.ConsultaSimpleServiciosResponse")
    public ServiciosValueObject consultaSimpleServicios(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg23
     * @param arg0
     * @param arg22
     * @param arg21
     * @param arg20
     * @param arg27
     * @param arg26
     * @param arg25
     * @param arg24
     * @param arg29
     * @param arg28
     * @param arg30
     * @param arg32
     * @param arg31
     * @param arg19
     * @param arg17
     * @param arg18
     * @param arg15
     * @param arg16
     * @param arg13
     * @param arg14
     * @param arg11
     * @param arg12
     * @param arg10
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "altaServicio", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.AltaServicio")
    @ResponseWrapper(localName = "altaServicioResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.AltaServicioResponse")
    public String altaServicio(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        String arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        String arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        String arg12,
        @WebParam(name = "arg13", targetNamespace = "")
        String arg13,
        @WebParam(name = "arg14", targetNamespace = "")
        String arg14,
        @WebParam(name = "arg15", targetNamespace = "")
        String arg15,
        @WebParam(name = "arg16", targetNamespace = "")
        String arg16,
        @WebParam(name = "arg17", targetNamespace = "")
        String arg17,
        @WebParam(name = "arg18", targetNamespace = "")
        String arg18,
        @WebParam(name = "arg19", targetNamespace = "")
        String arg19,
        @WebParam(name = "arg20", targetNamespace = "")
        String arg20,
        @WebParam(name = "arg21", targetNamespace = "")
        String arg21,
        @WebParam(name = "arg22", targetNamespace = "")
        String arg22,
        @WebParam(name = "arg23", targetNamespace = "")
        String arg23,
        @WebParam(name = "arg24", targetNamespace = "")
        String arg24,
        @WebParam(name = "arg25", targetNamespace = "")
        String arg25,
        @WebParam(name = "arg26", targetNamespace = "")
        String arg26,
        @WebParam(name = "arg27", targetNamespace = "")
        String arg27,
        @WebParam(name = "arg28", targetNamespace = "")
        String arg28,
        @WebParam(name = "arg29", targetNamespace = "")
        String arg29,
        @WebParam(name = "arg30", targetNamespace = "")
        String arg30,
        @WebParam(name = "arg31", targetNamespace = "")
        String arg31,
        @WebParam(name = "arg32", targetNamespace = "")
        String arg32);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg23
     * @param arg0
     * @param arg22
     * @param arg21
     * @param arg20
     * @param arg27
     * @param arg26
     * @param arg25
     * @param arg24
     * @param arg29
     * @param arg28
     * @param arg19
     * @param arg17
     * @param arg18
     * @param arg15
     * @param arg16
     * @param arg13
     * @param arg14
     * @param arg11
     * @param arg12
     * @param arg10
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "altaServicioSeq", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.AltaServicioSeq")
    @ResponseWrapper(localName = "altaServicioSeqResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.AltaServicioSeqResponse")
    public String altaServicioSeq(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        String arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        String arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        String arg12,
        @WebParam(name = "arg13", targetNamespace = "")
        String arg13,
        @WebParam(name = "arg14", targetNamespace = "")
        String arg14,
        @WebParam(name = "arg15", targetNamespace = "")
        String arg15,
        @WebParam(name = "arg16", targetNamespace = "")
        String arg16,
        @WebParam(name = "arg17", targetNamespace = "")
        String arg17,
        @WebParam(name = "arg18", targetNamespace = "")
        String arg18,
        @WebParam(name = "arg19", targetNamespace = "")
        String arg19,
        @WebParam(name = "arg20", targetNamespace = "")
        String arg20,
        @WebParam(name = "arg21", targetNamespace = "")
        String arg21,
        @WebParam(name = "arg22", targetNamespace = "")
        String arg22,
        @WebParam(name = "arg23", targetNamespace = "")
        String arg23,
        @WebParam(name = "arg24", targetNamespace = "")
        String arg24,
        @WebParam(name = "arg25", targetNamespace = "")
        String arg25,
        @WebParam(name = "arg26", targetNamespace = "")
        String arg26,
        @WebParam(name = "arg27", targetNamespace = "")
        String arg27,
        @WebParam(name = "arg28", targetNamespace = "")
        String arg28,
        @WebParam(name = "arg29", targetNamespace = "")
        String arg29);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg11
     * @param arg10
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "bajaServicio_Anular")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bajaServicio_Anular", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.BajaServicioAnular")
    @ResponseWrapper(localName = "bajaServicio_AnularResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.BajaServicioAnularResponse")
    public String bajaServicioAnular(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        String arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        String arg11);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "bajaServicio_Eliminar")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bajaServicio_Eliminar", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.BajaServicioEliminar")
    @ResponseWrapper(localName = "bajaServicio_EliminarResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.BajaServicioEliminarResponse")
    public String bajaServicioEliminar(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg23
     * @param arg0
     * @param arg22
     * @param arg21
     * @param arg20
     * @param arg27
     * @param arg26
     * @param arg25
     * @param arg24
     * @param arg29
     * @param arg28
     * @param arg30
     * @param arg31
     * @param arg19
     * @param arg17
     * @param arg18
     * @param arg15
     * @param arg16
     * @param arg13
     * @param arg14
     * @param arg11
     * @param arg12
     * @param arg10
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modificaServicio", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.ModificaServicio")
    @ResponseWrapper(localName = "modificaServicioResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.ModificaServicioResponse")
    public String modificaServicio(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        String arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        String arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        String arg12,
        @WebParam(name = "arg13", targetNamespace = "")
        String arg13,
        @WebParam(name = "arg14", targetNamespace = "")
        String arg14,
        @WebParam(name = "arg15", targetNamespace = "")
        String arg15,
        @WebParam(name = "arg16", targetNamespace = "")
        String arg16,
        @WebParam(name = "arg17", targetNamespace = "")
        String arg17,
        @WebParam(name = "arg18", targetNamespace = "")
        String arg18,
        @WebParam(name = "arg19", targetNamespace = "")
        String arg19,
        @WebParam(name = "arg20", targetNamespace = "")
        String arg20,
        @WebParam(name = "arg21", targetNamespace = "")
        String arg21,
        @WebParam(name = "arg22", targetNamespace = "")
        String arg22,
        @WebParam(name = "arg23", targetNamespace = "")
        String arg23,
        @WebParam(name = "arg24", targetNamespace = "")
        String arg24,
        @WebParam(name = "arg25", targetNamespace = "")
        String arg25,
        @WebParam(name = "arg26", targetNamespace = "")
        String arg26,
        @WebParam(name = "arg27", targetNamespace = "")
        String arg27,
        @WebParam(name = "arg28", targetNamespace = "")
        String arg28,
        @WebParam(name = "arg29", targetNamespace = "")
        String arg29,
        @WebParam(name = "arg30", targetNamespace = "")
        String arg30,
        @WebParam(name = "arg31", targetNamespace = "")
        String arg31);

    /**
     * 
     * @param numDoc
     * @param tipoDoc
     * @param codUbicUsu
     * @param idioma
     * @param codCentroUsu
     * @return
     *     returns es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.FormacionesOcupacionalesValueObject
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaSimpleForOcup", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.ConsultaSimpleForOcup")
    @ResponseWrapper(localName = "consultaSimpleForOcupResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.ConsultaSimpleForOcupResponse")
    public FormacionesOcupacionalesValueObject consultaSimpleForOcup(
        @WebParam(name = "cod_centro_usu", targetNamespace = "")
        String codCentroUsu,
        @WebParam(name = "cod_ubic_usu", targetNamespace = "")
        String codUbicUsu,
        @WebParam(name = "num_doc", targetNamespace = "")
        String numDoc,
        @WebParam(name = "tipo_doc", targetNamespace = "")
        String tipoDoc,
        @WebParam(name = "idioma", targetNamespace = "")
        String idioma);

    /**
     * 
     * @param tipoDoc
     * @param demFoocuFecFin
     * @param codUbicUsu
     * @param genFamCod
     * @param forAfCod
     * @param demFoocuTextLibre
     * @param idioma
     * @param demFoocuEspecialidad
     * @param demFoocuIndTifo
     * @param numDoc
     * @param listUnidsComp
     * @param demFoocuNroHoras
     * @param genEsCod
     * @param forInfAfCod
     * @param codCentroUsu
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modificaForOcup", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.ModificaForOcup")
    @ResponseWrapper(localName = "modificaForOcupResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.ModificaForOcupResponse")
    public String modificaForOcup(
        @WebParam(name = "cod_centro_usu", targetNamespace = "")
        String codCentroUsu,
        @WebParam(name = "cod_ubic_usu", targetNamespace = "")
        String codUbicUsu,
        @WebParam(name = "num_doc", targetNamespace = "")
        String numDoc,
        @WebParam(name = "tipo_doc", targetNamespace = "")
        String tipoDoc,
        @WebParam(name = "dem_foocu_ind_tifo", targetNamespace = "")
        String demFoocuIndTifo,
        @WebParam(name = "gen_es_cod", targetNamespace = "")
        String genEsCod,
        @WebParam(name = "gen_fam_cod", targetNamespace = "")
        String genFamCod,
        @WebParam(name = "dem_foocu_especialidad", targetNamespace = "")
        String demFoocuEspecialidad,
        @WebParam(name = "dem_foocu_text_libre", targetNamespace = "")
        String demFoocuTextLibre,
        @WebParam(name = "dem_foocu_fec_fin", targetNamespace = "")
        String demFoocuFecFin,
        @WebParam(name = "dem_foocu_nro_horas", targetNamespace = "")
        String demFoocuNroHoras,
        @WebParam(name = "for_af_cod", targetNamespace = "")
        String forAfCod,
        @WebParam(name = "for_inf_af_cod", targetNamespace = "")
        String forInfAfCod,
        @WebParam(name = "list_unids_comp", targetNamespace = "")
        List<String> listUnidsComp,
        @WebParam(name = "idioma", targetNamespace = "")
        String idioma);

    /**
     * 
     * @param tipoDoc
     * @param demFoocuFecFin
     * @param codUbicUsu
     * @param genFamCod
     * @param forAfCod
     * @param demFoocuTextLibre
     * @param idioma
     * @param demFoocuEspecialidad
     * @param demFoocuIndTifo
     * @param numDoc
     * @param listUnidsComp
     * @param demFoocuNroHoras
     * @param genEsCod
     * @param forInfAfCod
     * @param codCentroUsu
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "altaForOcup", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.AltaForOcup")
    @ResponseWrapper(localName = "altaForOcupResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.AltaForOcupResponse")
    public String altaForOcup(
        @WebParam(name = "cod_centro_usu", targetNamespace = "")
        String codCentroUsu,
        @WebParam(name = "cod_ubic_usu", targetNamespace = "")
        String codUbicUsu,
        @WebParam(name = "num_doc", targetNamespace = "")
        String numDoc,
        @WebParam(name = "tipo_doc", targetNamespace = "")
        String tipoDoc,
        @WebParam(name = "dem_foocu_ind_tifo", targetNamespace = "")
        String demFoocuIndTifo,
        @WebParam(name = "gen_es_cod", targetNamespace = "")
        String genEsCod,
        @WebParam(name = "gen_fam_cod", targetNamespace = "")
        String genFamCod,
        @WebParam(name = "dem_foocu_especialidad", targetNamespace = "")
        String demFoocuEspecialidad,
        @WebParam(name = "dem_foocu_text_libre", targetNamespace = "")
        String demFoocuTextLibre,
        @WebParam(name = "dem_foocu_fec_fin", targetNamespace = "")
        String demFoocuFecFin,
        @WebParam(name = "dem_foocu_nro_horas", targetNamespace = "")
        String demFoocuNroHoras,
        @WebParam(name = "for_af_cod", targetNamespace = "")
        String forAfCod,
        @WebParam(name = "for_inf_af_cod", targetNamespace = "")
        String forInfAfCod,
        @WebParam(name = "list_unids_comp", targetNamespace = "")
        List<String> listUnidsComp,
        @WebParam(name = "idioma", targetNamespace = "")
        String idioma);

    /**
     * 
     * @param demFoocuIndTifo
     * @param numDoc
     * @param tipoDoc
     * @param codUbicUsu
     * @param idioma
     * @param genEsCod
     * @param demFoocuEspecialidad
     * @param demFoocuFamCod
     * @param codCentroUsu
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bajaForOcup", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.BajaForOcup")
    @ResponseWrapper(localName = "bajaForOcupResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.BajaForOcupResponse")
    public String bajaForOcup(
        @WebParam(name = "cod_centro_usu", targetNamespace = "")
        String codCentroUsu,
        @WebParam(name = "cod_ubic_usu", targetNamespace = "")
        String codUbicUsu,
        @WebParam(name = "num_doc", targetNamespace = "")
        String numDoc,
        @WebParam(name = "tipo_doc", targetNamespace = "")
        String tipoDoc,
        @WebParam(name = "dem_foocu_ind_tifo", targetNamespace = "")
        String demFoocuIndTifo,
        @WebParam(name = "gen_es_cod", targetNamespace = "")
        String genEsCod,
        @WebParam(name = "dem_foocu_fam_cod", targetNamespace = "")
        String demFoocuFamCod,
        @WebParam(name = "dem_foocu_especialidad", targetNamespace = "")
        String demFoocuEspecialidad,
        @WebParam(name = "idioma", targetNamespace = "")
        String idioma);

    /**
     * 
     * @param numDoc
     * @param tipoDoc
     * @param codUbicUsu
     * @param idioma
     * @param codCentroUsu
     * @return
     *     returns es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.FormacionesComplementariasValueObject
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaSimpleForCompl", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.ConsultaSimpleForCompl")
    @ResponseWrapper(localName = "consultaSimpleForComplResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.ConsultaSimpleForComplResponse")
    public FormacionesComplementariasValueObject consultaSimpleForCompl(
        @WebParam(name = "cod_centro_usu", targetNamespace = "")
        String codCentroUsu,
        @WebParam(name = "cod_ubic_usu", targetNamespace = "")
        String codUbicUsu,
        @WebParam(name = "num_doc", targetNamespace = "")
        String numDoc,
        @WebParam(name = "tipo_doc", targetNamespace = "")
        String tipoDoc,
        @WebParam(name = "idioma", targetNamespace = "")
        String idioma);

    /**
     * 
     * @param demFocomFecFinNew
     * @param demFocomFecFin
     * @param numDoc
     * @param tipoDoc
     * @param codUbicUsu
     * @param demFocomNroHoras
     * @param idioma
     * @param genEsCod
     * @param demFocomTexto
     * @param demFocomNroHorasNew
     * @param codCentroUsu
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modificaForCompl", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.ModificaForCompl")
    @ResponseWrapper(localName = "modificaForComplResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.ModificaForComplResponse")
    public String modificaForCompl(
        @WebParam(name = "cod_centro_usu", targetNamespace = "")
        String codCentroUsu,
        @WebParam(name = "cod_ubic_usu", targetNamespace = "")
        String codUbicUsu,
        @WebParam(name = "num_doc", targetNamespace = "")
        String numDoc,
        @WebParam(name = "tipo_doc", targetNamespace = "")
        String tipoDoc,
        @WebParam(name = "gen_Es_cod", targetNamespace = "")
        String genEsCod,
        @WebParam(name = "dem_focom_fec_fin", targetNamespace = "")
        String demFocomFecFin,
        @WebParam(name = "dem_focom_nro_horas", targetNamespace = "")
        String demFocomNroHoras,
        @WebParam(name = "dem_focom_fec_fin_new", targetNamespace = "")
        String demFocomFecFinNew,
        @WebParam(name = "dem_focom_nro_horas_new", targetNamespace = "")
        String demFocomNroHorasNew,
        @WebParam(name = "dem_focom_texto", targetNamespace = "")
        String demFocomTexto,
        @WebParam(name = "idioma", targetNamespace = "")
        String idioma);

    /**
     * 
     * @param demFocomFecFin
     * @param numDoc
     * @param tipoDoc
     * @param codUbicUsu
     * @param demFocomNroHoras
     * @param genFamCod
     * @param idioma
     * @param genEsCod
     * @param demFocomTexto
     * @param genNivfCod
     * @param codCentroUsu
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "altaForCompl", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.AltaForCompl")
    @ResponseWrapper(localName = "altaForComplResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.AltaForComplResponse")
    public String altaForCompl(
        @WebParam(name = "cod_centro_usu", targetNamespace = "")
        String codCentroUsu,
        @WebParam(name = "cod_ubic_usu", targetNamespace = "")
        String codUbicUsu,
        @WebParam(name = "num_doc", targetNamespace = "")
        String numDoc,
        @WebParam(name = "tipo_doc", targetNamespace = "")
        String tipoDoc,
        @WebParam(name = "gen_nivf_cod", targetNamespace = "")
        String genNivfCod,
        @WebParam(name = "gen_Es_cod", targetNamespace = "")
        String genEsCod,
        @WebParam(name = "gen_fam_cod", targetNamespace = "")
        String genFamCod,
        @WebParam(name = "dem_focom_fec_fin", targetNamespace = "")
        String demFocomFecFin,
        @WebParam(name = "dem_focom_nro_horas", targetNamespace = "")
        String demFocomNroHoras,
        @WebParam(name = "dem_focom_texto", targetNamespace = "")
        String demFocomTexto,
        @WebParam(name = "idioma", targetNamespace = "")
        String idioma);

    /**
     * 
     * @param demFocomFecFin
     * @param numDoc
     * @param tipoDoc
     * @param codUbicUsu
     * @param demFocomNroHoras
     * @param idioma
     * @param genEsCod
     * @param codCentroUsu
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bajaForCompl", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.BajaForCompl")
    @ResponseWrapper(localName = "bajaForComplResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.BajaForComplResponse")
    public String bajaForCompl(
        @WebParam(name = "cod_centro_usu", targetNamespace = "")
        String codCentroUsu,
        @WebParam(name = "cod_ubic_usu", targetNamespace = "")
        String codUbicUsu,
        @WebParam(name = "num_doc", targetNamespace = "")
        String numDoc,
        @WebParam(name = "tipo_doc", targetNamespace = "")
        String tipoDoc,
        @WebParam(name = "gen_Es_cod", targetNamespace = "")
        String genEsCod,
        @WebParam(name = "dem_focom_fec_fin", targetNamespace = "")
        String demFocomFecFin,
        @WebParam(name = "dem_focom_nro_horas", targetNamespace = "")
        String demFocomNroHoras,
        @WebParam(name = "idioma", targetNamespace = "")
        String idioma);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg13
     * @param arg14
     * @param arg11
     * @param arg12
     * @param arg10
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "altaItinerario", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.AltaItinerario")
    @ResponseWrapper(localName = "altaItinerarioResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.AltaItinerarioResponse")
    public String altaItinerario(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        String arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        String arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        String arg12,
        @WebParam(name = "arg13", targetNamespace = "")
        String arg13,
        @WebParam(name = "arg14", targetNamespace = "")
        String arg14);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg15
     * @param arg13
     * @param arg14
     * @param arg11
     * @param arg12
     * @param arg10
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modificarItinerario", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.ModificarItinerario")
    @ResponseWrapper(localName = "modificarItinerarioResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.ModificarItinerarioResponse")
    public String modificarItinerario(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        String arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        String arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        String arg12,
        @WebParam(name = "arg13", targetNamespace = "")
        String arg13,
        @WebParam(name = "arg14", targetNamespace = "")
        String arg14,
        @WebParam(name = "arg15", targetNamespace = "")
        String arg15);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @param arg7
     * @param arg8
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "anularItinerario", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.AnularItinerario")
    @ResponseWrapper(localName = "anularItinerarioResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.AnularItinerarioResponse")
    public String anularItinerario(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @param arg7
     * @param arg8
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eliminarItinerario", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.EliminarItinerario")
    @ResponseWrapper(localName = "eliminarItinerarioResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.EliminarItinerarioResponse")
    public String eliminarItinerario(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cambioSitAdmSusp", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.CambioSitAdmSusp")
    @ResponseWrapper(localName = "cambioSitAdmSuspResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.CambioSitAdmSuspResponse")
    public String cambioSitAdmSusp(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6);

    /**
     * 
     * @param numDoc
     * @param tipoDocUsu
     * @param tipoDoc
     * @param codUbicUsu
     * @param idioma
     * @param numDocUsu
     * @param codCentroUsu
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reactivarDemanda", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.ReactivarDemanda")
    @ResponseWrapper(localName = "reactivarDemandaResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.ReactivarDemandaResponse")
    public String reactivarDemanda(
        @WebParam(name = "cod_centro_usu", targetNamespace = "")
        String codCentroUsu,
        @WebParam(name = "cod_ubic_usu", targetNamespace = "")
        String codUbicUsu,
        @WebParam(name = "num_doc_usu", targetNamespace = "")
        String numDocUsu,
        @WebParam(name = "tipo_doc_usu", targetNamespace = "")
        String tipoDocUsu,
        @WebParam(name = "num_doc", targetNamespace = "")
        String numDoc,
        @WebParam(name = "tipo_doc", targetNamespace = "")
        String tipoDoc,
        @WebParam(name = "idioma", targetNamespace = "")
        String idioma);

    /**
     * 
     * @param numDoc
     * @param tipoDocUsu
     * @param tipoDoc
     * @param codUbicUsu
     * @param codColect
     * @param idioma
     * @param numDocUsu
     * @param fechaColect
     * @param codCentroUsu
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "altaColectivoEspecial", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.AltaColectivoEspecial")
    @ResponseWrapper(localName = "altaColectivoEspecialResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.AltaColectivoEspecialResponse")
    public String altaColectivoEspecial(
        @WebParam(name = "cod_centro_usu", targetNamespace = "")
        String codCentroUsu,
        @WebParam(name = "cod_ubic_usu", targetNamespace = "")
        String codUbicUsu,
        @WebParam(name = "tipo_doc_usu", targetNamespace = "")
        String tipoDocUsu,
        @WebParam(name = "num_doc_usu", targetNamespace = "")
        String numDocUsu,
        @WebParam(name = "tipo_doc", targetNamespace = "")
        String tipoDoc,
        @WebParam(name = "num_doc", targetNamespace = "")
        String numDoc,
        @WebParam(name = "cod_colect", targetNamespace = "")
        String codColect,
        @WebParam(name = "fecha_colect", targetNamespace = "")
        String fechaColect,
        @WebParam(name = "idioma", targetNamespace = "")
        String idioma);

    /**
     * 
     * @param numDoc
     * @param tipoDocUsu
     * @param tipoDoc
     * @param codUbicUsu
     * @param codColect
     * @param idioma
     * @param numDocUsu
     * @param fechaColect
     * @param codCentroUsu
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bajaColectivoEspecial", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.BajaColectivoEspecial")
    @ResponseWrapper(localName = "bajaColectivoEspecialResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.BajaColectivoEspecialResponse")
    public String bajaColectivoEspecial(
        @WebParam(name = "cod_centro_usu", targetNamespace = "")
        String codCentroUsu,
        @WebParam(name = "cod_ubic_usu", targetNamespace = "")
        String codUbicUsu,
        @WebParam(name = "tipo_doc_usu", targetNamespace = "")
        String tipoDocUsu,
        @WebParam(name = "num_doc_usu", targetNamespace = "")
        String numDocUsu,
        @WebParam(name = "tipo_doc", targetNamespace = "")
        String tipoDoc,
        @WebParam(name = "num_doc", targetNamespace = "")
        String numDoc,
        @WebParam(name = "cod_colect", targetNamespace = "")
        String codColect,
        @WebParam(name = "fecha_colect", targetNamespace = "")
        String fechaColect,
        @WebParam(name = "idioma", targetNamespace = "")
        String idioma);

    /**
     * 
     * @param numDoc
     * @param tipoDocUsu
     * @param tipoDoc
     * @param codUbicUsu
     * @param codColect
     * @param idioma
     * @param numDocUsu
     * @param fechaColect
     * @param codCentroUsu
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modificaColectivoEspecial", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.ModificaColectivoEspecial")
    @ResponseWrapper(localName = "modificaColectivoEspecialResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.ModificaColectivoEspecialResponse")
    public String modificaColectivoEspecial(
        @WebParam(name = "cod_centro_usu", targetNamespace = "")
        String codCentroUsu,
        @WebParam(name = "cod_ubic_usu", targetNamespace = "")
        String codUbicUsu,
        @WebParam(name = "tipo_doc_usu", targetNamespace = "")
        String tipoDocUsu,
        @WebParam(name = "num_doc_usu", targetNamespace = "")
        String numDocUsu,
        @WebParam(name = "tipo_doc", targetNamespace = "")
        String tipoDoc,
        @WebParam(name = "num_doc", targetNamespace = "")
        String numDoc,
        @WebParam(name = "cod_colect", targetNamespace = "")
        String codColect,
        @WebParam(name = "fecha_colect", targetNamespace = "")
        String fechaColect,
        @WebParam(name = "idioma", targetNamespace = "")
        String idioma);

    /**
     * 
     * @param numDoc
     * @param tipoDocUsu
     * @param tipoDoc
     * @param codUbicUsu
     * @param idConvenio
     * @param idioma
     * @param numDocUsu
     * @param codCentroUsu
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "altaRelacionDemandaConvenio", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.AltaRelacionDemandaConvenio")
    @ResponseWrapper(localName = "altaRelacionDemandaConvenioResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.AltaRelacionDemandaConvenioResponse")
    public String altaRelacionDemandaConvenio(
        @WebParam(name = "cod_centro_usu", targetNamespace = "")
        String codCentroUsu,
        @WebParam(name = "cod_ubic_usu", targetNamespace = "")
        String codUbicUsu,
        @WebParam(name = "tipo_doc_usu", targetNamespace = "")
        String tipoDocUsu,
        @WebParam(name = "num_doc_usu", targetNamespace = "")
        String numDocUsu,
        @WebParam(name = "tipo_doc", targetNamespace = "")
        String tipoDoc,
        @WebParam(name = "num_doc", targetNamespace = "")
        String numDoc,
        @WebParam(name = "idConvenio", targetNamespace = "")
        String idConvenio,
        @WebParam(name = "idioma", targetNamespace = "")
        String idioma);

    /**
     * 
     * @param numDoc
     * @param tipoDocUsu
     * @param tipoDoc
     * @param codUbicUsu
     * @param idConvenio
     * @param idioma
     * @param numDocUsu
     * @param causa
     * @param codCentroUsu
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modificaRelacionDemandaConvenio", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.ModificaRelacionDemandaConvenio")
    @ResponseWrapper(localName = "modificaRelacionDemandaConvenioResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.ModificaRelacionDemandaConvenioResponse")
    public String modificaRelacionDemandaConvenio(
        @WebParam(name = "cod_centro_usu", targetNamespace = "")
        String codCentroUsu,
        @WebParam(name = "cod_ubic_usu", targetNamespace = "")
        String codUbicUsu,
        @WebParam(name = "tipo_doc_usu", targetNamespace = "")
        String tipoDocUsu,
        @WebParam(name = "num_doc_usu", targetNamespace = "")
        String numDocUsu,
        @WebParam(name = "tipo_doc", targetNamespace = "")
        String tipoDoc,
        @WebParam(name = "num_doc", targetNamespace = "")
        String numDoc,
        @WebParam(name = "idConvenio", targetNamespace = "")
        String idConvenio,
        @WebParam(name = "causa", targetNamespace = "")
        String causa,
        @WebParam(name = "idioma", targetNamespace = "")
        String idioma);

    /**
     * 
     * @param servicios
     * @param codigoCentro
     * @param tipoDocUsu
     * @param firmaOid
     * @param codigoUbic
     * @param numDocUsu
     * @param corrDemanda
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "firmaServicio", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.FirmaServicio")
    @ResponseWrapper(localName = "firmaServicioResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.FirmaServicioResponse")
    public String firmaServicio(
        @WebParam(name = "corr_demanda", targetNamespace = "")
        String corrDemanda,
        @WebParam(name = "codigo_centro", targetNamespace = "")
        String codigoCentro,
        @WebParam(name = "codigo_ubic", targetNamespace = "")
        String codigoUbic,
        @WebParam(name = "Tipo_doc_usu", targetNamespace = "")
        String tipoDocUsu,
        @WebParam(name = "Num_doc_usu", targetNamespace = "")
        String numDocUsu,
        @WebParam(name = "Servicios", targetNamespace = "")
        List<String> servicios,
        @WebParam(name = "Firma_oid", targetNamespace = "")
        String firmaOid);

    /**
     * 
     * @param modalidad
     * @param suspenderDemanda
     * @param fechaFin
     * @param especialidad
     * @param codigoUbic
     * @param viaFinanciacion
     * @param accionFormativa
     * @param codigoCentro
     * @param tipoDocUsu
     * @param tipoServicio
     * @param osOfeId
     * @param subserv
     * @param serv
     * @param descLibre
     * @param numDocUsu
     * @param fechaInicio
     * @param corrDemanda
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Inicio_AccFor")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Inicio_AccFor", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.InicioAccFor")
    @ResponseWrapper(localName = "Inicio_AccForResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.InicioAccForResponse")
    public String inicioAccFor(
        @WebParam(name = "corr_demanda", targetNamespace = "")
        String corrDemanda,
        @WebParam(name = "fecha_inicio", targetNamespace = "")
        String fechaInicio,
        @WebParam(name = "fecha_fin", targetNamespace = "")
        String fechaFin,
        @WebParam(name = "tipo_servicio", targetNamespace = "")
        String tipoServicio,
        @WebParam(name = "via_financiacion", targetNamespace = "")
        String viaFinanciacion,
        @WebParam(name = "especialidad", targetNamespace = "")
        String especialidad,
        @WebParam(name = "accion_formativa", targetNamespace = "")
        String accionFormativa,
        @WebParam(name = "desc_libre", targetNamespace = "")
        String descLibre,
        @WebParam(name = "codigo_centro", targetNamespace = "")
        String codigoCentro,
        @WebParam(name = "codigo_ubic", targetNamespace = "")
        String codigoUbic,
        @WebParam(name = "Tipo_doc_usu", targetNamespace = "")
        String tipoDocUsu,
        @WebParam(name = "Num_doc_usu", targetNamespace = "")
        String numDocUsu,
        @WebParam(name = "Os_ofe_id", targetNamespace = "")
        String osOfeId,
        @WebParam(name = "Suspender_demanda", targetNamespace = "")
        String suspenderDemanda,
        @WebParam(name = "serv", targetNamespace = "")
        String serv,
        @WebParam(name = "subserv", targetNamespace = "")
        String subserv,
        @WebParam(name = "modalidad", targetNamespace = "")
        String modalidad);

    /**
     * 
     * @param acreditable
     * @param areaConoc
     * @param modalidad
     * @param nroHoras
     * @param tipoFormacion
     * @param fechaFin
     * @param codigoUbic
     * @param especialidad
     * @param nroMin
     * @param accionFormativa
     * @param codigoCentro
     * @param tipoDocUsu
     * @param unidadesCompetencia
     * @param osOfeId
     * @param resultado
     * @param subserv
     * @param serv
     * @param reactivarDemanda
     * @param descLibre
     * @param numDocUsu
     * @param corrDemanda
     * @param familiaProfInt
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Fin_AccFor")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Fin_AccFor", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.FinAccFor")
    @ResponseWrapper(localName = "Fin_AccForResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.FinAccForResponse")
    public String finAccFor(
        @WebParam(name = "corr_demanda", targetNamespace = "")
        String corrDemanda,
        @WebParam(name = "codigo_centro", targetNamespace = "")
        String codigoCentro,
        @WebParam(name = "codigo_ubic", targetNamespace = "")
        String codigoUbic,
        @WebParam(name = "Tipo_doc_usu", targetNamespace = "")
        String tipoDocUsu,
        @WebParam(name = "Num_doc_usu", targetNamespace = "")
        String numDocUsu,
        @WebParam(name = "accion_formativa", targetNamespace = "")
        String accionFormativa,
        @WebParam(name = "resultado", targetNamespace = "")
        String resultado,
        @WebParam(name = "acreditable", targetNamespace = "")
        String acreditable,
        @WebParam(name = "tipo_formacion", targetNamespace = "")
        String tipoFormacion,
        @WebParam(name = "especialidad", targetNamespace = "")
        String especialidad,
        @WebParam(name = "area_conoc", targetNamespace = "")
        String areaConoc,
        @WebParam(name = "familia_prof_int", targetNamespace = "")
        String familiaProfInt,
        @WebParam(name = "desc_libre", targetNamespace = "")
        String descLibre,
        @WebParam(name = "fecha_fin", targetNamespace = "")
        String fechaFin,
        @WebParam(name = "nro_horas", targetNamespace = "")
        String nroHoras,
        @WebParam(name = "nro_min", targetNamespace = "")
        String nroMin,
        @WebParam(name = "unidades_competencia", targetNamespace = "")
        List<String> unidadesCompetencia,
        @WebParam(name = "Os_ofe_id", targetNamespace = "")
        String osOfeId,
        @WebParam(name = "Reactivar_demanda", targetNamespace = "")
        String reactivarDemanda,
        @WebParam(name = "serv", targetNamespace = "")
        String serv,
        @WebParam(name = "subserv", targetNamespace = "")
        String subserv,
        @WebParam(name = "modalidad", targetNamespace = "")
        String modalidad);

    /**
     * 
     * @param secuencialServicio
     * @param centro
     * @param resultado
     * @param tipoDocumento
     * @param numDocumento
     * @param ubicacion
     * @param origen
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cambiarResultadoServicio", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.CambiarResultadoServicio")
    @ResponseWrapper(localName = "cambiarResultadoServicioResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.CambiarResultadoServicioResponse")
    public String cambiarResultadoServicio(
        @WebParam(name = "origen", targetNamespace = "")
        String origen,
        @WebParam(name = "centro", targetNamespace = "")
        String centro,
        @WebParam(name = "ubicacion", targetNamespace = "")
        String ubicacion,
        @WebParam(name = "tipo_documento", targetNamespace = "")
        String tipoDocumento,
        @WebParam(name = "num_documento", targetNamespace = "")
        String numDocumento,
        @WebParam(name = "secuencial_servicio", targetNamespace = "")
        String secuencialServicio,
        @WebParam(name = "resultado", targetNamespace = "")
        String resultado);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @param arg7
     * @return
     *     returns es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.PersonaFisicaWSValueObject
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaUltIdentifAgrupacion", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.ConsultaUltIdentifAgrupacion")
    @ResponseWrapper(localName = "consultaUltIdentifAgrupacionResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.ConsultaUltIdentifAgrupacionResponse")
    public PersonaFisicaWSValueObject consultaUltIdentifAgrupacion(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7);

    /**
     * 
     * @param numDoc
     * @param tipoDoc
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "esDemandanteEmpleoASSPEE", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.EsDemandanteEmpleoASSPEE")
    @ResponseWrapper(localName = "esDemandanteEmpleoASSPEEResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.EsDemandanteEmpleoASSPEEResponse")
    public String esDemandanteEmpleoASSPEE(
        @WebParam(name = "tipo_doc", targetNamespace = "")
        String tipoDoc,
        @WebParam(name = "num_doc", targetNamespace = "")
        String numDoc);

    /**
     * 
     * @param numDoc
     * @param tipoDoc
     * @param numMeses
     * @param fechaRef
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaDLD", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.ConsultaDLD")
    @ResponseWrapper(localName = "consultaDLDResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.ConsultaDLDResponse")
    public String consultaDLD(
        @WebParam(name = "tipo_doc", targetNamespace = "")
        String tipoDoc,
        @WebParam(name = "num_doc", targetNamespace = "")
        String numDoc,
        @WebParam(name = "fecha_ref", targetNamespace = "")
        String fechaRef,
        @WebParam(name = "num_meses", targetNamespace = "")
        String numMeses);

    /**
     * 
     * @param codigoCentro
     * @param numDoc
     * @param tipoDocUsu
     * @param tipoDoc
     * @param codigoUbic
     * @param numDocUsu
     * @return
     *     returns java.util.List<es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.DuplicadosWSValueObject>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListaDuplicados", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.GetListaDuplicados")
    @ResponseWrapper(localName = "getListaDuplicadosResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.GetListaDuplicadosResponse")
    public List<DuplicadosWSValueObject> getListaDuplicados(
        @WebParam(name = "codigo_centro", targetNamespace = "")
        String codigoCentro,
        @WebParam(name = "codigo_ubic", targetNamespace = "")
        String codigoUbic,
        @WebParam(name = "Tipo_doc_usu", targetNamespace = "")
        String tipoDocUsu,
        @WebParam(name = "Num_doc_usu", targetNamespace = "")
        String numDocUsu,
        @WebParam(name = "tipo_doc", targetNamespace = "")
        String tipoDoc,
        @WebParam(name = "num_doc", targetNamespace = "")
        String numDoc);

    /**
     * 
     * @param codigoCentro
     * @param numDoc
     * @param tipoDocUsu
     * @param tipoDoc
     * @param codigoUbic
     * @param tipoDocDuplicado
     * @param accion
     * @param numDocDuplicado
     * @param numDocUsu
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "tratarDuplicados", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.TratarDuplicados")
    @ResponseWrapper(localName = "tratarDuplicadosResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.TratarDuplicadosResponse")
    public String tratarDuplicados(
        @WebParam(name = "codigo_centro", targetNamespace = "")
        String codigoCentro,
        @WebParam(name = "codigo_ubic", targetNamespace = "")
        String codigoUbic,
        @WebParam(name = "Tipo_doc_usu", targetNamespace = "")
        String tipoDocUsu,
        @WebParam(name = "Num_doc_usu", targetNamespace = "")
        String numDocUsu,
        @WebParam(name = "tipo_doc", targetNamespace = "")
        String tipoDoc,
        @WebParam(name = "num_doc", targetNamespace = "")
        String numDoc,
        @WebParam(name = "tipo_doc_duplicado", targetNamespace = "")
        String tipoDocDuplicado,
        @WebParam(name = "num_doc_duplicado", targetNamespace = "")
        String numDocDuplicado,
        @WebParam(name = "accion", targetNamespace = "")
        String accion);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg23
     * @param arg0
     * @param arg22
     * @param arg21
     * @param arg20
     * @param arg27
     * @param arg26
     * @param arg25
     * @param arg24
     * @param arg29
     * @param arg28
     * @param arg30
     * @param arg32
     * @param arg31
     * @param arg33
     * @param arg19
     * @param arg17
     * @param arg18
     * @param arg15
     * @param arg16
     * @param arg13
     * @param arg14
     * @param arg11
     * @param arg12
     * @param arg10
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "altaServicioConvocatoria", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.AltaServicioConvocatoria")
    @ResponseWrapper(localName = "altaServicioConvocatoriaResponse", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", className = "es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.AltaServicioConvocatoriaResponse")
    public String altaServicioConvocatoria(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        String arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        String arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        String arg12,
        @WebParam(name = "arg13", targetNamespace = "")
        String arg13,
        @WebParam(name = "arg14", targetNamespace = "")
        String arg14,
        @WebParam(name = "arg15", targetNamespace = "")
        String arg15,
        @WebParam(name = "arg16", targetNamespace = "")
        String arg16,
        @WebParam(name = "arg17", targetNamespace = "")
        String arg17,
        @WebParam(name = "arg18", targetNamespace = "")
        String arg18,
        @WebParam(name = "arg19", targetNamespace = "")
        String arg19,
        @WebParam(name = "arg20", targetNamespace = "")
        String arg20,
        @WebParam(name = "arg21", targetNamespace = "")
        String arg21,
        @WebParam(name = "arg22", targetNamespace = "")
        String arg22,
        @WebParam(name = "arg23", targetNamespace = "")
        String arg23,
        @WebParam(name = "arg24", targetNamespace = "")
        String arg24,
        @WebParam(name = "arg25", targetNamespace = "")
        String arg25,
        @WebParam(name = "arg26", targetNamespace = "")
        String arg26,
        @WebParam(name = "arg27", targetNamespace = "")
        String arg27,
        @WebParam(name = "arg28", targetNamespace = "")
        String arg28,
        @WebParam(name = "arg29", targetNamespace = "")
        String arg29,
        @WebParam(name = "arg30", targetNamespace = "")
        String arg30,
        @WebParam(name = "arg31", targetNamespace = "")
        String arg31,
        @WebParam(name = "arg32", targetNamespace = "")
        String arg32,
        @WebParam(name = "arg33", targetNamespace = "")
        String arg33);

}
