--DESPLEGABLES
select * from e_des where des_cod='MEPE';
select * from e_des_val where des_cod='MEPE';
insert into e_des (des_cod,des_nom) values ('MEPE','MESES CONTRATO PEX');
insert into e_des_val (des_cod,des_val_cod,des_nom,des_val_estado) values ('MEPE','10','10 MESES|10 HILABETE','A');
insert into e_des_val (des_cod,des_val_cod,des_nom,des_val_estado) values ('MEPE','11','11 MESES|11 HILABETE','A');
insert into e_des_val (des_cod,des_val_cod,des_nom,des_val_estado) values ('MEPE','12','12 MESES|12 HILABETE','A');

select * from e_des where des_cod='GCON';
select * from e_des_val where des_cod='GCON';
insert into e_des (des_cod,des_nom) values ('GCON','GRUPOS COTIZACION PEX');
insert into e_des_val (des_cod,des_val_cod,des_nom,des_val_estado) values ('GCON','1','GRUPO 1|1. TALDEA','A');
insert into e_des_val (des_cod,des_val_cod,des_nom,des_val_estado) values ('GCON','2','GRUPO 2|2. TALDEA','A');
insert into e_des_val (des_cod,des_val_cod,des_nom,des_val_estado) values ('GCON','3','GRUPO 3|3. TALDEA','A');
insert into e_des_val (des_cod,des_val_cod,des_nom,des_val_estado) values ('GCON','4','GRUPO 4|4. TALDEA','A');
insert into e_des_val (des_cod,des_val_cod,des_nom,des_val_estado) values ('GCON','5','GRUPO 5|5. TALDEA','A');
insert into e_des_val (des_cod,des_val_cod,des_nom,des_val_estado) values ('GCON','6','GRUPO 6|6. TALDEA','A');
insert into e_des_val (des_cod,des_val_cod,des_nom,des_val_estado) values ('GCON','7','GRUPO 7|7. TALDEA','A');
insert into e_des_val (des_cod,des_val_cod,des_nom,des_val_estado) values ('GCON','8','GRUPO 8|8. TALDEA','A');
insert into e_des_val (des_cod,des_val_cod,des_nom,des_val_estado) values ('GCON','9','GRUPO 9|9. TALDEA','A');


--TABLA SEGÚN MAPEO 'Mapeo campos - PEX- V0.xlsx'
CREATE SEQUENCE  SEQ_MELANBIDE85_CONTRATACION  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;

 CREATE TABLE "FLB"."MELANBIDE85_CONTRATACION" 
   (	"ID" NUMBER(8,0) NOT NULL ENABLE, 
	"NUM_EXP" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NUM_PUESTO" NUMBER(4,0) NOT NULL ENABLE, 
	"DENOMPUESTO1" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"TITULACION1" VARCHAR2(150 BYTE) NOT NULL ENABLE, 
	"MUNICIPIOCT1" VARCHAR2(150 BYTE) NOT NULL ENABLE, 
	"DURCONTRATO1" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	"GRUPOCOTIZ1" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	"COSTESALARIAL1" NUMBER(8,2) NOT NULL ENABLE, 
	"COSTEEPIS1" NUMBER(8,2) NOT NULL ENABLE, 
	"SUBVSOLICITADA1" NUMBER(8,2) NOT NULL ENABLE, 
	"EMPVERDE1" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"EMPDIGIT1" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "MELANBIDE85_CONTRATACION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLB_DBS1"  ENABLE, 
	 CONSTRAINT "MELANBIDE85_CONTRATACION_UK1" UNIQUE ("NUM_EXP", "NUM_PUESTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLB_DBS1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLB_DBS1" ;
  
  
CREATE SEQUENCE  SEQ_MELANBIDE85_CONTRATA_INI  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;

CREATE TABLE "FLB"."MELANBIDE85_CONTRATACION_INI" 
   (	"ID" NUMBER(8,0) NOT NULL ENABLE, 
	"NUM_EXP" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NUM_PUESTO" NUMBER(4,0) NOT NULL ENABLE, 
	"NOFERTA2" VARCHAR2(50 BYTE), 
	"NOMBRE2" VARCHAR2(100 BYTE), 
	"APELLIDO12" VARCHAR2(50 BYTE), 
	"APELLIDO22" VARCHAR2(50 BYTE), 
	"DNINIE2" VARCHAR2(15 BYTE), 
	"SEXO2" VARCHAR2(1 BYTE), 
	"TITULACION2" VARCHAR2(150 BYTE), 
	"DENOMPUESTO2" VARCHAR2(500 BYTE), 
	"MUNICIPIOCT2" VARCHAR2(150 BYTE), 
	"GRUPOCOTIZ2" VARCHAR2(2 BYTE), 
	"DURCONTRATO2" VARCHAR2(2 BYTE), 
	"FECHANACIMIENTO2" DATE, 
	"FECHAINICIO2" DATE, 
	"EDAD" NUMBER(2,0), 
	"RETRIBUCIONBRUTA2" NUMBER(8,2), 
	"EMPVERDE2" VARCHAR2(1 BYTE), 
	"EMPDIGIT2" VARCHAR2(1 BYTE), 
	 CONSTRAINT "MELANBIDE85_CONTRATA_INI_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLB_DBS1"  ENABLE, 
	 CONSTRAINT "FK_85CONTRATACION_INI" FOREIGN KEY ("NUM_EXP", "NUM_PUESTO")
	  REFERENCES "FLB"."MELANBIDE85_CONTRATACION" ("NUM_EXP", "NUM_PUESTO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLB_DBS1" ;
  
  
CREATE SEQUENCE  SEQ_MELANBIDE85_CONTRATA_FIN  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;

 CREATE TABLE "FLB"."MELANBIDE85_CONTRATACION_FIN" 
   (	"ID" NUMBER(8,0) NOT NULL ENABLE, 
	"NUM_EXP" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NUM_PUESTO" NUMBER(4,0) NOT NULL ENABLE, 
	"NOMBRE3" VARCHAR2(100 BYTE), 
	"APELLIDO13" VARCHAR2(50 BYTE), 
	"APELLIDO23" VARCHAR2(50 BYTE), 
	"DNINIE3" VARCHAR2(15 BYTE), 
	"DURCONTRATO3" VARCHAR2(2 BYTE), 
	"FECHAINICIO3" DATE, 
	"FECHAFIN3" DATE, 
	"COSTESALARIAL3" NUMBER(8,2), 
	"COSTESSS3" NUMBER(8,2), 
	"COSTEEPIS3" NUMBER(8,2), 
	"COSTETOTALREAL3" NUMBER(8,2), 
	"SUBVCONCEDIDALAN3" NUMBER(8,2), 
	 CONSTRAINT "MELANBIDE85_CONTRATA_FIN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLB_DBS1"  ENABLE, 
	 CONSTRAINT "FK_85CONTRATACION_FIN" FOREIGN KEY ("NUM_EXP", "NUM_PUESTO")
	  REFERENCES "FLB"."MELANBIDE85_CONTRATACION" ("NUM_EXP", "NUM_PUESTO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLB_DBS1" ;

