CREATE TABLE  MELANBIDE69_FACTURAS(
  ID                NUMBER(8,0),
  NUM_EXP 	        VARCHAR2(30 BYTE),
  ESTADO            VARCHAR2(1 BYTE),
  FECHA_FACTURA     DATE,
  CODIGO_CONCEPTO   VARCHAR2(3 BYTE),
  CODIGO_SUBCONCEPTO       VARCHAR2(5 BYTE), 
  IMPORTE           NUMBER(14,2),
  ENTREGADA_FACT    VARCHAR2(1 BYTE),
  ENTREGADO_JUSTIF  VARCHAR2(1 BYTE),
  OBSERVACIONES     CLOB,
  
  CONSTRAINT MELANBIDE69_FACTURAS_PK PRIMARY KEY (ID)
);

COMMENT ON COLUMN  MELANBIDE69_FACTURAS.ID IS 'Índice secuencial y clave primaria de la tabla'; 
COMMENT ON COLUMN  MELANBIDE69_FACTURAS.NUM_EXP IS 'Número de expediente';
COMMENT ON COLUMN  MELANBIDE69_FACTURAS.ESTADO IS 'Estado de la factura. A-Aceptada;N-No aceptada';
COMMENT ON COLUMN  MELANBIDE69_FACTURAS.FECHA_FACTURA IS 'Fecha de la factura';
COMMENT ON COLUMN  MELANBIDE69_FACTURAS.CODIGO_CONCEPTO IS 'Identificador de concepto.';
COMMENT ON COLUMN  MELANBIDE69_FACTURAS.CODIGO_SUBCONCEPTO IS 'Identificador de subconcepto';
COMMENT ON COLUMN  MELANBIDE69_FACTURAS.IMPORTE IS 'Importe de la factura';
COMMENT ON COLUMN  MELANBIDE69_FACTURAS.ENTREGADA_FACT IS 'Indica si se ha entregado la factura. S-Si;N-No';
COMMENT ON COLUMN  MELANBIDE69_FACTURAS.ENTREGADO_JUSTIF IS 'Indica si se ha entregado el justificante de pago. S-Si;N-No';
COMMENT ON COLUMN  MELANBIDE69_FACTURAS.OBSERVACIONES IS 'Comentarios sobre la factura'; 
COMMENT ON TABLE   MELANBIDE69_FACTURAS IS 'Relación de facturas de justificación del procedimiento APES';

CREATE SEQUENCE SEQ_MELANBIDE69_FACTURAS MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1;
COMMIT;

Insert into E_DES (DES_COD,DES_NOM) values ('CPT2','DESGLOSE CONCEPTO 2');
Insert into E_DES (DES_COD,DES_NOM) values ('CPTO','CONCEPTO');
Insert into E_DES (DES_COD,DES_NOM) values ('ACEP','ESTADO');
commit;

Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('CPT2','101','CUOTAS RELATIVAS AL PAGO DE LA COTIZACIÓN EN EL RÉGIMEN ESPECIAL DE TRABAJADORES AUTÓNOMOS DE LA SEGURIDAD SOCIAL');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('CPT2','201','GASTOS DE COMUNICACIÓN LIGADOS AL PROYECTO (CAMPAÑAS DE PUBLICIDAD, ANUNCIO EN PRENSA, CUÑAS DE RADIO Y TELEVISIÓN, DISEÑO DE PÁGINAS WEB, DISEÑO DE REDES SOCIALES)');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('CPT2','202','BANNER PUBLICITARIO EN PÁGINA WEB DE OTRA EMPRESA');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('CPT2','203','CUOTAS DE MANTENIMIENTO DE PÁGINAS WEB Y GASTOS RELATIVOS A LA INCORPORACIÓN DE PLUGINS EN LA WEB');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('CPT2','204','COSTE DE LOS SERVICIOS DE PROMOCIÓN EN FACEBOOK');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('CPT2','205','PATROCINIO O SPONSOR DE ALGÚN EVENTO RELACIONADO CON LA ACTIVIDAD COMERCIAL, O DEL MUNICIPIO, ETC');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('CPT2','206','MERCHANDISING DE PUBLICIDAD DE LA EMPRESA (BOLIS, CALENDARIOS, USBS, BOLSAS, NECESERES, MOCHILAS, BOLÍGRAFOS, GLOBOS ETC CON EL LOGO DE LA EMPRESA)');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('CPT2','207','ROTULACIÓN DE ESTABLECIMIENTOS, VEHÍCULOS, ILUMINACIÓN EN RÓTULOS, ETC');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('CPT2','208','PUBLICIDAD EN MANO: DISEÑO, IMPRESIÓN Y ENTREGA DE FOLLETOS PUBLICITARIOS Y CARTELERÍA. IMPRESIÓN DE TARJETAS DE VISITA');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('CPT2','209','DISEÑO DE LOGO');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('CPT2','210','TÓTEMS Y CABALLETES PUBLICITARIOS, PIZARRAS LUMINOSAS ETC');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('CPT2','301','EL ASESORAMIENTO FISCAL, LABORAL, CONTABLE, JURÍDICO O ADMINISTRATIVO RELATIVO A LA TENEDURÍA DE LIBROS Y OBLIGACIONES FISCALES Y CONTABLES COTIDIANAS');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('CPT2','401','GASTOS DE COACHING');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('CPT2','501','GASTOS DE ASESORAMIENTO PARA CAMBIOS Y MEJORAS DEL ESCAPARATE');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('CPT2','601','CURSOS DE FORMACIÓN REALIZADOS POR EL AUTÓNOMO (NO ASALARIADOS) DIRECTAMENTE RELACIONADOS CON LA PUESTA EN MARCHA Y FUNCIONAMIENTO DE LA EMPRESA (FORMACIÓN RELATIVA A LA ACTIVIDAD QUE SE EJERCE COMO TAL, PREVENCIÓN DE RIESGOS LABORALES, ESCAPARATISMO, FORMACIÓN RELATIVA A LA GESTIÓN DE LA WEB Y REDES SOCIALES, FORMACIÓN EN GESTIÓN EMPRESARIAL)');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('CPT2','701','LAS CUOTAS OBLIGATORIAS DE ASOCIACIONES DE COMERCIANTES, MUTUALIDADES Y COLEGIOS');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('CPT2','801','ASESORAMIENTO SOBRE RIESGOS LABORALES');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('CPTO','1','CUOTAS RELATIVAS AL PAGO DE LA COTIZACIÓN EN EL RÉGIMEN ESPECIAL DE TRABAJADORES AUTÓNOMOS DE LA SEGURIDAD SOCIAL');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('CPTO','2','GASTOS DE PUBLICIDAD');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('CPTO','3','EL ASESORAMIENTO FISCAL, LABORAL, CONTABLE, JURÍDICO O ADMINISTRATIVO RELATIVO A LA TENEDURÍA DE LIBROS Y OBLIGACIONES FISCALES Y CONTABLES COTIDIANAS');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('CPTO','4','GASTOS DE COACHING');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('CPTO','5','GASTOS DE ASESORAMIENTO PARA CAMBIOS Y MEJORAS DEL ESCAPARATE');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('CPTO','6','CURSOS DE FORMACIÓN REALIZADOS POR EL AUTÓNOMO (NO ASALARIADOS) DIRECTAMENTE RELACIONADOS CON LA PUESTA EN MARCHA Y FUNCIONAMIENTO DE LA EMPRESA (FORMACIÓN RELATIVA A LA ACTIVIDAD QUE SE EJERCE COMO TAL, PREVENCIÓN DE RIESGOS LABORALES, ESCAPARATISMO, FORMACIÓN RELATIVA A LA GESTIÓN DE LA WEB Y REDES SOCIALES, FORMACIÓN EN GESTIÓN EMPRESARIAL)');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('CPTO','7','LAS CUOTAS OBLIGATORIAS DE ASOCIACIONES DE COMERCIANTES, MUTUALIDADES Y COLEGIOS');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('CPTO','8','ASESORAMIENTO SOBRE RIESGOS LABORALES');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('ACEP','A','ACEPTADA');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('ACEP','N','NO ACEPTADA');
commit;