ALTER TABLE MELANBIDE69_FACTURAS
ADD IDENTIFICACION VARCHAR2(100 BYTE);
COMMIT;

Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('CPTO','9','OTROS');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('CPT2','901','OTROS');
commit;
