-- Auditoria independiente para consultas masivas de vida laboral por NIF.
-- No reutiliza INTEROP_VIDALABORAL para mantener separacion de expedientes.

CREATE SEQUENCE SEQ_INTEROP_CVL_MASIVO_NIF
  MINVALUE 1
  MAXVALUE 9999999999999999999999999999
  INCREMENT BY 1
  START WITH 1
  NOCACHE
  NOORDER
  NOCYCLE;

CREATE TABLE INTEROP_CVL_MASIVO_NIF (
  ID NUMBER(19,0) NOT NULL,
  FECHA_EJECUCION TIMESTAMP NOT NULL,
  NIF VARCHAR2(15 CHAR) NOT NULL,
  TIPO_DOC VARCHAR2(10 CHAR),
  COD_RESPUESTA VARCHAR2(20 CHAR),
  DESC_RESPUESTA VARCHAR2(500 CHAR),
  PAYLOAD_RESUMEN VARCHAR2(2000 CHAR),
  USUARIO VARCHAR2(100 CHAR) NOT NULL,
  CONSTRAINT PK_INTEROP_CVL_MASIVO_NIF PRIMARY KEY (ID)
);

CREATE INDEX IDX_ICMN_FECHA ON INTEROP_CVL_MASIVO_NIF (FECHA_EJECUCION);
CREATE INDEX IDX_ICMN_NIF ON INTEROP_CVL_MASIVO_NIF (NIF);
