--DESPLEGABLES

##################### CoDIGOS DESPLEGABLES - IGCEE #####################
#SEXO - SEXO 
0/MODULO_INTEGRACION/MELANBIDE91/IGCEE/COD_DES_SEXO=SEXO
1/MODULO_INTEGRACION/MELANBIDE91/IGCEE/COD_DES_SEXO=SEXO


#JORN - JORN 
0/MODULO_INTEGRACION/MELANBIDE91/IGCEE/COD_DES_JORN=JORN
1/MODULO_INTEGRACION/MELANBIDE91/IGCEE/COD_DES_JORN=JORN

#DATOS - DATOS
0/MODULO_INTEGRACION/MELANBIDE91/IGCEE/COD_DES_DATOS=TDAT
1/MODULO_INTEGRACION/MELANBIDE91/IGCEE/COD_DES_DATOS=TDAT

0/MODULO_INTEGRACION/MELANBIDE91/IGCEE/CODIGO_DESPLEGABLE_BOOLEAN=BOOL
1/MODULO_INTEGRACION/MELANBIDE91/IGCEE/CODIGO_DESPLEGABLE_BOOLEAN=BOOL



--TABLAS

  CREATE TABLE MELANBIDE91_CONTR_GEN 
  ( ID NUMBER(4,0) NOT NULL ENABLE, 
  NUM_EXP VARCHAR2(20 BYTE) NOT NULL, 
  NOMBRE VARCHAR2(100 BYTE) NOT NULL, 
  APELLIDO1 VARCHAR2(50 BYTE) NOT NULL,
  APELLIDO2 VARCHAR2(50 BYTE),
  SEXO VARCHAR2(1 BYTE), 
  DNI VARCHAR2(15 BYTE) NOT NULL, 
  PSIQUICA NUMBER (6,2), 
  FISICA NUMBER (6,2),
  SENSORIAL NUMBER (6,2),
  FECINI DATE,  
  JORNADA VARCHAR2 (4 BYTE),
  PORCPARCIAL NUMBER (6,2),
    CONSTRAINT MELANBIDE91_CONTR_GEN_PK PRIMARY KEY (ID)
 )
 ;

  COMMENT ON COLUMN MELANBIDE91_CONTR_GEN.ID IS 'ID';
  COMMENT ON COLUMN MELANBIDE91_CONTR_GEN.NUM_EXP IS 'Numero expediente';
  COMMENT ON COLUMN MELANBIDE91_CONTR_GEN.NOMBRE IS 'Nombre';
  COMMENT ON COLUMN MELANBIDE91_CONTR_GEN.APELLIDO1 IS 'Apellido 1';
  COMMENT ON COLUMN MELANBIDE91_CONTR_GEN.APELLIDO2 IS 'Apellidos 2';
  COMMENT ON COLUMN MELANBIDE91_CONTR_GEN.SEXO IS 'Sexo';
  COMMENT ON COLUMN MELANBIDE91_CONTR_GEN.DNI IS 'DNI';
  COMMENT ON COLUMN MELANBIDE91_CONTR_GEN.PSIQUICA IS 'Tipo y grado discapacidad psiquica (Porcentaje)';
  COMMENT ON COLUMN MELANBIDE91_CONTR_GEN.FISICA IS 'Tipo y grado discapacidad fisica (Porcentaje)';
  COMMENT ON COLUMN MELANBIDE91_CONTR_GEN.SENSORIAL IS 'Tipo y grado discapacidad sensorial (Porcentaje)';
  COMMENT ON COLUMN MELANBIDE91_CONTR_GEN.FECINI IS 'Contrato fecha inicio';
  COMMENT ON COLUMN MELANBIDE91_CONTR_GEN.JORNADA IS 'Jornada';
  COMMENT ON COLUMN MELANBIDE91_CONTR_GEN.PORCPARCIAL IS 'Porcentaje jornada parcial';
  
CREATE SEQUENCE  SEQ_MELANBIDE91_CONTR_GEN MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;



 CREATE TABLE MELANBIDE91_SUBVEN_SOLIC 
  ( ID NUMBER(4,0) NOT NULL ENABLE, 
  NUM_EXP VARCHAR2(20 BYTE) NOT NULL,  
  TIPODATOS VARCHAR2(2 BYTE) NOT NULL, 
  TIPO VARCHAR2(100 BYTE) NOT NULL,
  FECHA DATE,  
  DESTINO VARCHAR2 (150 BYTE) NOT NULL,
  COSTE NUMBER (10,2) NOT NULL,
    CONSTRAINT MELANBIDE91_SUBVEN_SOLIC_PK PRIMARY KEY (ID)
 )
 ;

 COMMENT ON COLUMN MELANBIDE91_SUBVEN_SOLIC.ID IS 'ID';
 COMMENT ON COLUMN MELANBIDE91_SUBVEN_SOLIC.NUM_EXP IS 'Numero expediente';
 COMMENT ON COLUMN MELANBIDE91_SUBVEN_SOLIC.TIPODATOS IS 'Tipo de datos';
 COMMENT ON COLUMN MELANBIDE91_SUBVEN_SOLIC.TIPO IS 'Tipo de la inversion o la asistencia tecnica';
 COMMENT ON COLUMN MELANBIDE91_SUBVEN_SOLIC.FECHA IS 'Fecha adquisicion/fecha';
 COMMENT ON COLUMN MELANBIDE91_SUBVEN_SOLIC.DESTINO IS 'Destino';
 COMMENT ON COLUMN MELANBIDE91_SUBVEN_SOLIC.COSTE IS 'Coste';

CREATE SEQUENCE  SEQ_MELANBIDE91_SUBVEN_SOLIC MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
