/* Generated by Together */
package es.altia.agora.interfaces.user.web.planeamiento.action.mantenimiento;

import es.altia.agora.interfaces.user.web.util.ActionSession;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;


import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

public final class SalirProcedimientoAction extends ActionSession {

    protected static Logger m_Log =
            LogManager.getLogger(SalirProcedimientoAction.class.getName());

    public ActionForward performSession(ActionMapping mapping, ActionForm form, HttpServletRequest request,
                                        HttpServletResponse response) throws IOException, ServletException {

        m_Log.info("SalirProcedimientoAction.perform");
        HttpSession session = request.getSession();

        if (session.getAttribute("MantenimientoProcedimientosForm")!=null) {
            session.removeAttribute("MantenimientoProcedimientosForm");
        }
        return (mapping.findForward("default"));
    }
}