
CREATE SEQUENCE  SEQ_MELANBIDE13_LISTA_EXPEDIENTES  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;

CREATE TABLE "MELANBIDE13_LISTA_EXPEDIENTES" 
   (	"ID" NUMBER(8,0) NOT NULL ENABLE, 
	"NUM_EXP" VARCHAR2(20 BYTE), 
	"MES" DATE(100 BYTE), 
	"IMPORTE" NUMBER(8,3), 
	"IMPORTE_TOTAL" NUMBER(8,3),
	
	 CONSTRAINT "MELANBIDE13_LISTA_EXPEDIENTES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLB_DBS1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLB_DBS1" ;


