----------------------------
--- ECA_JUS_PREPARADORES ---
----------------------------

ALTER TABLE ECA14_JUS_PREPARADORES ADD (ECA_PREP_TIPO_SUST NUMBER(1, 0) );

COMMENT ON COLUMN ECA14_JUS_PREPARADORES.ECA_PREP_TIPO_SUST IS 'Tipo de sustituto (1: Solicitud; 2: Justificación)';

----------------------------
--- ECA_JUS_PROSPECTORES ---
----------------------------

ALTER TABLE ECA14_JUS_PROSPECTORES ADD (ECA_PROS_TIPO_SUST NUMBER(1, 0) );

COMMENT ON COLUMN ECA14_JUS_PROSPECTORES.ECA_PROS_TIPO_SUST IS 'Tipo de sustituto (1: Solicitud; 2: Justificación)';


----------------------------
--- ECA_SOL_PREPARADORES ---
----------------------------

ALTER TABLE ECA14_SOL_PREPARADORES ADD (ECA_PREP_TIPO_SUST NUMBER(1, 0) );

COMMENT ON COLUMN ECA14_SOL_PREPARADORES.ECA_PREP_TIPO_SUST IS 'Tipo de sustituto (1: Solcitud; 2: Justificacion)';

ALTER TABLE ECA14_SOL_PREPARADORES ADD (ECA_PREP_CODORIGEN NUMBER(8, 0) );

COMMENT ON COLUMN ECA14_SOL_PREPARADORES.ECA_PREP_CODORIGEN IS 'Codigo del preparador al que sustituye';


----------------------------
--- ECA_SOL_PROSPECTORES ---
----------------------------

ALTER TABLE ECA14_SOL_PROSPECTORES ADD (ECA_PROS_TIPO_SUST NUMBER(1, 0) );

COMMENT ON COLUMN ECA14_SOL_PROSPECTORES.ECA_PROS_TIPO_SUST IS 'Tipo de sustituto (1: Solcitud; 2: Justificacion)';

ALTER TABLE ECA14_SOL_PROSPECTORES ADD (ECA_PROS_CODORIGEN NUMBER(8, 0) );

COMMENT ON COLUMN ECA14_SOL_PROSPECTORES.ECA_PROS_CODORIGEN IS 'Codigo del prospector al que sustituye';