--ECA14_SOLICITUD
  CREATE TABLE "ECA14_SOLICITUD"
  (
    "ECA_SOLICITUD_COD"    NUMBER(8,0) NOT NULL ENABLE,
    "ECA_NUMEXP"           VARCHAR2(30 BYTE),
    "ECA_INSER_C1_H"       NUMBER(8,0),
    "ECA_INSER_C1_M"       NUMBER(8,0),
    "ECA_INSER_C2_H"       NUMBER(8,0),
    "ECA_INSER_C2_M"       NUMBER(8,0),
    "ECA_INSER_C3_H"       NUMBER(8,0),
    "ECA_INSER_C3_M"       NUMBER(8,0),
    "ECA_INSER_C4_H"       NUMBER(8,0),
    "ECA_INSER_C4_M"       NUMBER(8,0),
    "ECA_SEG_H"            NUMBER(8,0),
    "ECA_SEG_M"            NUMBER(8,0),
    "ECA_SEG_ACTUACIONES"  NUMBER(10,2),
    "ECA_PROSPECTORES_NUM" NUMBER(4,0),
    "ECA_PROSPECTORES_IMP" NUMBER(10,2),
    "ECA_PREPARADORES_NUM" NUMBER(4,0),
    "ECA_PREPARADORES_IMP" NUMBER(10,2),
    "ECA_GASTOS"           NUMBER(10,2),
    "ECA_OTRAS_SUB"        NUMBER(1,0),
    "ECA_SUB_PUB"          NUMBER(10,2),
    "ECA_SUB_PRIV"         NUMBER(10,2),
    "ECA_TOTAL_SUBVENCION" NUMBER(10,2),
    "ECA_TOTAL_APROBADO"   NUMBER(10,2),
    "ECA_EXP_EJE"          NUMBER(4,0),
    CONSTRAINT "ECA14_SOLICITUD_PK" PRIMARY KEY ("ECA_SOLICITUD_COD")
  ) ;
COMMENT ON COLUMN "ECA14_SOLICITUD"."ECA_SOLICITUD_COD"
IS
  'IDENTIFICACION UNIVOCA DEL REGISTRO EN LA TABLA. PK';
  COMMENT ON COLUMN "ECA14_SOLICITUD"."ECA_NUMEXP"
IS
  'NUMERO DE EXPEDIENTE RELACIONADO';
  COMMENT ON COLUMN "ECA14_SOLICITUD"."ECA_INSER_C1_H"
IS
  'NUMERO DE INSERCIONES COLECTIVO 1 HOMBRE';
  COMMENT ON COLUMN "ECA14_SOLICITUD"."ECA_INSER_C1_M"
IS
  'NUMERO DE INSERCIONES COLECTIVO 1 MUJER';
  COMMENT ON COLUMN "ECA14_SOLICITUD"."ECA_INSER_C2_H"
IS
  'NUMERO DE INSERCIONES COLECTIVO 2 HOMBRE';
  COMMENT ON COLUMN "ECA14_SOLICITUD"."ECA_INSER_C2_M"
IS
  'NUMERO DE INSERCIONES COLECTIVO 2 MUJER';
  COMMENT ON COLUMN "ECA14_SOLICITUD"."ECA_INSER_C3_H"
IS
  'NUMERO DE INSERCIONES COLECTIVO 3 HOMBRE';
  COMMENT ON COLUMN "ECA14_SOLICITUD"."ECA_INSER_C3_M"
IS
  'NUMERO DE INSERCIONES COLECTIVO 3 MUJER';
  COMMENT ON COLUMN "ECA14_SOLICITUD"."ECA_INSER_C4_H"
IS
  'NUMERO DE INSERCIONES COLECTIVO 4 HOMBRE';
  COMMENT ON COLUMN "ECA14_SOLICITUD"."ECA_INSER_C4_M"
IS
  'NUMERO DE INSERCIONES COLECTIVO 4 MUJER';
  COMMENT ON COLUMN "ECA14_SOLICITUD"."ECA_SEG_H"
IS
  'NUMERO DE SEGUIMIENTOS A HOMBRES';
  COMMENT ON COLUMN "ECA14_SOLICITUD"."ECA_SEG_M"
IS
  'NUMERO DE SEGUIMIENTOS A MUJERES';
  COMMENT ON COLUMN "ECA14_SOLICITUD"."ECA_SEG_ACTUACIONES"
IS
  'IMPORTE SOLICITADO POR ACTUACIONES DE SEGUIMIENTOS';
  COMMENT ON COLUMN "ECA14_SOLICITUD"."ECA_PROSPECTORES_NUM"
IS
  'NUMERO DE PROSPECTORES SOLICITADOS';
  COMMENT ON COLUMN "ECA14_SOLICITUD"."ECA_PROSPECTORES_IMP"
IS
  'IMPORTE POR PROSPECTORES SOLICITADOS';
  COMMENT ON COLUMN "ECA14_SOLICITUD"."ECA_PREPARADORES_NUM"
IS
  'NUMERO DE PREPARADORES SOLICITADOS';
  COMMENT ON COLUMN "ECA14_SOLICITUD"."ECA_PREPARADORES_IMP"
IS
  'IMPORTE PREPARADORES SOLICITADOS';
  COMMENT ON COLUMN "ECA14_SOLICITUD"."ECA_GASTOS"
IS
  'GASTOS GENERALES DE ADMINISTRACION Y TRASLADOS';
  COMMENT ON COLUMN "ECA14_SOLICITUD"."ECA_OTRAS_SUB"
IS
  'INDICADOR DE SI RECIBE OTRAS SUBVENCIONES DE OTROS ORGANISMOS ';
  COMMENT ON COLUMN "ECA14_SOLICITUD"."ECA_SUB_PUB"
IS
  'IMPORTE SUBVENCION ORGANISMOS PUBLICOS';
  COMMENT ON COLUMN "ECA14_SOLICITUD"."ECA_SUB_PRIV"
IS
  'IMPORTE SUBVENCION ORGANISMOS PRIVADOS';
  COMMENT ON COLUMN "ECA14_SOLICITUD"."ECA_TOTAL_SUBVENCION"
IS
  'IMPORTE TOTAL SOLICITADO';
  COMMENT ON COLUMN "ECA14_SOLICITUD"."ECA_TOTAL_APROBADO"
IS
  'IMPORTE TOTAL APROBADO';
  COMMENT ON TABLE "ECA14_SOLICITUD"
IS
  'TABLA SOLICITUDES PROCEDIMIENTO ECA. MODULO DE EXTENSION';
  

--ECA14_AUDITORIA
CREATE TABLE "ECA14_AUDITORIA"
  (
    "USU_COD" NUMBER(4,0) NOT NULL ENABLE,
    "PROCESO" NUMBER(3,0) NOT NULL ENABLE,
    "FEC_EJECUCION" TIMESTAMP (0) NOT NULL ENABLE,
    "RESULTADO" VARCHAR2(100 BYTE)
  ) ;
COMMENT ON COLUMN "ECA14_AUDITORIA"."USU_COD"
IS
  'ID del usuario que ejecuta el proceso';
  COMMENT ON COLUMN "ECA14_AUDITORIA"."PROCESO"
IS
  'Código de proceso ejecutado';
  COMMENT ON COLUMN "ECA14_AUDITORIA"."FEC_EJECUCION"
IS
  'Fecha y hora de ejecución del proceso';
  COMMENT ON COLUMN "ECA14_AUDITORIA"."RESULTADO"
IS
  'Resultado devuelto por el proceso.';
  
--ECA14_CONFIGURACION  
CREATE TABLE "ECA14_CONFIGURACION"
  (
    "ANO"                 NUMBER(4,0) NOT NULL ENABLE,
    "PO_GASTOS"           NUMBER(4,2),
    "IM_SEGUIMIENTO"      NUMBER(8,2),
    "PO_MAX_SEGUIMIENTOS" NUMBER(4,2),
    "IM_C1_H"             NUMBER(8,2),
    "IM_C1_M"             NUMBER(8,2),
    "IM_C2_H"             NUMBER(8,2),
    "IM_C2_M"             NUMBER(8,2),
    "IM_C3_H"             NUMBER(8,2),
    "IM_C3_M"             NUMBER(8,2),
    "IM_C4_H"             NUMBER(8,2),
    "IM_C4_M"             NUMBER(8,2),
    "MIN_EMP_VISIT"       NUMBER(8,0),
    "MAX_EMP_VISIT"       NUMBER(8,0),
    "IMP_VISITA"          NUMBER(8,2),
    CONSTRAINT "ECA14_CONFIGURACION_PK" PRIMARY KEY ("ANO")
  );
COMMENT ON COLUMN "ECA14_CONFIGURACION"."MIN_EMP_VISIT"
IS
  'Mínimo de empresas a visitar (prospectores)';
  COMMENT ON COLUMN "ECA14_CONFIGURACION"."MAX_EMP_VISIT"
IS
  'Máximo de empresas a visitar (prospectores)';
  COMMENT ON COLUMN "ECA14_CONFIGURACION"."IMP_VISITA"
IS
  'Importe de cada visita a empresas (prospectores)';
  
  --ECA14_CUMPLELISMI
  CREATE TABLE "ECA14_CUMPLELISMI"
  (
    "COD_CUMPLE" NUMBER(2,0) NOT NULL ENABLE,
    "NOMBRE_C"   VARCHAR2(200 BYTE),
    "NOMBRE_E"   VARCHAR2(200 BYTE),
    CONSTRAINT "ECA14_CUMPLE_PK" PRIMARY KEY ("COD_CUMPLE") 
  ) ;
COMMENT ON COLUMN "ECA14_CUMPLELISMI"."COD_CUMPLE"
IS
  'CÓDIGO DE CUMPLELISMI';
  COMMENT ON COLUMN "ECA14_CUMPLELISMI"."NOMBRE_C"
IS
  'NOMBRE CUMPLELISMI CASTELLANO';
  COMMENT ON COLUMN "ECA14_CUMPLELISMI"."NOMBRE_E"
IS
  'NOMBRE CUMPLELISMI EUSKERA';
  COMMENT ON TABLE "ECA14_CUMPLELISMI" IS 'CUMPLE LISMI';
  
  
  --ECA14_DISCAPGRAVEDAD
  CREATE TABLE "ECA14_DISCAPGRAVEDAD"
  (
    "COD_GRAVEDAD" NUMBER(1,0) NOT NULL ENABLE,
    "NOMBRE_C"     VARCHAR2(100 BYTE),
    "NOMBRE_E"     VARCHAR2(100 BYTE),
    CONSTRAINT "ECA14_DISCAPGRAVEDAD_PK" PRIMARY KEY ("COD_GRAVEDAD")
  );
  
  
  --ECA14_JUS_PREPARADORES
  CREATE TABLE "ECA14_JUS_PREPARADORES"
  (
    "ECA_JUS_PREPARADORES_COD" NUMBER(8,0) NOT NULL ENABLE,
    "ECA_SOL_PREPARADORES_COD" NUMBER(8,0),
    "ECA_PREP_NIF"             VARCHAR2(10 BYTE),
    "ECA_PREP_NOMBRE"          VARCHAR2(200 BYTE),
    "ECA_PREP_FECINI" DATE,
    "ECA_PREP_FECFIN" DATE,
    "ECA_PREP_HORAS_JC"     NUMBER(8,2),
    "ECA_PREP_HORAS_CONT"   NUMBER(8,2),
    "ECA_PREP_HORAS_ECA"    NUMBER(8,2),
    "ECA_PREP_IMP_SS_JC"    NUMBER(8,2),
    "ECA_PREP_IMP_SS_JR"    NUMBER(8,2),
    "ECA_PREP_IMP_SS_ECA"   NUMBER(8,2),
    "ECA_PREP_SOLICITUD"    NUMBER(8,0),
    "ECA_PREP_TIPOCONTRATO" NUMBER(2,0),
    "ECA_PREP_TIPO_SUST"    NUMBER(1,0),
    "ECA_PREP_CODORIGEN"    NUMBER(8,0),
    CONSTRAINT "ECA14_JUS_PREPARADORES_PK" PRIMARY KEY ("ECA_JUS_PREPARADORES_COD"),
    CONSTRAINT "ECA14_JUS_PREPARADORES__FK1" FOREIGN KEY ("ECA_PREP_SOLICITUD") REFERENCES "ECA14_SOLICITUD" ("ECA_SOLICITUD_COD") ENABLE
  );
COMMENT ON COLUMN "ECA14_JUS_PREPARADORES"."ECA_JUS_PREPARADORES_COD"
IS
  'IDENTIFICACION UNIVOCA DEL REGISTRO EN LA TABLA. PK';
  COMMENT ON COLUMN "ECA14_JUS_PREPARADORES"."ECA_PREP_NIF"
IS
  'NIF DEL PREPARADOR';
  COMMENT ON COLUMN "ECA14_JUS_PREPARADORES"."ECA_PREP_NOMBRE"
IS
  'NOMBRE DEL PREPARADOR';
  COMMENT ON COLUMN "ECA14_JUS_PREPARADORES"."ECA_PREP_FECINI"
IS
  'FECHA DE INICIO DEL CONTRATO DEL PREPARADOR';
  COMMENT ON COLUMN "ECA14_JUS_PREPARADORES"."ECA_PREP_FECFIN"
IS
  'FECHA DE FIN DEL CONTRATO DEL PREPARADOR';
  COMMENT ON COLUMN "ECA14_JUS_PREPARADORES"."ECA_PREP_HORAS_JC"
IS
  'HORAS DEL CONTRATO A JORNADA COMPLETA';
  COMMENT ON COLUMN "ECA14_JUS_PREPARADORES"."ECA_PREP_HORAS_CONT"
IS
  'HORAS DEL CONTRATO REALES';
  COMMENT ON COLUMN "ECA14_JUS_PREPARADORES"."ECA_PREP_HORAS_ECA"
IS
  'HORAS DEDICADAS AL ECA';
  COMMENT ON COLUMN "ECA14_JUS_PREPARADORES"."ECA_PREP_IMP_SS_JC"
IS
  'IMPORTE DE LOS GASTOS DE SS A JORNADA COMPLETA';
  COMMENT ON COLUMN "ECA14_JUS_PREPARADORES"."ECA_PREP_IMP_SS_JR"
IS
  'IMPORTE DE LOS GASTOS DE SS A JORNADA REAL';
  COMMENT ON COLUMN "ECA14_JUS_PREPARADORES"."ECA_PREP_IMP_SS_ECA"
IS
  'IMPORTE DE LOS GASTOS DE SS IMPUTABLES ECA';
  COMMENT ON COLUMN "ECA14_JUS_PREPARADORES"."ECA_PREP_SOLICITUD"
IS
  'CLAVE FORANEA DE LA SOLICITUD';
  COMMENT ON COLUMN "ECA14_JUS_PREPARADORES"."ECA_PREP_TIPO_SUST"
IS
  'Tipo de sustituto (1: Solicitud; 2: Justificación)';
  COMMENT ON COLUMN "ECA14_JUS_PREPARADORES"."ECA_PREP_CODORIGEN"
IS
  'PREPARADOR ORIGEN';
  COMMENT ON TABLE "ECA14_JUS_PREPARADORES"
IS
  'TABLE DE PREPARADORES JUSTIFICADOS DEL MODULO DE EXTENSION 35 ';
  
--ECA14_JUS_PROSPECTORES
CREATE TABLE "ECA14_JUS_PROSPECTORES"
  (
    "ECA_JUS_PROSPECTORES_COD" NUMBER(8,0) NOT NULL ENABLE,
    "ECA_SOL_PROSPECTORES_COD" NUMBER(8,0),
    "ECA_PROS_NIF"             VARCHAR2(10 BYTE),
    "ECA_PROS_NOMBRE"          VARCHAR2(200 BYTE),
    "ECA_PROS_FECINI" DATE,
    "ECA_PROS_FECFIN" DATE,
    "ECA_PROS_HORAS_JC"     NUMBER(8,2),
    "ECA_PROS_HORAS_CONT"   NUMBER(8,2),
    "ECA_PROS_HORAS_ECA"    NUMBER(8,2),
    "ECA_PROS_IMP_SS_JC"    NUMBER(8,2),
    "ECA_PROS_IMP_SS_JR"    NUMBER(8,2),
    "ECA_PROS_IMP_SS_ECA"   NUMBER(8,2),
    "ECA_PROS_SOLICITUD"    NUMBER(8,0),
    "ECA_PROS_TIPOCONTRATO" NUMBER(2,0),
    "ECA_PROS_TIPO_SUST"    NUMBER(1,0),
    "ECA_PROS_CODORIGEN"    NUMBER(8,0),
    CONSTRAINT "ECA14_JUS_PROSPECTORES_PK" PRIMARY KEY ("ECA_JUS_PROSPECTORES_COD"),
    CONSTRAINT "ECA14_JUS_PROSPECTORES__FK1" FOREIGN KEY ("ECA_PROS_SOLICITUD") REFERENCES "ECA14_SOLICITUD" ("ECA_SOLICITUD_COD") ENABLE
  ) ;
COMMENT ON COLUMN "ECA14_JUS_PROSPECTORES"."ECA_JUS_PROSPECTORES_COD"
IS
  'IDENTIFICACION UNIVOCA DEL REGISTRO EN LA TABLA. PK';
  COMMENT ON COLUMN "ECA14_JUS_PROSPECTORES"."ECA_SOL_PROSPECTORES_COD"
IS
  'RELACION CON PROSPECTOR DE SOLICITUD';
  COMMENT ON COLUMN "ECA14_JUS_PROSPECTORES"."ECA_PROS_NIF"
IS
  'NIF DEL PROSPECTOR';
  COMMENT ON COLUMN "ECA14_JUS_PROSPECTORES"."ECA_PROS_NOMBRE"
IS
  'NOMBRE DEL PROSPECTOR';
  COMMENT ON COLUMN "ECA14_JUS_PROSPECTORES"."ECA_PROS_FECINI"
IS
  'FECHA DE INICIO DEL CONTRATO DEL PROSPECTOR';
  COMMENT ON COLUMN "ECA14_JUS_PROSPECTORES"."ECA_PROS_FECFIN"
IS
  'FECHA DE FIN DEL CONTRATO DEL PROSPECTOR';
  COMMENT ON COLUMN "ECA14_JUS_PROSPECTORES"."ECA_PROS_HORAS_JC"
IS
  'HORAS DEL CONTRATO A JORNADA COMPLETA';
  COMMENT ON COLUMN "ECA14_JUS_PROSPECTORES"."ECA_PROS_HORAS_CONT"
IS
  'HORAS DEL CONTRATO REALES';
  COMMENT ON COLUMN "ECA14_JUS_PROSPECTORES"."ECA_PROS_HORAS_ECA"
IS
  'HORAS DEDICADAS AL ECA';
  COMMENT ON COLUMN "ECA14_JUS_PROSPECTORES"."ECA_PROS_IMP_SS_JC"
IS
  'IMPORTE DE LOS GASTOS DE SS A JORNADA COMPLETA';
  COMMENT ON COLUMN "ECA14_JUS_PROSPECTORES"."ECA_PROS_IMP_SS_JR"
IS
  'IMPORTE DE LOS GASTOS DE SS A JORNADA REAL';
  COMMENT ON COLUMN "ECA14_JUS_PROSPECTORES"."ECA_PROS_IMP_SS_ECA"
IS
  'IMPORTE DE LOS GASTOS DE SS IMPUTABLES ECA';
  COMMENT ON COLUMN "ECA14_JUS_PROSPECTORES"."ECA_PROS_SOLICITUD"
IS
  'CLAVE FORANEA DE LA SOLICITUD';
  COMMENT ON COLUMN "ECA14_JUS_PROSPECTORES"."ECA_PROS_TIPOCONTRATO"
IS
  'TIPO DE CONTRATO DEL PROSPECTOR';
  COMMENT ON COLUMN "ECA14_JUS_PROSPECTORES"."ECA_PROS_TIPO_SUST"
IS
  'Tipo de sustituto (1: Solicitud; 2: Justificación)';
  COMMENT ON COLUMN "ECA14_JUS_PROSPECTORES"."ECA_PROS_CODORIGEN"
IS
  'PROSPECTOR ORIGEN';
  COMMENT ON TABLE "ECA14_JUS_PROSPECTORES"
IS
  'TABLE DE PROSPECTORES JUSTIFICADOS DEL MODULO DE EXTENSION 35 ';
  
  --ECA14_RES_PREPARADORES
  CREATE TABLE "ECA14_RES_PREPARADORES"
  (
    "ECA_RES_PREPARADORES_COD"       NUMBER,
    "ECA_NUMEXP"                     VARCHAR2(30 BYTE),
    "ECA_JUS_PREPARADORES_COD"       NUMBER,
    "NIF"                            VARCHAR2(10 BYTE),
    "NOMBRE"                         VARCHAR2(200 BYTE),
    "GASTOS_SALARIALES_SOLICITADOS"  NUMBER(8,2),
    "GASTOS_SALARIALES_CONCEDIDOS"   NUMBER(8,2),
    "GASTOS_SALARIALES_JUSTIFICADOS" NUMBER(8,2),
    "IMPORTE_SEGUIMIENTOS"           NUMBER(8,2),
    "IMPORTE_INS_CONCEDIDO"          NUMBER(8,2),
    "IMPORTE_INS_JUSTIFICADAS"       NUMBER(8,2),
    "IMPORTE_INSERCIONES"            NUMBER(8,2),
    "IMPORTE_SEG_INSERCIONES"        NUMBER(8,2),
    "A_PAGAR"                        NUMBER(8,2),
    "FEC_SYSDATE" DATE
  );
  
  --ECA14_RES_PROSPECTORES
  CREATE TABLE "ECA14_RES_PROSPECTORES"
  (
    "ECA_RES_PROSPECTORES_COD"       NUMBER,
    "ECA_NUMEXP"                     VARCHAR2(30 BYTE),
    "ECA_JUS_PROSPECTORES_COD"       NUMBER,
    "NIF"                            VARCHAR2(10 BYTE),
    "NOMBRE"                         VARCHAR2(200 BYTE),
    "GASTOS_SALARIALES_SOLICITADOS"  NUMBER(8,2),
    "GASTOS_SALARIALES_CONCEDIDOS"   NUMBER(8,2),
    "GASTOS_SALARIALES_JUSTIFICADOS" NUMBER(8,2),
    "VISITAS_CONCEDIDAS"             NUMBER,
    "VISITAS_JUSTIFICADAS"           NUMBER,
    "IMPORTE_VISITAS"                NUMBER(8,2),
    "A_PAGAR"                        NUMBER(8,2),
    "FEC_SYSDATE" DATE
  );
  
  --ECA14_RESULTADO
  CREATE TABLE "ECA14_RESULTADO"
  (
    "COD_RESULTADO" NUMBER(2,0) NOT NULL ENABLE,
    "NOMBRE_C"      VARCHAR2(200 BYTE),
    "NOMBRE_E"      VARCHAR2(200 BYTE),
    CONSTRAINT "ECA14_RESULTADO_PK" PRIMARY KEY ("COD_RESULTADO")
  );
COMMENT ON COLUMN "ECA14_RESULTADO"."COD_RESULTADO"
IS
  'CÓDIGO DE RESULTADO';
  COMMENT ON COLUMN "ECA14_RESULTADO"."NOMBRE_C"
IS
  'DESCRIPCIÓN RESULTADO CASTELLANO';
  COMMENT ON COLUMN "ECA14_RESULTADO"."NOMBRE_E"
IS
  'DESCRIPCIÓN RESULTADO EUSKERA';
  COMMENT ON TABLE "ECA14_RESULTADO"
IS
  'RESULTADO FINAL VISITA';
  
  --ECA14_RESUMEN
  CREATE TABLE "ECA14_RESUMEN"
  (
    "ECA_COD_RESUMEN"   NUMBER(8,0) NOT NULL ENABLE,
    "ECA_RES_SOLICITUD" NUMBER(8,0),
    "ECA_RES_SUB_PRIV"  NUMBER(10,2),
    "ECA_RES_SUB_PUB"   NUMBER(10,2),
    "ECA_RES_TOT_SUBV"  NUMBER(10,2),
    CONSTRAINT "ECA14_RESUMEN_PK" PRIMARY KEY ("ECA_COD_RESUMEN")
  );
  
  --ECA14_SECTORACT
  CREATE TABLE "ECA14_SECTORACT"
  (
    "COD_SECTOR" NUMBER(2,0) NOT NULL ENABLE,
    "NOMBRE_C"   VARCHAR2(200 BYTE),
    "NOMBRE_E"   VARCHAR2(200 BYTE),
    CONSTRAINT "ECA14_SECTORACT_PK" PRIMARY KEY ("COD_SECTOR") 
  ) ;
COMMENT ON COLUMN "ECA14_SECTORACT"."COD_SECTOR"
IS
  'CÓDIGO DE SECTOR';
  COMMENT ON COLUMN "ECA14_SECTORACT"."NOMBRE_C"
IS
  'NOMBRE SECTOR CASTELLANO';
  COMMENT ON COLUMN "ECA14_SECTORACT"."NOMBRE_E"
IS
  'NOMBRE SECTOR EUSKERA';
  COMMENT ON TABLE "ECA14_SECTORACT"
IS
  'SECTOR DE ACTIVIDAD';
  
  --ECA14_SEG_PREPARADORES
  CREATE TABLE "ECA14_SEG_PREPARADORES"
  (
    "ECA_SEG_PREPARADORES_COD" NUMBER(8,0) NOT NULL ENABLE,
    "ECA_JUS_PREPARADORES_COD" NUMBER(8,0) NOT NULL ENABLE,
    "ECA_SEG_TIPO"             NUMBER(1,0),
    "ECA_SEG_NIF"              VARCHAR2(10 BYTE),
    "ECA_SEG_NOMBRE"           VARCHAR2(200 BYTE),
    "ECA_SEG_FECNACIMIENTO" DATE,
    "ECA_SEG_SEXO"             NUMBER(1,0),
    "ECA_SEG_TIPODISCAPACIDAD" NUMBER(1,0),
    "ECA_SEG_DISCGRAVEDAD"     NUMBER(1,0),
    "ECA_SEG_TIPOCONTRATO"     NUMBER(2,0),
    "ECA_SEG_PORCJORNADA"      NUMBER(5,2),
    "ECA_SEG_FECINI" DATE,
    "ECA_SEG_FECFIN" DATE,
    "ECA_SEG_EMPRESA" VARCHAR2(100 BYTE),
    "ECA_SEG_HORAS"   NUMBER(8,2),
    "ECA_SEG_FECSEGUIMIENTO" DATE,
    "ECA_SEG_PERSCONTACTO"  VARCHAR2(100 BYTE),
    "ECA_SEG_OBSERVACIONES" VARCHAR2(200 BYTE),
    "ECA_SEG_CORRECTO"      VARCHAR2(1 BYTE),
    CONSTRAINT "ECA14_ECA_SEG_PREPARADORES_PK" PRIMARY KEY ("ECA_JUS_PREPARADORES_COD", "ECA_SEG_PREPARADORES_COD") ,
    CONSTRAINT "ECA14_SEG_PREPARADORES__FK1" FOREIGN KEY ("ECA_JUS_PREPARADORES_COD") REFERENCES "ECA14_JUS_PREPARADORES" ("ECA_JUS_PREPARADORES_COD") 
  );
COMMENT ON COLUMN "ECA14_SEG_PREPARADORES"."ECA_SEG_PREPARADORES_COD"
IS
  'Código Seguimientos / Inserciones';
  COMMENT ON COLUMN "ECA14_SEG_PREPARADORES"."ECA_JUS_PREPARADORES_COD"
IS
  'Código de preparador';
  COMMENT ON COLUMN "ECA14_SEG_PREPARADORES"."ECA_SEG_TIPO"
IS
  'Tipo: 0 - Seguimiento, 1- Inserción';
  COMMENT ON COLUMN "ECA14_SEG_PREPARADORES"."ECA_SEG_NIF"
IS
  'NIF  persona seguimiento/inserción';
  COMMENT ON COLUMN "ECA14_SEG_PREPARADORES"."ECA_SEG_NOMBRE"
IS
  'Nombre  persona seguimiento/inserción';
  COMMENT ON COLUMN "ECA14_SEG_PREPARADORES"."ECA_SEG_FECNACIMIENTO"
IS
  'Fecha nacimiento  persona seguimiento/inserción';
  COMMENT ON COLUMN "ECA14_SEG_PREPARADORES"."ECA_SEG_SEXO"
IS
  'Sexo  persona seguimiento/inserción: 0-Hombre, 1-Mujer';
  COMMENT ON COLUMN "ECA14_SEG_PREPARADORES"."ECA_SEG_TIPODISCAPACIDAD"
IS
  'Tipo discapacidad  persona seguimiento/inserción';
  COMMENT ON COLUMN "ECA14_SEG_PREPARADORES"."ECA_SEG_DISCGRAVEDAD"
IS
  'Gravedad discapacidad de la  persona del seguimiento/inserción';
  COMMENT ON COLUMN "ECA14_SEG_PREPARADORES"."ECA_SEG_TIPOCONTRATO"
IS
  'Tipo de contrato de la  persona del seguimiento/inserción';
  COMMENT ON COLUMN "ECA14_SEG_PREPARADORES"."ECA_SEG_PORCJORNADA"
IS
  'Porcentaje de jornada de  persona seguimiento/inserción';
  COMMENT ON COLUMN "ECA14_SEG_PREPARADORES"."ECA_SEG_FECINI"
IS
  'Fecha de inicio';
  COMMENT ON COLUMN "ECA14_SEG_PREPARADORES"."ECA_SEG_FECFIN"
IS
  'Fecha de fin';
  COMMENT ON COLUMN "ECA14_SEG_PREPARADORES"."ECA_SEG_EMPRESA"
IS
  'Empresa  persona seguimiento/inserción';
  COMMENT ON COLUMN "ECA14_SEG_PREPARADORES"."ECA_SEG_HORAS"
IS
  'Horas';
  COMMENT ON COLUMN "ECA14_SEG_PREPARADORES"."ECA_SEG_CORRECTO"
IS
  'Correcto (S/N)';
  COMMENT ON TABLE "ECA14_SEG_PREPARADORES"
IS
  'Seguimientos / Inserciones de preparadores';
  
  --ECA14_SOL_PREPARADORES
  
  CREATE TABLE "ECA14_SOL_PREPARADORES"
  (
    "ECA_SOL_PREPARADORES_COD" NUMBER(8,0) NOT NULL ENABLE,
    "ECA_PREP_NIF"             VARCHAR2(10 BYTE),
    "ECA_PREP_NOMBRE"          VARCHAR2(200 BYTE),
    "ECA_PREP_FECINI" DATE,
    "ECA_PREP_FECFIN" DATE,
    "ECA_PREP_HORAS_JC"        NUMBER(8,2),
    "ECA_PREP_HORAS_CONT"      NUMBER(8,2),
    "ECA_PREP_HORAS_ECA"       NUMBER(8,2),
    "ECA_PREP_IMP_SS_JC"       NUMBER(8,2),
    "ECA_PREP_IMP_SS_JR"       NUMBER(8,2),
    "ECA_PREP_IMP_SS_ECA"      NUMBER(8,2),
    "ECA_PREP_SEG_ANT"         NUMBER(8,0),
    "ECA_PREP_IMP_SEG_ANT"     NUMBER(8,2),
    "ECA_PREP_INS_C1_H"        NUMBER(8,2),
    "ECA_PREP_INS_C1_M"        NUMBER(8,2),
    "ECA_PREP_INS_C1"          NUMBER(8,2),
    "ECA_PREP_INS_C2_H"        NUMBER(8,2),
    "ECA_PREP_INS_C2_M"        NUMBER(8,2),
    "ECA_PREP_INS_C2"          NUMBER(8,2),
    "ECA_PREP_INS_C3_H"        NUMBER(8,2),
    "ECA_PREP_INS_C3_M"        NUMBER(8,2),
    "ECA_PREP_INS_C3"          NUMBER(8,2),
    "ECA_PREP_INS_C4_H"        NUMBER(8,2),
    "ECA_PREP_INS_C4_M"        NUMBER(8,2),
    "ECA_PREP_INS_C4"          NUMBER(8,2),
    "ECA_PREP_INS_IMPORTE"     NUMBER(8,2),
    "ECA_PREP_INS_SEG_IMPORTE" NUMBER(8,2),
    "ECA_PREP_COSTE"           NUMBER(8,2),
    "ECA_PREP_SOLICITUD"       NUMBER(8,0),
    "ECA_PREP_TIPO_SUST"       NUMBER(1,0),
    "ECA_PREP_CODORIGEN"       NUMBER(8,0),
    "ECA_PREP_NIF_CARGA"       VARCHAR2(10 BYTE),
    "ECA_PREP_NOMBRE_CARGA"    VARCHAR2(200 BYTE),
    "ECA_PREP_FECINI_CARGA" DATE,
    "ECA_PREP_FECFIN_CARGA" DATE,
    "ECA_PREP_HORAS_JC_CARGA"        NUMBER(8,2),
    "ECA_PREP_HORAS_CONT_CARGA"      NUMBER(8,2),
    "ECA_PREP_HORAS_ECA_CARGA"       NUMBER(8,2),
    "ECA_PREP_IMP_SS_JC_CARGA"       NUMBER(8,2),
    "ECA_PREP_IMP_SS_JR_CARGA"       NUMBER(8,2),
    "ECA_PREP_IMP_SS_ECA_CARGA"      NUMBER(8,2),
    "ECA_PREP_SEG_ANT_CARGA"         NUMBER(8,0),
    "ECA_PREP_IMP_SEG_ANT_CARGA"     NUMBER(8,2),
    "ECA_PREP_INS_C1_H_CARGA"        NUMBER(8,2),
    "ECA_PREP_INS_C1_M_CARGA"        NUMBER(8,2),
    "ECA_PREP_INS_C1_CARGA"          NUMBER(8,2),
    "ECA_PREP_INS_C2_H_CARGA"        NUMBER(8,2),
    "ECA_PREP_INS_C2_M_CARGA"        NUMBER(8,2),
    "ECA_PREP_INS_C2_CARGA"          NUMBER(8,2),
    "ECA_PREP_INS_C3_H_CARGA"        NUMBER(8,2),
    "ECA_PREP_INS_C3_M_CARGA"        NUMBER(8,2),
    "ECA_PREP_INS_C3_CARGA"          NUMBER(8,2),
    "ECA_PREP_INS_C4_H_CARGA"        NUMBER(8,2),
    "ECA_PREP_INS_C4_M_CARGA"        NUMBER(8,2),
    "ECA_PREP_INS_C4_CARGA"          NUMBER(8,2),
    "ECA_PREP_INS_IMPORTE_CARGA"     NUMBER(8,2),
    "ECA_PREP_INS_SEG_IMPORTE_CARGA" NUMBER(8,2),
    "ECA_PREP_COSTE_CARGA"           NUMBER(8,2),
    CONSTRAINT "ECA14_SOL_PREPARADORES_PK" PRIMARY KEY ("ECA_SOL_PREPARADORES_COD"),
    CONSTRAINT "ECA14_SOL_PREPARADORES_FK1" FOREIGN KEY ("ECA_PREP_SOLICITUD") REFERENCES "ECA14_SOLICITUD" ("ECA_SOLICITUD_COD") ENABLE
  );
COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_SOL_PREPARADORES_COD"
IS
  'IDENTIFICACION UNIVOCA DEL REGISTRO EN LA TABLA. PK';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_NIF"
IS
  'NIF DEL PREPARADOR';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_NOMBRE"
IS
  'NOMBRE DEL PREPARADOR';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_FECINI"
IS
  'FECHA DE INICIO DEL CONTRATO DEL PREPARADOR';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_FECFIN"
IS
  'FECHA DE FIN DEL CONTRATO DEL PREPARADOR';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_HORAS_JC"
IS
  'HORAS DEL CONTRATO A JORNADA COMPLETA';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_HORAS_CONT"
IS
  'HORAS DEL CONTRATO REALES';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_HORAS_ECA"
IS
  'HORAS DEDICADAS AL ECA';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_IMP_SS_JC"
IS
  'IMPORTE DE LOS GASTOS DE SS A JORNADA COMPLETA';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_IMP_SS_JR"
IS
  'IMPORTE DE LOS GASTOS DE SS A JORNADA REAL';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_IMP_SS_ECA"
IS
  'IMPORTE DE LOS GASTOS DE SS IMPUTABLES ECA';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_SEG_ANT"
IS
  'NUMERO DE SEGUIMIENTOS ANTERIORES';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_IMP_SEG_ANT"
IS
  'IMPORTE POR SEGUIMIENTOS ANTERIORES';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_INS_C1_H"
IS
  'INSERCIONES DEL COLECTIVO 1 HOMBRES';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_INS_C1_M"
IS
  'INSERCIONES DEL COLECTIVO 1 MUJERES';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_INS_C1"
IS
  'INSERCIONES DEL COLECTIVO 1';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_INS_C2_H"
IS
  'INSERCIONES DEL COLECTIVO 2 HOMBRES';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_INS_C2_M"
IS
  'INSERCIONES DEL COLECTIVO 2 MUJERES';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_INS_C2"
IS
  'INSERCIONES DEL COLECTIVO 2';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_INS_C3_H"
IS
  'INSERCIONES DEL COLECTIVO 3 HOMBRES';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_INS_C3_M"
IS
  'INSERCIONES DEL COLECTIVO 3 MUJERES';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_INS_C3"
IS
  'INSERCIONES DEL COLECTIVO 3';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_INS_C4_H"
IS
  'INSERCIONES DEL COLECTIVO 4 HOMBRES';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_INS_C4_M"
IS
  'INSERCIONES DEL COLECTIVO 4 MUJERES';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_INS_C4"
IS
  'INSERCIONES DEL COLECTIVO 4';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_INS_IMPORTE"
IS
  'IMPORTE POR INSERCIONES';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_INS_SEG_IMPORTE"
IS
  'IMPORTE POR INSERCIONES Y SEGUIMIENTOS';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_COSTE"
IS
  'COSTES DEL PREPARADOR POR SS+SALARIO';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_SOLICITUD"
IS
  'CLAVE FORANEA DE LA SOLICITUD';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_TIPO_SUST"
IS
  'Tipo de sustituto (1: Solcitud; 2: Justificacion)';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_CODORIGEN"
IS
  'Codigo del preparador al que sustituye';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_NIF_CARGA"
IS
  'PREPARADOR NIF EN CARGA INICIAL';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_NOMBRE_CARGA"
IS
  'NOMBRE DEL PREPARADOR EN CARGA INICIAL';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_FECINI_CARGA"
IS
  'FECHA DE INICIO DEL CONTRATO DEL PREPARADOR EN CARGA INICIAL';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_FECFIN_CARGA"
IS
  'FECHA DE FIN DEL CONTRATO DEL PREPARADOR EN CARGA INICIAL';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_HORAS_JC_CARGA"
IS
  'HORAS DEL CONTRATO A JORNADA COMPLETA EN CARGA INICIAL';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_HORAS_ECA_CARGA"
IS
  'HORAS DEDICADAS AL ECA EN CARGA INICIAL';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_IMP_SS_JC_CARGA"
IS
  'IMPORTE DE LOS GASTOS DE SS A JORNADA COMPLETA EN CARGA INICIAL';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_IMP_SS_JR_CARGA"
IS
  'IMPORTE DE LOS GASTOS DE SS A JORNADA REAL EN CARGA INICIAL';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_IMP_SS_ECA_CARGA"
IS
  'IMPORTE DE LOS GASTOS DE SS IMPUTABLES ECA EN CARGA INICIAL';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_SEG_ANT_CARGA"
IS
  'NUMERO DE SEGUIMIENTOS ANTERIORES EN CARGA INICIAL';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_IMP_SEG_ANT_CARGA"
IS
  'IMPORTE POR SEGUIMIENTOS ANTERIORES EN CARGA INICIAL';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_INS_C1_H_CARGA"
IS
  'INSERCIONES DEL COLECTIVO 1 HOMBRES EN CARGA INICIAL';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_INS_C1_M_CARGA"
IS
  'INSERCIONES DEL COLECTIVO 1 MUJERES EN CARGA INICIAL';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_INS_C1_CARGA"
IS
  'INSERCIONES DEL COLECTIVO 1 EN CARGA INICIAL';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_INS_C2_H_CARGA"
IS
  'INSERCIONES DEL COLECTIVO 2 HOMBRES EN CARGA INICIAL';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_INS_C2_M_CARGA"
IS
  'INSERCIONES DEL COLECTIVO 2 MUJERES EN CARGA INICIAL';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_INS_C2_CARGA"
IS
  'INSERCIONES DEL COLECTIVO 2 EN CARGA INICIAL';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_INS_C3_H_CARGA"
IS
  'INSERCIONES DEL COLECTIVO 3 HOMBRES EN CARGA INICIAL';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_INS_C3_M_CARGA"
IS
  'INSERCIONES DEL COLECTIVO 3 MUJERES EN CARGA INICIAL';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_INS_C3_CARGA"
IS
  'INSERCIONES DEL COLECTIVO 3 EN CARGA INICIAL';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_INS_C4_H_CARGA"
IS
  'INSERCIONES DEL COLECTIVO 4 HOMBRES EN CARGA INICIAL';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_INS_C4_M_CARGA"
IS
  'INSERCIONES DEL COLECTIVO 4 MUJERES EN CARGA INICIAL';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_INS_C4_CARGA"
IS
  'INSERCIONES DEL COLECTIVO 4 EN CARGA INICIAL';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_INS_IMPORTE_CARGA"
IS
  'IMPORTE POR INSERCIONES EN CARGA INICIAL';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_INS_SEG_IMPORTE_CARGA"
IS
  'IMPORTE POR INSERCIONES Y SEGUIMIENTOS EN CARGA INICIAL';
  COMMENT ON COLUMN "ECA14_SOL_PREPARADORES"."ECA_PREP_COSTE_CARGA"
IS
  'COSTES DEL PREPARADOR POR SS+SALARIO EN CARGA INICIAL';
  COMMENT ON TABLE "ECA14_SOL_PREPARADORES"
IS
  'TABLE DE PREPARADORES DEL MODULO DE EXTENSION 35 ';
  
  
  --ECA14_SOL_PROSPECTORES
  CREATE TABLE "ECA14_SOL_PROSPECTORES"
  (
    "ECA_SOL_PROSPECTORES_COD" NUMBER(8,0) NOT NULL ENABLE,
    "ECA_PROS_NIF"             VARCHAR2(10 BYTE),
    "ECA_PROS_NOMBRE"          VARCHAR2(100 BYTE),
    "ECA_PROS_FECINI" DATE,
    "ECA_PROS_FECFIN" DATE,
    "ECA_PROS_HORAS_JC"     NUMBER(8,2),
    "ECA_PROS_HORAS_CONT"   NUMBER(8,2),
    "ECA_PROS_HORAS_ECA"    NUMBER(8,2),
    "ECA_PROS_IMP_SS_JC"    NUMBER(8,2),
    "ECA_PROS_IMP_SS_JR"    NUMBER(8,2),
    "ECA_PROS_IMP_SS_ECA"   NUMBER(8,2),
    "ECA_PROS_VISITAS"      NUMBER(8,0),
    "ECA_PROS_VISITAS_IMP"  NUMBER(8,2),
    "ECA_PROS_COSTE"        NUMBER(8,2),
    "ECA_PROS_SOLICITUD"    NUMBER(8,0),
    "ECA_PROS_TIPO_SUST"    NUMBER(1,0),
    "ECA_PROS_CODORIGEN"    NUMBER(8,0),
    "ECA_PROS_NIF_CARGA"    VARCHAR2(10 BYTE),
    "ECA_PROS_NOMBRE_CARGA" VARCHAR2(100 BYTE),
    "ECA_PROS_FECINI_CARGA" DATE,
    "ECA_PROS_FECFIN_CARGA" DATE,
    "ECA_PROS_HORAS_JC_CARGA"    NUMBER(8,2),
    "ECA_PROS_HORAS_CONT_CARGA"  NUMBER(8,2),
    "ECA_PROS_HORAS_ECA_CARGA"   NUMBER(8,2),
    "ECA_PROS_IMP_SS_JC_CARGA"   NUMBER(8,2),
    "ECA_PROS_IMP_SS_JR_CARGA"   NUMBER(8,2),
    "ECA_PROS_IMP_SS_ECA_CARGA"  NUMBER(8,2),
    "ECA_PROS_VISITAS_CARGA"     NUMBER(8,0),
    "ECA_PROS_VISITAS_IMP_CARGA" NUMBER(8,2),
    "ECA_PROS_COSTE_CARGA"       NUMBER(8,2),
    CONSTRAINT "ECA14_SOL_PROSPECTORES_PK" PRIMARY KEY ("ECA_SOL_PROSPECTORES_COD") ,
    CONSTRAINT "ECA14_SOL_PROSPECTORES_FK1" FOREIGN KEY ("ECA_PROS_SOLICITUD") REFERENCES "ECA14_SOLICITUD" ("ECA_SOLICITUD_COD") ENABLE
  );
COMMENT ON COLUMN "ECA14_SOL_PROSPECTORES"."ECA_SOL_PROSPECTORES_COD"
IS
  'IDENTIFICACION UNIVOCA DEL REGISTRO EN LA TABLA. PK';
  COMMENT ON COLUMN "ECA14_SOL_PROSPECTORES"."ECA_PROS_NIF"
IS
  'NIF DEL PREPARADOR';
  COMMENT ON COLUMN "ECA14_SOL_PROSPECTORES"."ECA_PROS_NOMBRE"
IS
  'NOMBRE DEL PREPARADOR';
  COMMENT ON COLUMN "ECA14_SOL_PROSPECTORES"."ECA_PROS_FECINI"
IS
  'FECHA DE INICIO DEL CONTRATO DEL PREPARADOR';
  COMMENT ON COLUMN "ECA14_SOL_PROSPECTORES"."ECA_PROS_FECFIN"
IS
  'FECHA DE FIN DEL CONTRATO DEL PREPARADOR';
  COMMENT ON COLUMN "ECA14_SOL_PROSPECTORES"."ECA_PROS_HORAS_JC"
IS
  'HORAS DEL CONTRATO A JORNADA COMPLETA';
  COMMENT ON COLUMN "ECA14_SOL_PROSPECTORES"."ECA_PROS_HORAS_CONT"
IS
  'HORAS DEL CONTRATO REALES';
  COMMENT ON COLUMN "ECA14_SOL_PROSPECTORES"."ECA_PROS_HORAS_ECA"
IS
  'HORAS DEDICADAS AL ECA';
  COMMENT ON COLUMN "ECA14_SOL_PROSPECTORES"."ECA_PROS_IMP_SS_JC"
IS
  'IMPORTE DE LOS GASTOS DE SS A JORNADA COMPLETA';
  COMMENT ON COLUMN "ECA14_SOL_PROSPECTORES"."ECA_PROS_IMP_SS_JR"
IS
  'IMPORTE DE LOS GASTOS DE SS A JORNADA REAL';
  COMMENT ON COLUMN "ECA14_SOL_PROSPECTORES"."ECA_PROS_IMP_SS_ECA"
IS
  'IMPORTE DE LOS GASTOS DE SS IMPUTABLES ECA';
  COMMENT ON COLUMN "ECA14_SOL_PROSPECTORES"."ECA_PROS_VISITAS"
IS
  'NUMERO DE VISITAS';
  COMMENT ON COLUMN "ECA14_SOL_PROSPECTORES"."ECA_PROS_VISITAS_IMP"
IS
  'IMPORTE POR VISITAS';
  COMMENT ON COLUMN "ECA14_SOL_PROSPECTORES"."ECA_PROS_COSTE"
IS
  'COSTES DEL PROSPECTOR POR SS+SALARIO';
  COMMENT ON COLUMN "ECA14_SOL_PROSPECTORES"."ECA_PROS_SOLICITUD"
IS
  'CLAVE FORANEA DE LA SOLICITUD';
  COMMENT ON COLUMN "ECA14_SOL_PROSPECTORES"."ECA_PROS_TIPO_SUST"
IS
  'Tipo de sustituto (1: Solcitud; 2: Justificacion)';
  COMMENT ON COLUMN "ECA14_SOL_PROSPECTORES"."ECA_PROS_CODORIGEN"
IS
  'Codigo del prospector al que sustituye';
  COMMENT ON COLUMN "ECA14_SOL_PROSPECTORES"."ECA_PROS_NIF_CARGA"
IS
  'NIF DEL PROSPECTOR';
  COMMENT ON COLUMN "ECA14_SOL_PROSPECTORES"."ECA_PROS_NOMBRE_CARGA"
IS
  'NOMBRE DEL PROSPECTOR';
  COMMENT ON COLUMN "ECA14_SOL_PROSPECTORES"."ECA_PROS_FECINI_CARGA"
IS
  'FECHA DE INICIO DEL CONTRATO DEL PROSPECTOR';
  COMMENT ON COLUMN "ECA14_SOL_PROSPECTORES"."ECA_PROS_FECFIN_CARGA"
IS
  'FECHA DE FIN DEL CONTRATO DEL PROSPECTOR';
  COMMENT ON COLUMN "ECA14_SOL_PROSPECTORES"."ECA_PROS_HORAS_JC_CARGA"
IS
  'HORAS DEL CONTRATO A JORNADA COMPLETA';
  COMMENT ON COLUMN "ECA14_SOL_PROSPECTORES"."ECA_PROS_HORAS_CONT_CARGA"
IS
  'HORAS DEL CONTRATO REALES';
  COMMENT ON COLUMN "ECA14_SOL_PROSPECTORES"."ECA_PROS_HORAS_ECA_CARGA"
IS
  'HORAS DEDICADAS AL ECA';
  COMMENT ON COLUMN "ECA14_SOL_PROSPECTORES"."ECA_PROS_IMP_SS_JC_CARGA"
IS
  'IMPORTE DE LOS GASTOS DE SS A JORNADA COMPLETA';
  COMMENT ON COLUMN "ECA14_SOL_PROSPECTORES"."ECA_PROS_IMP_SS_JR_CARGA"
IS
  'IMPORTE DE LOS GASTOS DE SS A JORNADA REAL';
  COMMENT ON COLUMN "ECA14_SOL_PROSPECTORES"."ECA_PROS_IMP_SS_ECA_CARGA"
IS
  'IMPORTE DE LOS GASTOS DE SS IMPUTABLES ECA';
  COMMENT ON COLUMN "ECA14_SOL_PROSPECTORES"."ECA_PROS_VISITAS_CARGA"
IS
  'NUMERO DE VISITAS';
  COMMENT ON COLUMN "ECA14_SOL_PROSPECTORES"."ECA_PROS_VISITAS_IMP_CARGA"
IS
  'IMPORTE POR VISITAS';
  COMMENT ON COLUMN "ECA14_SOL_PROSPECTORES"."ECA_PROS_COSTE_CARGA"
IS
  'COSTES DEL PROSPECTOR POR SS+SALARIO';
  COMMENT ON TABLE "ECA14_SOL_PROSPECTORES"
IS
  'TABLE DE PROSPECTORES DEL MODULO DE EXTENSION 35 ';
  
  --ECA14_SOL_VALORACION
  CREATE TABLE "ECA14_SOL_VALORACION"
  (
    "ECA_SOL_VALORACION_COD"       NUMBER(8,0),
    "ECA_SOL_VAL_EXPERIENCIA_NUM"  NUMBER(8,0),
    "ECA_SOL_VAL_EXPERIENCIA_VAL"  NUMBER(8,2),
    "ECA_SOL_VAL_INS_MUJERES_NUM"  NUMBER(8,2),
    "ECA_SOL_VAL_INS_MUJERES_VAL"  NUMBER(8,2),
    "ECA_SOL_VAL_SENSIBILIDAD_NUM" NUMBER(8,0),
    "ECA_SOL_VAL_SENSIBILIDAD_VAL" NUMBER(8,2),
    "ECA_SOL_VAL_TOTAL"            NUMBER(8,2),
    "ECA_SOL_VAL_SOLICITUD"        NUMBER(8,0),
    CONSTRAINT "ECA14_SOL_VALORACION_SO_FK1" FOREIGN KEY ("ECA_SOL_VAL_SOLICITUD") REFERENCES "ECA14_SOLICITUD" ("ECA_SOLICITUD_COD") 
  );
COMMENT ON COLUMN "ECA14_SOL_VALORACION"."ECA_SOL_VALORACION_COD"
IS
  'IDENTIFICACION UNIVOCA DEL REGISTRO EN LA TABLA. PK';
  COMMENT ON COLUMN "ECA14_SOL_VALORACION"."ECA_SOL_VAL_EXPERIENCIA_NUM"
IS
  'NUMERO DE AÑOS DE EXPEDIENCIA';
  COMMENT ON COLUMN "ECA14_SOL_VALORACION"."ECA_SOL_VAL_EXPERIENCIA_VAL"
IS
  'VALORACION DE LA EXPERIENCIA';
  COMMENT ON COLUMN "ECA14_SOL_VALORACION"."ECA_SOL_VAL_INS_MUJERES_NUM"
IS
  'PORCENTAJE INSERCION DE MUJERES';
  COMMENT ON COLUMN "ECA14_SOL_VALORACION"."ECA_SOL_VAL_INS_MUJERES_VAL"
IS
  'VALORACION DEL PORCENTAJE DE INSERCION DE MUJERES';
  COMMENT ON COLUMN "ECA14_SOL_VALORACION"."ECA_SOL_VAL_SENSIBILIDAD_NUM"
IS
  'PORCENTAJE DE SENSIBILIDAD';
  COMMENT ON COLUMN "ECA14_SOL_VALORACION"."ECA_SOL_VAL_SENSIBILIDAD_VAL"
IS
  'VALORACION DE SENSIBILIDAD';
  COMMENT ON COLUMN "ECA14_SOL_VALORACION"."ECA_SOL_VAL_TOTAL"
IS
  'VALORACION TOTAL';
  COMMENT ON COLUMN "ECA14_SOL_VALORACION"."ECA_SOL_VAL_SOLICITUD"
IS
  'CLAVE FORANEA DE LA SOLICITUD';
  COMMENT ON TABLE "ECA14_SOL_VALORACION"
IS
  'TABLE DE PROSPECTORES DEL MODULO DE EXTENSION 35 ';
  
  
  
  --ECA14_TIPOCONTRATO
  CREATE TABLE "ECA14_TIPOCONTRATO"
  (
    "COD_TIPOCONTRATO" NUMBER(2,0) NOT NULL ENABLE,
    "NOMBRE_C"         VARCHAR2(100 BYTE),
    "NOMBRE_E"         VARCHAR2(100 BYTE),
    CONSTRAINT "ECA14_TIPOCONTRATO_PK" PRIMARY KEY ("COD_TIPOCONTRATO")
  );
  
  
  --ECA14_TIPODISCAPACIDAD
  CREATE TABLE "ECA14_TIPODISCAPACIDAD"
  (
    "COD_TDISCAPACIDAD" NUMBER(1,0) NOT NULL ENABLE,
    "NOMBRE_C"          VARCHAR2(100 BYTE),
    "NOMBRE_E"          VARCHAR2(100 BYTE),
    CONSTRAINT "ECA14_TIPODISCAPACIDAD_PK" PRIMARY KEY ("COD_TDISCAPACIDAD")
  );
  
  
  --ECA14_VIS_PROSPECTORES
  CREATE TABLE "ECA14_VIS_PROSPECTORES"
  (
    "ECA_VIS_PROSPECTORES_COD" NUMBER(8,0) NOT NULL ENABLE,
    "ECA_JUS_PROSPECTORES_COD" NUMBER(8,0) NOT NULL ENABLE,
    "ECA_VIS_EMPRESA"          VARCHAR2(100 BYTE),
    "ECA_VIS_CIF"              VARCHAR2(10 BYTE),
    "ECA_VIS_SECTOR"           NUMBER(2,0),
    "ECA_VIS_DIRECCION"        VARCHAR2(100 BYTE),
    "ECA_VIS_CP"               VARCHAR2(5 BYTE),
    "ECA_VIS_PROVINCIA"        NUMBER(2,0),
    "ECA_VIS_LOCALIDAD"        VARCHAR2(100 BYTE),
    "ECA_VIS_FECVISITA" DATE,
    "ECA_VIS_PERSCONTACTO"   VARCHAR2(100 BYTE),
    "ECA_VIS_CARGOPUESTO"    VARCHAR2(100 BYTE),
    "ECA_VIS_EMAIL"          VARCHAR2(100 BYTE),
    "ECA_VIS_TELEFONO"       NUMBER(9,0),
    "ECA_VIS_NUMTRAB"        NUMBER(6,0),
    "ECA_VIS_NUMTRABDISC"    NUMBER(6,0),
    "ECA_VIS_CUMPLELISMI"    NUMBER(1,0),
    "ECA_VIS_RESULTADOFINAL" NUMBER(1,0),
    "ECA_VIS_OBSERVACIONES"  VARCHAR2(200 BYTE),
    "ECA_VIS_CORRECTO"       VARCHAR2(1 BYTE),
    CONSTRAINT "ECA14_VIS_PROSPECTORES_PK" PRIMARY KEY ("ECA_JUS_PROSPECTORES_COD", "ECA_VIS_PROSPECTORES_COD"),
    CONSTRAINT "ECA14_VIS_PROSPECTORES__FK1" FOREIGN KEY ("ECA_JUS_PROSPECTORES_COD") REFERENCES "ECA14_JUS_PROSPECTORES" ("ECA_JUS_PROSPECTORES_COD") ENABLE
  );
COMMENT ON COLUMN "ECA14_VIS_PROSPECTORES"."ECA_VIS_PROSPECTORES_COD"
IS
  'Código visita';
  COMMENT ON COLUMN "ECA14_VIS_PROSPECTORES"."ECA_JUS_PROSPECTORES_COD"
IS
  'Código de prospector';
  COMMENT ON COLUMN "ECA14_VIS_PROSPECTORES"."ECA_VIS_EMPRESA"
IS
  'Empresa';
  COMMENT ON COLUMN "ECA14_VIS_PROSPECTORES"."ECA_VIS_FECVISITA"
IS
  'Fecha seguimiento';
  COMMENT ON COLUMN "ECA14_VIS_PROSPECTORES"."ECA_VIS_PERSCONTACTO"
IS
  'Persona de contacto';
  COMMENT ON COLUMN "ECA14_VIS_PROSPECTORES"."ECA_VIS_OBSERVACIONES"
IS
  'Observaciones';
  COMMENT ON COLUMN "ECA14_VIS_PROSPECTORES"."ECA_VIS_CORRECTO"
IS
  'Correcto (S/N)';
  COMMENT ON TABLE "ECA14_VIS_PROSPECTORES"
IS
  'Visitas de prospectores';
  