----------------------------------------------------------------
--DDL for Table ECA_SOL_PREPARADORES
----------------------------------------------------------------

ALTER TABLE ECA_SOL_PREPARADORES add 
	 ( 
		ECA_PREP_NIF_CARGA   VARCHAR2(10 BYTE),
		ECA_PREP_NOMBRE_CARGA VARCHAR2(200 BYTE),
		ECA_PREP_FECINI_CARGA DATE,
		ECA_PREP_FECFIN_CARGA DATE,
		ECA_PREP_HORAS_JC_CARGA        NUMBER(8,2),
		ECA_PREP_HORAS_CONT_CARGA      NUMBER(8,2),
		ECA_PREP_HORAS_ECA_CARGA       NUMBER(8,2),
		ECA_PREP_IMP_SS_JC_CARGA       NUMBER(8,2),
		ECA_PREP_IMP_SS_JR_CARGA       NUMBER(8,2),
		ECA_PREP_IMP_SS_ECA_CARGA      NUMBER(8,2),
		ECA_PREP_SEG_ANT_CARGA         NUMBER(8,0),
		ECA_PREP_IMP_SEG_ANT_CARGA     NUMBER(8,2),
		ECA_PREP_INS_C1_H_CARGA        NUMBER(8,2),
		ECA_PREP_INS_C1_M_CARGA        NUMBER(8,2),
		ECA_PREP_INS_C1_CARGA          NUMBER(8,2),
		ECA_PREP_INS_C2_H_CARGA        NUMBER(8,2),
		ECA_PREP_INS_C2_M_CARGA        NUMBER(8,2),
		ECA_PREP_INS_C2_CARGA          NUMBER(8,2),
		ECA_PREP_INS_C3_H_CARGA        NUMBER(8,2),
		ECA_PREP_INS_C3_M_CARGA        NUMBER(8,2),
		ECA_PREP_INS_C3_CARGA          NUMBER(8,2),
		ECA_PREP_INS_C4_H_CARGA        NUMBER(8,2),
		ECA_PREP_INS_C4_M_CARGA        NUMBER(8,2),
		ECA_PREP_INS_C4_CARGA          NUMBER(8,2),
		ECA_PREP_INS_IMPORTE_CARGA     NUMBER(8,2),
		ECA_PREP_INS_SEG_IMPORTE_CARGA NUMBER(8,2),
		ECA_PREP_COSTE_CARGA           NUMBER(8,2)
	);


	COMMENT ON COLUMN "ECA_SOL_PREPARADORES"."ECA_PREP_NIF_CARGA" IS 'PREPARADOR NIF EN CARGA INICIAL';
	COMMENT ON COLUMN "ECA_SOL_PREPARADORES"."ECA_PREP_NOMBRE_CARGA" IS 'NOMBRE DEL PREPARADOR EN CARGA INICIAL';
	COMMENT ON COLUMN "ECA_SOL_PREPARADORES"."ECA_PREP_FECINI_CARGA" IS 'FECHA DE INICIO DEL CONTRATO DEL PREPARADOR EN CARGA INICIAL';
	COMMENT ON COLUMN "ECA_SOL_PREPARADORES"."ECA_PREP_FECFIN_CARGA" IS 'FECHA DE FIN DEL CONTRATO DEL PREPARADOR EN CARGA INICIAL';
	COMMENT ON COLUMN "ECA_SOL_PREPARADORES"."ECA_PREP_HORAS_JC_CARGA" IS 'HORAS DEL CONTRATO A JORNADA COMPLETA EN CARGA INICIAL';
	COMMENT ON COLUMN "ECA_SOL_PREPARADORES"."ECA_PREP_HORAS_CONT_CARGA" IS 'HORAS DEL CONTRATO REALES EN CARGA INICIAL';
	COMMENT ON COLUMN "ECA_SOL_PREPARADORES"."ECA_PREP_HORAS_ECA_CARGA" IS 'HORAS DEDICADAS AL ECA EN CARGA INICIAL';
	COMMENT ON COLUMN "ECA_SOL_PREPARADORES"."ECA_PREP_IMP_SS_JC_CARGA" IS 'IMPORTE DE LOS GASTOS DE SS A JORNADA COMPLETA EN CARGA INICIAL';
	COMMENT ON COLUMN "ECA_SOL_PREPARADORES"."ECA_PREP_IMP_SS_JR_CARGA" IS 'IMPORTE DE LOS GASTOS DE SS A JORNADA REAL EN CARGA INICIAL';
	COMMENT ON COLUMN "ECA_SOL_PREPARADORES"."ECA_PREP_IMP_SS_ECA_CARGA" IS 'IMPORTE DE LOS GASTOS DE SS IMPUTABLES ECA EN CARGA INICIAL';
	COMMENT ON COLUMN "ECA_SOL_PREPARADORES"."ECA_PREP_SEG_ANT_CARGA" IS 'NUMERO DE SEGUIMIENTOS ANTERIORES EN CARGA INICIAL';
	COMMENT ON COLUMN "ECA_SOL_PREPARADORES"."ECA_PREP_IMP_SEG_ANT_CARGA" IS 'IMPORTE POR SEGUIMIENTOS ANTERIORES EN CARGA INICIAL';
	COMMENT ON COLUMN "ECA_SOL_PREPARADORES"."ECA_PREP_INS_C1_H_CARGA" IS 'INSERCIONES DEL COLECTIVO 1 HOMBRES EN CARGA INICIAL';
	COMMENT ON COLUMN "ECA_SOL_PREPARADORES"."ECA_PREP_INS_C1_M_CARGA" IS 'INSERCIONES DEL COLECTIVO 1 MUJERES EN CARGA INICIAL';
	COMMENT ON COLUMN "ECA_SOL_PREPARADORES"."ECA_PREP_INS_C1_CARGA" IS 'INSERCIONES DEL COLECTIVO 1 EN CARGA INICIAL';
	COMMENT ON COLUMN "ECA_SOL_PREPARADORES"."ECA_PREP_INS_C2_H_CARGA" IS 'INSERCIONES DEL COLECTIVO 2 HOMBRES EN CARGA INICIAL';
	COMMENT ON COLUMN "ECA_SOL_PREPARADORES"."ECA_PREP_INS_C2_M_CARGA" IS 'INSERCIONES DEL COLECTIVO 2 MUJERES EN CARGA INICIAL';
	COMMENT ON COLUMN "ECA_SOL_PREPARADORES"."ECA_PREP_INS_C2_CARGA" IS 'INSERCIONES DEL COLECTIVO 2 EN CARGA INICIAL';
	COMMENT ON COLUMN "ECA_SOL_PREPARADORES"."ECA_PREP_INS_C3_H_CARGA" IS 'INSERCIONES DEL COLECTIVO 3 HOMBRES EN CARGA INICIAL';
	COMMENT ON COLUMN "ECA_SOL_PREPARADORES"."ECA_PREP_INS_C3_M_CARGA" IS 'INSERCIONES DEL COLECTIVO 3 MUJERES EN CARGA INICIAL';
	COMMENT ON COLUMN "ECA_SOL_PREPARADORES"."ECA_PREP_INS_C3_CARGA" IS 'INSERCIONES DEL COLECTIVO 3 EN CARGA INICIAL';
	COMMENT ON COLUMN "ECA_SOL_PREPARADORES"."ECA_PREP_INS_C4_H_CARGA" IS 'INSERCIONES DEL COLECTIVO 4 HOMBRES EN CARGA INICIAL';
	COMMENT ON COLUMN "ECA_SOL_PREPARADORES"."ECA_PREP_INS_C4_M_CARGA" IS 'INSERCIONES DEL COLECTIVO 4 MUJERES EN CARGA INICIAL';
	COMMENT ON COLUMN "ECA_SOL_PREPARADORES"."ECA_PREP_INS_C4_CARGA" IS 'INSERCIONES DEL COLECTIVO 4 EN CARGA INICIAL';
	COMMENT ON COLUMN "ECA_SOL_PREPARADORES"."ECA_PREP_INS_IMPORTE_CARGA" IS 'IMPORTE POR INSERCIONES EN CARGA INICIAL';
	COMMENT ON COLUMN "ECA_SOL_PREPARADORES"."ECA_PREP_INS_SEG_IMPORTE_CARGA" IS 'IMPORTE POR INSERCIONES Y SEGUIMIENTOS EN CARGA INICIAL';
	COMMENT ON COLUMN "ECA_SOL_PREPARADORES"."ECA_PREP_COSTE_CARGA" IS 'COSTES DEL PREPARADOR POR SS+SALARIO EN CARGA INICIAL';	
	
	
----------------------------------------------------------------
--DDL for Table ECA_SOL_PROSPECTORES
----------------------------------------------------------------

	ALTER TABLE ECA_SOL_PROSPECTORES add 
	(
		ECA_PROS_NIF_CARGA             VARCHAR2(10 BYTE),
		ECA_PROS_NOMBRE_CARGA          VARCHAR2(100 BYTE),
		ECA_PROS_FECINI_CARGA DATE,
		ECA_PROS_FECFIN_CARGA DATE,
		ECA_PROS_HORAS_JC_CARGA    NUMBER(8,2),
		ECA_PROS_HORAS_CONT_CARGA  NUMBER(8,2),
		ECA_PROS_HORAS_ECA_CARGA   NUMBER(8,2),
		ECA_PROS_IMP_SS_JC_CARGA   NUMBER(8,2),
		ECA_PROS_IMP_SS_JR_CARGA   NUMBER(8,2),
		ECA_PROS_IMP_SS_ECA_CARGA  NUMBER(8,2),
		ECA_PROS_VISITAS_CARGA     NUMBER(8,0),
		ECA_PROS_VISITAS_IMP_CARGA NUMBER(8,2),
		ECA_PROS_COSTE_CARGA       NUMBER(8,2)
	);

	COMMENT ON COLUMN "ECA_SOL_PROSPECTORES"."ECA_PROS_NIF_CARGA" IS 'NIF DEL PROSPECTOR';

	COMMENT ON COLUMN "ECA_SOL_PROSPECTORES"."ECA_PROS_NOMBRE_CARGA" IS 'NOMBRE DEL PROSPECTOR';

	COMMENT ON COLUMN "ECA_SOL_PROSPECTORES"."ECA_PROS_FECINI_CARGA" IS 'FECHA DE INICIO DEL CONTRATO DEL PROSPECTOR';

	COMMENT ON COLUMN "ECA_SOL_PROSPECTORES"."ECA_PROS_FECFIN_CARGA" IS 'FECHA DE FIN DEL CONTRATO DEL PROSPECTOR';

	COMMENT ON COLUMN "ECA_SOL_PROSPECTORES"."ECA_PROS_HORAS_JC_CARGA" IS 'HORAS DEL CONTRATO A JORNADA COMPLETA';

	COMMENT ON COLUMN "ECA_SOL_PROSPECTORES"."ECA_PROS_HORAS_CONT_CARGA" IS 'HORAS DEL CONTRATO REALES';

	COMMENT ON COLUMN "ECA_SOL_PROSPECTORES"."ECA_PROS_HORAS_ECA_CARGA" IS 'HORAS DEDICADAS AL ECA';

	COMMENT ON COLUMN "ECA_SOL_PROSPECTORES"."ECA_PROS_IMP_SS_JC_CARGA" IS 'IMPORTE DE LOS GASTOS DE SS A JORNADA COMPLETA';

	COMMENT ON COLUMN "ECA_SOL_PROSPECTORES"."ECA_PROS_IMP_SS_JR_CARGA" IS 'IMPORTE DE LOS GASTOS DE SS A JORNADA REAL';

	COMMENT ON COLUMN "ECA_SOL_PROSPECTORES"."ECA_PROS_IMP_SS_ECA_CARGA" IS 'IMPORTE DE LOS GASTOS DE SS IMPUTABLES ECA';

	COMMENT ON COLUMN "ECA_SOL_PROSPECTORES"."ECA_PROS_VISITAS_CARGA" IS 'NUMERO DE VISITAS';

	COMMENT ON COLUMN "ECA_SOL_PROSPECTORES"."ECA_PROS_VISITAS_IMP_CARGA" IS 'IMPORTE POR VISITAS';

	COMMENT ON COLUMN "ECA_SOL_PROSPECTORES"."ECA_PROS_COSTE_CARGA" IS 'COSTES DEL PROSPECTOR POR SS+SALARIO';
	
	
----------------------------------------------------------------
--DDL for Table ECA_JUS_PREPARADORES
----------------------------------------------------------------

ALTER TABLE ECA_JUS_PREPARADORES  add ECA_PREP_CODORIGEN  NUMBER(8) ;
	COMMENT ON COLUMN "ECA_JUS_PREPARADORES"."ECA_PREP_CODORIGEN" IS 'PREPARADOR ORIGEN';
	
	
----------------------------------------------------------------
--DDL for Table ECA_JUS_PROSPECTORES
----------------------------------------------------------------

ALTER TABLE ECA_JUS_PROSPECTORES  add ECA_PROS_CODORIGEN  NUMBER(8) ;
	COMMENT ON COLUMN "ECA_JUS_PROSPECTORES"."ECA_PROS_CODORIGEN" IS 'PROSPECTOR ORIGEN';