--------------------------------------------------------
--  DDL for Table CME_PUESTO
--------------------------------------------------------

  CREATE TABLE "CME_PUESTO" 
   (	"CME_PTO_COD_PUESTO" VARCHAR2(4 BYTE), 
	"CME_PTO_DESC_PUESTO" VARCHAR2(200 BYTE), 
	"CME_PTO_PAI_COD_1" NUMBER(3,0), 
	"CME_PTO_PAI_COD_2" NUMBER(3,0), 
	"CME_PTO_PAI_COD_3" NUMBER(3,0), 
	"CME_PTO_COD_TIT_1" VARCHAR2(8 BYTE), 
	"CME_PTO_COD_TIT_2" VARCHAR2(8 BYTE), 
	"CME_PTO_COD_TIT_3" VARCHAR2(8 BYTE), 
	"CME_PTO_FUNCIONES" VARCHAR2(1000 BYTE), 
	"CME_PTO_COD_IDIOMA_1" VARCHAR2(8 BYTE), 
	"CME_PTO_COD_IDIOMA_2" VARCHAR2(8 BYTE), 
	"CME_PTO_COD_NIV_FORM" VARCHAR2(8 BYTE), 
	"CME_PTO_COD_GR_COT" VARCHAR2(8 BYTE), 
	"CME_PTO_SALARIO_ANEX1" NUMBER(10,2), 
	"CME_PTO_DIETAS_MANUT" NUMBER(10,2), 
	"CME_PTO_MESES_MANUT" NUMBER(4,0), 
	"CME_PTO_TRAM_SEGUROS" NUMBER(10,2), 
	"CME_PTO_IMP_MAX_SUBV" NUMBER(10,2), 
	"CME_PTO_FEC_INI" DATE, 
	"CME_PTO_FEC_FIN" DATE, 
	"CME_PTO_CONVENIO_COL" VARCHAR2(500 BYTE), 
	"CME_PTO_SAL_BRUTO" NUMBER(10,2), 
	"CME_PTO_DIETAS_CONV" NUMBER(10,2), 
	"CME_PTO_COSTE_CONT" NUMBER(10,2), 
	"CME_PTO_OTROS_BENEF" VARCHAR2(1000 BYTE), 
	"CME_PTO_COD_RESULT" VARCHAR2(8 BYTE), 
	"CME_PTO_COD_MOTIVO" VARCHAR2(8 BYTE), 
	"CME_PTO_OBSERVACIONES" VARCHAR2(1000 BYTE), 
	"CME_PTO_COD_NIV_IDI_1" VARCHAR2(8 BYTE), 
	"CME_PTO_COD_NIV_IDI_2" VARCHAR2(8 BYTE), 
	"CME_PTO_NUMEXP" VARCHAR2(30 BYTE), 
	"CME_PTO_EXP_EJE" NUMBER(4,0), 
	"CME_PTO_CIUDAD_DESTINO" VARCHAR2(200 BYTE), 
	"CME_PTO_DPTO" VARCHAR2(200 BYTE), 
	"CME_PTO_COD_IDIOMA_3" VARCHAR2(8 BYTE), 
	"CME_PTO_COD_NIV_IDI_3" VARCHAR2(8 BYTE), 
	"CME_PTO_SAL_SOLIC" NUMBER(10,2), 
	"CME_PTO_DIETAS_SOLIC" NUMBER(10,2), 
	"CME_PTO_TRAM_SOLIC" NUMBER(10,2), 
	"CME_PTO_IMP_TOT_SOLIC" NUMBER(10,2), 
	"CME_PTO_SALARIO_ANEX2" NUMBER(10,2), 
	"CME_PTO_SALARIO_ANEX3" NUMBER(10,2), 
	"CME_PTO_SALARIO_ANEX_TOT" NUMBER(10,2), 
	"CME_PTO_MESES_CONTRATO" NUMBER(6,0)
   );
 

   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_COD_PUESTO" IS 'Codigo univoco del puesto - PK';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_DESC_PUESTO" IS 'Descripción o nombre del puesto';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_PAI_COD_1" IS 'Código de país 1';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_PAI_COD_2" IS 'Código de país 2';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_PAI_COD_3" IS 'Código de país 3';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_COD_TIT_1" IS 'Código de titulación 1';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_COD_TIT_2" IS 'Código de titulación 2';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_COD_TIT_3" IS 'Código de titulación 3';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_FUNCIONES" IS 'Funciones del puesto';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_COD_IDIOMA_1" IS 'Código de idioma 1';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_COD_IDIOMA_2" IS 'Código de idioma 2';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_COD_NIV_FORM" IS 'Nivel formativo';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_COD_GR_COT" IS 'Grupo cotización';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_SALARIO_ANEX1" IS 'Salario según anexo 1 - Pais 1';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_DIETAS_MANUT" IS 'Dietas manutención';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_MESES_MANUT" IS 'Meses manutención';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_TRAM_SEGUROS" IS 'Tramitación seguros médicos y permisos';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_IMP_MAX_SUBV" IS 'Importe máximo subvencionable';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_FEC_INI" IS 'Fecha inicio';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_FEC_FIN" IS 'Fecha fin';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_CONVENIO_COL" IS 'Convenio colectivo';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_SAL_BRUTO" IS 'Salario Bruto + SS empresa';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_DIETAS_CONV" IS 'Dietas según convenio';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_COSTE_CONT" IS 'Coste contratación';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_OTROS_BENEF" IS 'Otros beneficios';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_COD_RESULT" IS 'Código de resultado';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_COD_MOTIVO" IS 'Código de motivo';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_OBSERVACIONES" IS 'Observaciones';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_COD_NIV_IDI_1" IS 'Nivel de idioma 1';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_COD_NIV_IDI_2" IS 'Nivel de idioma 2';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_NUMEXP" IS 'Número de expediente';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_EXP_EJE" IS 'Ejercicio del expediente';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_CIUDAD_DESTINO" IS 'Ciudad de destino';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_DPTO" IS 'Departamento';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_COD_IDIOMA_3" IS 'Código de idioma 3';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_COD_NIV_IDI_3" IS 'Nivel de idioma 3';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_SAL_SOLIC" IS 'Salario solicitado';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_DIETAS_SOLIC" IS 'Dietas solicitadas';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_TRAM_SOLIC" IS 'Tramitación / Seguros solicitado';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_IMP_TOT_SOLIC" IS 'Importe total solicitado';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_SALARIO_ANEX2" IS 'Salario según anexo 1 - Pais 2';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_SALARIO_ANEX3" IS 'Salario según anexo 1 - Pais 3';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_SALARIO_ANEX_TOT" IS 'Total salario';
 
   COMMENT ON COLUMN "CME_PUESTO"."CME_PTO_MESES_CONTRATO" IS 'Duración en meses del contrato';
   

   
   
   CREATE UNIQUE INDEX "CME_PUESTO_PK" ON "CME_PUESTO" ("CME_PTO_COD_PUESTO", "CME_PTO_NUMEXP");

   ALTER TABLE "CME_PUESTO" ADD CONSTRAINT "CME_PUESTO_PK" PRIMARY KEY ("CME_PTO_COD_PUESTO", "CME_PTO_NUMEXP") ENABLE;
 
   ALTER TABLE "CME_PUESTO" MODIFY ("CME_PTO_COD_PUESTO" NOT NULL ENABLE);
 
   ALTER TABLE "CME_PUESTO" MODIFY ("CME_PTO_NUMEXP" NOT NULL ENABLE);
   
   

   
--------------------------------------------------------
--  DDL for Table CME_OFERTA
--------------------------------------------------------

  CREATE TABLE "CME_OFERTA" 
   (	"CME_OFE_ID_OFERTA" NUMBER(8,0), 
	"CME_OFE_COD_OFERTA" VARCHAR2(15 BYTE), 
	"CME_OFE_COD_OFI_GEST" VARCHAR2(8 BYTE), 
	"CME_OFE_PREC" VARCHAR2(1 BYTE), 
	"CME_OFE_PREC_NOM" VARCHAR2(200 BYTE), 
	"CME_OFE_DIFUSION" VARCHAR2(1 BYTE), 
	"CME_OFE_FEC_DIFUSION" DATE, 
	"CME_OFE_FEC_ENV_CAND" DATE, 
	"CME_OFE_NUM_TOT_CAND" NUMBER(3,0), 
	"CME_OFE_DOC_GEST_OFE" BLOB, 
	"CME_OFE_CONTRATACION" VARCHAR2(1 BYTE), 
	"CME_OFE_MOT_CONTRATACION" VARCHAR2(1000 BYTE), 
	"CME_OFE_COD_TIPO_NIF" VARCHAR2(8 BYTE), 
	"CME_OFE_NIF" VARCHAR2(10 BYTE), 
	"CME_OFE_NOMBRE" VARCHAR2(200 BYTE), 
	"CME_OFE_APE1" VARCHAR2(200 BYTE), 
	"CME_OFE_APE2" VARCHAR2(200 BYTE), 
	"CME_OFE_EMAIL" VARCHAR2(200 BYTE), 
	"CME_OFE_TLF" VARCHAR2(15 BYTE), 
	"CME_OFE_FEC_NAC" DATE, 
	"CME_OFE_SEXO" VARCHAR2(1 BYTE), 
	"CME_OFE_COD_TITULACION" VARCHAR2(8 BYTE), 
	"CME_OFE_DOC_CONTRATACION" BLOB, 
	"CME_OFE_FEC_INI" DATE, 
	"CME_OFE_FEC_FIN" DATE, 
	"CME_OFE_COD_GR_COT" VARCHAR2(8 BYTE), 
	"CME_OFE_SALARIOB" NUMBER(10,2), 
	"CME_OFE_DIETAS_CONVENIO" NUMBER(10,2), 
	"CME_OFE_DIETAS_CONVOC" NUMBER(10,2), 
	"CME_OFE_FEC_BAJA" DATE, 
	"CME_OFE_COD_CAUSA_BAJA" VARCHAR2(8 BYTE), 
	"CME_OFE_OBSERVACIONES" VARCHAR2(1000 BYTE), 
	"CME_OFE_COD_PUESTO" VARCHAR2(4 BYTE), 
	"CME_OFE_NUMEXP" VARCHAR2(30 BYTE), 
	"CME_OFE_EXP_EJE" NUMBER(4,0), 
	"CME_OFE_ANO_TITULACION" NUMBER(4,0), 
	"CME_OFE_FL_SUSTITUTO" VARCHAR2(1 BYTE), 
	"CME_OFE_NOM_DOC_GEST_OFE" VARCHAR2(500 BYTE), 
	"CME_OFE_NOM_DOC_CONTRATACION" VARCHAR2(500 BYTE), 
	"CME_OFE_ID_OFERTA_ORIGEN" NUMBER(8,0),
	"CME_OFE_DESC_PUESTO"   VARCHAR2(200 BYTE),
    "CME_OFE_PAI_COD_1"     NUMBER(3,0),
    "CME_OFE_PAI_COD_2"     NUMBER(3,0),
    "CME_OFE_PAI_COD_3"     NUMBER(3,0),
    "CME_OFE_COD_TIT_1"     VARCHAR2(8 BYTE),
    "CME_OFE_COD_TIT_2"     VARCHAR2(8 BYTE),
    "CME_OFE_COD_TIT_3"     VARCHAR2(8 BYTE),
    "CME_OFE_FUNCIONES"     VARCHAR2(1000 BYTE),
    "CME_OFE_COD_IDIOMA_1"  VARCHAR2(8 BYTE),
    "CME_OFE_COD_IDIOMA_2"  VARCHAR2(8 BYTE),
	"CME_OFE_COD_IDIOMA_3"     VARCHAR2(8 BYTE),
	"CME_OFE_COD_NIV_IDI_1"    VARCHAR2(8 BYTE),
    "CME_OFE_COD_NIV_IDI_2"    VARCHAR2(8 BYTE),
    "CME_OFE_COD_NIV_IDI_3"    VARCHAR2(8 BYTE),
	"CME_OFE_COD_NIV_FORM"  VARCHAR2(8 BYTE),
	"CME_OFE_CIUDAD_DESTINO" VARCHAR2(200 BYTE), 
	"CME_OFE_DPTO" VARCHAR2(200 BYTE),
	"CME_OFE_MESES_CONTRATO" NUMBER(6),
	"CME_OFE_COD_CAUSA_RENUNCIA" VARCHAR2(8 BYTE)	
   );
   
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_ID_OFERTA" IS 'Id de la tabla';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_COD_OFERTA" IS 'Código de la oferta';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_COD_OFI_GEST" IS 'Código de la oficina de gestión';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_PREC" IS 'Precandidato (S/N)';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_PREC_NOM" IS 'Nombre precandidato';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_DIFUSION" IS 'Difusión (S/N)';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_FEC_DIFUSION" IS 'Fecha difusión';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_FEC_ENV_CAND" IS 'Fecha primer envío candidatos';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_NUM_TOT_CAND" IS 'Número total de l candidatos';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_DOC_GEST_OFE" IS 'Documento de gestión de la oferta';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_CONTRATACION" IS 'Contratación (S/N/Sin Datos)';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_MOT_CONTRATACION" IS 'Motivo de la NO contratación';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_COD_TIPO_NIF" IS 'Tipo de documento del contratado';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_NIF" IS 'Número de documento del contratado';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_NOMBRE" IS 'Nombre del contratado';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_APE1" IS 'Apellido 1 del contratado';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_APE2" IS 'Apellido 2 del contratado';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_EMAIL" IS 'email del contratado';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_TLF" IS 'Número de teléfono del contratado';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_FEC_NAC" IS 'Fecha de nacimiento del contratado';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_SEXO" IS 'Sexo del contratado';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_COD_TITULACION" IS 'Titulación del contratado';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_DOC_CONTRATACION" IS 'Documento de contratación';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_FEC_INI" IS 'Fecha de inicio del contrato';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_FEC_FIN" IS 'Fecha de fin del contrato';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_COD_GR_COT" IS 'Grupo de cotización del contratado';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_SALARIOB" IS 'Salario bruto + SS empresa';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_DIETAS_CONVENIO" IS 'Dietas según convenio';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_DIETAS_CONVOC" IS 'Dietas de la convocatoria';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_FEC_BAJA" IS 'Fecha de baja';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_COD_CAUSA_BAJA" IS 'Causa de baja';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_OBSERVACIONES" IS 'Observaciones';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_COD_PUESTO" IS 'FK al puesto';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_NUMEXP" IS 'Número del expediente';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_EXP_EJE" IS 'Ejercicio del expediente';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_ANO_TITULACION" IS 'Año Titulación';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_FL_SUSTITUTO" IS 'Flag que indica si la persona contratada es sustituto o no';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_NOM_DOC_GEST_OFE" IS 'Nombre del documento de gestión asociado.';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_NOM_DOC_CONTRATACION" IS 'Nombre del documento de contratación asociado.';
 
   COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_ID_OFERTA_ORIGEN" IS 'ID de la oferta de la cual se van a coger parte de los datos: oferta de origen.';

  COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_DESC_PUESTO" IS   'Descripción o nombre del puesto';
  COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_PAI_COD_1" IS   'Código de país 1';
  COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_PAI_COD_2" IS   'Código de país 2';
  COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_PAI_COD_3" IS   'Código de país 3';
  COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_COD_TIT_1" IS   'Código de titulación 1';
  COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_COD_TIT_2" IS   'Código de titulación 2';
  COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_COD_TIT_3" IS   'Código de titulación 3';
  COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_FUNCIONES" IS   'Funciones del puesto';
  COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_COD_IDIOMA_1" IS  'Código de idioma 1';
  COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_COD_IDIOMA_2" IS  'Código de idioma 2';
  COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_COD_IDIOMA_3" IS  'Código de idioma 3';
  COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_COD_NIV_FORM" IS  'Nivel formativo';
  COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_COD_NIV_IDI_1" IS  'Nivel de idioma 1';
  COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_COD_NIV_IDI_2" IS  'Nivel de idioma 2';
  COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_COD_NIV_IDI_3" IS  'Nivel de idioma 3';
  COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_CIUDAD_DESTINO" IS  'Ciudad destino';
  COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_DPTO" IS  'Departamento';
  COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_COD_CAUSA_RENUNCIA" IS 'Codigo de causa por la que se renuncia al puesto';
  COMMENT ON COLUMN "CME_OFERTA"."CME_OFE_MESES_CONTRATO" IS 'Meses contrato';
   
   CREATE UNIQUE INDEX "CME_OFERTA_PK" ON "CME_OFERTA" ("CME_OFE_ID_OFERTA", "CME_OFE_COD_PUESTO", "CME_OFE_NUMEXP");

   
   
   
   ALTER TABLE "CME_OFERTA" ADD CONSTRAINT "CME_OFERTA_PK" PRIMARY KEY ("CME_OFE_ID_OFERTA", "CME_OFE_COD_PUESTO", "CME_OFE_NUMEXP") ENABLE;
 
   ALTER TABLE "CME_OFERTA" MODIFY ("CME_OFE_ID_OFERTA" NOT NULL ENABLE);
 
   ALTER TABLE "CME_OFERTA" MODIFY ("CME_OFE_COD_PUESTO" NOT NULL ENABLE);
 
   ALTER TABLE "CME_OFERTA" MODIFY ("CME_OFE_NUMEXP" NOT NULL ENABLE);

   ALTER TABLE "CME_OFERTA" ADD CONSTRAINT "CME_OFERTA_CME_PUESTO_FK1" FOREIGN KEY ("CME_OFE_COD_PUESTO", "CME_OFE_NUMEXP")
   REFERENCES "CME_PUESTO" ("CME_PTO_COD_PUESTO", "CME_PTO_NUMEXP") ENABLE;
   
--------------------------------------------------------
--  DDL for Table CME_JUSTIFICACION
--------------------------------------------------------

  CREATE TABLE "CME_JUSTIFICACION" 
   (	"CME_JUS_ID_JUSTIFICACION" NUMBER(8,0), 
	"CME_JUS_COD_PUESTO" VARCHAR2(4 BYTE), 
	"CME_JUS_NUMEXP" VARCHAR2(30 BYTE), 
	"CME_JUS_EXP_EJE" NUMBER(4,0), 
	"CME_JUS_ID_OFERTA" NUMBER(8,0), 
	"CME_JUS_COD_ESTADO" VARCHAR2(8 BYTE), 
	"CME_JUS_FL_VARIOS_TRAB" VARCHAR2(1 BYTE), 
	"CME_JUS_IMP_JUSTIFICADO" NUMBER(10,2),
    "CME_JUS_SALARIOSUB" NUMBER(10,2),
    "CME_JUS_DIETAS" NUMBER(10,2),
    "CME_JUS_GASTOSGES" NUMBER(10,2),
    "CME_JUS_BONIF" NUMBER(10,2)
   );
 

   COMMENT ON COLUMN "CME_JUSTIFICACION"."CME_JUS_ID_JUSTIFICACION" IS 'ID de la tabla';
 
   COMMENT ON COLUMN "CME_JUSTIFICACION"."CME_JUS_COD_PUESTO" IS 'Código del puesto';
 
   COMMENT ON COLUMN "CME_JUSTIFICACION"."CME_JUS_NUMEXP" IS 'Número de expediente';
 
   COMMENT ON COLUMN "CME_JUSTIFICACION"."CME_JUS_EXP_EJE" IS 'Ejercicio del expediente';
 
   COMMENT ON COLUMN "CME_JUSTIFICACION"."CME_JUS_ID_OFERTA" IS 'Id de la oferta';
 
   COMMENT ON COLUMN "CME_JUSTIFICACION"."CME_JUS_COD_ESTADO" IS 'Estado (Justificado/Renuncia)';
 
   COMMENT ON COLUMN "CME_JUSTIFICACION"."CME_JUS_FL_VARIOS_TRAB" IS 'Flag para indicar si ha dispuesto de varios trabajadores';
 
   COMMENT ON COLUMN "CME_JUSTIFICACION"."CME_JUS_IMP_JUSTIFICADO" IS 'Importe jusiticado';
   
   
   

   CREATE UNIQUE INDEX "CME_JUSTIFICACION_PK" ON "CME_JUSTIFICACION" ("CME_JUS_ID_JUSTIFICACION", "CME_JUS_COD_PUESTO", "CME_JUS_ID_OFERTA", "CME_JUS_NUMEXP");

   ALTER TABLE "CME_JUSTIFICACION" ADD CONSTRAINT "CME_JUSTIFICACION_PK" PRIMARY KEY ("CME_JUS_ID_JUSTIFICACION", "CME_JUS_COD_PUESTO", "CME_JUS_ID_OFERTA", "CME_JUS_NUMEXP") ENABLE;
 
   ALTER TABLE "CME_JUSTIFICACION" MODIFY ("CME_JUS_ID_JUSTIFICACION" NOT NULL ENABLE);
 
   ALTER TABLE "CME_JUSTIFICACION" MODIFY ("CME_JUS_ID_OFERTA" NOT NULL ENABLE);
 
   ALTER TABLE "CME_JUSTIFICACION" MODIFY ("CME_JUS_COD_PUESTO" NOT NULL ENABLE);
 
   ALTER TABLE "CME_JUSTIFICACION" MODIFY ("CME_JUS_NUMEXP" NOT NULL ENABLE);


-------------------------------------------
-- TABLAS HISTORICO
-------------------------------------------
--TABLAS HISTÓRICAS CME
 --CME_HIST_PUESTO
  CREATE TABLE "CME_HIST_PUESTO"
  (
    "CME_PTO_ID"    NUMBER(8,0) NOT NULL ENABLE,
	"CME_PTO_COD_TRAMITE"    NUMBER(8,0) NOT NULL ENABLE,
	"CME_PTO_COD_PUESTO"    VARCHAR2(4 BYTE) NOT NULL ENABLE,
    "CME_PTO_DESC_PUESTO"   VARCHAR2(200 BYTE),
    "CME_PTO_PAI_COD_1"     NUMBER(3,0),
    "CME_PTO_PAI_COD_2"     NUMBER(3,0),
    "CME_PTO_PAI_COD_3"     NUMBER(3,0),
    "CME_PTO_COD_TIT_1"     VARCHAR2(8 BYTE),
    "CME_PTO_COD_TIT_2"     VARCHAR2(8 BYTE),
    "CME_PTO_COD_TIT_3"     VARCHAR2(8 BYTE),
    "CME_PTO_FUNCIONES"     VARCHAR2(1000 BYTE),
    "CME_PTO_COD_IDIOMA_1"  VARCHAR2(8 BYTE),
    "CME_PTO_COD_IDIOMA_2"  VARCHAR2(8 BYTE),
    "CME_PTO_COD_NIV_FORM"  VARCHAR2(8 BYTE),
    "CME_PTO_COD_GR_COT"    VARCHAR2(8 BYTE),
    "CME_PTO_SALARIO_ANEX1" NUMBER(10,2),
    "CME_PTO_DIETAS_MANUT"  NUMBER(10,2),
    "CME_PTO_MESES_MANUT"   NUMBER(4,0),
    "CME_PTO_TRAM_SEGUROS"  NUMBER(10,2),
    "CME_PTO_IMP_MAX_SUBV"  NUMBER(10,2),
    "CME_PTO_FEC_INI" DATE,
    "CME_PTO_FEC_FIN" DATE,
    "CME_PTO_CONVENIO_COL"     VARCHAR2(500 BYTE),
    "CME_PTO_SAL_BRUTO"        NUMBER(10,2),
    "CME_PTO_DIETAS_CONV"      NUMBER(10,2),
    "CME_PTO_COSTE_CONT"       NUMBER(10,2),
    "CME_PTO_OTROS_BENEF"      VARCHAR2(1000 BYTE),
    "CME_PTO_COD_RESULT"       VARCHAR2(8 BYTE),
    "CME_PTO_COD_MOTIVO"       VARCHAR2(4 BYTE),
    "CME_PTO_OBSERVACIONES"    VARCHAR2(1000 BYTE),
    "CME_PTO_COD_NIV_IDI_1"    VARCHAR2(8 BYTE),
    "CME_PTO_COD_NIV_IDI_2"    VARCHAR2(8 BYTE),
    "CME_PTO_NUMEXP"           VARCHAR2(30 BYTE) NOT NULL ENABLE,
    "CME_PTO_EXP_EJE"          NUMBER(4,0),
    "CME_PTO_CIUDAD_DESTINO"   VARCHAR2(200 BYTE),
    "CME_PTO_DPTO"             VARCHAR2(200 BYTE),
    "CME_PTO_COD_IDIOMA_3"     VARCHAR2(8 BYTE),
    "CME_PTO_COD_NIV_IDI_3"    VARCHAR2(8 BYTE),
    "CME_PTO_SAL_SOLIC"        NUMBER(10,2),
    "CME_PTO_DIETAS_SOLIC"     NUMBER(10,2),
    "CME_PTO_TRAM_SOLIC"       NUMBER(10,2),
    "CME_PTO_IMP_TOT_SOLIC"    NUMBER(10,2),
    "CME_PTO_SALARIO_ANEX2"    NUMBER(10,2),
    "CME_PTO_SALARIO_ANEX3"    NUMBER(10,2),
    "CME_PTO_SALARIO_ANEX_TOT" NUMBER(10,2),
    "CME_PTO_MESES_CONTRATO"   NUMBER(6,0),
    "FECHA_HIST"            DATE,
    CONSTRAINT "CME_HIST_PUESTO_PK2" PRIMARY KEY ("CME_PTO_ID")
  );
COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_COD_PUESTO"
IS
  'Codigo univoco del puesto';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_ID"
IS
  'Codigo univoco del puesto - PK';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_DESC_PUESTO"
IS
  'Descripción o nombre del puesto';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_PAI_COD_1"
IS
  'Código de país 1';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_PAI_COD_2"
IS
  'Código de país 2';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_PAI_COD_3"
IS
  'Código de país 3';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_COD_TIT_1"
IS
  'Código de titulación 1';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_COD_TIT_2"
IS
  'Código de titulación 2';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_COD_TIT_3"
IS
  'Código de titulación 3';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_FUNCIONES"
IS
  'Funciones del puesto';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_COD_IDIOMA_1"
IS
  'Código de idioma 1';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_COD_IDIOMA_2"
IS
  'Código de idioma 2';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_COD_NIV_FORM"
IS
  'Nivel formativo';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_COD_GR_COT"
IS
  'Grupo cotización';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_SALARIO_ANEX1"
IS
  'Salario según anexo 1';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_DIETAS_MANUT"
IS
  'Dietas manutención';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_MESES_MANUT"
IS
  'Meses manutención';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_TRAM_SEGUROS"
IS
  'Tramitación seguros médicos y permisos';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_IMP_MAX_SUBV"
IS
  'Importe solicitado';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_FEC_INI"
IS
  'Fecha inicio';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_FEC_FIN"
IS
  'Fecha fin';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_CONVENIO_COL"
IS
  'Convenio colectivo';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_SAL_BRUTO"
IS
  'Salario Bruto + SS empresa';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_DIETAS_CONV"
IS
  'Dietas según convenio';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_COSTE_CONT"
IS
  'Coste contratación';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_OTROS_BENEF"
IS
  'Otros beneficios';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_COD_RESULT"
IS
  'Código de resultado';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_COD_MOTIVO"
IS
  'Código de motivo';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_OBSERVACIONES"
IS
  'Observaciones';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_COD_NIV_IDI_1"
IS
  'Nivel de idioma 1';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_COD_NIV_IDI_2"
IS
  'Nivel de idioma 2';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_NUMEXP"
IS
  'Número de expediente';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_EXP_EJE"
IS
  'Ejercicio del expediente';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_CIUDAD_DESTINO"
IS
  'Ciudad de destino';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_DPTO"
IS
  'Departamento';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_COD_IDIOMA_3"
IS
  'Código de idioma 3';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_COD_NIV_IDI_3"
IS
  'Nivel de idioma 3';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_SAL_SOLIC"
IS
  'Salario solicitado';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_DIETAS_SOLIC"
IS
  'Dietas solicitadas';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_TRAM_SOLIC"
IS
  'Tramitación / Seguros solicitado';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_IMP_TOT_SOLIC"
IS
  'Importe total solicitado';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_SALARIO_ANEX2"
IS
  'Salario según anexo 1 - Pais 2';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_SALARIO_ANEX3"
IS
  'Salario según anexo 1 - Pais 3';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_SALARIO_ANEX_TOT"
IS
  'Total salario';
  COMMENT ON COLUMN "CME_HIST_PUESTO"."CME_PTO_MESES_CONTRATO"
IS
  'Duración en meses del contrato';
  
  

CREATE TABLE "CME_HIST_OFERTA"
  (
    "CME_OFE_ID"    NUMBER(8,0) NOT NULL ENABLE,
	"CME_OFE_COD_TRAMITE"    NUMBER(8,0) NOT NULL ENABLE,
	"CME_OFE_ID_OFERTA"    NUMBER(8,0) NOT NULL ENABLE,
    "CME_OFE_COD_OFERTA"   VARCHAR2(15 BYTE),
    "CME_OFE_COD_OFI_GEST" VARCHAR2(8 BYTE),
    "CME_OFE_PREC"         VARCHAR2(1 BYTE),
    "CME_OFE_PREC_NOM"     VARCHAR2(200 BYTE),
    "CME_OFE_DIFUSION"     VARCHAR2(1 BYTE),
    "CME_OFE_FEC_DIFUSION" DATE,
    "CME_OFE_FEC_ENV_CAND" DATE,
    "CME_OFE_NUM_TOT_CAND" NUMBER(3,0),
    "CME_OFE_DOC_GEST_OFE" BLOB,
    "CME_OFE_CONTRATACION"     VARCHAR2(1 BYTE),
    "CME_OFE_MOT_CONTRATACION" VARCHAR2(1000 BYTE),
    "CME_OFE_COD_TIPO_NIF"     VARCHAR2(8 BYTE),
    "CME_OFE_NIF"              VARCHAR2(10 BYTE),
    "CME_OFE_NOMBRE"           VARCHAR2(200 BYTE),
    "CME_OFE_APE1"             VARCHAR2(200 BYTE),
    "CME_OFE_APE2"             VARCHAR2(200 BYTE),
    "CME_OFE_EMAIL"            VARCHAR2(200 BYTE),
    "CME_OFE_TLF"              VARCHAR2(15 BYTE),
    "CME_OFE_FEC_NAC" DATE,
    "CME_OFE_SEXO"           VARCHAR2(1 BYTE),
    "CME_OFE_COD_TITULACION" VARCHAR2(8 BYTE),
    "CME_OFE_DOC_CONTRATACION" BLOB,
    "CME_OFE_FEC_INI" DATE,
    "CME_OFE_FEC_FIN" DATE,
    "CME_OFE_COD_GR_COT"      VARCHAR2(8 BYTE),
    "CME_OFE_SALARIOB"        NUMBER(10,2),
    "CME_OFE_DIETAS_CONVENIO" NUMBER(10,2),
    "CME_OFE_DIETAS_CONVOC"   NUMBER(10,2),
    "CME_OFE_FEC_BAJA" DATE,
    "CME_OFE_COD_CAUSA_BAJA"       VARCHAR2(8 BYTE),
    "CME_OFE_OBSERVACIONES"        VARCHAR2(1000 BYTE),
    "CME_OFE_COD_PUESTO"           VARCHAR2(4 BYTE) NOT NULL ENABLE,
    "CME_OFE_NUMEXP"               VARCHAR2(30 BYTE) NOT NULL ENABLE,
    "CME_OFE_EXP_EJE"              NUMBER(4,0),
    "CME_OFE_ANO_TITULACION"       NUMBER(4,0),
    "CME_OFE_FL_SUSTITUTO"         VARCHAR2(1 BYTE),
    "CME_OFE_NOM_DOC_GEST_OFE"     VARCHAR2(500 BYTE),
    "CME_OFE_NOM_DOC_CONTRATACION" VARCHAR2(500 BYTE),
    "CME_OFE_ID_OFERTA_ORIGEN"     NUMBER(8,0),
    "CME_OFE_DESC_PUESTO"          VARCHAR2(200 BYTE),
    "CME_OFE_PAI_COD_1"            NUMBER(3,0),
    "CME_OFE_PAI_COD_2"            NUMBER(3,0),
    "CME_OFE_PAI_COD_3"            NUMBER(3,0),
    "CME_OFE_COD_TIT_1"            VARCHAR2(8 BYTE),
    "CME_OFE_COD_TIT_2"            VARCHAR2(8 BYTE),
    "CME_OFE_COD_TIT_3"            VARCHAR2(8 BYTE),
    "CME_OFE_FUNCIONES"            VARCHAR2(1000 BYTE),
    "CME_OFE_COD_IDIOMA_1"         VARCHAR2(8 BYTE),
    "CME_OFE_COD_IDIOMA_2"         VARCHAR2(8 BYTE),
    "CME_OFE_COD_IDIOMA_3"         VARCHAR2(8 BYTE),
    "CME_OFE_COD_NIV_IDI_1"        VARCHAR2(8 BYTE),
    "CME_OFE_COD_NIV_IDI_2"        VARCHAR2(8 BYTE),
    "CME_OFE_COD_NIV_IDI_3"        VARCHAR2(8 BYTE),
    "CME_OFE_COD_NIV_FORM"         VARCHAR2(8 BYTE),
    "CME_OFE_CIUDAD_DESTINO"       VARCHAR2(200 BYTE),
    "CME_OFE_DPTO"                 VARCHAR2(200 BYTE),
    "CME_OFE_MESES_CONTRATO"       NUMBER(6,0),
    "CME_OFE_COD_CAUSA_RENUNCIA"   VARCHAR2(8 BYTE),
    "FECHA_HIST"            DATE,
    CONSTRAINT "CME_HIST_OFER_PK2" PRIMARY KEY ("CME_OFE_ID") 
  );
COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_ID"
IS
  'Id de la tabla';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_ID_OFERTA"
IS
  'Id de la tabla';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_COD_OFERTA"
IS
  'Código de la oferta';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_COD_OFI_GEST"
IS
  'Código de la oficina de gestión';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_PREC"
IS
  'Precandidato (S/N)';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_PREC_NOM"
IS
  'Nombre precandidato';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_DIFUSION"
IS
  'Difusión (S/N)';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_FEC_DIFUSION"
IS
  'Fecha difusión';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_FEC_ENV_CAND"
IS
  'Fecha primer envío candidatos';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_NUM_TOT_CAND"
IS
  'Número total de l candidatos';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_DOC_GEST_OFE"
IS
  'Documento de gestión de la oferta';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_CONTRATACION"
IS
  'Contratación (S/N/Sin Datos)';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_MOT_CONTRATACION"
IS
  'Motivo de la NO contratación';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_COD_TIPO_NIF"
IS
  'Tipo de documento del contratado';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_NIF"
IS
  'Número de documento del contratado';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_NOMBRE"
IS
  'Nombre del contratado';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_APE1"
IS
  'Apellido 1 del contratado';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_APE2"
IS
  'Apellido 2 del contratado';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_EMAIL"
IS
  'email del contratado';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_TLF"
IS
  'Número de teléfono del contratado';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_FEC_NAC"
IS
  'Fecha de nacimiento del contratado';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_SEXO"
IS
  'Sexo del contratado';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_COD_TITULACION"
IS
  'Titulación del contratado';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_DOC_CONTRATACION"
IS
  'Documento de contratación';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_FEC_INI"
IS
  'Fecha de inicio del contrato';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_FEC_FIN"
IS
  'Fecha de fin del contrato';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_COD_GR_COT"
IS
  'Grupo de cotización del contratado';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_SALARIOB"
IS
  'Salario bruto + SS empresa';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_DIETAS_CONVENIO"
IS
  'Dietas según convenio';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_DIETAS_CONVOC"
IS
  'Dietas de la convocatoria';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_FEC_BAJA"
IS
  'Fecha de baja';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_COD_CAUSA_BAJA"
IS
  'Causa de baja';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_OBSERVACIONES"
IS
  'Observaciones';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_COD_PUESTO"
IS
  'FK al puesto';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_NUMEXP"
IS
  'Número del expediente';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_EXP_EJE"
IS
  'Ejercicio del expediente';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_ANO_TITULACION"
IS
  'Año Titulación';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_FL_SUSTITUTO"
IS
  'Flag que indica si la persona contratada es sustituto o no';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_NOM_DOC_GEST_OFE"
IS
  'Nombre del documento de gestión asociado.';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_NOM_DOC_CONTRATACION"
IS
  'Nombre del documento de contratación asociado.';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_ID_OFERTA_ORIGEN"
IS
  'ID de la oferta de la cual se van a coger parte de los datos: oferta de origen.';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_DESC_PUESTO"
IS
  'Descripción o nombre del puesto';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_PAI_COD_1"
IS
  'Código de país 1';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_PAI_COD_2"
IS
  'Código de país 2';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_PAI_COD_3"
IS
  'Código de país 3';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_COD_TIT_1"
IS
  'Código de titulación 1';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_COD_TIT_2"
IS
  'Código de titulación 2';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_COD_TIT_3"
IS
  'Código de titulación 3';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_FUNCIONES"
IS
  'Funciones del puesto';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_COD_IDIOMA_1"
IS
  'Código de idioma 1';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_COD_IDIOMA_2"
IS
  'Código de idioma 2';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_COD_IDIOMA_3"
IS
  'Código de idioma 3';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_COD_NIV_IDI_1"
IS
  'Nivel de idioma 1';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_COD_NIV_IDI_2"
IS
  'Nivel de idioma 2';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_COD_NIV_IDI_3"
IS
  'Nivel de idioma 3';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_COD_NIV_FORM"
IS
  'Nivel formativo';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_CIUDAD_DESTINO"
IS
  'Ciudad destino';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_DPTO"
IS
  'Departamento';
  COMMENT ON COLUMN "CME_HIST_OFERTA"."CME_OFE_COD_CAUSA_RENUNCIA"
IS
  'Codigo de causa por la que se renuncia al puesto';


CREATE TABLE "CME_HIST_JUSTIFICACION"
  (
    "CME_JUS_ID"    NUMBER(8,0) NOT NULL ENABLE,
	"CME_JUS_COD_TRAMITE"    NUMBER(8,0) NOT NULL ENABLE,
	"CME_JUS_ID_JUSTIFICACION" NUMBER(8,0) NOT NULL ENABLE,
    "CME_JUS_COD_PUESTO"       VARCHAR2(4 BYTE) NOT NULL ENABLE,
    "CME_JUS_NUMEXP"           VARCHAR2(30 BYTE) NOT NULL ENABLE,
    "CME_JUS_EXP_EJE"          NUMBER(4,0),
    "CME_JUS_ID_OFERTA"        NUMBER(8,0) NOT NULL ENABLE,
    "CME_JUS_COD_ESTADO"       VARCHAR2(8 BYTE),
    "CME_JUS_FL_VARIOS_TRAB"   VARCHAR2(1 BYTE),
    "CME_JUS_IMP_JUSTIFICADO"  NUMBER(10,2),
    "CME_JUS_SALARIOSUB"       NUMBER(10,2),
    "CME_JUS_DIETAS"           NUMBER(10,2),
    "CME_JUS_GASTOSGES"        NUMBER(10,2),
    "CME_JUS_BONIF"            NUMBER(10,2),
    "FECHA_HIST"            DATE,
    CONSTRAINT "CME_HIST_JUSTIFICACION_PK2" PRIMARY KEY ("CME_JUS_ID")
  ) ;
COMMENT ON COLUMN "CME_HIST_JUSTIFICACION"."CME_JUS_ID_JUSTIFICACION"
IS
  'ID de la tabla';
  COMMENT ON COLUMN "CME_HIST_JUSTIFICACION"."CME_JUS_ID"
IS
  'ID de la tabla';
  COMMENT ON COLUMN "CME_HIST_JUSTIFICACION"."CME_JUS_COD_PUESTO"
IS
  'Código del puesto';
  COMMENT ON COLUMN "CME_HIST_JUSTIFICACION"."CME_JUS_NUMEXP"
IS
  'Número de expediente';
  COMMENT ON COLUMN "CME_HIST_JUSTIFICACION"."CME_JUS_EXP_EJE"
IS
  'Ejercicio del expediente';
  COMMENT ON COLUMN "CME_HIST_JUSTIFICACION"."CME_JUS_ID_OFERTA"
IS
  'Id de la oferta';
  COMMENT ON COLUMN "CME_HIST_JUSTIFICACION"."CME_JUS_COD_ESTADO"
IS
  'Estado (Justificado/Renuncia)';
  COMMENT ON COLUMN "CME_HIST_JUSTIFICACION"."CME_JUS_FL_VARIOS_TRAB"
IS
  'Flag para indicar si ha dispuesto de varios trabajadores';
  COMMENT ON COLUMN "CME_HIST_JUSTIFICACION"."CME_JUS_IMP_JUSTIFICADO"
IS
  'Importe jusiticado';
  
 --SECUENCIAS
CREATE SEQUENCE SEQ_CME_HIST_SOLICITUD MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE ;
CREATE SEQUENCE SEQ_CME_HIST_OFERTA MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE ;
CREATE SEQUENCE SEQ_CME_HIST_JUSTIF MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE ;

   
  
  