create or replace
PROCEDURE CME_BORRADO_HISTORICO (expediente in varchar2, tramite IN VARCHAR2) IS

  --CODIGO VARCHAR2(100);
 
BEGIN      
  dbms_output.put_line('INICIO FUNCION CME_BORRADO_HISTORICO: '||to_char(SYSDATE,'yyyymmdd hh24:mi:ss')); 
  
  --INSERTAMOS SOLICITUD
DELETE FROM CME_HIST_OFERTA WHERE CME_OFE_NUMEXP=EXPEDIENTE AND CME_OFE_COD_TRAMITE = tramite;
commit;

DELETE FROM CME_HIST_PUESTO WHERE CME_PTO_NUMEXP=EXPEDIENTE AND CME_PTO_COD_TRAMITE = tramite;
commit;

DELETE FROM CME_HIST_JUSTIFICACION WHERE CME_JUS_NUMEXP=EXPEDIENTE AND CME_JUS_COD_TRAMITE = tramite;
commit;

dbms_output.put_line('FIN PROCESO CME_BORRADO_HISTORICO: '||to_char(SYSDATE,'yyyymmdd hh24:mi:ss'));   

END CME_BORRADO_HISTORICO;