
package es.altia.flexia.integracion.moduloexterno.melanbide54.cliente.consultaagencia;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "IWACCIFS", targetNamespace = "http://namespace.softwareag.com/entirex/xml/mapping", wsdlLocation = "http://svc.integracion.des.ejgv.jaso/ctxweb/LAN02ACSEPEConsulta?WSDL")
public class IWACCIFS_Service
    extends Service
{

    private final static URL IWACCIFS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(es.altia.flexia.integracion.moduloexterno.melanbide54.cliente.consultaagencia.IWACCIFS_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = es.altia.flexia.integracion.moduloexterno.melanbide54.cliente.consultaagencia.IWACCIFS_Service.class.getResource(".");
            url = new URL(baseUrl, "http://svc.integracion.des.ejgv.jaso/ctxweb/LAN02ACSEPEConsulta?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://svc.integracion.des.ejgv.jaso/ctxweb/LAN02ACSEPEConsulta?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        IWACCIFS_WSDL_LOCATION = url;
    }

    public IWACCIFS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IWACCIFS_Service() {
        super(IWACCIFS_WSDL_LOCATION, new QName("http://namespace.softwareag.com/entirex/xml/mapping", "IWACCIFS"));
    }

    /**
     * 
     * @return
     *     returns IESISPEPort
     */
    @WebEndpoint(name = "IESISPESOAP12Port")
    public IESISPEPort getIESISPESOAP12Port() {
        return super.getPort(new QName("http://namespace.softwareag.com/entirex/xml/mapping", "IESISPESOAP12Port"), IESISPEPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IESISPEPort
     */
    @WebEndpoint(name = "IESISPESOAP12Port")
    public IESISPEPort getIESISPESOAP12Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://namespace.softwareag.com/entirex/xml/mapping", "IESISPESOAP12Port"), IESISPEPort.class, features);
    }

}
