# -------------------------------------
# Parametros de envio de mail
# -------------------------------------
mail.enviar.entrada=S
mail.enviar.salida=S
mail.service.active=si
mail.from=noreply.flexia@altia.es
mail.mime.host=
mail.smtp.host=smtp2.udc.es
mail.smtp.auth=false
mail.smtp.port = 
mail.user=
mail.password=
mail.cc=
mail.bcc=
mail.error=Se ha producido un error en el envio de un correo electronico

#Contenido del asunto y del mensaje
mail.asuntoE=Alta telem\u00e1tica de registro de entrada: @ano@/@numero@
mail.asuntoS=Alta telem\u00e1tica de registro de salida: @ano@/@numero@
mail.contenidoE=Se ha dado de alta telem\u00e1ticamente el siguiente registro de entrada: \r \
A\u00f1o/N\u00famero: @ano@/@numero@ \r \
Fecha de registro: @fechaRegistro@ \r \
Interesados: @interesados@ \r \
Asunto: @asunto@ \r \
Extracto: @extracto@
mail.contenidoS=Se ha dado de alta telem\u00e1ticamente el siguiente registro de salida: \r \
A\u00f1o/N\u00famero: @ano@/@numero@ \r \
Fecha de registro: @fechaRegistro@ \r \
Interesados: @interesados@ \r \
Asunto: @asunto@ \r \
Extracto: @extracto@ 

