SQL:

--TABLA TRABAJADOR
CREATE TABLE  MELANBIDE65_TRABAJADOR(
  ID          NUMBER(8,0),
  NUM_EXP 	  VARCHAR2(30 BYTE),
  NUM_LINEA   NUMBER(5,0),
  APELLIDO1 VARCHAR2(50),
  APELLIDO2 VARCHAR2(50),
  NOMBRE      VARCHAR2(80 BYTE),
  SEXO        VARCHAR2(1 BYTE), 
  DNI         VARCHAR2(10 BYTE),
  TIPDISCPSI  NUMBER(5,0),
  TIPDISCFIS  NUMBER(5,0),
  TIPDISCSEN NUMBER(5,0),
  JORPARCPORC NUMBER(5,2),
  TIPJORNADA VARCHAR2(5),
  TIPCONTRATO VARCHAR2(5),
  
  CONSTRAINT MELANBIDE65_TRABAJADOR_PK PRIMARY KEY (ID)
);

COMMENT ON COLUMN  MELANBIDE65_TRABAJADOR.ID IS 'Índice secuencial y clave primaria de la tabla'; 
COMMENT ON COLUMN  MELANBIDE65_TRABAJADOR.NUM_LINEA IS 'Número de línea';
COMMENT ON COLUMN  MELANBIDE65_TRABAJADOR.NOMBRE IS 'Nombre del trabajador';
COMMENT ON COLUMN MELANBIDE65_TRABAJADOR.APELLIDO1 IS 'Primer apellido';
COMMENT ON COLUMN MELANBIDE65_TRABAJADOR.APELLIDO2 IS 'Segundo apellido';
COMMENT ON COLUMN  MELANBIDE65_TRABAJADOR.SEXO IS 'Sexo del trabajador. Valores posibles: 1 – Varón,  2 – Mujer';
COMMENT ON COLUMN  MELANBIDE65_TRABAJADOR.DNI IS 'Número de documento nacional de identidad del trabajador';
COMMENT ON COLUMN  MELANBIDE65_TRABAJADOR.TIPDISCPSI IS 'A) Tipo y Grado Disc. Psíquica (33% o más) Nº Página';
COMMENT ON COLUMN  MELANBIDE65_TRABAJADOR.TIPDISCFIS IS 'B) Tipo y Grado Disc. Física (65% o más) Nº Página';
COMMENT ON COLUMN MELANBIDE65_TRABAJADOR.TIPDISCSEN IS 'C) Tipo y Grado Disc. Sensorial (65% o más)';
COMMENT ON COLUMN MELANBIDE65_TRABAJADOR.JORPARCPORC IS 'Porcentaje de jornada a tiempo parcial';
COMMENT ON COLUMN MELANBIDE65_TRABAJADOR.TIPJORNADA IS 'Tipo de jornada';
COMMENT ON COLUMN MELANBIDE65_TRABAJADOR.TIPCONTRATO IS 'Tipo de contrato';
COMMENT ON TABLE   MELANBIDE65_TRABAJADOR IS 'Relación de trabajadores';


CREATE SEQUENCE SEQ_MELANBIDE65_TRABAJADOR MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1;
COMMIT;

--TABLA TECNICO
CREATE TABLE  MELANBIDE65_TECNICO(
  ID                NUMBER(8,0),
  NUM_EXP			VARCHAR2(30 BYTE),
  NUM_LINEA         NUMBER(5,0),
  NOMBRE            VARCHAR2(80 BYTE),
  APELLIDO1 VARCHAR2(50),
  APELLIDO2 VARCHAR2(50),
  DNI               VARCHAR2(10 BYTE),
  FECALTACONTINDEF  DATE,
  JORPARCPORC       NUMBER(5,2),
  TIPCONTRATO VARCHAR2(5),
  TIPJORNADA VARCHAR2(5),
  FECALTACONTINDEFTEMP DATE,
  FECBAJACONTINDEFTEMP DATE,
  
  CONSTRAINT MELANBIDE65_TECNICO_PK PRIMARY KEY (ID)
);

COMMENT ON COLUMN  MELANBIDE65_TECNICO.ID IS 'Índice secuencial y clave primaria de la tabla'; 
COMMENT ON COLUMN  MELANBIDE65_TECNICO.NUM_LINEA IS 'Número de línea';
COMMENT ON COLUMN  MELANBIDE65_TECNICO.NOMBRE IS 'Nombre del TECNICO';
COMMENT ON COLUMN MELANBIDE65_TECNICO.APELLIDO1 IS 'Primer apellido';
COMMENT ON COLUMN MELANBIDE65_TECNICO.APELLIDO2 IS 'Segundo apellido';
COMMENT ON COLUMN  MELANBIDE65_TECNICO.DNI IS 'Número de documento nacional de identidad del TECNICO';
COMMENT ON COLUMN  MELANBIDE65_TECNICO.FECALTACONTINDEF IS 'Fecha de alta del contrato';
COMMENT ON COLUMN  MELANBIDE65_TECNICO.JORPARCPORC IS 'B) Jornada Laboral. Tiempo Parcial. % Jornada';
COMMENT ON COLUMN MELANBIDE65_TECNICO.TIPCONTRATO IS 'Tipo de contrato';
COMMENT ON COLUMN MELANBIDE65_TECNICO.TIPJORNADA IS 'Tipo de jornada';
COMMENT ON COLUMN MELANBIDE65_TECNICO.FECALTACONTINDEFTEMP IS 'Fecha de alta del contrato TEMPORAL';
COMMENT ON COLUMN MELANBIDE65_TECNICO.FECBAJACONTINDEFTEMP IS 'Fecha de baja del contrato TEMPORAL';

COMMENT ON TABLE   MELANBIDE65_TECNICO IS 'Relación de técnicos';

CREATE SEQUENCE SEQ_MELANBIDE65_TECNICO MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1;
COMMIT;

--TABLA ENCARGADO
CREATE TABLE  MELANBIDE65_ENCARGADO(
  ID                NUMBER(8,0),
  NUM_EXP			VARCHAR2(30 BYTE),
  NUM_LINEA         NUMBER(5,0),
  NOMBRE            VARCHAR2(80 BYTE),
  APELLIDO1 VARCHAR2(50),
  APELLIDO2 VARCHAR2(50),
  DNI               VARCHAR2(10 BYTE),
  FECALTACONTINDEF  DATE,
  JORPARCPORC       NUMBER(5,2),
  TIPCONTRATO VARCHAR2(5),
  TIPJORNADA VARCHAR2(5),
  FECALTACONTINDEFTEMP DATE,
  FECBAJACONTINDEFTEMP DATE,
  
  
  CONSTRAINT MELANBIDE65_ENCARGADO_PK PRIMARY KEY (ID)
);

COMMENT ON COLUMN  MELANBIDE65_ENCARGADO.ID IS 'Índice secuencial y clave primaria de la tabla'; 
COMMENT ON COLUMN  MELANBIDE65_ENCARGADO.NUM_LINEA IS 'Número de línea';
COMMENT ON COLUMN  MELANBIDE65_ENCARGADO.NOMBRE IS 'Nombre del ENCARGADO';
COMMENT ON COLUMN MELANBIDE65_ENCARGADO.APELLIDO1 IS 'Primer apellido';
COMMENT ON COLUMN MELANBIDE65_ENCARGADO.APELLIDO2 IS 'Segundo apellido';
COMMENT ON COLUMN  MELANBIDE65_ENCARGADO.DNI IS 'Número de documento nacional de identidad del ENCARGADO';
COMMENT ON COLUMN  MELANBIDE65_ENCARGADO.FECALTACONTINDEF IS 'Fecha de alta del contrato';
COMMENT ON COLUMN  MELANBIDE65_ENCARGADO.JORPARCPORC IS 'B) Jornada Laboral. Tiempo Parcial. % Jornada';
COMMENT ON COLUMN MELANBIDE65_ENCARGADO.TIPCONTRATO IS 'Tipo de contrato';
COMMENT ON COLUMN MELANBIDE65_ENCARGADO.TIPJORNADA IS 'Tipo de jornada';
COMMENT ON COLUMN MELANBIDE65_ENCARGADO.FECALTACONTINDEFTEMP IS 'Fecha de alta del contrato TEMPORAL';
COMMENT ON COLUMN MELANBIDE65_ENCARGADO.FECBAJACONTINDEFTEMP IS 'Fecha de baja del contrato TEMPORAL';
COMMENT ON TABLE   MELANBIDE65_ENCARGADO IS 'Relación de encargados';

CREATE SEQUENCE SEQ_MELANBIDE65_ENCARGADO MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1;
COMMIT;