 

Insert into E_DES (DES_COD,DES_NOM) values ('PEIA','TIPO ACTIVIDAD - IKER');

Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM,DES_VAL_ESTADO) values ('PEIA','PI','PERSONAL INVESTIGADOR (I+D+i)|IKERTZAILEAK (I+G+b)','A');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM,DES_VAL_ESTADO) values ('PEIA','PA','PERSONAL DE APOYO (I+D+i)|LAGUNTZAKO LANGILEAK (I+G+b)','A');


insert into e_des (des_cod,des_nom) values ('CIOI','INVESTIGACION INNOVACION IKER');

insert into e_des_val (des_cod,des_val_cod,des_nom,des_val_estado) values ('CIOI','S','SANIDAD|OSASUNA','A');
insert into e_des_val (des_cod,des_val_cod,des_nom,des_val_estado) values ('CIOI','TE','TRANSICION ECOLOGICA|TRANTSIZIO EKOLOGIKOA','A');
insert into e_des_val (des_cod,des_val_cod,des_nom,des_val_estado) values ('CIOI','EV','ECONOMIA VERDE (ENERGIAS RENOVABLES, EFICIENCIA ENERGETICA, TRATAMIENTO DE AGUAS Y RESIDUOS E INDUSTRIA AGROALIMENTARIA|EKONOMIA BERDEA (ENERGIA BERRIZTAGARRIAK, ENERGIA-ERAGINKORTASUNA, UREN ETA HONDAKINEN TRATAMENDUA ETA NEKAZARITZAKO ELIKAGAIEN INDUSTRIA)','A');
insert into e_des_val (des_cod,des_val_cod,des_nom,des_val_estado) values ('CIOI','DS','DIGITALIZACION DE SERVICIOS E INGENIERIA DE DATOS O DATA SCIENCE|ZERBITZUEN DIGITALIZAZIOA ETA DATUEN INGENIARITZA EDO DATA SCIENCE','A');
insert into e_des_val (des_cod,des_val_cod,des_nom,des_val_estado) values ('CIOI','PS','PROYECTOS DE INVESTIGACION DESTINADOS A LAS AREAS SOCIALES|GIZARTE-ARLOETARA BIDERATUTAKO IKERKETA-PROIEKTUAK','A');
insert into e_des_val (des_cod,des_val_cod,des_nom,des_val_estado) values ('CIOI','PC','PROYECTOS DE INVESTIGACION DESTINADOS A LAS AREAS SOCIALES CULTURALES|GIZARTE ETA KULTUR ARLOETARAKO IKERKETA-PROIEKTUAK','A');
insert into e_des_val (des_cod,des_val_cod,des_nom,des_val_estado) values ('CIOI','PA','PROYECTOS DE INVESTIGACION DESTINADOS A LAS AREAS ARTISTICAS|ARLO ARTISTIKOETARA BIDERATUTAKO IKERKETA-PROIEKTUAK','A');
insert into e_des_val (des_cod,des_val_cod,des_nom,des_val_estado) values ('CIOI','PO','PROYECTOS DE INVESTIGACION DESTINADOS A OTROS AMBITOS DE ESTUDIO|BESTE IKERKETA-EREMU BATZUETARA BIDERATUTAKO IKERKETA-PROIEKTUAK','A');