--------------------------------------------------------
--  Create Table MELANBIDE86_CONTRATACION
--------------------------------------------------------

  CREATE TABLE MELANBIDE86_CONTRATACION 
   (	ID NUMBER(8,0), 
	NUM_EXP VARCHAR2(20 BYTE), 
	NUM_PUESTO NUMBER(4,0),
	DENOMPUESTO1 VARCHAR2(500 BYTE), 
	ACTDES1 VARCHAR2(2 BYTE), 
	TITULACION1 VARCHAR2(150 BYTE), 
	TIPCONT1 VARCHAR2(150 BYTE), 	
	DURCONTRATO1 NUMBER(4,0),
	GRUPOCOTIZ1 VARCHAR2(2 BYTE), 	
	COSTESALARIAL1 NUMBER(8,2),
	SUBVSOLICITADA1 NUMBER(8,2),
	CAINVINN1 VARCHAR2(30 BYTE)
   );

   COMMENT ON COLUMN MELANBIDE86_CONTRATACION.ID IS 'Identificador Secuencial';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION.NUM_EXP IS 'Número de Expediente';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION.NUM_PUESTO IS 'Número de Puesto';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION.DENOMPUESTO1 IS 'Denominación del Puesto';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION.ACTDES1 IS 'Actividad a Desarrollar';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION.TITULACION1 IS 'Titulación Requerida';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION.TIPCONT1 IS 'Tipo De Contrato';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION.DURCONTRATO1 IS 'Duración Contrato En Meses';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION.GRUPOCOTIZ1 IS 'Grupo Cotización';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION.COSTESALARIAL1 IS 'Coste Salarial';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION.SUBVSOLICITADA1 IS 'Subvención Solicitada';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION.CAINVINN1 IS 'Campo Investigacion O Innovacion';

--------------------------------------------------------
--  Constraints for Table MELANBIDE86_CONTRATACION
--------------------------------------------------------
  ALTER TABLE MELANBIDE86_CONTRATACION ADD PRIMARY KEY (ID);
  
--------------------------------------------------------
--  DDL for Sequence SEQ_MELANBIDE86_CONTRATACION
--------------------------------------------------------

   CREATE SEQUENCE  SEQ_MELANBIDE86_CONTRATACION  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
   
------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------
--  Create Table MELANBIDE86_CONTRATACION_INI
--------------------------------------------------------

  CREATE TABLE MELANBIDE86_CONTRATACION_INI 
   (	ID NUMBER(8,0), 
	NUM_EXP VARCHAR2(20 BYTE), 
	NUM_PUESTO NUMBER(4,0),
	NOFERTA2 VARCHAR2(50),
	NOMBRE2 VARCHAR2(100),
	APELLIDO12 VARCHAR2(50),
	APELLIDO22 VARCHAR2(50),
	DNINIE2 VARCHAR2(15),
	SEXO2 VARCHAR2(1),
	DENOMPUESTO2 VARCHAR2(500 BYTE), 
	ACTDES2 VARCHAR2(2 BYTE), 
	TITULACION2 VARCHAR2(150 BYTE), 
	TIPCONT2 VARCHAR2(150 BYTE), 	
	DURCONTRATO2 NUMBER(4,0),
	GRUPOCOTIZ2 VARCHAR2(2 BYTE),
	FECHANACIMIENTO2 DATE,
	FECHAINICIO2 DATE,
	EDAD2 NUMBER(2),
	RETRIBUCIONBRUTA2 NUMBER(8,2),
	CAINVINN2 VARCHAR2(30 BYTE)
   );

   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_INI.ID IS 'Identificador Secuencial';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_INI.NUM_EXP IS 'Número de Expediente';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_INI.NUM_PUESTO IS 'Número de Puesto';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_INI.NOFERTA2 IS 'Número Oferta';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_INI.NOMBRE2 IS 'Nombre';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_INI.APELLIDO12 IS 'Primer Apellido';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_INI.APELLIDO22 IS 'Segundo Apellido';   
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_INI.DNINIE2 IS 'DNI/NIE';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_INI.SEXO2 IS 'Sexo';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_INI.DENOMPUESTO2 IS 'Denominación del Puesto Inicio';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_INI.ACTDES2 IS 'Actividad a Desarrollar Inicio';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_INI.TITULACION2 IS 'Titulación Requerida Inicio';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_INI.TIPCONT2 IS 'Tipo De Contrato Inicio';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_INI.DURCONTRATO2 IS 'Duración Contrato En Meses Inicio';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_INI.GRUPOCOTIZ2 IS 'Grupo Cotización Inicio';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_INI.FECHANACIMIENTO2 IS 'Fecha de Nacimiento Inicio';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_INI.FECHAINICIO2 IS 'Fecha de Inicio Contrato Inicio';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_INI.EDAD2 IS 'Edad';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_INI.RETRIBUCIONBRUTA2 IS 'Retribución Bruta';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_INI.CAINVINN2 IS 'Campo Investigacion o Innovacion Inicio';

--------------------------------------------------------
--  Constraints for Table MELANBIDE86_CONTRATACION_INI
--------------------------------------------------------
  ALTER TABLE MELANBIDE86_CONTRATACION_INI ADD PRIMARY KEY (ID);
  
--------------------------------------------------------
--  DDL for Sequence SEQ_MELANBIDE86_CONTRATA_INI
--------------------------------------------------------

   CREATE SEQUENCE  SEQ_MELANBIDE86_CONTRATA_INI  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
   
------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------
--  Create Table MELANBIDE86_CONTRATACION_FIN
--------------------------------------------------------

  CREATE TABLE MELANBIDE86_CONTRATACION_FIN 
   (	ID NUMBER(8,0), 
	NUM_EXP VARCHAR2(20 BYTE), 
	NUM_PUESTO NUMBER(4,0),
	NOMBRE3 VARCHAR2(100),
	APELLIDO13 VARCHAR2(50),
	APELLIDO23 VARCHAR2(50),
	DNINIE3 VARCHAR2(15),
	DURCONTRATO3 NUMBER(4,0),
	FECHAINICIO3 DATE,
	FECHAFIN3 DATE,
	COSTESALARIAL3 NUMBER(8,2),
	COSTESSS3 NUMBER(8,2),
	COSTETOTALREAL3 NUMBER(8,2),
	SUBVCONCEDIDALAN3 NUMBER(8,2)
   );

   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_FIN.ID IS 'Identificador Secuencial';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_FIN.NUM_EXP IS 'Número de Expediente';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_FIN.NUM_PUESTO IS 'Número de Puesto';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_FIN.NOMBRE3 IS 'Nombre';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_FIN.APELLIDO13 IS 'Primer Apellido';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_FIN.APELLIDO23 IS 'Segundo Apellido';   
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_FIN.DNINIE3 IS 'DNI/NIE';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_FIN.DURCONTRATO3 IS 'Duración Contrato En Meses Fin';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_FIN.FECHAINICIO3 IS 'Fecha de Inicio Contrato Fin';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_FIN.FECHAFIN3 IS 'Fecha Fin Contrato';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_FIN.COSTESALARIAL3 IS 'Coste Salarial';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_FIN.COSTESSS3 IS 'Coste Seguridad Social';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_FIN.COSTETOTALREAL3 IS 'Coste Total Real';
   COMMENT ON COLUMN MELANBIDE86_CONTRATACION_FIN.SUBVCONCEDIDALAN3 IS 'Subvención Concedida Por Lanbide';
   
--------------------------------------------------------
--  Constraints for Table MELANBIDE86_CONTRATACION_FIN
--------------------------------------------------------
  ALTER TABLE MELANBIDE86_CONTRATACION_FIN ADD PRIMARY KEY (ID);
  
--------------------------------------------------------
--  DDL for Sequence SEQ_MELANBIDE86_CONTRATA_FIN
--------------------------------------------------------

   CREATE SEQUENCE  SEQ_MELANBIDE86_CONTRATA_FIN  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
      