--------------------------------------------------------
--  DDL for Table ECA_RESUMEN
--------------------------------------------------------

CREATE TABLE ECA14_RESUMEN 
(
  ECA_COD_RESUMEN NUMBER(8, 0) NOT NULL 
, ECA_RES_SOLICITUD NUMBER(8, 0) 
, ECA_RES_SUB_PRIV NUMBER(10, 2) 
, ECA_RES_SUB_PUB NUMBER(10, 2) 
, ECA_RES_TOT_SUBV NUMBER(10, 2) 
, CONSTRAINT ECA14_RESUMEN_PK PRIMARY KEY 
  (
    ECA_COD_RESUMEN 
  )
  ENABLE 
);

--------------------------------------------------------
--  DDL for Table ECA_RES_PREPARADORES
--------------------------------------------------------

  CREATE TABLE ECA14_RES_PREPARADORES
   (	
    ECA_RES_PREPARADORES_COD NUMBER, 
	ECA_NUMEXP VARCHAR2(30 BYTE), 
	ECA_JUS_PREPARADORES_COD NUMBER, 
	NIF VARCHAR2(10 BYTE), 
	NOMBRE VARCHAR2(200 BYTE), 
	GASTOS_SALARIALES_SOLICITADOS NUMBER(8,2), 
	GASTOS_SALARIALES_CONCEDIDOS NUMBER(8,2), 
	GASTOS_SALARIALES_JUSTIFICADOS NUMBER(8,2), 
	IMPORTE_SEGUIMIENTOS NUMBER(8,2), 
	IMPORTE_INS_CONCEDIDO NUMBER(8,2), 
	IMPORTE_INS_JUSTIFICADAS NUMBER(8,2), 
	IMPORTE_INSERCIONES NUMBER(8,2), 
	IMPORTE_SEG_INSERCIONES NUMBER(8,2), 
	A_PAGAR NUMBER(8,2), 
	FEC_SYSDATE DATE
   );
   
--------------------------------------------------------
--  DDL for Table ECA_RES_PROSPECTORES
--------------------------------------------------------

  CREATE TABLE ECA14_RES_PROSPECTORES
   (	
    ECA_RES_PROSPECTORES_COD NUMBER, 
	ECA_NUMEXP VARCHAR2(30 BYTE), 
	ECA_JUS_PROSPECTORES_COD NUMBER, 
	NIF VARCHAR2(10 BYTE), 
	NOMBRE VARCHAR2(200 BYTE), 
	GASTOS_SALARIALES_SOLICITADOS NUMBER(8,2), 
	GASTOS_SALARIALES_CONCEDIDOS NUMBER(8,2), 
	GASTOS_SALARIALES_JUSTIFICADOS NUMBER(8,2), 
	VISITAS_CONCEDIDAS NUMBER, 
	VISITAS_JUSTIFICADAS NUMBER, 
	IMPORTE_VISITAS NUMBER(8,2), 
	A_PAGAR NUMBER(8,2), 
	FEC_SYSDATE DATE
   );

