
package es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "Exception", targetNamespace = "http://ws.service.ws.w75b.ejie.com/")
public class Exception_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.Exception faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public Exception_Exception(String message, es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.Exception faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public Exception_Exception(String message, es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.Exception faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.Exception
     */
    public es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.Exception getFaultInfo() {
        return faultInfo;
    }

}
