
package es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "W75bServiceOpc2", targetNamespace = "http://ws.service.ws.w75b.ejie.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface W75BServiceOpc2 {


    /**
     * 
     * @param w75BSeguridadVO
     * @param w75BResolucionVO
     * @return
     *     returns es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.W75BResultadoResolucionVO
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "grabarResolucion", targetNamespace = "http://ws.service.ws.w75b.ejie.com/", className = "es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.GrabarResolucion")
    @ResponseWrapper(localName = "grabarResolucionResponse", targetNamespace = "http://ws.service.ws.w75b.ejie.com/", className = "es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.GrabarResolucionResponse")
    public W75BResultadoResolucionVO grabarResolucion(
        @WebParam(name = "W75bSeguridadVO", targetNamespace = "")
        W75BSeguridadVO w75BSeguridadVO,
        @WebParam(name = "W75bResolucionVO", targetNamespace = "")
        W75BResolucionVO w75BResolucionVO)
        throws Exception_Exception
    ;

    /**
     * 
     * @param w75BSeguridadVO
     * @param w75BResolucionVO
     * @return
     *     returns es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.W75BResultadoResolucionVO
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "grabarPago", targetNamespace = "http://ws.service.ws.w75b.ejie.com/", className = "es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.GrabarPago")
    @ResponseWrapper(localName = "grabarPagoResponse", targetNamespace = "http://ws.service.ws.w75b.ejie.com/", className = "es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.GrabarPagoResponse")
    public W75BResultadoResolucionVO grabarPago(
        @WebParam(name = "W75bSeguridadVO", targetNamespace = "")
        W75BSeguridadVO w75BSeguridadVO,
        @WebParam(name = "W75bResolucionVO", targetNamespace = "")
        W75BResolucionVO w75BResolucionVO)
        throws Exception_Exception
    ;

    /**
     * 
     * @param w75BSeguridadVO
     * @param idReserva
     * @return
     *     returns es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.W75BResultadoReservaVO
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eliminarReserva", targetNamespace = "http://ws.service.ws.w75b.ejie.com/", className = "es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.EliminarReserva")
    @ResponseWrapper(localName = "eliminarReservaResponse", targetNamespace = "http://ws.service.ws.w75b.ejie.com/", className = "es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.EliminarReservaResponse")
    public W75BResultadoReservaVO eliminarReserva(
        @WebParam(name = "W75bSeguridadVO", targetNamespace = "")
        W75BSeguridadVO w75BSeguridadVO,
        @WebParam(name = "idReserva", targetNamespace = "")
        String idReserva)
        throws Exception_Exception
    ;

    /**
     * 
     * @param w75BSeguridadVO
     * @param w75BReservaVO
     * @return
     *     returns es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.W75BResultadoReservaVO
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "grabarReserva", targetNamespace = "http://ws.service.ws.w75b.ejie.com/", className = "es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.GrabarReserva")
    @ResponseWrapper(localName = "grabarReservaResponse", targetNamespace = "http://ws.service.ws.w75b.ejie.com/", className = "es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.GrabarReservaResponse")
    public W75BResultadoReservaVO grabarReserva(
        @WebParam(name = "W75bSeguridadVO", targetNamespace = "")
        W75BSeguridadVO w75BSeguridadVO,
        @WebParam(name = "W75bReservaVO", targetNamespace = "")
        W75BReservaVO w75BReservaVO)
        throws Exception_Exception
    ;

    /**
     * 
     * @param w75BSeguridadVO
     * @param w75BTerceroIkusVO
     * @return
     *     returns es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.W75BResultadoTerceroIkusVO
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recuperarTerceroIkus", targetNamespace = "http://ws.service.ws.w75b.ejie.com/", className = "es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.RecuperarTerceroIkus")
    @ResponseWrapper(localName = "recuperarTerceroIkusResponse", targetNamespace = "http://ws.service.ws.w75b.ejie.com/", className = "es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.RecuperarTerceroIkusResponse")
    public W75BResultadoTerceroIkusVO recuperarTerceroIkus(
        @WebParam(name = "W75bSeguridadVO", targetNamespace = "")
        W75BSeguridadVO w75BSeguridadVO,
        @WebParam(name = "W75bTerceroIkusVO", targetNamespace = "")
        W75BTerceroIkusVO w75BTerceroIkusVO)
        throws Exception_Exception
    ;

    /**
     * 
     * @param w75BSeguridadVO
     * @param idLineaAyuda
     * @param idFormaJuridica
     * @param ejercicioContable
     * @param idTerritorio
     * @param numExpediente
     * @return
     *     returns es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.W75BResultadoAplicacionVO
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recuperarAplicacion", targetNamespace = "http://ws.service.ws.w75b.ejie.com/", className = "es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.RecuperarAplicacion")
    @ResponseWrapper(localName = "recuperarAplicacionResponse", targetNamespace = "http://ws.service.ws.w75b.ejie.com/", className = "es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.RecuperarAplicacionResponse")
    public W75BResultadoAplicacionVO recuperarAplicacion(
        @WebParam(name = "W75bSeguridadVO", targetNamespace = "")
        W75BSeguridadVO w75BSeguridadVO,
        @WebParam(name = "idLineaAyuda", targetNamespace = "")
        String idLineaAyuda,
        @WebParam(name = "numExpediente", targetNamespace = "")
        String numExpediente,
        @WebParam(name = "ejercicioContable", targetNamespace = "")
        String ejercicioContable,
        @WebParam(name = "idTerritorio", targetNamespace = "")
        String idTerritorio,
        @WebParam(name = "idFormaJuridica", targetNamespace = "")
        String idFormaJuridica)
        throws Exception_Exception
    ;

    /**
     * 
     * @param w75BSeguridadVO
     * @param idLineaAyuda
     * @param ejercicioContable
     * @return
     *     returns es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.W75BResultadoListaAplicacionesVO
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recuperarListaAplicaciones", targetNamespace = "http://ws.service.ws.w75b.ejie.com/", className = "es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.RecuperarListaAplicaciones")
    @ResponseWrapper(localName = "recuperarListaAplicacionesResponse", targetNamespace = "http://ws.service.ws.w75b.ejie.com/", className = "es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.RecuperarListaAplicacionesResponse")
    public W75BResultadoListaAplicacionesVO recuperarListaAplicaciones(
        @WebParam(name = "W75bSeguridadVO", targetNamespace = "")
        W75BSeguridadVO w75BSeguridadVO,
        @WebParam(name = "idLineaAyuda", targetNamespace = "")
        String idLineaAyuda,
        @WebParam(name = "ejercicioContable", targetNamespace = "")
        String ejercicioContable)
        throws Exception_Exception
    ;

    /**
     * 
     * @param w75BSeguridadVO
     * @param idLineaAyuda
     * @return
     *     returns es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.W75BResultadoLineaAyudaVO
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recuperarEjercicio", targetNamespace = "http://ws.service.ws.w75b.ejie.com/", className = "es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.RecuperarEjercicio")
    @ResponseWrapper(localName = "recuperarEjercicioResponse", targetNamespace = "http://ws.service.ws.w75b.ejie.com/", className = "es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.RecuperarEjercicioResponse")
    public W75BResultadoLineaAyudaVO recuperarEjercicio(
        @WebParam(name = "W75bSeguridadVO", targetNamespace = "")
        W75BSeguridadVO w75BSeguridadVO,
        @WebParam(name = "idLineaAyuda", targetNamespace = "")
        String idLineaAyuda)
        throws Exception_Exception
    ;

    /**
     * 
     * @param nifTercero
     * @param w75BSeguridadVO
     * @return
     *     returns es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.W75BResultadoValidarTerceroIkusVO
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validarTerceroIkus", targetNamespace = "http://ws.service.ws.w75b.ejie.com/", className = "es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.ValidarTerceroIkus")
    @ResponseWrapper(localName = "validarTerceroIkusResponse", targetNamespace = "http://ws.service.ws.w75b.ejie.com/", className = "es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.ValidarTerceroIkusResponse")
    public W75BResultadoValidarTerceroIkusVO validarTerceroIkus(
        @WebParam(name = "W75bSeguridadVO", targetNamespace = "")
        W75BSeguridadVO w75BSeguridadVO,
        @WebParam(name = "nifTercero", targetNamespace = "")
        String nifTercero)
        throws Exception_Exception
    ;

}
