--------------------------------------------------------
--  DDL for Table MELANBIDE67_PUESTOS_TRAB
--------------------------------------------------------
  CREATE TABLE "MELANBIDE67_PUESTOS_TRAB" 
   (	"CODIGO" VARCHAR2(10 BYTE), 
	"DESCRIPCION" VARCHAR2(500 BYTE), 
	"HOMBRE" NUMBER(8,0), 
	"MUJER" NUMBER(8,0), 
	"TOTAL" NUMBER(15,0), 
	"PORCENTAJE" NUMBER(5,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLBPRU_DBS1" ;
   COMMENT ON COLUMN "MELANBIDE67_PUESTOS_TRAB"."CODIGO" IS 'Código del puesto de trabajo';
   COMMENT ON COLUMN "MELANBIDE67_PUESTOS_TRAB"."DESCRIPCION" IS 'Descripción del puesto de trabajo';
   COMMENT ON COLUMN "MELANBIDE67_PUESTOS_TRAB"."HOMBRE" IS 'Número de puestos de trabajo ocupados por hombres';
   COMMENT ON COLUMN "MELANBIDE67_PUESTOS_TRAB"."MUJER" IS 'Número de puestos de trabajo ocupados por mujeres';
   COMMENT ON COLUMN "MELANBIDE67_PUESTOS_TRAB"."TOTAL" IS 'Número total de puestos de trabajo';
   COMMENT ON COLUMN "MELANBIDE67_PUESTOS_TRAB"."PORCENTAJE" IS 'Porcentaje de participación de mujeres en el puesto de trabajo';
REM INSERTING into MELANBIDE67_PUESTOS_TRAB
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index MELANBIDE67_PUESTOS_TRAB_PK
--------------------------------------------------------
  CREATE UNIQUE INDEX "MELANBIDE67_PUESTOS_TRAB_PK" ON "MELANBIDE67_PUESTOS_TRAB" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLBPRU_DBS1" ;
--------------------------------------------------------
--  Constraints for Table MELANBIDE67_PUESTOS_TRAB
--------------------------------------------------------
  ALTER TABLE "MELANBIDE67_PUESTOS_TRAB" ADD CONSTRAINT "MELANBIDE67_PUESTOS_TRAB_PK" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLBPRU_DBS1"  ENABLE;
  ALTER TABLE "MELANBIDE67_PUESTOS_TRAB" MODIFY ("PORCENTAJE" NOT NULL ENABLE);
  ALTER TABLE "MELANBIDE67_PUESTOS_TRAB" MODIFY ("TOTAL" NOT NULL ENABLE);
  ALTER TABLE "MELANBIDE67_PUESTOS_TRAB" MODIFY ("MUJER" NOT NULL ENABLE);
  ALTER TABLE "MELANBIDE67_PUESTOS_TRAB" MODIFY ("HOMBRE" NOT NULL ENABLE);
  ALTER TABLE "MELANBIDE67_PUESTOS_TRAB" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "MELANBIDE67_PUESTOS_TRAB" MODIFY ("CODIGO" NOT NULL ENABLE);

