ALTER TABLE NOTIFICACION ADD (COD_NOTIFICACION_PLATEA VARCHAR2(60));
ALTER TABLE NOTIFICACION ADD (FECHA_SOL_ENVIO DATE);
ALTER TABLE NOTIFICACION ADD (NUM_INTENTOS NUMBER(1,0), RESPUESTA_LLAMADA VARCHAR2 (1000));
ALTER TABLE NOTIFICACION ADD (RESULTADO VARCHAR2(1));