--------------------------------------------------------
-- Archivo creado  - martes-marzo-31-2015   
--------------------------------------------------------
REM INSERTING into IDEN_ERR
SET DEFINE OFF;

Insert into IDEN_ERR (IDEN_ERR_ID,IDEN_ERR_DESC_C,IDEN_ERR_DESC,IDEN_ERR_TIPO,IDEN_ERR_CRIT,IDEN_ERR_MEN_AVISO,IDEN_ERR_MAILS,IDEN_ERR_ACC) values ('NOTIFICACIONES_001','Error al guardar la notificación','Error al guardar la notificación','2','1',null,null,'Revisar traza de error: posible fallo de conexión');
Insert into IDEN_ERR (IDEN_ERR_ID,IDEN_ERR_DESC_C,IDEN_ERR_DESC,IDEN_ERR_TIPO,IDEN_ERR_CRIT,IDEN_ERR_MEN_AVISO,IDEN_ERR_MAILS,IDEN_ERR_ACC) values ('NOTIFICACIONES_002','Error al enviar notificacion','Error al enviar la notificación','2','1',null,null,'Revisar la traza de error: posible fallo de conexión');
Insert into IDEN_ERR (IDEN_ERR_ID,IDEN_ERR_DESC_C,IDEN_ERR_DESC,IDEN_ERR_TIPO,IDEN_ERR_CRIT,IDEN_ERR_MEN_AVISO,IDEN_ERR_MAILS,IDEN_ERR_ACC) values ('NOTIFICACIONES_003','El documento de la notificación no ha sido enviado','El documento de la notificación no ha sido enviado','2','1',null,null,'Revisar la traza de error: posible retraso en el envío de los documentos');
Insert into IDEN_ERR (IDEN_ERR_ID,IDEN_ERR_DESC_C,IDEN_ERR_DESC,IDEN_ERR_TIPO,IDEN_ERR_CRIT,IDEN_ERR_MEN_AVISO,IDEN_ERR_MAILS,IDEN_ERR_ACC) values ('NOTIFICACIONES_004','Error en adaptadores al enviar una notificacion','Error en adaptadores al enviar una notificacion','2','1',null,null,'Revisar la traza de error: posible fallo en el envio de datos');
Insert into IDEN_ERR (IDEN_ERR_ID,IDEN_ERR_DESC_C,IDEN_ERR_DESC,IDEN_ERR_TIPO,IDEN_ERR_CRIT,IDEN_ERR_MEN_AVISO,IDEN_ERR_MAILS,IDEN_ERR_ACC) values ('NOTIFICACIONES_005','Error al obtener la notificacion','Error al obtener la notificacion','2','1',null,null,'Revisar la traza de error: posible fallo de conexión');
Insert into IDEN_ERR (IDEN_ERR_ID,IDEN_ERR_DESC_C,IDEN_ERR_DESC,IDEN_ERR_TIPO,IDEN_ERR_CRIT,IDEN_ERR_MEN_AVISO,IDEN_ERR_MAILS,IDEN_ERR_ACC) values ('NOTIFICACIONES_006','Error al comprobar si existen documentos firmados','Error al comprobar si existen documentos firmados','2','1',null,null,'Revisar la traza de error: posible fallo de conexión');
Insert into IDEN_ERR (IDEN_ERR_ID,IDEN_ERR_DESC_C,IDEN_ERR_DESC,IDEN_ERR_TIPO,IDEN_ERR_CRIT,IDEN_ERR_MEN_AVISO,IDEN_ERR_MAILS,IDEN_ERR_ACC) values ('NOTIFICACIONES_007','Error al comprobar la notificación de la firma','Error al comprobar la notificación de la firma','2','1',null,null,'Revisar la traza de error: posible fallo de conexión');
Insert into IDEN_ERR (IDEN_ERR_ID,IDEN_ERR_DESC_C,IDEN_ERR_DESC,IDEN_ERR_TIPO,IDEN_ERR_CRIT,IDEN_ERR_MEN_AVISO,IDEN_ERR_MAILS,IDEN_ERR_ACC) values ('NOTIFICACIONES_008','Error al verificar la firma','Error al verificar la firma','2','1',null,null,'Revisar la traza de error: posible fallo de conexión');
Insert into IDEN_ERR (IDEN_ERR_ID,IDEN_ERR_DESC_C,IDEN_ERR_DESC,IDEN_ERR_TIPO,IDEN_ERR_CRIT,IDEN_ERR_MEN_AVISO,IDEN_ERR_MAILS,IDEN_ERR_ACC) values ('NOTIFICACIONES_009','Error al guardar el estado de la notificación','Error al guardar el estado de la notificación','2','1',null,null,'Revisar la traza de error: posible fallo de conexión');
Insert into IDEN_ERR (IDEN_ERR_ID,IDEN_ERR_DESC_C,IDEN_ERR_DESC,IDEN_ERR_TIPO,IDEN_ERR_CRIT,IDEN_ERR_MEN_AVISO,IDEN_ERR_MAILS,IDEN_ERR_ACC) values ('NOTIFICACIONES_010','Error al actualizar la notificación','Error al actualizar la notificación','2','1',null,null,'Revisar la traza de error: posible fallo de conexión');
Insert into IDEN_ERR (IDEN_ERR_ID,IDEN_ERR_DESC_C,IDEN_ERR_DESC,IDEN_ERR_TIPO,IDEN_ERR_CRIT,IDEN_ERR_MEN_AVISO,IDEN_ERR_MAILS,IDEN_ERR_ACC) values ('NOTIFICACIONES_011','Error al crear la notificación defecto','Error al crear la notificación defecto','2','1',null,null,'Revisar la traza de error: posible fallo de conexión');
Insert into IDEN_ERR (IDEN_ERR_ID,IDEN_ERR_DESC_C,IDEN_ERR_DESC,IDEN_ERR_TIPO,IDEN_ERR_CRIT,IDEN_ERR_MEN_AVISO,IDEN_ERR_MAILS,IDEN_ERR_ACC) values ('NOTIFICACIONES_012','Error al recoger las notificaciones pendientes','Error al recoger las notificaciones pendientes','2','1',null,null,'Revisar la traza de error: posible fallo de conexión');