------------------------------------------------------------------
----------------------------- ALTERS -----------------------------
------------------------------------------------------------------


--------------------------------
-------- ORI_AMBITOS_CE --------
--------------------------------

ALTER TABLE ORI_AMBITOS_CE ADD (ORI_AMB_DISTR  NUMBER(1) );




------------------------------------------------------------------
----------------------------- INSERTS ----------------------------
------------------------------------------------------------------

--------------------------------
-------- ORI_AMBITOS_CE --------
--------------------------------

Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('33','1','VITORIA-GASTEIZ','2014','3','1');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('34','1','VALLES ALAVESES','2014','1','0');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('35','1','VALLE DE AYALA','2014','1','0');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('36','1','RIOJA ALAVESA','2014','1','0');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('37','1','LLANADA ALAVESA','2014','1','0');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('38','48','GOBELA','2014','1','0');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('39','48','TXORIERRI','2014','1','0');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('40','48','URIBEALDEA','2014','1','0');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('41','48','DURANGALDEA (SIN ERMUA)','2014','1','0');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('42','48','ARRATIA-ZORNOTZA','2014','1','0');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('43','48','BUSTURIALDEA','2014','1','0');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('44','48','LEA-ARTIBAI','2014','1','0');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('45','48','ENCARTACIONES','2014','1','0');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('46','48','ARRATIA-NERBIOI','2014','1','0');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('47','48','IBAIZABAL','2014','1','0');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('48','48','BILBAO','2014','5','1');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('49','48','SANTURTZI-MUSKIZ-ABANTO-ZIERBANA /ZIERBANA','2014','1','0');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('50','48','BARAKALDO','2014','1','0');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('51','48','PORTUGALETE-ORTUELLA','2014','1','0');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('52','48','SESTAO-TRAPAGARAN','2014','1','0');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('53','20','BAJO BIDASOA','2014','1','0');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('54','20','OARSOALDEA','2014','1','0');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('55','20','DONOSTIA / SAN SEBASTIAN','2014','2','1');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('56','20','DONOSTIA MENDEBALDEA','2014','1','0');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('57','20','TOLOSALDEA','2014','1','0');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('58','20','UROLA MEDIO','2014','1','0');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('59','20','GOIHERRI','2014','1','0');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('60','20','BAJO DEBA','2014','1','0');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('61','20','EIBAR-ERMUA','2014','1','0');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('62','20','ELGOIBAR-MUTRIKU-DEBA--MENDARO-SORALUZE','2014','1','0');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('63','20','ALTO UROLA','2014','1','0');
Insert into ORI_AMBITOS_CE (ORI_AMB_COD,ORI_AMB_TERHIS,ORI_AMB_AMBITO,ORI_AMB_ANOCONV,ORI_AMB_CE,ORI_AMB_CE_ESPECIAL) values ('64','20','UROLA KOSTA','2014','1','0');





------------------------------------------------------------------
----------------------------- UPDATES ----------------------------
------------------------------------------------------------------



------------------------------
------- ORI_AMBITOS_CE -------
------------------------------

update ORI_AMBITOS_CE set ORI_AMB_DISTR=1 where ORI_AMB_COD='34';
update ORI_AMBITOS_CE set ORI_AMB_DISTR=1 where ORI_AMB_COD='37';
update ORI_AMBITOS_CE set ORI_AMB_DISTR=1 where ORI_AMB_COD='39';
update ORI_AMBITOS_CE set ORI_AMB_DISTR=1 where ORI_AMB_COD='42';
update ORI_AMBITOS_CE set ORI_AMB_DISTR=1 where ORI_AMB_COD='45';
update ORI_AMBITOS_CE set ORI_AMB_DISTR=1 where ORI_AMB_COD='46';
update ORI_AMBITOS_CE set ORI_AMB_DISTR=1 where ORI_AMB_COD='47';
update ORI_AMBITOS_CE set ORI_AMB_DISTR=1 where ORI_AMB_COD='49';
update ORI_AMBITOS_CE set ORI_AMB_DISTR=1 where ORI_AMB_COD='61';
update ORI_AMBITOS_CE set ORI_AMB_DISTR=1 where ORI_AMB_COD='62';
update ORI_AMBITOS_CE set ORI_AMB_DISTR=0 where ORI_AMB_COD>='33' and ORI_AMB_DISTR is null;