CREATE TABLE MELANBIDE61_PERSCCCCAPV( 
  ID NUMBER(8) NOT NULL,
  NUM_EXP VARCHAR2(30 BYTE),
  NUMCCC VARCHAR2(20 BYTE), 
  NUMTRABFIJ 	NUMBER(6),
  CONSTRAINT MELANBIDE61_PERSCCCCAPV_PK PRIMARY KEY (ID)
);

COMMENT ON TABLE MELANBIDE61_PERSCCCCAPV IS 'Relación de personas trabajadoras fijas por CCC en la CAPV';
COMMENT ON COLUMN MELANBIDE61_PERSCCCCAPV.ID 	IS 'Índice secuencial y clave primaria de la tabla';
COMMENT ON COLUMN MELANBIDE61_PERSCCCCAPV.NUM_EXP 	IS 'Número del Expediente al que se asocia el registro.';
COMMENT ON COLUMN MELANBIDE61_PERSCCCCAPV.NUMCCC 	IS 'CCC en la CAPV';
COMMENT ON COLUMN MELANBIDE61_PERSCCCCAPV.NUMTRABFIJ		IS 'Número de personas trabajadoras fijas en el momento del inicio del contrato de relevo por CCC';

CREATE SEQUENCE SEQ_MELANBIDE61_PERSCCCCAPV MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1;

COMMIT;