 -- Tabla
 CREATE TABLE "MELANBIDE61_SUBSOLIC" 
   (	"ID" NUMBER, 
	"NUM_EXP" VARCHAR2(20 BYTE) NOT null ENABLE, 
	"ESTADO" VARCHAR2(1 BYTE), 
	"ORGANISMO" VARCHAR2(200 BYTE), 
	"OBJETO" VARCHAR2(200 BYTE), 
	"IMPORTE" NUMBER(8,2), 
	"FECHA" DATE
   ) ;

   COMMENT ON COLUMN "MELANBIDE61_SUBSOLIC"."ID" IS 'ID secuencial';
   COMMENT ON COLUMN "MELANBIDE61_SUBSOLIC"."NUM_EXP" IS 'Número de Expediente';
   COMMENT ON COLUMN "MELANBIDE61_SUBSOLIC"."ESTADO" IS 'Estado de la Ayuda';
   COMMENT ON COLUMN "MELANBIDE61_SUBSOLIC"."ORGANISMO" IS 'Organismo Concedente';
   COMMENT ON COLUMN "MELANBIDE61_SUBSOLIC"."OBJETO" IS 'Descripción Objeto de la Ayuda';
   COMMENT ON COLUMN "MELANBIDE61_SUBSOLIC"."IMPORTE" IS 'Importe de la Ayuda';
   COMMENT ON COLUMN "MELANBIDE61_SUBSOLIC"."FECHA" IS 'Fecha de Solicitud o Concesión';
   
   ALTER TABLE "MELANBIDE61_SUBSOLIC" ADD PRIMARY KEY ("ID");
   
-- Secuencia
   CREATE SEQUENCE  "SEQ_MELANBIDE61_SUBSOLIC"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

