--------------------------------------------------------
--  DDL for Table CPE_OFERTA
--------------------------------------------------------

  CREATE TABLE "CPE_OFERTA" 
   (	"CPE_OFE_ID_OFERTA" NUMBER(8,0), 
	"CPE_OFE_COD_OFERTA" VARCHAR2(15 BYTE), 
	"CPE_OFE_COD_OFI_GEST" VARCHAR2(8 BYTE), 
	"CPE_OFE_PREC" VARCHAR2(1 BYTE), 
	"CPE_OFE_PREC_NOM" VARCHAR2(200 BYTE), 
	"CPE_OFE_DIFUSION" VARCHAR2(1 BYTE), 
	"CPE_OFE_FEC_DIFUSION" DATE, 
	"CPE_OFE_FEC_ENV_CAND" DATE, 
	"CPE_OFE_NUM_TOT_CAND" NUMBER(3,0), 
	"CPE_OFE_DOC_GEST_OFE" BLOB, 
	"CPE_OFE_CONTRATACION" VARCHAR2(1 BYTE), 
	"CPE_OFE_MOT_CONTRATACION" VARCHAR2(1000 BYTE), 
	"CPE_OFE_COD_TIPO_NIF" VARCHAR2(8 BYTE), 
	"CPE_OFE_NIF" VARCHAR2(10 BYTE), 
	"CPE_OFE_NOMBRE" VARCHAR2(200 BYTE), 
	"CPE_OFE_APE1" VARCHAR2(200 BYTE), 
	"CPE_OFE_APE2" VARCHAR2(200 BYTE), 
	"CPE_OFE_EMAIL" VARCHAR2(200 BYTE), 
	"CPE_OFE_TLF" VARCHAR2(15 BYTE), 
	"CPE_OFE_FEC_NAC" DATE, 
	"CPE_OFE_SEXO" VARCHAR2(1 BYTE), 
	"CPE_OFE_COD_TITULACION" VARCHAR2(8 BYTE), 
	"CPE_OFE_DOC_CONTRATACION" BLOB, 
	"CPE_OFE_FEC_INI" DATE, 
	"CPE_OFE_FEC_FIN" DATE, 
	"CPE_OFE_COD_GR_COT" VARCHAR2(8 BYTE), 
	"CPE_OFE_SALARIOB" NUMBER(10,2), 
	"CPE_OFE_DIETAS_CONVENIO" NUMBER(10,2), 
	"CPE_OFE_DIETAS_CONVOC" NUMBER(10,2), 
	"CPE_OFE_FEC_BAJA" DATE, 
	"CPE_OFE_COD_CAUSA_BAJA" VARCHAR2(8 BYTE), 
	"CPE_OFE_OBSERVACIONES" VARCHAR2(1000 BYTE), 
	"CPE_OFE_COD_PUESTO" VARCHAR2(4 BYTE), 
	"CPE_OFE_NUMEXP" VARCHAR2(30 BYTE), 
	"CPE_OFE_EXP_EJE" NUMBER(4,0), 
	"CPE_OFE_ANO_TITULACION" NUMBER(4,0), 
	"CPE_OFE_FL_SUSTITUTO" VARCHAR2(1 BYTE), 
	"CPE_OFE_NOM_DOC_GEST_OFE" VARCHAR2(500 BYTE), 
	"CPE_OFE_NOM_DOC_CONTRATACION" VARCHAR2(500 BYTE), 
	"CPE_OFE_ID_OFERTA_ORIGEN" NUMBER(8,0),
	"CPE_OFE_MESES_CONTRATO" NUMBER(6,0)
   );
 

   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_ID_OFERTA" IS 'Id de la tabla';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_COD_OFERTA" IS 'Código de la oferta';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_COD_OFI_GEST" IS 'Código de la oficina de gestión';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_PREC" IS 'Precandidato (S/N)';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_PREC_NOM" IS 'Nombre precandidato';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_DIFUSION" IS 'Difusión (S/N)';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_FEC_DIFUSION" IS 'Fecha difusión';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_FEC_ENV_CAND" IS 'Fecha primer envío candidatos';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_NUM_TOT_CAND" IS 'Número total de l candidatos';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_DOC_GEST_OFE" IS 'Documento de gestión de la oferta';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_CONTRATACION" IS 'Contratación (S/N/Sin Datos)';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_MOT_CONTRATACION" IS 'Motivo de la NO contratación';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_COD_TIPO_NIF" IS 'Tipo de documento del contratado';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_NIF" IS 'Número de documento del contratado';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_NOMBRE" IS 'Nombre del contratado';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_APE1" IS 'Apellido 1 del contratado';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_APE2" IS 'Apellido 2 del contratado';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_EMAIL" IS 'email del contratado';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_TLF" IS 'Número de teléfono del contratado';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_FEC_NAC" IS 'Fecha de nacimiento del contratado';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_SEXO" IS 'Sexo del contratado';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_COD_TITULACION" IS 'Titulación del contratado';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_DOC_CONTRATACION" IS 'Documento de contratación';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_FEC_INI" IS 'Fecha de inicio del contrato';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_FEC_FIN" IS 'Fecha de fin del contrato';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_COD_GR_COT" IS 'Grupo de cotización del contratado';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_SALARIOB" IS 'Salario bruto + SS empresa';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_DIETAS_CONVENIO" IS 'Dietas según convenio';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_DIETAS_CONVOC" IS 'Dietas de la convocatoria';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_FEC_BAJA" IS 'Fecha de baja';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_COD_CAUSA_BAJA" IS 'Causa de baja';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_OBSERVACIONES" IS 'Observaciones';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_COD_PUESTO" IS 'FK al puesto';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_NUMEXP" IS 'Número del expediente';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_EXP_EJE" IS 'Ejercicio del expediente';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_ANO_TITULACION" IS 'Año Titulación';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_FL_SUSTITUTO" IS 'Flag que indica si la persona contratada es sustituto o no';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_NOM_DOC_GEST_OFE" IS 'Nombre del documento de gestión asociado.';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_NOM_DOC_CONTRATACION" IS 'Nombre del documento de contratación asociado.';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_ID_OFERTA_ORIGEN" IS 'ID de la oferta de la cual se van a coger parte de los datos: oferta de origen.';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_MESES_CONTRATO" IS 'Duración en meses del contrato';

   CREATE UNIQUE INDEX "CPE_OFERTA_PK" ON "CPE_OFERTA" ("CPE_OFE_ID_OFERTA", "CPE_OFE_COD_PUESTO", "CPE_OFE_NUMEXP");

   
   
   
   ALTER TABLE "CPE_OFERTA" ADD CONSTRAINT "CPE_OFERTA_PK" PRIMARY KEY ("CPE_OFE_ID_OFERTA", "CPE_OFE_COD_PUESTO", "CPE_OFE_NUMEXP") ENABLE;
 
   ALTER TABLE "CPE_OFERTA" MODIFY ("CPE_OFE_ID_OFERTA" NOT NULL ENABLE);
 
   ALTER TABLE "CPE_OFERTA" MODIFY ("CPE_OFE_COD_PUESTO" NOT NULL ENABLE);
 
   ALTER TABLE "CPE_OFERTA" MODIFY ("CPE_OFE_NUMEXP" NOT NULL ENABLE);

   ALTER TABLE "CPE_OFERTA" ADD CONSTRAINT "CPE_OFERTA_CPE_PUESTO_FK1" FOREIGN KEY ("CPE_OFE_COD_PUESTO", "CPE_OFE_NUMEXP")
   REFERENCES "CPE_PUESTO" ("CPE_PTO_COD_PUESTO", "CPE_PTO_NUMEXP") ENABLE;
   
   
   
   
--------------------------------------------------------
--  DDL for Table CPE_JUSTIFICACION
--------------------------------------------------------

  CREATE TABLE "CPE_JUSTIFICACION" 
   (	"CPE_JUS_ID_JUSTIFICACION" NUMBER(8,0), 
	"CPE_JUS_COD_PUESTO" VARCHAR2(4 BYTE), 
	"CPE_JUS_NUMEXP" VARCHAR2(30 BYTE), 
	"CPE_JUS_EXP_EJE" NUMBER(4,0), 
	"CPE_JUS_ID_OFERTA" NUMBER(8,0), 
	"CPE_JUS_COD_ESTADO" VARCHAR2(8 BYTE), 
	"CPE_JUS_FL_VARIOS_TRAB" VARCHAR2(1 BYTE), 
	"CPE_JUS_IMP_JUSTIFICADO" NUMBER(10,2)
   );
 

   COMMENT ON COLUMN "CPE_JUSTIFICACION"."CPE_JUS_ID_JUSTIFICACION" IS 'ID de la tabla';
 
   COMMENT ON COLUMN "CPE_JUSTIFICACION"."CPE_JUS_COD_PUESTO" IS 'Código del puesto';
 
   COMMENT ON COLUMN "CPE_JUSTIFICACION"."CPE_JUS_NUMEXP" IS 'Número de expediente';
 
   COMMENT ON COLUMN "CPE_JUSTIFICACION"."CPE_JUS_EXP_EJE" IS 'Ejercicio del expediente';
 
   COMMENT ON COLUMN "CPE_JUSTIFICACION"."CPE_JUS_ID_OFERTA" IS 'Id de la oferta';
 
   COMMENT ON COLUMN "CPE_JUSTIFICACION"."CPE_JUS_COD_ESTADO" IS 'Estado (Justificado/Renuncia)';
 
   COMMENT ON COLUMN "CPE_JUSTIFICACION"."CPE_JUS_FL_VARIOS_TRAB" IS 'Flag para indicar si ha dispuesto de varios trabajadores';
 
   COMMENT ON COLUMN "CPE_JUSTIFICACION"."CPE_JUS_IMP_JUSTIFICADO" IS 'Importe jusiticado';
   
   
   

   CREATE UNIQUE INDEX "CPE_JUSTIFICACION_PK" ON "CPE_JUSTIFICACION" ("CPE_JUS_ID_JUSTIFICACION", "CPE_JUS_COD_PUESTO", "CPE_JUS_ID_OFERTA", "CPE_JUS_NUMEXP");

   ALTER TABLE "CPE_JUSTIFICACION" ADD CONSTRAINT "CPE_JUSTIFICACION_PK" PRIMARY KEY ("CPE_JUS_ID_JUSTIFICACION", "CPE_JUS_COD_PUESTO", "CPE_JUS_ID_OFERTA", "CPE_JUS_NUMEXP") ENABLE;
 
   ALTER TABLE "CPE_JUSTIFICACION" MODIFY ("CPE_JUS_ID_JUSTIFICACION" NOT NULL ENABLE);
 
   ALTER TABLE "CPE_JUSTIFICACION" MODIFY ("CPE_JUS_ID_OFERTA" NOT NULL ENABLE);
 
   ALTER TABLE "CPE_JUSTIFICACION" MODIFY ("CPE_JUS_COD_PUESTO" NOT NULL ENABLE);
 
   ALTER TABLE "CPE_JUSTIFICACION" MODIFY ("CPE_JUS_NUMEXP" NOT NULL ENABLE);
