ALTER TABLE CPE_PUESTO  MODIFY (CPE_PTO_COD_TIT_1 VARCHAR2(8));
ALTER TABLE CPE_PUESTO  MODIFY (CPE_PTO_COD_TIT_2 VARCHAR2(8));
ALTER TABLE CPE_PUESTO  MODIFY (CPE_PTO_COD_TIT_3 VARCHAR2(8));
ALTER TABLE CPE_PUESTO  MODIFY (CPE_PTO_COD_IDIOMA_1 VARCHAR2(8));
ALTER TABLE CPE_PUESTO  MODIFY (CPE_PTO_COD_IDIOMA_2 VARCHAR2(8));
ALTER TABLE CPE_PUESTO  MODIFY (CPE_PTO_COD_NIV_FORM VARCHAR2(8));
ALTER TABLE CPE_PUESTO  MODIFY (CPE_PTO_COD_GR_COT VARCHAR2(8));
ALTER TABLE CPE_PUESTO  MODIFY (CPE_PTO_COD_RESULT VARCHAR2(8));
ALTER TABLE CPE_PUESTO  MODIFY (CPE_PTO_COD_NIV_IDI_1 VARCHAR2(8));
ALTER TABLE CPE_PUESTO  MODIFY (CPE_PTO_COD_NIV_IDI_2 VARCHAR2(8));

ALTER TABLE CPE_PUESTO RENAME COLUMN CPE_PTO_SALARIO_ANEX TO CPE_PTO_SALARIO_ANEX1;
ALTER TABLE CPE_PUESTO RENAME COLUMN CPE_PTO_IMP_SOLIC TO CPE_PTO_IMP_MAX_SUBV;

ALTER TABLE CPE_PUESTO ADD (CPE_PTO_CIUDAD_DESTINO VARCHAR2(20));
ALTER TABLE CPE_PUESTO ADD (CPE_PTO_DPTO VARCHAR2(200 BYTE));
ALTER TABLE CPE_PUESTO ADD (CPE_PTO_COD_IDIOMA_3 VARCHAR2(8 BYTE));
ALTER TABLE CPE_PUESTO ADD (CPE_PTO_COD_NIV_IDI_3 VARCHAR2(8 BYTE));
ALTER TABLE CPE_PUESTO ADD (CPE_PTO_SAL_SOLIC NUMBER(10,2));
ALTER TABLE CPE_PUESTO ADD (CPE_PTO_DIETAS_SOLIC NUMBER(10,2));
ALTER TABLE CPE_PUESTO ADD (CPE_PTO_TRAM_SOLIC NUMBER(10,2));
ALTER TABLE CPE_PUESTO ADD (CPE_PTO_IMP_TOT_SOLIC NUMBER(10,2));
ALTER TABLE CPE_PUESTO ADD (CPE_PTO_SALARIO_ANEX2 NUMBER(10,2));
ALTER TABLE CPE_PUESTO ADD (CPE_PTO_SALARIO_ANEX3 NUMBER(10,2));
ALTER TABLE CPE_PUESTO ADD (CPE_PTO_SALARIO_ANEX_TOT NUMBER(10,2));
ALTER TABLE CPE_PUESTO ADD (CPE_PTO_MESES_CONTRATO NUMBER(6,0));


COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_CIUDAD_DESTINO" IS 'Ciudad de destino';
COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_DPTO" IS 'Departamento';
COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_COD_IDIOMA_3" IS 'Código de idioma 3';
COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_COD_NIV_IDI_3" IS 'Nivel de idioma 3';
COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_SAL_SOLIC" IS 'Salario solicitado';
COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_DIETAS_SOLIC" IS 'Dietas solicitadas';
COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_TRAM_SOLIC" IS 'Tramitación / Seguros solicitado';
COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_IMP_TOT_SOLIC" IS 'Importe total solicitado';
COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_SALARIO_ANEX2" IS 'Salario según anexo 1 - Pais 2';
COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_SALARIO_ANEX3" IS 'Salario según anexo 1 - Pais 3';
COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_SALARIO_ANEX_TOT" IS 'Total salario';
COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_MESES_CONTRATO" IS 'Duración en meses del contrato';