CREATE SEQUENCE SEQ_MEIKUS01_RESPUESTAS_OP START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER;
commit;

CREATE SEQUENCE SQ_MEIKUS_CONVOCATORIA START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER;
commit;

Create table MEIKUS_CONVOCATORIA(
	ID NUMBER(19,0) NOT NULL,
	CONVOCATORIA NUMBER(4,0) NOT NULL,
	NUM_PAGOS NUMBER(5,0) NOT NULL,
	JUSTIFICACION NUMBER(1,0) NOT NULL,
	PLURIANUALIDADES NUMBER(1,0) NOT NULL,
	COD_PROCEDIMIENTO VARCHAR2(5 BYTE) NOT NULL,
	COD_ORGANIZACION NUMBER(3,0) NOT NULL,
	NUM_ANOS NUMBER(5,0) NULL,
	PRIMARY KEY(ID)
);
COMMENT ON COLUMN MEIKUS_CONVOCATORIA.ID IS 'Identificador de la convocatoria';
COMMENT ON COLUMN MEIKUS_CONVOCATORIA.CONVOCATORIA IS 'Ejercicio de la convocatoria';
COMMENT ON COLUMN MEIKUS_CONVOCATORIA.NUM_PAGOS IS 'Número de pagos de la convocatoria';
COMMENT ON COLUMN MEIKUS_CONVOCATORIA.JUSTIFICACION IS 'Indica si requiere o no justificación';
COMMENT ON COLUMN MEIKUS_CONVOCATORIA.PLURIANUALIDADES IS 'Indica si tiene o no plurianualidades';
COMMENT ON COLUMN MEIKUS_CONVOCATORIA.COD_PROCEDIMIENTO IS 'Código del procedimiento de la convocatoria';
COMMENT ON COLUMN MEIKUS_CONVOCATORIA.COD_ORGANIZACION IS 'Código de la organización del procedimiento';
COMMENT ON COLUMN MEIKUS_CONVOCATORIA.NUM_ANOS IS 'Número de años de la convocatoria';
commit;

Create table MEIKUS01_RESPUESTAS_OP(
	ID_RESPUESTA NUMBER(6,0) NOT NULL,
	ID_EXPEDIENTE VARCHAR2(30 BYTE) NOT NULL,
	COD_ORGANIZACION NUMBER(3,0) NOT NULL,
	COD_PROCEDIMIENTO VARCHAR2(5 BYTE) NOT NULL,
	EJERCICIO NUMBER(4,0) NOT NULL,
	COD_EVENTO VARCHAR2(10 BYTE) NOT NULL,
	INFO_ADICIONAL CLOB NOT NULL,
	PRIMARY KEY(ID_RESPUESTA)
);
COMMENT ON COLUMN MEIKUS01_RESPUESTAS_OP.ID_RESPUESTA IS 'Identificador de la respuesta';
COMMENT ON COLUMN MEIKUS01_RESPUESTAS_OP.ID_EXPEDIENTE IS 'Identificador del expediente';
COMMENT ON COLUMN MEIKUS01_RESPUESTAS_OP.COD_ORGANIZACION IS 'Código de la organización del expediente';
COMMENT ON COLUMN MEIKUS01_RESPUESTAS_OP.COD_PROCEDIMIENTO IS 'Código del procedimiento del expediente';
COMMENT ON COLUMN MEIKUS01_RESPUESTAS_OP.EJERCICIO IS 'Ejercicio del expediente';
COMMENT ON COLUMN MEIKUS01_RESPUESTAS_OP.COD_EVENTO IS 'Código del evento del expediente';
COMMENT ON COLUMN MEIKUS01_RESPUESTAS_OP.INFO_ADICIONAL IS 'Información adicional del expediente';
commit;

Create table MEIKUS01_PAGOS(
	ID_EXPEDIENTE VARCHAR2(30 BYTE) NOT NULL,
	COD_ORGANIZACION NUMBER(3,0) NOT NULL,
	COD_PROCEDIMIENTO VARCHAR2(5 BYTE) NOT NULL,
	EJERCICIO NUMBER(4,0) NOT NULL,
	NUMERO_PAGO NUMBER(4,0) NOT NULL,
	ID_EXPEDIENTE_PASARELA_PAGO VARCHAR2(30 BYTE),
	PRIMARY KEY(ID_EXPEDIENTE,COD_ORGANIZACION)
);
COMMENT ON COLUMN MEIKUS01_PAGOS.ID_EXPEDIENTE IS 'Identificador del expediente';
COMMENT ON COLUMN MEIKUS01_PAGOS.COD_ORGANIZACION IS 'Código de la organización del expediente';
COMMENT ON COLUMN MEIKUS01_PAGOS.COD_PROCEDIMIENTO IS 'Código del procedimiento del expediente';
COMMENT ON COLUMN MEIKUS01_PAGOS.EJERCICIO IS 'Ejercicio del expediente';
COMMENT ON COLUMN MEIKUS01_PAGOS.NUMERO_PAGO IS 'Número de pago del expediente';
COMMENT ON COLUMN MEIKUS01_PAGOS.ID_EXPEDIENTE_PASARELA_PAGO IS 'Identificador del expediente en la pasarela de pago';
commit;
