-- NIVEL CAUALIFICACIÓN
Insert into E_DES (DES_COD,DES_NOM) values ('NIGE','NIVEL CUALIFICACIÓN / ESTUDIOS GEL');

Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM,DES_VAL_ESTADO) values ('NIGE','1','LICENCIATURA, INGENIERÍA, ARQUITECTURA, MÁSTER UNIVERSITARIO, GRADO UNIVERSITARIO, DIPLOMATURA UNIVERSITARIA, INGENIERÍA TÉCNICA, ARQUITECTURA TÉCNICA|LIZENTZIATURA, INGENIARITZA, ARKITEKTURA, UNIBERTSITATE-MASTERRA, UNIBERTSITATE-GRADUA, UNIBERTSITATE-DIPLOMATURA, INGENIARITZA TEKNIKOA, ARKITEKTURA TEKNIKOA','A');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM,DES_VAL_ESTADO) values ('NIGE','2','CICLOS FORMATIVOS DE GRADO SUPERIOR O MEDIO, BACHILLERATO|GOI-MAILAKO EDO ERDI-MAILAKO HEZIKETA-ZIKLOAK, BATXILERGOA','A');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM,DES_VAL_ESTADO) values ('NIGE','3','FORMACIÓN PROFESIONAL BÁSICA, CERTIFICADOS DE PROFESIONALIDAD, GRADUADO EN ESO|OINARRIZKO LANBIDE HEZIKETA, PROFESIONALTASUN-ZIURTAGIRIAK, DBHKO GRADUATUA','A');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM,DES_VAL_ESTADO) values ('NIGE','4','CERTIFICADO ESCOLARIDAD, NO CUALIFICADOS|ESKOLA-ZIURTAGIRIA, KUALIFIKATU GABEA','A');

-- DURACIÓN CONTRATO
Insert into E_DES (DES_COD,DES_NOM) values ('DUGE','DURACIÓN CONTRATO GEL');

Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM,DES_VAL_ESTADO) values ('DUGE','8','8 MESES|8 HILABETE','A');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM,DES_VAL_ESTADO) values ('DUGE','12','12 MESES|12 HILABETE','A');



-- MELANBIDE82_CONTRATACION
  CREATE TABLE MELANBIDE82_CONTRATACION 
   (	ID NUMBER(8,0) NOT NULL ENABLE, 
	NUM_EXP VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	PRIORIDAD NUMBER(4,0) NOT NULL ENABLE, 
	DENOMPUESTO VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	NIVELCUALIFICACION VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	MODCONTRATO VARCHAR2(150 BYTE) NOT NULL ENABLE, 
	DURCONTRATO VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	GRUPOCOTIZ VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	COSTESALARIAL NUMBER(8,2) NOT NULL ENABLE, 
	SUBVSOLICITADA NUMBER(8,2) NOT NULL ENABLE, 
	CONSTRAINT MELANBIDE82_CONTRATACION_PK PRIMARY KEY (ID) USING INDEX  enable, 
	 CONSTRAINT MELANBIDE82_CONTRATACION_UK UNIQUE (NUM_EXP, PRIORIDAD)
  USING INDEX  enable
   ) ;

   COMMENT ON COLUMN MELANBIDE82_CONTRATACION.ID IS 'Identificador Secuencial';
   COMMENT ON COLUMN MELANBIDE82_CONTRATACION.NUM_EXP IS 'Número de Expediente';
   COMMENT ON COLUMN MELANBIDE82_CONTRATACION.PRIORIDAD IS 'Prioridad (Nº Puesto)';
   COMMENT ON COLUMN MELANBIDE82_CONTRATACION.DENOMPUESTO IS 'Denominación del Puesto';
   COMMENT ON COLUMN MELANBIDE82_CONTRATACION.NIVELCUALIFICACION IS 'Nivel de Cualificación';
   COMMENT ON COLUMN MELANBIDE82_CONTRATACION.MODCONTRATO IS 'Modalidad De Contrato';
   COMMENT ON COLUMN MELANBIDE82_CONTRATACION.DURCONTRATO IS 'Duración Contrato En Meses';
   COMMENT ON COLUMN MELANBIDE82_CONTRATACION.GRUPOCOTIZ IS 'Grupo Cotización';
   COMMENT ON COLUMN MELANBIDE82_CONTRATACION.COSTESALARIAL IS 'Coste Salarial';
   COMMENT ON COLUMN MELANBIDE82_CONTRATACION.SUBVSOLICITADA IS 'Subvención Solicitada';

   CREATE SEQUENCE  SEQ_MELANBIDE82_CONTRATACION  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;


-- MELANBIDE82_CONTRATACION_INI
  CREATE TABLE MELANBIDE82_CONTRATACION_INI 
   (	ID NUMBER(8,0) NOT NULL ENABLE, 
	NUM_EXP VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	NUM_PUESTO NUMBER(4,0) NOT NULL ENABLE, 
	MUNICIPIO2 VARCHAR2(100 BYTE), 
	NOMBRE2 VARCHAR2(100 BYTE), 
	APELLIDO12 VARCHAR2(50 BYTE), 
	APELLIDO22 VARCHAR2(50 BYTE), 
	DNINIE2 VARCHAR2(15 BYTE), 
	FECHANACIMIENTO2 DATE, 
	SEXO2 VARCHAR2(1 BYTE), 
	NIVELCUALIFICACION2 VARCHAR2(1 BYTE), 
	PUESTOTRABAJO2 VARCHAR2(500 BYTE), 
	NOFERTA2 VARCHAR2(50 BYTE), 
	GRUPOCOTIZ2 VARCHAR2(2 BYTE), 
	DURACION2 VARCHAR2(2 BYTE), 
	FECHAINICIO2 DATE, 
	EDAD2 NUMBER(2,0), 
	RETRIBUCIONBRUTA2 NUMBER(8,2), 

	CONSTRAINT MELANBIDE82_CONTRATACION_I_PK PRIMARY KEY (ID) USING INDEX  enable, 
	CONSTRAINT MELANBIDE82_CONTRATA_INI_UK UNIQUE (NUM_EXP, NUM_PUESTO) USING INDEX  enable, 
	CONSTRAINT MELANBIDE82_CONTRATA_INI_FK FOREIGN KEY (NUM_EXP, NUM_PUESTO) REFERENCES MELANBIDE82_CONTRATACION (NUM_EXP, PRIORIDAD) ENABLE
   ) ;

   COMMENT ON COLUMN MELANBIDE82_CONTRATACION_INI.ID IS 'Id Secuencial';
   COMMENT ON COLUMN MELANBIDE82_CONTRATACION_INI.NUM_EXP IS 'Número de Expediente';
   COMMENT ON COLUMN MELANBIDE82_CONTRATACION_INI.NUM_PUESTO IS 'Número de Puesto (Prioridad';
   COMMENT ON COLUMN MELANBIDE82_CONTRATACION_INI.NOMBRE2 IS 'Nombre';
   COMMENT ON COLUMN MELANBIDE82_CONTRATACION_INI.APELLIDO12 IS 'Primer Apellido';
   COMMENT ON COLUMN MELANBIDE82_CONTRATACION_INI.APELLIDO22 IS 'Segundo Apellido';
   COMMENT ON COLUMN MELANBIDE82_CONTRATACION_INI.DNINIE2 IS 'DNI/NIE';
   COMMENT ON COLUMN MELANBIDE82_CONTRATACION_INI.FECHANACIMIENTO2 IS 'Fecha de Nacimiento ';
   COMMENT ON COLUMN MELANBIDE82_CONTRATACION_INI.SEXO2 IS 'Sexo';
   COMMENT ON COLUMN MELANBIDE82_CONTRATACION_INI.NIVELCUALIFICACION2 IS 'Nivel de Cualificación';
   COMMENT ON COLUMN MELANBIDE82_CONTRATACION_INI.PUESTOTRABAJO2 IS 'Puesto de Trabajo';
   COMMENT ON COLUMN MELANBIDE82_CONTRATACION_INI.NOFERTA2 IS 'Número de Oferta';
   COMMENT ON COLUMN MELANBIDE82_CONTRATACION_INI.GRUPOCOTIZ2 IS 'Grupo Cotización';
   COMMENT ON COLUMN MELANBIDE82_CONTRATACION_INI.DURACION2 IS 'Duración Contrato En Meses';
   COMMENT ON COLUMN MELANBIDE82_CONTRATACION_INI.FECHAINICIO2 IS 'Fecha de Inicio Contrato';
   COMMENT ON COLUMN MELANBIDE82_CONTRATACION_INI.EDAD2 IS 'Edad';
   COMMENT ON COLUMN MELANBIDE82_CONTRATACION_INI.RETRIBUCIONBRUTA2 IS 'Retribución Bruta';
   COMMENT ON COLUMN MELANBIDE82_CONTRATACION_INI.MUNICIPIO2 IS 'Municipio';

   CREATE SEQUENCE  SEQ_MELANBIDE82_CONTRATA_INI  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;


-- MELANBIDE82_CONTRATACION_FIN
  CREATE TABLE MELANBIDE82_CONTRATACION_FIN 
   (	ID NUMBER(8,0) NOT NULL ENABLE, 
	NUM_EXP VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	NUM_PUESTO NUMBER(4,0) NOT NULL ENABLE, 
	MUNICIPIO3 VARCHAR2(150 BYTE), 
	NOMBRE3 VARCHAR2(100 BYTE), 
	APELLIDO13 VARCHAR2(50 BYTE), 
	APELLIDO23 VARCHAR2(50 BYTE), 
	DNINIE3 VARCHAR2(15 BYTE), 
	SEXO3 VARCHAR2(1 BYTE), 
	GRUPOCOTIZ3 VARCHAR2(2 BYTE), 
	DURACION3 VARCHAR2(2 BYTE), 
	FECHAINICIO3 DATE, 
	FECHAFIN3 DATE, 
	RETRIBUCIONBRUTA3 NUMBER(8,2), 
	COSTESALARIAL3 NUMBER(8,2), 
	COSTESSS3 NUMBER(8,2), 
	INDEMFINCONTRATO3 NUMBER(8,2), 
	COSTETOTALREAL3 NUMBER(8,2), 
	SUBVCONCEDIDALAN3 NUMBER(8,2), 
	 CONSTRAINT MELANBIDE82_CONTRATA_FIN_PK PRIMARY KEY (ID) USING INDEX  enable, 
	 CONSTRAINT MELANBIDE82_CONTRATA_FIN_UK UNIQUE (NUM_EXP, NUM_PUESTO) USING INDEX  enable, 
	 CONSTRAINT MELANBIDE82_CONTRATA_FIN_FK FOREIGN KEY (NUM_EXP, NUM_PUESTO) REFERENCES MELANBIDE82_CONTRATACION (NUM_EXP, PRIORIDAD) ENABLE
   ) ;

	COMMENT ON COLUMN MELANBIDE82_CONTRATACION_FIN.ID IS 'Id Secuencial';
	COMMENT ON COLUMN MELANBIDE82_CONTRATACION_FIN.NUM_EXP IS 'Número de Expediente';
	COMMENT ON COLUMN MELANBIDE82_CONTRATACION_FIN.NUM_PUESTO IS 'Nº Puesto (Prioridad)';
	COMMENT ON COLUMN MELANBIDE82_CONTRATACION_FIN.MUNICIPIO3 IS 'Municipio';
	COMMENT ON COLUMN MELANBIDE82_CONTRATACION_FIN.NOMBRE3 IS 'Nombre';
	COMMENT ON COLUMN MELANBIDE82_CONTRATACION_FIN.APELLIDO13 IS 'Primer Apellido';
	COMMENT ON COLUMN MELANBIDE82_CONTRATACION_FIN.APELLIDO23 IS 'Segundo Apellido';
	COMMENT ON COLUMN MELANBIDE82_CONTRATACION_FIN.DNINIE3 IS 'DNI/NIE';
    COMMENT ON COLUMN MELANBIDE82_CONTRATACION_FIN.SEXO3 IS 'Sexo';
	COMMENT ON COLUMN MELANBIDE82_CONTRATACION_FIN.GRUPOCOTIZ3 IS 'Grupo Cotización';
	COMMENT ON COLUMN MELANBIDE82_CONTRATACION_FIN.DURACION3 IS 'Duración Contrato En Meses';
    COMMENT ON COLUMN MELANBIDE82_CONTRATACION_FIN.FECHAINICIO3 IS 'Fecha de Inicio Contrato';
	COMMENT ON COLUMN MELANBIDE82_CONTRATACION_FIN.FECHAFIN3 IS 'Fecha de Inicio Contrato';
	COMMENT ON COLUMN MELANBIDE82_CONTRATACION_FIN.RETRIBUCIONBRUTA3 IS 'Retribución Bruta';
	COMMENT ON COLUMN MELANBIDE82_CONTRATACION_FIN.COSTESALARIAL3 IS 'Coste Salarial';
	COMMENT ON COLUMN MELANBIDE82_CONTRATACION_FIN.COSTESSS3 IS 'Costes SS';
	COMMENT ON COLUMN MELANBIDE82_CONTRATACION_FIN.INDEMFINCONTRATO3 IS 'Indemnización Fin de Contrato';
	COMMENT ON COLUMN MELANBIDE82_CONTRATACION_FIN.COSTETOTALREAL3 IS 'Coste Total Real';
	COMMENT ON COLUMN MELANBIDE82_CONTRATACION_FIN.SUBVCONCEDIDALAN3 IS 'Subvención Concedida Lanbide';
	
	CREATE SEQUENCE  SEQ_MELANBIDE82_CONTRATA_FIN  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
