
CREATE SEQUENCE SEQ_ME_LANBIDE01_DATOS_CALCULO START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER;
COMMIT;

CREATE SEQUENCE SEQ_ME_LANBIDE01_PERIODO START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER;
COMMIT;

Create table MELANBIDE01_DATOS_CALCULO(
	ID NUMBER(6,0) NOT NULL,
	COD_MUNICIPIO NUMBER(3,0) NOT NULL,
	NUM_EXPEDIENTE VARCHAR2(30 BYTE) NOT NULL,
	EJERCICIO NUMBER(4,0) NOT NULL,
	COD_PROCEDIMIENTO VARCHAR2(10) NOT NULL,
	IMPORTE_SUBVENC NUMBER(23,2) NOT NULL,
	MODULO VARCHAR2(50 BYTE) NOT NULL,
	PRIMARY KEY (ID)
);
COMMENT ON COLUMN MELANBIDE01_DATOS_CALCULO.ID IS 'ID datos cálculo';
COMMENT ON COLUMN MELANBIDE01_DATOS_CALCULO.COD_MUNICIPIO IS 'Cod municipio del expediente';
COMMENT ON COLUMN MELANBIDE01_DATOS_CALCULO.NUM_EXPEDIENTE IS 'Número del expediente';
COMMENT ON COLUMN MELANBIDE01_DATOS_CALCULO.EJERCICIO IS 'Ejercicio del expediente';
COMMENT ON COLUMN MELANBIDE01_DATOS_CALCULO.COD_PROCEDIMIENTO IS 'Código de procedimiento del expediente';
COMMENT ON COLUMN MELANBIDE01_DATOS_CALCULO.IMPORTE_SUBVENC IS 'Importe de la subvención';
COMMENT ON COLUMN MELANBIDE01_DATOS_CALCULO.MODULO IS 'Nombre del módulo';
COMMIT;

Create table MELANBIDE01_PERIODO(
	ID NUMBER(6,0) NOT NULL,
	ID_DATOS_CALCULO NUMBER(6,0) NOT NULL,
	FECHA_INICIO DATE NOT NULL,
	FECHA_FIN DATE NOT NULL,
	PORC_SUBVENC NUMBER(4,0) NOT NULL,
	NUM_DIAS NUMBER(4,0) NOT NULL,
	BASE_COTIZACION NUMBER(23,2) NOT NULL,
	GASTO NUMBER(23,2) NOT NULL,
	REDUC_PERS_SUST NUMBER(4,0) NOT NULL,
	JORN_PERS_SUST NUMBER(4,0) NOT NULL,
	JORN_PERS_CONT NUMBER(4,0) NOT NULL,
	BONIFICACION NUMBER(23,2),
	PRIMARY KEY (ID),
	FOREIGN KEY(ID_DATOS_CALCULO) REFERENCES MELANBIDE01_DATOS_CALCULO(ID));
);
COMMENT ON COLUMN MELANBIDE01_PERIODO.ID IS 'ID del periodo';
COMMENT ON COLUMN MELANBIDE01_PERIODO.ID_DATOS_CALCULO IS 'Id de los datos de calculo asociados al periodo';
COMMENT ON COLUMN MELANBIDE01_PERIODO.FECHA_INICIO IS 'Fecha de inicio del periodo';
COMMENT ON COLUMN MELANBIDE01_PERIODO.FECHA_FIN IS 'Fecha de fin del periodo';
COMMENT ON COLUMN MELANBIDE01_PERIODO.PORC_SUBVENC IS 'Porcentaje subvencionado';
COMMENT ON COLUMN MELANBIDE01_PERIODO.NUM_DIAS IS 'Número de dias';
COMMENT ON COLUMN MELANBIDE01_PERIODO.BASE_COTIZACION IS 'Base de cotizacion';
COMMENT ON COLUMN MELANBIDE01_PERIODO.GASTO IS 'Gasto';
COMMENT ON COLUMN MELANBIDE01_PERIODO.REDUC_PERS_SUST IS 'Reduccion persona sustituida';
COMMENT ON COLUMN MELANBIDE01_PERIODO.JORN_PERS_SUST IS 'Jornada persona sustituida';
COMMENT ON COLUMN MELANBIDE01_PERIODO.JORN_PERS_CONT IS 'Jornada persona contratada';
COMMENT ON COLUMN MELANBIDE01_PERIODO.BONIFICACION IS 'Bonificación del periodo';
COMMIT;

Alter table MELANBIDE01_PERIODO modify PORC_SUBVENC number(6,2);
Alter table MELANBIDE01_PERIODO modify REDUC_PERS_SUST number(6,2);
Alter table MELANBIDE01_PERIODO modify JORN_PERS_SUST number(6,2);
Alter table MELANBIDE01_PERIODO modify JORN_PERS_CONT number(6,2);
commit;




--------------------------------------------------------------------------
--------------------------------------------------------------------------
------- DE AQUÍ EN ADELANTE SCRIPTS PARA LA VERSIÓN 2.1 DEL PARCHE -------
--------------------------------------------------------------------------
--------------------------------------------------------------------------

ALTER TABLE MELANBIDE01_DATOS_CALCULO ADD DESCUENTO NUMBER(5,0) DEFAULT 0;
COMMENT ON COLUMN MELANBIDE01_DATOS_CALCULO.DESCUENTO IS 'Descuento a aplicar sobre el total de los gastos';

ALTER TABLE MELANBIDE01_DATOS_CALCULO ADD TOTAL_CON_DESCUENTO NUMBER(23,2) DEFAULT 0;
COMMENT ON COLUMN MELANBIDE01_DATOS_CALCULO.DESCUENTO IS 'Total gasto menos el descuento';
COMMIT;