Insert into E_PCA (PCA_MUN,PCA_PRO,PCA_COD,PCA_DES,PCA_PLT,PCA_TDA,PCA_TAM,PCA_MAS,PCA_OBL,PCA_NOR,PCA_ROT,PCA_ACTIVO,PCA_DESPLEGABLE,PCA_OCULTO,PCA_BLOQ,PLAZO_AVISO,PERIODO_PLAZO,PCA_GROUP,PCA_POS_X,PCA_POS_Y) 
values ('1','DLD50','REGISTRO','¿ INSCRITA EN REGISTRO ELECTRONICO DE REPRESENTANTES ADMON PUBLICA CAE ?','6','6','6',null,'0','119','¿ INSCRITA EN REGISTRO ELECTRONICO DE REPRESENTANTES ADMON PUBLICA CAE ?','SI','BOOL','NO','NO',null,null,'C',1,1);

Insert into E_PCA (PCA_MUN,PCA_PRO,PCA_COD,PCA_DES,PCA_PLT,PCA_TDA,PCA_TAM,PCA_MAS,PCA_OBL,PCA_NOR,PCA_ROT,PCA_ACTIVO,PCA_DESPLEGABLE,PCA_OCULTO,PCA_BLOQ,PLAZO_AVISO,PERIODO_PLAZO,PCA_GROUP,PCA_POS_X,PCA_POS_Y) 
values ('1','DLD50','DNIPCE','DNI','1','2','11',null,'0','120','DNI','SI',null,'NO','NO',null,null,'D','1','1');

Insert into E_PCA (PCA_MUN,PCA_PRO,PCA_COD,PCA_DES,PCA_PLT,PCA_TDA,PCA_TAM,PCA_MAS,PCA_OBL,PCA_NOR,PCA_ROT,PCA_ACTIVO,PCA_DESPLEGABLE,PCA_OCULTO,PCA_BLOQ,PLAZO_AVISO,PERIODO_PLAZO,PCA_GROUP,PCA_POS_X,PCA_POS_Y) 
values ('1','DLD50','IDIOMAAVISOSTIT','AVISO - IDIOMA | TITULAR','1','2','30',null,'0','121','AVISO - IDIOMA | TITULAR','SI',null,'SI','SI',null,null,'DAN','1','1');

update e_pca set pca_bloq='SI' where pca_pro='DLD50' and pca_cod='SANCIONADA';
update e_pca set pca_activo='SI' where pca_pro='DLD50' and pca_activo='NO' and pca_cod='SANCADM';

update e_pca set pca_bloq='SI' where pca_pro='DLD50' and pca_cod='OBLIGACIONES';
update e_pca set pca_activo='SI' where pca_pro='DLD50' and pca_activo='NO' and pca_cod='PAGREINT';

update e_pca set pca_bloq='SI' where pca_pro='DLD50' and pca_cod='CIRCUNSTANCIAS';
update e_pca set pca_activo='SI' where pca_pro='DLD50' and pca_activo='NO' and pca_cod='RESTCIRC';

update e_pca set pca_activo='SI',pca_des='NO SE HALLA EN PROCEDIMIENTO DE REINTEGRO O SANCIONADOR',pca_rot='NO SE HALLA EN PROCEDIMIENTO DE REINTEGRO O SANCIONADOR' 
where pca_pro='DLD50' and pca_activo='NO' and pca_cod='REINTSANC' and pca_des='EN PROCEDIMIENTO DE REINTEGRO O SANCIONADOR';

update e_pca set pca_activo='NO' where pca_pro='DLD50' and pca_cod='IMREI' and pca_activo='SI';
Insert into E_PCA (PCA_MUN,PCA_PRO,PCA_COD,PCA_DES,PCA_PLT,PCA_TDA,PCA_TAM,PCA_MAS,PCA_OBL,PCA_NOR,PCA_ROT,PCA_ACTIVO,PCA_DESPLEGABLE,PCA_OCULTO,PCA_BLOQ,PLAZO_AVISO,PERIODO_PLAZO,PCA_GROUP,PCA_POS_X,PCA_POS_Y) 
values ('1','DLD50','REINTAYUDA','NOMBRE AYUDA A REINTEGRAR','1','2','250',null,'0','122','NOMBRE AYUDA A REINTEGRAR','SI',null,'NO','NO',null,null,'H','1','1');

Insert into E_PCA (PCA_MUN,PCA_PRO,PCA_COD,PCA_DES,PCA_PLT,PCA_TDA,PCA_TAM,PCA_MAS,PCA_OBL,PCA_NOR,PCA_ROT,PCA_ACTIVO,PCA_DESPLEGABLE,PCA_OCULTO,PCA_BLOQ,PLAZO_AVISO,PERIODO_PLAZO,PCA_GROUP,PCA_POS_X,PCA_POS_Y) 
values ('1','DLD50','REINTENT','ENTIDAD A LA QUE DEBE REINTEGRAR LA AYUDA','1','2','150',null,'0','123','ENTIDAD A LA QUE DEBE REINTEGRAR LA AYUDA','SI',null,'NO','NO',null,null,'H','1','1');

update e_pca set pca_activo='SI' where pca_pro='DLD50' and pca_activo='NO' and pca_cod='NOAYUD';

update e_pca set pca_activo='SI' where pca_pro='DLD50' and pca_activo='NO' and pca_cod='CONCAYUD';

update e_pca set pca_activo='SI' where pca_pro='DLD50' and pca_activo='NO' and pca_cod='AYUDPDRESOL';

Insert into E_PCA (PCA_MUN,PCA_PRO,PCA_COD,PCA_DES,PCA_PLT,PCA_TDA,PCA_TAM,PCA_MAS,PCA_OBL,PCA_NOR,PCA_ROT,PCA_ACTIVO,PCA_DESPLEGABLE,PCA_OCULTO,PCA_BLOQ,PLAZO_AVISO,PERIODO_PLAZO,PCA_GROUP,PCA_POS_X,PCA_POS_Y) 
values ('1','DLD50','ADYENTPUPRI','ADMIN O ENTIDAD CON AYUDA PTE DE RESOLUCION','1','2','100',null,'0','124','ADMIN O ENTIDAD CON AYUDA PTE DE RESOLUCION','SI',null,'NO','NO',null,null,'H','1','1');

update e_pca set pca_activo='SI' where pca_pro='DLD50' and pca_cod='DOMCAPV' and pca_activo='NO';

update e_pca set pca_activo='SI' where pca_pro='DLD50' and pca_activo='NO' and pca_cod='COMRLT';

update e_pca set pca_activo='SI' where pca_pro='DLD50' and pca_activo='NO' and pca_cod='NORLT';

update e_pca set pca_bloq='SI' where pca_pro='DLD50' and pca_cod='SOLICPAR' and pca_bloq='NO';
Insert into E_PCA (PCA_MUN,PCA_PRO,PCA_COD,PCA_DES,PCA_PLT,PCA_TDA,PCA_TAM,PCA_MAS,PCA_OBL,PCA_NOR,PCA_ROT,PCA_ACTIVO,PCA_DESPLEGABLE,PCA_OCULTO,PCA_BLOQ,PLAZO_AVISO,PERIODO_PLAZO,PCA_GROUP,PCA_POS_X,PCA_POS_Y) 
values ('1','DLD50','NOSOLICPAR','NO SE SOLICITA SUBVENCIÓN POR LA CONTRATACIÓN DEL CÓNYUGE DESCENDIENTE Y DEMÁS PARIENTES','6','6','6',null,'0','125','NO SE SOLICITA SUBVENCIÓN POR LA CONTRATACIÓN DEL CÓNYUGE DESCENDIENTE Y DEMÁS PARIENTES','SI','BOOL','NO','NO',null,null,'H',1,1);

update e_pca set pca_bloq='SI' where pca_pro='DLD50' and pca_cod='MANTCONTRA' and pca_bloq='NO';
Insert into E_PCA (PCA_MUN,PCA_PRO,PCA_COD,PCA_DES,PCA_PLT,PCA_TDA,PCA_TAM,PCA_MAS,PCA_OBL,PCA_NOR,PCA_ROT,PCA_ACTIVO,PCA_DESPLEGABLE,PCA_OCULTO,PCA_BLOQ,PLAZO_AVISO,PERIODO_PLAZO,PCA_GROUP,PCA_POS_X,PCA_POS_Y) 
values ('1','DLD50','NOMANTCONTRA','NO HA MANTENIDO CON LA PERSONAS CONTRATADAS UNA RELACIÓN LABORAL PREVIA EN LOS 3 MESES ANTERIORES A LA CONTRATACIÓN','6','6','6',null,'0','126','HA MANTENIDO CON LA PERSONAS CONTRATADAS UNA RELACIÓN LABORAL PREVIA EN LOS 3 MESES ANTERIORES A LA CONTRATACIÓN','SI','BOOL','NO','NO',null,null,'H',1,1);

update e_pca set pca_activo='SI' where pca_pro='DLD50' and pca_cod='NOMINIMIS' and pca_activo='NO';

Insert into E_PCA (PCA_MUN,PCA_PRO,PCA_COD,PCA_DES,PCA_PLT,PCA_TDA,PCA_TAM,PCA_MAS,PCA_OBL,PCA_NOR,PCA_ROT,PCA_ACTIVO,PCA_DESPLEGABLE,PCA_OCULTO,PCA_BLOQ,PLAZO_AVISO,PERIODO_PLAZO,PCA_GROUP,PCA_POS_X,PCA_POS_Y) 
values ('1','DLD50','DATOSVER','QUE LOS DATOS CONSIGNADOS EN LA PRESENTE SOLICITUD SON VERACES','6','6','6',null,'0','127','QUE LOS DATOS CONSIGNADOS EN LA PRESENTE SOLICITUD SON VERACES','SI','BOOL','NO','NO',null,null,'H',1,1);

update e_pca set pca_bloq='SI' where pca_pro='DLD50' and pca_cod='AUTLANB' and pca_bloq='NO';

update e_pca set pca_bloq='SI' where pca_pro='DLD50' and pca_cod='CONSENTSS' and pca_bloq='NO';

update e_pca set pca_bloq='SI' where pca_pro='DLD50' and pca_cod='OPONE1' and pca_bloq='NO';
update e_pca set pca_bloq='SI' where pca_pro='DLD50' and pca_cod='OPONE2' and pca_bloq='NO';
update e_pca set pca_bloq='SI' where pca_pro='DLD50' and pca_cod='OPONE3' and pca_bloq='NO';

Insert into E_PCA (PCA_MUN,PCA_PRO,PCA_COD,PCA_DES,PCA_PLT,PCA_TDA,PCA_TAM,PCA_MAS,PCA_OBL,PCA_NOR,PCA_ROT,PCA_ACTIVO,PCA_DESPLEGABLE,PCA_OCULTO,PCA_BLOQ,PLAZO_AVISO,PERIODO_PLAZO,PCA_GROUP,PCA_POS_X,PCA_POS_Y) 
values ('1','DLD50','OPOSVERIAUTOHHFF','OPOSICION A OBTENER CERTIFICADO ACREDITATIVO DE ENCONTRARSE AL CORRIENTE EN SUS OBLIGACIONES TRIBUTARIAS','1','2','1',null,'0','128','OPOSICION A OBTENER CERTIFICADO ACREDITATIVO DE ENCONTRARSE AL CORRIENTE EN SUS OBLIGACIONES TRIBUTARIAS','SI',null,'NO','NO',null,null,'L','1','1');

Insert into E_PCA (PCA_MUN,PCA_PRO,PCA_COD,PCA_DES,PCA_PLT,PCA_TDA,PCA_TAM,PCA_MAS,PCA_OBL,PCA_NOR,PCA_ROT,PCA_ACTIVO,PCA_DESPLEGABLE,PCA_OCULTO,PCA_BLOQ,PLAZO_AVISO,PERIODO_PLAZO,PCA_GROUP,PCA_POS_X,PCA_POS_Y) 
values ('1','DLD50','OPOSVERIAUTOTGSS','OPOSICION A OBTENER CERTIFICADO ACREDITATIVO DE ENCONTRARSE AL CORRIENTE EN SUS OBLIGACIONES CON LA SEGURIDAD SOCIAL','1','2','1',null,'0','129','OPOSICION A OBTENER CERTIFICADO ACREDITATIVO DE ENCONTRARSE AL CORRIENTE EN SUS OBLIGACIONES CON LA SEGURIDAD SOCIAL','SI',null,'NO','NO',null,null,'L','1','1');

Insert into E_PCA (PCA_MUN,PCA_PRO,PCA_COD,PCA_DES,PCA_PLT,PCA_TDA,PCA_TAM,PCA_MAS,PCA_OBL,PCA_NOR,PCA_ROT,PCA_ACTIVO,PCA_DESPLEGABLE,PCA_OCULTO,PCA_BLOQ,PLAZO_AVISO,PERIODO_PLAZO,PCA_GROUP,PCA_POS_X,PCA_POS_Y) 
values ('1','DLD50','OPOSIDFISC','OPOSICIÓN A OBTENER TARJETA DE IDENTIFICACIÓN FISCAL DE EMPRESA','1','2','1',null,'0','130','OPOSICIÓN A OBTENER TARJETA DE IDENTIFICACIÓN FISCAL DE EMPRESA','SI',null,'NO','NO',null,null,'L','1','1');

Insert into E_PCA (PCA_MUN,PCA_PRO,PCA_COD,PCA_DES,PCA_PLT,PCA_TDA,PCA_TAM,PCA_MAS,PCA_OBL,PCA_NOR,PCA_ROT,PCA_ACTIVO,PCA_DESPLEGABLE,PCA_OCULTO,PCA_BLOQ,PLAZO_AVISO,PERIODO_PLAZO,PCA_GROUP,PCA_POS_X,PCA_POS_Y) 
values ('1','DLD50','OPOSPADRON','OPOSICIÓN A OBTENER PADRÓN','1','2','1',null,'0','131','OPOSICIÓN A OBTENER PADRÓN','SI',null,'NO','NO',null,null,'L','1','1');



___________________________________________________________________________________________________________________________________________________________________________________


select * from e_des where des_cod='DTRT';
select * from e_des_val where des_cod='DTRT';
insert into e_des (des_cod,des_nom) values ('DTRT','DLD50 - TIPO RETRIBUCION');
insert into e_des_val (des_cod,des_val_cod,des_nom,des_val_estado) values ('DTRT','A','ANUAL|URTEAN','A');
insert into e_des_val (des_cod,des_val_cod,des_nom,des_val_estado) values ('DTRT','M','MENSUAL|HILEAN','A');

select * from e_des where des_cod='DTSV';
select * from e_des_val where des_cod='DTSV';
insert into e_des (des_cod,des_nom) values ('DTSV','DLD50 - ESTADO AYUDA');
insert into e_des_val (des_cod,des_val_cod,des_nom,des_val_estado) values ('DTSV','S','SOLICITADA|ESKATUTAKO','A');
insert into e_des_val (des_cod,des_val_cod,des_nom,des_val_estado) values ('DTSV','C','CONCEDIDA|EMANDAKO','A');


--MELANBIDE11_CONTRATACION
ALTER TABLE MELANBIDE11_CONTRATACION ADD CODFORCONT VARCHAR2(20 BYTE);
COMMENT ON COLUMN MELANBIDE11_CONTRATACION.CODFORCONT IS 'Código de la acción formativa finalizada';

ALTER TABLE MELANBIDE11_CONTRATACION ADD DENFORCONT VARCHAR2(150 BYTE);
COMMENT ON COLUMN MELANBIDE11_CONTRATACION.DENFORCONT IS 'Denominación de la acción formativa finalizada';

ALTER TABLE MELANBIDE11_CONTRATACION ADD HORASCONV NUMBER(4,0);
COMMENT ON COLUMN MELANBIDE11_CONTRATACION.HORASCONV IS 'Horas convenio (en caso de Jornada Parcial)';

ALTER TABLE MELANBIDE11_CONTRATACION ADD TIPRSB VARCHAR2(10 BYTE);
COMMENT ON COLUMN MELANBIDE11_CONTRATACION.TIPRSB IS 'Tipo de retribución salarial bruta (coste contrato) A/M';


CREATE SEQUENCE  SEQ_MELANBIDE11_SUBSOLIC  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;

  CREATE TABLE MELANBIDE11_SUBSOLIC 
   (	ID NUMBER(8,0) NOT NULL ENABLE, 
	NUM_EXP VARCHAR2(30 BYTE), 
	ESTADO VARCHAR2(1 BYTE), 
	ORGANISMO VARCHAR2(150 BYTE), 
	OBJETO VARCHAR2(150 BYTE), 
    IMPORTE NUMBER(8,2), 
	FECHA DATE,  
	 CONSTRAINT MELANBIDE11_SUBSOLIC_PK PRIMARY KEY (ID)
 )
 ;

   COMMENT ON COLUMN MELANBIDE11_SUBSOLIC.ESTADO IS 'Estado de la Ayuda';
   COMMENT ON COLUMN MELANBIDE11_SUBSOLIC.ORGANISMO IS 'Organismo concedente';
   COMMENT ON COLUMN MELANBIDE11_SUBSOLIC.OBJETO IS 'Descripción objeto de la ayuda';
   COMMENT ON COLUMN MELANBIDE11_SUBSOLIC.FECHA IS 'Fecha Solicitud o Concesión';



--MELANBIDE11_CONTRATACION
ALTER TABLE MELANBIDE11_CONTRATACION ADD DESTITULACION VARCHAR2(200 BYTE);
COMMENT ON COLUMN MELANBIDE11_CONTRATACION.DESTITULACION IS 'Titulación solicitud';
