CREATE TABLE MELANBIDE03_EXP_IMPR_APA
  (
    NOMBRE_FICHERO VARCHAR2(225 BYTE) NOT NULL,
    NUM_EXPEDIENTE VARCHAR2(30 BYTE) NOT NULL
  )  TABLESPACE FLB_DBS1;
  
ALTER TABLE MELANBIDE03_EXP_IMPR_APA
ADD CONSTRAINT MELANBIDE03_EXP_IMPR_APA_PK PRIMARY KEY (NOMBRE_FICHERO, NUM_EXPEDIENTE) USING INDEX TABLESPACE FLB_IDX1;