CREATE TABLE MELANBIDE03_IMPRESION_APA 
(
  NOMBRE_FICHERO VARCHAR2(255 BYTE) 
, FECHA_GENERACION DATE 
, CONTENIDO BLOB 
)  TABLESPACE FLB_DBS1;

COMMENT ON COLUMN MELANBIDE03_IMPRESION_APA.NOMBRE_FICHERO IS 'Nombre del fichero generado';

COMMENT ON COLUMN MELANBIDE03_IMPRESION_APA.FECHA_GENERACION IS 'Fecha de generación del fichero';

COMMENT ON COLUMN MELANBIDE03_IMPRESION_APA.CONTENIDO IS 'Bytes del fichero';
