Create table MELANBIDE03_CERTIFICADO (
	COD_CERTIFICADO VARCHAR2(8) NOT NULL,
	COD_AREA VARCHAR2(4) NOT NULL,
	COD_FAMILIA VARCHAR2(3) NOT NULL,
	NUM_EXPEDIENTE VARCHAR2(30) NOT NULL,
	COD_ORGANIZACION NUMBER(3,0) NOT NULL,
	COD_PROCEDIMIENTO VARCHAR2(5) NOT NULL,
	PRIMARY KEY(COD_CERTIFICADO, NUM_EXPEDIENTE, COD_ORGANIZACION, COD_PROCEDIMIENTO)
);

COMMENT ON COLUMN MELANBIDE03_CERTIFICADO.COD_CERTIFICADO IS 'Código del certificado seleccionado para el expediente';
COMMENT ON COLUMN MELANBIDE03_CERTIFICADO.COD_AREA IS 'Código del área';
COMMENT ON COLUMN MELANBIDE03_CERTIFICADO.COD_FAMILIA IS 'Código de la familia';
COMMENT ON COLUMN MELANBIDE03_CERTIFICADO.NUM_EXPEDIENTE IS 'Número del expediente';
COMMENT ON COLUMN MELANBIDE03_CERTIFICADO.COD_ORGANIZACION IS 'Código de la organización';
COMMENT ON COLUMN MELANBIDE03_CERTIFICADO.COD_PROCEDIMIENTO IS 'Código del procedimiento al que pertenece ';

/* Tabla MELANBIDE03_CERT_CENTRO */

Create table MELANBIDE03_CERT_CENTRO (
	COD_CERTIFICADO VARCHAR2(8) NOT NULL,
	NUM_EXPEDIENTE VARCHAR2(30) NOT NULL,
	COD_ORGANIZACION NUMBER(3,0) NOT NULL,
	COD_PROCEDIMIENTO VARCHAR2(5) NOT NULL,
	COD_CENTRO VARCHAR2(20) NOT NULL,
	COD_UNIDAD VARCHAR2(8) NOT NULL,
	CENTRO_ACREDITADO NUMBER(1,0) NOT NULL,
	PRIMARY KEY(COD_CERTIFICADO, NUM_EXPEDIENTE, COD_ORGANIZACION, COD_PROCEDIMIENTO, COD_CENTRO, COD_UNIDAD)
);

COMMENT ON COLUMN MELANBIDE03_CERT_CENTRO.COD_CERTIFICADO IS 'Código del certificado seleccionado para el expediente';
COMMENT ON COLUMN MELANBIDE03_CERT_CENTRO.NUM_EXPEDIENTE IS 'Número del expediente';
COMMENT ON COLUMN MELANBIDE03_CERT_CENTRO.COD_ORGANIZACION IS 'Código de la organización';
COMMENT ON COLUMN MELANBIDE03_CERT_CENTRO.COD_PROCEDIMIENTO IS 'Código del procedimiento al que pertenece el expediente';
COMMENT ON COLUMN MELANBIDE03_CERT_CENTRO.COD_CENTRO IS 'Código del centro';
COMMENT ON COLUMN MELANBIDE03_CERT_CENTRO.COD_UNIDAD IS 'Código de la unidad';
COMMENT ON COLUMN MELANBIDE03_CERT_CENTRO.CENTRO_ACREDITADO IS 'Indica si el centro está acreditado para la unidad competencial. Valores: 1->Si, 2->No';

commit;

alter table MELANBIDE03_CERT_CENTRO ADD(
	COD_MOTIVO_ACREDITADO VARCHAR2(8) NULL,
	COD_ORIGEN_ACREDITACION VARCHAR2(8) NULL
);

commit;

COMMENT ON COLUMN MELANBIDE03_CERT_CENTRO.COD_MOTIVO_ACREDITADO IS 'Código del motivo seleccionado para la acreditación';
COMMENT ON COLUMN MELANBIDE03_CERT_CENTRO.COD_ORIGEN_ACREDITACION IS 'Código del origen del cual procede la acreditación';



-- Creación campo suplementario NOAC con los motivos de la acreditación
Insert into E_DES (DES_COD, DES_NOM) values('NOAC','MOTIVO NO ACREDITADO');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values('NOAC','1','CP NO VIGENTE Y NO ESTÁ DENTRO DEL PLAZO DEL DEROGADO');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values('NOAC','2','EL MÓDULO FORMATIVO NO REÚNE EL CÓMPUTO HORARIO ESTIPULADO');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values('NOAC','3','EL CENTRO O ENTIDAD FORMATIVA NO ESTÁ ACREDITADO');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values('NOAC','4','EL CURSO NO ES ACREDITABLE');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values('NOAC','5','NO EXISTE EL CERTIFICADO DE PROFESIONALIDAD');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values('NOAC','6','NO REALIZADO EL MP, NI EXISTE EXENCIÓN');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values('NOAC','7','EL MODULO DE PRÁCTICAS NO REÚNE LAS HORAS CORRESPONDIENTES');
commit;

-- Creación campo suplementario ACCF con los motivos de la acreditacion de los módulos formativos
Insert into E_DES (DES_COD, DES_NOM) values('ACCF','MOTIVO ACREDITACIÓN MÓDULO FORMATIVO');
commit;


--Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values('ACCF','C','Convalidado');
--Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values('ACCF','MF','Módulo formación');
--Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values('ACCF','D','Dispositivo');

Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values('ACCF','EXDI','EXENCIÓN POR DISPOSITIVO');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values('ACCF','EXPA','EXENCIÓN POR PROGRAMAS EN ALTERNANCIA');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values('ACCF','EXSO','EXENCIÓN VÍA SOLICITUD');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values('ACCF','R','REALIZADO');
commit;

Create table MELANBIDE03_MOD_PRACT (
	COD_CERTIFICADO VARCHAR2(8) NOT NULL,
	NUM_EXPEDIENTE VARCHAR2(30) NOT NULL,
	COD_ORGANIZACION NUMBER(3,0) NOT NULL,
	COD_PROCEDIMIENTO VARCHAR2(5) NOT NULL,
	COD_MODULO VARCHAR2(8) NOT NULL,
	MODULO_ACREDITADO NUMBER(1,0) NULL,
	COD_MOTIVO_ACREDITADO VARCHAR2(8) NULL,
	PRIMARY KEY(COD_CERTIFICADO, NUM_EXPEDIENTE, COD_ORGANIZACION, COD_PROCEDIMIENTO, COD_MODULO)
);

COMMENT ON COLUMN MELANBIDE03_MOD_PRACT.COD_CERTIFICADO IS 'Código del certificado asociado al módulo de prácticas';
COMMENT ON COLUMN MELANBIDE03_MOD_PRACT.NUM_EXPEDIENTE IS 'Número de expediente asociado a la información del módulo de prácticas';
COMMENT ON COLUMN MELANBIDE03_MOD_PRACT.COD_ORGANIZACION IS 'Código de la organización a la cual pertenece el expediente';
COMMENT ON COLUMN MELANBIDE03_MOD_PRACT.COD_PROCEDIMIENTO IS 'Código del procedimiento del expediente';
COMMENT ON COLUMN MELANBIDE03_MOD_PRACT.COD_MODULO IS 'Códulo del módulo de prácticas asociado al certificado seleccionado';
COMMENT ON COLUMN MELANBIDE03_MOD_PRACT.MODULO_ACREDITADO IS 'Indica si el módulo está acreditado o no';
COMMENT ON COLUMN MELANBIDE03_MOD_PRACT.COD_MOTIVO_ACREDITADO IS 'Motivo por el cual el módulo se encuentra o no acreditado';
commit;

-- #90628
-- Permitir valores nulos en el COD_CENTRO
Alter table MELANBIDE03_CERT_CENTRO drop primary key;
Alter table MELANBIDE03_CERT_CENTRO add primary key (COD_CERTIFICADO, NUM_EXPEDIENTE, COD_ORGANIZACION, COD_PROCEDIMIENTO, COD_UNIDAD);

--Alter table MELANBIDE03_CERT_CENTRO modify(
--	COD_CENTRO null
--);
Alter table MELANBIDE03_CERT_CENTRO modify COD_CENTRO default null;
commit;


CREATE TABLE MELANBIDE03_REPORT(
    NUM_EXPEDIENTE VARCHAR2(30 BYTE) NOT NULL ENABLE,
    COD_ORGANIZACION NUMBER(3,0) NOT NULL ENABLE,
    FECHA_CREACION DATE NOT NULL ENABLE,
    NOMBRE VARCHAR2(100 BYTE) NOT NULL ENABLE,
    MIME_TYPE VARCHAR2(50 BYTE),
    REPORT BLOB NOT NULL ENABLE,
    PRIMARY KEY (NUM_EXPEDIENTE, COD_ORGANIZACION, FECHA_CREACION));
  
  
COMMENT ON COLUMN MELANBIDE03_REPORT.NUM_EXPEDIENTE IS 'Número del expediente asociado al report';
COMMENT ON COLUMN MELANBIDE03_REPORT.COD_ORGANIZACION IS 'Código de la organización a la cual pertenece el expediente';
COMMENT ON COLUMN MELANBIDE03_REPORT.FECHA_CREACION IS 'Fecha de creación del report';
COMMENT ON COLUMN MELANBIDE03_REPORT.NOMBRE IS 'Nombre del report';

commit;


-- #93190
-- Modificamos la tabla MELANBIDE03_CERT_CENTRO
Alter table MELANBIDE03_CERT_CENTRO ADD(
	CLAVE_REGISTRAL VARCHAR2(30)
);

COMMENT ON COLUMN MELANBIDE03_CERT_CENTRO.CLAVE_REGISTRAL IS 'Clave registral asociada a la unidad competencial';
commit;


  -- Tarea #139404
-- Marcos Rama
-- SOLO LANBIDE

CREATE INDEX IX_MELANBIDE03_CERT_CENTRO ON MELANBIDE03_CERT_CENTRO(COD_CERTIFICADO, NUM_EXPEDIENTE, COD_ORGANIZACION,COD_PROCEDIMIENTO,COD_CENTRO,COD_UNIDAD,CENTRO_ACREDITADO,COD_MOTIVO_ACREDITADO,COD_ORIGEN_ACREDITACION,CLAVE_REGISTRAL);	

commit;
