REM INSERTING into IDEN_ERR
SET DEFINE OFF;
Insert into IDEN_ERR (IDEN_ERR_ID,IDEN_ERR_DESC_C,IDEN_ERR_DESC,IDEN_ERR_TIPO,IDEN_ERR_CRIT,IDEN_ERR_MEN_AVISO,IDEN_ERR_MAILS,IDEN_ERR_ACC,IDEN_ERR_MOD,FEC_HOR_INS,FEC_HOR_ACT) values ('TRAMITACION_AERTE_001','Error en el job de Inicio automático de expedientes AERTE. Error al llamar al SW iniciarExpediente.','Error en el job de Inicio automático de expedientes AERTE. Error al llamar al SW iniciarExpediente.','2','1','Se ha registrado el siguiente error: código: TRAMITACION_AERTE_001, descripción: Error en el job de Inicio automático de expedientes AERTE. Error al llamar al SW iniciarExpediente. Para más información consulte el módulo de gestión de errores.','ext.david.guerrero@altia.es;
r.lopez.frias@ibermatica.com;
o.isasi-isasmendi@ibermatica.com;
i.azkarate@ibermatica.com;
i.apraiz@ibermatica.com;
kepa.gonzalez@altia.es;
jose.delgado@altia.es;i.artutxa@ibermatica.com;e.rodriguez.zabalza@ibermatica.com',null,'MELANBIDE77',to_timestamp(SYSDATE),to_timestamp(SYSDATE));
Insert into IDEN_ERR (IDEN_ERR_ID,IDEN_ERR_DESC_C,IDEN_ERR_DESC,IDEN_ERR_TIPO,IDEN_ERR_CRIT,IDEN_ERR_MEN_AVISO,IDEN_ERR_MAILS,IDEN_ERR_ACC,IDEN_ERR_MOD,FEC_HOR_INS,FEC_HOR_ACT) values ('TRAMITACION_AERTE_002','Error en el job de Inicio automático de expedientes AERTE. Error al llamar al SW asociarExpRegistro.','Error en el job de Inicio automático de expedientes AERTE. Error al llamar al SW asociarExpRegistro.','2','1','Se ha registrado el siguiente error: código: TRAMITACION_AERTE_002, descripción: Error en el job de Inicio automático de expedientes AERTE. Error al llamar al SW asociarExpRegistro. Para más información consulte el módulo de gestión de errores.','ext.david.guerrero@altia.es;
r.lopez.frias@ibermatica.com;
o.isasi-isasmendi@ibermatica.com;
i.azkarate@ibermatica.com;
i.apraiz@ibermatica.com;
kepa.gonzalez@altia.es;
jose.delgado@altia.es;i.artutxa@ibermatica.com;e.rodriguez.zabalza@ibermatica.com',null,'MELANBIDE77',to_timestamp(SYSDATE),to_timestamp(SYSDATE));
Insert into IDEN_ERR (IDEN_ERR_ID,IDEN_ERR_DESC_C,IDEN_ERR_DESC,IDEN_ERR_TIPO,IDEN_ERR_CRIT,IDEN_ERR_MEN_AVISO,IDEN_ERR_MAILS,IDEN_ERR_ACC,IDEN_ERR_MOD,FEC_HOR_INS,FEC_HOR_ACT) values ('TRAMITACION_AERTE_003','Error en el job de Inicio automático de expedientes AERTE. No existe solicitud asociada al registro.','Error en el job de Inicio automático de expedientes AERTE. No existe solicitud asociada al registro.','1','1','Se ha registrado el siguiente error: código: TRAMITACION_AERTE_003, descripción: Error en el job de Inicio automático de expedientes AERTE. No existe solicitud asociada al registro. Para más información consulte el módulo de gestión de errores.','ext.david.guerrero@altia.es;
r.lopez.frias@ibermatica.com;
o.isasi-isasmendi@ibermatica.com;
i.azkarate@ibermatica.com;
i.apraiz@ibermatica.com;
kepa.gonzalez@altia.es;
jose.delgado@altia.es;i.artutxa@ibermatica.com;e.rodriguez.zabalza@ibermatica.com',null,'MELANBIDE77',to_timestamp(SYSDATE),to_timestamp(SYSDATE));
Insert into IDEN_ERR (IDEN_ERR_ID,IDEN_ERR_DESC_C,IDEN_ERR_DESC,IDEN_ERR_TIPO,IDEN_ERR_CRIT,IDEN_ERR_MEN_AVISO,IDEN_ERR_MAILS,IDEN_ERR_ACC,IDEN_ERR_MOD,FEC_HOR_INS,FEC_HOR_ACT) values ('TRAMITACION_AERTE_004','Error en el job de Inicio automático de expedientes AERTE. Error al llamar al grabadoDatosSuplementariosSolicitud.','Error en el job de Inicio automático de expedientes AERTE. Error al llamar al grabadoDatosSuplementariosSolicitud.','1','1','Se ha registrado el siguiente error: código: TRAMITACION_AERTE_004, descripción: Error en el job de Inicio automático de expedientes AERTE. Error al llamar al grabadoDatosSuplementariosSolicitud. Para más información consulte el módulo de gestión de errores.','ext.david.guerrero@altia.es;
r.lopez.frias@ibermatica.com;
o.isasi-isasmendi@ibermatica.com;
i.azkarate@ibermatica.com;
i.apraiz@ibermatica.com;
kepa.gonzalez@altia.es;
jose.delgado@altia.es;i.artutxa@ibermatica.com;e.rodriguez.zabalza@ibermatica.com',null,'MELANBIDE77',to_timestamp(SYSDATE),to_timestamp(SYSDATE));
Insert into IDEN_ERR (IDEN_ERR_ID,IDEN_ERR_DESC_C,IDEN_ERR_DESC,IDEN_ERR_TIPO,IDEN_ERR_CRIT,IDEN_ERR_MEN_AVISO,IDEN_ERR_MAILS,IDEN_ERR_ACC,IDEN_ERR_MOD,FEC_HOR_INS,FEC_HOR_ACT) values ('TRAMITACION_AERTE_005','Error en el job de Inicio automático de expedientes AERTE. Error al avanzar el tramite.','Error en el job de Inicio automático de expedientes AERTE. Error al avanzar el tramite.','2','1','Se ha registrado el siguiente error: código: TRAMITACION_AERTE_005, descripción: Error en el job de Inicio automático de expedientes AERTE. Error al avanzar el tramite. Para más información consulte el módulo de gestión de errores.','ext.david.guerrero@altia.es;
r.lopez.frias@ibermatica.com;
o.isasi-isasmendi@ibermatica.com;
i.azkarate@ibermatica.com;
i.apraiz@ibermatica.com;
kepa.gonzalez@altia.es;
jose.delgado@altia.es;i.artutxa@ibermatica.com;e.rodriguez.zabalza@ibermatica.com',null,'MELANBIDE77',to_timestamp(SYSDATE),to_timestamp(SYSDATE));
Insert into IDEN_ERR (IDEN_ERR_ID,IDEN_ERR_DESC_C,IDEN_ERR_DESC,IDEN_ERR_TIPO,IDEN_ERR_CRIT,IDEN_ERR_MEN_AVISO,IDEN_ERR_MAILS,IDEN_ERR_ACC,IDEN_ERR_MOD,FEC_HOR_INS,FEC_HOR_ACT) values ('TRAMITACION_AERTE_006','Error en el job de Inicio automático de expedientes AERTE. El número de solicitud recuperado no coincide con el asociado al registro.','Error en el job de Inicio automático de expedientes AERTE. El número de solicitud recuperado no coincide con el asociado al registro.','1','1','Se ha registrado el siguiente error: código: TRAMITACION_AERTE_006, descripción: Error en el job de Inicio automático de expedientes AERTE. El número de solicitud recuperado no coincide con el asociado al registro. Para más información consulte el módulo de gestión de errores.','ext.david.guerrero@altia.es;
r.lopez.frias@ibermatica.com;
o.isasi-isasmendi@ibermatica.com;
i.azkarate@ibermatica.com;
i.apraiz@ibermatica.com;
kepa.gonzalez@altia.es;
jose.delgado@altia.es;i.artutxa@ibermatica.com;e.rodriguez.zabalza@ibermatica.com',null,'MELANBIDE77',to_timestamp(SYSDATE),to_timestamp(SYSDATE));