-------------------------------
--------- ORI_ENTIDAD ---------
-------------------------------

ALTER TABLE ORI_ENTIDAD ADD (ORI_ENT_ADMLOCAL_VAL VARCHAR2(1 BYTE));
ALTER TABLE ORI_ENTIDAD ADD (ORI_ENT_SUPRAMUN_VAL VARCHAR2(1 BYTE));
ALTER TABLE ORI_ENTIDAD ADD (ORI_EXP_COD_VAL NUMBER(8,0));
ALTER TABLE ORI_ENTIDAD ADD (ORI_ENT_ACOLOCACION_VAL VARCHAR2(1 BYTE));
ALTER TABLE ORI_ENTIDAD ADD (ORI_ENT_NUMTRAB_VAL NUMBER(7,2));
ALTER TABLE ORI_ENTIDAD ADD (ORI_ENT_NUMTRAB_DISC_VAL NUMBER(7,2));
ALTER TABLE ORI_ENTIDAD ADD (ORI_ENT_OTROS_VAL VARCHAR2(100 BYTE));
ALTER TABLE ORI_ENTIDAD ADD (ORI_NUM_PERS_ATENDIDAS NUMBER(8, 0));

-------------------------------
-------- ORI_AUDITORIA --------
-------------------------------

ALTER TABLE ORI_AUDITORIA ADD (COD_PROCEDIMIENTO VARCHAR2(5 BYTE));

--------------------------------
-------- ORI_AMBITOS_CE --------
--------------------------------

ALTER TABLE ORI_AMBITOS_CE ADD (ORI_AMB_DISTR  NUMBER(1) );
