ALTER TABLE ORI_ENTIDAD ADD(ORI_ENT_PORTRAB_DISC NUMBER(7,2), ORI_ENT_PORTRAB_DISC_VAL	NUMBER(7,2));
COMMENT ON COLUMN ORI_ENTIDAD.ORI_ENT_PORTRAB_DISC IS 'PORCENTAJE DE EMPLEADOS DISCAPACITADOS EN LA ENTIDAD';
COMMENT ON COLUMN ORI_ENTIDAD.ORI_ENT_PORTRAB_DISC_VAL IS 'PORCENTAJE DE EMPLEADOS DISCAPACITADOS VALIDADOS EN LA ENTIDAD';
