-- en preproduccion desde el 24/04/14.
ALTER TABLE ORI_ENTIDAD ADD (ORI_ENT_ADMLOCAL_VAL VARCHAR2(1 BYTE) );
ALTER TABLE ORI_ENTIDAD ADD (ORI_ENT_SUPRAMUN_VAL VARCHAR2(1 BYTE) );
ALTER TABLE ORI_ENTIDAD ADD (ORI_EXP_COD_VAL NUMBER(8, 0) );
ALTER TABLE ORI_ENTIDAD ADD (ORI_ENT_OTROS_VAL VARCHAR2(100 BYTE) );
ALTER TABLE ORI_ENTIDAD ADD (ORI_ENT_ACOLOCACION_VAL VARCHAR2(1 BYTE) );
ALTER TABLE ORI_ENTIDAD ADD (ORI_ENT_NUMTRAB_VAL NUMBER(7, 2) );
ALTER TABLE ORI_ENTIDAD ADD (ORI_ENT_NUMTRAB_DISC_VAL NUMBER(7, 2) );
ALTER TABLE ORI_ENTIDAD ADD (ORI_NUM_PERS_ATENDIDAS NUMBER(8) );


--AÑADIDO EL 29/04/14 PARA GESTIONAR LOS AMBITOS DISTRIBUIDOS. Solo se debe adjudicar a uno.
alter table ORI_AMBITOS_CE add (ORI_AMB_DISTR  NUMBER(1) );