

 CREATE SEQUENCE  SEQ_MELANBIDE83_FACTURAS  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE ORDER NOCYCLE;

  CREATE TABLE MELANBIDE83_FACTURAS 
   (	"ID" NUMBER(8,0), 
	"NUM_EXP" VARCHAR2(30 BYTE), 
	"ESTADO" VARCHAR2(1 BYTE), 
	"FECHA_FACTURA" DATE, 
	"CODIGO_CONCEPTO" VARCHAR2(3 BYTE), 
	"IMPORTE" NUMBER(14,2),  
	"ENTREGADO_JUSTIF" VARCHAR2(1 BYTE), 
	"OBSERVACIONES" CLOB,
	"IMPUTADA" VARCHAR2(1 BYTE), 
	 CONSTRAINT "MELANBIDE83_FACTURAS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLB_DBS1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLB_DBS1" 
 LOB ("OBSERVACIONES") STORE AS BASICFILE (
  TABLESPACE "FLB_DBS1" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN MELANBIDE83_FACTURAS."ID" IS 'Índice secuencial y clave primaria de la tabla';
   COMMENT ON COLUMN MELANBIDE83_FACTURAS."NUM_EXP" IS 'Número de expediente';
   COMMENT ON COLUMN MELANBIDE83_FACTURAS."ESTADO" IS 'Estado de la factura. A-Aceptada;N-No aceptada';
   COMMENT ON COLUMN MELANBIDE83_FACTURAS."FECHA_FACTURA" IS 'Fecha de la factura';
   COMMENT ON COLUMN MELANBIDE83_FACTURAS."CODIGO_CONCEPTO" IS 'Identificador de concepto.';
   COMMENT ON COLUMN MELANBIDE83_FACTURAS."IMPORTE" IS 'Importe de la factura';
   COMMENT ON COLUMN MELANBIDE83_FACTURAS."ENTREGADO_JUSTIF" IS 'Indica si se ha entregado el justificante de pago. S-Si;N-No';
   COMMENT ON COLUMN MELANBIDE83_FACTURAS."OBSERVACIONES" IS 'Comentarios sobre la factura';
   COMMENT ON COLUMN MELANBIDE83_FACTURAS."IMPUTADA" IS 'Indica si la factura se ha tenido en cuenta para la subvención. S-Si;N-No';
   COMMENT ON TABLE MELANBIDE83_FACTURAS  IS 'Relación de facturas de justificación del procedimiento ATASE';


--DESPLEGABLE CONCEPTOS FACTURAS
Insert into E_DES (DES_COD,DES_NOM) values ('CTAT','CONCEPTO FACTURAS ATASE');

Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('CTAT','1','ARRENDAMIENTO DE LOCAL DE NEGOCIO');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM) values ('CTAT','2','CUOTAS RELATIVAS A LA COTIZACIÓN EN EL RETA');






