/* Generated by Together */
package es.altia.flexia.integracion.moduloexterno.melanbide03;

import es.altia.agora.business.escritorio.UsuarioValueObject;
import es.altia.agora.business.util.GeneralValueObject;
import es.altia.common.exception.*;
import es.altia.common.service.config.*;
import es.altia.common.service.jdbc.XAJDBCWrapper;
import es.altia.common.service.log.*;
import es.altia.flexia.integracion.moduloexterno.melanbide03.exception.MELANBIDE03Exception;
import es.altia.flexia.integracion.moduloexterno.melanbide03.i18n.MeLanbide03I18n;
import es.altia.flexia.integracion.moduloexterno.melanbide03.manager.MeLanbide03Manager;
import es.altia.flexia.integracion.moduloexterno.melanbide03.util.ConfigurationParameter;
import es.altia.flexia.integracion.moduloexterno.melanbide03.util.ConstantesMeLanbide03;
import es.altia.flexia.integracion.moduloexterno.melanbide03.util.MeLanbide03ReportFormatEnum;
import es.altia.flexia.integracion.moduloexterno.melanbide03.util.MeLanbide03ReportHelper;
import es.altia.flexia.integracion.moduloexterno.melanbide03.vo.MeLanbide03GenerateReportVO;
import es.altia.flexia.integracion.moduloexterno.melanbide03.vo.MeLanbide03InteresadoGenerateReportVO;
import es.altia.flexia.integracion.moduloexterno.melanbide03.vo.MeLanbide03UnidadCompetencialGenerateReportVO;
import es.altia.flexia.integracion.moduloexterno.melanbide03.vo.reports.Subreport;
import es.altia.util.conexion.AdaptadorSQLBD;
import es.altia.util.sqlxmlpdf.GeneralPDF;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileOutputStream;

import java.lang.Runnable;
import java.lang.Thread;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.List;
import java.util.Map;
import java.util.ResourceBundle;
import java.util.Vector;

import javax.naming.Context;
//import javax.transaction.UserTransaction;



public class EjecutaImpresion implements Runnable{
    /**
     * Esto es un código que sigue el patrón de diseño <code>Singleton</code>
     * Los métodos de negocio gestionan que la persistencia sea manual o automática
     * Es protected, por lo que la única manera de instanciar esta clase es usando el factory method <code>getInstance</code>
     */
    public EjecutaImpresion() {
        //Queremos usar el servicio de log
        m_Log = LogServiceHelper.getLog(this.getClass().getName());
    }
    

    private Thread comprobAdecAutThread = null;
     String resultado = null; 
     String expParam = null;
     int codOrganizacion = 0;
     String subreportName = null; 
     AdaptadorSQLBD adapt = null;
     UsuarioValueObject usuario = null;
    


    public void start( String result, String expP, int codOrg, String subreportNa,  
                UsuarioValueObject usu, AdaptadorSQLBD adaptador) {
        //m_Log.error("start comprobacion adecuacion automática: " + id_oferta);
        comprobAdecAutThread = new Thread(this, "EjecutaImpresion");
        resultado = result; 
        expParam = expP;
        codOrganizacion = codOrg; 
        subreportName = subreportNa;
        adapt = adaptador;
        usuario = usu;
        comprobAdecAutThread.start();
    }

    public void run() {
        String masterReportName = "";
        MeLanbide03Manager meLanbide03Manager = MeLanbide03Manager.getInstance();
            
            
            Subreport subreport = null;
            byte[] pdf = null;
            
            try
            {
                List<Subreport> subreportList = new ArrayList<Subreport>();
                Map<String, Object> reportParams = new HashMap<String, Object>();
                List<GeneralValueObject> expedientes = new ArrayList<GeneralValueObject>();
                List<GeneralValueObject> documentos = new ArrayList<GeneralValueObject>();
                String nomDoc = "_blank_";
                //Recuperar los datos
                ArrayList<MeLanbide03InteresadoGenerateReportVO> listaInteresados = new ArrayList<MeLanbide03InteresadoGenerateReportVO>();
                ArrayList<MeLanbide03UnidadCompetencialGenerateReportVO> listaUnidades = new ArrayList<MeLanbide03UnidadCompetencialGenerateReportVO>();
                MeLanbide03GenerateReportVO generateReport = null;
                String xmlReport = null;
                
                String[] expedientesPendientes = new String[0];
                
                
                if(expParam != null && !expParam.equals(""))
                {
                    expedientesPendientes = expParam.split("-");
                }
                
                String xpathReport = ConfigurationParameter.getParameter(ConstantesMeLanbide03.XPATH_PLANTILLA_PDF_APA, ConstantesMeLanbide03.FICHERO_PROPIEDADES);
                
                String numExp = null;
                String claveRegistral = null;
                int cont = 0;
                while(cont < expedientesPendientes.length && resultado.equals(ConstantesMeLanbide03.OPERACION_CORRECTA))
                {
                    numExp = expedientesPendientes[cont];
                //machacamos report original por el que corresponda segúin año de fecha de presentación    
               int anoFechaPresentacion = 0;                
               anoFechaPresentacion = meLanbide03Manager.getAnoFechaPresentacion(numExp,adapt);                
                if(anoFechaPresentacion<=2012){//Javier 
                    subreportName = ConfigurationParameter.getParameter(ConstantesMeLanbide03.NOMBRE_PLANTILLA_REPORT_PDF_APAJ, ConstantesMeLanbide03.FICHERO_PROPIEDADES);
                   
                }
                else if(anoFechaPresentacion>2012){//Adolfo
                    subreportName = ConfigurationParameter.getParameter(ConstantesMeLanbide03.NOMBRE_PLANTILLA_REPORT_PDF_APA, ConstantesMeLanbide03.FICHERO_PROPIEDADES);
                   
                }            
                    
                                   
                    
                    
                    
                    generateReport = new MeLanbide03GenerateReportVO();
                    
                    try
                    {
                        claveRegistral = MELANBIDE03.getInstance().generarClaveRegistral(codOrganizacion, numExp);
                        if(claveRegistral == null  || claveRegistral.equals(""))
                        {
                            resultado = ConstantesMeLanbide03.ERROR_GENERANDO_REPORT;
                        }
                    }
                    catch(Exception ex)
                    {
                        ex.printStackTrace();
                    }
                    
                    xmlReport = "";
                    try 
                    {
                        listaInteresados = MeLanbide03Manager.getInstance().getInteresadosReport(numExp, codOrganizacion, adapt);
                    } 
                    catch (MELANBIDE03Exception ex) 
                    {
                        ex.printStackTrace();
                        m_Log.error("Se ha producido un error recuperando interesados para el inform: "+ex.getMessage());
                        //resultado = ConstantesMeLanbide03.ERROR_RECUPERANDO_INTERESADOS;
                    }
        
                    if(resultado.equalsIgnoreCase(ConstantesMeLanbide03.OPERACION_CORRECTA))
                    {
                        try 
                        {
                            listaUnidades = MeLanbide03Manager.getInstance().getUnidadesCompetencialesReport(numExp, codOrganizacion, adapt);
                        } 
                        catch (MELANBIDE03Exception ex) 
                        {
                            ex.printStackTrace();
                            m_Log.error("Se ha producido un error recuperando la informacion de certificado y unidades para el report: " + ex.getMessage());
                            //resultado = ConstantesMeLanbide03.ERROR_UNIDADES_CERTIFICADO;
                        }
                    }
                    
                    if(resultado.equalsIgnoreCase(ConstantesMeLanbide03.OPERACION_CORRECTA))
                    {
                        generateReport.setInteresados(listaInteresados);
                        generateReport.setUnidades(listaUnidades);
                    }

                    if(resultado.equalsIgnoreCase(ConstantesMeLanbide03.OPERACION_CORRECTA))
                    {
                        m_Log.debug(numExp+" - listaInteresados: "+(listaInteresados != null ? listaInteresados.size() : "null"));
                        m_Log.debug(numExp+" - listaUnidades: "+(listaUnidades != null ? listaUnidades.size() : "null"));
                        xmlReport = MeLanbide03ReportHelper.generarXML(generateReport);
                    }
                    
                    if(generateReport.getInteresados() != null && generateReport.getInteresados().size() > 0)
                    {
                        if(generateReport.getUnidades() != null && generateReport.getUnidades().size() > 0)
                        {
                            try
                            {
                                subreport = MeLanbide03ReportHelper.inicializarSubreport(subreportName, xmlReport, xpathReport, reportParams);
                                subreportList.add(subreport);
                            }
                            catch(Exception ex)
                            {
                                resultado = ConstantesMeLanbide03.ERROR_GENERANDO_REPORT;
                            }
                        }
                    }
                    cont++;
                }
                
                if(!resultado.equals(ConstantesMeLanbide03.OPERACION_CORRECTA))
                {
                    subreportList.clear();
                    m_Log.debug("REPORT VACIO");
                    reportParams.put("mensaje", MeLanbide03I18n.getInstance().getMensaje(usuario.getIdioma(), "msg.error.recuperarDatosPdfPendientes"));
                    masterReportName = ConfigurationParameter.getParameter(ConstantesMeLanbide03.NOMBRE_PLANTILLA_GENERAL_VACIO, ConstantesMeLanbide03.FICHERO_PROPIEDADES);
                }
                else if(subreportList.isEmpty())
                {
                    subreportList.clear();
                    m_Log.debug("REPORT VACIO");
                    reportParams.put("mensaje", MeLanbide03I18n.getInstance().getMensaje(usuario.getIdioma(), "msg.informePendientesVacío"));
                    masterReportName = ConfigurationParameter.getParameter(ConstantesMeLanbide03.NOMBRE_PLANTILLA_GENERAL_VACIO, ConstantesMeLanbide03.FICHERO_PROPIEDADES);
                }
                else
                {
                    m_Log.debug("REPORT LLENO");
                    masterReportName = ConfigurationParameter.getParameter(ConstantesMeLanbide03.NOMBRE_PLANTILLA_GENERAL, ConstantesMeLanbide03.FICHERO_PROPIEDADES);
                }
                
                pdf = MeLanbide03ReportHelper.runMasterReportWithSubreports(masterReportName, reportParams, subreportList, MeLanbide03ReportFormatEnum.PDF);
                
                if(pdf != null && pdf.length > 0)
                {
                    try
                    {
                        ResourceBundle m_Conf = ResourceBundle.getBundle("common");

                        File directorioTemp = new File(m_Conf.getString("PDF.base_dir"));
                        if(!directorioTemp.exists())
                        {
                            directorioTemp.mkdirs();
                        }
                        File informe = File.createTempFile("expedientesCEPAP", ".pdf", directorioTemp);
                        nomDoc = informe.getName();
                        //FileOutputStream archivoSalida = new FileOutputStream(informe);
                        //archivoSalida.close();


                        FileOutputStream fileOutput = new FileOutputStream(informe);
                        BufferedOutputStream bufferedOutput = new BufferedOutputStream(fileOutput);
                        bufferedOutput.write(pdf, 0, pdf.length);
                        bufferedOutput.flush();
                        bufferedOutput.close();
                        fileOutput.flush();
                        fileOutput.close();
                        
                        resultado = ConstantesMeLanbide03.OPERACION_CORRECTA;
                    }
                    catch(Exception ex)
                    {
                        ex.printStackTrace();
                        m_Log.error("Se ha producido un error generando pdf expedientes pendientes apa: "+ex.getMessage());
                        resultado = ConstantesMeLanbide03.ERROR_GENERANDO_REPORT;
                    }
                }
                else
                {
                    resultado = ConstantesMeLanbide03.ERROR_GENERANDO_REPORT;
                }
                
                if(resultado.equals(ConstantesMeLanbide03.OPERACION_CORRECTA))
                {
                    int result = MeLanbide03Manager.getInstance().guardarPdfApaPendientes(nomDoc, pdf, adapt);
                    if(result == 0)
                    {
                        resultado = ConstantesMeLanbide03.ERROR_GENERANDO_REPORT;
                    }
                    //int resInsertImpr = inserta_MELANBIDE03_IMPRESION_CEPAP(nomDoc, pdf, adapt);
                    m_Log.error("antes de inserta_MELANBIDE03_EXP_IMPR_CEPAP");
                    int resInsertImprExp = MELANBIDE03.getInstance().inserta_MELANBIDE03_EXP_IMPR_CEPAP(nomDoc, expedientesPendientes, adapt);
                }
                
                if(resultado.equals(ConstantesMeLanbide03.OPERACION_CORRECTA))
                {
                    //Avanzamos los expedientes
                    int res = 0;
                    m_Log.error("Resultado antes de avanzarTramite: "+res);
                    String codigoTramite = MeLanbide03Manager.getInstance().
                            getCodigoInternoTramite(codOrganizacion, ConstantesMeLanbide03.CODIGO_PROCEDIMIENTO,
                                                    ConfigurationParameter.getParameter(ConstantesMeLanbide03.CODIGO_TRAMITE_IMPRESION_APA, ConstantesMeLanbide03.FICHERO_PROPIEDADES),
                                                    adapt);
                    
                    res = MELANBIDE03.getInstance().finalizarAvanzarTramite(codOrganizacion, codigoTramite, usuario.getParamsCon(), usuario, expedientesPendientes);
                    m_Log.error("Resultado despues de avanzarTramite: "+res);
                }
                
                if(resultado.equals(ConstantesMeLanbide03.OPERACION_CORRECTA))
                {                    
                    try
                    {
                        expedientes = MeLanbide03Manager.getInstance().getExpedientesApaPendientes(adapt);
                    }
                    catch(Exception ex)
                    {
                        ex.printStackTrace();
                        m_Log.error("Se ha producido un error recuperando expedientes para actualizr pantalla pendientes APA: "+ex.getMessage());
                    }
                    try
                    {
                        documentos = MeLanbide03Manager.getInstance().getFicherosImpresionGenerados(adapt);
                    }
                    catch(Exception ex)
                    {
                        ex.printStackTrace();
                        m_Log.error("Se ha producido un error recuperando documentos para actualizr pantalla pendientes APA: "+ex.getMessage());
                    }
                }
                else
                {
                    //Mostrar mensaje de error
                }
            }
            catch(Exception ex)
            {
                ex.printStackTrace();
                m_Log.error("Se ha producido un error generando pdf expedientes pendientes apa: "+ex.getMessage());
            }
        comprobAdecAutThread.stop();
    }

    /*
     * Declaracion de servicios
     */
    Log m_Log;
    
}
