/* Generated by Together */
package es.altia.flexia.integracion.moduloexterno.melanbide68;

import es.altia.agora.business.escritorio.UsuarioValueObject;
import es.altia.agora.business.util.GeneralValueObject;
import es.altia.common.exception.*;
import es.altia.common.service.config.*;
import es.altia.common.service.jdbc.XAJDBCWrapper;
import es.altia.common.service.log.*;
import es.altia.flexia.integracion.moduloexterno.melanbide68.dao.MeLanbide68DAO;
import es.altia.flexia.integracion.moduloexterno.melanbide68.exception.ExcelRowMappingException;
import es.altia.flexia.integracion.moduloexterno.melanbide68.manager.MeLanbide68Manager;
import es.altia.flexia.integracion.moduloexterno.melanbide68.util.MeLanbide68MappingUtils;
import es.altia.flexia.integracion.moduloexterno.melanbide68.vo.ObjetoSGAVO;
import es.altia.util.conexion.AdaptadorSQLBD;
import es.altia.util.conexion.BDException;
import es.altia.util.sqlxmlpdf.GeneralPDF;
import java.io.BufferedOutputStream;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileOutputStream;

import java.lang.Runnable;
import java.lang.Thread;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.List;
import java.util.Map;
import java.util.ResourceBundle;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.naming.Context;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.struts.upload.FormFile;
//import javax.transaction.UserTransaction;



public class EjecutaCargaDatosSGA implements Runnable{
    
    
    public EjecutaCargaDatosSGA() {
        //Queremos usar el servicio de log
        m_Log = LogServiceHelper.getLog(this.getClass().getName());
    }
    

    private Thread comprobAdecAutThread = null;
     FormFile fichero =null;
     AdaptadorSQLBD adaptador =null;
    


    public void start(FormFile file, AdaptadorSQLBD adapt ) { 
        comprobAdecAutThread = new Thread(this, "EjecutaCargaDatosSGA");
        fichero = file;
        adaptador = adapt;
        comprobAdecAutThread.start();
    }

    public void run() {
        int i =0;
        String resultadoProceso ="OK";
        String mensajeErrorProceso="";
        String detalleErrorRegistro="";
        int resultadoRegistro=0;
        int registrosProcesadosInsertados=0;
        int registrosProcesadosModificados=0;
        int registrosProcesadosNOOK=0;
        Integer idSecuenciaProceso=0;
        MeLanbide68DAO meLanbide68DAO = MeLanbide68DAO.getInstance();
        Connection con =null;
        try {
            con = adaptador.getConnection();
            idSecuenciaProceso=meLanbide68DAO.insertarProcesoCargaSGA(fichero.getFileName(),new Date(), con);
           
            byte[] data = fichero.getFileData();
            ByteArrayInputStream bais = new ByteArrayInputStream(data);
            HSSFWorkbook workbook = new HSSFWorkbook(bais);
            
            HSSFSheet sheet = workbook.getSheetAt(0);      
            
            int filaIni = sheet.getFirstRowNum();
            int filaFin = sheet.getLastRowNum();

            HSSFRow row = null;
            List<ObjetoSGAVO> filasImportar = new ArrayList<ObjetoSGAVO>();
            ObjetoSGAVO objSGA = null;
            
            for(i = filaIni+1; i <= filaFin; i++)
            {
                detalleErrorRegistro="";    
                try {
                    row = sheet.getRow(i);
                    objSGA = null;
                    objSGA = (ObjetoSGAVO)MeLanbide68MappingUtils.getInstance().mapRow(row, ObjetoSGAVO.class);
                    if(objSGA != null)
                    {
                        objSGA.setNumFila_carga(i+1);
                        filasImportar.add(objSGA);
                    }
                }
                catch(ExcelRowMappingException erme)
                {            
                    resultadoProceso ="OKERR";
                    registrosProcesadosNOOK++;
                    resultadoRegistro=2;
                    detalleErrorRegistro=erme.getMensaje();
                    String codSGA = objSGA==null?"":objSGA.getCodigoSGA();
                    meLanbide68DAO.insertarRegistroCargaSGA(idSecuenciaProceso,i+1, codSGA, new Date(), resultadoRegistro, detalleErrorRegistro, con);
                } 
            }
            if(filasImportar != null && filasImportar.size() > 0)
            {
                adaptador.inicioTransaccion(con);
                MeLanbide68Manager meLanbide68Manager = MeLanbide68Manager.getInstance();
                for (ObjetoSGAVO o : filasImportar ){
                    detalleErrorRegistro="";
                    try {
                        if (o.getExpedienteSGA().length()>=10 && meLanbide68Manager.existeRegistroRES(o.getExpedienteSGA(),con)){
                            if (meLanbide68Manager.existeObjetoSGA(o.getExpedienteSGA(),con)){                                
                                registrosProcesadosModificados++;
                                resultadoRegistro=1;
                            } else {
                                
                                registrosProcesadosInsertados++;
                                resultadoRegistro=0;
                            }
                            meLanbide68Manager.modificarObjetoSGA(o,con);
                        } else {                            
                            resultadoProceso ="OKERR";
                            registrosProcesadosNOOK++;
                            resultadoRegistro=2;
                            detalleErrorRegistro="No existe un Registro RES con ese ejercicio y número";
                            
                        }
                    } catch (BDException e) {
                        m_Log.error("Se ha producido una excepcion en la BBDD importando objetos SGA", e);
                        resultadoProceso ="OKERR";
                        registrosProcesadosNOOK++;
                        resultadoRegistro=2;
                        detalleErrorRegistro="Error al guardar el registro en BBDD";
                    } catch (NumberFormatException nfe) {
                        m_Log.error("Se ha producido una excepcion al convertir los 10 primeros dígutos del expediente en número ", nfe);
                        resultadoProceso ="OKERR";
                        registrosProcesadosNOOK++;
                        resultadoRegistro=2;
                        detalleErrorRegistro="Los primeros 10 dígitos del expediente SGA deben ser número.";
                    }finally {
                        meLanbide68DAO.insertarRegistroCargaSGA(idSecuenciaProceso, o.getNumFila_carga(), o.getCodigoSGA(), new Date(), resultadoRegistro, detalleErrorRegistro, con);
                    }
                }
                
            }                     
        } 
        catch(Exception ex)
        {
            ex.printStackTrace();
            resultadoProceso ="ERROR";
            mensajeErrorProceso=ex.getMessage();            
        }
        finally{
            try {
                meLanbide68DAO.modificarProcesoCargaSGA(idSecuenciaProceso, new Date(), resultadoProceso, registrosProcesadosInsertados, registrosProcesadosModificados, registrosProcesadosNOOK, mensajeErrorProceso, con);
                adaptador.finTransaccion(con);
                if (adaptador!= null) adaptador.devolverConexion(con);
            } catch (Exception ex) {
                Logger.getLogger(EjecutaCargaDatosSGA.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        comprobAdecAutThread.stop();
    }

    /*
     * Declaracion de servicios
     */
    Log m_Log;
    
}
