#Codigos de los campos
codigo.resfav=RESFAV
codigo.fecIniContrato=FECINICONTRATO
codigo.fecAltaSS=FECALTASS
codigo.solicEnPlazo=SOLICENPLAZO
codigo.fecPresRegistro=FECPRESEREGISTRO
codigo.subvTotal=SUBVTOTAL
codigo.fecFinContrato=FECFINCONTRATO
codigo.primerPago60=PRIMERPAGO60
codigo.numCuentaBancaria=NUMCUENTABANCARIA
codigo.segundoPago40=SEGUNDOPAGO40
codigo.fecMaximaResol=FECMAXIMARESOL
codigo.nifPersContr=NIFPERSCONTR
codigo.nombApelPersContr=NOMBAPELPERSCONTR
codigo.tipoContrato=TIPOCONTRATO
codigo.durContMeses=DURCONTMESES
codigo.durContDias=DURCONTDIAS
codigo.baseCotiz2=BASECOTIZ2
codigo.fecControlDoc=FECCONTROLDOC

#Descripcion de los campos
desc.resfav=RESFAV
desc.fecIniContrato=FECINICONTRATO
desc.fecAltaSS=FECALTASS
desc.solicEnPlazo=SOLICENPLAZO
desc.fecPresRegistro=FECPRESEREGISTRO
desc.subvTotal=SUBVTOTAL
desc.fecFinContrato=FECFINCONTRATO
desc.primerPago60=PRIMERPAGO60
desc.numCuentaBancaria=NUMCUENTABANCARIA
desc.segundoPago40=SEGUNDOPAGO40
desc.fecMaximaResol=FECMAXIMARESOL
desc.nifPersContr=NIFPERSCONTR
desc.nombApelPersContr=NOMBAPELPERSCONTR
desc.tipoContrato=TIPOCONTRATO
desc.durContMeses=DURCONTMESES
desc.durContDias=DURCONTDIAS
desc.baseCotiz2=BASECOTIZ2
desc.fecControlDoc=FECCONTROLDOC

#Tipo de dato de los campos
tipoDato.resfav=6
tipoDato.fecIniContrato=3
tipoDato.fecAltaSS=3
tipoDato.solicEnPlazo=6
tipoDato.fecPresRegistro=3
tipoDato.subvTotal=1
tipoDato.fecFinContrato=3
tipoDato.primerPago60=1
tipoDato.numCuentaBancaria=2
tipoDato.segundoPago40=1

#Valores para las validaciones
valor.fecIniContrato.fecDesde=20/12/2011
valor.fecIniContrato.fecHasta=31/10/2012
#--
valor.fecAltaSS.fecDesde=01/01/2012
valor.fecAltaSS.fecHasta=31/10/2012
#--
valor.maxValorSubvTotal=492.92
#--
valor.partePago1Subv=60
#--
valor.maxValorPago2=197.18
#--
valor.fechaAltaSS1=20/08/2012
valor.fechaPresReg1=21/09/2012
valor.fechaPresReg2=16/11/2012
#--
#Validaci\u00f3n de cuentas bancarias
#NOTA: La cadena va desde la cifra de m\u00e1s peso (unidad de millar de mill\u00f3n) hasta la de menos peso (unidad)
#NOTA: Los pesos est\u00e1 separados por comas
#NOTA: Debe tener siempre una longitud de 10. Si alg\u00fan peso se deja de utilizar, reemplazarlo por 1 (elemento neutro en la multiplicaci\u00f3n)

#Cadena con los pesos para obtener el primer digito de control
pesosDC=1,2,4,8,5,10,9,7,3,6

#--
valor.codigosProvincia=20,48,01

#--
valor.camposResFavSIOblig=FECPRESEREGISTRO,FECMAXIMARESOL,FECINICONTRATO,RANGOCONTRATO,FECALTASS,SOLICENPLAZO,NIFPERSCONTR,NOMBAPELPERSCONTR,RESFAV,TIPOCONTRATO,DURCONTMESES,DURCONTDIAS,FECFINCONTRATO,BASECOTIZ2,PRIMERPAGO60,SUBVTOTAL,NUMCUENTABANCARIA,FECCONTROLDOC
valor.camposResFavNOOblig=FECPRESEREGISTRO,FECMAXIMARESOL,FECINICONTRATO,RANGOCONTRATO,FECALTASS,SOLICENPLAZO,NIFPERSCONTR,NOMBAPELPERSCONTR
valor.camposResFavNOVacios=TIPOCONTRATO,DURCONTMESES,DURCONTDIAS,FECFINCONTRATO,BASECOTIZ2,PRIMERPAGO60,SUBVTOTAL,NUMCUENTABANCARIA,FECCONTROLDOC

#OTRO
formatoFecha=dd/MM/yyyy