# Plugin a cargar ( BBDD = Base de datos, GESTOR = Gestor documental ALFRESCO, NEXTRET = Integraci\u00F3n con WS de NextRet con Sharepoint DOKUSI = Gestor documental DOKUSI)
Almacenamiento/plugin = DOKUSI

# M\u00E9todos de almacenamiento de documentos de tramitaci\u00F3n en cada organizaci\u00F3n
Almacenamiento/0/BBDD/pluginDocumentosTramitacion       = es.altia.agora.business.sge.plugin.documentos.AlmacenDocumentoBBDDImpl
Almacenamiento/0/DOKUSI/pluginDocumentosTramitacion     = es.altia.agora.business.sge.plugin.documentos.AlmacenDocumentoDokusiImpl
Almacenamiento/0/DOKUSI/nombreGestor					= DOKUSI

Almacenamiento/DOKUSI/cabecera/ficheroHTMLDocumentosRelacion = <span style="font-family: Verdana; font-size: 10pt;">&nbsp;Los documentos que forman parte de la relaci&oacute;n son:</span>
Almacenamiento/DOKUSI/cuerpo/ficheroHTMLDocumentosRelacion    =  <ul><span style="font-family: Verdana; font-size: 10pt;text-decoration:none">@
Almacenamiento/DOKUSI/pie/ficheroHTMLDocumentosRelacion         = </span></ul>

# Longitud del campo de base de datos que contiene el c\u00F3digo de tr\u00E1mite visible
longitud_codigo_tramite_visible                  = 4
# Longitud del campo de base de datos que contiene el n\u00FAmero de un documento
longitud_numero_documento                     = 4
# Longitud del campo de base de datos que contiene la ocurrencia de un tr\u00E1mite
longitud_ocurrencia_tramite                       = 4

####### INIT: DATOS DE CONFIGURACI\u00D3N DE DOKUSI ##########

# Url del API de los servicios web de alfresco
Almacenamiento/0/DOKUSI/urlGestor              = http://localhost:8080/alfresco/api
# Clase que implementa el plugin de Alfresco
Almacenamiento/0/DOKUSI/implClass             = es.altia.agora.business.sge.plugin.documentos.AlmacenDocumentoDokusiImpl
# Usuario de conexi\u00F3n al gestor documental
Almacenamiento/0/DOKUSI/usuarioGestor         = admin
# Password del usuario del conexi\u00F3n al gestor documental
Almacenamiento/0/DOKUSI/passwordGestor        = admin
Almacenamiento/0/DOKUSI/carpetaRaiz          = FLEXIA

Almacenamiento/0/DOKUSI/caracteres_no_permitidos  = /;?;>;<;\\;|;:;*;\"
                                                     

####### END: DATOS DE CONFIGURACI\u00D3N DE DOKUSI ##########

########### ACTIVAR FORMATO ALTERNATIVO DE FECHAS PARA DOCUMENTOS DE TRAMITACION #####################
# FORMATO: [COD_ORGANIZACION]/FORMATO_ALTERNATIVO_FECHAS_DOC_TRAMITACION. EL FORMATO PUEDE SER UNO DE LOS V\u00c1LIDOS UTILIZADOS
# POR LA CLASE SimpleDateFormat DEL API DE JAVA
0/FORMATO_ALTERNATIVO_FECHAS_DOC_TRAMITACION = yyyy/MM/dd
1/FORMATO_ALTERNATIVO_FECHAS_DOC_TRAMITACION = yyyy/MM/dd


RUTA_DISCO_DOCUMENTOS = /datos/LAN06/tmp/almacenFicheros

### Mostrar columna que indica si el documento es visible o no desde App Ext. (SSR si, Resto no)

VISIBLE_EXT=no

extesion_plantilla_adjuntar=odt

0/CSV/RECUADRO_TEXTO1=Código de Validación: @csv@
0/CSV/RECUADRO_TEXTO2=Validación en: https://...
0/CSV/RECUADRO_ALTO=30
0/CSV/RECUADRO_ANCHO=350
0/CSV/RECUADRO_POS_X_CENTRO=25
0/CSV/RECUADRO_POS_Y_CENTRO=-1
0/CSV/RECUADRO_ROTACION=90
0/CSV/RECUADRO_OFFSET_TEXTO_X=50
0/CSV/RECUADRO_TAMANO_FUENTE=8
0/CSV/RECUADRO_SUPERPUESTO=true
0/CSV/RECUADRO_PINTAR_BORDE=false
0/CSV/ESCALADO=0.9


1/CSV/RECUADRO_TEXTO1=Código de Validación: @csv@
1/CSV/RECUADRO_TEXTO2=Validación en: https://...
1/CSV/RECUADRO_ALTO=30
1/CSV/RECUADRO_ANCHO=350
1/CSV/RECUADRO_POS_X_CENTRO=25
1/CSV/RECUADRO_POS_Y_CENTRO=-1
1/CSV/RECUADRO_ROTACION=90
1/CSV/RECUADRO_OFFSET_TEXTO_X=50
1/CSV/RECUADRO_TAMANO_FUENTE=8
1/CSV/RECUADRO_SUPERPUESTO=true
1/CSV/RECUADRO_PINTAR_BORDE=false
1/CSV/ESCALADO=0.9

################################################################################################
#### Propiedad para generar la URI del codigo seguro de verificacion
CSV/URI/SERVLET_VER_DOCUMENTO=/VerDocumentoDatosSuplementarios

################################################################################################
#### Propiedad que indica la extensión de inserción y apertura de las plantillas ODT
# EXTENSION_DOCUMENTOS_TRAMITACION = odt
EXTENSION_DOCUMENTOS_TRAMITACION = doc
# EXTENSION_DOCUMENTOS_TRAMITACION = docx

#############################################################################
#### Propiedad que indica si el documento a convertir sera PDF o PDF/A.  ####
#### Los casos posibles son SI o NO                                      ####
0/DOCUMENTOS_EXPEDIENTE/FORMATO_PDFA=SI
1/DOCUMENTOS_EXPEDIENTE/FORMATO_PDFA=SI

0/DATOS_SUPLEMENTARIOS/FORMATO_PDFA=SI
1/DATOS_SUPLEMENTARIOS/FORMATO_PDFA=SI

0/FICHA_EXPEDIENTE_DOCUMENTO/FORMATO_PDFA=SI
1/FICHA_EXPEDIENTE_DOCUMENTO/FORMATO_PDFA=SI