dataSource=sge_prueba_jndi

typeUserLogin=ORACLE

directorioPlantillasReal=
directorioPlantillas=http://localhost:8080/portal_formularios/plantillasPDF/

#---------------------------------------------------------------
#Fichero de configuracion de catalogo de Formularios para crtvg
#---------------------------------------------------------------

#Disponibilidad de precargas
#---------------------------------------------------------------
XML.precargas=no


## ACTIVAR EL REVISOR (TVG -> SI, UDC -> NO)
revisor.activado=no

## PESTA\u00D1A DE DATOS ADICIONALES EN LOS USUARIOS DEL CAT\u00C1LOGO (TVG -> SI, UDC -> NO)
#---------------------------------------------------------------
datosUsuarios=no

#idiomas
#---------------------------------------------------------------
# idiomapor defecto
idioma=es
#permite cambiar de idioma?si/no
idiomas=no

#pintar columna con el nombre del tramite asociado al adjunto en
#detalle de la solicitud
-----------------------------------------------------------------
verTramiteAdjunto=si
tipoDocUor=7

#Mostar/Ocultar referencias a la firma de los formularios, es
#decir,los botones DataSinatura y Asinado de una solicitud 
#---------------------------------------------------------------
mostrarFirmaFormularios=si
#mostrarFirmaFormularios=no

#acceso a la BD
#---------------------------------------------------------------
dataSource=jdbc_flexia_pruebas
genDataSource=jdbc_flexia_generico
testDataSource=jdbc_flexia_pruebas

#donde obtener los datos del usuario ORACLE=USUARIO_TEMP; LDAP; CERTIFICADO
#---------------------------------------------------------------
typeUserLogin=ORACLE

#Valores correspondientes a la aplicacion en su trato con SGE
#---------------------------------------------------------------
url.servidorSW=http://localhost:8080/
organizacion=0
entidad=1
locateSWTramite=flexia/services/WSTramiteImpl
locateSWExpediente=flexia/services/WSExpedienteImpl
locateSWRegistroES=WSRegistroES/services/WSRegistroESImpl
municipioParaSGE=0
usuarioParaSGE=SW.FORMULARIOS
departamentoParaSGE=1
moduloExpediente=12
#Usuario y psw de la BD a pasarle al servicios web de registro
swBDUser=flexia_pruebas
swBDPsw=flexia_pruebas

#Localizacion de las plantillas y firmas
#---------------------------------------------------------------
origenPlantillas=BD
#origenPlantillas=DIRECTORIO
servidorPlantillas=http://localhost:8080/
contextoPlantillas=portal_formularios/
directorioPlantillasReal=plantillasPDF/
directorioPlantillas=plantillasPDF/

#Forma de nombrar los ficheros con la rubrica de los usuarios
#---------------------------------------------------------------
nombreRubrica=NIF
tipoFicheroFirma=tif