
#time out en milisegundos
TIME_OUT=40000
USER=XC004
PASS=iopetest
#USER=LAN62
#PASS=LAN62

NISAE.ENDPOINT=https://svc.integracion.des.ejgv.jaso/ctxweb/secured_ssl/x53jiGetIntermediacionWSUser?WSDL

OTDDFF.NISAE.CODIGO_CERTIFICADO=SWIOPOBLIDIPU
OTDDFF.NISAE.CODIGO_ESTADO=0001
OTDDFF.NISAE.LITERAL_ERROR=PENDIENTE
OTDDFF.NISAE.NIF_EMISOR=P00000000
OTDDFF.NISAE.NOMBRE_EMISOR=HACIENDAS FORALES VASCAS
OTDDFF.NISAE.NIF_SOLICITANTE=Q0100571I
OTDDFF.NISAE.ORGANO_SOLICITANTE=LANBIDE
OTDDFF.NISAE.UNIDAD_TRAMITADORA=DIRECCIÓN DE ACTIVACION LABORAL


#Fichero propiedades de log
LOGCONFIG_FILE=/config/log4j.properties



# ----------------------- Procedimiento de ATASE--------------------#
#Identificador de procedimiento
PROCEDIMIENTO_ID_LAN62_ATASE=LAN62_ATASE
#Descripción procedimiento Castellano
PROCEDIMIENTO_NOMBRE_LAN62_ATASE=Ayudas extraordinarias para las personas trabajadoras por cuenta propia o autónomas cuyas actividades han quedado suspendidas a consecuencia de la declaración del estado de alarma
#Descripción procedimiento Euskera
PROCEDIMIENTO_NOMBRE_EU_LAN62_ATASE=Ayudas extraordinarias para las personas trabajadoras por cuenta propia o autónomas cuyas actividades han quedado suspendidas a consecuencia de la declaración del estado de alarma
# Nombre de la aplicación
APP_NAME_LAN62_ATASE=LAN62
#Archivo digital del procedimiento
ID_PROC_ARCHIVO_DIGITAL_LAN62_ATASE=11026

# ----------------------- Fin Procedimiento de ATASE --------------------#

# ----------------------- Procedimiento de ACASE--------------------#

#Identificador de procedimiento
PROCEDIMIENTO_ID_LAN62_ACASE=LAN62_ACASE
#Descripción procedimiento Castellaño
PROCEDIMIENTO_NOMBRE_LAN62_ACASE=AYUDAS A PERSONAS PROFESIONALES DE LA CULTURA CON ACTIVIDADES CANCELADAS O SUSPENDIDAS POR ESTADO DE ALARMA
#Descripción procedimiento Euskera
PROCEDIMIENTO_NOMBRE_EU_LAN62_ACASE=AYUDAS A PERSONAS PROFESIONALES DE LA CULTURA CON ACTIVIDADES CANCELADAS O SUSPENDIDAS POR ESTADO DE ALARMA
APP_NAME_LAN62_ACASE =LAN62
#Archivo digital del procedimiento
ID_PROC_ARCHIVO_DIGITAL_LAN62_ACASE=11035

# ----------------------- Fin Procedimiento de ACASE --------------------#

# ----------------------- Procedimiento de AAEEF--------------------#

#Identificador de procedimiento
PROCEDIMIENTO_ID_AAEEF=AAEEF
#Descripción procedimiento Castellano
PROCEDIMIENTO_NOMBRE_AAEEF= Ayudas para acciones estratégicas formativas por parte de las empresas de la CAPV
#Descripción procedimiento Euskera
PROCEDIMIENTO_NOMBRE_EU_AAEEF= Enpresek prestakuntzako estrategi-ekintzen diru laguntzak
#Archivo digital del procedimiento
ID_PROC_ARCHIVO_DIGITAL_AAEEF=01368


# ----------------------- Fin Procedimiento de AAEEF --------------------#

# ----------------------- Procedimiento de TRECO--------------------#

#Identificador de procedimiento
PROCEDIMIENTO_ID_LAN62_TRECO=LAN62_TRECO
#Descripción procedimiento Castellano
PROCEDIMIENTO_NOMBRE_LAN62_TRECO=Ayudas para el mantenimiento del empleo en entidades para inversiones dirigidas a la transformación ecológica y digital
#Descripción procedimiento Euskera
PROCEDIMIENTO_NOMBRE_EU_LAN62_TRECO=Erakundeetan enpleguari eusteko laguntzak, eraldaketa ekologikora eta digitalera bideratutako inbertsioetarako
# Nombre de la aplicación
APP_NAME_LAN62_TRECO =LAN62
# Familia
ID_FAMILIA_PROC_LAN62_TRECO=AYUSUB
#Archivo digital del procedimiento
ID_PROC_ARCHIVO_DIGITAL_LAN62_TRECO=12108

# ----------------------- Fin Procedimiento de TRECO--------------------#

# ----------------------- Procedimiento de DEM50--------------------#
#Identificador de procedimiento
PROCEDIMIENTO_ID_LAN62_DEM50=LAN62_DEM50
#Descripción procedimiento Castellano
PROCEDIMIENTO_NOMBRE_LAN62_DEM50=AYUDA CONTRATACION PERSONAS MAYORES 50 AÑOS EN SITUACION DE DESEMPLEO POR TIEMPO IGUAL O INFERIOR A 1 AÑO
#Descripción procedimiento Euskera
PROCEDIMIENTO_NOMBRE_EU_LAN62_DEM50=50 URTETIK GORAKO ETA URTEBETEKO EDO HORTIK BEHERAKO LANGABEZIAN DAUDEN PERTSONAK KONTRATATZEKO LAGUNTZA
# Nombre de la aplicación
APP_NAME_LAN62_DEM50 =LAN62
# Familia
ID_FAMILIA_PROC_LAN62_DEM50=AYUSUB
#Archivo digital del procedimiento
ID_PROC_ARCHIVO_DIGITAL_LAN62_DEM50=01368

# ----------------------- Fin Procedimiento de DEM50 --------------------#

# ----------------------- Procedimiento de DLDUR--------------------#
#Identificador de procedimiento
PROCEDIMIENTO_ID_LAN62_DLDUR=LAN62_DLDUR
#Descripción procedimiento Castellano
PROCEDIMIENTO_NOMBRE_LAN62_DLDUR= CONTRATACIÓN PERSONAS DESEMPLEADAS DE LARGA DURACIÓN MAYORES DE 30 AÑOS
#Descripción procedimiento Euskera
PROCEDIMIENTO_NOMBRE_EU_LAN62_DLDUR=30 URTETIK GORAKO IRAUPEN LUZEKO LANGABEAK KONTRATATZEA
# Nombre de la aplicación
APP_NAME_LAN62_DLDUR =LAN62
# Familia
ID_FAMILIA_PROC_LAN62_DLDUR=AYUSUB
#Archivo digital del procedimiento
ID_PROC_ARCHIVO_DIGITAL_LAN62_DLDUR=10928

# ----------------------- Fin Procedimiento de DLDUR --------------------#
