##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE77/LISTA_OPERACIONES_DISPONIBLES=
1/MODULO_INTEGRACION/MELANBIDE77/LISTA_OPERACIONES_DISPONIBLES=

##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE77
COD_PROCEDIMIENTO=AERTE
ASUNTO_PROCEDIMIENT0=RGIAERTE

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE77/DESCRIPCION_MODULO = MODULO AERTE
1/MODULO_INTEGRACION/MELANBIDE77/DESCRIPCION_MODULO = MODULO AERTE

##################### NOMBRES DE TABLAS #####################
TABLA_OCURRENCIAS=E_CRO
TABLA_EXPEDIENTES=E_EXP
TABLA_TERCERO_EXPEDIENTE=E_EXT
TABLA_EXPEDIENTE_REGISTRO=E_EXR
TABLA_SUPLEMENTARIOS_PROCEDIMIENTO=E_PCA
TABLA_CONDICION_SALIDA=E_SAL
TABLA_TIPO_SUPLEMENTARIO=E_TDA
TABLA_NOMBRE_TRAMITES=E_TML
TABLA_DOCUMENTOS_REGISTRO=R_RED
TABLA_REGISTRO=R_RES
TABLA_TERCERO_REGISTRO=R_EXT
TABLA_DOMICILIO=T_DNN
TABLA_TERCEROS_HIST=T_HTE
TABLA_MUNICIPIOS=T_MUN
TABLA_PROVINCIAS=T_PRV
TABLA_TERCEROS=T_TER
TABLA_TIPO_VIA=T_TVI
TABLA_VIA=T_VIA
TABLA_TAREAS_PENDIENTES=TAREAS_PENDIENTES_INICIO
TABLA_REG_BATCH=MELANBIDE77_REG_BATCH
# en DESA 
TABLA_SOLICITUDES=AYUDAS_ERTE
# en PRE y PRO
#TABLA_SOLICITUDES=AYUDAS_ERTE_SINONIMO

##################### NOMBRES DE SECUENCIAS #####################
SECUENCIA_REG_BATCH=SEQ_MELANBIDE77_REG_BATCH

##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide77.i18n.text
FICHEROS_MENSAJES = MELANBIDE77_TEXT_1;MELANBIDE77_TEXT_4

# EL caracter es pipeline hay que escaparlo porque es un caracter especial para hacer condicion or en regex
BARRA_SEPARADORA_IDIOMA_DESPLEGABLES=\\Q|\\E

### OTROS
CARACTERES_ESPECIALES=&'<>|^\\%

ULTIMO_EXP_CONVOCATORIA=2020/AERTE/007319

#####URL_WS_REGISTRO#########################################################################
#DESA
#URL_WS_TRAMITACION=http://10.168.212.21:7081/WSTramitacion/services/WSTramitacionPort?wsdl
URL_WS_TRAMITACION=http://integ.serv.des.lanbide.lan/WSTramitacion/services/WSTramitacionPort?wsdl

#PRE
#URL_WS_TRAMITACION=http://10.168.212.161:17003/WSTramitacion/services/WSTramitacionPort?wsdl
#URL_WS_TRAMITACION=http://integ.serv.pru.lanbide.lan/WSTramitacion/services/WSTramitacionPort?wsdl
#PRO
#URL_WS_TRAMITACION=http://integ.serv.lanbide.lan/WSTramitacion/services/WSTramitacionPort?wsdl

#DESARROLLO
SERVIDOR = E22_DES_WL12_LANBIDE_FLEXIA111
COD_ORG=0
DOS_ENTORNOS=TRUE
COD_UOR=8
INICIO_EXPEDIENTE=2
REVISION_DOCUMENTACION=3


#PRE
#SERVIDOR = paprergi1_flexia1
#COD_ORG=1
#DOS_ENTORNOS=FALSE
#COD_UOR=107 
#INICIO_EXPEDIENTE=1
#REVISION_DOCUMENTACION=2

#PRO
#SERVIDOR = pargi1_flexia1
#COD_ORG=0
#DOS_ENTORNOS=TRUE
#COD_UOR=107
#INICIO_EXPEDIENTE=1
#REVISION_DOCUMENTACION=2