##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE30/LISTA_OPERACIONES_DISPONIBLES=
1/MODULO_INTEGRACION/MELANBIDE30/LISTA_OPERACIONES_DISPONIBLES=

# NOMBRE DEL M\u00d3DULO QUE SE MUESTRA JUNTO CON EL NOMBRE DE LA OPERACI\u00d3N; A LA HORA DE SELECCIONAR UNA OPERACI\u00d3N QUE SE ASOCIAR\u00c1 A UN TR\u00c1MITE
# FORMATO: [COD_ORGANIZACION]/MODULO_INTEGRACION/[NOMBRE_MODULO]/NOMBRE_MODULO
0/MODULO_INTEGRACION/MELANBIDE30/NOMBRE_MODULO = MELANBIDE30
1/MODULO_INTEGRACION/MELANBIDE30/NOMBRE_MODULO = MELANBIDE30

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE30/DESCRIPCION_MODULO = M\u00d3DULO DE EXTENSI\u00d3N PARA MANTENIMIENTO DE CONTRATOS DE SOCIOS
1/MODULO_INTEGRACION/MELANBIDE30/DESCRIPCION_MODULO = M\u00d3DULO DE EXTENSI\u00d3N PARA MANTENIMIENTO DE CONTRATOS DE SOCIOS

##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE30/CNEE/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = MANTENIMIENTO_CONTRATOS
1/MODULO_INTEGRACION/MELANBIDE30/CNEE/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = MANTENIMIENTO_CONTRATOS

##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE30/CNEE/URL_PANTALLA_EXPEDIENTE/MANTENIMIENTO_CONTRATOS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE30&operacion=cargarContratos&tipo=0
1/MODULO_INTEGRACION/MELANBIDE30/CNEE/URL_PANTALLA_EXPEDIENTE/MANTENIMIENTO_CONTRATOS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE30&operacion=cargarContratos&tipo=0

##################### NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE #####################
0/MODULO_INTEGRACION/MELANBIDE30/CNEE/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/MANTENIMIENTO_CONTRATOS =
1/MODULO_INTEGRACION/MELANBIDE30/CNEE/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/MANTENIMIENTO_CONTRATOS =

#0/MODULO_INTEGRACION/MELANBIDE30/CNEE/PANTALLA_EXPEDIENTE/SALIDA = /jsp/extension/melanbide32/melanbide32.jsp
#1/MODULO_INTEGRACION/MELANBIDE30/CNEE/PANTALLA_EXPEDIENTE/SALIDA = /jsp/extension/melanbide32/melanbide32.jsp

##################### NOMBRE DE LA OPERACION DEL MODULO QUE SE ENCARGA DE ACTUALIZAR LOS DATOS DE LA PANTALLA DE EXPEDIENTE #####################
0/MODULO_INTEGRACION/MELANBIDE30/CNEE/ACTUALIZAR_PANTALLA_EXPEDIENTE/MANTENIMIENTO_CONTRATOS = 
1/MODULO_INTEGRACION/MELANBIDE30/CNEE/ACTUALIZAR_PANTALLA_EXPEDIENTE/MANTENIMIENTO_CONTRATOS = 

##################### NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE DE UNA RELACI\u00d3N ENTRE EXPEDIENTES #####################
0/MODULO_INTEGRACION/MELANBIDE30/CNEE/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/SELECCION_CERTIFICADO  =
1/MODULO_INTEGRACION/MELANBIDE30/CNEE/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/SELECCION_CERTIFICADO  =

##################### NOMBRES DE TABLAS #####################
TABLA_CNEE_SOXEX=CNEE_SOXEX
TABLA_TERCEROS=T_TER

##################### NOMBRES DE SECUENCIAS #####################


##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide30.i18n.text
FICHEROS_MENSAJES = MELANBIDE30_TEXT_1

# Nombre del campo suplementario de tipo desplegable del que se extrae los valores para componer el combo "N. Estudios" 
# de la /jsp/extension/melanbide30/nuevoContratoSocios.jsp
0/CAMPO_SUPLEMENTARIO_ESTUDIOS = ESTU
1/CAMPO_SUPLEMENTARIO_ESTUDIOS = ESTU

# Nombre del campo suplementario de tipo desplegable del que se extrae los valores para componer el combo "Colectivo" 
# de la /jsp/extension/melanbide30/nuevoContratoSocios.jsp
0/CAMPO_SUPLEMENTARIO_COLECTIVOS = COLE
1/CAMPO_SUPLEMENTARIO_COLECTIVOS = COLE

# Nombre del campo suplementario de tipo desplegable del que se extrae los valores para componer el combo "TIP. CON. DUR." 
# de la /jsp/extension/melanbide30/nuevoContratoSocios.jsp
0/CAMPO_SUPLEMENTARIO_TCD = TCD
1/CAMPO_SUPLEMENTARIO_TCD = TCD

# Nombre del campo suplementario de tipo desplegable del que se extrae los valores para componer el combo "Tipo Jornada" 
# de la /jsp/extension/melanbide30/nuevoContratoSocios.jsp
0/CAMPO_SUPLEMENTARIO_TIPO_JORNADA = TJOR
1/CAMPO_SUPLEMENTARIO_TIPO_JORNADA = TJOR

# Nombre del campo suplementario de tipo desplegable del que se extrae los valores para componer el combo "CNOE" 
# de la /jsp/extension/melanbide30/nuevoContratoSocios.jsp
0/CAMPO_SUPLEMENTARIO_CNOE = CNOE
1/CAMPO_SUPLEMENTARIO_CNOE = CNOE

# Nombre del campo suplementario de tipo desplegable del que se extrae los valores para componer el combo "Tipo Contrato" 
# de la /jsp/extension/melanbide30/nuevoContratoSocios.jsp
0/CAMPO_SUPLEMENTARIO_TIPO_CONTRATO = TCCN
1/CAMPO_SUPLEMENTARIO_TIPO_CONTRATO = TCCN