##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE35/LISTA_OPERACIONES_DISPONIBLES=
1/MODULO_INTEGRACION/MELANBIDE35/LISTA_OPERACIONES_DISPONIBLES=

##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE35

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE35/DESCRIPCION_MODULO = M\u00f3dulo de Procedimiento Empleo con Apoyo  Discapacitados en mercado ordinario - ECA
1/MODULO_INTEGRACION/MELANBIDE35/DESCRIPCION_MODULO = M\u00f3dulo de Procedimiento Empleo con Apoyo  Discapacitados en mercado ordinario - ECA

##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE35/ECA/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = SOLICITUD;JUSTIFICACION;RESUMEN;VALIDACION;RESUMENCAMPOS
1/MODULO_INTEGRACION/MELANBIDE35/ECA/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = SOLICITUD;JUSTIFICACION;RESUMEN;VALIDACION;RESUMENCAMPOS


##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE35/ECA/URL_PANTALLA_EXPEDIENTE/SOLICITUD = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE35&operacion=cargarPantallaSolicitudPrincipal&tipo=0
1/MODULO_INTEGRACION/MELANBIDE35/ECA/URL_PANTALLA_EXPEDIENTE/SOLICITUD = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE35&operacion=cargarPantallaSolicitudPrincipal&tipo=0
0/MODULO_INTEGRACION/MELANBIDE35/ECA/URL_PANTALLA_EXPEDIENTE/JUSTIFICACION = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE35&operacion=cargarPantallaJustificacion&tipo=0
1/MODULO_INTEGRACION/MELANBIDE35/ECA/URL_PANTALLA_EXPEDIENTE/JUSTIFICACION = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE35&operacion=cargarPantallaJustificacion&tipo=0
0/MODULO_INTEGRACION/MELANBIDE35/ECA/URL_PANTALLA_EXPEDIENTE/RESUMEN = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE35&operacion=cargarPantallaResumen&tipo=0
1/MODULO_INTEGRACION/MELANBIDE35/ECA/URL_PANTALLA_EXPEDIENTE/RESUMEN = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE35&operacion=cargarPantallaResumen&tipo=0
0/MODULO_INTEGRACION/MELANBIDE35/ECA/URL_PANTALLA_EXPEDIENTE/VALIDACION = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE35&operacion=cargarPantallaValidacion&tipo=0
1/MODULO_INTEGRACION/MELANBIDE35/ECA/URL_PANTALLA_EXPEDIENTE/VALIDACION = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE35&operacion=cargarPantallaValidacion&tipo=0
0/MODULO_INTEGRACION/MELANBIDE35/ECA/URL_PANTALLA_EXPEDIENTE/RESUMENCAMPOS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE35&operacion=cargarPantallaResumenCampos&tipo=0
1/MODULO_INTEGRACION/MELANBIDE35/ECA/URL_PANTALLA_EXPEDIENTE/RESUMENCAMPOS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE35&operacion=cargarPantallaResumenCampos&tipo=0

##################### NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE #####################
0/MODULO_INTEGRACION/MELANBIDE35/ECA/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/SOLICITUD =
1/MODULO_INTEGRACION/MELANBIDE35/ECA/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/SOLICITUD =

#0/MODULO_INTEGRACION/MELANBIDE35/ECA/PANTALLA_EXPEDIENTE/SALIDA = /jsp/extension/MELANBIDE35/MELANBIDE35.jsp
#1/MODULO_INTEGRACION/MELANBIDE35/ECA/PANTALLA_EXPEDIENTE/SALIDA = /jsp/extension/MELANBIDE35/MELANBIDE35.jsp

##################### NOMBRE DE LA OPERACION DEL MODULO QUE SE ENCARGA DE ACTUALIZAR LOS DATOS DE LA PANTALLA DE EXPEDIENTE #####################
0/MODULO_INTEGRACION/MELANBIDE35/ECA/ACTUALIZAR_PANTALLA_EXPEDIENTE/SOLICITUD = 
1/MODULO_INTEGRACION/MELANBIDE35/ECA/ACTUALIZAR_PANTALLA_EXPEDIENTE/SOLICITUD = 

##################### NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE DE UNA RELACI\u00d3N ENTRE EXPEDIENTES #####################
0/MODULO_INTEGRACION/MELANBIDE35/ECA/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/SOLICITUD  =
1/MODULO_INTEGRACION/MELANBIDE35/ECA/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/SOLICITUD  =

##################### NOMBRES DE TABLAS #####################
TABLA_ECA_SOLICITUD=ECA_SOLICITUD
TABLA_ECA_SOL_PREPARADORES=ECA_SOL_PREPARADORES
TABLA_ECA_SOL_PROSPECTORES=ECA_SOL_PROSPECTORES
TABLA_ECA_JUS_PREPARADORES=ECA_JUS_PREPARADORES
TABLA_ECA_JUS_PROSPECTORES=ECA_JUS_PROSPECTORES
TABLA_ECA_SOL_VALORACION=ECA_SOL_VALORACION
TABLA_ECA_CONFIGURACION=ECA_CONFIGURACION
TABLA_ECA_SEG_PREPARADORES=ECA_SEG_PREPARADORES
TABLA_ECA_VIS_PROSPECTORES=ECA_VIS_PROSPECTORES
TABLA_ECA_TIPODISCAPACIDAD = ECA_TIPODISCAPACIDAD
TABLA_ECA_TIPOCONTRATO = ECA_TIPOCONTRATO
TABLA_ECA_DISCAPGRAVEDAD = ECA_DISCAPGRAVEDAD
TABLA_ECA_SECTORACTIVIDAD = ECA_SECTORACT
TABLA_PROVINCIAS = T_PRV
TABLA_ECA_AUDITORIA=ECA_AUDITORIA
TABLA_USUARIOS=A_USU
TABLA_ECA_CUMPLELISMI = ECA_CUMPLELISMI
TABLA_ECA_RESULTADO = ECA_RESULTADO
TABLA_ECA_RES_PROSPECTORES=ECA_RES_PROSPECTORES
TABLA_ECA_RES_PREPARADORES=ECA_RES_PREPARADORES
TABLA_ECA_RESUMEN=ECA_RESUMEN

TABLA_ECA23_SOL_INSERCIONES=ECA23_INSERCIONES
TABLA_ECA23_SOL_PROSPECTORES=ECA23_PROSPECTOR
TABLA_ECA23_SOL_PREPARADORES=ECA23_PREPARADOR
TABLA_ECA23_SOLICITUD=ECA23_SOLICITUD
TABLA_ECA23_CONFIGURACION=ECA23_CONFIGURACION
TABLA_VALORES_DESPLEGABLES=E_DES_VAL
TABLA_ECA23_JUSTIFICACION=ECA23_JUSTIFICACION
TABLA_ECA23_JUS_INSERCIONES=ECA23_JUS_INSERCIONES
TABLA_ECA23_JUS_PREPARADORES=ECA23_JUS_PREPARADORES
TABLA_ECA23_JUS_SEGUIMIENTOS=ECA23_JUS_SEGUIMIENTOS
TABLA_DESPLEGABLES_EXP=E_TDE
TABLA_DESPLEGABLES_EXT=E_TDEX
TABLA_NUMERICOS_EXP=E_TNU
TABLA_ECA23_VAL_INSERCIONES=ECA23_VAL_INSERCIONES
TABLA_ECA23_VAL_PREPARADORES=ECA23_VAL_PREPARADORES
TABLA_ECA23_VAL_SEGUIMIENTOS=ECA23_VAL_SEGUIMIENTOS

##################### NOMBRES DE SECUENCIAS #####################
SEQ_ECA_SOLICITUD=SEQ_ECA_SOLICITUD
SEQ_ECA_SOL_PREPARADORES=SEQ_ECA_SOL_PREPARADORES
SEQ_ECA_SOL_PROSPECTORES=SEQ_ECA_SOL_PROSPECTORES
SEQ_ECA_SOL_VALORACION=SEQ_ECA_SOL_VALORACION
SEQ_ECA_JUS_PREPARADORES=SEQ_ECA_JUS_PREPARADORES
SEQ_ECA_JUS_PROSPECTORES=SEQ_ECA_JUS_PROSPECTORES
SEQ_ECA_RESUMEN=SEQ_ECA_RESUMEN

SEQ_ECA23_JUSTIFICACION=ECA23_JUSTIFICACION_SEQ
SEQ_ECA_23_JUS_INSERCIONES=ECA23_JUS_INSERCIONES_SEQ
SEQ_ECA_23_JUS_PREPARADORES=ECA23_JUS_PREPARADORES_SEQ
SEQ_ECA_23_JUS_SEGUIMIENTOS=ECA23_JUS_SEGUIMIENTOS_SEQ

SEQ_ECA_23_VAL_INSERCIONES=ECA23_VAL_INSERCIONES_SEQ
SEQ_ECA_23_VAL_PREPARADORES=ECA23_VAL_PREPARADORES_SEQ
SEQ_ECA_23_VAL_SEGUIMIENTOS=ECA23_VAL_SEGUIMIENTOS_SEQ

##################### SUPLEMENTARIOS #####################
CAMPO_IMPORTE_VALIDADO_23=IMPORTEVALIDADO
CAMPO_IMPORTE_SUBV_CONC=SUBVCONC

##################### DESPLEGABLES #####################
COD_DES_SEXO=SEXO
COD_DES_TIPO_DIS=TDEC
COD_DES_COLECTIVO=TPDE
COD_DES_CONTRATO=TINT
COD_DES_EDAD_SEXO=TPSE
COD_DES_CNAE=CNAE

VISTA_DES_CNAE=S_LAN_CNAE_09

##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide35.i18n.text
FICHEROS_MENSAJES = MELANBIDE35_TEXT_1;MELANBIDE35_TEXT_4

# EL caracter es pipeline hay que escaparlo porque es un caracter especial para hacer condicion or en regex
BARRA_SEPARADORA_IDIOMA=\\Q|\\E