##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE38/LISTA_OPERACIONES_DISPONIBLES=
1/MODULO_INTEGRACION/MELANBIDE38/LISTA_OPERACIONES_DISPONIBLES=



# NOMBRE DEL M\u00d3DULO QUE SE MUESTRA JUNTO CON EL NOMBRE DE LA OPERACI\u00d3N; A LA HORA DE SELECCIONAR UNA OPERACI\u00d3N QUE SE ASOCIAR\u00c1 A UN TR\u00c1MITE
# FORMATO: [COD_ORGANIZACION]/MODULO_INTEGRACION/[NOMBRE_MODULO]/NOMBRE_MODULO
0/MODULO_INTEGRACION/MELANBIDE38/NOMBRE_MODULO = MELANBIDE38
1/MODULO_INTEGRACION/MELANBIDE38/NOMBRE_MODULO = MELANBIDE38

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE38/DESCRIPCION_MODULO = M\u00d3DULO DE EXTENSI\u00d3N PARA MANTENIMIENTO DE AYUDAS A LA CONTRATACI\u00d3N
1/MODULO_INTEGRACION/MELANBIDE38/DESCRIPCION_MODULO = M\u00d3DULO DE EXTENSI\u00d3N PARA MANTENIMIENTO DE AYUDAS A LA CONTRATACI\u00d3N




##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE38/AYCON/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = LISTADO_CONTRATOS
1/MODULO_INTEGRACION/MELANBIDE38/AYCON/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = LISTADO_CONTRATOS

##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE38/AYCON/URL_PANTALLA_EXPEDIENTE/LISTADO_CONTRATOS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE38&operacion=cargarContratos&tipo=0
1/MODULO_INTEGRACION/MELANBIDE38/AYCON/URL_PANTALLA_EXPEDIENTE/LISTADO_CONTRATOS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE38&operacion=cargarContratos&tipo=0

##################### NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE #####################
0/MODULO_INTEGRACION/MELANBIDE38/AYCON/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/LISTADO_CONTRATOS =
1/MODULO_INTEGRACION/MELANBIDE38/AYCON/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/LISTADO_CONTRATOS =

##################### NOMBRE DE LA OPERACION DEL MODULO QUE SE ENCARGA DE ACTUALIZAR LOS DATOS DE LA PANTALLA DE EXPEDIENTE #####################
0/MODULO_INTEGRACION/MELANBIDE38/AYCON/ACTUALIZAR_PANTALLA_EXPEDIENTE/LISTADO_CONTRATOS = 
1/MODULO_INTEGRACION/MELANBIDE38/AYCON/ACTUALIZAR_PANTALLA_EXPEDIENTE/LISTADO_CONTRATOS = 




##################### RELACI\u00d3N DE EXPEDIENTES #####################

0/MODULO_INTEGRACION/MELANBIDE38/AYCON/PANTALLA_EXPEDIENTE_RELACION/NOMBRE_PANTALLAS=LISTADO_CONTRATOS
1/MODULO_INTEGRACION/MELANBIDE38/AYCON/PANTALLA_EXPEDIENTE_RELACION/NOMBRE_PANTALLAS=LISTADO_CONTRATOS

0/MODULO_INTEGRACION/MELANBIDE38/AYCON/URL_PANTALLA_EXPEDIENTE_RELACION/LISTADO_CONTRATOS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE38&operacion=cargarContratos&tipo=0
1/MODULO_INTEGRACION/MELANBIDE38/AYCON/URL_PANTALLA_EXPEDIENTE_RELACION/LISTADO_CONTRATOS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE38&operacion=cargarContratos&tipo=0

##################### NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE DE UNA RELACI\u00d3N ENTRE EXPEDIENTES #####################
0/MODULO_INTEGRACION/MELANBIDE38/AYCON/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/SELECCION_CERTIFICADO  =
1/MODULO_INTEGRACION/MELANBIDE38/AYCON/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/SELECCION_CERTIFICADO  =




##################### NOMBRES DE TABLAS #####################
TABLA_CNEE_SOXEX=CNEE_SOXEX
TABLA_TERCEROS=T_TER

##################### NOMBRES DE SECUENCIAS #####################


##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide38.i18n.text
FICHEROS_MENSAJES = MELANBIDE38_TEXT_1:MELANBIDE38_TEXT_4

# Nombre del campo suplementario de tipo desplegable del que se extrae los valores para componer el combo "N. Estudios" 
# de la /jsp/extension/melanbide38/nuevoContrato.jsp
0/CAMPO_SUPLEMENTARIO_ESTUDIOS = ESTU
1/CAMPO_SUPLEMENTARIO_ESTUDIOS = ESTU

# Nombre del campo suplementario de tipo desplegable del que se extrae los valores para componer el combo "Colectivo" 
# de la /jsp/extension/melanbide38/nuevoContrato.jsp
0/CAMPO_SUPLEMENTARIO_COLECTIVOS = COLE
1/CAMPO_SUPLEMENTARIO_COLECTIVOS = COLE

# Nombre del campo suplementario de tipo desplegable del que se extrae los valores para componer el combo "TIP. CON. DUR." 
# de la /jsp/extension/melanbide38/nuevoContrato.jsp
0/CAMPO_SUPLEMENTARIO_TCD = TCD
1/CAMPO_SUPLEMENTARIO_TCD = TCD

# Nombre del campo suplementario de tipo desplegable del que se extrae los valores para componer el combo "Tipo Jornada" 
# de la /jsp/extension/melanbide38/nuevoContrato.jsp
0/CAMPO_SUPLEMENTARIO_TIPO_JORNADA = TJOR
1/CAMPO_SUPLEMENTARIO_TIPO_JORNADA = TJOR

# Nombre del campo suplementario de tipo desplegable del que se extrae los valores para componer el combo "CNOE" 
# de la /jsp/extension/melanbide38/nuevoContrato.jsp
0/CAMPO_SUPLEMENTARIO_CNOE = CNOE
1/CAMPO_SUPLEMENTARIO_CNOE = CNOE

# Nombre del campo suplementario de tipo desplegable del que se extrae los valores para componer el combo "Tipo Contrato" 
# de la /jsp/extension/melanbide38/nuevoContrato.jsp
0/CAMPO_SUPLEMENTARIO_TIPO_CONTRATO = TCCN
1/CAMPO_SUPLEMENTARIO_TIPO_CONTRATO = TCCN

# Nombre del campo suplementario de tipo desplegable del que se extrae los valores para componer el combo "Categoria Profesional" 
# de la /jsp/extension/melanbide38/nuevoContrato.jsp
0/CAMPO_SUPLEMENTARIO_CATEGORIA_PROFESIONAL = TCCN
1/CAMPO_SUPLEMENTARIO_CATEGORIA_PROFESIONAL = TCCN