##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE34/LISTA_OPERACIONES_DISPONIBLES=refrescarPantalla
1/MODULO_INTEGRACION/MELANBIDE34/LISTA_OPERACIONES_DISPONIBLES=refrescarPantalla

##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE34

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE34/DESCRIPCION_MODULO = M\u00f3dulo de Subvenciones de inserci\u00f3n social \u2013 Creaci\u00f3n Empresas de Inserci\u00f3n
1/MODULO_INTEGRACION/MELANBIDE34/DESCRIPCION_MODULO = M\u00f3dulo de Subvenciones de inserci\u00f3n social \u2013 Creaci\u00f3n Empresas de Inserci\u00f3n

##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
#0/MODULO_INTEGRACION/MELANBIDE34/CEI/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CALCULOS
#1/MODULO_INTEGRACION/MELANBIDE34/CEI/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CALCULOS
0/MODULO_INTEGRACION/MELANBIDE34/CEI/7/PANTALLA_TRAMITE/NOMBRE_PANTALLAS = CALCULOS
1/MODULO_INTEGRACION/MELANBIDE34/CEI/7/PANTALLA_TRAMITE/NOMBRE_PANTALLAS = CALCULOS

0/MODULO_INTEGRACION/MELANBIDE34/CEI/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = SUBVENCIONES
1/MODULO_INTEGRACION/MELANBIDE34/CEI/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = SUBVENCIONES

0/MODULO_INTEGRACION/MELANBIDE34/CEI/52/PANTALLA_TRAMITE/NOMBRE_PANTALLAS = CALCULOSPRIMERPAGO
1/MODULO_INTEGRACION/MELANBIDE34/CEI/52/PANTALLA_TRAMITE/NOMBRE_PANTALLAS = CALCULOSPRIMERPAGO

0/MODULO_INTEGRACION/MELANBIDE34/CEI/18/PANTALLA_TRAMITE/NOMBRE_PANTALLAS = CALCULOSSEGUNDOPAGO
1/MODULO_INTEGRACION/MELANBIDE34/CEI/18/PANTALLA_TRAMITE/NOMBRE_PANTALLAS = CALCULOSSEGUNDOPAGO

0/MODULO_INTEGRACION/MELANBIDE34/CEI/25/PANTALLA_TRAMITE/NOMBRE_PANTALLAS = CALCULOSTERCERPAGO
1/MODULO_INTEGRACION/MELANBIDE34/CEI/25/PANTALLA_TRAMITE/NOMBRE_PANTALLAS = CALCULOSTERCERPAGO

##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
#0/MODULO_INTEGRACION/MELANBIDE34/CEI/URL_PANTALLA_EXPEDIENTE/CALCULOS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE34&operacion=cargarPantalla&tipo=0
#1/MODULO_INTEGRACION/MELANBIDE34/CEI/URL_PANTALLA_EXPEDIENTE/CALCULOS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE34&operacion=cargarPantalla&tipo=0
0/MODULO_INTEGRACION/MELANBIDE34/CEI/7/URL_PANTALLA_TRAMITACION/CALCULOS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE34&operacion=cargarPantalla&tipo=0
1/MODULO_INTEGRACION/MELANBIDE34/CEI/7/URL_PANTALLA_TRAMITACION/CALCULOS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE34&operacion=cargarPantalla&tipo=0

0/MODULO_INTEGRACION/MELANBIDE34/CEI/52/URL_PANTALLA_TRAMITACION/CALCULOSPRIMERPAGO = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE34&operacion=cargarPantallaPrimerPago&tipo=0
1/MODULO_INTEGRACION/MELANBIDE34/CEI/52/URL_PANTALLA_TRAMITACION/CALCULOSPRIMERPAGO = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE34&operacion=cargarPantallaPrimerPago&tipo=0

0/MODULO_INTEGRACION/MELANBIDE34/CEI/18/URL_PANTALLA_TRAMITACION/CALCULOSSEGUNDOPAGO = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE34&operacion=cargarPantallaSegundoPago&tipo=0
1/MODULO_INTEGRACION/MELANBIDE34/CEI/18/URL_PANTALLA_TRAMITACION/CALCULOSSEGUNDOPAGO = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE34&operacion=cargarPantallaSegundoPago&tipo=0

0/MODULO_INTEGRACION/MELANBIDE34/CEI/25/URL_PANTALLA_TRAMITACION/CALCULOSTERCERPAGO = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE34&operacion=cargarPantallaTercerPago&tipo=0
1/MODULO_INTEGRACION/MELANBIDE34/CEI/25/URL_PANTALLA_TRAMITACION/CALCULOSTERCERPAGO = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE34&operacion=cargarPantallaTercerPago&tipo=0

0/MODULO_INTEGRACION/MELANBIDE34/CEI/URL_PANTALLA_EXPEDIENTE/SUBVENCIONES = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE34&operacion=cargarPantallaSubSolic&tipo=0
1/MODULO_INTEGRACION/MELANBIDE34/CEI/URL_PANTALLA_EXPEDIENTE/SUBVENCIONES = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE34&operacion=cargarPantallaSubSolic&tipo=0


##################### NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE #####################
#0/MODULO_INTEGRACION/MELANBIDE34/CEI/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/CALCULOS =
#1/MODULO_INTEGRACION/MELANBIDE34/CEI/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/CALCULOS =
0/MODULO_INTEGRACION/MELANBIDE34/CEI/7/OPERACION_PROCESAR/CALCULOS =
1/MODULO_INTEGRACION/MELANBIDE34/CEI/7/OPERACION_PROCESAR/CALCULOS =

#0/MODULO_INTEGRACION/MELANBIDE34/CEI/PANTALLA_EXPEDIENTE/SALIDA = /jsp/extension/MELANBIDE34/MELANBIDE34.jsp
#1/MODULO_INTEGRACION/MELANBIDE34/CEI/PANTALLA_EXPEDIENTE/SALIDA = /jsp/extension/MELANBIDE34/MELANBIDE34.jsp

##################### NOMBRE DE LA OPERACION DEL MODULO QUE SE ENCARGA DE ACTUALIZAR LOS DATOS DE LA PANTALLA DE EXPEDIENTE #####################
#0/MODULO_INTEGRACION/MELANBIDE34/CEI/ACTUALIZAR_PANTALLA_EXPEDIENTE/CALCULOS = actualizarCalculosCEI
#1/MODULO_INTEGRACION/MELANBIDE34/CEI/ACTUALIZAR_PANTALLA_EXPEDIENTE/CALCULOS = actualizarCalculosCEI
0/MODULO_INTEGRACION/MELANBIDE34/CEI/7/ACTUALIZAR_PANTALLA_TRAMITE/CALCULOS = actualizarCalculosCEI
1/MODULO_INTEGRACION/MELANBIDE34/CEI/7/ACTUALIZAR_PANTALLA_TRAMITE/CALCULOS = actualizarCalculosCEI

0/MODULO_INTEGRACION/MELANBIDE34/CEI/52/ACTUALIZAR_PANTALLA_TRAMITE/CALCULOSPRIMERPAGO = actualizarCalculosPrimerPagoCEI
1/MODULO_INTEGRACION/MELANBIDE34/CEI/52/ACTUALIZAR_PANTALLA_TRAMITE/CALCULOSPRIMERPAGO = actualizarCalculosPrimerPagoCEI

##################### NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE DE UNA RELACI\u00d3N ENTRE EXPEDIENTES #####################
0/MODULO_INTEGRACION/MELANBIDE34/CEI/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/SELECCION_CERTIFICADO  =
1/MODULO_INTEGRACION/MELANBIDE34/CEI/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/SELECCION_CERTIFICADO  =

##################### NOMBRES DE TABLAS #####################

#NUMERICOS
TABLA_TIPO_DATO_NUMERICO=E_TNU
TABLA_TIPO_DATO_NUMERICO_TRAMITE=E_TNUT
TABLA_TIPO_DATO_FECHA_TRAMITE=E_TFET
TABLA_TIPO_DATO_DESPLEGABLE=E_TDE
TABLA_VALORES_DESPLEGABLES=E_DES_VAL
TABLA_S75_PAGOS=S75PAGOS
TABLA_TRAMITES=E_TRA
TABLA_E_CRO=E_CRO
MELANBIDE34_SUBSOLIC=MELANBIDE34_SUBSOLIC
TABLA_CODIGOS_DESPLEGABLES=E_DES

##################### C\u00d3DIGOS DESPLEGABLES - ININ #####################
#DESPLEGABLE DTSV
COD_DES_DTSV=DTSV

##################### NOMBRES DE SECUENCIAS #####################
SEQ_MELANBIDE34_SUBSOLIC=SEQ_MELANBIDE34_SUBSOLIC


##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide34.i18n.text
FICHEROS_MENSAJES = MELANBIDE34_TEXT_1;MELANBIDE34_TEXT_4

#############################JOB#################################
#DESARROLLO
SERVIDOR = E22_DES_WL12_LANBIDE_FLEXIA111
COD_ORG=0
DOS_ENTORNOS=TRUE

#PRE
#SERVIDOR = paprergi1_flexia1
#COD_ORG=1
#DOS_ENTORNOS=FALSE

#PRO
#SERVIDOR = pargi1_flexia1
#COD_ORG=0
#DOS_ENTORNOS=TRUE

ENTORNO=LOCAL
UNIDAD_ORG=FOMEMT

# EL caracter es pipeline hay que escaparlo porque es un caracter especial para hacer condicion or en regex
BARRA_SEPARADORA_IDIOMA_DESPLEGABLES=\\Q|\\E