# M\u00e9todos del m\u00f3dulo que se utilizan para configurar el m\u00f3dulo en la pesta\u00f1a "Conf.SW"
0/MODULO_INTEGRACION/MELANBIDE51/LISTA_OPERACIONES_DISPONIBLES=
1/MODULO_INTEGRACION/MELANBIDE51/LISTA_OPERACIONES_DISPONIBLES=
# NOMBRE DEL M\u00d3DULO QUE SE MUESTRA JUNTO CON EL NOMBRE DE LA OPERACI\u00d3N; A LA HORA DE SELECCIONAR UNA OPERACI\u00d3N QUE SE ASOCIAR\u00c1 A UN TR\u00c1MITE
# FORMATO: [COD_ORGANIZACION]/MODULO_INTEGRACION/[NOMBRE_MODULO]/NOMBRE_MODULO
0/MODULO_INTEGRACION/MELANBIDE51/DESCRIPCION_MODULO = MODULO CONTROL DE ACCESO
1/MODULO_INTEGRACION/MELANBIDE51/DESCRIPCION_MODULO = MODULO CONTROL DE ACCESO

NOMBRE_MODULO = MELANBIDE51


### Definicion de tablas del Modulo
TABLA_MELANBIDE51_CONTROL_ACCESO=MELANBIDE51_CONTROL_ACCESO
TABLA_CODIGOS_DESPLEGABLES=E_DES
TABLA_VALORES_DESPLEGABLES=E_DES_VAL

### Definicion de Sequencia ID de tabla Control de Acceso
SEQ_MELANBIDE51_CONTROL_ACCESO=SEQ_MELANBIDE51_CONTROL_ACCESO

### Codigo Desplegable Motivo Visita
COD_DES_MOTVIS=MVIS

### OTROS
CARACTERES_ESPECIALES=&'<>|^\\%

UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide51.i18n.text
FICHEROS_MENSAJES = MELANBIDE51_TEXT_1;MELANBIDE51_TEXT_4