##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE13/LISTA_OPERACIONES_DISPONIBLES=
1/MODULO_INTEGRACION/MELANBIDE13/LISTA_OPERACIONES_DISPONIBLES=

##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE13

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE13/DESCRIPCION_MODULO = MODULO CEESA
1/MODULO_INTEGRACION/MELANBIDE13/DESCRIPCION_MODULO = MODULO CEESA

##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE13/CEESA/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = LISTA_EXPEDIENTES
1/MODULO_INTEGRACION/MELANBIDE13/CEESA/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = LISTA_EXPEDIENTES

##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE13/CEESA/URL_PANTALLA_EXPEDIENTE/LISTA_EXPEDIENTES = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE13&operacion=cargarPantallaPrincipal&tipo=0
1/MODULO_INTEGRACION/MELANBIDE13/CEESA/URL_PANTALLA_EXPEDIENTE/LISTA_EXPEDIENTES = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE13&operacion=cargarPantallaPrincipal&tipo=0

##################### TABLAS DEL M\u00d3DULO #####################
MELANBIDE13_LISTA_EXPEDIENTES=MELANBIDE13_LISTA_EXPEDIENTES
TABLA_DESPLEGABLES_EXP=E_TDE
TABLA_TERCERO_EXP=E_EXT
TABLA_TERCEROS=T_HTE
TABLA_VALORES_DESPLEGABLE=E_DES_VAL
TABLA_NUMERICOS_EXP=E_TNU

### SECUENCIAS ID DE TABLAS CONTRATACION
SEQ_MELANBIDE13_LISTA_EXPEDIENTES=SEQ_MELANBIDE13_LISTA_EXPEDIENTES

##################### C\u00d6DIGOS DESPLEGABLES - CEESA #####################
COD_ANIO=ANIOAYUDA
COD_MES=MESAYUDA
COD_TERRITORIO=TERRHIST
COD_IMPORTE=IMPRESOLUCION
COD_DES_ANIO=ANCE
COD_DES_MES=MES
COD_DES_TERRITORIO=TTHH

##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide13.i18n.text
FICHEROS_MENSAJES = MELANBIDE13_TEXT_1;MELANBIDE13_TEXT_4

# EL caracter es pipeline hay que escaparlo porque es un caracter especial para hacer condicion or en regex
BARRA_SEPARADORA_IDIOMA=\\Q|\\E