##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE89/LISTA_OPERACIONES_DISPONIBLES=
1/MODULO_INTEGRACION/MELANBIDE89/LISTA_OPERACIONES_DISPONIBLES=

##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE89

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE89/DESCRIPCION_MODULO = MODULO ACCESOS GO
1/MODULO_INTEGRACION/MELANBIDE89/DESCRIPCION_MODULO = MODULO ACCESOS GO

##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE89/GO/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = ACCESOS
1/MODULO_INTEGRACION/MELANBIDE89/GO/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = ACCESOS

##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE89/GO/URL_PANTALLA_EXPEDIENTE/ACCESOS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE89&operacion=cargarPantallaPrincipal&tipo=0
1/MODULO_INTEGRACION/MELANBIDE89/GO/URL_PANTALLA_EXPEDIENTE/ACCESOS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE89&operacion=cargarPantallaPrincipal&tipo=0

##################### TABLAS DEL M\u00d3DULO #####################
MELANBIDE89_ACCESOS=MELANBIDE89_ACCESOS

### SECUENCIAS ID DE TABLAS CONTRATACION
SEQ_MELANBIDE89_ACCESOS=SEQ_MELANBIDE89_ACCESOS

##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide89.i18n.text
FICHEROS_MENSAJES = MELANBIDE89_TEXT_1;MELANBIDE89_TEXT_4
