##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE18/LISTA_OPERACIONES_DISPONIBLES=fraccionarDeudas;cambioCuentaFraccionamiento
1/MODULO_INTEGRACION/MELANBIDE18/LISTA_OPERACIONES_DISPONIBLES=fraccionarDeudas;cambioCuentaFraccionamiento

##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE18

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE18/DESCRIPCION_MODULO = Fraccionamiento deudas prestaciones FRACC/FRACU/FRACR
1/MODULO_INTEGRACION/MELANBIDE18/DESCRIPCION_MODULO = Fraccionamiento deudas prestaciones FRACC/FRACU/FRACR

##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE18/FRACC/2/PANTALLA_TRAMITE/NOMBRE_PANTALLAS = DEUDAS
1/MODULO_INTEGRACION/MELANBIDE18/FRACC/2/PANTALLA_TRAMITE/NOMBRE_PANTALLAS = DEUDAS

##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE18/FRACC/2/URL_PANTALLA_TRAMITACION/DEUDAS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE18&operacion=cargarPantallaDeudasFracc&tipo=0
1/MODULO_INTEGRACION/MELANBIDE18/FRACC/2/URL_PANTALLA_TRAMITACION/DEUDAS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE18&operacion=cargarPantallaDeudasFracc&tipo=0

##################### NOMBRES DE TABLAS #####################
VISTA_DEUDAS_A_FRACCIONAR=LANZK.VW_INFO_DEUDAS_A_FRACCIONAR
TABLA_MELANBIDE18_DEUDASFRAC=MELANBIDE18_DEUDASFRACC
TABLA_E_EXT=E_EXT
TABLA_T_HTE=T_HTE
TABLA_E_TRA=E_TRA
TABLA_E_CRO=E_CRO

##################### NOMBRES DE SECUENCIAS #####################
SECUENCIA_M18_DEUDASFRAC=SEQ_M18_DEUDASFRACC

################# SUPLEMENTARIOS #################
CAMPO_CTAIBAN=CTAIBAN
CAMPO_CTAENTIDAD=CTAENTIDAD
CAMPO_CTASUCURSAL=CTASUCURSAL
CAMPO_CTADC=CTADC
CAMPO_CTANUMERO=CTANUMCUENTA
CAMPO_CUOTA=IMPMENSDEUDA
CAMPO_TODAS=DEUDFRACC
CAMPO_ESTIMA_RECURSO=RECURESTIM

##########################################################
### DATOS PARA LA CONEXION AL SERVICIO ###################
##########################################################
USUARIO_ZORKU=REGEXLANWS
PASS_ZORKU=REGEXLANWS
URL_FRACCIONAMIENTO=https://zorku.des.lanbide.eus/Zorku/api/altaFraccionamiento
URL_CAMBIO_CUENTA=http://integ.serv.des.lanbide.lan/Zorku/api/cambioCuentaDomiciliacion
URL_RECURSO=http://integ.serv.des.lanbide.eus/Zorku/api/recursoResolucion

##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide18.i18n.text
FICHEROS_MENSAJES = MELANBIDE18_TEXT_1;MELANBIDE18_TEXT_4

# EL caracter es pipeline hay que escaparlo porque es un caracter especial para hacer condicion or en regex
BARRA_SEPARADORA_IDIOMA=\\Q|\\E

####################################################################################################################
##################      CÓDIGOS DE ERROR PARA LA OPERACIÓN LLAMA SERVICIO fraccionarDeudas      ####################
####################################################################################################################
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/1=ERROR_1
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/10=ERROR_10
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/11=ERROR_11
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/12=ERROR_12
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/13=ERROR_13
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/14=ERROR_14
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/15=ERROR_15
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/16=ERROR_16
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/17=ERROR_17
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/18=ERROR_18
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/19=ERROR_19
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/20=ERROR_20
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/23=ERROR_23
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/25=ERROR_25
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/403=ERROR_403
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/404=ERROR_404
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/500=ERROR_500
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/503=ERROR_503
## errores ZORKU
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/ZorUsuario=ERROR_30
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/ZOR-CAMPO-OBLIGATORIO=ERROR_31
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/ZORKU-DEUDA_FRACC-TERCERO=ERROR_32
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/ZORKU-DEUDA_FRACC=ERROR_33
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/ZOR-TAMANO-FORMATO-INCORRECTO=ERROR_34
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/ZORKU-DEUDA_TOTAL-TERCERO=ERROR_35

###############################################################################################################################
##################      CODIGOS DE ERROR PARA LA OPERACIÓN LLAMA SERVICIO cambioCuentaFraccionamiento      ####################
###############################################################################################################################
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/1=ERROR_1
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/11=ERROR_11
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/12=ERROR_12
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/13=ERROR_13
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/14=ERROR_14
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/15=ERROR_15
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/16=ERROR_16
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/17=ERROR_17
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/20=ERROR_20
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/21=ERROR_21
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/22=ERROR_22
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/403=ERROR_403
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/404=ERROR_404
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/500=ERROR_500
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/503=ERROR_503
## errores ZORKU
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/ZorUsuario=ERROR_30
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/ZOR-CAMPO-OBLIGATORIO=ERROR_31
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/ZORKU-DEUDA_FRACC=ERROR_33
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/ZOR-TAMANO-FORMATO-INCORRECTO=ERROR_34
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/ZORKU-DEUDA_TOTAL-TERCERO=ERROR_35

############################################################################################################
##################      CÓDIGOS DE ERROR PARA LA OPERACIÓN  recursoResolucionFRACC      ####################
############################################################################################################
0/MODULO_INTEGRACION/recursoResolucionFRACC/MENSAJE_ERROR/1=ERROR_1

##################### DESCRIPCION ERRORES
ERROR_1_1=Ha ocurrido un error gen\u00e9rico.
ERROR_10_1=Ha ocurrido un error gen\u00e9rico en la llamada al servicio de Fraccionamiento.
ERROR_11_1=Falta IBAN de la Cuenta bancaria.
ERROR_12_1=Falta la Entidad Bancaria.
ERROR_13_1=Falta la sucursal.
ERROR_14_1=Falta el D\u00edgito de Control de la cuenta.
ERROR_15_1=Falta el n\u00famero de cuenta.
ERROR_16_1=Alg\u00fan campo de la cuenta tiene un tama\u00f1o o formato incorrecto
ERROR_17_1=El n\u00famero de cuenta corriente no es correcto
ERROR_18_1=No se ha(n) recuperado la(s) deuda(s) a fraccionar
ERROR_19_1=No se ha recuperado el tel\u00e9fono del interesado
ERROR_20_1=Se ha producido un error recuperando el n\u00famero del documento del interesado.
ERROR_21_1=Se ha producido un error gen\u00e9rico en la llamada al servicio de Cambio de Cuenta
ERROR_22_1=El servicio de Cambio de Cuenta ha devuelto un error. Consulte con el Administrador
ERROR_23_1=El servicio de Fraccionamiento ha devuelto un error. Consulte con el Administrador
ERROR_24_1=El servicio de ZORKU ha devuelto un error gestionando la resolución. Consulte con el Administrador.
ERROR_25_1=Falta el valor el campo \u0022Solicita Fraccionar Todas las Deudas\u0022.
## errores ZORKU
ERROR_30_1=El usuario de invocación no es v\u00e1lido
ERROR_31_1=Falta alg\u00fan campo obligatorio. Consulte con el Administrador.
ERROR_32_1=Alguna de las deudas introducidas en la lista no se puede fraccionar. Revise el listado
ERROR_33_1=El tercero no tiene deudas a fraccionar.
ERROR_34_1=Alg\u00fan campo tiene un tama\u00f1o o formato incorrecto. Consulte con el Administrador.
ERROR_35_1=El tercero consultado no existe en Zorku
## errores HTTP
ERROR_403_1=No est\u00e1 permitido el acceso al servicio de ZORKU.
ERROR_404_1=No est\u00e1 disponible el servicio de ZORKU. Int\u00e9ntelo más tarde.
ERROR_500_1=Se ha producido un error en el servidor al realizar la llamada al servicio de ZORKU. Int\u00e9ntelo más tarde.
ERROR_503_1=No est\u00e1 disponible el servicio de ZORKU. Int\u00e9ntelo más tarde.

ERROR_1_4=Errore generiko bat gertatu da.
ERROR_10_4=Errore generiko bat gertatu da SWaren erantzunean
ERROR_11_4=IBAN falta da
ERROR_12_4=Banketxea falta da
ERROR_13_4=Sukurtsala falta da
ERROR_14_4=Kontuaren kontrol-digitua falta da
ERROR_15_4=Kontuaren zenbakia falta da
ERROR_16_4=Kontu-zenbakia ez da baliozkoa - Daturen baten tamaina ez da zuzena
ERROR_17_4=Kontu-zenbakia ez da baliozkoa
ERROR_18_4=Zatikatu beharreko zorra (k) ez da berreskuratu.
ERROR_19_4=Ez da interesdunaren telefonoa berreskuratu.
ERROR_20_4=Errorea gertatu da interesdunaren dokumentuaren zenbakia berreskuratzean.
ERROR_21_4=Errorea gertatu da kontua aldatzeko zerbitzura egindako deian
ERROR_22_4=ZORKUren Kontua aldatzeko zerbitzuak errore bat itzuli du. Galdetu administratzaileari.
ERROR_23_4=ZORKUren zatikapen-zerbitzuak akats bat itzuli du. Galdetu administratzaileari.
ERROR_24_4=ZORKU zerbitzuak errore bat itzuli du ebazpena kudeatzean. Galdetu administratzaileari.
ERROR_25_4=\u0022Zor guztiak zatikatzea eskatzen du\u0022 eremuaren balioa falta da.
## errores ZORKU
ERROR_30_4=Deiaren erabiltzaileak ez du balio
ERROR_31_4=Nahitaezko eremuren bat falta da. Galdetu administratzaileari.
ERROR_32_4=Zorretako bat zatituta dago. Berrikusi zerrenda.
ERROR_33_4=Hirugarrenak ez du zatitzeko zorrik.
ERROR_34_4=Eremuren batek tamaina edo formatu okerra du. Galdetu administratzaileari.
ERROR_35_4=Kontsultatutako hirugarrena ez dago Zorkun
## errores HTTP
ERROR_403_4=Ezin da ZORKU zerbitzura sartu.
ERROR_404_4=ZORKU zerbitzua ez dago erabilgarri. Saia zaitez geroago.
ERROR_500_4=Errorea gertatu da zerbitzarian ZORKU zerbitzura deitzean. Saia zaitez geroago.
ERROR_503_4=ZORKU zerbitzua ez dago erabilgarri. Saia zaitez geroago..