##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE54/LISTA_OPERACIONES_DISPONIBLES=llamadaSWSEPEBajaCentro
1/MODULO_INTEGRACION/MELANBIDE54/LISTA_OPERACIONES_DISPONIBLES=llamadaSWSEPEBajaCentro

#####URL_WS_REGISTRO#########################################################################
#URL_WS_REGISTRO=http://10.168.212.21:7081/WSTramitacion/services/WSTramitacionPort?wsdl
URL_WS_REGISTRO=http://integ.serv.des.lanbide.lan/WSTramitacion/services/WSTramitacionPort?wsdl
#PRE
#URL_WS_REGISTRO=http://10.168.212.161:17003/WSTramitacion/services/WSTramitacionPort?wsdl
#PRO
#URL_WS_REGISTRO=http://integ.serv.lanbide.lan/WSTramitacion/services/WSTramitacionPort?wsdl


##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE54
COD_PROCEDIMIENTO=AACC

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE54/DESCRIPCION_MODULO = Mantenimiento de lista de centros de trabajo
1/MODULO_INTEGRACION/MELANBIDE54/DESCRIPCION_MODULO = Mantenimiento de lista de centros de trabajo

##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE54/AACC/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CENTROS_TRABAJO
1/MODULO_INTEGRACION/MELANBIDE54/AACC/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CENTROS_TRABAJO


##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE54/AACC/URL_PANTALLA_EXPEDIENTE/CENTROS_TRABAJO = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE54&operacion=cargarPantallaPrincipal&tipo=0
1/MODULO_INTEGRACION/MELANBIDE54/AACC/URL_PANTALLA_EXPEDIENTE/CENTROS_TRABAJO = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE54&operacion=cargarPantallaPrincipal&tipo=0

0/MODULO_INTEGRACION/MELANBIDE54/AACC/PANTALLA_EXPEDIENTE_RELACION/NOMBRE_PANTALLAS=CENTROS_TRABAJO
1/MODULO_INTEGRACION/MELANBIDE54/AACC/PANTALLA_EXPEDIENTE_RELACION/NOMBRE_PANTALLAS=CENTROS_TRABAJO

0/MODULO_INTEGRACION/MELANBIDE54/AACC/URL_PANTALLA_EXPEDIENTE_RELACION/CENTROS_TRABAJO = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE54&operacion=cargarPantallaPrincipal&tipo=0
1/MODULO_INTEGRACION/MELANBIDE54/AACC/URL_PANTALLA_EXPEDIENTE_RELACION/CENTROS_TRABAJO = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE54&operacion=cargarPantallaPrincipal&tipo=0



##################### NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE #####################
0/MODULO_INTEGRACION/MELANBIDE54/AACC/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/ESPECIALIDADES =
0/MODULO_INTEGRACION/MELANBIDE54/AACC/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR =
1/MODULO_INTEGRACION/MELANBIDE54/AACC/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/ESPECIALIDADES =

0/MODULO_INTEGRACION/MELANBIDE54/AACC/PANTALLA_EXPEDIENTE/SALIDA = /jsp/extension/MELANBIDE54/MELANBIDE54.jsp
1/MODULO_INTEGRACION/MELANBIDE54/AACC/PANTALLA_EXPEDIENTE/SALIDA = /jsp/extension/MELANBIDE54/MELANBIDE54.jsp

##################### NOMBRE DE LA OPERACION DEL MODULO QUE SE ENCARGA DE ACTUALIZAR LOS DATOS DE LA PANTALLA DE EXPEDIENTE #####################
0/MODULO_INTEGRACION/MELANBIDE54/AACC/ACTUALIZAR_PANTALLA_EXPEDIENTE/ESPECIALIDADES = 
1/MODULO_INTEGRACION/MELANBIDE54/AACC/ACTUALIZAR_PANTALLA_EXPEDIENTE/ESPECIALIDADES = 


##################### NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE DE UNA RELACI\u00d3N ENTRE EXPEDIENTES #####################
0/MODULO_INTEGRACION/MELANBIDE54/AACC/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/ESPECIALIDADES  =
1/MODULO_INTEGRACION/MELANBIDE54/AACC/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/ESPECIALIDADES  =

#####################################################
0/MODULO_INTEGRACION/MELANBIDE54/AACC/ESPECIALIDADES/CODIGOS_UNIDADES_ORGANICAS_VALIDAS
1/MODULO_INTEGRACION/MELANBIDE54/AACC/ESPECIALIDADES/CODIGOS_UNIDADES_ORGANICAS_VALIDAS




##################### NOMBRES DE TABLAS #####################
TABLA_AACC_ESPECIALIDADES=MELANBIDE54_ESPECIALIDADES
TABLA_AACC_SERVICIOS=MELANBIDE54_SERVICIOS
TABLA_AACC_DISPONRECURSOS=MELANBIDE54_DISPONRECURSOS
TABLA_AACC_CAPACIDADINSTALA=MELANBIDE54_CAPACIDADINST
TABLA_AACC_DOTACION=MELANBIDE54_DOTACION
TABLA_AACC_MATERIALCONSUMO=MELANBIDE54_MATERIALCONSU
TABLA_AACC_IDENTIFICACIONESP=MELANBIDE54_IDENTIFICESP
#TABLA_CER_CERTIFICADOS=CER_CERTIFICADOS
TABLA_CER_CERTIFICADOS = FPE_ESP_ESPECIALIDADESCAT
TABLA_AACC_CENTROS=MELANBIDE54_CENTROS


##################### NOMBRES DE SECUENCIAS #####################
SEQ_AACC_ESPECIALIDADES=SEQ_MELANBIDE54_ESPECIALIDADES
SEQ_AACC_SERVICIOS=SEQ_MELANBIDE54_SERVICIOS
SEQ_AACC_DISPONRECURSOS=SEQ_MELANBIDE54_DISPONRECURSOS
SEQ_AACC_CAPACIDADINSTALA=SEQ_MELANBIDE54_CAPACIDADINST
SEQ_AACC_DOTACION=SEQ_MELANBIDE54_DOTACION
SEQ_AACC_MATERIALCONSUMO=SEQ_MELANBIDE54_MATERIALCONSU
SEQ_AACC_IDENTIFICACIONESP=SEQ_MELANBIDE54_IDENTIFICESP


##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide54.i18n.text
FICHEROS_MENSAJES = MELANBIDE54_TEXT_1;MELANBIDE54_TEXT_4


###########  OTRAS CONFIGURACIONES #####

MSG_ERROR_FECHA_NO_VALIDA_1 = Fecha no v\u00e1lida
MSG_ERROR_FECHA_NO_VALIDA_4 = Balio gabeko data



# URL SERVICIO WEB DE ALTA DE CENTROS Y ESPECIALIDADES
## URL_WS_REGISTROCENTROS = http://10.168.212.161:11003/ikaslanWS/WSRegistroCentrosFormacion?wsdl
URL_WS_REGISTROCENTROS = http://integ.serv.des.lanbide.lan/ikaslanWS/WSRegistroCentrosFormacion?wsdl

############ CODIGOS DE CAMPOS SUPLEMENTARIOS #######
# Codigo campo codCentro definido a nivel del tr\u00e1mite "CONSULTA Y SELECCION DE CENTRO"
CODIGO_CAMPO_CODCENTRO = CODCENTRO
# Codigo campo codUbicacion definido a nivel del tr\u00e1mite "CONSULTA Y SELECCION DE CENTRO"
CODIGO_CAMPO_CODUBICACION = CODUBICACION
# Codigo campo suplementario TIPOCENTRO definido a nivel del tr\u00e1mite "CONSULTA Y SELECCION DE CENTRO"
CODIGO_CAMPO_TIPOCENTRO = TIPOCENTRO

# C\u00f3digo campo suplementario de tr\u00e1mite en el que se almacenar\u00e1 el n\u00famero de registro devuelto por la operaci\u00f3n
# altaCentroConEspecialidades
CODIGO_CAMPO_NUMREGISTRO_VASCO = NUMREGCENTRO

# C\u00f3digo del campo suplementario que contiene la fecha de resoluci\u00f3n
CODIGO_CAMPO_TRAMITE_FECHA_RESOLUCION = FECRESOL


###### ERRORES PERSONALIZADOS DE LA OPERACI\u00d3N altaCentroConEspecialidades 
0/MODULO_INTEGRACION/altaCentroConEspecialidades/MENSAJE_ERROR/1= ERROR_PROPIEDADES_ARCHIVO_CONFIGURACION
0/MODULO_INTEGRACION/altaCentroConEspecialidades/MENSAJE_ERROR/2= ERROR_VALORES_PROPIEDADES_ARCHIVO_CONFIGURACION
0/MODULO_INTEGRACION/altaCentroConEspecialidades/MENSAJE_ERROR/3= ERROR_CONEXION_SERVICIO_WEB
0/MODULO_INTEGRACION/altaCentroConEspecialidades/MENSAJE_ERROR/4= ERROR_CODCENTRO_SIN_VALOR
0/MODULO_INTEGRACION/altaCentroConEspecialidades/MENSAJE_ERROR/5= ERROR_CODUBICACION_SIN_VALOR
0/MODULO_INTEGRACION/altaCentroConEspecialidades/MENSAJE_ERROR/6= ERROR_FECHARESOLUCION_SIN_VALOR
0/MODULO_INTEGRACION/altaCentroConEspecialidades/MENSAJE_ERROR/7= ERROR_CONEXION_BD
0/MODULO_INTEGRACION/altaCentroConEspecialidades/MENSAJE_ERROR/8= ERROR_TIPO_CENTRO_SIN_VALOR
0/MODULO_INTEGRACION/altaCentroConEspecialidades/MENSAJE_ERROR/9= ERROR_CODIGO_TIPO_CENTRO
0/MODULO_INTEGRACION/altaCentroConEspecialidades/MENSAJE_ERROR/10= ERROR_ALTA_CENTRO_SERVICIO_WEB
0/MODULO_INTEGRACION/altaCentroConEspecialidades/MENSAJE_ERROR/11= ERROR_TECNICO_CENTRO_SERVICIO_WEB
0/MODULO_INTEGRACION/altaCentroConEspecialidades/MENSAJE_ERROR/12= ERROR_NUMERO_CENSO_REGISTRO_DESCONOCIDO
0/MODULO_INTEGRACION/altaCentroConEspecialidades/MENSAJE_ERROR/13= ERROR_GRABACION_NUMERO_REGISTRO
0/MODULO_INTEGRACION/altaCentroConEspecialidades/MENSAJE_ERROR/14= ERROR_ESPECIALIDADES_CENTRO_VACIAS


1/MODULO_INTEGRACION/altaCentroConEspecialidades/MENSAJE_ERROR/1= ERROR_PROPIEDADES_ARCHIVO_CONFIGURACION
1/MODULO_INTEGRACION/altaCentroConEspecialidades/MENSAJE_ERROR/2= ERROR_VALORES_PROPIEDADES_ARCHIVO_CONFIGURACION
1/MODULO_INTEGRACION/altaCentroConEspecialidades/MENSAJE_ERROR/3= ERROR_CONEXION_SERVICIO_WEB
1/MODULO_INTEGRACION/altaCentroConEspecialidades/MENSAJE_ERROR/4= ERROR_CODCENTRO_SIN_VALOR
1/MODULO_INTEGRACION/altaCentroConEspecialidades/MENSAJE_ERROR/5= ERROR_CODUBICACION_SIN_VALOR
1/MODULO_INTEGRACION/altaCentroConEspecialidades/MENSAJE_ERROR/6= ERROR_FECHARESOLUCION_SIN_VALOR
1/MODULO_INTEGRACION/altaCentroConEspecialidades/MENSAJE_ERROR/7= ERROR_CONEXION_BD
1/MODULO_INTEGRACION/altaCentroConEspecialidades/MENSAJE_ERROR/8= ERROR_TIPO_CENTRO_SIN_VALOR
1/MODULO_INTEGRACION/altaCentroConEspecialidades/MENSAJE_ERROR/9= ERROR_CODIGO_TIPO_CENTRO
1/MODULO_INTEGRACION/altaCentroConEspecialidades/MENSAJE_ERROR/10= ERROR_ALTA_CENTRO_SERVICIO_WEB
1/MODULO_INTEGRACION/altaCentroConEspecialidades/MENSAJE_ERROR/11= ERROR_TECNICO_CENTRO_SERVICIO_WEB
1/MODULO_INTEGRACION/altaCentroConEspecialidades/MENSAJE_ERROR/12= ERROR_NUMERO_CENSO_REGISTRO_DESCONOCIDO
1/MODULO_INTEGRACION/altaCentroConEspecialidades/MENSAJE_ERROR/13= ERROR_GRABACION_NUMERO_REGISTRO
1/MODULO_INTEGRACION/altaCentroConEspecialidades/MENSAJE_ERROR/14= ERROR_ESPECIALIDADES_CENTRO_VACIAS

ERROR_PROPIEDADES_ARCHIVO_CONFIGURACION_1 = Error al obtener las propiedades de configuraci\u00f3n
ERROR_PROPIEDADES_ARCHIVO_CONFIGURACION_4 = Error al obtener las propiedades de configuraci\u00f3n

ERROR_VALORES_PROPIEDADES_ARCHIVO_CONFIGURACION_1 = Revisar las propiedades de configuraci\u00f3n con los valores de los campos suplementarios y c\u00f3digo de tr\u00e1mite
ERROR_VALORES_PROPIEDADES_ARCHIVO_CONFIGURACION_4 = Revisar las propiedades de configuraci\u00f3n con los valores de los campos suplementarios y c\u00f3digo de tr\u00e1mite

ERROR_CONEXION_SERVICIO_WEB_1 = No se ha podido establecer conexi\u00f3n con el servicio web de centros de formaci\u00f3n 
ERROR_CONEXION_SERVICIO_WEB_4 = No se ha podido establecer conexi\u00f3n con el servicio web de centros de formaci\u00f3n 

ERROR_CODCENTRO_SIN_VALOR_1 = El campo suplementario de expediente con el c\u00f3digo de centro no tiene valor
ERROR_CODCENTRO_SIN_VALOR_4 = El campo suplementario de expediente con el c\u00f3digo de centro no tiene valor

ERROR_CODUBICACION_SIN_VALOR_1 = El campo suplementario de expediente con el c\u00f3digo de ubicaci\u00f3n no tiene valor
ERROR_CODUBICACION_SIN_VALOR_4 = El campo suplementario de expediente con el c\u00f3digo de ubicaci\u00f3n no tiene valor

ERROR_FECHARESOLUCION_SIN_VALOR_1 = No se ha podido obtener el valor del campo Fecha de resoluci\u00f3n
ERROR_FECHARESOLUCION_SIN_VALOR_4 = No se ha podido obtener el valor del campo Fecha de resoluci\u00f3n

ERROR_CONEXION_BD_1 = No se ha podido obtener una conexi\u00f3n a la BBDD
ERROR_CONEXION_BD_4 = No se ha podido obtener una conexi\u00f3n a la BBDD

ERROR_TIPO_CENTRO_SIN_VALOR_1 = El campo suplementario tipo centro no tiene valor
ERROR_TIPO_CENTRO_SIN_VALOR_4 = El campo suplementario tipo centro no tiene valor

ERROR_CODIGO_TIPO_CENTRO_1 = No se puede obtener el c\u00f3digo correspondiente al tipo de centro de base de datos
ERROR_CODIGO_TIPO_CENTRO_4 = No se puede obtener el c\u00f3digo correspondiente al tipo de centro de base de datos

ERROR_ALTA_CENTRO_SERVICIO_WEB_1 = No se ha podido dar de alta el centro con la especialidades en el servicio web de centros de formaci\u00f3n
ERROR_ALTA_CENTRO_SERVICIO_WEB_4 = No se ha podido dar de alta el centro con la especialidades en el servicio web de centros de formaci\u00f3n

ERROR_NUMERO_CENSO_REGISTRO_DESCONOCIDO_1 = Se ha grabado las especialidades del centro pero no se ha obtenido el n\u00famero de censo del Registro Vasco
ERROR_NUMERO_CENSO_REGISTRO_DESCONOCIDO_4 = Se ha grabado las especialidades del centro pero no se ha obtenido el n\u00famero de censo del Registro Vasco

ERROR_TECNICO_CENTRO_SERVICIO_WEB_1 = Se ha producido un error t\u00e9cnico al ejecutar la operaci\u00f3n altaCentrosConEspecialidades
ERROR_TECNICO_CENTRO_SERVICIO_WEB_4 = Se ha producido un error t\u00e9cnico al ejecutar la operaci\u00f3n altaCentrosConEspecialidades

ERROR_GRABACION_NUMERO_REGISTRO_1 = Se ha producido un error al grabar el n\u00famero de registro
ERROR_GRABACION_NUMERO_REGISTRO_4 = Se ha producido un error al grabar el n\u00famero de registro

ERROR_ESPECIALIDADES_CENTRO_VACIAS_1 = No se han seleccionado las especialidades del centro
ERROR_ESPECIALIDADES_CENTRO_VACIAS_4 = No se han seleccionado las especialidades del centro


###### ERRORES PERSONALIZADOS DE LA OPERACI\u00d3N envioCorreoAltaCentro 
0/MODULO_INTEGRACION/envioCorreoAltaCentro/MENSAJE_ERROR/1= ERROR_RECUPERAR_INTERESADOS
0/MODULO_INTEGRACION/envioCorreoAltaCentro/MENSAJE_ERROR/2= ERROR_EXPEDIENTE_SIN_INTERESADOS
0/MODULO_INTEGRACION/envioCorreoAltaCentro/MENSAJE_ERROR/3= ERROR_OBTENER_CONEXION
0/MODULO_INTEGRACION/envioCorreoAltaCentro/MENSAJE_ERROR/4= ERROR_SERVICIO_EMAIL_NO_ACTIVADO
0/MODULO_INTEGRACION/envioCorreoAltaCentro/MENSAJE_ERROR/5= ERROR_ENVIO_EMAIL

1/MODULO_INTEGRACION/envioCorreoAltaCentro/MENSAJE_ERROR/1= ERROR_RECUPERAR_INTERESADOS
1/MODULO_INTEGRACION/envioCorreoAltaCentro/MENSAJE_ERROR/2= ERROR_EXPEDIENTE_SIN_INTERESADOS
1/MODULO_INTEGRACION/envioCorreoAltaCentro/MENSAJE_ERROR/3= ERROR_OBTENER_CONEXION
1/MODULO_INTEGRACION/envioCorreoAltaCentro/MENSAJE_ERROR/4= ERROR_SERVICIO_EMAIL_NO_ACTIVADO
1/MODULO_INTEGRACION/envioCorreoAltaCentro/MENSAJE_ERROR/5= ERROR_ENVIO_EMAIL

ERROR_RECUPERAR_INTERESADOS_1= Error al recuperar los interesados del expediente
ERROR_RECUPERAR_INTERESADOS_4= Error al recuperar los interesados del expediente

ERROR_EXPEDIENTE_SIN_INTERESADOS_1= Expdiente sin interesados asociados
ERROR_EXPEDIENTE_SIN_INTERESADOS_4= Expdiente sin interesados asociados

ERROR_OBTENER_CONEXION_1= Error al obtener la conexi\u00f3n de BD 
ERROR_OBTENER_CONEXION_4= Error al obtener la conexi\u00f3n de BD

ERROR_SERVICIO_EMAIL_NO_ACTIVADO_1= Servicio de email no activado
ERROR_SERVICIO_EMAIL_NO_ACTIVADO_4= Servicio de email no activado

ERROR_ENVIO_EMAIL_1= Error en el env\u00edo del email
ERROR_ENVIO_EMAIL_4= Error en el env\u00edo del email

## -----------------------------------------------------
# ENVIO DE MAIL
# -----------------------------------------------------
###### VALORES PARA EL ENVIO DE CORREOS EN EL ALTA DE CENTRO envioCorreoAltaCentro
mail.destinatario= olaia.albizu@lanbide.net
mail.remitente= regexlan@lanbide.net
mail.asunto= Alta de nuevo centro / ubicaci\u00f3n
mail.contenido= INTERESADO @interesado@ \n Rol: @rol@ \n Documento:@documento@ \n Nombre:@nombre@ \n Domicilio: @domicilio@ \n Municipio: @municipio@ \n Provincia: @provincia@ \n C\u00f3digo postal: @codigopostal@ \n Email: @email@ \n Telefono: @telefono@ \n\n

#############################JOB#################################
#DESARROLLO
SERVIDOR = E22_DES_WL12_LANBIDE_FLEXIA111
COD_ORG=0
DOS_ENTORNOS=TRUE
COD_UOR=9
COMPROBACION_AGENCIA=13
GENERACION_NMERO_DE_AGENCIA_EN_SILCOI_WEB=14
COMPROBACION_NUEVO_CENTRO=20
COMUNICACION_NUMERO_DE_AGENCIA_ALTA_CENTRO=15
COMUNICACION_NUEVA_AGENCIA_CENTRO=16
NUEVA_VISITA=19
COMUNICACION_AGENCIA_YA_REGISTRADA=18
CIERRE_DE_EXPEDIENTE=8

INICIO_DE_EXPEDIENTE=1
NOTIFICACION_INICIO_EXPEDIENTE_BAJA_CENTRO=2
ESPERA_ACUSE_RECIBO=3
ESPERA_RECEPCION_ALEGACIONES_SUBSANACION=4
REVISION_ALEGACIONES=5
NOTIFICACION_RESOLUCION_ALEGACIONES=6
ESPERA_ACUSE_RECIBO_RESOLUCION_ALEGACIONES=7
NOTIFICACION_RESOLUCION_BAJA=8
ESPERA_ACUSE_RECIBO_RESOLUCION_BAJA=9
BAJA_CENTRO_REGISTRO =10
CIERRE_DE_EXPEDIENTE_ESTIMADAS=11
CIERRE_DE_EXPEDIENTE_DESESTIMADAS=12

#PRE
#SERVIDOR = paprergi1_flexia1
#COD_ORG=1
#DOS_ENTORNOS=FALSE
#COD_UOR=103
#COMPROBACION_AGENCIA=
#GENERACION_NMERO_DE_AGENCIA_EN_SILCOI_WEB=
#COMPROBACION_NUEVO_CENTRO=
#COMUNICACION_NUMERO_DE_AGENCIA_ALTA_CENTRO=
#COMUNICACION_NUEVA_AGENCIA_CENTRO=
#NUEVA_VISITA=
#COMUNICACION_AGENCIA_YA_REGISTRADA=
#CIERRE_DE_EXPEDIENTE=

#PRO
#SERVIDOR = pargi1_flexia1
#COD_ORG=0
#DOS_ENTORNOS=TRUE
#COD_UOR=103
#COMPROBACION_AGENCIA=
#GENERACION_NMERO_DE_AGENCIA_EN_SILCOI_WEB=
#COMPROBACION_NUEVO_CENTRO=
#COMUNICACION_NUMERO_DE_AGENCIA_ALTA_CENTRO=
#COMUNICACION_NUEVA_AGENCIA_CENTRO=
#NUEVA_VISITA=
#COMUNICACION_AGENCIA_YA_REGISTRADA=
#CIERRE_DE_EXPEDIENTE=

##########################################################################################################################
### DATOS PARA LA CONEXION A LOS SERVICIOS WEB DEL SEPE ###################
#CONSULTA AGENCIA
URL_SW_IWACCIFS=http://svc.integracion.des.ejgv.jaso/ctxweb/LAN02ACSEPEConsulta?WSDL
NAMESPACE_SW_IWACCIFS=http://namespace.softwareag.com/entirex/xml/mapping
NAME_SW_IWACCIFS=IWACCIFS
#PRE
#URL_SW_IWACCIFS=http://svc.integracion.pru.ejgv.jaso/ctxweb/LAN02ACSEPEConsulta?WSDL
#NAMESPACE_SW_IWACCIFS=http://namespace.softwareag.com/entirex/xml/mapping
#NAME_SW_IWACCIFS=IWACCIFS
#PRO
#URL_SW_IWACCIFS=http://svc.integracion.ejgv.jaso/ctxweb/LAN02ACSEPEConsulta?WSDL
#NAMESPACE_SW_IWACCIFS=http://namespace.softwareag.com/entirex/xml/mapping
#NAME_SW_IWACCIFS=IWACCIFS

#ALTA AGENCIA
URL_SW_IWACALAS=http://svc.integracion.des.ejgv.jaso/ctxweb/LAN02ACSEPEAlta?WSDL
NAMESPACE_SW_IWACALAS=http://namespace.softwareag.com/entirex/xml/mapping
NAME_SW_IWACALAS=IWACALAS
#PRE
#URL_SW_IWACALAS=http://svc.integracion.pru.ejgv.jaso/ctxweb/LAN02ACSEPEAlta?WSDL
#NAMESPACE_SW_IWACALAS=http://namespace.softwareag.com/entirex/xml/mapping
#NAME_SW_IWACALAS=IWACALAS
#PRO
#URL_SW_IWACALAS=http://svc.integracion.ejgv.jaso/ctxweb/LAN02ACSEPEAlta?WSDL
#NAMESPACE_SW_IWACALAS=http://namespace.softwareag.com/entirex/xml/mapping
#NAME_SW_IWACALAS=IWACALAS

#ALTA CENTRO
URL_SW_IWACACTS=http://svc.integracion.des.ejgv.jaso/ctxweb/LAN02ACSEPEAltaCentro?WSDL
NAMESPACE_SW_IWACACTS=http://namespace.softwareag.com/entirex/xml/mapping
NAME_SW_IWACACTS=IWACACTS
#PRE
#URL_SW_IWACACTS=http://svc.integracion.pru.ejgv.jaso/ctxweb/LAN02ACSEPEAltaCentro?WSDL
#NAMESPACE_SW_IWACACTS=http://namespace.softwareag.com/entirex/xml/mapping
#NAME_SW_IWACACTS=IWACACTS
#PRO
#URL_SW_IWACACTS=http://svc.integracion.ejgv.jaso/ctxweb/LAN02ACSEPEAltaCentro?WSDL
#NAMESPACE_SW_IWACACTS=http://namespace.softwareag.com/entirex/xml/mapping
#NAME_SW_IWACACTS=IWACACTS

USUARIO_SWSEPE=LANBIDE001
EXISTE_AGENCIA=IAG0017
NO_EXISTE_AGENCIA=IAG0018
TABLA_CAMPOS_TEXTO=E_TXT
TABLA_CAMPOS_DESPLEGABLES=E_TDE
CAMPO_COD_AGENCIA=NUMAGENCIA2
CAMPO_COD_CENTRO=CODSEPE
CAMPO_PAGWEB=PAGWEB
CAMPO_ACTREALIZ=ACTREALIZ
CAMPO_CORREOWEB=CORREOWEB
CAMPO_ETT=ETT
