##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE56/LISTA_OPERACIONES_DISPONIBLES=altaRegistro
1/MODULO_INTEGRACION/MELANBIDE56/LISTA_OPERACIONES_DISPONIBLES=altaRegistro

##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO=MELANBIDE56

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE56/DESCRIPCION_MODULO=M\u00d3DULO DE EXTENSI\u00d3N DE REGISTRO DE SALIDA DE DOCUMENTACI\u00d3N
1/MODULO_INTEGRACION/MELANBIDE56/DESCRIPCION_MODULO=M\u00d3DULO DE EXTENSI\u00d3N DE REGISTRO DE SALIDA DE DOCUMENTACI\u00d3N

##################### NOMBRES DE TABLAS #####################
TABLA_TERCEROS=T_TER
TABLA_TERCEROS_HIST=T_HTE
TABLA_REL_TERCERO_DOMICILIO=E_EXT
TABLA_DOMICILIO=T_DNN
TABLA_T_DOT=T_DOT
TABLA_E_TNU=E_TNU
TABLA_E_TFE=E_TFE
TABLA_E_EXP=E_EXP
TABLA_E_EXR=E_EXR
TABLA_R_RES=R_RES
TABLA_T_VIA=T_VIA

##################### CAMPOS SUPLEMENTARIOS #####################

CAMPO_SUPL_FECREGSALIDA=FECREGSALIDA
CAMPO_SUPL_NUMREGSALIDA=NUMREGSALIDA

##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide56.i18n.text
FICHEROS_MENSAJES = MELANBIDE56_TEXT_1;MELANBIDE56_TEXT_4

##################### URL SERVICIO #####################

#DESARROLLO
#URL_WS_REGISTRO=http://10.168.212.21:7081/WSRegistroES/services/WSRegistroESPort?wsdl
URL_WS_REGISTRO=http://integ.serv.des.lanbide.lan/WSRegistroES/services/WSRegistroESPort?wsdl
#PRE
#URL_WS_REGISTRO=https://rlanbide.pru.lanbide.net/WSRegistroES/services/WSRegistroESPort?wsdl
#PRO
#URL_WS_REGISTRO=http://integ.serv.lanbide.lan/WSRegistroES/services/WSRegistroESPort?wsdl
ASUNTO=Comunicacion - Notificacion interesado expediente 
OBSERVACIONES=Sin observaciones
TIPO_DOC=119