##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE14/LISTA_OPERACIONES_DISPONIBLES=
1/MODULO_INTEGRACION/MELANBIDE14/LISTA_OPERACIONES_DISPONIBLES=

##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE14

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE14/DESCRIPCION_MODULO = MODULO PFSE
1/MODULO_INTEGRACION/MELANBIDE14/DESCRIPCION_MODULO = MODULO PFSE

##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE14/PFSE/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = OPERACIONES;FINANCIACION
1/MODULO_INTEGRACION/MELANBIDE14/PFSE/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = OPERACIONES;FINANCIACION

##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE14/PFSE/URL_PANTALLA_EXPEDIENTE/OPERACIONES = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE14&operacion=cargarPantallaPrincipal&tipo=0
1/MODULO_INTEGRACION/MELANBIDE14/PFSE/URL_PANTALLA_EXPEDIENTE/OPERACIONES = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE14&operacion=cargarPantallaPrincipal&tipo=0

0/MODULO_INTEGRACION/MELANBIDE14/PFSE/URL_PANTALLA_EXPEDIENTE/FINANCIACION = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE14&operacion=cargarPantallaFinanciacion&tipo=0
1/MODULO_INTEGRACION/MELANBIDE14/PFSE/URL_PANTALLA_EXPEDIENTE/FINANCIACION = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE14&operacion=cargarPantallaFinanciacion&tipo=0

##################### TABLAS DEL M\u00d3DULO #####################
MELANBIDE14_OPERACIONES=MELANBIDE14_OPERACIONES
M14_OPE_PRESENTADAS=MELANBIDE14_OPE_PRESENTADAS
TABLA_CODIGOS_DESPLEGABLES=E_DES
TABLA_VALORES_DESPLEGABLES=E_DES_VAL

### SECUENCIAS ID DE TABLAS CONTRATACION
SEQ_MELANBIDE14_OPERACIONES=SEQ_MELANBIDE14_OPERACIONES
SEQ_M14_OPE_PRESENTADAS=SEQ_M14_OPE_PRESENTADAS

##################### C\u00d3DIGOS DESPLEGABLES - PFSE #####################
COD_DES_PRIO=PRIO
COD_DES_LINACT1=LIN1
COD_DES_LINACT2=LIN2
COD_DES_LINACT3=LIN3
COD_DES_PRIORIDAD=PROP
COD_DES_OBJETIVO=OBJO
COD_DES_TIPOLOGIA=TIOB
COD_DES_ENTIDAD=ENPS

##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide14.i18n.text
FICHEROS_MENSAJES = MELANBIDE14_TEXT_1;MELANBIDE14_TEXT_4

# EL caracter es pipeline hay que escaparlo porque es un caracter especial para hacer condicion or en regex
BARRA_SEPARADORA_IDIOMA_DESPLEGABLES=\\Q|\\E