##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE83/LISTA_OPERACIONES_DISPONIBLES=
1/MODULO_INTEGRACION/MELANBIDE83/LISTA_OPERACIONES_DISPONIBLES=

##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE83

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE83/DESCRIPCION_MODULO = Lista de facturas de justificaci\u00f3n
1/MODULO_INTEGRACION/MELANBIDE83/DESCRIPCION_MODULO = Lista de facturas de justificaci\u00f3n

##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE83/ATASE/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = FACTURAS
1/MODULO_INTEGRACION/MELANBIDE83/ATASE/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = FACTURAS

##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE83/ATASE/URL_PANTALLA_EXPEDIENTE/FACTURAS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE83&operacion=cargarPantallaListaFacturas&tipo=0
1/MODULO_INTEGRACION/MELANBIDE83/ATASE/URL_PANTALLA_EXPEDIENTE/FACTURAS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE83&operacion=cargarPantallaListaFacturas&tipo=0

##################### NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE #####################
0/MODULO_INTEGRACION/MELANBIDE83/ATASE/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/FACTURAS = 
1/MODULO_INTEGRACION/MELANBIDE83/ATASE/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/FACTURAS = 

##################### NOMBRE DE LA OPERACION DEL MODULO QUE SE ENCARGA DE ACTUALIZAR LOS DATOS DE LA PANTALLA DE EXPEDIENTE #####################
0/MODULO_INTEGRACION/MELANBIDE83/ATASE/ACTUALIZAR_PANTALLA_EXPEDIENTE/FACTURAS = 
1/MODULO_INTEGRACION/MELANBIDE83/ATASE/ACTUALIZAR_PANTALLA_EXPEDIENTE/FACTURAS = 

##################### NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE #####################
0/MODULO_INTEGRACION/MELANBIDE83/ATASE/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/FACTURAS  =
1/MODULO_INTEGRACION/MELANBIDE83/ATASE/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/FACTURAS  =

##################### NOMBRES DE TABLAS #####################
MELANBIDE83_FACTURAS = MELANBIDE83_FACTURAS

##################### NOMBRES DE SECUENCIAS #####################
SEQ_MELANBIDE83_FACTURAS = SEQ_MELANBIDE83_FACTURAS

##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide83.i18n.text
FICHEROS_MENSAJES = MELANBIDE83_TEXT_1;MELANBIDE83_TEXT_4


###### C\u00f3digos de los campos desplegables ######
0/MODULO_INTEGRACION/MELANBIDE83/ATASE/DESPLEGABLES/COD_DESPL_ESTADO = ACEP
1/MODULO_INTEGRACION/MELANBIDE83/ATASE/DESPLEGABLES/COD_DESPL_ESTADO = ACEP
0/MODULO_INTEGRACION/MELANBIDE83/ATASE/DESPLEGABLES/COD_DESPL_CONCEPTO = CTAT
1/MODULO_INTEGRACION/MELANBIDE83/ATASE/DESPLEGABLES/COD_DESPL_CONCEPTO = CTAT
0/MODULO_INTEGRACION/MELANBIDE83/ATASE/DESPLEGABLES/COD_DESPL_SN = BOOL
1/MODULO_INTEGRACION/MELANBIDE83/ATASE/DESPLEGABLES/COD_DESPL_SN = BOOL


###### ERRORES PERSONALIZADOS DE LA OPERACI\u00d3N actualizarDatosSuplementarios 
0/MODULO_INTEGRACION/actualizarDatosSuplementarios/MENSAJE_ERROR/1= ERROR_GENERICO
1/MODULO_INTEGRACION/actualizarDatosSuplementarios/MENSAJE_ERROR/1= ERROR_GENERICO
0/MODULO_INTEGRACION/actualizarDatosSuplementarios/MENSAJE_ERROR/2= ERROR_CONEXIONBD
1/MODULO_INTEGRACION/actualizarDatosSuplementarios/MENSAJE_ERROR/2= ERROR_CONEXIONBD

ERROR_GENERICO_1 = Ha ocurrido un error gen\u00e9rico
ERROR_GENERICO_4 = Ha ocurrido un error gen\u00e9rico

ERROR_CONEXIONBD_1 = No se ha podido obtener una conexi\u00f3n a la BBDD
ERROR_CONEXIONBD_4 = No se ha podido obtener una conexi\u00f3n a la BBDD


#desplegables documentos
0/MODULO_INTEGRACION/MELANBIDE83/ATASE/PLANTILLA_NORMAL/ETIQUETAS=ATASE_ETIQUETA_EXPREINTEGRO
1/MODULO_INTEGRACION/MELANBIDE83/ATASE/PLANTILLA_NORMAL/ETIQUETAS=ATASE_ETIQUETA_EXPREINTEGRO


#etiqueta expediente reintegro
0/MODULO_INTEGRACION/MELANBIDE83/ATASE/PLANTILLA_NORMAL/ATASE_ETIQUETA_EXPREINTEGRO/TIPO_ETIQUETA=2
0/MODULO_INTEGRACION/MELANBIDE83/ATASE/PLANTILLA_NORMAL/ATASE_ETIQUETA_EXPREINTEGRO/NOMBRE_ETIQUETA=EXPREINTEGRO
0/MODULO_INTEGRACION/MELANBIDE83/ATASE/PLANTILLA_NORMAL/ATASE_ETIQUETA_EXPREINTEGRO/CODIGO_ETIQUETA=EXPREINTEGRO
#cuando crea un expediente relacionado se hacen dos inserts (para que los dos expedientes tengan al otro como relacionado... no hace falta buscar en num y numr)
#0/MODULO_INTEGRACION/MELANBIDE83/ATASE/PLANTILLA_NORMAL/ATASE_ETIQUETA_EXPREINTEGRO/SQL_ETIQUETA=select distinct(numreint) from (SELECT case when e_rex.rex_numr like '%REINT%' THEN rex_numr ELSE rex_num END as numReint,case when e_rex.rex_numr like '%REINT%' THEN rex_num ELSE rex_numr END as numNoReint FROM e_rex where rex_num LIKE '%REINT%' or rex_numr LIKE '%REINT%') 
0/MODULO_INTEGRACION/MELANBIDE83/ATASE/PLANTILLA_NORMAL/ATASE_ETIQUETA_EXPREINTEGRO/SQL_ETIQUETA=select rex_numr from e_rex
0/MODULO_INTEGRACION/MELANBIDE83/ATASE/PLANTILLA_NORMAL/ATASE_ETIQUETA_EXPREINTEGRO/SQL_NOMBRE_COLUMNA=rex_numr
0/MODULO_INTEGRACION/MELANBIDE83/ATASE/PLANTILLA_NORMAL/ATASE_ETIQUETA_EXPREINTEGRO/CLAUSULA_WHERE= WHERE rex_num=
0/MODULO_INTEGRACION/MELANBIDE83/ATASE/PLANTILLA_NORMAL/ATASE_ETIQUETA_EXPREINTEGRO/CLAUSULA_WHERE/CAMPO=numeroExpediente
0/MODULO_INTEGRACION/MELANBIDE83/ATASE/PLANTILLA_NORMAL/ATASE_ETIQUETA_EXPREINTEGRO/CLAUSULA_AND3=AND rex_numr LIKE '%REINT%'

1/MODULO_INTEGRACION/MELANBIDE83/ATASE/PLANTILLA_NORMAL/ATASE_ETIQUETA_EXPREINTEGRO/TIPO_ETIQUETA=2
1/MODULO_INTEGRACION/MELANBIDE83/ATASE/PLANTILLA_NORMAL/ATASE_ETIQUETA_EXPREINTEGRO/NOMBRE_ETIQUETA=EXPREINTEGRO
1/MODULO_INTEGRACION/MELANBIDE83/ATASE/PLANTILLA_NORMAL/ATASE_ETIQUETA_EXPREINTEGRO/CODIGO_ETIQUETA=EXPREINTEGRO
#cuando crea un expediente relacionado se hacen dos inserts (para que los dos expedientes tengan al otro como relacionado... no hace falta buscar en num y numr)
#1/MODULO_INTEGRACION/MELANBIDE83/ATASE/PLANTILLA_NORMAL/ATASE_ETIQUETA_EXPREINTEGRO/SQL_ETIQUETA=select distinct(numreint) from (SELECT case when e_rex.rex_numr like '%REINT%' THEN rex_numr ELSE rex_num END as numReint,case when e_rex.rex_numr like '%REINT%' THEN rex_num ELSE rex_numr END as numNoReint FROM e_rex where rex_num LIKE '%REINT%' or rex_numr LIKE '%REINT%') 
1/MODULO_INTEGRACION/MELANBIDE83/ATASE/PLANTILLA_NORMAL/ATASE_ETIQUETA_EXPREINTEGRO/SQL_ETIQUETA=select rex_numr from e_rex
1/MODULO_INTEGRACION/MELANBIDE83/ATASE/PLANTILLA_NORMAL/ATASE_ETIQUETA_EXPREINTEGRO/SQL_NOMBRE_COLUMNA=rex_numr
1/MODULO_INTEGRACION/MELANBIDE83/ATASE/PLANTILLA_NORMAL/ATASE_ETIQUETA_EXPREINTEGRO/CLAUSULA_WHERE= WHERE rex_num=
1/MODULO_INTEGRACION/MELANBIDE83/ATASE/PLANTILLA_NORMAL/ATASE_ETIQUETA_EXPREINTEGRO/CLAUSULA_WHERE/CAMPO=numeroExpediente
1/MODULO_INTEGRACION/MELANBIDE83/ATASE/PLANTILLA_NORMAL/ATASE_ETIQUETA_EXPREINTEGRO/CLAUSULA_AND3=AND rex_numr LIKE '%REINT%'

