# M\u00e9todos del m\u00f3dulo que se utilizan para configurar el m\u00f3dulo en la pesta\u00f1a "Conf. SW" de la definici\u00f3n del tr\u00e1mite
0/MODULO_INTEGRACION/MELANBIDE31/LISTA_OPERACIONES_DISPONIBLES=validarDatos
1/MODULO_INTEGRACION/MELANBIDE31/LISTA_OPERACIONES_DISPONIBLES=validarDatos
# NOMBRE DEL M\u00d3DULO QUE SE MUESTRA JUNTO CON EL NOMBRE DE LA OPERACI\u00d3N; A LA HORA DE SELECCIONAR UNA OPERACI\u00d3N QUE SE ASOCIAR\u00c1 A UN TR\u00c1MITE
# FORMATO: [COD_ORGANIZACION]/MODULO_INTEGRACION/[NOMBRE_MODULO]/NOMBRE_MODULO
0/MODULO_INTEGRACION/MELANBIDE31/DESCRIPCION_MODULO = M\u00d3DULO DE VALIDACIONES DE DATOS SUPLEMENTARIOS
1/MODULO_INTEGRACION/MELANBIDE31/DESCRIPCION_MODULO = M\u00d3DULO DE VALIDACIONES DE DATOS SUPLEMENTARIOS

##################################################################################################################################
######################                             PANTALLAS DEL EXPEDIENTE                              #########################
##################################################################################################################################

# FORMATO: [COD_ORGANIZACION]/MODULO_INTEGRACION/[NOMBRE_MODULO]/[COD_PROCEDIMIENTO]/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS
0/MODULO_INTEGRACION/MELANBIDE31/EH/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = VALIDACION_DATOS
1/MODULO_INTEGRACION/MELANBIDE31/EH/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = VALIDACION_DATOS

##################################################################################################################################
######################                             PANTALLA DE EXPEDIENTE CEPAP CP-APA                   #########################
##################################################################################################################################

# SE INDICA CUAL ES LA URL DE LA PANTALLA DE CONFIGURACI\u00d3N DEL M\u00d3DULO SI LA TIENE. ESTA PANTALLA SE CARGA COMO
# UNA PESTA\u00d1A EN LA DEFINICI\u00d3N DE LOS PROCEDIMIENTOS
# FORMATO: [COD_ORGANIZACION]/MODULO_INTEGRACION/[NOMBRE_MODULO]/[COD_PROCEDIMIENTO]/URL_PANTALLA_EXPEDIENTE

0/MODULO_INTEGRACION/MELANBIDE31/EH/URL_PANTALLA_EXPEDIENTE/VALIDACION_DATOS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE31&operacion=validarDatos&tipo=0
1/MODULO_INTEGRACION/MELANBIDE31/EH/URL_PANTALLA_EXPEDIENTE/VALIDACION_DATOS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE31&operacion=validarDatos&tipo=0

0/MODULO_INTEGRACION/MELANBIDE31/EH/PANTALLA_EXPEDIENTE/SALIDA = /jsp/extension/melanbide31/melanbide31.jsp
1/MODULO_INTEGRACION/MELANBIDE31/EH/PANTALLA_EXPEDIENTE/SALIDA = /jsp/extension/melanbide31/melanbide31.jsp

# NOMBRE DE LA OPERACION DEL MODULO QUE SE ENCARGA DE ACTUALIZAR LOS DATOS DE LA PANTALLA DE EXPEDIENTE
0/MODULO_INTEGRACION/MELANBIDE31/EH/ACTUALIZAR_PANTALLA_EXPEDIENTE/VALIDACION_DATOS = actualizarValidacionesDatosSuplementarios
1/MODULO_INTEGRACION/MELANBIDE31/EH/ACTUALIZAR_PANTALLA_EXPEDIENTE/VALIDACION_DATOS = actualizarValidacionesDatosSuplementarios

# NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE
0/MODULO_INTEGRACION/MELANBIDE31/EH/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/SELECCION_CERTIFICADO =
1/MODULO_INTEGRACION/MELANBIDE31/EH/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/SELECCION_CERTIFICADO =

# NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE DE UNA RELACI\u00d3N ENTRE EXPEDIENTES
0/MODULO_INTEGRACION/MELANBIDE31/EH/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/SELECCION_CERTIFICADO  =
1/MODULO_INTEGRACION/MELANBIDE31/EH/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/SELECCION_CERTIFICADO  =

##################### NOMBRES DE TABLAS #####################

#NUMERICOS
TABLA_TIPO_DATO_1=E_TNU
#TEXTOS
TABLA_TIPO_DATO_2=E_TXT
#FECHAS
TABLA_TIPO_DATO_3=E_TFE
#TEXTOS LARGOS
TABLA_TIPO_DATO_4=E_TTL
#FICHEROS
TABLA_TIPO_DATO_5=E_TFI
#DESPLEGABLES
TABLA_TIPO_DATO_6=E_TDE

#CAMPOS POR PROCEDIMIENTO
TABLA_CAMPOS_PROC=E_PCA


NOMBRE_MODULO = MELANBIDE31

UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide31.i18n.text
FICHEROS_MENSAJES = MELANBIDE31_TEXT_1;MELANBIDE31_TEXT_4