##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE62/LISTA_OPERACIONES_DISPONIBLES=actualizarDatosSuplementariosCUOTS
1/MODULO_INTEGRACION/MELANBIDE62/LISTA_OPERACIONES_DISPONIBLES=actualizarDatosSuplementariosCUOTS

##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE62

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE62/DESCRIPCION_MODULO = Abono de cuotas a la Seguridad Social
1/MODULO_INTEGRACION/MELANBIDE62/DESCRIPCION_MODULO = Abono de cuotas a la Seguridad Social

##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = FICHA_TECNICA
1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = FICHA_TECNICA

##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/URL_PANTALLA_EXPEDIENTE/FICHA_TECNICA = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE62&operacion=cargarDatosFichaTecnica&tipo=0
1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/URL_PANTALLA_EXPEDIENTE/FICHA_TECNICA = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE62&operacion=cargarDatosFichaTecnica&tipo=0

##################### NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE #####################
0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/FICHA_TECNICA =
1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/FICHA_TECNICA =

#0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PANTALLA_EXPEDIENTE/SALIDA = /jsp/extension/MELANBIDE62/MELANBIDE62.jsp
#1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PANTALLA_EXPEDIENTE/SALIDA = /jsp/extension/MELANBIDE62/MELANBIDE62.jsp

##################### NOMBRE DE LA OPERACION DEL MODULO QUE SE ENCARGA DE ACTUALIZAR LOS DATOS DE LA PANTALLA DE EXPEDIENTE #####################
0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/ACTUALIZAR_PANTALLA_EXPEDIENTE/FICHA_TECNICA = recargarDatosFichaTecnica
1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/ACTUALIZAR_PANTALLA_EXPEDIENTE/FICHA_TECNICA = recargarDatosFichaTecnica 

##################### NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE #####################
0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/FICHA_TECNICA  =
1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/FICHA_TECNICA  =

##################### NOMBRES DE TABLAS #####################


###### ERRORES PERSONALIZADOS DE LA OPERACIÓN actualizarDatosSuplementariosCUOTS 
0/MODULO_INTEGRACION/actualizarDatosSuplementariosCUOTS/MENSAJE_ERROR/1= ERROR_GENERICO
1/MODULO_INTEGRACION/actualizarDatosSuplementariosCUOTS/MENSAJE_ERROR/1= ERROR_GENERICO
0/MODULO_INTEGRACION/actualizarDatosSuplementariosCUOTS/MENSAJE_ERROR/2= ERROR_CONEXIONBD
1/MODULO_INTEGRACION/actualizarDatosSuplementariosCUOTS/MENSAJE_ERROR/2= ERROR_CONEXIONBD
0/MODULO_INTEGRACION/actualizarDatosSuplementariosCUOTS/MENSAJE_ERROR/3= ERROR_DATOSEXPEDIENTE_TERCERO
1/MODULO_INTEGRACION/actualizarDatosSuplementariosCUOTS/MENSAJE_ERROR/3= ERROR_DATOSEXPEDIENTE_TERCERO
0/MODULO_INTEGRACION/actualizarDatosSuplementariosCUOTS/MENSAJE_ERROR/4= ERROR_DATOSEXPEDIENTE_TERCERO_INCOMPLETO
1/MODULO_INTEGRACION/actualizarDatosSuplementariosCUOTS/MENSAJE_ERROR/4= ERROR_DATOSEXPEDIENTE_TERCERO_INCOMPLETO

ERROR_GENERICO_1 = Ha ocurrido un error genérico
ERROR_GENERICO_4 = Ha ocurrido un error genérico

ERROR_CONEXIONBD_1 = No se ha podido obtener una conexión a la BBDD
ERROR_CONEXIONBD_4 = No se ha podido obtener una conexión a la BBDD

ERROR_DATOSEXPEDIENTE_TERCERO_1 = Error al obtener datos del expediente y tercero
ERROR_DATOSEXPEDIENTE_TERCERO_4 = Error al obtener datos del expediente y tercero

ERROR_DATOSEXPEDIENTE_TERCERO_INCOMPLETO_1 = Datos del expediente y/o tercero incompletos
ERROR_DATOSEXPEDIENTE_TERCERO_INCOMPLETO_4 = Datos del expediente y/o tercero incompletos


##################### NOMBRES DE SECUENCIAS #####################
#######################CAMPOS CALCULADOS PARA PLANTILLAS###############################################
#El tipo_etiqueta nos indica el tipo de dato de la etiqueta (lo queremos para saber como formatear) (1->Entero, 2->String, 3-> Fecha, 4->Lista)

0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/ETIQUETAS=CUOTS_ETIQUETA_LISTAREQEUS;CUOTS_ETIQUETA_LISTAREQ;
1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/ETIQUETAS=CUOTS_ETIQUETA_LISTAREQEUS;CUOTS_ETIQUETA_LISTAREQ;



#etiqueta LISTAREQEUS, euskera
0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQEUS/TIPO_ETIQUETA=2
0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQEUS/NOMBRE_ETIQUETA=LISTAREQEUS
0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQEUS/CODIGO_ETIQUETA=EXPEDIENTE_LISTAREQEUS
0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQEUS/SQL_ETIQUETA=SELECT RTRIM (XMLAGG (XMLELEMENT (E,DESCRIPCION||'.'||TTLT_VALOR|| CHR(13))).EXTRACT ('//text()').GETCLOBVAL(),',') AS REQUISITOS FROM E_TDET INNER JOIN PLANTILLA_DESCLARGA ON CODIGO  = TDET_COD AND IDIOMA ='eu' LEFT JOIN E_TTLT ON SUBSTR(TTLT_COD,4,LENGTH(TTLT_COD))=TDET_COD AND TTLT_TRA=TDET_TRA AND TDET_PRO=TTLT_PRO
0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQEUS/SQL_NOMBRE_COLUMNA=REQUISITOS
0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQEUS/CLAUSULA_WHERE= WHERE tdet_num=
0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQEUS/CLAUSULA_WHERE/CAMPO=numeroExpediente
0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQEUS/CLAUSULA_AND3=AND PROCEDIMIENTO='CUOTS' AND TDET_TRA=17 AND TDET_VALOR='X'  AND tdet_ocu = (SELECT MAX(cro_ocu) FROM E_CRO WHERE cro_tra = 17 AND CRO_NUM=tdet_num)

1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQEUS/TIPO_ETIQUETA=2
1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQEUS/NOMBRE_ETIQUETA=LISTAREQEUS
1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQEUS/CODIGO_ETIQUETA=EXPEDIENTE_LISTAREQEUS
1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQEUS/SQL_ETIQUETA=SELECT RTRIM (XMLAGG (XMLELEMENT (E,DESCRIPCION||'.'||TTLT_VALOR|| CHR(13))).EXTRACT ('//text()').GETCLOBVAL(),',') AS REQUISITOS FROM E_TDET INNER JOIN PLANTILLA_DESCLARGA ON CODIGO  = TDET_COD AND IDIOMA ='eu' LEFT JOIN E_TTLT ON SUBSTR(TTLT_COD,4,LENGTH(TTLT_COD))=TDET_COD AND TTLT_TRA=TDET_TRA AND TDET_PRO=TTLT_PRO
1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQEUS/SQL_NOMBRE_COLUMNA=REQUISITOS
1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQEUS/CLAUSULA_WHERE= WHERE tdet_num=
1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQEUS/CLAUSULA_WHERE/CAMPO=numeroExpediente
1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQEUS/CLAUSULA_AND3=AND PROCEDIMIENTO='CUOTS' AND TDET_TRA=7 AND TDET_VALOR='X'  AND tdet_ocu = (SELECT MAX(cro_ocu) FROM E_CRO WHERE cro_tra = 17  AND CRO_NUM=tdet_num)


#etiqueta LISTAREQ, castellano
0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQ/TIPO_ETIQUETA=2
0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQ/NOMBRE_ETIQUETA=LISTAREQ
0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQ/CODIGO_ETIQUETA=EXPEDIENTE_LISTAREQ
0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQ/SQL_ETIQUETA=SELECT RTRIM (XMLAGG (XMLELEMENT (E,DESCRIPCION||'.'||TTLT_VALOR|| CHR(13))).EXTRACT ('//text()').GETCLOBVAL(),',') AS REQUISITOS FROM E_TDET INNER JOIN PLANTILLA_DESCLARGA ON CODIGO  = TDET_COD AND IDIOMA ='es' LEFT JOIN E_TTLT ON SUBSTR(TTLT_COD,4,LENGTH(TTLT_COD))=TDET_COD AND TTLT_TRA=TDET_TRA AND TDET_PRO=TTLT_PRO
0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQ/SQL_NOMBRE_COLUMNA=REQUISITOS
0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQ/CLAUSULA_WHERE=WHERE tdet_num=
0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQ/CLAUSULA_WHERE/CAMPO=numeroExpediente
0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQ/CLAUSULA_AND3=AND PROCEDIMIENTO='CUOTS' AND TDET_TRA=7 AND TDET_VALOR='X'  AND tdet_ocu = (SELECT MAX(cro_ocu) FROM E_CRO WHERE cro_tra = 17 AND CRO_NUM=tdet_num)

1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQ/TIPO_ETIQUETA=2
1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQ/NOMBRE_ETIQUETA=LISTAREQ
1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQ/CODIGO_ETIQUETA=EXPEDIENTE_LISTAREQ
1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQ/SQL_ETIQUETA=SELECT RTRIM (XMLAGG (XMLELEMENT (E,DESCRIPCION||'.'||TTLT_VALOR|| CHR(13))).EXTRACT ('//text()').GETCLOBVAL(),',') AS REQUISITOS FROM E_TDET INNER JOIN PLANTILLA_DESCLARGA ON CODIGO  = TDET_COD AND IDIOMA ='es' LEFT JOIN E_TTLT ON SUBSTR(TTLT_COD,4,LENGTH(TTLT_COD))=TDET_COD AND TTLT_TRA=TDET_TRA AND TDET_PRO=TTLT_PRO
1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQ/SQL_NOMBRE_COLUMNA=REQUISITOS
1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQ/CLAUSULA_WHERE=WHERE tdet_num=
1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQ/CLAUSULA_WHERE/CAMPO=numeroExpediente
1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/CUOTS_ETIQUETA_LISTAREQ/CLAUSULA_AND3=AND PROCEDIMIENTO='CUOTS' AND TDET_TRA=7 AND TDET_VALOR='X'   AND tdet_ocu = (SELECT MAX(cro_ocu) FROM E_CRO WHERE cro_tra = 17 AND CRO_NUM=tdet_num)





#etiqueta LISTAREQEUS, euskera
#0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQEUS/NOMBRE_ETIQUETA=LISTAREQEUS
#0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQEUS/CODIGO_ETIQUETA=EXPEDIENTE_LISTAREQEUS
#0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQEUS/SQL_ETIQUETA=SELECT PLANTILLA_DESCLARGA.DESCRIPCION as REQUISITOS FROM E_TDET INNER JOIN PLANTILLA_DESCLARGA ON  E_TDET.TDET_COD =PLANTILLA_DESCLARGA.CODIGO AND PLANTILLA_DESCLARGA.IDIOMA ='EU'
#0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQEUS/SQL_NOMBRE_COLUMNA=REQUISITOS
#0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQEUS/CLAUSULA_WHERE= WHERE tdet_num=
#0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQEUS/CLAUSULA_WHERE/CAMPO=numeroExpediente
#0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQEUS/CLAUSULA_AND3=AND TDET_TRA=17 AND TDET_VALOR='X'

#1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQEUS/TIPO_ETIQUETA=2
#1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQEUS/NOMBRE_ETIQUETA=LISTAREQEUS
#1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQEUS/CODIGO_ETIQUETA=EXPEDIENTE_LISTAREQEUS
#1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQEUS/SQL_ETIQUETA=SELECT PLANTILLA_DESCLARGA.DESCRIPCION as REQUISITOS FROM E_TDET INNER JOIN PLANTILLA_DESCLARGA ON  E_TDET.TDET_COD =PLANTILLA_DESCLARGA.CODIGO AND PLANTILLA_DESCLARGA.IDIOMA ='EU'
#1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQEUS/SQL_NOMBRE_COLUMNA=REQUISITOS
#1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQEUS/CLAUSULA_WHERE= WHERE tdet_num=
#1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQEUS/CLAUSULA_WHERE/CAMPO=numeroExpediente
#1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQEUS/CLAUSULA_AND3=AND TDET_TRA=17 AND TDET_VALOR='X'


#etiqueta LISTAREQ, castellano
#0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQ/TIPO_ETIQUETA=2
#0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQ/NOMBRE_ETIQUETA=LISTAREQ
#0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQ/CODIGO_ETIQUETA=EXPEDIENTE_LISTAREQ
#0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQ/SQL_ETIQUETA=SELECT PLANTILLA_DESCLARGA.DESCRIPCION as REQUISITOS FROM E_TDET INNER JOIN PLANTILLA_DESCLARGA ON  E_TDET.TDET_COD =PLANTILLA_DESCLARGA.CODIGO AND PLANTILLA_DESCLARGA.IDIOMA ='ES'
#0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQ/SQL_NOMBRE_COLUMNA=REQUISITOS
#0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQ/CLAUSULA_WHERE= WHERE tdet_num=
#0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQ/CLAUSULA_WHERE/CAMPO=numeroExpediente
#0/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQ/CLAUSULA_AND3=AND TDET_TRA=17 AND TDET_VALOR='X'

#1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQ/TIPO_ETIQUETA=2
#1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQ/NOMBRE_ETIQUETA=LISTAREQ
#1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQ/CODIGO_ETIQUETA=EXPEDIENTE_LISTAREQ
#1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQ/SQL_ETIQUETA=SELECT PLANTILLA_DESCLARGA.DESCRIPCION as REQUISITOS FROM E_TDET INNER JOIN PLANTILLA_DESCLARGA ON  E_TDET.TDET_COD =PLANTILLA_DESCLARGA.CODIGO AND PLANTILLA_DESCLARGA.IDIOMA ='ES'
#1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQ/SQL_NOMBRE_COLUMNA=REQUISITOS
#1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQ/CLAUSULA_WHERE= WHERE tdet_num=
#1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQ/CLAUSULA_WHERE/CAMPO=numeroExpediente
#1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQ/CLAUSULA_AND3=AND TDET_TRA=17 AND TDET_VALOR='X'
#1/MODULO_INTEGRACION/MELANBIDE62/CUOTS/PLANTILLA_NORMAL/DISCP_ETIQUETA_LISTAREQ/TIPO_ETIQUETA=2



##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide62.i18n.text
FICHEROS_MENSAJES = MELANBIDE62_TEXT_1;MELANBIDE62_TEXT_4

############ C\u00f3digo del tr\u00e1mite del que queremos obtener los datos ################
CODIGO_TRAMITE_PAGOS = 71