##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE49/LISTA_OPERACIONES_DISPONIBLES=insertarSecuencia
1/MODULO_INTEGRACION/MELANBIDE49/LISTA_OPERACIONES_DISPONIBLES=insertarSecuencia

0/MODULO_INTEGRACION/MELANBIDE49/DESCRIPCION_MODULO = NUMAGENCIA
1/MODULO_INTEGRACION/MELANBIDE49/DESCRIPCION_MODULO = NUMAGENCIA


# NOMBRE DEL M\u00d3DULO QUE SE MUESTRA JUNTO CON EL NOMBRE DE LA OPERACI\u00d3N; A LA HORA DE SELECCIONAR UNA OPERACI\u00d3N QUE SE ASOCIAR\u00c1 A UN TR\u00c1MITE
# FORMATO: [COD_ORGANIZACION]/MODULO_INTEGRACION/[NOMBRE_MODULO]/NOMBRE_MODULO
0/MODULO_INTEGRACION/MELANBIDE49/NOMBRE_MODULO = MELANBIDE49
1/MODULO_INTEGRACION/MELANBIDE49/NOMBRE_MODULO = MELANBIDE49


##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE49/AACC/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = 
1/MODULO_INTEGRACION/MELANBIDE49/AACC/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = 

##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE49/AACC/URL_PANTALLA_EXPEDIENTE/LISTADO_CONTRATOS = 
1/MODULO_INTEGRACION/MELANBIDE49/AACC/URL_PANTALLA_EXPEDIENTE/LISTADO_CONTRATOS = 

##################### NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE #####################
0/MODULO_INTEGRACION/MELANBIDE49/AACC/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/LISTADO_CONTRATOS =
1/MODULO_INTEGRACION/MELANBIDE49/AACC/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/LISTADO_CONTRATOS =

##################### NOMBRE DE LA OPERACION DEL MODULO QUE SE ENCARGA DE ACTUALIZAR LOS DATOS DE LA PANTALLA DE EXPEDIENTE #####################
0/MODULO_INTEGRACION/MELANBIDE49/AACC/ACTUALIZAR_PANTALLA_EXPEDIENTE/LISTADO_CONTRATOS = 
1/MODULO_INTEGRACION/MELANBIDE49/AACC/ACTUALIZAR_PANTALLA_EXPEDIENTE/LISTADO_CONTRATOS = 




##################### RELACI\u00d3N DE EXPEDIENTES #####################

0/MODULO_INTEGRACION/MELANBIDE49/AACC/PANTALLA_EXPEDIENTE_RELACION/NOMBRE_PANTALLAS=
1/MODULO_INTEGRACION/MELANBIDE49/AACC/PANTALLA_EXPEDIENTE_RELACION/NOMBRE_PANTALLAS=

0/MODULO_INTEGRACION/MELANBIDE49/AACC/URL_PANTALLA_EXPEDIENTE_RELACION/LISTADO_CONTRATOS = 
1/MODULO_INTEGRACION/MELANBIDE49/AACC/URL_PANTALLA_EXPEDIENTE_RELACION/LISTADO_CONTRATOS = 

##################### NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE DE UNA RELACI\u00d3N ENTRE EXPEDIENTES #####################
0/MODULO_INTEGRACION/MELANBIDE49/AACC/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/SELECCION_CERTIFICADO  =
1/MODULO_INTEGRACION/MELANBIDE49/AACC/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/SELECCION_CERTIFICADO  =




##################### NOMBRES DE TABLAS #####################
TABLA_TIPO_DATO_TEXTO=E_TXT

##################### NOMBRES DE SECUENCIAS #####################
AACC_NUMEROAGENCIA_SQ=AACC_NUMEROAGENCIA_SQ


##################### CAMPOS SUPLEMENTARIOS #####################

CAMPO_SUPL_NUMAGENCIA2=NUMAGENCIA2