##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE17/LISTA_OPERACIONES_DISPONIBLES=refrescarPantalla
1/MODULO_INTEGRACION/MELANBIDE17/LISTA_OPERACIONES_DISPONIBLES=refrescarPantalla

##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE17

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE17/DESCRIPCION_MODULO = M\u00f3dulo de Subvenciones de inserci\u00f3n social \u2013 Creaci\u00f3n Empresas de Inserci\u00f3n
1/MODULO_INTEGRACION/MELANBIDE17/DESCRIPCION_MODULO = M\u00f3dulo de Subvenciones de inserci\u00f3n social \u2013 Creaci\u00f3n Empresas de Inserci\u00f3n

##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE17/LAKCC/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = SUBVENCIONES
1/MODULO_INTEGRACION/MELANBIDE17/LAKCC/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = SUBVENCIONES


##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE17/LAKCC/URL_PANTALLA_EXPEDIENTE/SUBVENCIONES = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE17&operacion=cargarPantallaSubSolic&tipo=0
1/MODULO_INTEGRACION/MELANBIDE17/LAKCC/URL_PANTALLA_EXPEDIENTE/SUBVENCIONES = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE17&operacion=cargarPantallaSubSolic&tipo=0

##################### NOMBRES DE TABLAS #####################

#NUMERICOS
TABLA_TIPO_DATO_NUMERICO=E_TNU
TABLA_TIPO_DATO_DESPLEGABLE=E_TDE
TABLA_VALORES_DESPLEGABLES=E_DES_VAL
MELANBIDE17_SUBSOLIC=MELANBIDE17_SUBSOLIC
TABLA_CODIGOS_DESPLEGABLES=E_DES

##################### C\u00d3DIGOS DESPLEGABLES - ININ #####################
#DESPLEGABLE DTSV
COD_DES_DTSV=DTSV

##################### NOMBRES DE SECUENCIAS #####################
SEQ_MELANBIDE17_SUBSOLIC=SEQ_MELANBIDE17_SUBSOLIC


##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide17.i18n.text
FICHEROS_MENSAJES = MELANBIDE17_TEXT_1;MELANBIDE17_TEXT_4

#############################JOB#################################
#DESARROLLO
SERVIDOR = E22_DES_WL12_LANBIDE_FLEXIA111
COD_ORG=0
DOS_ENTORNOS=TRUE

#PRE
#SERVIDOR = paprergi1_flexia1
#COD_ORG=1
#DOS_ENTORNOS=FALSE

#PRO
#SERVIDOR = pargi1_flexia1
#COD_ORG=0
#DOS_ENTORNOS=TRUE

ENTORNO=LOCAL
UNIDAD_ORG=FOMEMT

# EL caracter es pipeline hay que escaparlo porque es un caracter especial para hacer condicion or en regex
BARRA_SEPARADORA_IDIOMA_DESPLEGABLES=\\Q|\\E