# M\u00e9todos del m\u00f3dulo que se utilizan para configurar el m\u00f3dulo en la pesta\u00f1a "Conf. SW" de la definici\u00f3n del tr\u00e1mite
0/MODULO_INTEGRACION/MELANBIDE37/LISTA_OPERACIONES_DISPONIBLES=generarClaveCP;generarClaveAPA
1/MODULO_INTEGRACION/MELANBIDE37/LISTA_OPERACIONES_DISPONIBLES=generarClaveCP;generarClaveAPA
# NOMBRE DEL M\u00d3DULO QUE SE MUESTRA JUNTO CON EL NOMBRE DE LA OPERACI\u00d3N; A LA HORA DE SELECCIONAR UNA OPERACI\u00d3N QUE SE ASOCIAR\u00c1 A UN TR\u00c1MITE
# FORMATO: [COD_ORGANIZACION]/MODULO_INTEGRACION/[NOMBRE_MODULO]/NOMBRE_MODULO
0/MODULO_INTEGRACION/MELANBIDE37/DESCRIPCION_MODULO = OPERACIONES CEPAP
1/MODULO_INTEGRACION/MELANBIDE37/DESCRIPCION_MODULO = OPERACIONES CEPAP

##################################################################################################################################
######################                             PANTALLAS DEL EXPEDIENTE                              #########################
##################################################################################################################################

# FORMATO: [COD_ORGANIZACION]/MODULO_INTEGRACION/[NOMBRE_MODULO]/[COD_PROCEDIMIENTO]/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS

##################################################################################################################################
######################                             PANTALLA DE EXPEDIENTE CEPAP CP-APA                   #########################
##################################################################################################################################

# SE INDICA CUAL ES LA URL DE LA PANTALLA DE CONFIGURACI\u00d3N DEL M\u00d3DULO SI LA TIENE. ESTA PANTALLA SE CARGA COMO
# UNA PESTA\u00d1A EN LA DEFINICI\u00d3N DE LOS PROCEDIMIENTOS
# FORMATO: [COD_ORGANIZACION]/MODULO_INTEGRACION/[NOMBRE_MODULO]/[COD_PROCEDIMIENTO]/URL_PANTALLA_EXPEDIENTE
#0/MODULO_INTEGRACION/MELANBIDE37/CEPAP/URL_PANTALLA_EXPEDIENTE/SELECCION_CERTIFICADO = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE37&operacion=inicioCEPAP&tipo=0
#1/MODULO_INTEGRACION/MELANBIDE37/CEPAP/URL_PANTALLA_EXPEDIENTE/SELECCION_CERTIFICADO = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE37&operacion=inicioCEPAP&tipo=0

0/MODULO_INTEGRACION/MELANBIDE37/CEPAP/PANTALLA_EXPEDIENTE/SALIDA = /jsp/extension/melanbide37/melanbide37.jsp
1/MODULO_INTEGRACION/MELANBIDE37/CEPAP/PANTALLA_EXPEDIENTE/SALIDA = /jsp/extension/melanbide37/melanbide37.jsp

# NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE
0/MODULO_INTEGRACION/MELANBIDE37/CEPAP/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/SELECCION_CERTIFICADO =
1/MODULO_INTEGRACION/MELANBIDE37/CEPAP/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/SELECCION_CERTIFICADO =

# NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE DE UNA RELACI\u00d3N ENTRE EXPEDIENTES
0/MODULO_INTEGRACION/MELANBIDE37/CEPAP/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/SELECCION_CERTIFICADO  =
1/MODULO_INTEGRACION/MELANBIDE37/CEPAP/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/SELECCION_CERTIFICADO  =

##################################################################################################################################
######################                      PANTALLA DE EXPEDIENTE CEPAP CP-APA PDF                      #########################
##################################################################################################################################

0/MODULO_INTEGRACION/MELANBIDE37/CEPAP/URL_PANTALLA_EXPEDIENTE/SELECCION_REPORT = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE37&operacion=inicioPDF&tipo=0
1/MODULO_INTEGRACION/MELANBIDE37/CEPAP/URL_PANTALLA_EXPEDIENTE/SELECCION_REPORT = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE37&operacion=inicioPDF&tipo=0

# NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE
0/MODULO_INTEGRACION/MELANBIDE37/CEPAP/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/SELECCION_REPORT =
1/MODULO_INTEGRACION/MELANBIDE37/CEPAP/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/SELECCION_REPORT =

# NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE DE UNA RELACI\u00d3N ENTRE EXPEDIENTES
0/MODULO_INTEGRACION/MELANBIDE37/CEPAP/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/SELECCION_REPORT  =
1/MODULO_INTEGRACION/MELANBIDE37/CEPAP/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/SELECCION_REPORT  =

# Nombre del campo suplementario de tipo texto donde se guardar\u00e1 la clave de registro CP 
# de la /jsp/extension/melanbide37/melanbide37.jsp
0/CAMPO_SUPLEMENTARIO_CLAVE_REGISTRAL_CP = CLAVEREGISTRALCP

# Nombre del campo suplementario de tipo texto donde se guardar\u00e1 la clave de registro APA 
# de la /jsp/extension/melanbide37/melanbide37.jsp
0/CAMPO_SUPLEMENTARIO_CLAVE_REGISTRAL_APA = CLAVEREGISTRALAPA


##################### NOMBRES DE TABLAS #####################
#En local se usa la tabla CER_CERTIFICADOS, en Lanbide el sin\u00f3nimo S_CER_CERTIFICADOS
TABLA_CER_CERTIFICADOS = CER_CERTIFICADOS
TABLA_MELANBIDE37_CERTIFICADO = MELANBIDE03_CERTIFICADO
TABLA_MELANBIDE37_CERT_CENTRO = MELANBIDE03_CERT_CENTRO
TABLA_CER_CENTROS = CER_CENTROS
TABLA_MELANBIDE37_S_CERTIFICADOS = S_CER_CERTIFICADOS

TABLA_EXPEDIENTES=E_EXP
TABLA_EXPTERCEROS=E_EXT
TABLA_TERCEROS=T_TER
TABLA_HIST_TERCEROS=T_HTE
TABLA_TIPO_DATO_NUMERICO=E_TNU
TABLA_TIPO_DATO_TEXTO=E_TXT
TABLA_CONTADORES = MELANBIDE37_CONT_CLAVES
TABLA_VALORES_DESPLEGABLE=E_DES_VAL

NOMBRE_MODULO = MELANBIDE37

UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide37.i18n.text
FICHEROS_MENSAJES = MELANBIDE37_TEXT_1;MELANBIDE37_TEXT_2

##################################################################################################################################
######################              CODIGOS DE ERROR PARA LA OPERACI\u00d3N DE GENERAR CLAVE CP              #########################
##################################################################################################################################

0/MODULO_INTEGRACION/generarClaveCP/MENSAJE_ERROR/1=ERROR_CERTIFICADO_NO_EXISTE
0/MODULO_INTEGRACION/generarClaveCP/MENSAJE_ERROR/2=ERROR_GENERAL

1/MODULO_INTEGRACION/generarClaveCP/MENSAJE_ERROR/1=ERROR_CERTIFICADO_NO_EXISTE
1/MODULO_INTEGRACION/generarClaveCP/MENSAJE_ERROR/2=ERROR_GENERAL

ERROR_CERTIFICADO_NO_EXISTE_1=Se ha producido un error al generar la clave registral CP. No existe el certificado.
ERROR_CERTIFICADO_NO_EXISTE_2=Se ha producido un error al generar la clave registral CP. No existe el certificado.
ERROR_GENERAL_1 = Se ha producido un error al generar la clave registral CP.
ERROR_GENERAL_2 = Se ha producido un error al generar la clave registral CP.


##################################################################################################################################
######################              CODIGOS DE ERROR PARA LA OPERACI\u00d3N DE GENERAR CLAVE APA              #########################
##################################################################################################################################

0/MODULO_INTEGRACION/generarClaveAPA/MENSAJE_ERROR/1=ERROR_CERTIFICADO_APA
0/MODULO_INTEGRACION/generarClaveAPA/MENSAJE_ERROR/2=ERROR_GENERAL_APA
0/MODULO_INTEGRACION/generarClaveAPA/MENSAJE_ERROR/3=ERROR_ACTUALIZARCLAVE_APA
0/MODULO_INTEGRACION/generarClaveAPA/MENSAJE_ERROR/4=ERROR_ACTUALIZARCONT_APA
0/MODULO_INTEGRACION/generarClaveAPA/MENSAJE_ERROR/5=ERROR_UNIDADES_APA

1/MODULO_INTEGRACION/generarClaveAPA/MENSAJE_ERROR/1=ERROR_CERTIFICADO_APA
1/MODULO_INTEGRACION/generarClaveAPA/MENSAJE_ERROR/2=ERROR_GENERAL_APA
1/MODULO_INTEGRACION/generarClaveAPA/MENSAJE_ERROR/3=ERROR_ACTUALIZARCLAVE_APA
1/MODULO_INTEGRACION/generarClaveAPA/MENSAJE_ERROR/4=ERROR_ACTUALIZARCONT_APA
1/MODULO_INTEGRACION/generarClaveAPA/MENSAJE_ERROR/5=ERROR_UNIDADES_APA

ERROR_CERTIFICADO_APA_1 = Se ha producido un error al generar la clave registral APA. No existe el certificado.
ERROR_CERTIFICADO_APA_2= Se ha producido un error al generar la clave registral APA. No existe el certificado.
ERROR_GENERAL_APA_1 = Se ha producido un error al generar la clave registral APA.
ERROR_GENERAL_APA_2 = Se ha producido un error al generar la clave registral APA.
ERROR_ACTUALIZARCLAVE_APA_1 = Se ha producido un error al grabar la clave registral APA. 
ERROR_ACTUALIZARCLAVE_APA_2 = Se ha producido un error al grabar la clave registral APA. 
ERROR_ACTUALIZARCLAVE_APA_1 = Se ha producido un error al actualizar el contador por a\u00f1o para APA. 
ERROR_ACTUALIZARCLAVE_APA_2 = Se ha producido un error al actualizar el contador por a\u00f1o para APA. 
ERROR_UNIDADES_APA_1 = Se ha producido un error al generar la clave registral APA. No existen unidades.
ERROR_UNIDADES_APA_2 = Se ha producido un error al generar la clave registral APA. No existen unidades.

## Propiedades para la consulta de listado de EMPNL 
    EMPNL_CODIGO_PROCEDIMIENTO=EMPNL
    EMPNL_CODIGO_INTERNO_TRAMITE_VALORACION=2
    EMPNL_NOMBRE_FICHERO_GENERADO=listadoExpExencionEMPNL
    EMPNL_EXTENSION_FICHERO_GENERADO=xls
    
    EMPNL_CAMPO_SUPL_FECHA_PRESENTACION=FECHAPRESENTACION
    EMPNL_CAMPO_SUPL_MOTIVO_EXENCION=MOTEXENC
    EMPNL_CAMPO_SUPL_ORIGEN_SOLICITUD=ORIGSOL
    EMPNL_CAMPO_SUPL_CENTRO=CENTRO
    EMPNL_CAMPO_SUPL_OFICINA_LANBIDE=OFICLANBIDE
    EMPNL_CAMPO_SUPL_VALORACION_EXENCION=VALEXENCION
    EMPNL_COD_DESP_MOTIV_EXENCION=MEXE
    EMPNL_COD_DESP_ORIGEN_SOLICITUD=ORSO
    EMPNL_COD_DESP_CENTRO=CENT
    EMPNL_COD_DESP_OFICINA_LANBIDE=OFLA
    EMPNL_COD_DESP_FAVORABLE_DESFAVO=FADE

## Propiedades Numero de Lineas por hoja
NUMERO_LINEAS_HOJA_EXCEL=22000
## Nombre de la vista Materializada para generaci\u00f3n del listado de todas las UC
NOMBRE_VISTA_MATERIALIZADA_TODAS_UC=CEPAP_LISTADOS_TODAS_UC

# Numero de linea por pagina - paginacion
NUMERO_LINEAS_PAGINA=15

#CEPAP - Entrega título
#DESA
TRAMITE_ENVIO_OFICINA=32
#PRE
#TRAMITE_ENVIO_OFICINA=9
#PRO
#TRAMITE_ENVIO_OFICINA=9