# N\u00famero de d\u00edas de aviso m\u00ednimo que han transcurrido desde que una anotaci\u00f3n ha sido registrada.
#       Por defecto toma el valor 2.
NUMERO_DIAS_REGISTRO_ANOTACIONES = 2 
# C\u00f3digo del asunto codificado que tienen que tener asociadas las anotaciones de registro a recuperar.
#       Si hay m\u00e1s de una deber\u00e1n estar separadas por comas.
COD_ASUNTO_CODIFICADO = 'QUEJA3'
TEXTO_ASUNTO_EMAIL = Notificacion de Anotacion pendiente - Oharraren abisua egiteke
TEXTO_NOTIFICACION_EMAIL = La entrada [NUMERO_ENTRADA], creada el [XX/XX/XXXX] y con asunto QUEJA, no tiene adjunto el documento de queja entregado por el interesado. Se debe adjuntar este documento escaneado en el plazo m\u00e1s breve posible
TEXTO_NOTIFICACION_EMAIL_EUSK = [NUMERO_ENTRADA] sarrerak, [XX/XX/XXXX] sortuta eta "kexa" gaia duenak, ez dauka interesatuak egindako kexa erantsia. Kexa-dokumentu hori ahalik eta azkarren eskaneatua bidaltzea eskertzen dizugu.
##### ---------------------
# Parametros de envio de mail
# ---------------------
#Propiedad que indica si el servicio de envio de mails est\u00e1 activo (si) o no (por defecto)
#mail.service.active=si
#mail.from=regexlan@lanbide.net
#mail.mime.host=
#mail.smtp.host=172.16.4.214
#mail.smtp.auth=false
#mail.smtp.port=
#mail.user=
#mail.password=
#mail.cc=
#mail.bcc=
#attribute.from=Notificacion de Anotacion pendiente - Oharraren abisua egiteke
# ---------------------
# Parametros de envio de mail al servidor (confirmacion de firma)
# ---------------------
#mail.send.confirm.to=cuenta_correo
