# Fichero properties plataforma Pki

#-----------------------------------------------------------------------
# DATOS CONTENEDOR
#-----------------------------------------------------------------------
#VALORES STORETYPE SOPORTADOS(para AFIRMA) : JKS(Java Keystore),p12 o pfx o pkcs12(almacenes PKCS#12),jceks(Java Cryptography Extension KeyStore)
# VALORES CASE INSENSITIVE
PLATPKI_STORETYPE=jks

#ALIAS : Esta propiedad puede ir vacia, se cogera el primer alias del almacen.
PLATPKI_ALIAS_CERTIFICADO=

# Propiedades comunes
PLATPKI_NIVEL_LOG=30
PLATPKI_RUTA_TRUSTSTORE=C:/certificados/trusted.jks
PLATPKI_PASS_TRUSTSTORE=trustedsle
PLATPKI_RUTA_KEYSTORE=C:/certificados/certificadoSelloRegistro.jks
PLATPKI_PASS_KEYSTORE=NDNUIO356SKI

# Acceso a SW DLL_CRYPTO
PLATPKI_URL_WEBSERVICES_DLLCRYPTO=https://10.232.100.196/dllcryptows/dllcryptoservice.asmx
# Propiedades @firma
PLATPKI_RUTA_TRUSTSTORE=P:/Entorno/conversorEni/branches/conversorEni/src/test/resources/pki/certificadosConfianza/jks.jks
PLATPKI_PASS_TRUSTSTORE=369258
PLATPKI_ELEVACION_FIRMA=S

#VALORES PARA PLATPKI_TIPO_ELEVACION (T, C, XL, A)
PLATPKI_TIPO_ELEVACION=T
PLATPKI_SELLAR_TIEMPO=S

# Propiedades @firma
PLATPKI_VERSI0N_SW=1.0
PLATPKI_URL_WEBSERVICE_AFIRMA=https://217.15.39.2/afirmaws/services/
PLATPKI_ID_APLIC = aytotomelloso.ae
PLATPKI_MODO_VAL_CERT=2
PLATPKI_OBTENER_INFO_CERT=true
PLATPKI_CUSTODIA_DOCS=false
PLATPKI_CLASE_RESPUESTA_SW=es.altia.sle.commons.pki.afirma.RespuestaSWMap

# Propiedades asf
PLATPKI_URL_WEBSERVICE_ASF=https://asf.demo.red.es/asf/services/
PLATPKI_INVOKING_APP=elic
PLATPKI_OPERACION_VERIFICACION_FIRMA=verificacionfirma
PLATPKI_OPERACION_FIRMA=firma
PLATPKI_ALIAS_SERVIDOR=firmaelic

#---------------------------------------------------------------------
# ACTION AUTENTICACION (SLE_Internet)
# este parametro se recoge en el servlet de via firma para enviar al action correspondiente
#----------------------------------------------------------------
PLATPKI_ACTION_VALIDACION = 

#----------------------------------------------------------------------------------
# Propiedades viaFirma
#-----------------------------------------------------------------------------------
PLATPKI_URL_VIAFIRMA=http://testservices.viafirma.com/viafirma
PLATPKI_URL_VIAFIRMA_WS=http://testservices.viafirma.com/viafirma
PLATPKI_API_KEY=anfpf
PLATPKI_API_PASS=aca
PLATPKI_CERTALIAS=xnoccio
PLATPKI_CERTPASS=12345
