
#DESARROLLO
SERVIDOR = E22_DES_WL12_LANBIDE_FLEXIA111

#PRE
#SERVIDOR = paprergi1_flexia1

#PRO
#SERVIDOR = pargi1_flexia1

TRAMITE_INCUMPLIMIENTO = 2
CODIGO_DOC_TRAMITE=4
COD_ORG=0
DOS_ENTORNOS=TRUE

#PROCEDIMIENTO DESARROLLO 0
#PROCEDIMIENTO_ID_DESARROLLO_CERO=LAN62_LEAUK
PROCEDIMIENTO_ID_DESARROLLO_CERO=LAN64_RECUR

