##############################################################
# 			SECURIZACI\u00d3N DE PETICI\u00d3N SOAP DEL CLIENTE        #
##############################################################

# MODO DE SECURIZACION
# Valores posibles: None, UsernameToken, BinarySecurityToken
security.mode=None

# Atributos exclusivos si security.mode es UsernameToken
# - usuario:  usuario dado de alta para la aplicaci\u00f3n que realiza la petici\u00f3n
# - password: password correspondiente
# Valores posibles de passwordType: PasswordDigest (la password se env\u00eda hasheada) o PasswordText (la password se env\u00eda en claro)
security.usertoken.user=usuario
security.usertoken.password=password
security.usertoken.passwordType=PasswordDigest

# Atributos exclusivos si security.mode es BinarySecurityToken
# - location: 	   Ruta al almac\u00e9n que contiene el certificado y la clave privada con la que firmar la petici\u00f3n WS
# - type: 	       Tipo de almac\u00e9n (PKCS12, JKS)
# - password:      password del Almac\u00e9n
# - cert alias:    Alias del certificado del usuario que est\u00e1 dentro del almac\u00e9n
# - cert password: Password de la clave privada correspondiente al certificado anterior
security.keystore.location=C:\\@FIRMA\\workspace\\@firmaMAPClienteWS\\colegiado.pfx
security.keystore.type=PKCS12
security.keystore.password=1111
security.keystore.cert.alias=pruebas
security.keystore.cert.password=1111
