## Propiedades generales de la busqueda de terceros.
Terceros.mostrarOrigen = si

# Configuracion para la busqueda de terceros. Con BusquedaAbierta 
# activada se busca todo lo que coincida en parte o totalmente con la cadena 
# introducida. Si esta desactivada solo se busca lo que coincida exactamente.
# Valores posibles: si,no
BusquedaAbierta = si

## Configuracion para la integraci\u00f3n con servicios web de Registro
#BusquedaTercero/0/serviciosDisp = UOR;LANBIDE;SGE
#BusquedaTercero/1/serviciosDisp = UOR;LANBIDE;SGE
BusquedaTercero/0/serviciosDisp = LANBIDE;SGE;UOR
BusquedaTercero/1/serviciosDisp = LANBIDE;SGE;UOR



BusquedaTercero/0/UOR/implClassName = es.altia.agora.webservice.tercero.servicios.uor.BusquedaTerceroUORImpl
BusquedaTercero/0/UOR/continuar = false


BusquedaTercero/1/UOR/implClassName = es.altia.agora.webservice.tercero.servicios.uor.BusquedaTerceroUORImpl
BusquedaTercero/1/UOR/continuar = true

BusquedaTercero/1/SGE/implClassName = es.altia.agora.webservice.tercero.servicios.sge.BusquedaTerceroSGEImpl
BusquedaTercero/1/SGE/continuar = true


BusquedaTercero/0/SGE/implClassName = es.altia.agora.webservice.tercero.servicios.sge.BusquedaTerceroSGEImpl
BusquedaTercero/0/SGE/continuar = false

BusquedaTercero/0/LANBIDE/implClassName = es.altia.agora.webservice.tercero.servicios.lanbide.BusquedaTerceroLanbideImpl
BusquedaTercero/0/LANBIDE/urlEndPoint = http://integ.serv.des.lanbide.lan/langaiWS/services/LangaiEECC?wsdl
BusquedaTercero/0/LANBIDE/continuar = true

BusquedaTercero/1/LANBIDE/implClassName = es.altia.agora.webservice.tercero.servicios.lanbide.BusquedaTerceroLanbideImpl
BusquedaTercero/1/LANBIDE/urlEndPoint = http://integ.serv.des.lanbide.lan/langaiWS/services/LangaiEECC?wsdl
BusquedaTercero/1/LANBIDE/continuar = true




###########################################################################################################
################################### SISTEMA DE ALTA DE TERCEROS EXTERNOS ##################################
###########################################################################################################

# Esta propiedad indica si se activa la pesta\u00F1a de campos de terceros externos en la pantalla
# de gesti\u00F3n de terceros. Valores (SI|NO)
CamposSuplementariosTercero/0/activar = SI
CamposSuplementariosTercero/1/activar = SI

# Servicios de alta de terceros externos disponibles
AltaTerceroExterno/0/serviciosDisp = 
AltaTerceroExterno/1/serviciosDisp = 

# Esta propiedad indica si el alta del tercero tiene que ser transaccional en los dos sistemas, es decir, si no se puede dar de alta
# el tercero en el/los sistema/s externo/s de tercero/s, entonces tampoco se podr\u00E1 dar de alta en Flexia (valor=true). Si (valor=false) entonces se puede
# dar de alta el tercero en Flexia aunque el alta en los sistemas externos de tercero hallan fallado.
# Valor: true o false
AltaTerceroExterno/0/transaccional = true
AltaTerceroExterno/1/transaccional = true

# URL DE ACCESO AL WSDL DEL SERVICIO DE  PERSONA F\u00CDSICA DE LANBIDE
AltaTerceroExterno/0/PersonaFisicaLanbide/urlEndPoint = http://integ.serv.des.lanbide.lan/langaiWS/services/LangaiEECC?wsdl
AltaTerceroExterno/1/PersonaFisicaLanbide/urlEndPoint = http://integ.serv.des.lanbide.lan/langaiWS/services/LangaiEECC?wsdl

# Clase que implementa el servicio externo de terceros de persona f\u00EDsica de Lanbide
AltaTerceroExterno/0/PersonaFisicaLanbide/implClassName = es.altia.flexia.terceros.integracion.externa.personafisica.SistemaTerceroExternoPersonaFisicaLanbide
AltaTerceroExterno/1/PersonaFisicaLanbide/implClassName = es.altia.flexia.terceros.integracion.externa.personafisica.SistemaTerceroExternoPersonaFisicaLanbide

# Esta propiedad indica las restricciones para el alta del tercero en Flexia para un determinado sistema de terceros externo. Los codigos de aplicacion
# se pueden consultar en ESQUEMA_GENERICO.A_APL.APL_COD
AltaTerceroExterno/0/PersonaFisicaLanbide/RestriccionesAltaTercero/CodigoAplicaciones = 1
AltaTerceroExterno/1/PersonaFisicaLanbide/RestriccionesAltaTercero/CodigoAplicaciones = 1


# ESTA PROPIEDAD S\u00D3LO LA USA EL PLUGIN PARA PERSONA F\u00CDSICA LANBIDE
# Esta propiedad indica cuales son los tipos de documentos del tercero que no son v\u00E1lidos a la hora de realizar el alta. Si la propiedad no tiene valor o no
# existe, se supone que todos los tips de documentos para el tercero son v\u00E1lidos.
# S\u00F3lo se permiten los tipos de documentos: NIF, NIE, W y U
AltaTerceroExterno/0/PersonaFisicaLanbide/tipos_documentos_flexia_validos_alta = 1;3;8;9
AltaTerceroExterno/1/PersonaFisicaLanbide/tipos_documentos_flexia_validos_alta = 1;3;8;9

# ESTA PROPIEDAD S\u00D3LO LA USA EL PLUGIN PARA PERSONA F\u00CDSICA LANBIDE
# Esta propiedad indica cuales son los tipos de documentos del tercero que no son v\u00E1lidos a la hora de modificar el tercero. Si la propiedad no tiene valor o no
# existe, se supone que todos los tips de documentos para el tercero son v\u00E1lidos.
AltaTerceroExterno/0/PersonaFisicaLanbide/tipos_documentos_flexia_validos_modificar =
AltaTerceroExterno/1/PersonaFisicaLanbide/tipos_documentos_flexia_validos_modificar =


###########################################################################################################
################################### SISTEMA DE ALTA DE TERCEROS EXTERNOS ##################################
###########################################################################################################




# PROPIEDAD QUE INDICA SI AL MODIFICAR EL DOMICILIO DE UN INTERESADO SE ACTUALIZA TAMBIEN EL DOM EN EL REGISTRO O EXPEDIENTE (SI) O SE MANTIENE EL ANTERIOR (NO)

0/ActualizarDomIntRegistroExpediente = no
1/ActualizarDomIntRegistroExpediente = no


0/limiteResultadosFlexia = 300
1/limiteResultadosFlexia = 300
