# URL DE ACCESO AL WSDL DEL SERVICIO WEB UTILIZADO PARA LLAMAR A LA OPERACI\u00D3N finalizarExpediente QUE COMPRUEBA SI SE PUEDE O NO FINALIZAR UN EXPEDIENTE
# FORMATO: [COD_ORGANIZACION]/URL_WEBSERVICE_VERIFICACION
# 0/URL_WEBSERVICE_VERIFICACION = http://integ.serv.des.lanbide.lan/rgi/services/RGIServices?wsdl
# 1/URL_WEBSERVICE_VERIFICACION = http://integ.serv.des.lanbide.lan/rgi/services/RGIServices?wsdl

0/URL_WEBSERVICE_VERIFICACION = http://integ.serv.des.lanbide.lan/rgiserv/services/RGIServicesRegexlan?WSDL
1/URL_WEBSERVICE_VERIFICACION = http://integ.serv.des.lanbide.lan/rgiserv/services/RGIServicesRegexlan?WSDL
