CREATE TABLE MELANBIDE45_MATERIALCONSU
  (
    ID        NUMBER(9,0),
    MAC_CANT  NUMBER(9,0),
    MAC_DET   VARCHAR2(1000 BYTE)
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "FLBPRU_DBS1" ;
  
  ALTER TABLE MELANBIDE45_MATERIALCONSU ADD (MAC_NUM VARCHAR2(30));
COMMENT ON COLUMN MELANBIDE41_MATERIALCONSU.ID
IS
  'CORRELATIVO DE REGISTROS DE LA TABLA';
  COMMENT ON COLUMN "FLBPRU"."MELANBIDE41_MATERIALCONSU"."ID_ESPSOL"
IS
  'ID TABLA ESPECIALIDADES - RELACIONA LOS REGISTROS DE LAS DOS TABLAS';
  COMMENT ON COLUMN "FLBPRU"."MELANBIDE41_MATERIALCONSU"."MAC_NUM"
IS
  'NUMERO DE EXPEDIENTE';
  COMMENT ON COLUMN "FLBPRU"."MELANBIDE41_MATERIALCONSU"."MAC_CANT"
IS
  'CANTIDAD';
  COMMENT ON COLUMN "FLBPRU"."MELANBIDE41_MATERIALCONSU"."MAC_DET"
IS
  'DENOMINACION Y ESPECIFICACIONES TECNICAS';
  COMMENT ON TABLE "FLBPRU"."MELANBIDE41_MATERIALCONSU"
IS
  'LISTA DE DOTACION DE EQUIPO Y MATERIALES  Y ELEMENTOS PRNCIPALES (EQUIPOS AMOSTIZABLES)';
  
CREATE SEQUENCE "SEQ_MELANBIDE45_MATERIALCONSU" MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE ;

ALTER TABLE MELANBIDE45_MODFORMATIVO ADD (
  MDF_COD         VARCHAR2(30),
  MDF_UC_COD      VARCHAR2(30),
  MDF_UC_DEN      VARCHAR2(500),
  MDF_DUR_MAX_TEL NUMBER(8,2),
  MDF_CP VARCHAR2(4000)
);

alter table MELANBIDE45_MODFORMATIVO rename column
MDF_CTP to MDF_CT;