-- MELANBIDE81_PROYECTOS
  CREATE TABLE MELANBIDE81_PROYECTOS(
	ID 			NUMBER(8,0) 		NOT NULL ENABLE,
	NUM_EXP 	VARCHAR2(20 BYTE) 	NOT NULL ENABLE,
	PRIORIDAD	NUMBER(6,0) 		NOT NULL ENABLE,
	DENOM 		VARCHAR2(200 BYTE) 	NOT NULL ENABLE,
	ENTIDAD 	VARCHAR2(100 BYTE) 	NOT NULL ENABLE,
	TIPO 		VARCHAR2(1 BYTE) 	NOT NULL ENABLE,
	NUMFASES 	NUMBER(2,0) 		NOT NULL ENABLE,

	CONSTRAINT M81_PROYECTOS_PK PRIMARY KEY (ID) USING INDEX  ENABLE
   );

COMMENT ON COLUMN MELANBIDE81_PROYECTOS.ID IS 		'Identificador Secuencial';
COMMENT ON COLUMN MELANBIDE81_PROYECTOS.NUM_EXP IS 	'Número de Expediente';
COMMENT ON COLUMN MELANBIDE81_PROYECTOS.PRIORIDAD IS	'Prioridad del Proyecto';
COMMENT ON COLUMN MELANBIDE81_PROYECTOS.DENOM IS 	'Denominación Del Proyecto';
COMMENT ON COLUMN MELANBIDE81_PROYECTOS.ENTIDAD IS 	'Entidad Actuante';
COMMENT ON COLUMN MELANBIDE81_PROYECTOS.TIPO IS 		'Tipo Proyecto: 1) Fomento Del Empleo, 2) Ayudas A La Contratacion';
COMMENT ON COLUMN MELANBIDE81_PROYECTOS.NUMFASES IS 	'Número De Fases';

--  SEQ_MELANBIDE81_PROYECTOS
CREATE SEQUENCE  SEQ_MELANBIDE81_PROYECTOS  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
  
-- MELANBIDE81_PUESTOS
  CREATE TABLE MELANBIDE81_PUESTOS(
	ID 				NUMBER(8,0) 		NOT NULL ENABLE,
	ID_PROYECTO 	NUMBER(8,0) 		NOT NULL ENABLE,
	ID_PRIORIDAD_PROYECTO	NUMBER(6,0) NOT NULL ENABLE,
	NUM_EXP 		VARCHAR2(20 BYTE) 	NOT NULL ENABLE,
	DENOMPUESTO 	VARCHAR2(50 BYTE) 	NOT NULL ENABLE,
	DURESTIM 		NUMBER(6,2) 		NOT NULL ENABLE,
	PORCJORN 		NUMBER(5,2) 		NOT NULL ENABLE,
	NUMCONTRATOS 	NUMBER(3) 			NOT NULL ENABLE,
	COSTEESTIMADO	NUMBER(9,2) 		NOT NULL ENABLE,
	SUBVENSOLIC 	NUMBER(9,2) 		NOT NULL ENABLE,

	CONSTRAINT M81_PUESTOS_PK PRIMARY KEY (ID) USING INDEX  ENABLE,
	CONSTRAINT M81_PUESTOS_FK FOREIGN KEY (ID_PROYECTO) REFERENCES MELANBIDE81_PROYECTOS(ID) ENABLE
   );

COMMENT ON COLUMN MELANBIDE81_PUESTOS.ID IS 			'Identificador Secuencial';
COMMENT ON COLUMN MELANBIDE81_PUESTOS.ID_PROYECTO IS 	'FK a MELANBIDE81_PROYECTOS(ID)';
COMMENT ON COLUMN MELANBIDE81_PUESTOS.ID_PRIORIDAD_PROYECTO IS	'Prioridad del Proyecto';
COMMENT ON COLUMN MELANBIDE81_PUESTOS.NUM_EXP IS 		'Número de Expediente';
COMMENT ON COLUMN MELANBIDE81_PUESTOS.DENOMPUESTO IS	'Denominación Del Proyecto';
COMMENT ON COLUMN MELANBIDE81_PUESTOS.DURESTIM IS 		'Duración Estimada (Meses)';
COMMENT ON COLUMN MELANBIDE81_PUESTOS.PORCJORN IS 		'Porcentaje Jornada';
COMMENT ON COLUMN MELANBIDE81_PUESTOS.NUMCONTRATOS IS 	'Número de Contratos';
COMMENT ON COLUMN MELANBIDE81_PUESTOS.COSTEESTIMADO IS 	'Coste Total Estimado';
COMMENT ON COLUMN MELANBIDE81_PUESTOS.SUBVENSOLIC IS 	'Subvención Solicitada';

--  SEQ_MELANBIDE81_PUESTOS
CREATE SEQUENCE  SEQ_MELANBIDE81_PUESTOS  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
  
-- MELANBIDE81_CONTRATACIONES
  CREATE TABLE MELANBIDE81_CONTRATACIONES(
	ID 				NUMBER(8,0) 		NOT NULL ENABLE,
	ID_PROYECTO 	NUMBER(8,0) 		NOT NULL ENABLE,
	ID_PRIORIDAD_PROYECTO	NUMBER(6,0) NOT NULL ENABLE,
	NUM_EXP 		VARCHAR2(20 BYTE)	NOT NULL ENABLE,
	TIPOPERSDESEM 	VARCHAR2(1 BYTE) 	NOT NULL ENABLE,
	DURACESTIMADAA	NUMBER(6,2) 		NOT NULL ENABLE,
	SEXO 			VARCHAR2(1 BYTE) 	NOT NULL ENABLE,
	PORCJORN		NUMBER(5,2) 		NOT NULL ENABLE,
	NUMCONTRPREV 	NUMBER(3,0) 		NOT NULL ENABLE,
	SUBVENSOLIC 	NUMBER(9,2) 		NOT NULL ENABLE,

	CONSTRAINT M81_CONTRATACIONES_PK PRIMARY KEY (ID) USING INDEX  ENABLE,
	CONSTRAINT M81_CONTRATACIONES_FK FOREIGN KEY (ID_PROYECTO) REFERENCES MELANBIDE81_PROYECTOS(ID) ENABLE

   );

COMMENT ON COLUMN MELANBIDE81_CONTRATACIONES.ID IS 			'Identificador Secuencial';
COMMENT ON COLUMN MELANBIDE81_CONTRATACIONES.ID_PROYECTO IS 	'FK a MELANBIDE81_PROYECTOS(ID)';
COMMENT ON COLUMN MELANBIDE81_CONTRATACIONES.ID_PRIORIDAD_PROYECTO IS	'Prioridad del Proyecto';
COMMENT ON COLUMN MELANBIDE81_CONTRATACIONES.NUM_EXP IS 		'Número de Expediente';
COMMENT ON COLUMN MELANBIDE81_CONTRATACIONES.TIPOPERSDESEM IS 'Tipo de Persona Desempleada: 1)Desempleadas En General 2)Colectivos Especiales ';
COMMENT ON COLUMN MELANBIDE81_CONTRATACIONES.DURACESTIMADAA IS 'Duración Estimada (Meses)';
COMMENT ON COLUMN MELANBIDE81_CONTRATACIONES.SEXO IS 			'Sexo';
COMMENT ON COLUMN MELANBIDE81_CONTRATACIONES.PORCJORN IS 		'Porcentaje Jornada';
COMMENT ON COLUMN MELANBIDE81_CONTRATACIONES.NUMCONTRPREV IS 	'Número de Contratos Previstos';
COMMENT ON COLUMN MELANBIDE81_CONTRATACIONES.SUBVENSOLIC IS 	'Subvención Solicitada';

--  SEQ_MELANBIDE81_CONTRATACIONES
CREATE SEQUENCE  SEQ_MELANBIDE81_CONTRATACIONES  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;


-- TIPO PROYECTO LPEEL
Insert into E_DES (DES_COD,DES_NOM) values ('TPLP','TIPO PROYECTO LPEEL');

Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM,DES_VAL_ESTADO) values ('TPLP','1','FOMENTO DEL EMPLEO|ENPLEGUA SUSTATZEA','A');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM,DES_VAL_ESTADO) values ('TPLP','2','AYUDAS A LA CONTRATACIÓN|KONTRATAZIORAKO LAGUNTZAK','A');

-- TIPO PERSONA DESEMPLEADA LPEEL: 
Insert into E_DES (DES_COD,DES_NOM) values ('TPDL','TIPO PERSONA DESEMPLEADA LPEEL');

Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM,DES_VAL_ESTADO) values ('TPDL','G','PERSONAS DESEMPLEADAS EN GENERAL|LANGABEAK ORO HAR','A');
Insert into E_DES_VAL (DES_COD,DES_VAL_COD,DES_NOM,DES_VAL_ESTADO) values ('TPDL','C','PERSONAS DESEMPLEADAS COLECTIVOS ESPECIALES|PERTSONA LANGABEAK, KOLEKTIBOA BEREZIAK','A');

  