-- Generales 
INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( 'PLUG_DOK_ERROR_GENERICO', 'Se ha presentado una Exception general en el Plugin de Dokusi', 'Se ha presentado una Exception general en el Plugin de Dokusi', '2', '2', NULL, NULL, 'Comprobar logs de aplicacion y servidor, comunicar a Soporte', 'APP_DOKUSI' ); 
INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( 'PLUG_DOK_ERR_MET_NOSUPPOR', 'Método no Soportado por el plugin DOKUSI. Metodo no implementado.', 'Método no Soportado por el plugin DOKUSI. Metodo no implementado.', '2', '2', NULL, NULL, 'Comunicar a soporte y equipo de desarrollo Flexia', 'APP_DOKUSI' ); 
INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( 'FLEX_PLUG_DOK_CODPROCED', 'No se ha podido recuperar el codigo del procedimiento para instanciar los servicios de Dokusi', 'No se ha podido recuperar el codigo del procedimiento para instanciar los servicios de Dokusi', '2', '2', NULL, NULL, 'Comprobar en el fichero de configuracion MELANBIDE_DOKUSI.properties que esta dado de alta el codigo del procedimiento para el que se intenta realizar la operacion en DOKUSI.', 'APP_DOKUSI' ); 
-- APP Flexia
INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( 'FLEX_PLUG_DOK_SETDOC_TRAM', 'Error al dar de alta un documento de tramitación en Dokusi. LLamada Metodo SetDocumento()', 'Error al dar de alta un documento de tramitación en Dokusi. LLamada Metodo SetDocumento()', '2', '2', NULL, NULL, 'Comprobar ID de procedimiento - Conexiones a adaptadores - Parámetros de Documento', 'APP_DOKUSI' ); 
INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( 'FLEX_PLUG_DOK_GETDOC_TRAM', 'Error al recuperar un documento de tramitación en Dokusi. LLamada Metodo getDocumento()', 'Error al recuperar un documento de tramitación en Dokusi. LLamada Metodo getDocumento()', '2', '2', NULL, NULL, 'Comprobar ID de procedimiento - Conexiones a adaptadores - Parámetros de Documento', 'APP_DOKUSI' ); 
INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( 'FLEX_PLUG_DOK_DELDOC_TRAM', 'Error al eliminar un documento de tramitación en Dokusi. LLamada Metodo eliminarDocumento()', 'Error al eliminar un documento de tramitación en Dokusi. LLamada Metodo eliminarDocumento()', '2', '2', NULL, NULL, 'Comprobar ID de procedimiento - Conexiones a adaptadores - Parámetros de Documento', 'APP_DOKUSI' ); 
INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( 'FLEX_PLU_DOK_SETD_TRA_REL', 'Error al dar de alta un documento de tramitación en Dokusi, para una relación de expedientes.', 'Error al dar de alta un documento de tramitación en Dokusi, para una relación de expedientes. LLamada Metodo SetDocumento()', '2', '2', NULL, NULL, 'Comprobar ID de procedimiento - Conexiones a adaptadores - Parametros de Documento', 'APP_DOKUSI' ); 
INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( 'FLEX_PLU_DOK_GETD_TRA_REL', 'Error al recuperar un documento de tramitación en Dokusi, para una relación de expedientes.', 'Error al recuperar un documento de tramitación en Dokusi, para una relación de expedientes. LLamada Metodo getDocumento()', '2', '2', NULL, NULL, 'Comprobar ID de procedimiento - Conexiones a adaptadores - Parametros de Documento', 'APP_DOKUSI' ); 
INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( 'FLEX_PLU_DOK_DELD_TRA_REL', 'Error al eliminar un documento de tramitación en Dokusi, para una relación de expedientes.', 'Error al eliminar un documento de tramitación en Dokusi, para una relación de expedientes. LLamada Metodo eliminarDocumentO()', '2', '2', NULL, NULL, 'Comprobar ID de procedimiento - Conexiones a adaptadores - Parametros de Documento', 'APP_DOKUSI' ); 
INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( 'FLEX_PLUG_DOK_SETDOC_EXT', 'Error al consultar documento externo de DOKUSI. LLamada Metodo getDocumentoExterno()','Error al consultar documento externo de DOKUSI. LLamada Metodo getDocumentoExterno()', '2', '2', NULL, NULL, 'Comprobar ID de procedimiento - Conexiones a adaptadores - Parametros de Documento', 'APP_DOKUSI' ); 
INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( 'FLEX_PLUG_DOK_GETDOC_EXT', 'Error al dar de alta un documento externo de DOKUSI. LLamada Metodo setDocumentoExterno()','Error al dar de alta un documento externo de DOKUSI. LLamada Metodo setDocumentoExterno()', '2', '2', NULL, NULL, 'Comprobar ID de procedimiento - Conexiones a adaptadores - Parametros de Documento', 'APP_DOKUSI' ); 
INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( 'FLEX_PLUG_DOK_DELDOC_EXT', 'Error al eliminar un documento externo de DOKUSI. LLamada Metodo eliminarDocumentoExterno()','Error al eliminar un documento externo de DOKUSI. LLamada Metodo eliminarDocumentoExterno()', '2', '2', NULL, NULL, 'Comprobar ID de procedimiento - Conexiones a adaptadores - Parametros de Documento', 'APP_DOKUSI' ); 
INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( 'FLEX_PLUG_DOK_SETDOC_PRE', 'Error al consultar documento presentado de DOKUSI. LLamada Metodo getDocumentoPresentado()','Error al consultar documento presentado de DOKUSI. LLamada Metodo getDocumentoPresentado()', '2', '2', NULL, NULL, 'Comprobar ID de procedimiento - Conexiones a adaptadores - Parametros de Documento', 'APP_DOKUSI' ); 
INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( 'FLEX_PLUG_DOK_GETDOC_PRE', 'Error al dar de alta un documento presentado de DOKUSI. LLamada Metodo setDocumentoPresentado()','Error al dar de alta un documento presentado de DOKUSI. LLamada Metodo setDocumentoPresentado()', '2', '2', NULL, NULL, 'Comprobar ID de procedimiento - Conexiones a adaptadores - Parametros de Documento', 'APP_DOKUSI' ); 
INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( 'FLEX_PLUG_DOK_DELDOC_PRE', 'Error al eliminar un documento presetnado de DOKUSI. LLamada Metodo eliminarDocumentoPresentado()','Error al eliminar un documento presetnado de DOKUSI. LLamada Metodo eliminarDocumentoPresentado()', '2', '2', NULL, NULL, 'Comprobar ID de procedimiento - Conexiones a adaptadores - Parametros de Documento', 'APP_DOKUSI' ); 
INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( 'FLEX_PLUG_DOK_SETDOC_CSE', 'Error al dar de alta un documento en un campo suplementario a nivel de Expediente en DOKUSI.','Error al dar de alta un documento en un campo suplementario a nivel de Expediente en DOKUSI. LLamada Metodo setDocumentoDatoSuplementarioExpediente()', '2', '2', NULL, NULL, 'Comprobar ID de procedimiento - Conexiones a adaptadores - Parametros de Documento', 'APP_DOKUSI' ); 
INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( 'FLEX_PLUG_DOK_GETDOC_CSE', 'Error al consultar un documento en un campo suplementario a nivel de Expediente en DOKUSI.','Error al consultar un documento en un campo suplementario a nivel de Expediente en DOKUSI. LLamada Metodo getDocumentoDatosSuplementarios()', '2', '2', NULL, NULL, 'Comprobar ID de procedimiento - Conexiones a adaptadores - Parametros de Documento', 'APP_DOKUSI' ); 
INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( 'FLEX_PLUG_DOK_DELDOC_CSE', 'Error al eliminar un documento en un campo suplementario a nivel de Expediente en DOKUSI.','Error al eliminar un documento en un campo suplementario a nivel de Expediente en DOKUSI. LLamada Metodo eliminarDocumentoDatosSuplementarios()', '2', '2', NULL, NULL, 'Comprobar ID de procedimiento - Conexiones a adaptadores - Parametros de Documento', 'APP_DOKUSI' ); 
INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( 'FLEX_PLUG_DOK_SETDOC_CST', 'Error al dar de alta un documento en un campo suplementario a nivel de Tramite en DOKUSI','Error al dar de alta un documento en un campo suplementario a nivel de Tramite en DOKUSI. LLamada Metodo setDocumentoDatoSuplementarioTramite()', '2', '2', NULL, NULL, 'Comprobar ID de procedimiento - Conexiones a adaptadores - Parametros de Documento', 'APP_DOKUSI' ); 
INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( 'FLEX_PLUG_DOK_GETDOC_CST', 'Error al consultar un documento en un campo suplementario a nivel de Tramite en DOKUSI.','Error al consultar un documento en un campo suplementario a nivel de Tramite en DOKUSI. LLamada Metodo getDocumentoDatoSuplementarioTramite()', '2', '2', NULL, NULL, 'Comprobar ID de procedimiento - Conexiones a adaptadores - Parametros de Documento', 'APP_DOKUSI' ); 
INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( 'FLEX_PLUG_DOK_DELDOC_CST', 'Error al eliminar un documento en un campo suplementario a nivel de Tramite en DOKUSI.','Error al eliminar un documento en un campo suplementario a nivel de Tramite en DOKUSI. LLamada Metodo eliminarDocumentoDatoSuplementarioTramite()', '2', '2', NULL, NULL, 'Comprobar ID de procedimiento - Conexiones a adaptadores - Parametros de Documento', 'APP_DOKUSI' ); 
INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( 'FLEX_PLUG_DOK_GETDOC_REG', 'Error al dar de alta un documento de Registro en DOKUSI. LLamada Metodo setDocumentoRegistro()','Error al dar de alta un documento de Registro en DOKUSI. LLamada Metodo setDocumentoRegistro()', '2', '2', NULL, NULL, 'Comprobar ID de procedimiento - Conexiones a adaptadores - Parametros de Documento', 'APP_DOKUSI' ); 
INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( 'FLEX_PLUG_DOK_SETDOC_REG', 'Error al consultar un documento de Registro en DOKUSI. LLamada Metodo getDocumentoRegistro()','Error al consultar un documento de Registro en DOKUSI. LLamada Metodo getDocumentoRegistro()', '2', '2', NULL, NULL, 'Comprobar ID de procedimiento - Conexiones a adaptadores - Parametros de Documento', 'APP_DOKUSI' ); 
INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( 'FLEX_PLUG_DOK_DELDOC_REG', 'Error al eliminar un documento de Registro en DOKUSI. LLamada Metodo eliminarDocumentoRegistro()','Error al eliminar un documento de Registro en DOKUSI. LLamada Metodo eliminarDocumentoRegistro()', '2', '2', NULL, NULL, 'Comprobar ID de procedimiento - Conexiones a adaptadores - Parametros de Documento', 'APP_DOKUSI' ); 
INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( 'FLEX_PLUG_DOK_SETDOC_EXTN', 'Error al dar de alta un documento externo de notificacion  en DOKUSI.','Error al dar de alta un documento externo de notificacion  en DOKUSI. LLamada Metodo setDocumentoExternoNotificacion()', '2', '2', NULL, NULL, 'Comprobar ID de procedimiento - Conexiones a adaptadores - Parametros de Documento', 'APP_DOKUSI' ); 
INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( 'FLEX_PLUG_DOK_GETDOC_EXTN', 'Error al consultar un documento externo de notificacion en DOKUSI.','Error al consultar un documento externo de notificacion en DOKUSI. LLamada Metodo getDocumentoExternoNotificacion()', '2', '2', NULL, NULL, 'Comprobar ID de procedimiento - Conexiones a adaptadores - Parametros de Documento', 'APP_DOKUSI' ); 
INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( 'FLEX_PLUG_DOK_DELDOC_EXTN', 'Error al eliminar un documento externo de Notificacion en DOKUSI.','Error al eliminar un documento externo de Notificacion en DOKUSI. LLamada Metodo eliminarDocumentoExternoNotificacion()', '2', '2', NULL, NULL, 'Comprobar ID de procedimiento - Conexiones a adaptadores - Parametros de Documento', 'APP_DOKUSI' ); 
INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( 'FLEX_PLUG_DOK_SETFIRMADOC', 'Error al anadir firma a un documento en Dokusi. LLamada Metodo anadirFirmaDocumento()','Error al anadir firma a un documento en Dokusi. LLamada Metodo anadirFirmaDocumento()', '2', '2', NULL, NULL, 'Comprobar ID de procedimiento - Conexiones a adaptadores - Parametros de Documento', 'APP_DOKUSI' ); 
INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( 'FLEX_PLUG_DOK_DELD_ALLCST', 'Error Recuperando los codigos de los campos Suplementarios a Borrar Todo Documentos Datos Supleme.','Error Recuperando los codigos de los campos Suplementarios a Borrar - Al eliminarTodosDocumentosDatosSuplementariosTramite - DOKUSI', '2', '2', NULL, NULL, 'Comprobar ID de procedimiento - Conexiones a adaptadores - Parametros de Documento', 'APP_DOKUSI' ); 

-- Webservice Tramitacion
--INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( 'WSTR_PLUG_DOK_SETDOC_TRAM', 'Error al dar de alta un documento de tramitación en Dokusi, Servicio invocado desde WSRegistro', 'Error al dar de alta un documento de tramitación en Dokusi, Servicio invocado desde Web Service de Registro', '2', '2', NULL, NULL, 'Comprobar ID de procedimiento - Conexiones a adaptadores - Parametros de Documento', 'WSREGISTRO_DOKUSI' ); 
--WebService Regsitro

COMMIT;

---INSERT INTO IDEN_ERR (IDEN_ERR_ID, IDEN_ERR_DESC_C, IDEN_ERR_DESC, IDEN_ERR_TIPO, IDEN_ERR_CRIT, IDEN_ERR_MEN_AVISO, IDEN_ERR_MAILS, IDEN_ERR_ACC, IDEN_ERR_MOD ) VALUES ( '', '','', '2', '2', NULL, NULL, 'Comprobar ID de procedimiento - Conexiones a adaptadores - Parametros de Documento', 'APP_DOKUSI' ); 
