 --TABLA ORI_AMBITOS
 CREATE TABLE "ORI_AMBITOS" 
   (	"ORI_AMB_COD" NUMBER(8,0) NOT NULL ENABLE, 
	"ORI_AMB_TERHIS" NUMBER(2,0), 
	"ORI_AMB_AMBITO" VARCHAR2(50 BYTE), 
	"ORI_AMB_HORASTOT" NUMBER(8,0), 
	"ORI_AMB_ANOCONV" NUMBER(4,0), 
	"ORI_AMB_CE" NUMBER(2,0), 
	"ORI_AMB_CE_ESPECIAL" NUMBER(2,0), 
	 CONSTRAINT "XPK_ORI_AMBITOS" PRIMARY KEY ("ORI_AMB_COD") ENABLE
   );
 

   COMMENT ON COLUMN "ORI_AMBITOS"."ORI_AMB_COD" IS 'IDENTIFICADOR DEL CODIGO DEL AMBITO';
 
   COMMENT ON COLUMN "ORI_AMBITOS"."ORI_AMB_TERHIS" IS 'IDENTIFICADOR DEL CODIGO DE TERRITORIO HISOTIRCO: 1 ALAVA, 48 BIZKAYA, 20 GIPUZKOA';
 
   COMMENT ON COLUMN "ORI_AMBITOS"."ORI_AMB_AMBITO" IS 'DESCRIPCION DEL AMBITO';
 
   COMMENT ON COLUMN "ORI_AMBITOS"."ORI_AMB_HORASTOT" IS 'HORAS DE ORIENTACION DEL AMBITO';
 
   COMMENT ON COLUMN "ORI_AMBITOS"."ORI_AMB_ANOCONV" IS 'AÑO DE LA CONVOCATORIA';
 
   COMMENT ON COLUMN "ORI_AMBITOS"."ORI_AMB_CE" IS 'NUMERO DE CENTROS ASOCIADOS AL AMBITO';
 
   COMMENT ON COLUMN "ORI_AMBITOS"."ORI_AMB_CE_ESPECIAL" IS 'NUMERO DE CENTROS ESPECIALES ASOCIADOS AL AMBITO';
 
   COMMENT ON TABLE "ORI_AMBITOS"  IS 'AMBITOS DEL PROCEDIMIENTOS DE ORIENTACION';
   
   --TABLA ORI_ENTIDAD
   CREATE TABLE "ORI_ENTIDAD" 
   (	"ORI_ENT_COD" NUMBER(38,0) NOT NULL ENABLE, 
	"EXT_MUN" NUMBER(3,0), 
	"EXT_EJE" NUMBER(4,0), 
	"EXT_NUM" VARCHAR2(30 BYTE), 
	"EXT_TER" NUMBER(12,0), 
	"EXT_NVR" NUMBER(3,0), 
	"ORI_ENT_ADMLOCAL" VARCHAR2(1 BYTE), 
	"ORI_ENT_SUPRAMUN" VARCHAR2(1 BYTE), 
	"ORI_EXP_COD" NUMBER(8,0), 
	"ORI_ENT_OTROS" VARCHAR2(100 BYTE), 
	"ORI_ENT_ACOLOCACION" VARCHAR2(1 BYTE), 
	"ORI_ENT_NUMTRAB" NUMBER(5,0), 
	"ORI_ENT_NUMTRAB_DISC" NUMBER(5,0), 
	"ORI_ENT_TRAYECTORIA" NUMBER(2,0), 
	"ORI_ENT_TRAYECTORIA_VAL" NUMBER(2,0), 
	"ORI_ENT_NOM" VARCHAR2(80 BYTE), 
	 CONSTRAINT "XPKORI_ENTIDAD" PRIMARY KEY ("ORI_ENT_COD") ENABLE
   );
 

   COMMENT ON COLUMN "ORI_ENTIDAD"."ORI_ENT_NOM" IS 'Nombre de la entidad';
   
   --TABLA ORI_ESPECIALIDADES
   CREATE TABLE "ORI_ESPECIALIDADES" 
   (	"ORI_ESP_COD" NUMBER(8,0) NOT NULL ENABLE, 
	"ORI_ESP_DESC" VARCHAR2(100 BYTE), 
	 CONSTRAINT "XPKORI_ESPECIALIDADES" PRIMARY KEY ("ORI_ESP_COD") ENABLE
   );
  
  --TABLA ORI_UBICACIONES
  CREATE TABLE "ORI_UBICACIONES" 
   (	"ORI_UBI_COD" NUMBER NOT NULL ENABLE, 
	"ORI_UBIC_ANO" NUMBER(4,0), 
	"ORI_UBIC_PUNTUACION" NUMBER(8,2), 
	"ORI_AMB_COD" NUMBER(8,0), 
	"MUN_PAI" NUMBER(3,0), 
	"MUN_PRV" NUMBER(2,0), 
	"MUN_COD" NUMBER(4,0), 
	"PRV_PAI" NUMBER(3,0), 
	 CONSTRAINT "XPKORI_UBICACIONES" PRIMARY KEY ("ORI_UBI_COD") ENABLE
   );
 

   COMMENT ON COLUMN "ORI_UBICACIONES"."ORI_UBI_COD" IS 'IDENTIFICADOR DEL CODIGO DE LA UBICACION';
 
   COMMENT ON COLUMN "ORI_UBICACIONES"."ORI_UBIC_ANO" IS 'AÑO DE LA CONVOCATORIA';
 
   COMMENT ON COLUMN "ORI_UBICACIONES"."ORI_UBIC_PUNTUACION" IS 'PUNTUACION SEGUN ANEXOS';
 
   COMMENT ON COLUMN "ORI_UBICACIONES"."ORI_AMB_COD" IS 'IDENTIFICADOR DEL CODIGO DEL AMBITO. FK CON ORI_AMBITOS';
 
   COMMENT ON COLUMN "ORI_UBICACIONES"."MUN_PAI" IS 'FK A LA TABLA DE MUNICIPIOS DE FLEXIA. PAIS';
 
   COMMENT ON COLUMN "ORI_UBICACIONES"."MUN_PRV" IS 'FK A LA TABLA DE MUNICIPIOS DE FLEXIA. PROVINCIA';
 
   COMMENT ON COLUMN "ORI_UBICACIONES"."MUN_COD" IS 'FK A LA TABLA DE MUNICIPIOS DE FLEXIA. MUNICIPIO';
 
   COMMENT ON COLUMN "ORI_UBICACIONES"."PRV_PAI" IS 'FK A LA TABLA DE MUNICIPIOS DE FLEXIA. PAIS DE LA PROVINCIA';
 
   COMMENT ON TABLE "ORI_UBICACIONES"  IS 'AMBITOS DEL PROCEDIMIENTOS DE ORIENTACION';
   
   --TABLA ORI_ORI_UBIC
   CREATE TABLE "ORI_ORI_UBIC" 
   (	"ORI_ORIENT_UBIC_COD" NUMBER(8,0) NOT NULL ENABLE, 
	"ORI_ORIENT_ANO" NUMBER(4,0), 
	"ORI_ENT_COD" NUMBER(38,0), 
	"ORI_AMB_COD" NUMBER(8,0), 
	"MUN_PAI" NUMBER(3,0), 
	"MUN_PRV" NUMBER(2,0), 
	"MUN_COD" NUMBER(4,0), 
	"PRV_PAI" NUMBER(3,0), 
	"ORI_ORIENT_DIRECCION" VARCHAR2(100 BYTE), 
	"ORI_ORIENT_HORASSOLICITADAS" NUMBER(8,2), 
	"ORI_ORIENT_HORASADJ" NUMBER(8,2), 
	"ORI_ORIENT_DESPACHOS" NUMBER(2,0), 
	"ORI_ORIENT_AULAGRUPAL" VARCHAR2(1 BYTE), 
	"ORI_ORIENT_DESPACHOS_VALIDADOS" NUMBER(2,0), 
	"ORI_ORIENT_AULAGRUPAL_VALIDADA" VARCHAR2(1 BYTE), 
	"ORI_ORIENT_VAL_TRAY" NUMBER(1,0), 
	"ORI_ORIENT_VAL_UBIC" NUMBER, 
	"ORI_ORIENT_VAL_DESPACHOS" NUMBER, 
	"ORI_ORIENT_VAL_AULAS" NUMBER, 
	"ORI_ORIENT_PUNTUACION" NUMBER, 
	"ORI_ORIENT_OBSERVACIONES" VARCHAR2(500 BYTE), 
	 CONSTRAINT "XPKORI_ORI_UBIC" PRIMARY KEY ("ORI_ORIENT_UBIC_COD") ENABLE, 
	 CONSTRAINT "R_2" FOREIGN KEY ("ORI_ENT_COD")
	  REFERENCES "ORI_ENTIDAD" ("ORI_ENT_COD") ON DELETE SET NULL ENABLE, 
	 CONSTRAINT "R_3" FOREIGN KEY ("ORI_AMB_COD")
	  REFERENCES "ORI_AMBITOS" ("ORI_AMB_COD") ON DELETE SET NULL ENABLE
   );
   
   --TABLA ORI_ORI_TRAYECTORIA
   CREATE TABLE "ORI_ORI_TRAYECTORIA" 
   (	"ORI_ORITRAY_COD" NUMBER(8,0) NOT NULL ENABLE, 
	"ORI_ENT_COD" NUMBER(38,0), 
	"ORI_ORITRAY_DESCRIPCION" VARCHAR2(500 BYTE), 
	"ORI_ORITRAY_DURACION" NUMBER(2,0), 
	"ORI_ORITRAY_ORGANISMO" VARCHAR2(100 BYTE), 
	 CONSTRAINT "XPKORI_ORI_TRAYECTORIA" PRIMARY KEY ("ORI_ORITRAY_COD") ENABLE
   );
  
  --TABLA ORI_CE_UBIC
  CREATE TABLE "ORI_CE_UBIC" 
   (	"ORI_CE_UBIC_COD" NUMBER(8,0) CONSTRAINT "SYS_C0021677" NOT NULL ENABLE, 
	"ORI_ENT_COD" NUMBER(38,0), 
	"ORI_AMB_COD" NUMBER(8,0), 
	"MUN_PAI" NUMBER(3,0), 
	"MUN_PRV" NUMBER(2,0), 
	"MUN_COD" NUMBER(4,0), 
	"PRV_PAI" NUMBER(3,0), 
	"ORI_CE_DIRECCION" VARCHAR2(100 BYTE), 
	"ORI_CE_ADJUDICADA" VARCHAR2(1 BYTE), 
	"ORI_CE_ESPECIAL" VARCHAR2(1 BYTE), 
	 CONSTRAINT "XPKORI_CE_UBIC" PRIMARY KEY ("ORI_CE_UBIC_COD") ENABLE, 
	 CONSTRAINT "R_4" FOREIGN KEY ("ORI_ENT_COD")
	  REFERENCES "ORI_ENTIDAD" ("ORI_ENT_COD") ON DELETE SET NULL ENABLE, 
	 CONSTRAINT "R_7" FOREIGN KEY ("ORI_AMB_COD")
	  REFERENCES "ORI_AMBITOS" ("ORI_AMB_COD") ON DELETE SET NULL ENABLE
   );
  
  --TABLA ORI_CE_TRAYECTORIA
  CREATE TABLE "ORI_CE_TRAYECTORIA" 
   (	"ORI_CE_COD" NUMBER(8,0) NOT NULL ENABLE, 
	"ORI_ENT_COD" NUMBER(38,0), 
	"ORI_CETRA_DESCRIPCION" VARCHAR2(100 BYTE), 
	"ORI_CETRA_DURACION" NUMBER(2,0), 
	 CONSTRAINT "XPKORI_CE_TRAYECTORIA" PRIMARY KEY ("ORI_CE_COD") ENABLE
   );
  
  --TABLA ORI_TMP_ADJUDICACION
  CREATE TABLE "ORI_TMP_ADJUDICACION" 
   (	"ORI_ORIENT_UBIC_COD" NUMBER(8,0), 
	"VALORACION" NUMBER(8,2), 
	"HORAS_SOLICITADAS" NUMBER(8,2), 
	"HORAS_ASIGNADAS_TEMP" NUMBER(8,2), 
	"PORC_TEMP" NUMBER(8,2), 
	"PORC_SOLICITADO" NUMBER(8,2), 
	"PORC_CONSUMIDO" NUMBER(8,2), 
	"HORAS_ASIGNADAS" NUMBER(8,2), 
	"IND_FINALIZA" NUMBER, 
	"FECHA_CREACION" DATE, 
	"COD_AMBITO" NUMBER
   );
  
  --TABLA ORI_TMP_ADJUDICACION_CENTROS
  CREATE TABLE "ORI_TMP_ADJUDICACION_CENTROS" 
   (	"ORI_CE_UBIC_COD" NUMBER(8,0), 
	"ORI_CE_ADJUDICADO" VARCHAR2(1 BYTE), 
	"ORI_AMB_COD" NUMBER(8,0)
   );
   
  --TABLA ORI_AUDITORIA
  CREATE TABLE "ORI_AUDITORIA" 
   (	"USU_COD" NUMBER(4,0) NOT NULL ENABLE, 
	"PROCESO" NUMBER(3,0) NOT NULL ENABLE, 
	"FEC_EJECUCION" TIMESTAMP (0) NOT NULL ENABLE, 
	"RESULTADO" VARCHAR2(100 BYTE)
   );
 

   COMMENT ON COLUMN "ORI_AUDITORIA"."USU_COD" IS 'ID del usuario que ejecuta el proceso';
 
   COMMENT ON COLUMN "ORI_AUDITORIA"."PROCESO" IS 'Código de proceso ejecutado';
 
   COMMENT ON COLUMN "ORI_AUDITORIA"."FEC_EJECUCION" IS 'Fecha y hora de ejecución del proceso';
 
   COMMENT ON COLUMN "ORI_AUDITORIA"."RESULTADO" IS 'Resultado devuelto por el proceso.';