Insert into ORI_ESPECIALIDADES (ORI_ESP_COD,ORI_ESP_DESC) values ('1','ATENCION A PERSONAS CON DISCAPACIDAD');
Insert into ORI_ESPECIALIDADES (ORI_ESP_COD,ORI_ESP_DESC) values ('2','ATENCION A COLECTIVOS EN SITAUCION O RIESGO DE EXCLUSION');
Insert into ORI_ESPECIALIDADES (ORI_ESP_COD,ORI_ESP_DESC) values ('3','CENTROS FORMACION PROFESIONAL PUBLICO O CONCERTADO');
Insert into ORI_ESPECIALIDADES (ORI_ESP_COD,ORI_ESP_DESC) values ('4','ORGANIZACION SINDICAL O EMPRESARIAL');
Insert into ORI_ESPECIALIDADES (ORI_ESP_COD,ORI_ESP_DESC) values ('5','OTRAS ENTIDADES SIN ANIMO DE LUCRO');
Insert into ORI_ESPECIALIDADES (ORI_ESP_COD,ORI_ESP_DESC) values ('6','OTRAS');
commit;