
DELETE FROM ORI_ORI_UBIC;
DELETE FROM ORI_ORI_TRAYECTORIA;
DELETE FROM ORI_CE_UBIC;
DELETE FROM ORI_CE_TRAYECTORIA;
DELETE FROM ORI_AUDITORIA;
DELETE FROM ORI_ENTIDAD;
 
 
 
 
 --TABLA ORI_AMBITOS_HORAS
 CREATE TABLE "ORI_AMBITOS_HORAS" 
   (	"ORI_AMB_COD" NUMBER(8,0) NOT NULL ENABLE, 
	"ORI_AMB_TERHIS" NUMBER(2,0), 
	"ORI_AMB_AMBITO" VARCHAR2(50 BYTE), 
	"ORI_AMB_HORASTOT" NUMBER(8,0), 
	"ORI_AMB_ANOCONV" NUMBER(4,0), 
	 CONSTRAINT "XPK_ORI_AMBITOS_HORAS" PRIMARY KEY ("ORI_AMB_COD") ENABLE
   );
 

   COMMENT ON COLUMN "ORI_AMBITOS_HORAS"."ORI_AMB_COD" IS 'IDENTIFICADOR DEL CODIGO DEL AMBITO';
 
   COMMENT ON COLUMN "ORI_AMBITOS_HORAS"."ORI_AMB_TERHIS" IS 'IDENTIFICADOR DEL CODIGO DE TERRITORIO HISOTIRCO: 1 ALAVA, 48 BIZKAYA, 20 GIPUZKOA';
 
   COMMENT ON COLUMN "ORI_AMBITOS_HORAS"."ORI_AMB_AMBITO" IS 'DESCRIPCION DEL AMBITO';
 
   COMMENT ON COLUMN "ORI_AMBITOS_HORAS"."ORI_AMB_HORASTOT" IS 'HORAS DE ORIENTACION DEL AMBITO';
 
   COMMENT ON COLUMN "ORI_AMBITOS_HORAS"."ORI_AMB_ANOCONV" IS 'AÑO DE LA CONVOCATORIA';
 
   COMMENT ON TABLE "ORI_AMBITOS_HORAS"  IS 'AMBITOS DEL PROCEDIMIENTO DE ORIENTACION - ORIENTACION';
   
   
   
   
    --TABLA ORI_AMBITOS_CE
 CREATE TABLE "ORI_AMBITOS_CE" 
   (	"ORI_AMB_COD" NUMBER(8,0) NOT NULL ENABLE, 
	"ORI_AMB_TERHIS" NUMBER(2,0), 
	"ORI_AMB_AMBITO" VARCHAR2(50 BYTE), 
	"ORI_AMB_ANOCONV" NUMBER(4,0), 
	"ORI_AMB_CE" NUMBER(2,0), 
	"ORI_AMB_CE_ESPECIAL" NUMBER(2,0), 
	 CONSTRAINT "XPK_ORI_AMBITOS_CE" PRIMARY KEY ("ORI_AMB_COD") ENABLE
   );
 

   COMMENT ON COLUMN "ORI_AMBITOS_CE"."ORI_AMB_COD" IS 'IDENTIFICADOR DEL CODIGO DEL AMBITO';
 
   COMMENT ON COLUMN "ORI_AMBITOS_CE"."ORI_AMB_TERHIS" IS 'IDENTIFICADOR DEL CODIGO DE TERRITORIO HISOTIRCO: 1 ALAVA, 48 BIZKAYA, 20 GIPUZKOA';
 
   COMMENT ON COLUMN "ORI_AMBITOS_CE"."ORI_AMB_AMBITO" IS 'DESCRIPCION DEL AMBITO';
 
   COMMENT ON COLUMN "ORI_AMBITOS_CE"."ORI_AMB_ANOCONV" IS 'AÑO DE LA CONVOCATORIA';
 
   COMMENT ON COLUMN "ORI_AMBITOS_CE"."ORI_AMB_CE" IS 'NUMERO DE CENTROS ASOCIADOS AL AMBITO';
 
   COMMENT ON COLUMN "ORI_AMBITOS_CE"."ORI_AMB_CE_ESPECIAL" IS 'NUMERO DE CENTROS ESPECIALES ASOCIADOS AL AMBITO';
 
   COMMENT ON TABLE "ORI_AMBITOS_CE"  IS 'AMBITOS DEL PROCEDIMIENTOS DE ORIENTACION';
   
   
   
   
   
     --TABLA ORI_UBICACIONES_CE
  CREATE TABLE "ORI_UBICACIONES_CE" 
   (	"ORI_UBI_COD" NUMBER NOT NULL ENABLE, 
	"ORI_UBIC_ANO" NUMBER(4,0), 
	"ORI_AMB_COD" NUMBER(8,0), 
	"MUN_PAI" NUMBER(3,0), 
	"MUN_PRV" NUMBER(2,0), 
	"MUN_COD" NUMBER(4,0), 
	"PRV_PAI" NUMBER(3,0), 
	 CONSTRAINT "XPKORI_UBICACIONES_CE" PRIMARY KEY ("ORI_UBI_COD") ENABLE
   );
 

   COMMENT ON COLUMN "ORI_UBICACIONES_CE"."ORI_UBI_COD" IS 'IDENTIFICADOR DEL CODIGO DE LA UBICACION';
 
   COMMENT ON COLUMN "ORI_UBICACIONES_CE"."ORI_UBIC_ANO" IS 'AÑO DE LA CONVOCATORIA';
 
   COMMENT ON COLUMN "ORI_UBICACIONES_CE"."ORI_AMB_COD" IS 'IDENTIFICADOR DEL CODIGO DEL AMBITO. FK CON ORI_AMBITOS';
 
   COMMENT ON COLUMN "ORI_UBICACIONES_CE"."MUN_PAI" IS 'FK A LA TABLA DE MUNICIPIOS DE FLEXIA. PAIS';
 
   COMMENT ON COLUMN "ORI_UBICACIONES_CE"."MUN_PRV" IS 'FK A LA TABLA DE MUNICIPIOS DE FLEXIA. PROVINCIA';
 
   COMMENT ON COLUMN "ORI_UBICACIONES_CE"."MUN_COD" IS 'FK A LA TABLA DE MUNICIPIOS DE FLEXIA. MUNICIPIO';
 
   COMMENT ON COLUMN "ORI_UBICACIONES_CE"."PRV_PAI" IS 'FK A LA TABLA DE MUNICIPIOS DE FLEXIA. PAIS DE LA PROVINCIA';
 
   COMMENT ON TABLE "ORI_UBICACIONES_CE"  IS 'AMBITOS DEL PROCEDIMIENTOS DE ORIENTACION - CENTRO EMPLEO';
   
   
   
	alter table ori_ori_ubic drop constraint R_3;

	alter table ori_ori_ubic add constraint "R_3" foreign key ("ORI_AMB_COD")
	references "ORI_AMBITOS_HORAS" ("ORI_AMB_COD") on delete set null ENABLE novalidate;


	alter table ori_ce_ubic drop constraint R_7;

	alter table ori_ce_ubic add constraint "R_7" foreign key ("ORI_AMB_COD")
	references "ORI_AMBITOS_CE" ("ORI_AMB_COD") on delete set null enable novalidate;
  
    
  
  
	ALTER TABLE ORI_ORI_UBIC  
	MODIFY (ORI_ORIENT_VAL_UBIC NUMBER(8, 2) );

	ALTER TABLE ORI_ORI_UBIC  
	MODIFY (ORI_ORIENT_PUNTUACION NUMBER(8, 2) );

	ALTER TABLE ORI_ORI_UBIC  
	MODIFY (ORI_ORIENT_VAL_TRAY NUMBER(2, 0) );