ALTER TABLE ORI_ORI_TRAYECTORIA  
MODIFY (ORI_ORITRAY_DURACION NUMBER(4, 2) );

ALTER TABLE ORI_CE_TRAYECTORIA  
MODIFY (ORI_CETRA_DURACION NUMBER(4, 2) );

ALTER TABLE ORI_ENTIDAD  
MODIFY (ORI_ENT_NUMTRAB NUMBER(7, 2) );

ALTER TABLE ORI_ENTIDAD  
MODIFY (ORI_ENT_NUMTRAB_DISC NUMBER(7, 2) );

