
package es.altia.flexia.integracion.moduloexterno.melanbide54.cliente.altacentro;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IESISPEPort", targetNamespace = "http://namespace.softwareag.com/entirex/xml/mapping")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IESISPEPort {


    /**
     * 
     * @param areaCOMUNICACION
     * @return
     *     returns es.altia.flexia.integracion.moduloexterno.melanbide54.cliente.altacentro.IWACACTSResponse.AREACOMUNICACION
     */
    @WebMethod(operationName = "IWACACTS", action = "IWACACTS")
    @WebResult(name = "AREA-COMUNICACION", targetNamespace = "")
    @RequestWrapper(localName = "IWACACTS", targetNamespace = "urn:com-softwareag-entirex-rpc:IESISPE", className = "es.altia.flexia.integracion.moduloexterno.melanbide54.cliente.altacentro.IWACACTS")
    @ResponseWrapper(localName = "IWACACTSResponse", targetNamespace = "urn:com-softwareag-entirex-rpc:IESISPE", className = "es.altia.flexia.integracion.moduloexterno.melanbide54.cliente.altacentro.IWACACTSResponse")
    public es.altia.flexia.integracion.moduloexterno.melanbide54.cliente.altacentro.IWACACTSResponse.AREACOMUNICACION iwacacts(
        @WebParam(name = "AREA-COMUNICACION", targetNamespace = "")
        es.altia.flexia.integracion.moduloexterno.melanbide54.cliente.altacentro.IWACACTS.AREACOMUNICACION areaCOMUNICACION);

}
