
package es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "LangaiDemandaService", targetNamespace = "http://langaiDemanda.services.langaiWS.es/", wsdlLocation = "http://10.168.212.173:17003/langaiWS_Final/langaiDemanda?wsdl")
public class LangaiDemandaService
    extends Service
{

    private final static URL LANGAIDEMANDASERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.LangaiDemandaService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = es.altia.flexia.integracion.moduloexterno.melanbide_interop.webservice.langaiWS.fse.LangaiDemandaService.class.getResource(".");
            url = new URL(baseUrl, "http://10.168.212.173:17003/langaiWS_Final/langaiDemanda?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.168.212.173:17003/langaiWS_Final/langaiDemanda?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        LANGAIDEMANDASERVICE_WSDL_LOCATION = url;
    }

    public LangaiDemandaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LangaiDemandaService() {
        super(LANGAIDEMANDASERVICE_WSDL_LOCATION, new QName("http://langaiDemanda.services.langaiWS.es/", "LangaiDemandaService"));
    }

    /**
     * 
     * @return
     *     returns LangaiDemanda
     */
    @WebEndpoint(name = "LangaiDemandaPort")
    public LangaiDemanda getLangaiDemandaPort() {
        return super.getPort(new QName("http://langaiDemanda.services.langaiWS.es/", "LangaiDemandaPort"), LangaiDemanda.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LangaiDemanda
     */
    @WebEndpoint(name = "LangaiDemandaPort")
    public LangaiDemanda getLangaiDemandaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://langaiDemanda.services.langaiWS.es/", "LangaiDemandaPort"), LangaiDemanda.class, features);
    }

}
