--------------------------------------------------------
--  DDL for Table CPE_PUESTO
--------------------------------------------------------

  CREATE TABLE "CPE_PUESTO" 
   (	"CPE_PTO_COD_PUESTO" VARCHAR2(4 BYTE), 
	"CPE_PTO_DESC_PUESTO" VARCHAR2(200 BYTE), 
	"CPE_PTO_PAI_COD_1" NUMBER(3,0), 
	"CPE_PTO_PAI_COD_2" NUMBER(3,0), 
	"CPE_PTO_PAI_COD_3" NUMBER(3,0), 
	"CPE_PTO_COD_TIT_1" VARCHAR2(8 BYTE), 
	"CPE_PTO_COD_TIT_2" VARCHAR2(8 BYTE), 
	"CPE_PTO_COD_TIT_3" VARCHAR2(8 BYTE), 
	"CPE_PTO_FUNCIONES" VARCHAR2(1000 BYTE), 
	"CPE_PTO_COD_IDIOMA_1" VARCHAR2(8 BYTE), 
	"CPE_PTO_COD_IDIOMA_2" VARCHAR2(8 BYTE), 
	"CPE_PTO_COD_NIV_FORM" VARCHAR2(8 BYTE), 
	"CPE_PTO_COD_GR_COT" VARCHAR2(8 BYTE), 
	"CPE_PTO_SALARIO_ANEX1" NUMBER(10,2), 
	"CPE_PTO_DIETAS_MANUT" NUMBER(10,2), 
	"CPE_PTO_MESES_MANUT" NUMBER(4,0), 
	"CPE_PTO_TRAM_SEGUROS" NUMBER(10,2), 
	"CPE_PTO_IMP_MAX_SUBV" NUMBER(10,2), 
	"CPE_PTO_FEC_INI" DATE, 
	"CPE_PTO_FEC_FIN" DATE, 
	"CPE_PTO_CONVENIO_COL" VARCHAR2(500 BYTE), 
	"CPE_PTO_SAL_BRUTO" NUMBER(10,2), 
	"CPE_PTO_DIETAS_CONV" NUMBER(10,2), 
	"CPE_PTO_COSTE_CONT" NUMBER(10,2), 
	"CPE_PTO_OTROS_BENEF" VARCHAR2(1000 BYTE), 
	"CPE_PTO_COD_RESULT" VARCHAR2(8 BYTE), 
	"CPE_PTO_COD_MOTIVO" VARCHAR2(8 BYTE), 
	"CPE_PTO_OBSERVACIONES" VARCHAR2(1000 BYTE), 
	"CPE_PTO_COD_NIV_IDI_1" VARCHAR2(8 BYTE), 
	"CPE_PTO_COD_NIV_IDI_2" VARCHAR2(8 BYTE), 
	"CPE_PTO_NUMEXP" VARCHAR2(30 BYTE), 
	"CPE_PTO_EXP_EJE" NUMBER(4,0), 
	"CPE_PTO_CIUDAD_DESTINO" VARCHAR2(200 BYTE), 
	"CPE_PTO_DPTO" VARCHAR2(200 BYTE), 
	"CPE_PTO_COD_IDIOMA_3" VARCHAR2(8 BYTE), 
	"CPE_PTO_COD_NIV_IDI_3" VARCHAR2(8 BYTE), 
	"CPE_PTO_SAL_SOLIC" NUMBER(10,2), 
	"CPE_PTO_DIETAS_SOLIC" NUMBER(10,2), 
	"CPE_PTO_TRAM_SOLIC" NUMBER(10,2), 
	"CPE_PTO_IMP_TOT_SOLIC" NUMBER(10,2), 
	"CPE_PTO_SALARIO_ANEX2" NUMBER(10,2), 
	"CPE_PTO_SALARIO_ANEX3" NUMBER(10,2), 
	"CPE_PTO_SALARIO_ANEX_TOT" NUMBER(10,2), 
	"CPE_PTO_MESES_CONTRATO" NUMBER(6,0)
   );
 

   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_COD_PUESTO" IS 'Codigo univoco del puesto - PK';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_DESC_PUESTO" IS 'Descripción o nombre del puesto';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_PAI_COD_1" IS 'Código de país 1';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_PAI_COD_2" IS 'Código de país 2';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_PAI_COD_3" IS 'Código de país 3';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_COD_TIT_1" IS 'Código de titulación 1';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_COD_TIT_2" IS 'Código de titulación 2';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_COD_TIT_3" IS 'Código de titulación 3';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_FUNCIONES" IS 'Funciones del puesto';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_COD_IDIOMA_1" IS 'Código de idioma 1';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_COD_IDIOMA_2" IS 'Código de idioma 2';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_COD_NIV_FORM" IS 'Nivel formativo';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_COD_GR_COT" IS 'Grupo cotización';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_SALARIO_ANEX1" IS 'Salario según anexo 1 - Pais 1';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_DIETAS_MANUT" IS 'Dietas manutención';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_MESES_MANUT" IS 'Meses manutención';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_TRAM_SEGUROS" IS 'Tramitación seguros médicos y permisos';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_IMP_MAX_SUBV" IS 'Importe máximo subvencionable';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_FEC_INI" IS 'Fecha inicio';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_FEC_FIN" IS 'Fecha fin';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_CONVENIO_COL" IS 'Convenio colectivo';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_SAL_BRUTO" IS 'Salario Bruto + SS empresa';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_DIETAS_CONV" IS 'Dietas según convenio';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_COSTE_CONT" IS 'Coste contratación';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_OTROS_BENEF" IS 'Otros beneficios';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_COD_RESULT" IS 'Código de resultado';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_COD_MOTIVO" IS 'Código de motivo';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_OBSERVACIONES" IS 'Observaciones';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_COD_NIV_IDI_1" IS 'Nivel de idioma 1';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_COD_NIV_IDI_2" IS 'Nivel de idioma 2';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_NUMEXP" IS 'Número de expediente';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_EXP_EJE" IS 'Ejercicio del expediente';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_CIUDAD_DESTINO" IS 'Ciudad de destino';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_DPTO" IS 'Departamento';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_COD_IDIOMA_3" IS 'Código de idioma 3';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_COD_NIV_IDI_3" IS 'Nivel de idioma 3';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_SAL_SOLIC" IS 'Salario solicitado';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_DIETAS_SOLIC" IS 'Dietas solicitadas';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_TRAM_SOLIC" IS 'Tramitación / Seguros solicitado';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_IMP_TOT_SOLIC" IS 'Importe total solicitado';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_SALARIO_ANEX2" IS 'Salario según anexo 1 - Pais 2';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_SALARIO_ANEX3" IS 'Salario según anexo 1 - Pais 3';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_SALARIO_ANEX_TOT" IS 'Total salario';
 
   COMMENT ON COLUMN "CPE_PUESTO"."CPE_PTO_MESES_CONTRATO" IS 'Duración en meses del contrato';
   

   
   
   CREATE UNIQUE INDEX "CPE_PUESTO_PK" ON "CPE_PUESTO" ("CPE_PTO_COD_PUESTO", "CPE_PTO_NUMEXP");

   ALTER TABLE "CPE_PUESTO" ADD CONSTRAINT "CPE_PUESTO_PK" PRIMARY KEY ("CPE_PTO_COD_PUESTO", "CPE_PTO_NUMEXP") ENABLE;
 
   ALTER TABLE "CPE_PUESTO" MODIFY ("CPE_PTO_COD_PUESTO" NOT NULL ENABLE);
 
   ALTER TABLE "CPE_PUESTO" MODIFY ("CPE_PTO_NUMEXP" NOT NULL ENABLE);
   
   

   
--------------------------------------------------------
--  DDL for Table CPE_OFERTA
--------------------------------------------------------

  CREATE TABLE "CPE_OFERTA" 
   (	"CPE_OFE_ID_OFERTA" NUMBER(8,0), 
	"CPE_OFE_COD_OFERTA" VARCHAR2(15 BYTE), 
	"CPE_OFE_COD_OFI_GEST" VARCHAR2(8 BYTE), 
	"CPE_OFE_PREC" VARCHAR2(1 BYTE), 
	"CPE_OFE_PREC_NOM" VARCHAR2(200 BYTE), 
	"CPE_OFE_DIFUSION" VARCHAR2(1 BYTE), 
	"CPE_OFE_FEC_DIFUSION" DATE, 
	"CPE_OFE_FEC_ENV_CAND" DATE, 
	"CPE_OFE_NUM_TOT_CAND" NUMBER(3,0), 
	"CPE_OFE_DOC_GEST_OFE" BLOB, 
	"CPE_OFE_CONTRATACION" VARCHAR2(1 BYTE), 
	"CPE_OFE_MOT_CONTRATACION" VARCHAR2(1000 BYTE), 
	"CPE_OFE_COD_TIPO_NIF" VARCHAR2(8 BYTE), 
	"CPE_OFE_NIF" VARCHAR2(10 BYTE), 
	"CPE_OFE_NOMBRE" VARCHAR2(200 BYTE), 
	"CPE_OFE_APE1" VARCHAR2(200 BYTE), 
	"CPE_OFE_APE2" VARCHAR2(200 BYTE), 
	"CPE_OFE_EMAIL" VARCHAR2(200 BYTE), 
	"CPE_OFE_TLF" VARCHAR2(15 BYTE), 
	"CPE_OFE_FEC_NAC" DATE, 
	"CPE_OFE_SEXO" VARCHAR2(1 BYTE), 
	"CPE_OFE_COD_TITULACION" VARCHAR2(8 BYTE), 
	"CPE_OFE_DOC_CONTRATACION" BLOB, 
	"CPE_OFE_FEC_INI" DATE, 
	"CPE_OFE_FEC_FIN" DATE, 
	"CPE_OFE_COD_GR_COT" VARCHAR2(8 BYTE), 
	"CPE_OFE_SALARIOB" NUMBER(10,2), 
	"CPE_OFE_DIETAS_CONVENIO" NUMBER(10,2), 
	"CPE_OFE_DIETAS_CONVOC" NUMBER(10,2), 
	"CPE_OFE_FEC_BAJA" DATE, 
	"CPE_OFE_COD_CAUSA_BAJA" VARCHAR2(8 BYTE), 
	"CPE_OFE_OBSERVACIONES" VARCHAR2(1000 BYTE), 
	"CPE_OFE_COD_PUESTO" VARCHAR2(4 BYTE), 
	"CPE_OFE_NUMEXP" VARCHAR2(30 BYTE), 
	"CPE_OFE_EXP_EJE" NUMBER(4,0), 
	"CPE_OFE_ANO_TITULACION" NUMBER(4,0), 
	"CPE_OFE_FL_SUSTITUTO" VARCHAR2(1 BYTE), 
	"CPE_OFE_NOM_DOC_GEST_OFE" VARCHAR2(500 BYTE), 
	"CPE_OFE_NOM_DOC_CONTRATACION" VARCHAR2(500 BYTE), 
	"CPE_OFE_ID_OFERTA_ORIGEN" NUMBER(8,0),
	"CPE_OFE_MESES_CONTRATO" NUMBER(6,0)
   );
 

   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_ID_OFERTA" IS 'Id de la tabla';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_COD_OFERTA" IS 'Código de la oferta';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_COD_OFI_GEST" IS 'Código de la oficina de gestión';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_PREC" IS 'Precandidato (S/N)';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_PREC_NOM" IS 'Nombre precandidato';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_DIFUSION" IS 'Difusión (S/N)';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_FEC_DIFUSION" IS 'Fecha difusión';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_FEC_ENV_CAND" IS 'Fecha primer envío candidatos';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_NUM_TOT_CAND" IS 'Número total de l candidatos';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_DOC_GEST_OFE" IS 'Documento de gestión de la oferta';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_CONTRATACION" IS 'Contratación (S/N/Sin Datos)';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_MOT_CONTRATACION" IS 'Motivo de la NO contratación';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_COD_TIPO_NIF" IS 'Tipo de documento del contratado';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_NIF" IS 'Número de documento del contratado';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_NOMBRE" IS 'Nombre del contratado';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_APE1" IS 'Apellido 1 del contratado';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_APE2" IS 'Apellido 2 del contratado';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_EMAIL" IS 'email del contratado';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_TLF" IS 'Número de teléfono del contratado';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_FEC_NAC" IS 'Fecha de nacimiento del contratado';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_SEXO" IS 'Sexo del contratado';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_COD_TITULACION" IS 'Titulación del contratado';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_DOC_CONTRATACION" IS 'Documento de contratación';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_FEC_INI" IS 'Fecha de inicio del contrato';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_FEC_FIN" IS 'Fecha de fin del contrato';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_COD_GR_COT" IS 'Grupo de cotización del contratado';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_SALARIOB" IS 'Salario bruto + SS empresa';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_DIETAS_CONVENIO" IS 'Dietas según convenio';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_DIETAS_CONVOC" IS 'Dietas de la convocatoria';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_FEC_BAJA" IS 'Fecha de baja';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_COD_CAUSA_BAJA" IS 'Causa de baja';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_OBSERVACIONES" IS 'Observaciones';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_COD_PUESTO" IS 'FK al puesto';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_NUMEXP" IS 'Número del expediente';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_EXP_EJE" IS 'Ejercicio del expediente';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_ANO_TITULACION" IS 'Año Titulación';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_FL_SUSTITUTO" IS 'Flag que indica si la persona contratada es sustituto o no';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_NOM_DOC_GEST_OFE" IS 'Nombre del documento de gestión asociado.';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_NOM_DOC_CONTRATACION" IS 'Nombre del documento de contratación asociado.';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_ID_OFERTA_ORIGEN" IS 'ID de la oferta de la cual se van a coger parte de los datos: oferta de origen.';
 
   COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_MESES_CONTRATO" IS 'Duración en meses del contrato';

   CREATE UNIQUE INDEX "CPE_OFERTA_PK" ON "CPE_OFERTA" ("CPE_OFE_ID_OFERTA", "CPE_OFE_COD_PUESTO", "CPE_OFE_NUMEXP");

   
   
   
   ALTER TABLE "CPE_OFERTA" ADD CONSTRAINT "CPE_OFERTA_PK" PRIMARY KEY ("CPE_OFE_ID_OFERTA", "CPE_OFE_COD_PUESTO", "CPE_OFE_NUMEXP") ENABLE;
 
   ALTER TABLE "CPE_OFERTA" MODIFY ("CPE_OFE_ID_OFERTA" NOT NULL ENABLE);
 
   ALTER TABLE "CPE_OFERTA" MODIFY ("CPE_OFE_COD_PUESTO" NOT NULL ENABLE);
 
   ALTER TABLE "CPE_OFERTA" MODIFY ("CPE_OFE_NUMEXP" NOT NULL ENABLE);

   ALTER TABLE "CPE_OFERTA" ADD CONSTRAINT "CPE_OFERTA_CPE_PUESTO_FK1" FOREIGN KEY ("CPE_OFE_COD_PUESTO", "CPE_OFE_NUMEXP")
   REFERENCES "CPE_PUESTO" ("CPE_PTO_COD_PUESTO", "CPE_PTO_NUMEXP") ENABLE;
   
   
   
--------------------------------------------------------
--  DDL for Table CPE_JUSTIFICACION
--------------------------------------------------------

  CREATE TABLE "CPE_JUSTIFICACION" 
   (	"CPE_JUS_ID_JUSTIFICACION" NUMBER(8,0), 
	"CPE_JUS_COD_PUESTO" VARCHAR2(4 BYTE), 
	"CPE_JUS_NUMEXP" VARCHAR2(30 BYTE), 
	"CPE_JUS_EXP_EJE" NUMBER(4,0), 
	"CPE_JUS_ID_OFERTA" NUMBER(8,0), 
	"CPE_JUS_COD_ESTADO" VARCHAR2(8 BYTE), 
	"CPE_JUS_FL_VARIOS_TRAB" VARCHAR2(1 BYTE), 
	"CPE_JUS_IMP_JUSTIFICADO" NUMBER(10,2)
   );
 

   COMMENT ON COLUMN "CPE_JUSTIFICACION"."CPE_JUS_ID_JUSTIFICACION" IS 'ID de la tabla';
 
   COMMENT ON COLUMN "CPE_JUSTIFICACION"."CPE_JUS_COD_PUESTO" IS 'Código del puesto';
 
   COMMENT ON COLUMN "CPE_JUSTIFICACION"."CPE_JUS_NUMEXP" IS 'Número de expediente';
 
   COMMENT ON COLUMN "CPE_JUSTIFICACION"."CPE_JUS_EXP_EJE" IS 'Ejercicio del expediente';
 
   COMMENT ON COLUMN "CPE_JUSTIFICACION"."CPE_JUS_ID_OFERTA" IS 'Id de la oferta';
 
   COMMENT ON COLUMN "CPE_JUSTIFICACION"."CPE_JUS_COD_ESTADO" IS 'Estado (Justificado/Renuncia)';
 
   COMMENT ON COLUMN "CPE_JUSTIFICACION"."CPE_JUS_FL_VARIOS_TRAB" IS 'Flag para indicar si ha dispuesto de varios trabajadores';
 
   COMMENT ON COLUMN "CPE_JUSTIFICACION"."CPE_JUS_IMP_JUSTIFICADO" IS 'Importe jusiticado';
   
   
   

   CREATE UNIQUE INDEX "CPE_JUSTIFICACION_PK" ON "CPE_JUSTIFICACION" ("CPE_JUS_ID_JUSTIFICACION", "CPE_JUS_COD_PUESTO", "CPE_JUS_ID_OFERTA", "CPE_JUS_NUMEXP");

   ALTER TABLE "CPE_JUSTIFICACION" ADD CONSTRAINT "CPE_JUSTIFICACION_PK" PRIMARY KEY ("CPE_JUS_ID_JUSTIFICACION", "CPE_JUS_COD_PUESTO", "CPE_JUS_ID_OFERTA", "CPE_JUS_NUMEXP") ENABLE;
 
   ALTER TABLE "CPE_JUSTIFICACION" MODIFY ("CPE_JUS_ID_JUSTIFICACION" NOT NULL ENABLE);
 
   ALTER TABLE "CPE_JUSTIFICACION" MODIFY ("CPE_JUS_ID_OFERTA" NOT NULL ENABLE);
 
   ALTER TABLE "CPE_JUSTIFICACION" MODIFY ("CPE_JUS_COD_PUESTO" NOT NULL ENABLE);
 
   ALTER TABLE "CPE_JUSTIFICACION" MODIFY ("CPE_JUS_NUMEXP" NOT NULL ENABLE);




  
  

--------------------------------------------------------
--  DDL for Table CPE_SALARIOS
--------------------------------------------------------

  CREATE TABLE "CPE_SALARIOS" 
   (	"CPE_SAL_PAI_COD" NUMBER(3,0), 
	"CPE_SAL_COD_GR_COT" VARCHAR2(4 BYTE), 
	"CPE_SAL_DESCRIPCION" VARCHAR2(200 BYTE), 
	"CPE_SAL_IMPORTE" NUMBER(10,2)
   );
 

  COMMENT ON COLUMN "CPE_SALARIOS"."CPE_SAL_PAI_COD" IS 'Código de país';
 
  COMMENT ON COLUMN "CPE_SALARIOS"."CPE_SAL_COD_GR_COT" IS 'Código Grupo Cotización';
 
  COMMENT ON COLUMN "CPE_SALARIOS"."CPE_SAL_DESCRIPCION" IS 'Descripción';
 
  COMMENT ON COLUMN "CPE_SALARIOS"."CPE_SAL_IMPORTE" IS 'Importe del salario';

  

  
  CREATE UNIQUE INDEX "CPE_SALARIOS_PK" ON "CPE_SALARIOS" ("CPE_SAL_PAI_COD", "CPE_SAL_COD_GR_COT");

  ALTER TABLE "CPE_SALARIOS" ADD CONSTRAINT "CPE_SALARIOS_PK" PRIMARY KEY ("CPE_SAL_PAI_COD", "CPE_SAL_COD_GR_COT") ENABLE;
 
  ALTER TABLE "CPE_SALARIOS" MODIFY ("CPE_SAL_COD_GR_COT" NOT NULL ENABLE);
 
  ALTER TABLE "CPE_SALARIOS" MODIFY ("CPE_SAL_PAI_COD" NOT NULL ENABLE);

