--------------------------------------------------------
--  DDL for Table CPE_PUESTO
--------------------------------------------------------
ALTER TABLE CPE_PUESTO  MODIFY (CPE_PTO_COD_TIT_1 VARCHAR2(8));
ALTER TABLE CPE_PUESTO  MODIFY (CPE_PTO_COD_TIT_2 VARCHAR2(8));
ALTER TABLE CPE_PUESTO  MODIFY (CPE_PTO_COD_TIT_3 VARCHAR2(8));
ALTER TABLE CPE_PUESTO  MODIFY (CPE_PTO_COD_IDIOMA_1 VARCHAR2(8));
ALTER TABLE CPE_PUESTO  MODIFY (CPE_PTO_COD_IDIOMA_2 VARCHAR2(8));
ALTER TABLE CPE_PUESTO  MODIFY (CPE_PTO_COD_NIV_FORM VARCHAR2(8));
ALTER TABLE CPE_PUESTO  MODIFY (CPE_PTO_COD_GR_COT VARCHAR2(8));
ALTER TABLE CPE_PUESTO  MODIFY (CPE_PTO_COD_RESULT VARCHAR2(8));
ALTER TABLE CPE_PUESTO  MODIFY (CPE_PTO_COD_NIV_IDI_1 VARCHAR2(8));
ALTER TABLE CPE_PUESTO  MODIFY (CPE_PTO_COD_NIV_IDI_2 VARCHAR2(8));

--------------------------------------------------------
--  DDL for Table CPE_OFERTA
--------------------------------------------------------
   ALTER TABLE "CPE_OFERTA" ADD 
   (
    "CPE_OFE_DESC_PUESTO"   VARCHAR2(200 BYTE),
    "CPE_OFE_PAI_COD_1"     NUMBER(3,0),
    "CPE_OFE_PAI_COD_2"     NUMBER(3,0),
    "CPE_OFE_PAI_COD_3"     NUMBER(3,0),
    "CPE_OFE_COD_TIT_1"     VARCHAR2(8 BYTE),
    "CPE_OFE_COD_TIT_2"     VARCHAR2(8 BYTE),
    "CPE_OFE_COD_TIT_3"     VARCHAR2(8 BYTE),
    "CPE_OFE_FUNCIONES"     VARCHAR2(1000 BYTE),
    "CPE_OFE_COD_IDIOMA_1"  VARCHAR2(8 BYTE),
    "CPE_OFE_COD_IDIOMA_2"  VARCHAR2(8 BYTE),
	"CPE_OFE_COD_IDIOMA_3"     VARCHAR2(8 BYTE),
	"CPE_OFE_COD_NIV_IDI_1"    VARCHAR2(8 BYTE),
    "CPE_OFE_COD_NIV_IDI_2"    VARCHAR2(8 BYTE),
    "CPE_OFE_COD_NIV_IDI_3"    VARCHAR2(8 BYTE),
	"CPE_OFE_COD_NIV_FORM"  VARCHAR2(8 BYTE),
	"CPE_OFE_CIUDAD_DESTINO" VARCHAR2(200 BYTE), 
	"CPE_OFE_DPTO" VARCHAR2(200 BYTE),
	"CPE_OFE_COD_CAUSA_RENUNCIA" VARCHAR2(8 BYTE) 
	);
   
  COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_DESC_PUESTO" IS   'Descripción o nombre del puesto';
  COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_PAI_COD_1" IS   'Código de país 1';
  COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_PAI_COD_2" IS   'Código de país 2';
  COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_PAI_COD_3" IS   'Código de país 3';
  COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_COD_TIT_1" IS   'Código de titulación 1';
  COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_COD_TIT_2" IS   'Código de titulación 2';
  COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_COD_TIT_3" IS   'Código de titulación 3';
  COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_FUNCIONES" IS   'Funciones del puesto';
  COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_COD_IDIOMA_1" IS  'Código de idioma 1';
  COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_COD_IDIOMA_2" IS  'Código de idioma 2';
  COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_COD_IDIOMA_3" IS  'Código de idioma 3';
  COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_COD_NIV_IDI_1" IS  'Nivel de idioma 1';
  COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_COD_NIV_IDI_2" IS  'Nivel de idioma 2';
  COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_COD_NIV_IDI_3" IS  'Nivel de idioma 3';
  COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_COD_NIV_FORM" IS  'Nivel formativo';
  COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_CIUDAD_DESTINO" IS  'Ciudad destino';
  COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_DPTO" IS  'Departamento';
  COMMENT ON COLUMN "CPE_OFERTA"."CPE_OFE_COD_CAUSA_RENUNCIA" IS 'Codigo de causa por la que se renuncia al puesto';


ALTER TABLE CPE_JUSTIFICACION ADD (CPE_JUS_MINORACION NUMBER(10, 2) );
ALTER TABLE CPE_JUSTIFICACION ADD (CPE_JUS_BASCOT_CC NUMBER(10, 2) );
ALTER TABLE CPE_JUSTIFICACION ADD (CPE_JUS_COEF_TGSS NUMBER(10, 2) );
ALTER TABLE CPE_JUSTIFICACION ADD (CPE_JUS_FOGASA NUMBER(10, 2) );
ALTER TABLE CPE_JUSTIFICACION ADD (CPE_JUS_AT NUMBER(10, 2) );
ALTER TABLE CPE_JUSTIFICACION ADD (CPE_JUS_EPSV NUMBER(10, 2) );
ALTER TABLE CPE_JUSTIFICACION ADD (CPE_JUS_DIETAS_ABO NUMBER(10, 2) );
ALTER TABLE CPE_JUSTIFICACION ADD (CPE_JUS_VIS_MED_ABO NUMBER(10, 2) );
ALTER TABLE CPE_JUSTIFICACION ADD (CPE_JUS_BONIF NUMBER(10, 2) );