create or replace
PROCEDURE CPE_BORRADO_HISTORICO (expediente in varchar2, tramite IN VARCHAR2) IS

  --CODIGO VARCHAR2(100);
 
BEGIN      
  dbms_output.put_line('INICIO FUNCION CPE_BORRADO_HISTORICO: '||to_char(SYSDATE,'yyyymmdd hh24:mi:ss')); 
  
  --INSERTAMOS SOLICITUD
DELETE FROM CPE_HIST_OFERTA WHERE CPE_OFE_NUMEXP=EXPEDIENTE AND CPE_OFE_COD_TRAMITE = tramite;
commit;

DELETE FROM CPE_HIST_PUESTO WHERE CPE_PTO_NUMEXP=EXPEDIENTE AND CPE_PTO_COD_TRAMITE = tramite;
commit;

DELETE FROM CPE_HIST_JUSTIFICACION WHERE CPE_JUS_NUMEXP=EXPEDIENTE AND CPE_JUS_COD_TRAMITE = tramite;
commit;

dbms_output.put_line('FIN PROCESO CPE_BORRADO_HISTORICO: '||to_char(SYSDATE,'yyyymmdd hh24:mi:ss'));   

END CPE_BORRADO_HISTORICO;