
package es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "serviceOpc2", targetNamespace = "http://ws.service.ws.w75b.ejie.com/", wsdlLocation = "http://10.168.212.21:7085/pasIkusServices/serviceOpc2?wsdl")
public class ServiceOpc2
    extends Service
{

    private final static URL SERVICEOPC2_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.ServiceOpc2 .class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = es.altia.flexia.integracion.moduloexterno.meikus.plugin.bilbomatica.ServiceOpc2 .class.getResource(".");
            url = new URL(baseUrl, "http://10.168.212.21:7085/pasIkusServices/serviceOpc2?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.168.212.21:7085/pasIkusServices/serviceOpc2?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SERVICEOPC2_WSDL_LOCATION = url;
    }

    public ServiceOpc2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceOpc2() {
        super(SERVICEOPC2_WSDL_LOCATION, new QName("http://ws.service.ws.w75b.ejie.com/", "serviceOpc2"));
    }

    /**
     * 
     * @return
     *     returns W75BServiceOpc2
     */
    @WebEndpoint(name = "serviceOpc2Port")
    public W75BServiceOpc2 getServiceOpc2Port() {
        return super.getPort(new QName("http://ws.service.ws.w75b.ejie.com/", "serviceOpc2Port"), W75BServiceOpc2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns W75BServiceOpc2
     */
    @WebEndpoint(name = "serviceOpc2Port")
    public W75BServiceOpc2 getServiceOpc2Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.service.ws.w75b.ejie.com/", "serviceOpc2Port"), W75BServiceOpc2.class, features);
    }

}
