-- Crear campos para guardar campos Aviso Email y SMS : Titular 
INSERT INTO E_PCA
select
PCA_MUN, PCA_PRO, PCA_COD||'TIT', PCA_DES||' TITULAR', PCA_PLT, PCA_TDA, PCA_TAM, PCA_MAS, PCA_OBL
, (max(pca_nor) over (partition by pca_pro order by pca_pro))+1 PCA_NOR
, PCA_ROT||' TITULAR', PCA_ACTIVO, PCA_DESPLEGABLE, PCA_OCULTO, PCA_BLOQ, PLAZO_AVISO, PERIODO_PLAZO, PCA_GROUP, PCA_POS_X, PCA_POS_Y
from e_pca 
where (pca_cod ='AVISOSMS' OR PCA_COD='AVISOEMAIL')
AND PCA_PRO NOT IN(SELECT DISTINCT PCA_PRO FROM E_PCA  WHERE (pca_cod='AVISOEMAILTIT' OR PCA_COD='AVISOSMSTIT'))
;
COMMIT;

-- Crear campos para guardar campos ID Cuenta Interesado: Titular / Representante

INSERT INTO E_PCA --(PCA_MUN, PCA_PRO, PCA_COD, PCA_DES, PCA_PLT, PCA_TDA, PCA_TAM, PCA_MAS, PCA_OBL, PCA_NOR, PCA_ROT, PCA_ACTIVO, PCA_DESPLEGABLE, PCA_OCULTO, PCA_BLOQ, PLAZO_AVISO, PERIODO_PLAZO, PCA_GROUP, PCA_POS_X, PCA_POS_Y)
select 
--* 
PCA_MUN, PCA_PRO
, case when PCA_COD like '%TIT' then 'AVISOIDCTAINTETIT' ELSE 'AVISOIDCTAINTE' END PCA_COD
, case when PCA_COD like '%TIT' then 'ID CUENTA INTERESADO | REPRESENTANTE ' ELSE 'ID CUENTA INTERESADO | TTULAR ' END PCA_DES
, PCA_PLT, PCA_TDA
, 50 PCA_TAM
, PCA_MAS, PCA_OBL
,(max(pca_nor) over (partition by pca_pro order by pca_pro))+1 PCA_NOR
, case when PCA_COD like '%TIT' then 'ID CUENTA INTERESADO | REPRESENTANTE ' ELSE 'ID CUENTA INTERESADO | TTULAR ' END PCA_ROT
, PCA_ACTIVO, PCA_DESPLEGABLE, PCA_OCULTO, PCA_BLOQ, PLAZO_AVISO, PERIODO_PLAZO, PCA_GROUP
,NULL PCA_POS_X, NULL PCA_POS_Y
from e_pca 
where pca_cod like'AVISOEMAIL%' 
;
