CREATE TABLE "MELANBIDE43_KONTUJOB"
(
	"ID" NUMBER(8, 0) PRIMARY KEY,
	"EJE_ANOTACION" NUMBER(4,0) NOT NULL, 
	"NUM_ANOTACION" NUMBER(6,0) NOT NULL, 
	"NUM_EXPEDIENTE" VARCHAR2(30 BYTE) NULL,
	"FECHA" DATE NOT NULL,
	"RESULTADO" VARCHAR2(2 BYTE) NOT NULL,
	"DESC_ERROR" VARCHAR2(4000 BYTE)
);

COMMENT ON COLUMN "MELANBIDE43_KONTUJOB"."ID" IS 'Identificador unico de cada registro de la tabla.';
COMMENT ON COLUMN "MELANBIDE43_KONTUJOB"."EJE_ANOTACION" IS 'Ejercicio de la anotación procesada.';
COMMENT ON COLUMN "MELANBIDE43_KONTUJOB"."NUM_ANOTACION" IS 'Número de la anotación procesada.';
COMMENT ON COLUMN "MELANBIDE43_KONTUJOB"."NUM_EXPEDIENTE" IS 'Número del expediente creado';
COMMENT ON COLUMN "MELANBIDE43_KONTUJOB"."FECHA" IS 'Fecha en la que se procesa la anotación.';
COMMENT ON COLUMN "MELANBIDE43_KONTUJOB"."RESULTADO" IS 'Resultado de la ejecución del job.';
COMMENT ON COLUMN "MELANBIDE43_KONTUJOB"."DESC_ERROR" IS 'Descripción.';
COMMENT ON TABLE "MELANBIDE43_KONTUJOB" IS 'Registra cada procesamiento de anotación realizado por el Job de gestión automática de KONTU.'; 

ALTER TABLE MELANBIDE43_KONTUJOB
ADD CONSTRAINT CK_RESULTADO_VALORES
CHECK (RESULTADO IN ('OK', 'KO'));

CREATE SEQUENCE MELANBIDE43_KONTUJOB_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

ALTER TABLE MELANBIDE43_KONTUJOB
MODIFY ID NUMBER(8, 0) DEFAULT MELANBIDE43_KONTUJOB_SEQ.NEXTVAL;
  
CREATE INDEX IDX_MELANBIDE43_KONTUJOB_EXP
ON MELANBIDE43_KONTUJOB (NUM_EXPEDIENTE);

CREATE INDEX IDX_MELANBIDE43_KONTUJOB_ANOT
ON MELANBIDE43_KONTUJOB (EJE_ANOTACION, NUM_ANOTACION);

CREATE INDEX IDX_MELANBIDE43_KONTUJOB_FECHA
ON MELANBIDE43_KONTUJOB (FECHA);