ori.nuevaUbicacion.listaProvincias=01,20,48
ce.nuevaUbicacion.listaProvincias=01,20,48
codEspecialidadOtros=6
minAnosValTray=2
maxAnosValTray=12

####### C\u00d3DIGOS DE MUNICIPIOS QUE DEBEN APARECER EN OTRAS PROVINCIAS QUE NO SON LAS QUE APARECEN EN BD #######
####### (C\u00d3DIGOS SEPARADOS POR ',' CON FORMATO 'PPMM', DONDE 'PP' ES C\u00d3DIGO DE PROV. Y 'MM' C\u00d3DIGO DE MUN.) #######

## \u00c1LAVA ##
CODIGOS_MUN_ANADIDOS_1=4874
CODIGOS_MUN_EXCLUIDOS_1=
## VIZCAYA ##
CODIGOS_MUN_ANADIDOS_48=2030
CODIGOS_MUN_EXCLUIDOS_48=4874
## GUIP\u00daZCOA ##
CODIGOS_MUN_ANADIDOS_20=
CODIGOS_MUN_EXCLUIDOS_20=2030