##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE36/LISTA_OPERACIONES_DISPONIBLES=cargaDatosCONCMContacto
1/MODULO_INTEGRACION/MELANBIDE36/LISTA_OPERACIONES_DISPONIBLES=cargaDatosCONCMContacto

##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE36

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE36/DESCRIPCION_MODULO = Lista de expedientes relacionados y n\u00famero de d\u00edas
1/MODULO_INTEGRACION/MELANBIDE36/DESCRIPCION_MODULO = Lista de expedientes relacionados y n\u00famero de d\u00edas

##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE36/CONCM/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = LISTA_EXPEDIENTES
1/MODULO_INTEGRACION/MELANBIDE36/CONCM/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = LISTA_EXPEDIENTES

##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE36/CONCM/URL_PANTALLA_EXPEDIENTE/LISTA_EXPEDIENTES = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE36&operacion=cargarListaExpedientes&tipo=0
1/MODULO_INTEGRACION/MELANBIDE36/CONCM/URL_PANTALLA_EXPEDIENTE/LISTA_EXPEDIENTES = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE36&operacion=cargarListaExpedientes&tipo=0

##################### NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE #####################
0/MODULO_INTEGRACION/MELANBIDE36/CONCM/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/LISTA_EXPEDIENTES = 
1/MODULO_INTEGRACION/MELANBIDE36/CONCM/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/LISTA_EXPEDIENTES =

#0/MODULO_INTEGRACION/MELANBIDE36/CONCM/PANTALLA_EXPEDIENTE/SALIDA = /jsp/extension/MELANBIDE36/MELANBIDE36.jsp
#1/MODULO_INTEGRACION/MELANBIDE36/CONCM/PANTALLA_EXPEDIENTE/SALIDA = /jsp/extension/MELANBIDE36/MELANBIDE36.jsp

##################### NOMBRE DE LA OPERACION DEL MODULO QUE SE ENCARGA DE ACTUALIZAR LOS DATOS DE LA PANTALLA DE EXPEDIENTE #####################
0/MODULO_INTEGRACION/MELANBIDE36/CONCM/ACTUALIZAR_PANTALLA_EXPEDIENTE/LISTA_EXPEDIENTES = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE36&operacion=cargarListaExpedientes&tipo=0
1/MODULO_INTEGRACION/MELANBIDE36/CONCM/ACTUALIZAR_PANTALLA_EXPEDIENTE/LISTA_EXPEDIENTES = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE36&operacion=cargarListaExpedientes&tipo=0

##################### NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE DE UNA RELACI\u00d3N ENTRE EXPEDIENTES #####################
0/MODULO_INTEGRACION/MELANBIDE36/CONCM/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/LISTA_EXPEDIENTES  =
1/MODULO_INTEGRACION/MELANBIDE36/CONCM/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/LISTA_EXPEDIENTES  =

##################### NOMBRES DE TABLAS #####################

#NUMERICOS


##################### NOMBRES DE SECUENCIAS #####################



##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide36.i18n.text
FICHEROS_MENSAJES = MELANBIDE36_TEXT_1;MELANBIDE36_TEXT_4

#A\u00d1O MINIMO VISIBLE EN PESTA\u00d1A EXPEDIENTES RELACIONADOS
ANO_MIN_VISION_EXP_REL=2011