# M\u00e9todos del m\u00f3dulo que se utilizan para configurar el m\u00f3dulo en la pesta\u00f1a "Conf.SW"
0/MODULO_INTEGRACION/MELANBIDE53/LISTA_OPERACIONES_DISPONIBLES=
1/MODULO_INTEGRACION/MELANBIDE53/LISTA_OPERACIONES_DISPONIBLES=
# NOMBRE DEL M\u00d3DULO QUE SE MUESTRA JUNTO CON EL NOMBRE DE LA OPERACI\u00d3N; A LA HORA DE SELECCIONAR UNA OPERACI\u00d3N QUE SE ASOCIAR\u00c1 A UN TR\u00c1MITE
# FORMATO: [COD_ORGANIZACION]/MODULO_INTEGRACION/[NOMBRE_MODULO]/NOMBRE_MODULO
0/MODULO_INTEGRACION/MELANBIDE53/DESCRIPCION_MODULO = MODULO CONTROL GESTION DE ERRORES
1/MODULO_INTEGRACION/MELANBIDE53/DESCRIPCION_MODULO = MODULO CONTROL GESTION DE ERRORES

NOMBRE_MODULO = MELANBIDE53

#Organizaci\u00f3n (como esto est\u00e1 en men\u00fa dentro de administrdor general, coge siempre organizaci\u00f3n 0)
#DESA
COD_ORGANIZACION=0

#PRE, PRO
COD_ORGANIZACION=1

### Definicion de tablas del Modulo
TABLA_MELANBIDE53_REG_ERR=REG_ERR
TABLA_MELANBIDE53_IDEN_ERR=IDEN_ERR
TABLA_MELANBIDE53_ESTADISTICAS=ESTADISTICAS
TABLA_MELANBIDE53_ESTADISTICAS_HIST=ESTADISTICAS_HIST

### Definicion de campos de tablas
CAMPO_FECHA_ERROR_REG_ERR=REG_ERR_FEC_ERROR
CAMPO_FECHA_REVISION_REG_ERR=REG_ERR_FEC_REV


### OTROS
CARACTERES_ESPECIALES=&'<>|^\\%
## OJO  PONER EN EL MISMO ORDEN CARACTER Y ESCAPE
CARACTERES_ESPECIALES_XML=",',<,>,&
ESCAPE_CARACTERES_ESPECIALES_XML=&quot;,&apos;,&lt;,&gt;,&amp;

UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide53.i18n.text
FICHEROS_MENSAJES = MELANBIDE53_TEXT_1;MELANBIDE53_TEXT_4

## 0 o Vacio todas las filas de errores al cargar la pagina.
NUMERO_MAX_LINEAS_TABLAINICIAL=0
# Numero de linea por pagina - paginacion
NUMERO_LINEAS_PAGINA=15