##################### CONFIGURACI\u00d3N DE OPERACIONES #####################
0/MODULO_INTEGRACION/MELANBIDE15/LISTA_OPERACIONES_DISPONIBLES=
1/MODULO_INTEGRACION/MELANBIDE15/LISTA_OPERACIONES_DISPONIBLES=

##################### INFORMACI\u00d3N GENERAL DEL M\u00d3DULO #####################
NOMBRE_MODULO=MELANBIDE15
0/MODULO_INTEGRACION/MELANBIDE15/DESCRIPCION_MODULO=M\u00d3DULO DE COLECTIVOS DE ATENCI\u00d3N PRIORITARIA - CATP
1/MODULO_INTEGRACION/MELANBIDE15/DESCRIPCION_MODULO=M\u00d3DULO DE COLECTIVOS DE ATENCI\u00d3N PRIORITARIA - CATP

##################### CONFIGURACI\u00d3N DE PANTALLAS #####################
# Nombres de pantallas
0/MODULO_INTEGRACION/MELANBIDE15/CATP/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS=PARTICIPANTES
1/MODULO_INTEGRACION/MELANBIDE15/CATP/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS=PARTICIPANTES

# URLs de pantallas
0/MODULO_INTEGRACION/MELANBIDE15/CATP/URL_PANTALLA_EXPEDIENTE/PARTICIPANTES=/PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE15&operacion=cargarPantallaCATP&tipo=0
1/MODULO_INTEGRACION/MELANBIDE15/CATP/URL_PANTALLA_EXPEDIENTE/PARTICIPANTES=/PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE15&operacion=cargarPantallaCATP&tipo=0

##################### TABLAS Y SECUENCIAS #####################
# Tablas del m\u00f3dulo
MELANBIDE15_CONTRATACION=MELANBIDE15_CONTRATACION
MELANBIDE15_FORMACION=MELANBIDE15_FORMACION
MELANBIDE15_IDENTIDAD=MELANBIDE15_IDENTIDAD
MELANBIDE15_ORIENTACION=MELANBIDE15_ORIENTACION

TABLA_VALORES_DESPLEGABLES=E_DES_VAL
TABLA_CODIGOS_DESPLEGABLES=E_DES

# Secuencias
SEQ_M15_CONTRATACION=SEQ_M15_CONTRATACION
SEQ_M15_FORMACION=SEQ_M15_FORMACION
SEQ_M15_IDENTIDAD=SEQ_M15_IDENTIDAD
SEQ_M15_ORIENTACION=SEQ_M15_ORIENTACION

##################### CONFIGURACI\u00d3N DE DESPLEGABLES #####################
COD_DES_DTSV=DTSV
COD_DES_TCPT=TCPT
COD_DES_SEXO=SEXO
COD_DES_DNINIE=DNINIE
COD_DES_BOOL=BOOL


##################### CONFIGURACI\u00d3N DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES=es.altia.flexia.integracion.moduloexterno.melanbide15.i18n.text
FICHEROS_MENSAJES=MELANBIDE15_TEXT_1;MELANBIDE15_TEXT_4

# EL caracter es pipeline hay que escaparlo porque es un caracter especial para hacer condicion or en regex
BARRA_SEPARADORA_IDIOMA_DESPLEGABLES=\\Q|\\E