##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE84/LISTA_OPERACIONES_DISPONIBLES=
1/MODULO_INTEGRACION/MELANBIDE84/LISTA_OPERACIONES_DISPONIBLES=

##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE84

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE84/DESCRIPCION_MODULO = MODULO PERSONAS EMPRENDEDORAS - ENTAP
1/MODULO_INTEGRACION/MELANBIDE84/DESCRIPCION_MODULO = MODULO PERSONAS EMPRENDEDORAS - ENTAP

##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE84/ENTAP/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = PERSONAS
1/MODULO_INTEGRACION/MELANBIDE84/ENTAP/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = PERSONAS

##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE84/ENTAP/URL_PANTALLA_EXPEDIENTE/PERSONAS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE84&operacion=cargarPantallaPrincipal&tipo=0
1/MODULO_INTEGRACION/MELANBIDE84/ENTAP/URL_PANTALLA_EXPEDIENTE/PERSONAS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE84&operacion=cargarPantallaPrincipal&tipo=0

##################### TABLAS  #####################
MELANBIDE84_PERSONAS=MELANBIDE84_PERSONAS
TABLA_CODIGOS_DESPLEGABLES=E_DES
TABLA_VALORES_DESPLEGABLES=E_DES_VAL
TABLA_DESPLEGABLES_EXPEDIENTE=E_TDE
TABLA_FECHAS_EXPEDIENTE=E_TFE
TABLA_TERCEROS=T_TER
TABLA_TERCEROS_HIST=T_HTE
TABLA_TERCERO_EXPEDIENTE=E_EXT
TABLA_DOMICILIO=T_DNN
TABLA_DOMICILIO_TERCERO=T_DOT
TABLA_FECHAS_TERCEROS=T_CAMPOS_FECHA
TABLA_DESPLE_TERCEROS=T_CAMPOS_DESPLEGABLE
TABLA_T_VIA=T_VIA
TABLA_E_EXP=E_EXP
TABLA_E_EXR=E_EXR
TABLA_R_RES=R_RES

##################### C\u00d3DIGOS DESPLEGABLES  #####################
COD_DES_NAPE=NAPE
COD_DES_APEX=APEX
COD_DES_SEXO=SEXO
COD_DES_ENTI=ECAP

##################### CAMPOS SUPLEMENTARIOS  #####################
COD_SEXO_TER=TSEXOTERCERO
COD_FNAC_TER=TFECNACIMIENTO
COD_NIVEL=NIVELACAD
COD_FEC_SOLICITUD=FECHAPRESENTACION
COD_FEC_INICIO=FECINICACT
COD_ENTI_COLAB=ENTCOLAB

## TRAMITES
# APEA/APEI
COD_TRAM_INICIO=1
# ENTAP
##13 en pre y pro
CODIGO_TRAMITE110=55
#CODIGO_TRAMITE110=13

### SECUENCIA ID DE TABLA PLANTILLA
SEQ_MELANBIDE84_PERSONAS=SEQ_MELANBIDE84_PERSONAS

##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide84.i18n.text
FICHEROS_MENSAJES = MELANBIDE84_TEXT_1;MELANBIDE84_TEXT_4

# EL caracter es pipeline hay que escaparlo porque es un caracter especial para hacer condicion or en regex
BARRA_SEPARADORA_IDIOMA=\\Q|\\E

##### URL_WS_TRAMITACION #########################################################################
## desa
#URL_WS_TRAMITACION=http://10.168.212.21:7081/WSTramitacion/services/WSTramitacionPort?wsdl
URL_WS_TRAMITACION=http://integ.serv.des.lanbide.lan/WSTramitacion/services/WSTramitacionPort?wsdl

## pre
#URL_WS_TRAMITACION=http://10.168.212.161:17003/WSTramitacion/services/WSTramitacionPort?wsdl
#URL_WS_TRAMITACION=http://integ.serv.pru.lanbide.lan/WSTramitacion/services/WSTramitacionPort?wsdl

## pro
#URL_WS_TRAMITACION=http://integ.serv.lanbide.lan/WSTramitacion/services/WSTramitacionPort?wsdl