##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE87/LISTA_OPERACIONES_DISPONIBLES=
1/MODULO_INTEGRACION/MELANBIDE87/LISTA_OPERACIONES_DISPONIBLES=

##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE87

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE87/DESCRIPCION_MODULO = MODULO COLECTIVOS VULNERABLES - COLVU
1/MODULO_INTEGRACION/MELANBIDE87/DESCRIPCION_MODULO = MODULO COLECTIVOS VULNERABLES - COLVU

##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE87/COLVU/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = INSTALACIONES
1/MODULO_INTEGRACION/MELANBIDE87/COLVU/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = INSTALACIONES

##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE87/COLVU/URL_PANTALLA_EXPEDIENTE/INSTALACIONES = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE87&operacion=cargarPantallaPrincipal&tipo=0
1/MODULO_INTEGRACION/MELANBIDE87/COLVU/URL_PANTALLA_EXPEDIENTE/INSTALACIONES = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE87&operacion=cargarPantallaPrincipal&tipo=0

##################### TABLAS  #####################
MELANBIDE87_INSTALACIONES=MELANBIDE87_INSTALACIONES
TABLA_VALORES_DESPLEGABLES=E_DES_VAL

##################### C\u00d3DIGOS DESPLEGABLES  #####################
COD_DES_TINS=TINS

##################### CAMPOS SUPLEMENTARIOS  #####################


### SECUENCIA ID DE TABLA PLANTILLA
SEQ_MELANBIDE87_INSTALACIONES=SEQ_MELANBIDE87_INSTALACIONES

##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide87.i18n.text
FICHEROS_MENSAJES = MELANBIDE87_TEXT_1;MELANBIDE87_TEXT_4

# EL caracter es pipeline hay que escaparlo porque es un caracter especial para hacer condicion or en regex
BARRA_SEPARADORA_IDIOMA=\\Q|\\E