##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE08/LISTA_OPERACIONES_DISPONIBLES=
1/MODULO_INTEGRACION/MELANBIDE08/LISTA_OPERACIONES_DISPONIBLES=

##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE08

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE08/DESCRIPCION_MODULO = M\u00f3dulo Consulta de estado de firma de documentos Portafirmas
1/MODULO_INTEGRACION/MELANBIDE08/DESCRIPCION_MODULO = M\u00f3dulo Consulta de estado de firma de documentos Portafirmas

##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide08.i18n.text
FICHEROS_MENSAJES = MELANBIDE_08_TEXT_1;MELANBIDE_08_TEXT_4


##################### TABLAS DEL M\u00d3DULO #####################

TABLA_DOCUMENTOS_NOTIFICADOS=ADJUNTO_NOTIFICACION
TABLA_DOCUMENTOS_ENVIADOS_FIRMAR=E_CRD
TABLA_LOG_JOB=MELANBIDE08_LOG_JOB

