
#DESARROLLO
#SERVIDOR = flexia1

#PRE
SERVIDOR = paprergi1_flexia1

#PRO
#SERVIDOR = pargi1_flexia1

TRAMITE_INCUMPLIMIENTO = 2
CODIGO_DOC_TRAMITE=4
COD_ORG=0
DOS_ENTORNOS=FALSE

#LOCAL, DESA
CODIGO_TRAMITE_REVISION_GRABACION_DATOS = 2
#PRO y PRE
#CODIGO_TRAMITE_REVISION_GRABACION_DATOS = 1

#LOCAL, DESA
CODIGO_TRAMITE_ARCHIVO = 8
#PRE
#CODIGO_TRAMITE_ARCHIVO = 6
#PRO
#CODIGO_TRAMITE_ARCHIVO = 11

#LOCAL, DESA, PRE?, PRO
CODIGO_CAMPO_RESPUESTA1 = RESUELTA1
CODIGO_CAMPO_RESPUESTA2 = RESUELTA2
CODIGO_CAMPO_RESPUESTA3 = RESUELTA3
CODIGO_CAMPO_RESPUESTA4 = RESUELTA4
CODIGO_CAMPO_TIPOLOGIA=TIPO
CODIGO_CAMPO_CANAL_RECEPCION=CANALQUEJASUGERENCIA
CODIGO_CAMPO_IDIOMA=IDIOMARESPUESTA
CODIGO_CAMPO_GENERO=GENERO
CODIGO_CAMPO_TIPO_INTERLOC=TIPOINTERLOCUTOR
CODIGO_CAMPO_ESTADO_CIERRE=NIVRESPQUEJA1
CODIGO_CAMPO_UNIDAD_CAUSANTE=UNIDADCAUSANTE

##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE57/QUEJA/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = DATOSSUPL_AREAS
1/MODULO_INTEGRACION/MELANBIDE57/QUEJA/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = DATOSSUPL_AREAS


##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE57/QUEJA/URL_PANTALLA_EXPEDIENTE/DATOSSUPL_AREAS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE57&operacion=datosSuplAreas&tipo=0
1/MODULO_INTEGRACION/MELANBIDE57/QUEJA/URL_PANTALLA_EXPEDIENTE/DATOSSUPL_AREAS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE57&operacion=datosSuplAreas&tipo=0


0/MODULO_INTEGRACION/MELANBIDE57/QUEJA/PANTALLA_EXPEDIENTE/SALIDA = /jsp/extension/MELANBIDE57/melanbide57.jsp
1/MODULO_INTEGRACION/MELANBIDE57/QUEJA/PANTALLA_EXPEDIENTE/SALIDA = /jsp/extension/MELANBIDE57/melanbide57.jsp



UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide57.i18n.text
FICHEROS_MENSAJES = MELANBIDE57_TEXT_1;MELANBIDE57_TEXT_4