##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE70/LISTA_OPERACIONES_DISPONIBLES=actualizarDatosSuplementariosAPEI
1/MODULO_INTEGRACION/MELANBIDE70/LISTA_OPERACIONES_DISPONIBLES=actualizarDatosSuplementariosAPEI

##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE70

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE70/DESCRIPCION_MODULO = Datos suplementarios APEI
1/MODULO_INTEGRACION/MELANBIDE70/DESCRIPCION_MODULO = Datos suplementarios APEI

##################### NOMBRES DE TABLAS #####################


##################### NOMBRES DE SECUENCIAS #####################


##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide70.i18n.text
FICHEROS_MENSAJES = MELANBIDE70_TEXT_1;MELANBIDE70_TEXT_4

###### ERRORES PERSONALIZADOS DE LA OPERACI\u00d3N actualizarDatosSuplementariosAPEI 
0/MODULO_INTEGRACION/actualizarDatosSuplementariosAPEI/MENSAJE_ERROR/1= ERROR_GENERICO
1/MODULO_INTEGRACION/actualizarDatosSuplementariosAPEI/MENSAJE_ERROR/1= ERROR_GENERICO
0/MODULO_INTEGRACION/actualizarDatosSuplementariosAPEI/MENSAJE_ERROR/2= ERROR_CONEXIONBD
1/MODULO_INTEGRACION/actualizarDatosSuplementariosAPEI/MENSAJE_ERROR/2= ERROR_CONEXIONBD
0/MODULO_INTEGRACION/actualizarDatosSuplementariosAPEI/MENSAJE_ERROR/3= ERROR_DATOSEXPEDIENTE_TERCERO
1/MODULO_INTEGRACION/actualizarDatosSuplementariosAPEI/MENSAJE_ERROR/3= ERROR_DATOSEXPEDIENTE_TERCERO
0/MODULO_INTEGRACION/actualizarDatosSuplementariosAPEI/MENSAJE_ERROR/4= ERROR_DATOSEXPEDIENTE_TERCERO_INCOMPLETO
1/MODULO_INTEGRACION/actualizarDatosSuplementariosAPEI/MENSAJE_ERROR/4= ERROR_DATOSEXPEDIENTE_TERCERO_INCOMPLETO

ERROR_GENERICO_1 = Ha ocurrido un error gen\u00e9rico
ERROR_GENERICO_4 = Ha ocurrido un error gen\u00e9rico

ERROR_CONEXIONBD_1 = No se ha podido obtener una conexi\u00f3n a la BBDD
ERROR_CONEXIONBD_4 = No se ha podido obtener una conexi\u00f3n a la BBDD

ERROR_DATOSEXPEDIENTE_TERCERO_1 = Error al obtener datos del expediente y tercero
ERROR_DATOSEXPEDIENTE_TERCERO_4 = Error al obtener datos del expediente y tercero

ERROR_DATOSEXPEDIENTE_TERCERO_INCOMPLETO_1 = Datos del expediente y/o tercero incompletos
ERROR_DATOSEXPEDIENTE_TERCERO_INCOMPLETO_4 = Datos del expediente y/o tercero incompletos

###### C\u00f3digos de los campos suplementarios que necesita consultar y/o grabar y su tipo ######
0/MODULO_INTEGRACION/MELANBIDE70/APEI/CAMPO_SUP/CODIGO/SUBV = IMPSUBVENCIONG
1/MODULO_INTEGRACION/MELANBIDE70/APEI/CAMPO_SUP/CODIGO/SUBV = IMPSUBVENCIONG
0/MODULO_INTEGRACION/MELANBIDE70/APEI/CAMPO_SUP/TIPO/SUBV = 1
1/MODULO_INTEGRACION/MELANBIDE70/APEI/CAMPO_SUP/TIPO/SUBV = 1