##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE44/LISTA_OPERACIONES_DISPONIBLES=
1/MODULO_INTEGRACION/MELANBIDE44/LISTA_OPERACIONES_DISPONIBLES=

##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE44

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE44/DESCRIPCION_MODULO = M\u00f3dulo de Procedimiento Empleo con Apoyo  Discapacitados en mercado ordinario - ECA
1/MODULO_INTEGRACION/MELANBIDE44/DESCRIPCION_MODULO = M\u00f3dulo de Procedimiento Empleo con Apoyo  Discapacitados en mercado ordinario - ECA

##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE44/ECA14/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = SOLICITUD;JUSTIFICACION;RESUMEN
1/MODULO_INTEGRACION/MELANBIDE44/ECA14/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = SOLICITUD;JUSTIFICACION;RESUMEN


##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE44/ECA14/URL_PANTALLA_EXPEDIENTE/SOLICITUD = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE44&operacion=cargarPantallaSolicitudPrincipal&tipo=0
1/MODULO_INTEGRACION/MELANBIDE44/ECA14/URL_PANTALLA_EXPEDIENTE/SOLICITUD = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE44&operacion=cargarPantallaSolicitudPrincipal&tipo=0
0/MODULO_INTEGRACION/MELANBIDE44/ECA14/URL_PANTALLA_EXPEDIENTE/JUSTIFICACION = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE44&operacion=cargarPantallaJustificacion&tipo=0
1/MODULO_INTEGRACION/MELANBIDE44/ECA14/URL_PANTALLA_EXPEDIENTE/JUSTIFICACION = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE44&operacion=cargarPantallaJustificacion&tipo=0
0/MODULO_INTEGRACION/MELANBIDE44/ECA14/URL_PANTALLA_EXPEDIENTE/RESUMEN = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE44&operacion=cargarPantallaResumen&tipo=0
1/MODULO_INTEGRACION/MELANBIDE44/ECA14/URL_PANTALLA_EXPEDIENTE/RESUMEN = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE44&operacion=cargarPantallaResumen&tipo=0

##################### NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE #####################
0/MODULO_INTEGRACION/MELANBIDE44/ECA14/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/SOLICITUD =
1/MODULO_INTEGRACION/MELANBIDE44/ECA14/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/SOLICITUD =

#0/MODULO_INTEGRACION/MELANBIDE44/ECA/PANTALLA_EXPEDIENTE/SALIDA = /jsp/extension/MELANBIDE44/MELANBIDE44.jsp
#1/MODULO_INTEGRACION/MELANBIDE44/ECA/PANTALLA_EXPEDIENTE/SALIDA = /jsp/extension/MELANBIDE44/MELANBIDE44.jsp

##################### NOMBRE DE LA OPERACION DEL MODULO QUE SE ENCARGA DE ACTUALIZAR LOS DATOS DE LA PANTALLA DE EXPEDIENTE #####################
0/MODULO_INTEGRACION/MELANBIDE44/ECA14/ACTUALIZAR_PANTALLA_EXPEDIENTE/SOLICITUD = 
1/MODULO_INTEGRACION/MELANBIDE44/ECA14/ACTUALIZAR_PANTALLA_EXPEDIENTE/SOLICITUD = 

##################### NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE DE UNA RELACI\u00d3N ENTRE EXPEDIENTES #####################
0/MODULO_INTEGRACION/MELANBIDE44/ECA14/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/SOLICITUD  =
1/MODULO_INTEGRACION/MELANBIDE44/ECA14/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/SOLICITUD  =

##################### NOMBRES DE TABLAS #####################
TABLA_ECA_SOLICITUD=ECA14_SOLICITUD
TABLA_ECA_SOL_PREPARADORES=ECA14_SOL_PREPARADORES
TABLA_ECA_SOL_PROSPECTORES=ECA14_SOL_PROSPECTORES
TABLA_ECA_JUS_PREPARADORES=ECA14_JUS_PREPARADORES
TABLA_ECA_JUS_PROSPECTORES=ECA14_JUS_PROSPECTORES
TABLA_ECA_SOL_VALORACION=ECA14_SOL_VALORACION
TABLA_ECA_CONFIGURACION=ECA14_CONFIGURACION
TABLA_ECA_SEG_PREPARADORES=ECA14_SEG_PREPARADORES
TABLA_ECA_VIS_PROSPECTORES=ECA14_VIS_PROSPECTORES
TABLA_ECA_TIPODISCAPACIDAD = ECA14_TIPODISCAPACIDAD
TABLA_ECA_TIPOCONTRATO = ECA14_TIPOCONTRATO
TABLA_ECA_DISCAPGRAVEDAD = ECA14_DISCAPGRAVEDAD
TABLA_ECA_SECTORACTIVIDAD = ECA14_SECTORACT
TABLA_PROVINCIAS = T_PRV
TABLA_ECA_AUDITORIA=ECA14_AUDITORIA
TABLA_USUARIOS=A_USU
TABLA_ECA_CUMPLELISMI = ECA14_CUMPLELISMI
TABLA_ECA_RESULTADO = ECA14_RESULTADO
TABLA_ECA_RES_PROSPECTORES=ECA14_RES_PROSPECTORES
TABLA_ECA_RES_PREPARADORES=ECA14_RES_PREPARADORES
TABLA_ECA_RESUMEN=ECA14_RESUMEN


##################### NOMBRES DE SECUENCIAS #####################
SEQ_ECA_SOLICITUD=SEQ_ECA14_SOLICITUD
SEQ_ECA_SOL_PREPARADORES=SEQ_ECA14_SOL_PREPARADORES
SEQ_ECA_SOL_PROSPECTORES=SEQ_ECA14_SOL_PROSPECTORES
SEQ_ECA_SOL_VALORACION=SEQ_ECA14_SOL_VALORACION
SEQ_ECA_JUS_PREPARADORES=SEQ_ECA14_JUS_PREPARADORES
SEQ_ECA_JUS_PROSPECTORES=SEQ_ECA14_JUS_PROSPECTORES
SEQ_ECA_RESUMEN=SEQ_ECA14_RESUMEN


##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide44.i18n.text
FICHEROS_MENSAJES = MELANBIDE44_TEXT_1;MELANBIDE44_TEXT_4