##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE52/LISTA_OPERACIONES_DISPONIBLES=bajaCentroConEspecialidades
1/MODULO_INTEGRACION/MELANBIDE52/LISTA_OPERACIONES_DISPONIBLES=


##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE52

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE52/DESCRIPCION_MODULO = M\u00f3dulo MELANBIDE52 - Procedimiento Baja de centros formativos en Registro CF
1/MODULO_INTEGRACION/MELANBIDE52/DESCRIPCION_MODULO = M\u00f3dulo MELANBIDE52 - Procedimiento Baja de centros formativos en Registro CF

##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE52/RGCFB/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CENTROS
1/MODULO_INTEGRACION/MELANBIDE52/RGCFB/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CENTROS


##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE52/RGCFB/URL_PANTALLA_EXPEDIENTE/CENTROS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE52&operacion=cargarPantallaPrincipal&tipo=0
1/MODULO_INTEGRACION/MELANBIDE52/RGCFB/URL_PANTALLA_EXPEDIENTE/CENTROS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE52&operacion=cargarPantallaPrincipal&tipo=0


##################### NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE #####################
0/MODULO_INTEGRACION/MELANBIDE52/RGCFB/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/CENTROS =
1/MODULO_INTEGRACION/MELANBIDE52/RGCFB/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/CENTROS =

0/MODULO_INTEGRACION/MELANBIDE52/RGCFB/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR =
1/MODULO_INTEGRACION/MELANBIDE52/RGCFB/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR =

0/MODULO_INTEGRACION/MELANBIDE52/RGCFB/PANTALLA_EXPEDIENTE/SALIDA = /jsp/extension/melanbide52/seleccionUbicacionCentro.jsp
1/MODULO_INTEGRACION/MELANBIDE52/RGCFB/PANTALLA_EXPEDIENTE/SALIDA = /jsp/extension/melanbide52/seleccionUbicacionCentro.jsp

##################### NOMBRE DE LA OPERACION DEL MODULO QUE SE ENCARGA DE ACTUALIZAR LOS DATOS DE LA PANTALLA DE EXPEDIENTE #####################
0/MODULO_INTEGRACION/MELANBIDE52/RGCFB/ACTUALIZAR_PANTALLA_EXPEDIENTE/CENTROS = 
1/MODULO_INTEGRACION/MELANBIDE52/RGCFB/ACTUALIZAR_PANTALLA_EXPEDIENTE/CENTROS = 


##################### NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE DE UNA RELACI\u00d3N ENTRE EXPEDIENTES #####################
0/MODULO_INTEGRACION/MELANBIDE52/CENTROS/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/CENTROS  =
1/MODULO_INTEGRACION/MELANBIDE52/CENTROS/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/CENTROS  =


##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide52.i18n.text
FICHEROS_MENSAJES = MELANBIDE52_TEXT_1;MELANBIDE52_TEXT_4


# URL SERVICIO WEB DE ALTA DE CENTROS Y ESPECIALIDADES
## URL_WS_REGISTROCENTROS = http://10.168.212.21:18007/ikaslanWS/WSRegistroCentrosFormacion?wsdl
URL_WS_REGISTROCENTROS = http://integ.serv.des.lanbide.lan/ikaslanWS/WSRegistroCentrosFormacion?wsdl

############ CODIGOS DE CAMPOS SUPLEMENTARIOS #######
# Codigo campo codCentro definido a nivel del tr\u00e1mite "CONSULTA Y SELECCION DE CENTRO"
CODIGO_CAMPO_CODCENTRO = CODCENTRO
# Codigo campo codUbicacion definido a nivel del tr\u00e1mite "CONSULTA Y SELECCION DE CENTRO"
CODIGO_CAMPO_CODUBICACION = CODUBICACION

# C\u00f3digo campo suplementario de tr\u00e1mite en el que se almacenar\u00e1 el n\u00famero de censo del centro devuelto
CODIGO_CAMPO_NUMCENSO_CENTRO = NUMREGCENTRO

# C\u00f3digo del campo suplementario que contiene la fecha de resoluci\u00f3n
CODIGO_CAMPO_TRAMITE_FECHA_RESOLUCION = FECRESOL

# Codigo del tr\u00e1mite NOTIFICACION RESOLUCION BAJA del que se lee el valor del campo fecha de resoluci\u00f3n
CODIGO_TRAMITE_NOTIFICACION_RESOLUCION_BAJA = 1


###### ERRORES PERSONALIZADOS DE LA OPERACI\u00d3N altaCentroConEspecialidades 
0/MODULO_INTEGRACION/bajaCentroConEspecialidades/MENSAJE_ERROR/1= ERROR_PROPIEDADES_ARCHIVO_CONFIGURACION
0/MODULO_INTEGRACION/bajaCentroConEspecialidades/MENSAJE_ERROR/2= ERROR_PROPIEDADES_ARCHIVO_CONFIGURACION_SIN_VALOR
0/MODULO_INTEGRACION/bajaCentroConEspecialidades/MENSAJE_ERROR/3= ERROR_CONEXION_SERVICIO_WEB_REGISTRO_CENTROS
0/MODULO_INTEGRACION/bajaCentroConEspecialidades/MENSAJE_ERROR/4= ERROR_OBTENER_FECHA_RESOLUCION
0/MODULO_INTEGRACION/bajaCentroConEspecialidades/MENSAJE_ERROR/5= ERROR_LLAMADA_SERVICIO_WEB
0/MODULO_INTEGRACION/bajaCentroConEspecialidades/MENSAJE_ERROR/6= ERROR_DEVUELTO_SERVICIO_WEB
0/MODULO_INTEGRACION/bajaCentroConEspecialidades/MENSAJE_ERROR/7= ERROR_TECNICO
0/MODULO_INTEGRACION/bajaCentroConEspecialidades/MENSAJE_ERROR/8= ERROR_OBTENER_NUM_CENSO_CENTRO


ERROR_PROPIEDADES_ARCHIVO_CONFIGURACION_1 = Error al recuperar propiedades de configuraci\u00f3n del fichero de configuraci\u00f3n del modulo
ERROR_PROPIEDADES_ARCHIVO_CONFIGURACION_4 = Error al recuperar propiedades de configuraci\u00f3n del fichero de configuraci\u00f3n del modulo

ERROR_PROPIEDADES_ARCHIVO_CONFIGURACION_SIN_VALOR_1 = Determinadas propiedades del fichero de configuraci\u00f3n est\u00e1n vac\u00edas y no se puede dar de baja el centro
ERROR_PROPIEDADES_ARCHIVO_CONFIGURACION_SIN_VALOR_4 = Determinadas propiedades del fichero de configuraci\u00f3n est\u00e1n vac\u00edas y no se puede dar de baja el centro

ERROR_CONEXION_SERVICIO_WEB_REGISTRO_CENTROS_1 = Error al establecer conexi\u00f3n con el servicio web de registro de centros de formacion
ERROR_CONEXION_SERVICIO_WEB_REGISTRO_CENTROS_4 = Error al establecer conexi\u00f3n con el servicio web de registro de centros de formacion

ERROR_OBTENER_FECHA_RESOLUCION_1 = No se ha podido recuperar la fecha de resolucion
ERROR_OBTENER_FECHA_RESOLUCION_4 = No se ha podido recuperar la fecha de resolucion

ERROR_LLAMADA_SERVICIO_WEB_1 = Error al realizar la llamada a la operacion de baja de centros del servicio web de registro de centros de formacion
ERROR_LLAMADA_SERVICIO_WEB_4 = Error al realizar la llamada a la operacion de baja de centros del servicio web de registro de centros de formacion

ERROR_DEVUELTO_SERVICIO_WEB_1 = El servicio web de registro de centros de formacion lanza un error al dar de baja el centro
ERROR_DEVUELTO_SERVICIO_WEB_4 = El servicio web de registro de centros de formacion lanza un error al dar de baja el centro

ERROR_TECNICO_1 = Se ha producido un error t\u00e9cnico durante la ejecuci\u00f3n de la operaci\u00f3n
ERROR_TECNICO_4 = Se ha producido un error t\u00e9cnico durante la ejecuci\u00f3n de la operaci\u00f3n

ERROR_OBTENER_NUM_CENSO_CENTRO_1 = No se ha podido recuperar el n\u00famero de censo del centro
ERROR_OBTENER_NUM_CENSO_CENTRO_4 = No se ha podido recuperar el n\u00famero de censo del centro
