##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE16

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE16/DESCRIPCION_MODULO = LAKOF - Subvenci\u00f3n Ofertas Entidades Colaboradoras
1/MODULO_INTEGRACION/MELANBIDE16/DESCRIPCION_MODULO = LAKOF - Subvenci\u00f3n Ofertas Entidades Colaboradoras

##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE16/LAKOF/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = SUBVENCIONES
1/MODULO_INTEGRACION/MELANBIDE16/LAKOF/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = SUBVENCIONES

##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE16/LAKOF/URL_PANTALLA_EXPEDIENTE/SUBVENCIONES = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE16&operacion=cargarPantallaSubSolic&tipo=0
1/MODULO_INTEGRACION/MELANBIDE16/LAKOF/URL_PANTALLA_EXPEDIENTE/SUBVENCIONES = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE16&operacion=cargarPantallaSubSolic&tipo=0

#NUMERICOS
MELANBIDE16_SUBSOLIC=MELANBIDE16_SUBSOLIC
TABLA_VALORES_DESPLEGABLES=E_DES_VAL
##################### C\u00d3DIGOS DESPLEGABLES  #####################
#DESPLEGABLE DTSV
COD_DES_DTSV=DTSV

##################### NOMBRES DE SECUENCIAS #####################
SEQ_MELANBIDE16_SUBSOLIC=SEQ_MELANBIDE16_SUBSOLIC

##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide16.i18n.text
FICHEROS_MENSAJES = MELANBIDE16_TEXT_1;MELANBIDE16_TEXT_4

# EL caracter es pipeline hay que escaparlo porque es un caracter especial para hacer condicion or en regex
BARRA_SEPARADORA_IDIOMA_DESPLEGABLES=\\Q|\\E