# M\u00e9todos del m\u00f3dulo que se utilizan para configurar el m\u00f3dulo en la pesta\u00f1a "Conf. SW" de la definici\u00f3n del tr\u00e1mite
0/MODULO_INTEGRACION/MELANBIDE04/LISTA_OPERACIONES_DISPONIBLES = 
1/MODULO_INTEGRACION/MELANBIDE04/LISTA_OPERACIONES_DISPONIBLES = 
# NOMBRE DEL M\u00d3DULO QUE SE MUESTRA JUNTO CON EL NOMBRE DE LA OPERACI\u00d3N; A LA HORA DE SELECCIONAR UNA OPERACI\u00d3N QUE SE ASOCIAR\u00c1 A UN TR\u00c1MITE
# FORMATO: [COD_ORGANIZACION]/MODULO_INTEGRACION/[NOMBRE_MODULO]/NOMBRE_MODULO
0/MODULO_INTEGRACION/MELANBIDE04/DESCRIPCION_MODULO = M\u00d3DULO AYUDA CONTRATACI\u00d3N EMPLEADOS DE HOGAR
1/MODULO_INTEGRACION/MELANBIDE04/DESCRIPCION_MODULO = M\u00d3DULO AYUDA CONTRATACI\u00d3N EMPLEADOS DE HOGAR

##################################################################################################################################
######################                             PANTALLAS DE EXPEDIENTE EH                            #########################
##################################################################################################################################
# FORMATO: [COD_ORGANIZACION]/MODULO_INTEGRACION/[NOMBRE_MODULO]/[COD_PROCEDIMIENTO]/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS
0/MODULO_INTEGRACION/MELANBIDE04/EH/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = PANTALLA_CALCULO
1/MODULO_INTEGRACION/MELANBIDE04/EH/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = PANTALLA_CALCULO

# SE INDICA CUAL ES LA URL DE LA PANTALLA DE CONFIGURACI\u00d3N DEL M\u00d3DULO SI LA TIENE. ESTA PANTALLA SE CARGA COMO
# UNA PESTA\u00d1A EN LA DEFINICI\u00d3N DE LOS PROCEDIMIENTOS
# FORMATO: [COD_ORGANIZACION]/MODULO_INTEGRACION/[NOMBRE_MODULO]/[COD_PROCEDIMIENTO]/URL_PANTALLA_EXPEDIENTE
0/MODULO_INTEGRACION/MELANBIDE04/EH/URL_PANTALLA_EXPEDIENTE/PANTALLA_CALCULO = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE04&operacion=prepararPantallaCalculo&tipo=0
0/MODULO_INTEGRACION/MELANBIDE04/EH/PANTALLA_EXPEDIENTE/SALIDA = /jsp/extension/melanbide04/pantallaCalculo.jsp

1/MODULO_INTEGRACION/MELANBIDE04/EH/URL_PANTALLA_EXPEDIENTE/PANTALLA_CALCULO = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE04&operacion=prepararPantallaCalculo&tipo=0
1/MODULO_INTEGRACION/MELANBIDE04/EH/PANTALLA_EXPEDIENTE/SALIDA = /jsp/extension/melanbide04/pantallaCalculo.jsp

# NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE
0/MODULO_INTEGRACION/MELANBIDE04/EH/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/SELECCION_CERTIFICADO =
1/MODULO_INTEGRACION/MELANBIDE04/EH/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/SELECCION_CERTIFICADO =
# NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE DE UNA RELACI\u00d3N ENTRE EXPEDIENTES
0/MODULO_INTEGRACION/MELANBIDE04/EH/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/SELECCION_CERTIFICADO  =
1/MODULO_INTEGRACION/MELANBIDE04/EH/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/SELECCION_CERTIFICADO  =

# Cuando se pulsa el bot\u00f3n de [Grabar] en la ficha del expediente, se puede llamar a una funci\u00f3n javascript de la pantalla del m\u00f3dulo
# que se encarga de actualizar el contenido de la pantalla
0/MODULO_INTEGRACION/MELANBIDE04/EH/ACTUALIZAR_PANTALLA_EXPEDIENTE/PANTALLA_CALCULO = actualizarResultadoCalculos
1/MODULO_INTEGRACION/MELANBIDE04/EH/ACTUALIZAR_PANTALLA_EXPEDIENTE/PANTALLA_CALCULO = actualizarResultadoCalculos

# Operaci\u00f3n javascript que se ejecuta desde ocultoFichaExpediente.jsp para actualizar la pantalla de un m\u00f3dulo externo. Esta operaci\u00f3n puede por ejemplo
# recuperar valores de campos desplegables de expediente necesarios para los c\u00e1lculos, o bien, no hacer nada. Como s\u00f3lo puede haber una pantalla de m\u00f3dulo de expediente
# por procedimiento, hay que asegurarse de que en caso de que el nombre de las operaciones no coincida entre ellas
0/MODULO_INTEGRACION/MELANBIDE04/EH/PANTALLA_EXPEDIENTE/METODOS_LLAMADA = 
1/MODULO_INTEGRACION/MELANBIDE04/EH/PANTALLA_EXPEDIENTE/METODOS_LLAMADA = 



##################################################################################################################################
######################                           FIN PANTALLAS DE EXPEDIENTE EH                          #########################
##################################################################################################################################



##################################################################################################################################
###############        INICIO:CAMPOS SUPLEMENTARIOS UTILIZADOS EN EL C\u00c1LCULO POR LA PANTALLA PANTALLA_CALCULO    #################
##################################################################################################################################
0/CAMPO_SUPLEMENTARIO_BASE_COTIZACION = BASECOTIZ2
1/CAMPO_SUPLEMENTARIO_BASE_COTIZACION = BASECOTIZ2
0/CAMPO_SUPLEMENTARIO_DURACION_CONTRATO_MESES = DURCONTMESES
1/CAMPO_SUPLEMENTARIO_DURACION_CONTRATO_MESES = DURCONTMESES
0/CAMPO_SUPLEMENTARIO_DURACION_CONTRATO_DIAS  = DURCONTDIAS
1/CAMPO_SUPLEMENTARIO_DURACION_CONTRATO_DIAS  = DURCONTDIAS
0/CAMPO_SUPLEMENTARIO_SUBVENCION_TOTAL            = SUBVTOTAL
1/CAMPO_SUPLEMENTARIO_SUBVENCION_TOTAL            = SUBVTOTAL
0/CAMPO_SUPLEMENTARIO_PRIMER_PAGO_60               = PRIMERPAGO60
1/CAMPO_SUPLEMENTARIO_PRIMER_PAGO_60               = PRIMERPAGO60
0/CAMPO_SUPLEMENTARIO_SEGUNDO_PAGO_40             = SEGUNDOPAGO40
1/CAMPO_SUPLEMENTARIO_SEGUNDO_PAGO_40             = SEGUNDOPAGO40
0/CAMPO_SUPLEMENTARIO_CANTIDAD_SOBRANTE_NO_PAGADA = CANTSOBNOPAG
1/CAMPO_SUPLEMENTARIO_CANTIDAD_SOBRANTE_NO_PAGADA = CANTSOBNOPAG
0/CAMPO_SUPLEMENTARIO_CANTIDAD_TOTAL_PAGADA           = CANTTOTPAGADA
1/CAMPO_SUPLEMENTARIO_CANTIDAD_TOTAL_PAGADA           = CANTTOTPAGADA
##################################################################################################################################
##################       FIN: CAMPOS SUPLEMENTARIOS UTILIZADOS EN EL C\u00c1LCULO POR LA PANTALLA PANTALLA_CALCULO    #################
##################################################################################################################################


UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide04.i18n.text
FICHEROS_MENSAJES = MELANBIDE04_TEXT_1;MELANBIDE04_TEXT_2;MELANBIDE04_TEXT_4