##################### OPERACIONES DISPONIBLES EN LA PESTAÑA "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE18/LISTA_OPERACIONES_DISPONIBLES=fraccionarDeudas;cambioCuentaFraccionamiento
1/MODULO_INTEGRACION/MELANBIDE18/LISTA_OPERACIONES_DISPONIBLES=fraccionarDeudas;cambioCuentaFraccionamiento

##################### NOMBRE DEL MÓDULO #####################
NOMBRE_MODULO = MELANBIDE18

##################### DESCRIPCIÓN DEL MÓDULO #####################
0/MODULO_INTEGRACION/MELANBIDE18/DESCRIPCION_MODULO = Módulo de Fraccionamiento deudas prestaciones FRACC/FRACU
1/MODULO_INTEGRACION/MELANBIDE18/DESCRIPCION_MODULO = Módulo de Fraccionamiento deudas prestaciones FRACC/FRACU

##################### NOMBRE DE LAS PANTALLAS DEL MÓDULO #####################
# DESA 2
# PRE y PRO 1
0/MODULO_INTEGRACION/MELANBIDE18/FRACC/2/PANTALLA_TRAMITE/NOMBRE_PANTALLAS = DEUDAS
1/MODULO_INTEGRACION/MELANBIDE18/FRACC/1/PANTALLA_TRAMITE/NOMBRE_PANTALLAS = DEUDAS

##################### URL DE LAS PANTALLAS DEL MÓDULO #####################
0/MODULO_INTEGRACION/MELANBIDE18/FRACC/2/URL_PANTALLA_TRAMITACION/DEUDAS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE18&operacion=cargarPantallaDeudasFracc&tipo=0
1/MODULO_INTEGRACION/MELANBIDE18/FRACC/1/URL_PANTALLA_TRAMITACION/DEUDAS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE18&operacion=cargarPantallaDeudasFracc&tipo=0

##################### NOMBRES DE TABLAS #####################
TABLA_E_EXT=E_EXT
TABLA_T_HTE=T_HTE
TABLA_E_TRA=E_TRA
TABLA_E_CRO=E_CRO
TABLA_MELANBIDE18_DEUDASFRAC=MELANBIDE18_DEUDASFRACC
VISTA_DEUDAS_A_FRACCIONAR=LANZK.VW_INFO_DEUDAS_A_FRACCIONAR

##################### NOMBRES DE SECUENCIAS #####################
SECUENCIA_M18_DEUDASFRAC=M18_MELANBIDE18_DEUDASFRACC_SEQ

################# SUPLEMENTARIOS #################
CAMPO_CTAIBAN=CTAIBAN
CAMPO_CTAENTIDAD=CTAENTIDAD
CAMPO_CTASUCURSAL=CTASUCURSAL
CAMPO_CTADC=CTADC
CAMPO_CTANUMERO=CTANUMCUENTA
CAMPO_CUOTA=IMPMENSDEUDA
CAMPO_TODAS=DEUDFRACC

##########################################################
### DATOS PARA LA CONEXION AL SERVICIO ###################
##########################################################
USUARIO_ZORKU=REGEXLANWS
PASS_ZORKU=REGEXLANWS
## DESA
URL_FRACCIONAMIENTO=https://zorku.des.lanbide.eus/Zorku/api/altaFraccionamiento
URL_CAMBIO_CUENTA=http://integ.serv.des.lanbide.lan/Zorku/api/cambioCuentaDomiciliacion
URL_RECURSO=http://integ.serv.des.lanbide.eus/Zorku/api/recursoResolucion
## PRE
# URL_FRACCIONAMIENTO=https://zorku.pru.lanbide.eus/Zorku/api/altaFraccionamiento
# URL_CAMBIO_CUENTA=http://integ.serv.pru.lanbide.lan/Zorku/api/cambioCuentaDomiciliacion
# URL_RECURSO=http://integ.serv.pru.lanbide.eus/Zorku/api/recursoResolucion
## PRO
# URL_FRACCIONAMIENTO=http://integ.serv.lanbide.lan/Zorku/api/altaFraccionamiento
# URL_CAMBIO_CUENTA=http://integ.serv.lanbide.lan/Zorku/api/cambioCuentaDomiciliacion
# URL_RECURSO= http://integ.serv.lanbide.eus/Zorku/api/recursoResolucion

##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide18.i18n.text
FICHEROS_MENSAJES = MELANBIDE18_TEXT_1;MELANBIDE18_TEXT_4

# EL caracter es pipeline hay que escaparlo porque es un caracter especial para hacer condicion or en regex
BARRA_SEPARADORA_IDIOMA=\\Q|\\E

######################################################################################################
##################      CÓDIGOS DE ERROR PARA LA OPERACIÓN  fraccionarDeudas      ####################
######################################################################################################
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/1=ERROR_1
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/10=ERROR_10
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/11=ERROR_11
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/12=ERROR_12
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/13=ERROR_13
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/14=ERROR_14
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/15=ERROR_15
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/16=ERROR_16
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/17=ERROR_17
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/18=ERROR_18
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/19=ERROR_19
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/20=ERROR_20
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/23=ERROR_23
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/24=ERROR_24
## errores ZORKU
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/ZOR-CAMPO-OBLIGATORIO=ERROR_30
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/ZORKU-DEUDA_FRACC-TERCERO=ERROR_31
0/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/404=ERROR_404

1/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/1=ERROR_1
1/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/10=ERROR_10
1/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/11=ERROR_11
1/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/12=ERROR_12
1/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/13=ERROR_13
1/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/14=ERROR_14
1/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/15=ERROR_15
1/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/16=ERROR_16
1/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/17=ERROR_17
1/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/18=ERROR_18
1/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/19=ERROR_19
1/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/20=ERROR_20
1/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/23=ERROR_23
1/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/24=ERROR_24
## errores ZORKU
1/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/ZOR-CAMPO-OBLIGATORIO=ERROR_30
1/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/ZORKU-DEUDA_FRACC-TERCERO=ERROR_31
1/MODULO_INTEGRACION/fraccionarDeudas/MENSAJE_ERROR/404=ERROR_404

#################################################################################################################
##################      CÓDIGOS DE ERROR PARA LA OPERACIÓN  cambioCuentaFraccionamiento      ####################
#################################################################################################################
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/1=ERROR_1
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/11=ERROR_11
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/12=ERROR_12
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/13=ERROR_13
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/14=ERROR_14
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/15=ERROR_15
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/16=ERROR_16
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/17=ERROR_17
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/20=ERROR_20
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/21=ERROR_21
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/22=ERROR_22
0/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/404=ERROR_404

1/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/1=ERROR_1
1/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/11=ERROR_11
1/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/12=ERROR_12
1/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/13=ERROR_13
1/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/14=ERROR_14
1/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/15=ERROR_15
1/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/16=ERROR_16
1/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/17=ERROR_17
1/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/20=ERROR_20
1/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/21=ERROR_21
1/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/22=ERROR_22
1/MODULO_INTEGRACION/cambioCuentaFraccionamiento/MENSAJE_ERROR/404=ERROR_404

#################### DESCRIPCION ERRORES
ERROR_1_1=Se ha producido un error genérico
ERROR_10_1=Ha ocurrido un error gen\u00e9rico en la llamada al servicio de Fraccionamiento
ERROR_11_1=Falta el IBAN de la Cuenta bancaria
ERROR_12_1=Falta la Entidad Bancaria
ERROR_13_1=Falta la sucursal
ERROR_14_1=Falta el dígito de Control de la cuenta
ERROR_15_1=Falta el número de la cuenta
ERROR_16_1=Alg\u00fan campo de la cuenta tiene un tama\u00f1o o formato incorrecto
ERROR_17_1=El numero de cuenta no es valido
ERROR_18_1=No se ha(n) recuperado la(s) deuda(s) a fraccionar
ERROR_20_1=Se ha producio un error recuperando el número del documento del interesado.
ERROR_21_1=Se ha producido un error en la llamada al servicio de Cambio de Cuenta
ERROR_22_1=El servicio de Cambio de Cuenta ha devuelto un error. Consulte con el Administrador
ERROR_23_1=
ERROR_24_1=
## errores ZORKU
ERROR_30_1=Falta alg\u00fan campo obligatorio
ERROR_31_1=Alguna de las deudas ya está fraccionada. Revise el listado
ERROR_404_1=No está disponible el servicio de ZORKU. Inténtelo más tarde.

ERROR_1_4=Errore generiko bat gertatu da
ERROR_10_4=Errore generiko bat gertatu da
ERROR_11_4=IBAN falta da
ERROR_12_4=Banketxea falta da
ERROR_13_4=Sukurtsala falta da
ERROR_14_4=Kontuaren kontrol-digitua falta da
ERROR_15_4=Kontuaren zenbakia falta da
ERROR_16_4=Kontu-zenbakia ez da baliozkoa - Daturen baten tamaina ez da zuzena
ERROR_17_4=Kontu-zenbakia ez da baliozkoa
ERROR_18_4=No se ha(n) recuperado la(s) deuda(s) a fraccionar_eu
ERROR_20_4=Errorea gertatu da interesdunaren dokumentuaren zenbakia berreskuratzean.
ERROR_21_4=Errorea gertatu da kontua aldatzeko zerbitzura egindako deian
ERROR_22_4=Kontua aldatzeko zerbitzuak errore bat itzuli du. Galdetu administratzaileari
ERROR_23_4=
ERROR_24_4=
## errores ZORKU
ERROR_30_4=
ERROR_31_4=
ERROR_404_4=ZORKU zerbitzua ez dago erabilgarri. Saia zaitez geroago.