##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE85/LISTA_OPERACIONES_DISPONIBLES=
1/MODULO_INTEGRACION/MELANBIDE85/LISTA_OPERACIONES_DISPONIBLES=

##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE85

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE85/DESCRIPCION_MODULO = MODULO CONTRATACION PEX
1/MODULO_INTEGRACION/MELANBIDE85/DESCRIPCION_MODULO = MODULO CONTRATACION PEX

##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE85/PEX/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CONTRATACION
1/MODULO_INTEGRACION/MELANBIDE85/PEX/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CONTRATACION

##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE85/PEX/URL_PANTALLA_EXPEDIENTE/CONTRATACION = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE85&operacion=cargarPantallaPrincipal&tipo=0
1/MODULO_INTEGRACION/MELANBIDE85/PEX/URL_PANTALLA_EXPEDIENTE/CONTRATACION = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE85&operacion=cargarPantallaPrincipal&tipo=0

##################### TABLAS DEL M\u00d3DULO #####################
MELANBIDE85_CONTRATACION=MELANBIDE85_CONTRATACION
MELANBIDE85_CONTRATACION_INI=MELANBIDE85_CONTRATACION_INI
MELANBIDE85_CONTRATACION_FIN=MELANBIDE85_CONTRATACION_FIN
TABLA_CODIGOS_DESPLEGABLES=E_DES
TABLA_VALORES_DESPLEGABLES=E_DES_VAL
TABLA_TIPO_DATO_FICHERO=E_TFI

##################### C\u00d3DIGOS DESPLEGABLES - PEX #####################
#MEPE - MESES CONTRATO PEX
COD_DES_MEPE=MEPE
#GCON - GRUPOS COTIZACION PEX
COD_DES_GCON=GCON
#SEXO - SEXO PEX
COD_DES_SEXO=SEXO
#BOOL - BOOL PEX (S/N)
COD_DES_BOOL=BOOL

### SECUENCIAS ID DE TABLAS CONTRATACION
SEQ_MELANBIDE85_CONTRATACION=SEQ_MELANBIDE85_CONTRATACION
SEQ_MELANBIDE85_CONTRATA_INI=SEQ_MELANBIDE85_CONTRATA_INI
SEQ_MELANBIDE85_CONTRATA_FIN=SEQ_MELANBIDE85_CONTRATA_FIN

##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide85.i18n.text
FICHEROS_MENSAJES = MELANBIDE85_TEXT_1;MELANBIDE85_TEXT_4

# EL caracter es pipeline hay que escaparlo porque es un caracter especial para hacer condicion or en regex
BARRA_SEPARADORA_IDIOMA_DESPLEGABLES=\\Q|\\E


#######################CAMPOS CALCULADOS PARA PLANTILLAS###############################################
#El tipo_etiqueta nos indica el tipo de dato de la etiqueta (lo queremos para saber como formatear) (1->Entero, 2->String, 3-> Fecha, 4->Lista)
0/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/ETIQUETAS=PEX_ETIQUETA_LISTAREQEUS;PEX_ETIQUETA_LISTAREQ;PEX_ETIQUETA_TABLAPUESTOS

#etiqueta LISTAREQEUS, euskera
0/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQEUS/TIPO_ETIQUETA=2
0/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQEUS/NOMBRE_ETIQUETA=LISTAREQEUS
0/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQEUS/CODIGO_ETIQUETA=LISTAREQEUS
0/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQEUS/SQL_ETIQUETA=SELECT RTRIM (XMLAGG (XMLELEMENT (E,DESCRIPCION||'-'||TTLT_VALOR|| CHR(13))).EXTRACT ('//text()').GETCLOBVAL(),',') AS REQUISITOS FROM E_TDET INNER JOIN PLANTILLA_DESCLARGA ON CODIGO  = TDET_COD AND IDIOMA ='eu' and procedimiento=TDET_PRO LEFT JOIN E_TTLT ON SUBSTR(TTLT_COD,4,LENGTH(TTLT_COD))=TDET_COD AND TTLT_TRA=TDET_TRA AND TDET_PRO=TTLT_PRO
0/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQEUS/SQL_NOMBRE_COLUMNA=REQUISITOS
0/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQEUS/CLAUSULA_WHERE= WHERE tdet_num=
0/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQEUS/CLAUSULA_WHERE/CAMPO=numeroExpediente
0/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQEUS/CLAUSULA_AND3=and procedimiento=TDET_PRO AND E_TDET.TDET_PRO='PEX' AND TDET_TRA=7 AND TDET_VALOR='X' AND tdet_ocu = (SELECT MAX(cro_ocu) FROM E_CRO WHERE cro_tra = 7 AND CRO_NUM=tdet_num)

#etiqueta LISTAREQ, castellano
0/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQ/TIPO_ETIQUETA=2
0/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQ/NOMBRE_ETIQUETA=LISTAREQ
0/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQ/CODIGO_ETIQUETA=LISTAREQ
0/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQ/SQL_ETIQUETA=SELECT RTRIM (XMLAGG (XMLELEMENT (E,DESCRIPCION||'-'||TTLT_VALOR|| CHR(13))).EXTRACT ('//text()').GETCLOBVAL(),',') AS REQUISITOS FROM E_TDET INNER JOIN PLANTILLA_DESCLARGA ON CODIGO  = TDET_COD AND IDIOMA ='es' and procedimiento=TDET_PRO LEFT JOIN E_TTLT ON SUBSTR(TTLT_COD,4,LENGTH(TTLT_COD))=TDET_COD AND TTLT_TRA=TDET_TRA AND TDET_PRO=TTLT_PRO
0/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQ/SQL_NOMBRE_COLUMNA=REQUISITOS
0/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQ/CLAUSULA_WHERE= WHERE tdet_num=
0/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQ/CLAUSULA_WHERE/CAMPO=numeroExpediente
0/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQ/CLAUSULA_AND3=and procedimiento=TDET_PRO AND E_TDET.TDET_PRO='PEX' AND TDET_TRA=7 AND TDET_VALOR='X' AND tdet_ocu = (SELECT MAX(cro_ocu) FROM E_CRO WHERE cro_tra = 7 AND CRO_NUM=tdet_num)

#etiqueta TABLAPUESTOS
0/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_TABLAPUESTOS/TIPO_ETIQUETA=2
0/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_TABLAPUESTOS/NOMBRE_ETIQUETA=TABLAPUESTOS
0/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_TABLAPUESTOS/CODIGO_ETIQUETA=TABLAPUESTOS
0/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_TABLAPUESTOS/SQL_ETIQUETA=select RTRIM (XMLAGG (XMLELEMENT (E,sol.num_puesto||'|'||sol.denompuesto1||'|'||sol.titulacion1||'|'||sol.municipioct1||'|'||sol.durcontrato1||'|'||sol.grupocotiz1||'|'||fin.subvconcedidalan3||'|'||sol.empverde1||'|'||sol.empdigit1|| '|'||sol.empgen|| CHR(13)) order by sol.num_puesto).EXTRACT ('//text()').getclobval(),',') ETIQUETA from melanbide85_contratacion sol left join melanbide85_contratacion_ini ini on ini.num_exp=sol.num_exp and ini.num_puesto=sol.num_puesto left join melanbide85_contratacion_fin fin on fin.num_exp=sol.num_exp and fin.num_puesto=sol.num_puesto
0/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_TABLAPUESTOS/SQL_NOMBRE_COLUMNA=ETIQUETA
0/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_TABLAPUESTOS/CLAUSULA_WHERE= WHERE sol.num_exp=
0/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_TABLAPUESTOS/CLAUSULA_WHERE/CAMPO=numeroExpediente
0/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_TABLAPUESTOS/CLAUSULA_AND3= order by sol.num_puesto


## pre pro
1/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/ETIQUETAS=PEX_ETIQUETA_LISTAREQEUS;PEX_ETIQUETA_LISTAREQ;PEX_ETIQUETA_TABLAPUESTOS

#etiqueta LISTAREQEUS, euskera
1/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQEUS/TIPO_ETIQUETA=2
1/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQEUS/NOMBRE_ETIQUETA=LISTAREQEUS
1/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQEUS/CODIGO_ETIQUETA=LISTAREQEUS
1/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQEUS/SQL_ETIQUETA=SELECT RTRIM (XMLAGG (XMLELEMENT (E,DESCRIPCION||'-'||TTLT_VALOR|| CHR(13))).EXTRACT ('//text()').GETCLOBVAL(),',') AS REQUISITOS FROM E_TDET INNER JOIN PLANTILLA_DESCLARGA ON CODIGO  = TDET_COD AND IDIOMA ='eu' and procedimiento=TDET_PRO LEFT JOIN E_TTLT ON SUBSTR(TTLT_COD,4,LENGTH(TTLT_COD))=TDET_COD AND TTLT_TRA=TDET_TRA AND TDET_PRO=TTLT_PRO
1/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQEUS/SQL_NOMBRE_COLUMNA=REQUISITOS
1/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQEUS/CLAUSULA_WHERE= WHERE tdet_num=
1/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQEUS/CLAUSULA_WHERE/CAMPO=numeroExpediente
1/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQEUS/CLAUSULA_AND3=and procedimiento=TDET_PRO AND E_TDET.TDET_PRO='PEX' AND TDET_TRA=16 AND TDET_VALOR='X' AND tdet_ocu = (SELECT MAX(cro_ocu) FROM E_CRO WHERE cro_tra = 16 AND CRO_NUM=tdet_num)

#etiqueta LISTAREQ, castellano
1/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQ/TIPO_ETIQUETA=2
1/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQ/NOMBRE_ETIQUETA=LISTAREQ
1/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQ/CODIGO_ETIQUETA=LISTAREQ
1/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQ/SQL_ETIQUETA=SELECT RTRIM (XMLAGG (XMLELEMENT (E,DESCRIPCION||'-'||TTLT_VALOR|| CHR(13))).EXTRACT ('//text()').GETCLOBVAL(),',') AS REQUISITOS FROM E_TDET INNER JOIN PLANTILLA_DESCLARGA ON CODIGO  = TDET_COD AND IDIOMA ='es' and procedimiento=TDET_PRO LEFT JOIN E_TTLT ON SUBSTR(TTLT_COD,4,LENGTH(TTLT_COD))=TDET_COD AND TTLT_TRA=TDET_TRA AND TDET_PRO=TTLT_PRO
1/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQ/SQL_NOMBRE_COLUMNA=REQUISITOS
1/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQ/CLAUSULA_WHERE= WHERE tdet_num=
1/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQ/CLAUSULA_WHERE/CAMPO=numeroExpediente
1/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_LISTAREQ/CLAUSULA_AND3=and procedimiento=TDET_PRO AND E_TDET.TDET_PRO='PEX' AND TDET_TRA=16 AND TDET_VALOR='X' AND tdet_ocu = (SELECT MAX(cro_ocu) FROM E_CRO WHERE cro_tra = 16 AND CRO_NUM=tdet_num)

#etiqueta TABLAPUESTOS
1/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_TABLAPUESTOS/TIPO_ETIQUETA=2
1/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_TABLAPUESTOS/NOMBRE_ETIQUETA=TABLAPUESTOS
1/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_TABLAPUESTOS/CODIGO_ETIQUETA=TABLAPUESTOS
1/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_TABLAPUESTOS/SQL_ETIQUETA=select RTRIM (XMLAGG (XMLELEMENT (E,sol.num_puesto||'|'||sol.denompuesto1||'|'||sol.titulacion1||'|'||sol.municipioct1||'|'||sol.durcontrato1||'|'||sol.grupocotiz1||'|'||fin.subvconcedidalan3||'|'||sol.empverde1||'|'||sol.empdigit1|| '|'||sol.empgen|| CHR(13)) order by sol.num_puesto).EXTRACT ('//text()').getclobval(),',') ETIQUETA from melanbide85_contratacion sol left join melanbide85_contratacion_ini ini on ini.num_exp=sol.num_exp and ini.num_puesto=sol.num_puesto left join melanbide85_contratacion_fin fin on fin.num_exp=sol.num_exp and fin.num_puesto=sol.num_puesto
1/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_TABLAPUESTOS/SQL_NOMBRE_COLUMNA=ETIQUETA
1/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_TABLAPUESTOS/CLAUSULA_WHERE= WHERE sol.num_exp=
1/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_TABLAPUESTOS/CLAUSULA_WHERE/CAMPO=numeroExpediente
1/MODULO_INTEGRACION/MELANBIDE85/PEX/PLANTILLA_NORMAL/PEX_ETIQUETA_TABLAPUESTOS/CLAUSULA_AND3= order by sol.num_puesto