##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE68/LISTA_OPERACIONES_DISPONIBLES=
1/MODULO_INTEGRACION/MELANBIDE68/LISTA_OPERACIONES_DISPONIBLES=

##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE68

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE68/DESCRIPCION_MODULO = M\u00f3dulo General 
1/MODULO_INTEGRACION/MELANBIDE68/DESCRIPCION_MODULO = M\u00f3dulo General

##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide68.i18n.text
FICHEROS_MENSAJES = MELANBIDE68_TEXT_1;MELANBIDE68_TEXT_4

