
##########################################################################################################################
#                                                                                                                        #
#                                                   CONGIGURACION ALARMAS                                                #
#                                                                                                                        #
##########################################################################################################################


##  MAIL DE DONDE SE ENVIA    ##

mail.from=regexlan@lanbide.eus

## CONFIGURACION DE LAS DIFERENTES ALARMAS ##


## ALARMA 1 ##
## 50 d\u00edas desde la fecha del registro que ha iniciado el expediente ##

alarma1.mail.destino=DECEX1@lanbide.eus
alarma1.mail.asunto=Notificaci\u00f3n aviso silencio positivo DECEX ( Alarma 1)
alarma1.mail.contenido=Han pasado 50 d\u00edas desde la fecha @fechaAltaRegistro@ del registro @numeroEntradaRegistro@ que ha iniciado el expediente @numeroexpediente@ \n


## ALARMA 2 ##
##Hay cuatro requerimientos##

alarma2.mail.destino=DECEX2@lanbide.eus
alarma2.mail.asunto=Notificaci\u00f3n del requerimiento de subsanaci\u00f3n DECEX ( Alarma 2)
alarma2.mail.contenido.base=Han trascurrido 10 d\u00edas laborales (15 naturales ) desde la notifiaci\u00f3n del requerimiento de subsanaci\u00f3n, revisa los siguientes expedientes para resolver en forma denegatoria si no han subsanado. para los siguientes expediente:
alarma2.mail.contenido.texto.1= Solicitud: expedientes con tr\u00e1mite 102 " ESPERA RECEPCI\u00d3N DOC SUBSANACI\u00d3N SOLICITUD " abierto, para los que han pasado 15 d\u00edas desde la fecha de acuse de recibo del tramite 101 "ACUSE RECIBO NOTIFICACI\u00d3N REQ SUBS DOC SOLICITUD" :  \n
alarma2.mail.contenido.texto.2= \n \n Tres meses: expedientes con tr\u00e1mite 132 " ESPERA RECEPCI\u00d3N DOC SUBSANACI\u00d3N 3 MESES " abierto, para los que hayan pasado 15 d\u00edas desde la fecha de acuse de recibo del tramite 131 " ACUSE RECIBO NOTIFICACI\u00d3N REQ SUBS DOC 3 MESES " :   \n
alarma2.mail.contenido.texto.3= \n \n Anual: expedientes con tr\u00e1mite 192 " ESPERA RECEPCI\u00d3N DOC SUBSANACI\u00d3N ANUAL " abierto, para los que hayan pasado 15 d\u00edas desde la fecha de acuse de recibo del tramite 191 " ACUSE RECIBO NOTIFICACI\u00d3N REQ SUBS DOC ANUAL " :  \n
alarma2.mail.contenido.texto.4= \n \n Modificaci\u00f3n: expedientes con tr\u00e1mite 182 " ESPERA RECEPCI\u00d3N DOCSUBSANACI\u00d3N MODIFICACIONES " abierto, para los que hayan pasado 15 d\u00edas desde la fecha de acuse de recibo del tramite 181 " ACUSE RECIBO NOTIFICACI\u00d3N REQ SUBS DOC MODIFICACIONES " :  \n


## ACUSE RECIBO NOTIFICACION REQ SUBS DOC SOLICITUD ##
alarma2.codigo.visible.tramite.notifRequeSolic=101

## ACUSE RECIBO NOTIFICACION REQ SUBS ACUSE RECIBO NOTIFICACION REQ SUBS DOC 3 MESES ##
alarma2.codigo.visible.tramite.notifReque3M=131

## ACUSE RECIBO NOTIFICACION REQ SUBS DOC MODIFICACIONES ##
alarma2.codigo.visible.tramite.notifRequeModi=191

## ACUSE RECIBO NOTIFICACION REQ SUBS DOC ANUAL ##
alarma2.codigo.visible.tramite.notifRequeAnual=181


## ALARMA 3 ##

alarma3.mail.destino=DECEX3@lanbide.eus
alarma3.mail.asunto=Notificaci\u00f3n entrega documentaci\u00f3n 3 meses DECEX (Alarma 3)
alarma3.mail.contenido=Han pasado m\u00e1s de 15 d\u00edas desde la fecha para la entrega de la documentaci\u00f3n desde que se inici\u00f3 el tr\u00e1mite 300 " RECEPCI\u00d3N Y REGISTRO DE ENTRADA 3 MESES " de los expedientes : \n \n
alarma3.mail.contenido.variable= - @numeroExpediente@ 
  
  

## RECEPCION Y REGISTRO DE ENTRADA 3 MESES ##
alarma3.codigo.visible.tramite.notifacuse3M=300


## ALARMA 4 ##

alarma4.mail.destino=DECEX4@lanbide.eus
alarma4.mail.asunto=Notificaci\u00f3n al a\u00f1o de la notificaci\u00f3n de la resoluci\u00f3n DECEX ( Alarma 4)
alarma4.mail.contenido=Han pasado el a\u00f1o de la resolici\u00f3n desde iniciado el expediente : \n \n
alarma4.mail.contenido.variable= - @numeroExpediente@

## RECEPCION Y REGISTRO DE ENTRADA A\u00d1O 1, 2 O 3 ##

alarma4.codigo.visible.tramite.notiRegisAnual=1000
alarma4.codigo.visible.tramite.notiRegisBi=2000
alarma4.codigo.visible.tramite.notiRegisTri=3000

