# M\u00e9todos del m\u00f3dulo que se utilizan para configurar el m\u00f3dulo en la pesta\u00f1a "Conf. SW" de la definici\u00f3n del tr\u00e1mite
0/MODULO_INTEGRACION/MELANBIDE05/LISTA_OPERACIONES_DISPONIBLES=grabarFechaPresentacion
1/MODULO_INTEGRACION/MELANBIDE05/LISTA_OPERACIONES_DISPONIBLES=grabarFechaPresentacion

# NOMBRE DEL M\u00d3DULO QUE SE MUESTRA JUNTO CON EL NOMBRE DE LA OPERACI\u00d3N; A LA HORA DE SELECCIONAR UNA OPERACI\u00d3N QUE SE ASOCIAR\u00c1 A UN TR\u00c1MITE
# FORMATO: [COD_ORGANIZACION]/MODULO_INTEGRACION/[NOMBRE_MODULO]/NOMBRE_MODULO
0/MODULO_INTEGRACION/MELANBIDE05/DESCRIPCION_MODULO = M\u00d3DULO GEN\u00c9RICO DE GRABACION DE FECHA DE ANOTACI\u00d3N INICIO EXPEDIENTE
1/MODULO_INTEGRACION/MELANBIDE05/DESCRIPCION_MODULO = M\u00d3DULO GEN\u00c9RICO DE GRABACION DE FECHA DE ANOTACI\u00d3N INICIO EXPEDIENTE

#----------------------------------------------------------------------------------------------------------------------------------------------#
#                                                       CAMPOS SUPLEMENTARIOS DEL EXPEDIENTE                                                   #
#----------------------------------------------------------------------------------------------------------------------------------------------#
#TIPO DEL CAMPO (1=N\u00famero,2=texto corto, 3=fecha,4=texto_largo,5=fichero, 6=desplegable )
#[COD_ORGANIZACION]/MODULO_INTEGRACION/MELANBIDE05/[COD_PROCEDIMIENTO]/NOMBRE_CAMPO/[NOMBRE_CAMPO]
#0/MODULO_INTEGRACION/MELANBIDE05/ORICE/NOMBRE_CAMPO/FECHA_PRESENTACION=FECHAPRESENTACION
#1/MODULO_INTEGRACION/MELANBIDE05/ORICE/NOMBRE_CAMPO/FECHA_PRESENTACION=FECHAPRESENTACION

0/MODULO_INTEGRACION/MELANBIDE05/NOMBRE_CAMPO/FECHA_PRESENTACION=FECHAPRESENTACION
1/MODULO_INTEGRACION/MELANBIDE05/NOMBRE_CAMPO/FECHA_PRESENTACION=FECHAPRESENTACION

#[COD_ORGANIZACION]/MODULO_INTEGRACION/[NOMBRE_OPERACION]/MENSAJE_ERROR/[COD_ERROR]
0/MODULO_INTEGRACION/grabarFechaPresentacion/MENSAJE_ERROR/1=ERROR_RECUPERANDO_FECHA_PRESENTACION
0/MODULO_INTEGRACION/grabarFechaPresentacion/MENSAJE_ERROR/2=ERROR_GRABANDO_FECHA_CAMPO_SUPLEMENTARIO
0/MODULO_INTEGRACION/grabarFechaPresentacion/MENSAJE_ERROR/3=ERROR

#[COD_ORGANIZACION]/MODULO_INTEGRACION/[NOMBRE_OPERACION]/MENSAJE_ERROR/[COD_ERROR]
1/MODULO_INTEGRACION/grabarFechaPresentacion/MENSAJE_ERROR/1=ERROR_RECUPERANDO_FECHA_PRESENTACION
1/MODULO_INTEGRACION/grabarFechaPresentacion/MENSAJE_ERROR/2=ERROR_GRABANDO_FECHA_CAMPO_SUPLEMENTARIO
1/MODULO_INTEGRACION/grabarFechaPresentacion/MENSAJE_ERROR/3=ERROR

ERROR_RECUPERANDO_FECHA_PRESENTACION_1=Se ha producido un error recuperando la fecha de la anotaci\u00f3n del registro
ERROR_RECUPERANDO_FECHA_PRESENTACION_4=Se ha producido un error recuperando la fecha de la anotaci\u00f3n del registro
ERROR_GRABANDO_FECHA_CAMPO_SUPLEMENTARIO_1=Se ha producido un error grabando la fecha de inicio del expediente en el campo suplementario
ERROR_GRABANDO_FECHA_CAMPO_SUPLEMENTARIO_4=Se ha producido un error grabando la fecha de inicio del expediente en el campo suplementario
ERROR_1=Se ha producido un error en la operaci\u00f3n de grabar la fecha de la presentaci\u00f3n
ERROR_4=Se ha producido un error en la operaci\u00f3n de grabar la fecha de la presentaci\u00f3n

















