##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE10/LISTA_OPERACIONES_DISPONIBLES=
1/MODULO_INTEGRACION/MELANBIDE10/LISTA_OPERACIONES_DISPONIBLES=

##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE10

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE10/DESCRIPCION_MODULO = MODULO MINIMIS DISCP
1/MODULO_INTEGRACION/MELANBIDE10/DESCRIPCION_MODULO = MODULO MINIMIS DISCP

##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE10/DISCP/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = MINIMIS
1/MODULO_INTEGRACION/MELANBIDE10/DISCP/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = MINIMIS

##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE10/DISCP/URL_PANTALLA_EXPEDIENTE/MINIMIS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE10&operacion=cargarPantallaPrincipal&tipo=0
1/MODULO_INTEGRACION/MELANBIDE10/DISCP/URL_PANTALLA_EXPEDIENTE/MINIMIS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE10&operacion=cargarPantallaPrincipal&tipo=0

##################### TABLAS DEL M\u00d3DULO #####################
MELANBIDE10_SUBSOLIC=MELANBIDE10_SUBSOLIC
TABLA_CODIGOS_DESPLEGABLES=E_DES
TABLA_VALORES_DESPLEGABLES=E_DES_VAL

##################### C\u00d3DIGOS DESPLEGABLES #####################
#DESPLEGABLE DTSV
COD_DES_DTSV=DTSV

### SECUENCIAS ID DE TABLAS CONTRATACION
SEQ_MELANBIDE10_SUBSOLIC=SEQ_MELANBIDE10_SUBSOLIC

##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide10.i18n.text
FICHEROS_MENSAJES = MELANBIDE10_TEXT_1;MELANBIDE10_TEXT_4

# EL caracter es pipeline hay que escaparlo porque es un caracter especial para hacer condicion or en regex
BARRA_SEPARADORA_IDIOMA_DESPLEGABLES=\\Q|\\E
