##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE40/LISTA_OPERACIONES_DISPONIBLES=refrescarPantalla
1/MODULO_INTEGRACION/MELANBIDE40/LISTA_OPERACIONES_DISPONIBLES=refrescarPantalla

##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE40

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE40/DESCRIPCION_MODULO = M\u00f3dulo EMPNL
1/MODULO_INTEGRACION/MELANBIDE40/DESCRIPCION_MODULO = M\u00f3dulo EMPNL

##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
# FORMATO: [COD_ORGANIZACION]/MODULO_INTEGRACION/[NOMBRE_MODULO]/[COD_PROCEDIMIENTO]/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = DATOS_CP_MP
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = DATOS_CP_MP

##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/URL_PANTALLA_EXPEDIENTE/DATOS_CP_MP = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE40&operacion=cargarPantalla&tipo=0
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/URL_PANTALLA_EXPEDIENTE/DATOS_CP_MP = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE40&operacion=cargarPantalla&tipo=0

##################### NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE #####################
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/CALCULOS =
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/CALCULOS =
#0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/7/OPERACION_PROCESAR/CALCULOS =
#1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/7/OPERACION_PROCESAR/CALCULOS =

#0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PANTALLA_EXPEDIENTE/SALIDA = /jsp/extension/MELANBIDE40/MELANBIDE40.jsp
#1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PANTALLA_EXPEDIENTE/SALIDA = /jsp/extension/MELANBIDE40/MELANBIDE40.jsp

##################### NOMBRE DE LA OPERACION DEL MODULO QUE SE ENCARGA DE ACTUALIZAR LOS DATOS DE LA PANTALLA DE EXPEDIENTE #####################
#0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/ACTUALIZAR_PANTALLA_EXPEDIENTE/CALCULOS = actualizarCalculosEMPNL
#1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/ACTUALIZAR_PANTALLA_EXPEDIENTE/CALCULOS = actualizarCalculosEMPNL
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/7/ACTUALIZAR_PANTALLA_TRAMITE/CALCULOS = actualizarCalculosEMPNL
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/7/ACTUALIZAR_PANTALLA_TRAMITE/CALCULOS = actualizarCalculosEMPNL

##################### NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE DE UNA RELACI\u00d3N ENTRE EXPEDIENTES #####################
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/SELECCION_CERTIFICADO  =
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR/SELECCION_CERTIFICADO  =

##################### NOMBRES DE TABLAS #####################

TABLA_MELANBIDE40_CERTIFICADO = MELANBIDE40_CERTIFICADO
#TABLA_CER_CERTIFICADOS = CER_CERTIFICADOS
TABLA_CER_CERTIFICADOS = S_CER_CERTIFICADOS
TABLA_CER_REL_MOD_CERT = CP_UC
#TABLA_CER_MODULOS_FORMATIVOS = CER_MODULOS_FORMATIVOS
TABLA_CER_MODULOS_FORMATIVOS = S_CER_MODULOS_FORMATIVOS
TABLA_MELANBIDE03_MOD_PRACT = MELANBIDE03_MOD_PRACT


#NUMERICOS
TABLA_TIPO_DATO_NUMERICO=E_TNU
TABLA_TIPO_DATO_NUMERICO_TRAMITE=E_TNUT
TABLA_S75_PAGOS=S75PAGOS
TABLA_TRAMITES=E_TRA
TABLA_E_CRO=E_CRO


##################### NOMBRES DE SECUENCIAS #####################



##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide40.i18n.text
FICHEROS_MENSAJES = MELANBIDE40_TEXT_1,MELANBIDE40_TEXT_4


##################################################################################################################################
######################                 ETIQUETAS PARA DOCUMENTOS DE TRAMITACION                          #########################
##################################################################################################################################

#El tipo_etiqueta nos indica el tipo de dato de la etiqueta (lo queremos para saber como formatear) (1->Entero, 2->String, 3-> Fecha, 4->Lista)

#PLANTILLA NORMAL

#CODIGO CERTIFICADO
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/ETIQUETAS=MELANBIDE40_ETIQUETA_CODCERTIFICADO;MELANBIDE40_ETIQUETA_CODMODPRAC;MELANBIDE40_ETIQUETA_DESCMODPRACCAS;MELANBIDE40_ETIQUETA_DESCMODPRACEUS;MELANBIDE40_ETIQUETA_DESCCERTIFICADOCAS;MELANBIDE40_ETIQUETA_DESCCERTIFICADOEUS;
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/ETIQUETAS=MELANBIDE40_ETIQUETA_CODCERTIFICADO;MELANBIDE40_ETIQUETA_CODMODPRAC;MELANBIDE40_ETIQUETA_DESCMODPRACCAS;MELANBIDE40_ETIQUETA_DESCMODPRACEUS;MELANBIDE40_ETIQUETA_DESCCERTIFICADOCAS;MELANBIDE40_ETIQUETA_DESCCERTIFICADOEUS;

0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_CODCERTIFICADO/TIPO_ETIQUETA=2
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_CODCERTIFICADO/NOMBRE_ETIQUETA=CODCERTIFICADO
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_CODCERTIFICADO/CODIGO_ETIQUETA=EXPEDIENTE_CODCERTIFICADO
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_CODCERTIFICADO/SQL_ETIQUETA=SELECT COD_CERTIFICADO FROM MELANBIDE40_CERTIFICADO
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_CODCERTIFICADO/SQL_NOMBRE_COLUMNA=COD_CERTIFICADO
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_CODCERTIFICADO/CLAUSULA_WHERE= WHERE NUM_EXPEDIENTE=
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_CODCERTIFICADO/CLAUSULA_WHERE/CAMPO=numeroExpediente


1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_CODCERTIFICADO/TIPO_ETIQUETA=2
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_CODCERTIFICADO/NOMBRE_ETIQUETA=CODCERTIFICADO
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_CODCERTIFICADO/CODIGO_ETIQUETA=EXPEDIENTE_CODCERTIFICADO
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_CODCERTIFICADO/SQL_ETIQUETA=SELECT COD_CERTIFICADO FROM MELANBIDE40_CERTIFICADO
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_CODCERTIFICADO/SQL_NOMBRE_COLUMNA=COD_CERTIFICADO
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_CODCERTIFICADO/CLAUSULA_WHERE= WHERE NUM_EXPEDIENTE=
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_CODCERTIFICADO/CLAUSULA_WHERE/CAMPO=numeroExpediente

#DESCRIPCION CERTIFICADO CASTELLANO
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCCERTIFICADOCAS/TIPO_ETIQUETA=2
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCCERTIFICADOCAS/NOMBRE_ETIQUETA=DESCCERTIFICADOCAS
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCCERTIFICADOCAS/CODIGO_ETIQUETA=EXPEDIENTE_DESCCERTIFICADOCAS
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCCERTIFICADOCAS/SQL_ETIQUETA=SELECT DES_CERTIFICADO_CAS FROM MELANBIDE40_CERTIFICADO
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCCERTIFICADOCAS/SQL_NOMBRE_COLUMNA=DES_CERTIFICADO_CAS
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCCERTIFICADOCAS/CLAUSULA_WHERE= WHERE NUM_EXPEDIENTE=
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCCERTIFICADOCAS/CLAUSULA_WHERE/CAMPO=numeroExpediente

1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCCERTIFICADOCAS/NOMBRE_ETIQUETA=DESCCERTIFICADOCAS
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCCERTIFICADOCAS/CODIGO_ETIQUETA=EXPEDIENTE_DESCCERTIFICADOCAS
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCCERTIFICADOCAS/SQL_ETIQUETA=SELECT DES_CERTIFICADO_CAS FROM MELANBIDE40_CERTIFICADO
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCCERTIFICADOCAS/SQL_NOMBRE_COLUMNA=DES_CERTIFICADO_CAS
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCCERTIFICADOCAS/CLAUSULA_WHERE/CAMPO=numeroExpediente

#DESCRIPCION CERTIFICADO EUSKERA
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCCERTIFICADOEUS/TIPO_ETIQUETA=2
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCCERTIFICADOEUS/NOMBRE_ETIQUETA=DESCCERTIFICADOEUS
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCCERTIFICADOEUS/CODIGO_ETIQUETA=EXPEDIENTE_DESCCERTIFICADOEUS
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCCERTIFICADOEUS/SQL_ETIQUETA=SELECT DES_CERTIFICADO_EUS FROM MELANBIDE40_CERTIFICADO
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCCERTIFICADOEUS/SQL_NOMBRE_COLUMNA=DES_CERTIFICADO_EUS
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCCERTIFICADOEUS/CLAUSULA_WHERE= WHERE NUM_EXPEDIENTE=
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCCERTIFICADOEUS/CLAUSULA_WHERE/CAMPO=numeroExpediente

1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCCERTIFICADOEUS/TIPO_ETIQUETA=2
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCCERTIFICADOEUS/NOMBRE_ETIQUETA=DESCCERTIFICADOEUS
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCCERTIFICADOEUS/CODIGO_ETIQUETA=EXPEDIENTE_DESCCERTIFICADOEUS
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCCERTIFICADOEUS/SQL_ETIQUETA=SELECT DES_CERTIFICADO_EUS FROM MELANBIDE40_CERTIFICADO
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCCERTIFICADOEUS/SQL_NOMBRE_COLUMNA=DES_CERTIFICADO_EUS
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCCERTIFICADOEUS/CLAUSULA_WHERE= WHERE NUM_EXPEDIENTE=
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCCERTIFICADOEUS/CLAUSULA_WHERE/CAMPO=numeroExpediente


#CODIGO MODULO PRACTICAS
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_CODMODPRAC/TIPO_ETIQUETA=2
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_CODMODPRAC/NOMBRE_ETIQUETA=CODMODPRAC
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_CODMODPRAC/CODIGO_ETIQUETA=EXPEDIENTE_CODMODPRAC
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_CODMODPRAC/SQL_ETIQUETA=SELECT COD_MODPRAC FROM MELANBIDE40_CERTIFICADO
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_CODMODPRAC/SQL_NOMBRE_COLUMNA=COD_MODPRAC
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_CODMODPRAC/CLAUSULA_WHERE= WHERE NUM_EXPEDIENTE=
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_CODMODPRAC/CLAUSULA_WHERE/CAMPO=numeroExpediente

1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_CODMODPRAC/TIPO_ETIQUETA=2
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_CODMODPRAC/NOMBRE_ETIQUETA=CODMODPRAC
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_CODMODPRAC/CODIGO_ETIQUETA=EXPEDIENTE_CODMODPRAC
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_CODMODPRAC/SQL_ETIQUETA=SELECT COD_MODPRAC FROM MELANBIDE40_CERTIFICADO
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_CODMODPRAC/SQL_NOMBRE_COLUMNA=COD_MODPRAC
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_CODMODPRAC/CLAUSULA_WHERE= WHERE NUM_EXPEDIENTE=
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_CODMODPRAC/CLAUSULA_WHERE/CAMPO=numeroExpediente

#DESCRIPCION MODULO PRACTICAS CASTELLANO
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCMODPRACCAS/TIPO_ETIQUETA=2
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCMODPRACCAS/NOMBRE_ETIQUETA=DESCMODPRACCAS
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCMODPRACCAS/CODIGO_ETIQUETA=EXPEDIENTE_DESCMODPRACCAS
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCMODPRACCAS/SQL_ETIQUETA=SELECT DES_MODULO_CAS FROM MELANBIDE40_CERTIFICADO
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCMODPRACCAS/SQL_NOMBRE_COLUMNA=DES_MODULO_CAS
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCMODPRACCAS/CLAUSULA_WHERE= WHERE NUM_EXPEDIENTE=
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCMODPRACCAS/CLAUSULA_WHERE/CAMPO=numeroExpediente

1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCMODPRACCAS/TIPO_ETIQUETA=2
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCMODPRACCAS/NOMBRE_ETIQUETA=DESCMODPRACCAS
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCMODPRACCAS/CODIGO_ETIQUETA=EXPEDIENTE_DESCMODPRACCAS
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCMODPRACCAS/SQL_ETIQUETA=SELECT DES_MODULO_CAS FROM MELANBIDE40_CERTIFICADO
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCMODPRACCAS/SQL_NOMBRE_COLUMNA=DES_MODULO_CAS
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCMODPRACCAS/CLAUSULA_WHERE= WHERE NUM_EXPEDIENTE=
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCMODPRACCAS/CLAUSULA_WHERE/CAMPO=numeroExpediente

#DESCRIPCION MODULO PRACTICAS EUSKERA
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCMODPRACEUS/TIPO_ETIQUETA=2
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCMODPRACEUS/NOMBRE_ETIQUETA=DESCMODPRACEUS
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCMODPRACEUS/CODIGO_ETIQUETA=EXPEDIENTE_DESCMODPRACEUS
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCMODPRACEUS/SQL_ETIQUETA=SELECT DES_MODULO_EUS FROM MELANBIDE40_CERTIFICADO
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCMODPRACEUS/SQL_NOMBRE_COLUMNA=DES_MODULO_EUS
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCMODPRACEUS/CLAUSULA_WHERE= WHERE NUM_EXPEDIENTE=
0/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCMODPRACEUS/CLAUSULA_WHERE/CAMPO=numeroExpediente

1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCMODPRACEUS/TIPO_ETIQUETA=2
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCMODPRACEUS/NOMBRE_ETIQUETA=DESCMODPRACEUS
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCMODPRACEUS/CODIGO_ETIQUETA=EXPEDIENTE_DESCMODPRACEUS
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCMODPRACEUS/SQL_ETIQUETA=SELECT DES_MODULO_EUS FROM MELANBIDE40_CERTIFICADO
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCMODPRACEUS/SQL_NOMBRE_COLUMNA=DES_MODULO_EUS
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCMODPRACEUS/CLAUSULA_WHERE= WHERE NUM_EXPEDIENTE=
1/MODULO_INTEGRACION/MELANBIDE40/EMPNL/PLANTILLA_NORMAL/MELANBIDE40_ETIQUETA_DESCMODPRACEUS/CLAUSULA_WHERE/CAMPO=numeroExpediente