##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE81/LISTA_OPERACIONES_DISPONIBLES=
1/MODULO_INTEGRACION/MELANBIDE81/LISTA_OPERACIONES_DISPONIBLES=

##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE81

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE81/DESCRIPCION_MODULO = ACCIONES LOCALES PROMOCI\u00d3N DE EMPLEO - LPEEL
1/MODULO_INTEGRACION/MELANBIDE81/DESCRIPCION_MODULO = ACCIONES LOCALES PROMOCI\u00d3N DE EMPLEO - LPEEL

##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE81/LPEEL/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = M81_LPEEL;PESTANA_APORTACION_CONTRATACIONES
1/MODULO_INTEGRACION/MELANBIDE81/LPEEL/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = M81_LPEEL;PESTANA_APORTACION_CONTRATACIONES

##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE81/LPEEL/URL_PANTALLA_EXPEDIENTE/M81_LPEEL = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE81&operacion=cargarPantallaLPEEL&tipo=0
1/MODULO_INTEGRACION/MELANBIDE81/LPEEL/URL_PANTALLA_EXPEDIENTE/M81_LPEEL = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE81&operacion=cargarPantallaLPEEL&tipo=0
0/MODULO_INTEGRACION/MELANBIDE81/LPEEL/URL_PANTALLA_EXPEDIENTE/PESTANA_APORTACION_CONTRATACIONES = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE81&operacion=cargarPantallaAportacionContrataciones&tipo=0
1/MODULO_INTEGRACION/MELANBIDE81/LPEEL/URL_PANTALLA_EXPEDIENTE/PESTANA_APORTACION_CONTRATACIONES = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE81&operacion=cargarPantallaAportacionContrataciones&tipo=0

##################### NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE #####################
0/MODULO_INTEGRACION/MELANBIDE81/LPEEL/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/M81_LPEEL =
1/MODULO_INTEGRACION/MELANBIDE81/LPEEL/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/M81_LPEEL =
0/MODULO_INTEGRACION/MELANBIDE81/LPEEL/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/PESTANA_APORTACION_CONTRATACIONES =
1/MODULO_INTEGRACION/MELANBIDE81/LPEEL/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/PESTANA_APORTACION_CONTRATACIONES =

##################### NOMBRE DE LA OPERACION DEL MODULO QUE SE ENCARGA DE ACTUALIZAR LOS DATOS DE LA PANTALLA DE EXPEDIENTE #####################
0/MODULO_INTEGRACION/MELANBIDE81/LPEEL/ACTUALIZAR_PANTALLA_EXPEDIENTE/M81_LPEEL = 
1/MODULO_INTEGRACION/MELANBIDE81/LPEEL/ACTUALIZAR_PANTALLA_EXPEDIENTE/M81_LPEEL = 
0/MODULO_INTEGRACION/MELANBIDE81/LPEEL/ACTUALIZAR_PANTALLA_EXPEDIENTE/PESTANA_APORTACION_CONTRATACIONES = 
1/MODULO_INTEGRACION/MELANBIDE81/LPEEL/ACTUALIZAR_PANTALLA_EXPEDIENTE/PESTANA_APORTACION_CONTRATACIONES = 

# NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE DE UNA RELACI\u00d3N ENTRE EXPEDIENTES
0/MODULO_INTEGRACION/MELANBIDE81/LPEEL/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR=
1/MODULO_INTEGRACION/MELANBIDE81/LPEEL/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR=

##################### TABLAS DEL M\u00d3DULO #####################
TAB_PROYECTOS=MELANBIDE81_PROYECTOS
TAB_PUESTOS=MELANBIDE81_PUESTOS
TAB_CONTRATOS=MELANBIDE81_CONTRATACIONES
TAB_TIPO1=MELANBIDE81_TIPO1
TAB_TIPO2=MELANBIDE81_TIPO2

TABLA_CODIGOS_DESPLEGABLES=E_DES
TABLA_VALORES_DESPLEGABLES=E_DES_VAL

##################### C\u00d6DIGOS DESPLEGABLES - LPEEL #####################
COD_TIPO_PROY=TPLP
COD_TIPO_DESE=TPDL
COD_SEXO=SEXO
COD_GCON=GCON
#BOOL (S/N)
COD_DES_BOOL=BOOL
COD_DES_TCLE=TCLE
COD_DES_CLEP=CLEP

##################### NOMBRES DE SECUENCIAS #####################
SEQ_PROYECTOS=SEQ_MELANBIDE81_PROYECTOS
SEQ_PUESTOS=SEQ_MELANBIDE81_PUESTOS
SEQ_CONTRATOS=SEQ_MELANBIDE81_CONTRATACIONES
SEQ_TIPO1=SEQ_MELANBIDE81_TIPO1
SEQ_TIPO2=SEQ_MELANBIDE81_TIPO2

##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide81.i18n.text
FICHEROS_MENSAJES = MELANBIDE81_TEXT_1;MELANBIDE81_TEXT_4

# EL caracter es pipeline hay que escaparlo porque es un caracter especial para hacer condicion or en regex
BARRA_SEPARADORA_IDIOMA=\\Q|\\E

### OTROS
CARACTERES_ESPECIALES=&'<>|^\\%