##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE86/LISTA_OPERACIONES_DISPONIBLES=
1/MODULO_INTEGRACION/MELANBIDE86/LISTA_OPERACIONES_DISPONIBLES=

##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE86

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE86/DESCRIPCION_MODULO = PROGRAMA INVESTIGO - IKER
1/MODULO_INTEGRACION/MELANBIDE86/DESCRIPCION_MODULO = PROGRAMA INVESTIGO - IKER

##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE86/IKER/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CONTRATACIONES;VIDA_LABORAL
1/MODULO_INTEGRACION/MELANBIDE86/IKER/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CONTRATACIONES;VIDA_LABORAL

##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE86/IKER/URL_PANTALLA_EXPEDIENTE/CONTRATACIONES = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE86&operacion=cargarPantallaPrincipal&tipo=0
1/MODULO_INTEGRACION/MELANBIDE86/IKER/URL_PANTALLA_EXPEDIENTE/CONTRATACIONES = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE86&operacion=cargarPantallaPrincipal&tipo=0

0/MODULO_INTEGRACION/MELANBIDE86/IKER/URL_PANTALLA_EXPEDIENTE/VIDA_LABORAL = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE86&operacion=cargarVidaLaboral&tipo=0
1/MODULO_INTEGRACION/MELANBIDE86/IKER/URL_PANTALLA_EXPEDIENTE/VIDA_LABORAL = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE86&operacion=cargarVidaLaboral&tipo=0

##################### TABLAS  #####################
MELANBIDE86_CONTRATACION=MELANBIDE86_CONTRATACION
MELANBIDE86_CONTRATACION_INI=MELANBIDE86_CONTRATACION_INI
MELANBIDE86_CONTRATACION_FIN=MELANBIDE86_CONTRATACION_FIN
TABLA_VALORES_DESPLEGABLES=E_DES_VAL
TABLA_TIPO_DATO_FICHERO=E_TFI
TABLA_TIPO_DATO_FECHA=E_TFE

### SECUENCIA ID DE TABLA PLANTILLA
SEQ_MELANBIDE86_CONTRATACION=SEQ_MELANBIDE86_CONTRATACION
SEQ_MELANBIDE86_CONTRATA_INI=SEQ_MELANBIDE86_CONTRATA_INI
SEQ_MELANBIDE86_CONTRATA_FIN=SEQ_MELANBIDE86_CONTRATA_FIN

##################### C\u00d3DIGOS DESPLEGABLES  #####################
COD_DES_PEIA=PEIA
COD_DES_GCON=GCON
COD_DES_SEXO=SEXO
COD_DES_CIOI=CIOI

##################### CAMPOS SUPLEMENTARIOS  #####################

##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide86.i18n.text
FICHEROS_MENSAJES = MELANBIDE86_TEXT_1;MELANBIDE86_TEXT_4

# EL caracter es pipeline hay que escaparlo porque es un caracter especial para hacer condicion or en regex
BARRA_SEPARADORA_IDIOMA=\\Q|\\E

#######################CAMPOS CALCULADOS PARA PLANTILLAS###############################################
#El tipo_etiqueta nos indica el tipo de dato de la etiqueta (lo queremos para saber como formatear) (1->Entero, 2->String, 3-> Fecha, 4->Lista)
0/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/ETIQUETAS=IKER_ETIQUETA_LISTAREQEUS;IKER_ETIQUETA_LISTAREQ;IKER_ETIQUETA_TABLAPUESTOS

#etiqueta LISTAREQEUS, euskera
0/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQEUS/TIPO_ETIQUETA=2
0/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQEUS/NOMBRE_ETIQUETA=LISTAREQEUS
0/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQEUS/CODIGO_ETIQUETA=LISTAREQEUS
0/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQEUS/SQL_ETIQUETA=SELECT RTRIM (XMLAGG (XMLELEMENT (E,DESCRIPCION||'-'||TTLT_VALOR|| CHR(13))).EXTRACT ('//text()').GETCLOBVAL(),',') AS REQUISITOS FROM E_TDET INNER JOIN PLANTILLA_DESCLARGA ON CODIGO  = TDET_COD AND IDIOMA ='eu' and procedimiento=TDET_PRO LEFT JOIN E_TTLT ON SUBSTR(TTLT_COD,4,LENGTH(TTLT_COD))=TDET_COD AND TTLT_TRA=TDET_TRA AND TDET_PRO=TTLT_PRO
0/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQEUS/SQL_NOMBRE_COLUMNA=REQUISITOS
0/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQEUS/CLAUSULA_WHERE= WHERE tdet_num=
0/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQEUS/CLAUSULA_WHERE/CAMPO=numeroExpediente
0/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQEUS/CLAUSULA_AND3=and procedimiento=TDET_PRO AND E_TDET.TDET_PRO='IKER' AND TDET_TRA=7 AND TDET_VALOR='X' AND tdet_ocu = (SELECT MAX(cro_ocu) FROM E_CRO WHERE cro_tra = 7 AND CRO_NUM=tdet_num)
#etiqueta LISTAREQ, castellano
0/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQ/TIPO_ETIQUETA=2
0/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQ/NOMBRE_ETIQUETA=LISTAREQ
0/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQ/CODIGO_ETIQUETA=LISTAREQ
0/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQ/SQL_ETIQUETA=SELECT RTRIM (XMLAGG (XMLELEMENT (E,DESCRIPCION||'-'||TTLT_VALOR|| CHR(13))).EXTRACT ('//text()').GETCLOBVAL(),',') AS REQUISITOS FROM E_TDET INNER JOIN PLANTILLA_DESCLARGA ON CODIGO  = TDET_COD AND IDIOMA ='es' and procedimiento=TDET_PRO LEFT JOIN E_TTLT ON SUBSTR(TTLT_COD,4,LENGTH(TTLT_COD))=TDET_COD AND TTLT_TRA=TDET_TRA AND TDET_PRO=TTLT_PRO
0/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQ/SQL_NOMBRE_COLUMNA=REQUISITOS
0/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQ/CLAUSULA_WHERE= WHERE tdet_num=
0/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQ/CLAUSULA_WHERE/CAMPO=numeroExpediente
0/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQ/CLAUSULA_AND3=and procedimiento=TDET_PRO AND E_TDET.TDET_PRO='IKER' AND TDET_TRA=7 AND TDET_VALOR='X' AND tdet_ocu = (SELECT MAX(cro_ocu) FROM E_CRO WHERE cro_tra = 7 AND CRO_NUM=tdet_num)

#etiqueta TABLAPUESTOS
0/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_TABLAPUESTOS/TIPO_ETIQUETA=2
0/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_TABLAPUESTOS/NOMBRE_ETIQUETA=TABLAPUESTOS
0/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_TABLAPUESTOS/CODIGO_ETIQUETA=TABLAPUESTOS
0/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_TABLAPUESTOS/SQL_ETIQUETA=select RTRIM (XMLAGG (XMLELEMENT (E,sol.num_puesto||'|'||sol.denompuesto1||'|'||sol.titulacion1||'|'||sol.durcontrato1||'|'||sol.grupocotiz1||'|'||fin.subvconcedidalan3|| CHR(13)) order by sol.num_puesto).EXTRACT ('//text()').getclobval(),',') ETIQUETA from melanbide86_contratacion sol left join melanbide86_contratacion_ini ini on ini.num_exp=sol.num_exp and ini.num_puesto=sol.num_puesto left join melanbide86_contratacion_fin fin on fin.num_exp=sol.num_exp and fin.num_puesto=sol.num_puesto
0/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_TABLAPUESTOS/SQL_NOMBRE_COLUMNA=ETIQUETA
0/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_TABLAPUESTOS/CLAUSULA_WHERE= WHERE sol.num_exp=
0/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_TABLAPUESTOS/CLAUSULA_WHERE/CAMPO=numeroExpediente
0/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_TABLAPUESTOS/CLAUSULA_AND3= order by sol.num_puesto

## pre pro
1/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/ETIQUETAS=IKER_ETIQUETA_LISTAREQEUS;IKER_ETIQUETA_LISTAREQ;IKER_ETIQUETA_TABLAPUESTOS

#etiqueta LISTAREQEUS, euskera
1/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQEUS/TIPO_ETIQUETA=2
1/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQEUS/NOMBRE_ETIQUETA=LISTAREQEUS
1/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQEUS/CODIGO_ETIQUETA=LISTAREQEUS
1/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQEUS/SQL_ETIQUETA=SELECT RTRIM (XMLAGG (XMLELEMENT (E,DESCRIPCION||'-'||TTLT_VALOR|| CHR(13))).EXTRACT ('//text()').GETCLOBVAL(),',') AS REQUISITOS FROM E_TDET INNER JOIN PLANTILLA_DESCLARGA ON CODIGO  = TDET_COD AND IDIOMA ='eu' and procedimiento=TDET_PRO LEFT JOIN E_TTLT ON SUBSTR(TTLT_COD,4,LENGTH(TTLT_COD))=TDET_COD AND TTLT_TRA=TDET_TRA AND TDET_PRO=TTLT_PRO
1/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQEUS/SQL_NOMBRE_COLUMNA=REQUISITOS
1/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQEUS/CLAUSULA_WHERE= WHERE tdet_num=
1/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQEUS/CLAUSULA_WHERE/CAMPO=numeroExpediente
1/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQEUS/CLAUSULA_AND3=and procedimiento=TDET_PRO AND E_TDET.TDET_PRO='IKER' AND TDET_TRA=16 AND TDET_VALOR='X' AND tdet_ocu = (SELECT MAX(cro_ocu) FROM E_CRO WHERE cro_tra = 16 AND CRO_NUM=tdet_num)
#etiqueta LISTAREQ, castellano
1/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQ/TIPO_ETIQUETA=2
1/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQ/NOMBRE_ETIQUETA=LISTAREQ
1/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQ/CODIGO_ETIQUETA=LISTAREQ
1/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQ/SQL_ETIQUETA=SELECT RTRIM (XMLAGG (XMLELEMENT (E,DESCRIPCION||'-'||TTLT_VALOR|| CHR(13))).EXTRACT ('//text()').GETCLOBVAL(),',') AS REQUISITOS FROM E_TDET INNER JOIN PLANTILLA_DESCLARGA ON CODIGO  = TDET_COD AND IDIOMA ='es' and procedimiento=TDET_PRO LEFT JOIN E_TTLT ON SUBSTR(TTLT_COD,4,LENGTH(TTLT_COD))=TDET_COD AND TTLT_TRA=TDET_TRA AND TDET_PRO=TTLT_PRO
1/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQ/SQL_NOMBRE_COLUMNA=REQUISITOS
1/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQ/CLAUSULA_WHERE= WHERE tdet_num=
1/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQ/CLAUSULA_WHERE/CAMPO=numeroExpediente
1/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_LISTAREQ/CLAUSULA_AND3=and procedimiento=TDET_PRO AND E_TDET.TDET_PRO='IKER' AND TDET_TRA=16 AND TDET_VALOR='X' AND tdet_ocu = (SELECT MAX(cro_ocu) FROM E_CRO WHERE cro_tra = 16 AND CRO_NUM=tdet_num)

#etiqueta TABLAPUESTOS
1/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_TABLAPUESTOS/TIPO_ETIQUETA=2
1/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_TABLAPUESTOS/NOMBRE_ETIQUETA=TABLAPUESTOS
1/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_TABLAPUESTOS/CODIGO_ETIQUETA=TABLAPUESTOS
1/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_TABLAPUESTOS/SQL_ETIQUETA=select RTRIM (XMLAGG (XMLELEMENT (E,sol.num_puesto||'|'||sol.denompuesto1||'|'||sol.titulacion1||'|'||sol.durcontrato1||'|'||sol.grupocotiz1||'|'||fin.subvconcedidalan3|| CHR(13)) order by sol.num_puesto).EXTRACT ('//text()').getclobval(),',') ETIQUETA from melanbide86_contratacion sol left join melanbide86_contratacion_ini ini on ini.num_exp=sol.num_exp and ini.num_puesto=sol.num_puesto left join melanbide86_contratacion_fin fin on fin.num_exp=sol.num_exp and fin.num_puesto=sol.num_puesto
1/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_TABLAPUESTOS/SQL_NOMBRE_COLUMNA=ETIQUETA
1/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_TABLAPUESTOS/CLAUSULA_WHERE= WHERE sol.num_exp=
1/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_TABLAPUESTOS/CLAUSULA_WHERE/CAMPO=numeroExpediente
1/MODULO_INTEGRACION/MELANBIDE86/IKER/PLANTILLA_NORMAL/IKER_ETIQUETA_TABLAPUESTOS/CLAUSULA_AND3= order by sol.num_puesto