# M\u00e9todos del m\u00f3dulo que se utilizan para configurar el m\u00f3dulo en la pesta\u00f1a "Conf.SW"
0/MODULO_INTEGRACION/MELANBIDE73/LISTA_OPERACIONES_DISPONIBLES=
1/MODULO_INTEGRACION/MELANBIDE73/LISTA_OPERACIONES_DISPONIBLES=

##################### NOMBRE DEL MODULO ###################
NOMBRE_MODULO = MELANBIDE73

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE73/DESCRIPCION_MODULO = CAMBIO UNIDAD TRAMITADORA
1/MODULO_INTEGRACION/MELANBIDE73/DESCRIPCION_MODULO = CAMBIO UNIDAD TRAMITADORA

##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE73/RGI/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CAMBIO_UNIDAD
1/MODULO_INTEGRACION/MELANBIDE73/RGI/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CAMBIO_UNIDAD

0/MODULO_INTEGRACION/MELANBIDE73/APO/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CAMBIO_UNIDAD
1/MODULO_INTEGRACION/MELANBIDE73/APO/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CAMBIO_UNIDAD

0/MODULO_INTEGRACION/MELANBIDE73/REN/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CAMBIO_UNIDAD
1/MODULO_INTEGRACION/MELANBIDE73/REN/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CAMBIO_UNIDAD

0/MODULO_INTEGRACION/MELANBIDE73/REV/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CAMBIO_UNIDAD
1/MODULO_INTEGRACION/MELANBIDE73/REV/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CAMBIO_UNIDAD

0/MODULO_INTEGRACION/MELANBIDE73/RKP/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CAMBIO_UNIDAD
1/MODULO_INTEGRACION/MELANBIDE73/RKP/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CAMBIO_UNIDAD

0/MODULO_INTEGRACION/MELANBIDE73/REI/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CAMBIO_UNIDAD
1/MODULO_INTEGRACION/MELANBIDE73/REI/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CAMBIO_UNIDAD

0/MODULO_INTEGRACION/MELANBIDE73/REC/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CAMBIO_UNIDAD
1/MODULO_INTEGRACION/MELANBIDE73/REC/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CAMBIO_UNIDAD

0/MODULO_INTEGRACION/MELANBIDE73/EXT/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CAMBIO_UNIDAD
1/MODULO_INTEGRACION/MELANBIDE73/EXT/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CAMBIO_UNIDAD

0/MODULO_INTEGRACION/MELANBIDE73/PAC/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CAMBIO_UNIDAD
1/MODULO_INTEGRACION/MELANBIDE73/PAC/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CAMBIO_UNIDAD

0/MODULO_INTEGRACION/MELANBIDE73/PC/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CAMBIO_UNIDAD
1/MODULO_INTEGRACION/MELANBIDE73/PC/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CAMBIO_UNIDAD

##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE73/RGI/URL_PANTALLA_EXPEDIENTE/CAMBIO_UNIDAD = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE73&operacion=unidadRGI&tipo=0
1/MODULO_INTEGRACION/MELANBIDE73/RGI/URL_PANTALLA_EXPEDIENTE/CAMBIO_UNIDAD = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE73&operacion=unidadRGI&tipo=0

0/MODULO_INTEGRACION/MELANBIDE73/APO/URL_PANTALLA_EXPEDIENTE/CAMBIO_UNIDAD = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE73&operacion=unidadRGI&tipo=0
1/MODULO_INTEGRACION/MELANBIDE73/APO/URL_PANTALLA_EXPEDIENTE/CAMBIO_UNIDAD = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE73&operacion=unidadRGI&tipo=0

0/MODULO_INTEGRACION/MELANBIDE73/REN/URL_PANTALLA_EXPEDIENTE/CAMBIO_UNIDAD = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE73&operacion=unidadRGI&tipo=0
1/MODULO_INTEGRACION/MELANBIDE73/REN/URL_PANTALLA_EXPEDIENTE/CAMBIO_UNIDAD = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE73&operacion=unidadRGI&tipo=0

0/MODULO_INTEGRACION/MELANBIDE73/REV/URL_PANTALLA_EXPEDIENTE/CAMBIO_UNIDAD = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE73&operacion=unidadRGI&tipo=0
1/MODULO_INTEGRACION/MELANBIDE73/REV/URL_PANTALLA_EXPEDIENTE/CAMBIO_UNIDAD = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE73&operacion=unidadRGI&tipo=0

0/MODULO_INTEGRACION/MELANBIDE73/RKP/URL_PANTALLA_EXPEDIENTE/CAMBIO_UNIDAD = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE73&operacion=unidadRGI&tipo=0
1/MODULO_INTEGRACION/MELANBIDE73/RKP/URL_PANTALLA_EXPEDIENTE/CAMBIO_UNIDAD = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE73&operacion=unidadRGI&tipo=0

0/MODULO_INTEGRACION/MELANBIDE73/REI/URL_PANTALLA_EXPEDIENTE/CAMBIO_UNIDAD = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE73&operacion=unidadRGI&tipo=0
1/MODULO_INTEGRACION/MELANBIDE73/REI/URL_PANTALLA_EXPEDIENTE/CAMBIO_UNIDAD = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE73&operacion=unidadRGI&tipo=0

0/MODULO_INTEGRACION/MELANBIDE73/REC/URL_PANTALLA_EXPEDIENTE/CAMBIO_UNIDAD = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE73&operacion=unidadRGI&tipo=0
1/MODULO_INTEGRACION/MELANBIDE73/REC/URL_PANTALLA_EXPEDIENTE/CAMBIO_UNIDAD = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE73&operacion=unidadRGI&tipo=0

0/MODULO_INTEGRACION/MELANBIDE73/EXT/URL_PANTALLA_EXPEDIENTE/CAMBIO_UNIDAD = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE73&operacion=unidadRGI&tipo=0
1/MODULO_INTEGRACION/MELANBIDE73/EXT/URL_PANTALLA_EXPEDIENTE/CAMBIO_UNIDAD = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE73&operacion=unidadRGI&tipo=0

0/MODULO_INTEGRACION/MELANBIDE73/PAC/URL_PANTALLA_EXPEDIENTE/CAMBIO_UNIDAD = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE73&operacion=unidadRGI&tipo=0
1/MODULO_INTEGRACION/MELANBIDE73/PAC/URL_PANTALLA_EXPEDIENTE/CAMBIO_UNIDAD = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE73&operacion=unidadRGI&tipo=0

0/MODULO_INTEGRACION/MELANBIDE73/PC/URL_PANTALLA_EXPEDIENTE/CAMBIO_UNIDAD = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE73&operacion=unidadRGI&tipo=0
1/MODULO_INTEGRACION/MELANBIDE73/PC/URL_PANTALLA_EXPEDIENTE/CAMBIO_UNIDAD = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE73&operacion=unidadRGI&tipo=0

##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide73.i18n.text
FICHEROS_MENSAJES = MELANBIDE73_TEXT_1;MELANBIDE73_TEXT_4


################## NOMBRES DE TABLAS ###########################
TABLA_A_UOR = A_UOR
TABLA_E_CRO = E_CRO
TABLA_E_EXP = E_EXP
TABLA_A_UOU = FLBGEN.A_UOU
TABLA_OPERACIONES_EXPEDIENTE = OPERACIONES_EXPEDIENTE
TABLA_A_USU = FLBGEN.A_USU
TABLA_A_OUR = FLBPRU.A_UOR
TABLA_A_GRPUOR = FLBGEN.A_GRPUOR
TABLA_A_USU_GRPUOR = FLBGEN.A_USU_GRPUOR
TABLA_A_UOR_GRPUOR = FLBGEN.A_UOR_GRPUOR
VALUE_UOU_ENT = 1
VALUE_UOU_CAR = 0
VALUE_UOR_ACTIVA = A
VALUE_UOU_USU_ADMIN = 5
VALUE_OFICINA_REGISTRO = 1

########### OFICINAS CUYOS USUARIOS PUEDEN CAMBIAR LA UNIDAD TRAMITADORA
# Pongo 4 en cada entorno porque en PRO son 4 las oficinas

### LOCAL
OFICINA_CENTRAL = RGIAPO
OFICINA_ARABA = RGIOF1
OFICINA_BIZKAIA = RGIOF2
OFICINA_GIPUZKOA = RGIOF3

### DESA
# OFICINA_CENTRAL = RGIAPO
# OFICINA_ARABA = RGIOF1
# OFICINA_BIZKAIA = RGIOF2
# OFICINA_GIPUZKOA = RGIOF3

### PRE
# OFICINA_CENTRAL = RGIREC
# OFICINA_ARABA = RGIVSM
# OFICINA_BIZKAIA = RGIBIB
# OFICINA_GIPUZKOA = RGIDSS

### PRO

# OFICINA_CENTRAL = RGISSCC
# OFICINA_ARABA = RGIOTA
# OFICINA_BIZKAIA = RGIOTB
# OFICINA_GIPUZKOA = RGIOTG