##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE91/LISTA_OPERACIONES_DISPONIBLES=
1/MODULO_INTEGRACION/MELANBIDE91/LISTA_OPERACIONES_DISPONIBLES=

##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE91

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE91/DESCRIPCION_MODULO = MODULO CONTRATACIONES SUBVENCIONES IGCEE
1/MODULO_INTEGRACION/MELANBIDE91/DESCRIPCION_MODULO = MODULO CONTRATACIONES SUBVENCIONES IGCEE

##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE91/IGCEE/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = ACCESOS;SUBVENCION
1/MODULO_INTEGRACION/MELANBIDE91/IGCEE/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = ACCESOS;SUBVENCION


##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE91/IGCEE/URL_PANTALLA_EXPEDIENTE/ACCESOS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE91&operacion=cargarPantallaPrincipal&tipo=0
1/MODULO_INTEGRACION/MELANBIDE91/IGCEE/URL_PANTALLA_EXPEDIENTE/ACCESOS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE91&operacion=cargarPantallaPrincipal&tipo=0

0/MODULO_INTEGRACION/MELANBIDE91/IGCEE/URL_PANTALLA_EXPEDIENTE/SUBVENCION = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE91&operacion=cargarPantallaPrincipalSubvenciones&tipo=0
1/MODULO_INTEGRACION/MELANBIDE91/IGCEE/URL_PANTALLA_EXPEDIENTE/SUBVENCION = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE91&operacion=cargarPantallaPrincipalSubvenciones&tipo=0

##################### TABLAS DEL M\u00d3DULO #####################
MELANBIDE91_CONTR_GEN = MELANBIDE91_CONTR_GEN
MELANBIDE91_SUBVEN_SOLIC = MELANBIDE91_SUBVEN_SOLIC
TABLA_CODIGOS_DESPLEGABLES=E_DES
TABLA_VALORES_DESPLEGABLES=E_DES_VAL

### SECUENCIAS ID DE TABLAS CONTRATACION
SEQ_MELANBIDE91_CONTR_GEN = SEQ_MELANBIDE91_CONTR_GEN
SEQ_MELANBIDE91_SUBVEN_SOLIC = SEQ_MELANBIDE91_SUBVEN_SOLIC

##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide91.i18n.text
FICHEROS_MENSAJES = MELANBIDE91_TEXT_1;MELANBIDE91_TEXT_4

##################### C\u00d3DIGOS DESPLEGABLES - IGCEE #####################
#SEXO - SEXO 
0/MODULO_INTEGRACION/MELANBIDE91/IGCEE/COD_DES_SEXO=SEXO
1/MODULO_INTEGRACION/MELANBIDE91/IGCEE/COD_DES_SEXO=SEXO


#JORN - JORN 
0/MODULO_INTEGRACION/MELANBIDE91/IGCEE/COD_DES_JORN=JORN
1/MODULO_INTEGRACION/MELANBIDE91/IGCEE/COD_DES_JORN=JORN

#DATOS - DATOS
0/MODULO_INTEGRACION/MELANBIDE91/IGCEE/COD_DES_DATOS=TDAT
1/MODULO_INTEGRACION/MELANBIDE91/IGCEE/COD_DES_DATOS=TDAT

0/MODULO_INTEGRACION/MELANBIDE91/IGCEE/CODIGO_DESPLEGABLE_BOOLEAN=BOOL
1/MODULO_INTEGRACION/MELANBIDE91/IGCEE/CODIGO_DESPLEGABLE_BOOLEAN=BOOL0

#PEN2 - PEN2 
1/MODULO_INTEGRACION/MELANBIDE91/IGCEE/COD_DES_PEN2=PEN2
0/MODULO_INTEGRACION/MELANBIDE91/IGCEE/COD_DES_PEN2=PEN2

# EL caracter es pipeline hay que escaparlo porque es un caracter especial para hacer condicion or en regex
BARRA_SEPARADORA_IDIOMA_DESPLEGABLES=\\Q|\\E

### OTROS
CARACTERES_ESPECIALES=&'<>|^\\%

