##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE76/LISTA_OPERACIONES_DISPONIBLES=
1/MODULO_INTEGRACION/MELANBIDE76/LISTA_OPERACIONES_DISPONIBLES=

##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE76

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE76/DESCRIPCION_MODULO = MODULO CONTRATACION DLDUR
1/MODULO_INTEGRACION/MELANBIDE76/DESCRIPCION_MODULO = MODULO CONTRATACION DLDUR

##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE76/DLDUR/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CONTRATACION;SUBVENCIONES_MINIMIS
1/MODULO_INTEGRACION/MELANBIDE76/DLDUR/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = CONTRATACION;SUBVENCIONES_MINIMIS

##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE76/DLDUR/URL_PANTALLA_EXPEDIENTE/CONTRATACION = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE76&operacion=cargarPantallaPrincipal&tipo=0
1/MODULO_INTEGRACION/MELANBIDE76/DLDUR/URL_PANTALLA_EXPEDIENTE/CONTRATACION = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE76&operacion=cargarPantallaPrincipal&tipo=0

0/MODULO_INTEGRACION/MELANBIDE76/DLDUR/URL_PANTALLA_EXPEDIENTE/SUBVENCIONES_MINIMIS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE76&operacion=cargarPantallaMinimis&tipo=0
1/MODULO_INTEGRACION/MELANBIDE76/DLDUR/URL_PANTALLA_EXPEDIENTE/SUBVENCIONES_MINIMIS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE76&operacion=cargarPantallaMinimis&tipo=0

##################### TABLAS DEL M\u00d3DULO #####################
MELANBIDE76_CONTRATACION=MELANBIDE76_CONTRATACION
MELANBIDE76_SUBSOLIC=MELANBIDE76_SUBSOLIC
TABLA_CODIGOS_DESPLEGABLES=E_DES
TABLA_VALORES_DESPLEGABLES=E_DES_VAL

TABLA_CODIGOS_DESPLEGABLES_EXTERNOS=DESPLEGABLE_EXTERNO

##################### C\u00d3DIGOS DESPLEGABLES - DLDUR #####################
#SEXO
COD_DES_SEXO=SEXO

#BOOL (S/N)
COD_DES_BOOL=BOOL

#JORN (TIPO JORNADA - COMPLETA/PARCIAL)
COD_DES_JORN=JORN

#GCOT (GRUPO COTIZACI\u00d3N)
COD_DES_GCOT=GCOT

#DTRT (TIPO RETRIBUCI\u00d3N - ANUAL/MENSUAL)
COD_DES_DTRT=DTRT

#DTSV (ESTADO DE LA AYUDA - SOLICITADA/CONCEDIDA)
COD_DES_DTSV=DTSV

##################### C\u00d3DIGOS DESPLEGABLES EXTERNOS - DLDUR #####################
#OCIN - GEN_OCUPACS_ALTER (OCUPACI\u00d3N)
COD_DES_EXT_OCIN=OCIN

#TIIN - GEN_TITULACIONES (TITULACI\u00d3N)
#se modifica TIIN por TITI
COD_DES_EXT_TIIN=TITI

#CPIN - GEN_CERTIF_PROF (CERTIFICADO PROFESIONAL)
COD_DES_EXT_CPIN=CPIN


### SECUENCIA ID DE TABLA CONTRATACION
SEQ_MELANBIDE76_CONTRATACION=SEQ_MELANBIDE76_CONTRATACION
SEQ_MELANBIDE76_SUBSOLIC=SEQ_MELANBIDE76_SUBSOLIC

##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide76.i18n.text
FICHEROS_MENSAJES = MELANBIDE76_TEXT_1;MELANBIDE76_TEXT_4

# EL caracter es pipeline hay que escaparlo porque es un caracter especial para hacer condicion or en regex
BARRA_SEPARADORA_IDIOMA_DESPLEGABLES=\\Q|\\E

### OTROS
CARACTERES_ESPECIALES=&'<>|^\\%











