##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE64/LISTA_OPERACIONES_DISPONIBLES=cerrarTramites;impedirAvanceManualNotifTel;impedirAvanceManualTramite;inicioExpedienteREINT;copiadoCamposTramiteExp;cargaCamposExpTramite;impedirRetrocederTramiteAbierto
1/MODULO_INTEGRACION/MELANBIDE64/LISTA_OPERACIONES_DISPONIBLES=cerrarTramites;impedirAvanceManualNotifTel;impedirAvanceManualTramite;inicioExpedienteREINT;copiadoCamposTramiteExp;cargaCamposExpTramite;impedirRetrocederTramiteAbierto

#####URL_WS_REGISTRO#########################################################################
#URL_WS_REGISTRO=http://10.168.212.21:7081/WSTramitacion/services/WSTramitacionPort?wsdl
URL_WS_REGISTRO=http://integ.serv.des.lanbide.lan/WSTramitacion/services/WSTramitacionPort?wsdl
#PRO
#URL_WS_REGISTRO=http://integ.serv.lanbide.lan/WSTramitacion/services/WSTramitacionPort?wsdl


##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE64




##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE64/DESCRIPCION_MODULO = M\u00f3dulo de operaciones de gesti\u00f3n de flujo
1/MODULO_INTEGRACION/MELANBIDE64/DESCRIPCION_MODULO = M\u00f3dulo de operaciones de gesti\u00f3n de flujo

##################### NOMBRES DE TABLAS #####################
TABLA_E_CRO=E_CRO
TABLA_TRAMITES=E_TRA
TABLA_VALORDESPLEGCAMPOSUPL=E_TDE
TABLA_VALORNUMCAMPOSUPL=E_TNU
TABLA_RELACIONEXPTSFLEXIA=E_REX
TABLA_RELACIONTERCEROSXEXPTS=E_EXT

TABLA_TERCEROS=T_TER
TABLA_TERCEROS_HIST=T_HTE
TABLA_REL_TERCERO_DOMICILIO=E_EXT
TABLA_DOMICILIO=T_DNN
TABLA_T_DOT=T_DOT
TABLA_E_TNU=E_TNU
TABLA_E_TFE=E_TFE
TABLA_E_EXP=E_EXP
TABLA_E_EXR=E_EXR
TABLA_R_RES=R_RES
TABLA_T_VIA=T_VIA
TABLA_SUPLEMENTARIOS_PROCEDIMIENTO=E_PCA
TABLA_E_TXT=E_TXT
TABLA_E_TTL=E_TTL
TABLA_E_TFI=E_TFI
TABLA_E_TNUC=E_TNUC
TABLA_E_TFEC=E_TFEC
TABLA_E_TDE=E_TDE
TABLA_E_TDEX=E_TDEX

###### TABLAS DE SUPLEMENTARIOS DE TRAMITES ######

TABLA_E_TCA=E_TCA
TABLA_E_TNUT=E_TNUT
TABLA_E_TXTT=E_TXTT
TABLA_E_TFET=E_TFET
TABLA_E_TTLT=E_TTLT
TABLA_E_TFIT=E_TFIT
TABLA_E_TDET=E_TDET
TABLA_E_TNUCT=E_TNUCT
TABLA_E_TFECT=E_TFECT
TABLA_E_TDEXT=E_TDEXT

##################### CAMPOS SUPLEMENTARIOS #####################

CAMPO_SUPL_FECREGSALIDA=FECREGSALIDA
CAMPO_SUPL_NUMREGSALIDA=NUMREGSALIDA

#################### NOMBRES DE SECUENCIAS #####################

##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide64.i18n.text
FICHEROS_MENSAJES = MELANBIDE64_TEXT_1;MELANBIDE64_TEXT_4

##################################################################################################################################
##################     CODIGOS DE ERROR PARA LA OPERACION IMPEDIR AVANCE MANUAL NOTIFICACION TELEMATICA       ####################
##################################################################################################################################

0/MODULO_INTEGRACION/impedirAvanceManualNotifTel/MENSAJE_ERROR/1=ERROR-NOTIFICACION-TELEMATICA
1/MODULO_INTEGRACION/impedirAvanceManualNotifTel/MENSAJE_ERROR/1=ERROR-NOTIFICACION-TELEMATICA

ERROR-NOTIFICACION-TELEMATICA_1=No es posible avanzar manualmente el acuse de recibo de una notificaci\u00f3n telem\u00e1tica.
ERROR-NOTIFICACION-TELEMATICA_4=Ezin da eskuz aurrera egin jakinarazpen telematiko bat jaso izanaren agirian.

##########################################################################################################
##################     CODIGOS DE ERROR PARA LA OPERACION IMPEDIR AVANCE MANUAL       ####################
##########################################################################################################
0/MODULO_INTEGRACION/impedirAvanceManualTramite/MENSAJE_ERROR/1=ERROR-AVANCE_MANUAL
1/MODULO_INTEGRACION/impedirAvanceManualTramite/MENSAJE_ERROR/1=ERROR-AVANCE_MANUAL

AVANCE_MANUAL_1=No es posible avanzar manualmente este tr\u00e1mite.
AVANCE_MANUAL_4=Izapide hori ezin da eskuz egin.

##################     CODIGOS DE ERROR PARA LA OPERACION inicioExpedienteREINT       ####################
0/MODULO_INTEGRACION/inicioExpedienteREINT/MENSAJE_ERROR/5=ERROR-INICIO-EXPEDIENTE-REINT
1/MODULO_INTEGRACION/inicioExpedienteREINT/MENSAJE_ERROR/5=ERROR-INICIO-EXPEDIENTE-REINT

0/MODULO_INTEGRACION/inicioExpedienteREINT/MENSAJE_ERROR/6=ERROR-WS-INICIO-EXPEDIENTE-REINT
1/MODULO_INTEGRACION/inicioExpedienteREINT/MENSAJE_ERROR/6=ERROR-WS-INICIO-EXPEDIENTE-REINT

0/MODULO_INTEGRACION/inicioExpedienteREINT/MENSAJE_ERROR/7=ERROR-WS-RELACIONAR-EXPEDIENTES
1/MODULO_INTEGRACION/inicioExpedienteREINT/MENSAJE_ERROR/7=ERROR-WS-RELACIONAR-EXPEDIENTES

ERROR-INICIO-EXPEDIENTE-REINT_1=No se ha dado de alta la convocatoria del ejercicio del expediente para este procedimiento. Debe hablar con el Area Econ\u00f3mica.
ERROR-INICIO-EXPEDIENTE-REINT_4=Ez zaio alta eman prozedura honetarako espedientearen ekitaldiko deialdiari. Arlo Ekonomikoarekin hitz egin behar duzu.

ERROR-WS-INICIO-EXPEDIENTE-REINT_1=No se ha podido iniciar el expediente del procedimiento REINT.
ERROR-WS-INICIO-EXPEDIENTE-REINT_4=Ezin izan da REINT prozeduraren espedientea hasi.

ERROR-WS-RELACIONAR-EXPEDIENTES_1=No se han podido relacionar los expedientes.
ERROR-WS-RELACIONAR-EXPEDIENTES_4=Ezin izan dira espedienteak erlazionatu.

######### errores copiadoCamposTramiteExp

0/MODULO_INTEGRACION/copiadoCamposTramiteExp/MENSAJE_ERROR/1=ERROR-COPIADO-BBDD
1/MODULO_INTEGRACION/copiadoCamposTramiteExp/MENSAJE_ERROR/1=ERROR-COPIADO-BBDD

0/MODULO_INTEGRACION/copiadoCamposTramiteExp/MENSAJE_ERROR/2=ERROR-COPIADO-CARGA
1/MODULO_INTEGRACION/copiadoCamposTramiteExp/MENSAJE_ERROR/2=ERROR-COPIADO-CARGA

0/MODULO_INTEGRACION/copiadoCamposTramiteExp/MENSAJE_ERROR/3=ERROR-COPIADO-GENERICO
1/MODULO_INTEGRACION/copiadoCamposTramiteExp/MENSAJE_ERROR/3=ERROR-COPIADO-GENERICO

ERROR-COPIADO-BBDD_1=Se ha producido un error al obtener una conexion a la BBDD en copiadoCamposTramiteExp()
ERROR-COPIADO-BBDD_4=Se ha producido un error al obtener una conexion a la BBDD en copiadoCamposTramiteExp()_EU

ERROR-COPIADO-CARGA_1=Se ha producido un error al obtener datos en copiadoCamposTramiteExp()
ERROR-COPIADO-CARGA_4=Se ha producido un error al obtener datos en copiadoCamposTramiteExp()_EU

ERROR-COPIADO-GENERICO_1=No se han copiado los campos suplementarios del tr\u00e1mite en el expediente.
ERROR-COPIADO-GENERICO_4=Espedientean ez dira kopiatu izapidearen eremu gehigarriak.

######### errores impedirRetrocederTramiteAbierto
0/MODULO_INTEGRACION/impedirRetrocederTramiteAbierto/MENSAJE_ERROR/1=ERROR-TRAMITE-ABIERTO
1/MODULO_INTEGRACION/impedirRetrocederTramiteAbierto/MENSAJE_ERROR/1=ERROR-TRAMITE-ABIERTO

0/MODULO_INTEGRACION/impedirRetrocederTramiteAbierto/MENSAJE_ERROR/2=ERROR-TRAMITE-GENERICO
1/MODULO_INTEGRACION/impedirRetrocederTramiteAbierto/MENSAJE_ERROR/2=ERROR-TRAMITE-GENERICO

ERROR-TRAMITE-ABIERTO_1=No es posible retroceder este tr\u00e1mite.
ERROR-TRAMITE-ABIERTO_4=Izapide hori ezin da atzera egin.

ERROR-TRAMITE-GENERICO_1=Ha ocurrido un error en la operaci\u00f3n impedirRetrocederTramiteAbierto()
ERROR-TRAMITE-GENERICO_4=Errorea gertatu da impedirRetrocederTramiteAbierto () eragiketan

################################################################################
##### CODIGOS DE TRAMITES QUE IMPIDEN RETROCEDER    ############################
################################################################################
#   TRAMITES-IMPIDEN/codProcedimiento = codTramite que impide
# DESA
TRAMITES_IMPIDEN/REV=15

# PRE
# TRAMITES_IMPIDEN/REV=12
