##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE90/LISTA_OPERACIONES_DISPONIBLES=
1/MODULO_INTEGRACION/MELANBIDE90/LISTA_OPERACIONES_DISPONIBLES=

##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE90

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE90/DESCRIPCION_MODULO = MODULO ININ
1/MODULO_INTEGRACION/MELANBIDE90/DESCRIPCION_MODULO = MODULO ININ

##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE90/ININ/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = MINIMIS;FACTURAS
1/MODULO_INTEGRACION/MELANBIDE90/ININ/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = MINIMIS;FACTURAS

##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE90/ININ/URL_PANTALLA_EXPEDIENTE/MINIMIS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE90&operacion=cargarPantallaPrincipal&tipo=0
1/MODULO_INTEGRACION/MELANBIDE90/ININ/URL_PANTALLA_EXPEDIENTE/MINIMIS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE90&operacion=cargarPantallaPrincipal&tipo=0

0/MODULO_INTEGRACION/MELANBIDE90/ININ/URL_PANTALLA_EXPEDIENTE/FACTURAS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE90&operacion=cargarPantallaFacturas&tipo=0
1/MODULO_INTEGRACION/MELANBIDE90/ININ/URL_PANTALLA_EXPEDIENTE/FACTURAS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE90&operacion=cargarPantallaFacturas&tipo=0

##################### TABLAS DEL M\u00d3DULO #####################
MELANBIDE90_SUBSOLIC=MELANBIDE90_SUBSOLIC
TABLA_FACTURAS=MELANBIDE90_FACTURAS
TABLA_MAXIMOS=MELANBIDE90_IMPORTES_EJE
TABLA_VALORES_DESPLEGABLES=E_DES_VAL
TABLA_DESPLEGABLES_EXP=E_TDE
TABLA_DESPLEGABLES_EXT=E_TDEX
TABLA_NUMERICOS_EXPEDIENTE=E_TNU
TABLA_TERCERO_EXP=E_EXT
TABLA_TERCEROS=T_HTE
TABLA_FAMILIAS=FPE_FAMILIA_ACTIVA
VISTA_ESP_FAMILIA=S_VW_REGEXLAN_ININ_ESP_CIFS_FAMILIA
VISTA_AFS_FAMILIA=S_VW_REGEXLAN_ININ_AFS_CIFS_FAMILIA

### SECUENCIAS ID DE TABLAS 
SEQ_MELANBIDE90_SUBSOLIC=SEQ_MELANBIDE90_SUBSOLIC
SEQ_FACTURAS=SEQ_M90_FACTURAS

##################### C\u00d3DIGOS DESPLEGABLES  #####################
COD_DES_ESTADO_AYUDA=DTSV
COD_DES_GASTO=TIGF
COD_DES_MODALIDAD=MOIN
COD_DES_BOOL=BOOL
COD_DES_MOTIVO=MONO
COD_DES_PORCIVA=PIVA

##################### C\u00d3DIGOS DESPLEGABLES EXTERNOS #####################
COD_DES_FAMILIA=FFAM

##################### C\u00d3DIGOS SUPLEMENTARIOS #####################
COD_CAMPO_MODALIDAD=MODALIDAD
PREF_CAMPO_FAMILIA=FAMILIA
PREF_CAMPO_VALIDADO=VALIDADO
PREF_CAMPO_ESPECIALIDADES=ESPECIALIDADES
PREF_CAMPO_MEDIA=MEDIA
PREF_CAMPO_PORCENTAJE=PORCENTAJE
PREF_CAMPO_SUBVCALCU=SUBVCALCU
PREF_CAMPO_SUBVCONCE=SUBVCONCE
COD_CAMPO_MAX_MINIMIS=MINIMISMAX
COD_CAMPO_MINIMIS=MINIMIS
COD_CAMPO_SUBVTOTAL=SUBVTOTAL
COD_CAMPO_SUBVFINAL=SUBVFINAL

## ETIQUETAS
#DESA
0/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ETIQUETAS=ININ_ETIQUETA_ININMOTDENEGCAST;ININ_ETIQUETA_ININMOTDENEGEUSK

## ININMOTDENEGCAST
0/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGCAST/TIPO_ETIQUETA=2
0/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGCAST/NOMBRE_ETIQUETA=ININMOTDENEGCAST
0/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGCAST/CODIGO_ETIQUETA=ININMOTDENEGCAST
0/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGCAST/SQL_ETIQUETA=select '- '||REGEXP_SUBSTR(des_nom, '[^|]*', 1, 1) as MOTDENEG from e_tdet inner join e_des_val on e_des_val.des_val_cod=e_tdet.tdet_valor
0/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGCAST/SQL_NOMBRE_COLUMNA=MOTDENEG
0/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGCAST/CLAUSULA_WHERE=where tdet_num=
0/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGCAST/CLAUSULA_WHERE/CAMPO=numeroExpediente
0/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGCAST/CLAUSULA_AND3=and tdet_tra=4 and e_des_val.des_cod='MDAT'

## ININMOTDENEGEUSK
0/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGEUSK/TIPO_ETIQUETA=2
0/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGEUSK/NOMBRE_ETIQUETA=ININMOTDENEGEUSK
0/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGEUSK/CODIGO_ETIQUETA=ININMOTDENEGEUSK
0/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGEUSK/SQL_ETIQUETA=select '- '||REGEXP_SUBSTR(des_nom, '[^|]*', 1, 3) as MOTDENEG from e_tdet inner join e_des_val on e_des_val.des_val_cod=e_tdet.tdet_valor
0/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGEUSK/SQL_NOMBRE_COLUMNA=MOTDENEG
0/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGEUSK/CLAUSULA_WHERE=where tdet_num=
0/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGEUSK/CLAUSULA_WHERE/CAMPO=numeroExpediente
0/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGEUSK/CLAUSULA_AND3=and tdet_tra=4 and e_des_val.des_cod='MDAT'

#PRE / PRO
1/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ETIQUETAS=ININ_ETIQUETA_ININMOTDENEGCAST;ININ_ETIQUETA_ININMOTDENEGEUSK

## ININMOTDENEGCAST
1/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGCAST/TIPO_ETIQUETA=2
1/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGCAST/NOMBRE_ETIQUETA=ININMOTDENEGCAST
1/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGCAST/CODIGO_ETIQUETA=ININMOTDENEGCAST
1/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGCAST/SQL_ETIQUETA=select '- '||REGEXP_SUBSTR(des_nom, '[^|]*', 1, 1) as MOTDENEG from e_tdet inner join e_des_val on e_des_val.des_val_cod=e_tdet.tdet_valor
1/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGCAST/SQL_NOMBRE_COLUMNA=MOTDENEG
1/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGCAST/CLAUSULA_WHERE=where tdet_num=
1/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGCAST/CLAUSULA_WHERE/CAMPO=numeroExpediente
1/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGCAST/CLAUSULA_AND3=and tdet_tra=6 and e_des_val.des_cod='MDAT'

## ININMOTDENEGEUSK
1/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGEUSK/TIPO_ETIQUETA=2
1/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGEUSK/NOMBRE_ETIQUETA=ININMOTDENEGEUSK
1/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGEUSK/CODIGO_ETIQUETA=ININMOTDENEGEUSK
1/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGEUSK/SQL_ETIQUETA=select '- '||REGEXP_SUBSTR(des_nom, '[^|]*', 1, 3) as MOTDENEG from e_tdet inner join e_des_val on e_des_val.des_val_cod=e_tdet.tdet_valor
1/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGEUSK/SQL_NOMBRE_COLUMNA=MOTDENEG
1/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGEUSK/CLAUSULA_WHERE=where tdet_num=
1/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGEUSK/CLAUSULA_WHERE/CAMPO=numeroExpediente
1/MODULO_INTEGRACION/MELANBIDE90/ININ/PLANTILLA_NORMAL/ININ_ETIQUETA_ININMOTDENEGEUSK/CLAUSULA_AND3=and tdet_tra=6 and e_des_val.des_cod='MDAT'

##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide90.i18n.text
FICHEROS_MENSAJES = MELANBIDE90_TEXT_1;MELANBIDE90_TEXT_4

# EL caracter es pipeline hay que escaparlo porque es un caracter especial para hacer condicion or en regex
BARRA_SEPARADORA_IDIOMA=\\Q|\\E
