##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE80/LISTA_OPERACIONES_DISPONIBLES=
1/MODULO_INTEGRACION/MELANBIDE80/LISTA_OPERACIONES_DISPONIBLES=

##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE80

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE80/DESCRIPCION_MODULO = MODULO PERSONAS AEXCE
1/MODULO_INTEGRACION/MELANBIDE80/DESCRIPCION_MODULO = MODULO PERSONAS AEXCE

##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE80/AEXCE/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = PERSONAS
1/MODULO_INTEGRACION/MELANBIDE80/AEXCE/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = PERSONAS

##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE80/AEXCE/URL_PANTALLA_EXPEDIENTE/PERSONAS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE80&operacion=cargarPantallaPrincipal&tipo=0
1/MODULO_INTEGRACION/MELANBIDE80/AEXCE/URL_PANTALLA_EXPEDIENTE/PERSONAS = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE80&operacion=cargarPantallaPrincipal&tipo=0

##################### TABLAS DEL M\u00d3DULO #####################
MELANBIDE80_PERSONAS=MELANBIDE80_PERSONAS
TABLA_CODIGOS_DESPLEGABLES=E_DES
TABLA_VALORES_DESPLEGABLES=E_DES_VAL
TABLA_DOCUMENTOS_REGISTRO=R_RED
TABLA_EXPEDIENTE_REGISTRO=E_EXR

##################### C\u00d6DIGOS DESPLEGABLES - AEXCE #####################
##################### TIPO CONTRATO #####################
COD_DES_CTRA=CTRA
##################### JORNADA #####################
COD_DES_JORN=JORN
##################### TIPO ERTE #####################
COD_DES_ERTE=ERTE

### SECUENCIA ID DE TABLA PLANTILLA
SEQ_MELANBIDE80_PERSONAS=SEQ_MELANBIDE80_PERSONAS

##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide80.i18n.text
FICHEROS_MENSAJES = MELANBIDE80_TEXT_1;MELANBIDE80_TEXT_4

# EL caracter es pipeline hay que escaparlo porque es un caracter especial para hacer condicion or en regex
BARRA_SEPARADORA_IDIOMA_DESPLEGABLES=\\Q|\\E

### OTROS
CARACTERES_ESPECIALES=&'<>|^\\%