# M\u00e9todos del m\u00f3dulo que se utilizan para configurar el m\u00f3dulo en la pesta\u00f1a "Conf.SW"
0/MODULO_INTEGRACION/MELANBIDE65/LISTA_OPERACIONES_DISPONIBLES=
1/MODULO_INTEGRACION/MELANBIDE65/LISTA_OPERACIONES_DISPONIBLES=
# NOMBRE DEL M\u00d3DULO QUE SE MUESTRA JUNTO CON EL NOMBRE DE LA OPERACI\u00d3N; A LA HORA DE SELECCIONAR UNA OPERACI\u00d3N QUE SE ASOCIAR\u00c1 A UN TR\u00c1MITE
# FORMATO: [COD_ORGANIZACION]/MODULO_INTEGRACION/[NOMBRE_MODULO]/NOMBRE_MODULO
0/MODULO_INTEGRACION/MELANBIDE65/DESCRIPCION_MODULO = MODULO CONTROL DE ACCESO
1/MODULO_INTEGRACION/MELANBIDE65/DESCRIPCION_MODULO = MODULO CONTROL DE ACCESO

##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE65/UAAP/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = ANEXOA;ANEXOB;ANEXOC;DATOSSUPL_SUB;VIDA_LABORAL
1/MODULO_INTEGRACION/MELANBIDE65/UAAP/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = ANEXOA;ANEXOB;ANEXOC;DATOSSUPL_SUB;VIDA_LABORAL

##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE65/UAAP/URL_PANTALLA_EXPEDIENTE/ANEXOA = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE65&operacion=cargarPantallaAnexoA&tipo=0
1/MODULO_INTEGRACION/MELANBIDE65/UAAP/URL_PANTALLA_EXPEDIENTE/ANEXOA = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE65&operacion=cargarPantallaAnexoA&tipo=0
0/MODULO_INTEGRACION/MELANBIDE65/UAAP/URL_PANTALLA_EXPEDIENTE/ANEXOB = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE65&operacion=cargarPantallaAnexoB&tipo=0
1/MODULO_INTEGRACION/MELANBIDE65/UAAP/URL_PANTALLA_EXPEDIENTE/ANEXOB = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE65&operacion=cargarPantallaAnexoB&tipo=0
0/MODULO_INTEGRACION/MELANBIDE65/UAAP/URL_PANTALLA_EXPEDIENTE/ANEXOC = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE65&operacion=cargarPantallaAnexoC&tipo=0
1/MODULO_INTEGRACION/MELANBIDE65/UAAP/URL_PANTALLA_EXPEDIENTE/ANEXOC = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE65&operacion=cargarPantallaAnexoC&tipo=0
0/MODULO_INTEGRACION/MELANBIDE65/UAAP/URL_PANTALLA_EXPEDIENTE/DATOSSUPL_SUB = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE65&operacion=cargarSubvencion&tipo=0
1/MODULO_INTEGRACION/MELANBIDE65/UAAP/URL_PANTALLA_EXPEDIENTE/DATOSSUPL_SUB = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE65&operacion=cargarSubvencion&tipo=0
0/MODULO_INTEGRACION/MELANBIDE65/UAAP/URL_PANTALLA_EXPEDIENTE/VIDA_LABORAL = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE65&operacion=cargarVidaLaboral&tipo=0
1/MODULO_INTEGRACION/MELANBIDE65/UAAP/URL_PANTALLA_EXPEDIENTE/VIDA_LABORAL = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE65&operacion=cargarVidaLaboral&tipo=0

0/MODULO_INTEGRACION/MELANBIDE65/UAAP/PANTALLA_EXPEDIENTE/SALIDA = /jsp/extension/MELANBIDE65/melanbide65.jsp
1/MODULO_INTEGRACION/MELANBIDE65/UAAP/PANTALLA_EXPEDIENTE/SALIDA = /jsp/extension/MELANBIDE65/melanbide65.jsp

NOMBRE_MODULO = MELANBIDE65

### Definicion de las listas
LISTA_CONTRATO = TICU
LISTA_JORNADA = JORN
LISTA_CONTRATO_B = TINT
LISTA_SEXO = SEXO
LISTA_PENSIONISTA = PENS
BARRA_SEPARADORA_IDIOMA_DESPLEGABLES=\\Q|\\E
### Definicion de tablas del Modulo y Sequencias ID para ellas
MELANBIDE65_TRABAJADOR=MELANBIDE65_TRABAJADOR
SEQ_MELANBIDE65_TRABAJADOR=SEQ_MELANBIDE65_TRABAJADOR

MELANBIDE65_TECNICO=MELANBIDE65_TECNICO
SEQ_MELANBIDE65_TECNICO=SEQ_MELANBIDE65_TECNICO

MELANBIDE65_ENCARGADO=MELANBIDE65_ENCARGADO
SEQ_MELANBIDE65_ENCARGADO=SEQ_MELANBIDE65_ENCARGADO

##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide65.i18n.text
FICHEROS_MENSAJES = MELANBIDE65_TEXT_1;MELANBIDE65_TEXT_4

##################### ETIQUETAS CAMPOS SUPLEMENTARIOS PARA PLANTILLAS #####################
0/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/ETIQUETAS=UAAP_ETIQUETA_LISTAREQ;UAAP_ETIQUETA_LISTAREQEU
1/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/ETIQUETAS=UAAP_ETIQUETA_LISTAREQ;UAAP_ETIQUETA_LISTAREQEU
# cod_tram Notif Requerimiento DESA 7 - PRE y PRO 15
#etiqueta LISTAREQ, castellano 
0/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQ/CODIGO_ETIQUETA=LISTAREQ
0/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQ/NOMBRE_ETIQUETA=LISTAREQ
0/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQ/TIPO_ETIQUETA=2
0/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQ/SQL_ETIQUETA=SELECT RTRIM (XMLAGG (XMLELEMENT (E,DESCRIPCION|| CHR(13))).EXTRACT ('//text()').GETCLOBVAL(),',')  AS REQUISITOS FROM E_TDET INNER JOIN PLANTILLA_DESCLARGA ON CODIGO  = TDET_COD AND IDIOMA ='es' 
0/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQ/SQL_NOMBRE_COLUMNA=REQUISITOS
0/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQ/CLAUSULA_WHERE=WHERE tdet_num=
0/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQ/CLAUSULA_WHERE/CAMPO=numeroExpediente
0/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQ/CLAUSULA_AND3=and procedimiento=TDET_PRO AND E_TDET.TDET_PRO='UAAP' AND TDET_TRA=15 AND TDET_VALOR='X' AND tdet_ocu = (SELECT MAX(cro_ocu) FROM E_CRO WHERE cro_tra = 15 AND CRO_NUM=tdet_num)

1/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQ/CODIGO_ETIQUETA=LISTAREQ
1/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQ/NOMBRE_ETIQUETA=LISTAREQ
1/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQ/TIPO_ETIQUETA=2
1/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQ/SQL_ETIQUETA=SELECT RTRIM (XMLAGG (XMLELEMENT (E,DESCRIPCION|| CHR(13))).EXTRACT ('//text()').GETCLOBVAL(),',')  AS REQUISITOS FROM E_TDET INNER JOIN PLANTILLA_DESCLARGA ON CODIGO  = TDET_COD AND IDIOMA ='es' 
1/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQ/SQL_NOMBRE_COLUMNA=REQUISITOS
1/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQ/CLAUSULA_WHERE=WHERE tdet_num=
1/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQ/CLAUSULA_WHERE/CAMPO=numeroExpediente
1/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQ/CLAUSULA_AND3=and procedimiento=TDET_PRO AND E_TDET.TDET_PRO='UAAP' AND TDET_TRA=15 AND TDET_VALOR='X' AND tdet_ocu = (SELECT MAX(cro_ocu) FROM E_CRO WHERE cro_tra = 15 AND CRO_NUM=tdet_num)

#etiqueta LISTAREQEU, euskera 
0/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQEU/CODIGO_ETIQUETA=LISTAREQEU
0/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQEU/NOMBRE_ETIQUETA=LISTAREQEU
0/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQEU/TIPO_ETIQUETA=2
0/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQEU/SQL_ETIQUETA=SELECT RTRIM (XMLAGG (XMLELEMENT (E,DESCRIPCION|| CHR(13))).EXTRACT ('//text()').GETCLOBVAL(),',')  AS REQUISITOS FROM E_TDET INNER JOIN PLANTILLA_DESCLARGA ON CODIGO  = TDET_COD AND IDIOMA ='eu' 
0/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQEU/SQL_NOMBRE_COLUMNA=REQUISITOS
0/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQEU/CLAUSULA_WHERE=WHERE tdet_num=
0/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQEU/CLAUSULA_WHERE/CAMPO=numeroExpediente
0/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQEU/CLAUSULA_AND3=and procedimiento=TDET_PRO AND E_TDET.TDET_PRO='UAAP' AND TDET_TRA=15 AND TDET_VALOR='X' AND tdet_ocu = (SELECT MAX(cro_ocu) FROM E_CRO WHERE cro_tra = 15 AND CRO_NUM=tdet_num)

1/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQEU/CODIGO_ETIQUETA=LISTAREQEU
1/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQEU/NOMBRE_ETIQUETA=LISTAREQEU
1/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQEU/TIPO_ETIQUETA=2
1/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQEU/SQL_ETIQUETA=SELECT RTRIM (XMLAGG (XMLELEMENT (E,DESCRIPCION|| CHR(13))).EXTRACT ('//text()').GETCLOBVAL(),',')  AS REQUISITOS FROM E_TDET INNER JOIN PLANTILLA_DESCLARGA ON CODIGO  = TDET_COD AND IDIOMA ='eu' 
1/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQEU/SQL_NOMBRE_COLUMNA=REQUISITOS
1/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQEU/CLAUSULA_WHERE=WHERE tdet_num=
1/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQEU/CLAUSULA_WHERE/CAMPO=numeroExpediente
1/MODULO_INTEGRACION/MELANBIDE65/UAAP/PLANTILLA_NORMAL/UAAP_ETIQUETA_LISTAREQEU/CLAUSULA_AND3=and procedimiento=TDET_PRO AND E_TDET.TDET_PRO='UAAP' AND TDET_TRA=15 AND TDET_VALOR='X' AND tdet_ocu = (SELECT MAX(cro_ocu) FROM E_CRO WHERE cro_tra = 15 AND CRO_NUM=tdet_num)


##################### TABLAS DEL M\u00d3DULO #####################

TABLA_CODIGOS_DESPLEGABLES=E_DES
TABLA_VALORES_DESPLEGABLES=E_DES_VAL
TABLA_DOCUMENTOS_REGISTRO=R_RED
TABLA_EXPEDIENTE_REGISTRO=E_EXR
