##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE71/LISTA_OPERACIONES_DISPONIBLES=actualizarDatosSuplementariosAPEA;actualizarDatosAPEAI
1/MODULO_INTEGRACION/MELANBIDE71/LISTA_OPERACIONES_DISPONIBLES=actualizarDatosSuplementariosAPEA;actualizarDatosAPEAI

##################### NOMBRE DEL M\u00d3DULO #####################
NOMBRE_MODULO = MELANBIDE71

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE71/DESCRIPCION_MODULO = Datos suplementarios APEA / APEAI
1/MODULO_INTEGRACION/MELANBIDE71/DESCRIPCION_MODULO = Datos suplementarios APEA / APEAI

##################### NOMBRES DE TABLAS #####################


##################### NOMBRES DE SECUENCIAS #####################


##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide71.i18n.text
FICHEROS_MENSAJES = MELANBIDE71_TEXT_1;MELANBIDE71_TEXT_4

###### ERRORES PERSONALIZADOS DE LA OPERACI\u00d3N actualizarDatosSuplementariosAPEA 
0/MODULO_INTEGRACION/actualizarDatosSuplementariosAPEA/MENSAJE_ERROR/1= ERROR_GENERICO
1/MODULO_INTEGRACION/actualizarDatosSuplementariosAPEA/MENSAJE_ERROR/1= ERROR_GENERICO
0/MODULO_INTEGRACION/actualizarDatosSuplementariosAPEA/MENSAJE_ERROR/2= ERROR_CONEXIONBD
1/MODULO_INTEGRACION/actualizarDatosSuplementariosAPEA/MENSAJE_ERROR/2= ERROR_CONEXIONBD
0/MODULO_INTEGRACION/actualizarDatosSuplementariosAPEA/MENSAJE_ERROR/3= ERROR_DATOSEXPEDIENTE_TERCERO
1/MODULO_INTEGRACION/actualizarDatosSuplementariosAPEA/MENSAJE_ERROR/3= ERROR_DATOSEXPEDIENTE_TERCERO
0/MODULO_INTEGRACION/actualizarDatosSuplementariosAPEA/MENSAJE_ERROR/4= ERROR_DATOSEXPEDIENTE_TERCERO_INCOMPLETO
1/MODULO_INTEGRACION/actualizarDatosSuplementariosAPEA/MENSAJE_ERROR/4= ERROR_DATOSEXPEDIENTE_TERCERO_INCOMPLETO

###### ERRORES PERSONALIZADOS DE LA OPERACI\u00d3N actualizarDatosAPEAI 
0/MODULO_INTEGRACION/actualizarDatosAPEAI/MENSAJE_ERROR/1= ERROR_GENERICO
0/MODULO_INTEGRACION/actualizarDatosAPEAI/MENSAJE_ERROR/2= ERROR_CONEXIONBD
0/MODULO_INTEGRACION/actualizarDatosAPEAI/MENSAJE_ERROR/3= ERROR_DATOSEXPEDIENTE_TERCERO
0/MODULO_INTEGRACION/actualizarDatosAPEAI/MENSAJE_ERROR/4= ERROR_DATOSEXPEDIENTE_TERCERO_INCOMPLETO
0/MODULO_INTEGRACION/actualizarDatosAPEAI/MENSAJE_ERROR/5= ERROR_FEC_SOLICITUD
0/MODULO_INTEGRACION/actualizarDatosAPEAI/MENSAJE_ERROR/6= ERROR_FEC_NACIMIENTO
0/MODULO_INTEGRACION/actualizarDatosAPEAI/MENSAJE_ERROR/7= ERROR_SEXO

1/MODULO_INTEGRACION/actualizarDatosAPEAI/MENSAJE_ERROR/1= ERROR_GENERICO
1/MODULO_INTEGRACION/actualizarDatosAPEAI/MENSAJE_ERROR/2= ERROR_CONEXIONBD
1/MODULO_INTEGRACION/actualizarDatosAPEAI/MENSAJE_ERROR/3= ERROR_DATOSEXPEDIENTE_TERCERO
1/MODULO_INTEGRACION/actualizarDatosAPEAI/MENSAJE_ERROR/4= ERROR_DATOSEXPEDIENTE_TERCERO_INCOMPLETO
1/MODULO_INTEGRACION/actualizarDatosAPEAI/MENSAJE_ERROR/5= ERROR_FEC_SOLICITUD
1/MODULO_INTEGRACION/actualizarDatosAPEAI/MENSAJE_ERROR/6= ERROR_FEC_NACIMIENTO
1/MODULO_INTEGRACION/actualizarDatosAPEAI/MENSAJE_ERROR/7= ERROR_SEXO

## Mensajes de ERROR

ERROR_GENERICO_1 = Ha ocurrido un error gen\u00e9rico
ERROR_CONEXIONBD_1 = No se ha podido obtener una conexi\u00f3n a la BBDD
ERROR_DATOSEXPEDIENTE_TERCERO_1 = Error al obtener datos del expediente y tercero
ERROR_DATOSEXPEDIENTE_TERCERO_INCOMPLETO_1=Datos del expediente y/o tercero incompletos
ERROR_FEC_SOLICITUD_1=Falta la Fecha de Solicitud
ERROR_FEC_NACIMIENTO_1=Falta la Fecha de nacimiento del interesado.
ERROR_SEXO_1=Falta el Sexo del interesado.

ERROR_GENERICO_4=Errore generiko bat gertatu da.
ERROR_CONEXIONBD_4=Ezin izan da datu-baseetarako konexiorik lortu
ERROR_DATOSEXPEDIENTE_TERCERO_4=Errorea espedientearen eta hirugarrenaren datuak eskuratzean
ERROR_DATOSEXPEDIENTE_TERCERO_INCOMPLETO_4=Espedientearen edo hirugarrenaren datuak osatu gabe daude
ERROR_FEC_SOLICITUD_4=Eskaera-data falta da
ERROR_FEC_NACIMIENTO_4=Interesdunaren jaioteguna falta da.
ERROR_SEXO_4=Interesdunaren sexua falta da.

###### C\u00f3digos de los campos suplementarios que necesita consultar y/o grabar y su tipo ######
## APEA
0/MODULO_INTEGRACION/MELANBIDE71/APEA/CAMPO_SUP/CODIGO/SUBV = IMPSUBVENCIONG
1/MODULO_INTEGRACION/MELANBIDE71/APEA/CAMPO_SUP/CODIGO/SUBV = IMPSUBVENCIONG
0/MODULO_INTEGRACION/MELANBIDE71/APEA/CAMPO_SUP/TIPO/SUBV = 1
1/MODULO_INTEGRACION/MELANBIDE71/APEA/CAMPO_SUP/TIPO/SUBV = 1

0/MODULO_INTEGRACION/MELANBIDE71/APEA/CAMPO_SUP/CODIGO/CS_EDAD = EDAD
1/MODULO_INTEGRACION/MELANBIDE71/APEA/CAMPO_SUP/CODIGO/CS_EDAD = EDAD
0/MODULO_INTEGRACION/MELANBIDE71/APEA/CAMPO_SUP/TIPO/CS_EDAD = 1
1/MODULO_INTEGRACION/MELANBIDE71/APEA/CAMPO_SUP/TIPO/CS_EDAD = 1

0/MODULO_INTEGRACION/MELANBIDE71/APEA/CAMPO_SUP/CODIGO/CS_SEXO = SEXO
1/MODULO_INTEGRACION/MELANBIDE71/APEA/CAMPO_SUP/CODIGO/CS_SEXO = SEXO
0/MODULO_INTEGRACION/MELANBIDE71/APEA/CAMPO_SUP/TIPO/CS_SEXO = 6
1/MODULO_INTEGRACION/MELANBIDE71/APEA/CAMPO_SUP/TIPO/CS_SEXO = 6

## APEAI
0/MODULO_INTEGRACION/MELANBIDE71/APEAI/CAMPO_SUP/CODIGO/SUBV = IMPSUBVENCIONG
0/MODULO_INTEGRACION/MELANBIDE71/APEAI/CAMPO_SUP/CODIGO/CS_EDAD = EDAD
0/MODULO_INTEGRACION/MELANBIDE71/APEAI/CAMPO_SUP/CODIGO/CS_SEXO = SEXO
0/MODULO_INTEGRACION/MELANBIDE71/APEAI/CAMPO_SUP/TIPO/SUBV = 1

1/MODULO_INTEGRACION/MELANBIDE71/APEAI/CAMPO_SUP/CODIGO/SUBV = IMPSUBVENCIONG
1/MODULO_INTEGRACION/MELANBIDE71/APEAI/CAMPO_SUP/CODIGO/CS_EDAD = EDAD
1/MODULO_INTEGRACION/MELANBIDE71/APEAI/CAMPO_SUP/CODIGO/CS_SEXO = SEXO
1/MODULO_INTEGRACION/MELANBIDE71/APEAI/CAMPO_SUP/TIPO/SUBV = 1