# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.

##################### OPERACIONES DISPONIBLES EN LA PESTA\u00d1A "CONF. SW" #####################
0/MODULO_INTEGRACION/MELANBIDE88/LISTA_OPERACIONES_DISPONIBLES=
1/MODULO_INTEGRACION/MELANBIDE88/LISTA_OPERACIONES_DISPONIBLES=

# NOMBRE DEL M\u00d3DULO QUE SE MUESTRA JUNTO CON EL NOMBRE DE LA OPERACI\u00d3N; A LA HORA DE SELECCIONAR UNA OPERACI\u00d3N QUE SE ASOCIAR\u00c1 A UN TR\u00c1MITE
# FORMATO: [COD_ORGANIZACION]/MODULO_INTEGRACION/[NOMBRE_MODULO]/NOMBRE_MODULO
0/MODULO_INTEGRACION/MELANBIDE88/NOMBRE_MODULO = MELANBIDE88
1/MODULO_INTEGRACION/MELANBIDE88/NOMBRE_MODULO = MELANBIDE88

##################### DESCRIPCI\u00d3N DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE88/DESCRIPCION_MODULO = M\u00d3DULO DE EXTENSI\u00d3N TRECO TRANSFORMACION ECOLOGICA Y DIGITAL EN MICROEMPRESAS
1/MODULO_INTEGRACION/MELANBIDE88/DESCRIPCION_MODULO = M\u00d3DULO DE EXTENSI\u00d3N TRECO TRANSFORMACION ECOLOGICA Y DIGITAL EN MICROEMPRESAS

##################### NOMBRE DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE88/TRECO/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = M88_DATOS_TRECO
1/MODULO_INTEGRACION/MELANBIDE88/TRECO/PANTALLA_EXPEDIENTE/NOMBRE_PANTALLAS = M88_DATOS_TRECO

##################### URL DE LAS PANTALLAS DEL M\u00d3DULO #####################
0/MODULO_INTEGRACION/MELANBIDE88/TRECO/URL_PANTALLA_EXPEDIENTE/M88_DATOS_TRECO = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE88&operacion=cargarPantallaDatosTreco&tipo=0
1/MODULO_INTEGRACION/MELANBIDE88/TRECO/URL_PANTALLA_EXPEDIENTE/M88_DATOS_TRECO = /PeticionModuloIntegracion.do?tarea=preparar&modulo=MELANBIDE88&operacion=cargarPantallaDatosTreco&tipo=0

##################### NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE #####################
0/MODULO_INTEGRACION/MELANBIDE88/TRECO/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/M88_DATOS_TRECO =
1/MODULO_INTEGRACION/MELANBIDE88/TRECO/PANTALLA_EXPEDIENTE/OPERACION_PROCESAR/M88_DATOS_TRECO =

##################### NOMBRE DE LA OPERACION DEL MODULO QUE SE ENCARGA DE ACTUALIZAR LOS DATOS DE LA PANTALLA DE EXPEDIENTE #####################
0/MODULO_INTEGRACION/MELANBIDE88/TRECO/ACTUALIZAR_PANTALLA_EXPEDIENTE/M88_DATOS_TRECO = 
1/MODULO_INTEGRACION/MELANBIDE88/TRECO/ACTUALIZAR_PANTALLA_EXPEDIENTE/M88_DATOS_TRECO = 

# NOMBRE DE LA OPERACION DEL M\u00d3DULO QUE SE ENCARGA DE PROCESAR LA PANTALLA DE EXPEDIENTE DE UNA RELACI\u00d3N ENTRE EXPEDIENTES
0/MODULO_INTEGRACION/MELANBIDE88/TRECO/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR=
1/MODULO_INTEGRACION/MELANBIDE88/TRECO/PANTALLA_EXPEDIENTE_RELACION/OPERACION_PROCESAR=

##################### NOMBRES DE TABLAS #####################


##################### NOMBRES DE SECUENCIAS #####################


##################### FICHEROS DE MENSAJES #####################
UBICACION_FICHEROS_MENSAJES = es.altia.flexia.integracion.moduloexterno.melanbide88.i18n.text
FICHEROS_MENSAJES = MELANBIDE88_TEXT_1;MELANBIDE88_TEXT_4


#######################CAMPOS CALCULADOS PARA PLANTILLAS###############################################
#El tipo_etiqueta nos indica el tipo de dato de la etiqueta (lo queremos para saber como formatear) (1->Entero, 2->String, 3-> Fecha, 4->Lista)

## DESA 11
0/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/ETIQUETAS=TRECO_ETIQUETA_MOTDENEGEUS;TRECO_ETIQUETA_MOTDENEG

#etiqueta MOTDENEGEUS, euskera
0/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEGEUS/TIPO_ETIQUETA=2
0/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEGEUS/NOMBRE_ETIQUETA=MOTDENEGEUS
0/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEGEUS/CODIGO_ETIQUETA=MOTDENEGEUS
0/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEGEUS/SQL_ETIQUETA=SELECT RTRIM (XMLAGG (XMLELEMENT (E,'- ' || DESCRIPCION || CHR(13) || CHR(13))).EXTRACT ('//text()').GETCLOBVAL(),',') AS REQUISITOS FROM e_tdet INNER JOIN plantilla_desclarga ON codigo = tdet_valor AND idioma ='eu' AND procedimiento = tdet_pro AND tipodesple='MDAT'
0/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEGEUS/SQL_NOMBRE_COLUMNA=REQUISITOS
0/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEGEUS/CLAUSULA_WHERE= WHERE tdet_num=
0/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEGEUS/CLAUSULA_WHERE/CAMPO=numeroExpediente
0/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEGEUS/CLAUSULA_AND3=AND tdet_pro='TRECO' AND tdet_cod LIKE 'MOTIVODENEGACION%' AND tdet_tra=11 AND tdet_ocu = (SELECT MAX(cro_ocu) FROM e_cro WHERE cro_tra = 11 AND cro_num=tdet_num)

#etiqueta MOTDENEG, castellano
0/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEG/TIPO_ETIQUETA=2
0/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEG/NOMBRE_ETIQUETA=MOTDENEG
0/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEG/CODIGO_ETIQUETA=MOTDENEG
0/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEG/SQL_ETIQUETA=SELECT RTRIM (XMLAGG (XMLELEMENT (E,'- ' || DESCRIPCION || CHR(13) || CHR(13))).EXTRACT ('//text()').GETCLOBVAL(),',') AS REQUISITOS FROM e_tdet INNER JOIN plantilla_desclarga ON codigo = tdet_valor AND idioma ='es' AND procedimiento = tdet_pro AND tipodesple='MDAT'
0/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEG/SQL_NOMBRE_COLUMNA=REQUISITOS
0/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEG/CLAUSULA_WHERE= WHERE tdet_num=
0/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEG/CLAUSULA_WHERE/CAMPO=numeroExpediente
0/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEG/CLAUSULA_AND3=AND tdet_pro='TRECO' AND tdet_cod LIKE 'MOTIVODENEGACION%' AND tdet_tra=11 AND tdet_ocu = (SELECT MAX(cro_ocu) FROM e_cro WHERE cro_tra = 11 AND cro_num=tdet_num)

## PRE y PRO 3
1/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/ETIQUETAS=TRECO_ETIQUETA_MOTDENEGEUS;TRECO_ETIQUETA_MOTDENEG

#etiqueta MOTDENEGEUS, euskera
1/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEGEUS/TIPO_ETIQUETA=2
1/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEGEUS/NOMBRE_ETIQUETA=MOTDENEGEUS
1/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEGEUS/CODIGO_ETIQUETA=MOTDENEGEUS
1/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEGEUS/SQL_ETIQUETA=SELECT RTRIM (XMLAGG (XMLELEMENT (E,'- ' || DESCRIPCION || CHR(13) || CHR(13))).EXTRACT ('//text()').GETCLOBVAL(),',') AS REQUISITOS FROM e_tdet INNER JOIN plantilla_desclarga ON codigo = tdet_valor AND idioma ='eu' AND procedimiento = tdet_pro AND tipodesple='MDAT'
1/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEGEUS/SQL_NOMBRE_COLUMNA=REQUISITOS
1/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEGEUS/CLAUSULA_WHERE= WHERE tdet_num=
1/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEGEUS/CLAUSULA_WHERE/CAMPO=numeroExpediente
1/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEGEUS/CLAUSULA_AND3=AND tdet_pro='TRECO' AND tdet_cod LIKE 'MOTIVODENEGACION%' AND tdet_tra=3 AND tdet_ocu = (SELECT MAX(cro_ocu) FROM e_cro WHERE cro_tra = 3 AND cro_num=tdet_num)

#etiqueta MOTDENEG, castellano
1/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEG/TIPO_ETIQUETA=2
1/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEG/NOMBRE_ETIQUETA=MOTDENEG
1/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEG/CODIGO_ETIQUETA=MOTDENEG
1/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEG/SQL_ETIQUETA=SELECT RTRIM (XMLAGG (XMLELEMENT (E,'- ' || DESCRIPCION || CHR(13) || CHR(13))).EXTRACT ('//text()').GETCLOBVAL(),',') AS REQUISITOS FROM e_tdet INNER JOIN plantilla_desclarga ON codigo = tdet_valor AND idioma ='es' AND procedimiento = tdet_pro AND tipodesple='MDAT'
1/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEG/SQL_NOMBRE_COLUMNA=REQUISITOS
1/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEG/CLAUSULA_WHERE= WHERE tdet_num=
1/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEG/CLAUSULA_WHERE/CAMPO=numeroExpediente
1/MODULO_INTEGRACION/MELANBIDE88/TRECO/PLANTILLA_NORMAL/TRECO_ETIQUETA_MOTDENEG/CLAUSULA_AND3=AND tdet_pro='TRECO' AND tdet_cod LIKE 'MOTIVODENEGACION%' AND tdet_tra=3 AND tdet_ocu = (SELECT MAX(cro_ocu) FROM e_cro WHERE cro_tra = 3 AND cro_num=tdet_num)



