# SE DA LA POSIBILIDAD AL USUARIO DE CARGAR VARIAS URLS. SI HAY M\u00C1S DE UNA SE DEBE
0/TRAMITACION_EXTERNA/PLUGIN_REGEXLAN_RGI/URLS_DISPONIBLES = ENLACE_1
0/TRAMITACION_EXTERNA/PLUGIN_REGEXLAN_RGI/ENLACE_1/URL = https://rlanbide.des.lanbide.lan/rgi/regexlanController.seam
#0/TRAMITACION_EXTERNA/PLUGIN_REGEXLAN_RGI/ENLACE_1/URL = http://pavdeslan.lanbide.lan:18003/rgi/regexlanController.seam

1/TRAMITACION_EXTERNA/PLUGIN_REGEXLAN_RGI/URLS_DISPONIBLES = ENLACE_1
1/TRAMITACION_EXTERNA/PLUGIN_REGEXLAN_RGI/ENLACE_1/URL = https://rlanbide.des.lanbide.lan/rgi/regexlanController.seam
#1/TRAMITACION_EXTERNA/PLUGIN_REGEXLAN_RGI/ENLACE_1/URL = http://pavdeslan.lanbide.lan:18003/rgi/regexlanController.seam


0/TRAMITACION_EXTERNA/PLUGIN_REGEXLAN_RGI/ENLACE_1/PARAMETROS = codOrganizacion;codUsuario;codTramite;ocurrenciaTramite;numExpediente;codProcedimiento;codUorTramitadora;tramiteAbierto;ejercicio;listaTramitesSiguientes;codigosTerceros;asientoRegistro;ejercicioRegistro;uorRegistro;codDepartamentoRegistro;tipoEntradaRegistro;uorVisibleRegistro;loginUsuario
0/TRAMITACION_EXTERNA/PLUGIN_REGEXLAN_RGI/ENLACE_1/METODOS    = getCodOrganizacion;getCodUsuario;getCodTramite;getOcurrenciaTramite;getNumExpediente;getCodProcedimiento;getCodUorTramitadora;isTramiteAbierto;getEjercicio;getListaTramitesSiguientes;getCodigoTerceroAlternativo;getAsientoRegistroInicioExpediente;getEjercicioAsientoRegistroInicioExpediente;getUorRegistro;getCodDepartamentoAsiento;getTipoEntradaAsiento;getUorVisibleRegistro;getLoginUsuario


1/TRAMITACION_EXTERNA/PLUGIN_REGEXLAN_RGI/ENLACE_1/PARAMETROS = codOrganizacion;codUsuario;codTramite;ocurrenciaTramite;numExpediente;codProcedimiento;codUorTramitadora;tramiteAbierto;ejercicio;listaTramitesSiguientes;codigosTerceros;asientoRegistro;ejercicioRegistro;uorRegistro;codDepartamentoRegistro;tipoEntradaRegistro;uorVisibleRegistro;loginUsuario
1/TRAMITACION_EXTERNA/PLUGIN_REGEXLAN_RGI/ENLACE_1/METODOS    = getCodOrganizacion;getCodUsuario;getCodTramite;getOcurrenciaTramite;getNumExpediente;getCodProcedimiento;getCodUorTramitadora;isTramiteAbierto;getEjercicio;getListaTramitesSiguientes;getCodigoTerceroAlternativo;getAsientoRegistroInicioExpediente;getEjercicioAsientoRegistroInicioExpediente;getUorRegistro;getCodDepartamentoAsiento;getTipoEntradaAsiento;getUorVisibleRegistro;getLoginUsuario




# INDICA CUALES SON LOS PAR\u00C1METROS DE CONFIGURACI\u00D3N DE LA VENTANA QUE SE ABRE PARA LA FICHA DE TRAMITACI\u00D3N EXTERNA
# FORMATO: [COD_ORGANIZACION]/TRAMITACION_EXTERNA/[NOMBRE_PLUGIN]/PARAMETROS_CONFIGURACION_VENTANA
#0/TRAMITACION_EXTERNA/PLUGIN_REGEXLAN_RGI/PARAMETROS_CONFIGURACION_VENTANA = 'width:980px,height:850px,resizable:yes,scrollbars:yes,toolbar:yes,status:yes,menubar:yes,location:yes'

0/TRAMITACION_EXTERNA/PLUGIN_REGEXLAN_RGI/PARAMETROS_CONFIGURACION_VENTANA = 'fullscreen=yes,toolbar=yes, location=yes, directories=no, status=no, menubar=yes, scrollbars=yes, resizable=yes, copyhistory=yes'

1/TRAMITACION_EXTERNA/PLUGIN_REGEXLAN_RGI/PARAMETROS_CONFIGURACION_VENTANA = 'fullscreen=yes,toolbar=yes, location=yes, directories=no, status=no, menubar=yes, scrollbars=yes, resizable=yes, copyhistory=yes'



0/TRAMITACION_EXTERNA/PLUGIN_REGEXLAN_RGI/BLOQUEO_FINALIZAR_TRAMITE = SI
0/TRAMITACION_EXTERNA/PLUGIN_REGEXLAN_RGI/BLOQUEO_RETROCESO_EXPEDIENTE = NO
1/TRAMITACION_EXTERNA/PLUGIN_REGEXLAN_RGI/BLOQUEO_FINALIZAR_TRAMITE = SI
1/TRAMITACION_EXTERNA/PLUGIN_REGEXLAN_RGI/BLOQUEO_RETROCESO_EXPEDIENTE = NO

# CONEXI\u00D3N
#0/TRAMITACION_EXTERNA/URL           = 
#0/TRAMITACION_EXTERNA/DRIVER        = oracle.jdbc.driver.OracleDriver
#0/TRAMITACION_EXTERNA/USUARIO       = flbpru
#0/TRAMITACION_EXTERNA/PASSWORD      = flbpru
0/TRAMITACION_EXTERNA/GENERICO	   = flbgen
1/TRAMITACION_EXTERNA/GENERICO     = flbgen
#0/TRAMITACION_EXTERNA/MAX_ACTIVE   = 70
#0/TRAMITACION_EXTERNA/MAX_WAIT     = 50
#0/TRAMITACION_EXTERNA/MAX_IDLE     = 2
#0/TRAMITACION_EXTERNA/MIN_IDLE     = 0
#0/TRAMITACION_EXTERNA/INITIAL_SIZE = 10
