
#DESARROLLO
SERVIDOR = flexia1

#PRE
#SERVIDOR = paprergi1_flexia1

#PRO
#SERVIDOR = pargi1_flexia1

TRAMITE_INCUMPLIMIENTO = 2
CODIGO_DOC_TRAMITE=4
COD_ORG=0
DOS_ENTORNOS=FALSE

#PROCEDIMIENTO DESARROLLO 0
#PROCEDIMIENTO_ID_DESARROLLO_CERO=LAN64_RECUR
PROCEDIMIENTO_ID_DESARROLLO_CERO=LAN62_LEAUK

