#LANBIDE/URL = https://212.55.11.59/rgi/services/RGIServices?wsdl
#LANBIDE/URL = https://rlanbideform.lanbide.net/rgi/services/RGIServices?wsdl
#LANBIDE/URL http://pavdeslan.lanbide.lan:7003/rgi/services/RGIServices?wsdl
#LANBIDE/URL = http://pavdeslan.lanbide.lan:7003/rgi/services/RGIServices?wsdl
#LANBIDE/URL = http://desarrollolanbide.indra.es:18003/rgi/services/RGIServices?wsdl
LANBIDE/URL = http://pavdeslan.lanbide.lan:18003/rgi/services/RGIServices?wsdl
### MENSAJES DE ERROR SEGÚ IDIOMA
ERR_PARAMETROS_INCORRECTOS_1 = Uno o mas parametros incorrectos
ERR_ACCESO_BASEDATOS_1 = Error de base de datos
ERR_EXPEDIENTE_REINTEGRO_1 = La entrada de registro a desasociar corresponde a un Reintegro
ERR_CONEXION_WS_1 = Error al conectarse al servicio web
ERR_URL_MAL_FORMADA_1 = URL de acceso al servicio web mal formada

ERR_PARAMETROS_INCORRECTOS_4 = Uno o mas parametros incorrectos
ERR_ACCESO_BASEDATOS_4 = Error de base de datos
ERR_EXPEDIENTE_REINTEGRO_4 = La entrada de registro a desasociar corresponde a un Reintegro
ERR_CONEXION_WS_4 = Error al conectarse al servicio web
ERR_URL_MAL_FORMADA_4 = URL de acceso al servicio web mal formada
